cortexproject/cortex

chunk_store.go
=> Store chunks in S3 in parallel

ring/ingester_lifecycle.go
Part of #19.  I don't believe this will fix the issue, but it won't hurt.
=> Avoid panics and nil map assignments in the ingester_lifecycle

user/id.go, vendor/github.com/prometheus/prometheus/storage/local/prism.go, vendor/manifest
Incorporates https://github.com/tomwilkie/prometheus/pull/82
Helps with #36.
=> Don't log chunk flushing

README.md
Thanks to @bboreham for the pointers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/53)
=> Readability changes from user feedback

cmd/prism/main.go, prism-build/Dockerfile, vendor/github.com/weaveworks/scope/common/middleware/logging.go, vendor/manifest
Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/54)
=> Don't log successful requests

chunk/chunk_cache.go
Missed in #66. Fixes #57.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/69)
=> Consistent namespace for memcache metrics

ingester/ingester.go, ingester/series.go
This code was copied over from Prometheus and we don't need all of it.
=> Clean up copied-over series code

chunk/chunk_cache.go, chunk/chunk_store.go, cmd/cortex/main.go
Based on findings from building better dashboards.
=> Tune histogram bucket sizes

cmd/cortex/main.go, ingester/ingester.go, ring/ring.go, server.go
Add `/ready` on the ingesters which returns 200 is everyone in the ring is healthy & active, and 500 otherwise.
Will wire this up in the k8s config later.
=> Add readiness probe

cortex-build/Dockerfile
Do not merge yet; going to use this to test the new readiness handlers.
=> Upgrade to go 1.7.3

chunk/chunk_store.go
To help with #11 
Will need post-merge review #97
=> Add metric for dynamo entries per chunk

ingester/ingester.go
Follow-up to #103, merged without review
=> Use LinearBuckets

ingester/ingester.go
Helps with https://github.com/weaveworks/monitoring/issues/12
=> Record chunk store error value in label

cmd/cortex/main.go
=> Instrument the base router so we don't miss endpoints.

cmd/cortex/main.go
Reverts weaveworks/cortex#134
I couldn't test locally  (issues), so I merged and it was wrong...
=> Revert "Instrument the base router so we don't miss endpoints."

cmd/cortex/main.go, ingester/ingester.go, ingester/ingester_test.go
=> Instead of flushing chunks that hit 1hr old, flush chunks that have been idle for one hour (or are full).

chunk/chunk.go, chunk/chunk_cache.go, chunk/chunk_store.go, chunk/chunk_store_test.go, chunk/chunk_test.go, ingester/ingester.go, vendor/github.com/docker/docker/pkg/ioutils/LICENSE, vendor/github.com/docker/docker/pkg/ioutils/buffer.go, vendor/github.com/docker/docker/pkg/ioutils/bytespipe.go, vendor/github.com/docker/docker/pkg/ioutils/fmt.go, vendor/github.com/docker/docker/pkg/ioutils/fswriters.go, vendor/github.com/docker/docker/pkg/ioutils/multireader.go, vendor/github.com/docker/docker/pkg/ioutils/readers.go, vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go, vendor/github.com/docker/docker/pkg/ioutils/temp_windows.go, vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go, vendor/github.com/docker/docker/pkg/ioutils/writers.go, vendor/github.com/docker/docker/pkg/longpath/LICENSE, vendor/github.com/docker/docker/pkg/longpath/longpath.go, vendor/github.com/docker/docker/vendor/golang.org/x/net/context/LICENSE, vendor/github.com/docker/docker/vendor/golang.org/x/net/context/context.go, vendor/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/cancelreq.go, vendor/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/cancelreq_go14.go, vendor/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go, vendor/manifest
Fixes #7 and lays ground work for #130
=> Write chunk metadata as header in chunks, not into index

ruler/ruler.go
Now that Prometheus exposes some methods on rules, use those. 
Still structurally the same. Differences:
* Don't write temp files to disk, instead parse & use directly
* Maintain control of when evaluation happens, rather than delegated to Manager (which we no longer use)
* Use a ticker rather than sleeping
Part of #4
=> Use exposed rules methods

querier/querier.go
=> Read ingesters and chunk store in parallel

cmd/cortex/main.go
Hopefully fixes #133 (again).
See #133 for discussion.
=> Use same buckets as authfe

ingester/ingester.go, util/priority_queue.go, util/priority_queue_test.go
=> Make priority queue public

chunk/chunk_store.go
- Use "Decorrelated Jitter" approach from https://www.awsarchitectureblog.com/2015/03/backoff.html
- Calculate batch size properly.
=> Flush optimisations

ring/http.go
One long line is just too hard to read.
=> Pretty-print JSON on /ring page

cmd/cortex/main.go, ring/ingester_lifecycle.go, ring/ingester_lifecycle_test.go, ring/mock_consul_client_test.go
Also, add a unit test for basic ring functionality (which failed without this fix).
Fixes #169
=> Only add new tokens to the ring, don't re-add all tokens.

chunk/chunk_store.go
As we're already passing in from/through to lookupChunks and it fits
conceptually in there, it should do the filtering already.
=> cleanup: move chunk filtering to lookupChunks

ring/http.go
So its stable across page refreshes.
=> Sort ring table by ingester ID

cmd/cortex/main.go
=> Add ingester flags for periodic tables

chunk/chunk_store.go, chunk/chunk_store_test.go
=> Fix distributor panic on empty, non-name matches

chunk/dynamodb_client.go
=> Propagate nil in dynamoRequestAdapter.NextPage()

cortex.proto, distributor/distributor.go, distributor/http_ingester_client.go, ingester/ingester.go, ingester/ingester_test.go, querier/querier.go, util/compat.go, util/compat_test.go
=> MetricsForLabelMatchers implementation

chunk/chunk_store.go, chunk/chunk_store_test.go, chunk/dynamodb_test.go
=> Don't use BETWEEN and next(), use BEGINS_WITH

chunk/dynamodb_client.go
=> Don't put empty write reqests list in the outgoing dynamodb write request map

ingester/series.go
=> Deal with chunk.Add() resulting in reencoding.

util/validate.go, util/validate_test.go
=> Validate samples (including metric name).

chunk/chunk_store.go, chunk/chunk_store_test.go, ingester/ingester.go, ingester/user_state.go, util/matchers.go
=> Fix empty-label query semantics

cmd/ruler/main.go, ruler/ruler.go
=> Start ruler server in constructor

distributor/distributor.go
Fixes #242 
/cc @juliusv I should have caught this in review, sorry.
How to design a language where is easy to make obvious mistakes 101.
=> Capture client connection as a parameters, because golang for loop suck.

ingester/ingester.go
=> Add flag to set chunk encoding

circle.yml
Doesn't seem to make a huge difference on circle (it does locally), but what the hell.
=> Parallelise test and lint in circle.

distributor/http_server.go, ingester/index.go, ingester/ingester.go, ingester/ingester_test.go, ingester/user_state.go, util/error.go
Fixes https://github.com/weaveworks/cortex/issues/47
=> Limit series per metric

chunk/dynamodb_client.go, chunk/dynamodb_client_test.go, chunk/storage_client_mock_test.go
=> Typo: don't write duplicate values to dynamodb

server/server.go
I considered only fudging around with the initialization/startup order
in ruler/main.go, but I think initializing the global tracer in `init()`
is clearer and less likely to be accidentally broken in the future.
Fixes https://github.com/weaveworks/cortex/issues/291
=> Fix data races in ruler

cmd/ruler/main.go, k8s/alertmanager-config.yaml, k8s/alertmanager-dep.yaml, k8s/alertmanager-svc.yaml, k8s/ruler-dep.yaml, ruler/ruler.go
=> Single-tenant static Alertmanager support

chunk/chunk.go, chunk/chunk_store.go, chunk/chunk_store_test.go, chunk/dynamodb_client.go, chunk/schema.go, chunk/schema_test.go, chunk/storage_client.go, chunk/storage_client_mock_test.go, util/math.go
=> Add chunk end time to range key

chunk/chunk_store.go, chunk/s3_client.go, chunk/s3_client_test.go
Not a big fix, but I wish it was there before. This will assure that potential user will not spend too much time to figure out the logic here.
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Documented s3 & DynamoDb URL flags a little bit more, added test case for awsConfig to show expected format.

alertmanager/multitenant.go, chunk/chunk_store.go, chunk/chunk_store_test.go, cmd/alertmanager/main.go, cmd/distributor/main.go, cmd/ingester/main.go, cmd/querier/main.go, cmd/ruler/main.go, cmd/table-manager/main.go, distributor/distributor.go, distributor/distributor_test.go, distributor/http_server.go, ingester/ingester.go, ingester/ingester_test.go, ingester/user_state.go, ruler/ruler.go, util/error.go, vendor/github.com/weaveworks/common/errors/error.go, vendor/github.com/weaveworks/common/httpgrpc/httpgrpc.go, vendor/github.com/weaveworks/common/instrument/instrument.go, vendor/github.com/weaveworks/common/middleware/grpc_auth.go, vendor/github.com/weaveworks/common/middleware/grpc_logging.go, vendor/github.com/weaveworks/common/middleware/http_auth.go, vendor/github.com/weaveworks/common/middleware/logging.go, vendor/github.com/weaveworks/common/server/server.go, vendor/github.com/weaveworks/common/signals/signals.go, vendor/github.com/weaveworks/common/user/grpc.go, vendor/github.com/weaveworks/common/user/http.go, vendor/github.com/weaveworks/common/user/id.go, vendor/manifest
See https://github.com/weaveworks/common/pull/22
Also pull in a more up to date common/server.
Still need to work out the new server shutdown logic for the ingester.
=> Update weaveworks/common, and harmonise user ID management.

cmd/configs/main.go, configs/api/api.go
=> Fix configs routes

chunk/dynamodb_client.go
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Removed not used metric 'dynamo_unprocessed_items_total'

ingester/ingester.go
Searched for other places like that mentioned in the ticket.
Changes:
- Ingester: Moved mentioned recordings after PUT and update only on success
Fixes issue https://github.com/weaveworks/cortex/issues/333
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> #333: Fixed places of wrong metric recording (e.g on error case)

chunk/chunk_store.go
=> Disallow queries where through < from.

chunk/chunk_cache.go, chunk/chunk_store.go, cmd/ingester/main.go, cmd/querier/main.go, cmd/ruler/main.go
Part of #209 
Also, when I flushed the cached due to previous bugs, we started trying to write 2.5k chunks to the cache in parallel.  This change limits the parallelism with which we write to the cache.
=> Write-back to memcache in the background, don't block the query.

distributor/http_server.go
Fixes https://github.com/weaveworks/cortex/issues/314
=> Return 429 (not 507) for exceeded cardinality

ingester/ingester_lifecycle.go
And rejig the timeouts so we wait the right amount of time (and don't check, sleep, fail).
Fixes #353
=> Don't fatal when we fail to find an ingester to transfer to

ring/http.go
Addresses part of https://github.com/weaveworks/service/issues/1156
=> Use CSRF token in cortex ring admin

ingester/ingester_lifecycle.go
I haven't done any testing. Not sure how to write an automated one that isn't a Change Detector test.
=> Flush even if transfer fails

chunk/chunk_store.go, chunk/chunk_store_test.go, chunk/storage_client.go, chunk/table_manager.go, chunk/table_manager_test.go, cmd/ingester/main.go, cmd/querier/main.go, cmd/ruler/main.go, cmd/table-manager/main.go
=> Remove deprecated ability to set DynamoDB table name via URL

alertmanager/multitenant.go
This avoids the situations where a half-initialized AM instance hangs around, but it actually panics in the web handler when the user wants to look at the UI.
=> Only register new AM if the initial config applies

chunk/aws_storage_client.go, chunk/aws_storage_client_test.go
We should only wrap the error if its non-nil.
Plus, add a test so this doesn't happen again.
=> Fix all queries returning "QueryPages error: table=cortex_weekly_2465, err=\u003cnil\u003e"

ring/consul_client.go
=> Add a default consul http timeout of 2*long poll duration - ie 20s

ingester/ingester_lifecycle.go
=> Continue to heartbeat to consul whilst flushing / transferring.

cortex.proto, querier/querier.go
/cc @juliusv 
See prometheus/prometheus#2588
=> Return multiple read responses as per prometheus/prometheus#2588

alertmanager/multitenant.go, cmd/alertmanager/main.go, ring/http.go
@bboreham pointed me at the status information for mesh. This has already proved useful in debugging #334, so I figure we might as well get it into master now.
=> Mesh status page

chunk/aws_storage_client.go, chunk/aws_storage_client_test.go, chunk/inmemory_storage_client.go, chunk/schema.go
=> Revert "Filter equality matchers on the dynamo side"

pkg/configs/api/api.go, pkg/configs/api/api_test.go, pkg/configs/api/helpers_test.go
@jml You already approved this in https://github.com/weaveworks/cortex/pull/405, but then that PR needed a rebase, and I did it from the wrong machine where that branch was empty and thus GitHub closed the PR because it ended up having 0 commits and counted as already merged. Here it is again :)
=> Validate Alertmanager config upon setting it

pkg/ingester/ingester.go
=> More aggressively flush idle chunks

pkg/chunk/aws_storage_client.go, pkg/chunk/aws_storage_client_test.go
Fixes #431
- Made the mock honour AttributesToGet in change #1, tickling the issue.
- change #2 asks for the right attributes to get, fixing the issue.
=> Fix "Error: Got response from DynamoDB with no hash key"

pkg/ingester/ingester.go, pkg/ingester/ingester_flush.go, pkg/ingester/ingester_lifecycle.go, pkg/ingester/ingester_lifecycle_test.go
=> Ingesters must flush chunks then remove themselves from consul!

README.md
=> Update README install instructions to add k8s 1.6 support

build-image/Dockerfile
Minor security improvement following #434.
I've just done it for Net, so thought I might as well do it for Cortex.
=> Checksum shfmt for increased security

pkg/chunk/aws_storage_client.go, pkg/chunk/aws_storage_client_test.go, pkg/chunk/dynamodb_table_client.go
Also, use dynamodb's constants where we can.
=> Backoff and retry throttled requests in the table manager.

pkg/ingester/ingester_claim.go, pkg/ingester/ingester_lifecycle.go, pkg/util/priority_queue.go
=> Don't flush chunks after a successful transfer

pkg/chunk/aws_storage_client.go
Should help in identifying capacity usage.
=> Add more information to dynamo metrics

k8s/configs-db-dep.yaml, k8s/configs-db-svc.yaml, k8s/configs-dep.yaml, k8s/configs-svc.yaml, k8s/table-manager-svc.yaml
Create missing k8s config.
Fixes #470
=> Create configs and configs-db k8s config

README.md
=> Update README.md for new Prometheus config file format.

pkg/chunk/aws_storage_client.go
We see a number of non-fatal errors when talking to dynamodb which we could do a better job of retrying.
The AWS SDK does a good job of [flagging retryable requests](https://github.com/aws/aws-sdk-go/blob/master/aws/corehandlers/handlers.go#L177); this hooks our retry loop into that.
=> Retry 'Retryable' requests to dynamoDB

pkg/chunk/aws_storage_client.go
=> Revert "Retry 'Retryable' requests to dynamoDB"

pkg/chunk/schema_config.go, pkg/chunk/table_manager.go
Follow up to #485 that probably works.
=> Tags for legacy tables too

pkg/chunk/aws_storage_client.go, pkg/chunk/aws_storage_client_test.go
Second try at #480 (reverted in #481).
Currently the aws_storage_client tests panic because the mocking is no longer right.
Fixing it isn't simple because `Batch*Request` returns a concrete type, which makes it difficult to mock.
Options are:
- Disable the test 🙈 
- Find a way to shoehorn the mock through golang's type system
- Rework the retry logic to use a Retryer type, but somehow preserve our metrics
- ..?
Any suggestions welcome! :)
=> Second attempt at Retry 'Retryable' requests to dynamoDB

pkg/chunk/chunk_store.go
=> Asynchronously write chunks to the cache from the ingester.

Makefile, circle.yml, push-images
Before you merge this PR, you'll need to set the Circle CI env var `IMAGE_PREFIX=quay.io/weaveworks/cortex-`.
Otherwise everything else should just work.
=> Allow pushing images from a fork

pkg/alertmanager/multitenant.go, pkg/configs/client/configs.go, pkg/ruler/scheduler.go
We fixed a bug in #492, but this change aims to prevent the same bug from happening again.
=> Reduce gotcha potential of GetLatestConfigID

cmd/lite/main.go
Include the ruler in cortex lite as it relies on the ingesters, ring etc and would be useful for local development.
Only start the ruler if the ruler configs url is provided, as not everyone will want to run the ruler scheduler and workers in cortex lite.
Test plan:
```
~/g/s/g/w/cortex ❯❯❯ kubectl logs --namespace cortex lite-3798408835-rbkwx | grep ruler
time="2017-07-13T12:16:53Z" level=info msg="Ruler up and running" source="ruler.go:309"
time="2017-07-13T12:16:53Z" level=debug msg="Waiting for next work item" source="ruler.go:352"```
=> Include ruler in cortex lite if configured

pkg/ruler/ruler.go
I believe the old comment was out of date.
=> Update comment to reflect support for alerts

pkg/ingester/user_state.go
Gives us a fighting chance at helping end user, and maybe helps end user too.
Haven't tested yet.
=> Log which metric has too many series

pkg/chunk/aws_storage_client.go, pkg/chunk/aws_storage_client_test.go
Fixes part of #516 - continue would skip pages instead of backing off.
Also include maxRetries in the QueryPages retry logic.
=> Fix AWS QueryPages backoff logic

pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go
To fix #472
Grafana queries for current month/year would mostly fail due to
weekly tables not existing into future.
Fix is to detect when end of time range is future and quietly change to now
=> Quietly truncate queries ranging into future

pkg/chunk/chunk_cache.go, pkg/chunk/gcp/instrumentation.go, pkg/chunk/gcp/storage_client.go
=> Fetch chunks from bigtable in batches of 100

pkg/chunk/aws_storage_client.go
We've been getting a number of "maxRetries exceeded", which is frustrating when you can't figure out why.
This change prints out all errors apart from `ProvisionedThroughputExceeded`, on the grounds we expect lots of those.  And it always includes the last error if we get as far as "maxRetries exceeded".
=> Expose more information about retried DynamoDB errors

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ring/http.go, pkg/ring/ring.go
=> Extract function to decide if an ingester is healthy

pkg/ruler/ruler.go
Since I spent three hours hunting this down
=> Add a check for format of SRV lookup string

pkg/ring/consul_client.go
Prior to this change, I would see about 100 repeats of this in the logs when first running `lite`:
```
time="2017-09-11T11:03:26Z" level=debug msg="Get ring (0)" source="consul_client_mock.go:97" 
time="2017-09-11T11:03:26Z" level=debug msg="Get ring - not found" source="consul_client_mock.go:104" 
time="2017-09-11T11:03:26Z" level=debug msg="Get ring (0)" source="consul_client_mock.go:97" 
time="2017-09-11T11:03:26Z" level=debug msg="Get ring - not found" source="consul_client_mock.go:104" 
time="2017-09-11T11:03:26Z" level=debug msg="Get ring (0)" source="consul_client_mock.go:97" 
...
```
The real Consul API behaves the same - key not found returns `nil` and no error.  Since we don't really want to "watch" an empty value, I think treating it the same as an error and going round the …
=> In WatchKey(), back-off when value not found

Gopkg.lock, Gopkg.toml, cmd/alertmanager/main.go, cmd/configs/main.go, cmd/distributor/main.go, cmd/ingester/main.go, cmd/lite/main.go, cmd/querier/main.go, cmd/ruler/main.go, cmd/table-manager/main.go, vendor/github.com/weaveworks/promrus/README.md, vendor/github.com/weaveworks/promrus/promrus.go, vendor/github.com/weaveworks/promrus/promrus_test.go
Less verbose and DRY-er hook creation, as suggested in #572.
=> Simplify promrus setup by using MustNewPrometheusHook

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
=> Allow the rejection of old samples

pkg/alertmanager/multitenant.go
When the config for an instance is unusable (generally because it is blank), allow the alertmanager to be configured with a fallback.
We also allow the instance-id to be encoded in the Slack URL, triggered by a magic value, because multitenant.
This addresses #529, in that you no longer get a continuous stream of errors about having no valid config.
=> Fallback configuration for alertmanager

pkg/chunk/gcp/instrumentation.go
=> Update bigtable latency histogram buckets to reflect reality.

pkg/ruler/scheduler.go
I find it very hard to debug a wall of meaningless hex.
Instead:
* Make work items readable instead of hex strings
* Print out when rules config changes
Old:
```
time="2017-11-10T15:10:35Z" level=debug msg="Scheduler: work item added: {1 [0xc420015090] {63645923435 10244791 0x30f1ba0}}" source="scheduler.go:202" 
time="2017-11-10T15:10:35Z" level=debug msg="Scheduler: work item granted: {1 [0xc420015090] {63645923435 10244791 0x30f1ba0}}" source="scheduler.go:219" 
time="2017-11-10T15:10:35Z" level=debug msg="Processing &{1 [0xc420015090] {63645923435 10244791 0x30f1ba0}}" source="ruler.go:361" 
```
New:
```
time="2017-11-10T15:22:56Z" level=info msg="Scheduler: updating rules for 1: len=1" source="scheduler.go:198" 
time="2017-11-10T15:22:56Z" level=debug msg="Scheduler: work item added: …
```
=> Slightly more useful ruler logs

pkg/configs/api/api.go, pkg/configs/api/api_test.go
=> Check that rules files parse, in setConfig

pkg/chunk/chunk.go
For performance: we avoid parsing the JSON for each subsequent chunk in the same timeseries.
`Metric` is the set of label=value pairs for a timeseries. 
`Fingerprint` is a 64-bit hash of the `Metric` and we already assume that chunks with the same `Fingerprint` must have the same `Metric`.
This PR is based off #633 to get the `DecodeContext` - please comment on earlier commits there.
Fixes #630 
Part of #624 
Benchmarks - before (after #633):
```
BenchmarkDecode1-2       	  200000	    113408 ns/op	  155772 B/op	     117 allocs/op
BenchmarkDecode100-2     	    3000	   4202005 ns/op	  967774 B/op	   11335 allocs/op
BenchmarkDecode10000-2   	      30	 378176958 ns/op	82100856 B/op	 1133154 allocs/op
```
after:
```
BenchmarkDecode1-2       	   10000	    119247 ns/op	  159455 B/op	     127 …
```
=> Re-use Metric when decoding chunks with the same Fingerprint

pkg/chunk/aws_storage_client.go, pkg/chunk/chunk.go, pkg/chunk/chunk_cache.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_test.go
This fills in a few blank spots in #624.
=> More OpenTracing calls in chunk handling

pkg/chunk/chunk.go
Because it allocates enormous buffers, and therefore drives GC to run more often, `snappy.NewWriter()` is a massive drag on performance.
Benchmarks: before:
```
BenchmarkEncode-2   	   30000	     37264 ns/op	   85127 B/op	      27 allocs/op
```
after:
```
BenchmarkEncode-2   	  200000	      5744 ns/op	    3091 B/op	      25 allocs/op
```
I hadn't particularly profiled the write path, since it's asynch and easily scaleable, but this is too good to miss.
@tomwilkie I wonder if you could review before I give my Go performance talk tomorrow 🙂
=> Re-use snappy writers via pool, for performance

pkg/ruler/ruler.go
This is a RED metric for how overloaded the ruler is.
`blocked_workers` can serve as a USE metric, but a bit hit-and-miss if you're trying to alert on it.
=> Add a histogram measuring lateness of rule evaluation

pkg/chunk/gcp/storage_client.go
Trace the time querying the table index.
Matching the dynamoDB tracing.
=> Add tracing the the gcp QueryPages

pkg/chunk/table_manager.go
Quick one, noticed this wasn't being registered.
=> Don't forget to register syncTableDuration

cmd/distributor/main.go, cmd/lite/main.go, cmd/querier/main.go, cmd/ruler/main.go
=> Revert "Enable configurable Jaeger sampling strategies (with defaults)"

pkg/chunk/cache/cache.go
=> Register cache background flags

Makefile
And document the usage of both `$(TTY)` and `$(RM)`.
It's worth noting that taking advantage of this change via `make all TTY=` will yield un-cancel-able GCB builds, if you're into that sort of thing.
=> Make TTY optional to enable GCB builds

pkg/ruler/scheduler.go
This got put down to Debug in #719, and I missed it on review.
=> Restore logging of rules updates

pkg/chunk/aws/dynamodb_table_client.go
=> Register DynamoDB auto-scaling metric

pkg/util/log.go
Fixes #666 
Matching PR https://github.com/weaveworks/promrus/pull/9
=> Use pre-existing metric for log messages

pkg/ingester/ingester_flush.go
This is in the context that, looking at a dashboard, we can see that the flush queue suddenly jumped by several million, but we cannot tell why.
Event logging (#755) helps to see which user, series, etc., but I find I want the specific reason for each series.
=> Collect the reason why we decided to flush a series

pkg/chunk/cassandra/storage_client.go
Bit of an oversight from the original PR.
Alternatively I can make this a repeated flag (with common/mflagext), but thats mflag so a bit of a pain.
=> Comma-separated addresses for Cassandra.

pkg/util/events.go
=> Increment sample counter atomically

pkg/chunk/aws/dynamodb_table_client.go
Fixes #803 - check pointers are non-nil before following
I tried to apply a consistent rule in the file that an error causes an early exit; no error means we assume the return is non-nil, but any sub-parts of the return data accessed via a pointer have to be checked.
=> Check pointers are non-nil before following, in table manager DynamoDB code

.circleci/config.yml
Fixes #805
Sorry about that @bboreham!
=> Only deploy off master branch.

pkg/chunk/aws/storage_client.go
=> DynamoDB: use eventual-consistency reads for chunks

pkg/distributor/billing.go
Turns out we lost this somewhere!
=> Register billing metrics

pkg/chunk/aws/storage_client.go
You can eyeball it from the hash key, but much easier to do statistical analysis if the field is provided separately
=> Add UserID to event for AWS retry

pkg/configs/db/db.go
Allow RDS credentials from mounted secret.
=> Add --database.password-file option to configs

pkg/chunk/cassandra/storage_client.go
This PR adds a few extra config settings for connecting to a Cassandra cluster to allow SSL and authentication.
The DisableInitialHostLookup driver option is also exposed which is needed when connecting to some managed Cassandra services, like Azure Cosmos DB. These Cassandra services don't expose
the internal cluster topology, so we need to disable initial host lookup and just send requests to the configured cluster address.
=> add new config options for connecting to cassandra

pkg/ingester/series.go
=> Register forgotten metric 'createdChunks'

cmd/ingester/main.go, cmd/lite/main.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/lifecycle_test.go
=> Reject samples from too far into the future

pkg/alertmanager/multitenant.go
Need this for https://github.com/weaveworks/service/issues/2132
=> notification: add webhook for notifications

pkg/ingester/ingester.go, pkg/ingester/user_state.go
I made some bigger changes to add tracing to ingest, but I am not sure the complicating the hot path is worth it. I'll make a separate PR for that.
=> New metrics to track the series churn

pkg/chunk/chunk_store.go
=> Don't forget to Finish spans.

cmd/distributor/main.go, cmd/lite/main.go, cmd/querier/main.go, cmd/ruler/main.go
Was previously done by the distributor, but thats moved over to global metrics now.
=> Register ring metrics.

cmd/distributor/main.go, cmd/ingester/main.go, pkg/chunk/gcp/instrumentation.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/http_server.go, pkg/ingester/client/client.go, pkg/ingester/client/client_test.go, pkg/ingester/client/compat.go, pkg/ingester/client/cortex.proto, pkg/ingester/client/timeseries.go, pkg/util/middleware/grpc.go
Reduce CPU usage by about 25% for the distributor.
Still looks like mostly GC-related CPU usage, so hopefully more to come.
=> Minor distributor optimisations

pkg/ingester/ingester_test.go
I really ought to have added this to the test in the original PR!
=> Assert ingester validation errors report 400s in test

README.md
This key feature of Cortex was not emphasised in the README.
=> Say 'multi-tenant' three more times

pkg/ingester/lifecycle_test.go
Should speed up the tests a little.
=> TransferTest doesn't need to wait this long.

pkg/ingester/flush.go
=> Ensure flush metrics are registered

docs/arguments.md
If you spot any typos,  feel free to correct and push straight to this branch.
=> Document how the limits and overrides work.

pkg/ingester/lifecycle_test.go
#936 was pretty wrong; this change reduces run time for the test correctly.
=> Fix lifecycle introduced by #936

pkg/chunk/series_store.go, pkg/ingester/ingester.go
To help with query performance improvements.
=> Add some per-query histograms to the chunk store.

pkg/chunk/cache/cache.go, pkg/chunk/cache/cache_test.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/chunk_store_utils.go, pkg/chunk/series_store.go
=> Parallelise the decoding of chunks coming from the cache.

pkg/ring/http.go, pkg/ring/lifecycler.go, pkg/ring/ring.go
* Also make sure the percentage is exposed for ingesters
that are not having any tokens
=> Expose the number of tokens owned by an ingester

Gopkg.lock, cmd/querier/main.go, vendor/github.com/weaveworks/common/server/server.go
Fixes #949.
~Needs https://github.com/weaveworks/common/pull/118 to be merged first.~
=> Use HTTP server for request from query frontend.

Makefile
Was left over from the mistakes in #910.
=> Remove vendored proto from Makefile.

.circleci/config.yml, Makefile, build-image/Dockerfile
This should prevent us from accidentally commiting changes to vendor again.
Fixes #992
=> Add `dep check` phase to CI.

pkg/distributor/distributor.go
Previously it was allowing one to fail, which would give the wrong answer since we divide by replication factor.
If `-distributor.extra-query-delay` is set, it might not even call the last one.
=> Ensure we call UserStats() on all ingesters

README.md
Add a note about DCO in the README.
When this is approved I will turn the DCO bot back on and close #1021
=> Add a note about signing off in the README

docs/dashboards/bigtable.libsonnet, pkg/chunk/gcp/storage_client.go, pkg/chunk/util/util.go
One word, no space, no inner capital.
=> Fix capitalization of Bigtable. [skip ci]

pkg/chunk/series_store.go
=> Small log & comment improvements in series_store.go

pkg/chunk/chunk.go
otherwise the error can be very frustrating
=> Include the chunk ID that caused an error

pkg/chunk/chunk_store.go
Now that `QueryPages()` runs across multiple goroutines, the callback can be running in parallel so we need to lock round the single data structure it is accessing.
Absence of any protection causes queries to return different results, randomly.
=> Lock round access to query results

pkg/util/extract/extract.go
`Metric` is implemented as a `map`; use this knowledge.
=> Small optimisation in chunk indexing

pkg/distributor/query.go, pkg/querier/ingester_streaming_queryable.go
(From #1043, separated out as these are more straight forward).
=> Reduce some allocations on the query path.

pkg/querier/frontend/query_range.go
Signed-off-by: Elena Morozova <lelenanam@gmail.com>
=> Add error check for unmarshal in querier

build-image/Dockerfile
See: golang/lint#415
Signed-off-by: Graham Rounds <graham@platform9.com>
=> update golint path

pkg/distributor/http_admin.go
=> Add API & Rule ingestion rates to user stats page

pkg/querier/frontend/frontend.go
=> frontend: propagate errors returned by queriers

pkg/chunk/storage/caching_storage_client.go, pkg/chunk/storage/caching_storage_client_test.go
=> Make sure we cache empty results in the index cache.

pkg/chunk/storage/caching_storage_client_test.go
Guessing this was a result of a merger.
=> Fix test that was failing to compile

pkg/querier/frontend/frontend.go, pkg/querier/frontend/results_cache.go
We were seeing huge latencies and these are two high-probability candidates. Tracing them should help us narrow down on root cause.
=> Add spans for queuing and unmarshalling

pkg/chunk/aws/metrics_autoscaling.go
=> Don't do metrics autoscaling unless enabled on table

pkg/chunk/schema_config.go, pkg/chunk/table_manager.go
=> more table-manager fixes

MAINTAINERS
Switching away from FreshTracks related stuff. 
=> Use personal emails for FreshTracks maintainers

docs/architecture.md
@tomwilkie Okay, I'm realizing now that we had parallel efforts underway. I'm thinking perhaps you could merge your PR and I could swoop in and smooth it over?
=> Update architecture docs

pkg/chunk/schema_config.go
=> Only override store type for aws.

pkg/chunk/storage/factory.go
=> Don't wrap the storage in a cache twice.

pkg/ingester/ingester.go, pkg/ingester/user_state.go
=> Add some spans to the query path of the ingester.

k8s/nginx-config.yaml, k8s/querier-dep.yaml, k8s/query-frontend-dep.yaml, k8s/query-frontend-svc.yaml
Signed-off-by: Nazar Boyko <blackvorik@gmail.com>
=> added query-frontend k8s manifests

push-images
Correct `quey` to `quay`
Nothing Major :)
=> Fix typo in push-images script

pkg/ring/lifecycler.go, pkg/util/net.go
=> Don't fail if first interface doesn't have any addresses.

pkg/chunk/encoding/chunk.go, pkg/chunk/encoding/factory.go
=> Allow people importing cortex to add their own chunk formats.

pkg/ingester/flush.go
I would like to understand which users chew up the most storage.
=> Add ingester metric for chunk storage per user

pkg/ingester/lifecycle_test.go, pkg/ring/lifecycler.go
This is to ensure we can set it to 0 in single node mode
=> Make minReadyDuration configurable

pkg/chunk/aws/dynamodb_table_client.go, pkg/chunk/local/boltdb_table_client.go
After merging #1133 , the master branch was broken due to the small changes below missing. We should review the PR merge tasks to make sure that when the head of master changes, existing PRs get re-run to make sure they are not hiding subtle breaks.
=> Minor, yet breaking tweaks that were missed in the merging of #1133

.gitignore
File name changed, need to update gitignore.
=> gitignore: s/caching_storage_client.pb.go/caching_index_client.pb.go/

pkg/ingester/flush.go
Or if `Enqueue()` returns false which means the series was already queued.
The `NoFlush` case was just counting how many series got scanned and not flushed, which is not very interesting.
=> Don't bump flush metric in 'noFlush' case

pkg/ingester/flush.go
Since with object storage, the create operation is going to cost
significant $$$, we need to measure the number of creates also.
CHANGE
metric name: `cortex_ingester_chunk_bytes_total` --> `cortex_ingester_chunk_bytes_stored_total`
=> Count the chunks stored per user.

pkg/chunk/aws/dynamodb_storage_client.go
In most cases the spans for `query()` are one-for-one with the spans for `DynamoDB.QueryPages()`, and when there are thousands of small queries this just makes traces larger and harder to read.
To distinguish the case where a query has multiple pages from the case where one page is retried, I added tags with the page number and retry count.
=> Remove tracing span for dynamoDB query

pkg/chunk/aws/dynamodb_storage_client.go
=> Pull span from the correct context, in dynamoDB.queryPage()

pkg/querier/remote_read.go, pkg/querier/remote_read_test.go
=> Pass start and end of the query to the Querier during remote read requests

pkg/ingester/flush.go
This is to give a parent for spans created by lower levels such as the index write cache and chunk store.
=> Add a span for flushUserSeries()

pkg/chunk/encoding/bigchunk.go
Instead of three parallel slices, use a slice of structs.
Saves 2x24-byte slice headers per `bigchunk`, and some GC overhead.
also `UnmarshalFromBuf()` becomes more efficient because it was only pre-sizing one of the three slices.
=> More efficient memory layout of bigchunk chunks

pkg/querier/frontend/frontend.go
=> Ensure queries are correctly cancelled when the user goes away.

pkg/distributor/distributor_test.go, pkg/util/validation/limits.go, pkg/util/validation/override.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
=> Make enforcement of the presence of metic name on pushes optional.

pkg/chunk/encoding/bigchunk.go
The `Chunk` indirection doubles the pointer size for every sub-chunk, which we don't need because there is only one kind of Chunk.
Note this will clash with #1216 but I wanted to separate the ideas.  Can rebase or merge the PRs if appropriate.
=> Strip Chunk interface indirection on bigchunk sub-chunks

pkg/distributor/distributor.go, pkg/ring/batch.go
Mainly as I want to reuse it in Loki.  But I also like the refactoring and separation of concerns, makes it easier to see whats going on IMO.
=> Factor out the batch write logic from the distributor to the ring package.

pkg/chunk/encoding/varbit_helpers.go
"returs" to "returns" in line 41.
=> Fix typo in comment

pkg/chunk/storage/caching_index_client.go
And make the metric count the number of gets correctly so you can calculate hit rate.
=> Add some more logging to the index cache, 

pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/gcp/fixtures.go, pkg/chunk/gcp/fnv.go, pkg/chunk/storage/factory.go
=> Optionally prepend a hash of row key to improve distribution.

pkg/chunk/table_manager.go
Schema transitions can happen on any day; table transitions happen weekly.  When they don't align, the table manager will try and create table twice.
This PR fixes the logic to handle these duplicates.
=> Handle schema transition which don't align to periodic table transistions.

pkg/chunk/gcp/table_client.go
Check to see if the Column family already exists in bigtable and not return an error if it does.
Fixes #1249 
=> Bigtable fix family already exists error

pkg/chunk/chunk_store.go
Queries within the ingester retention time are satisfied without going to the chunk store, so we shouldn't reject ones that the chunk store can't implement.
In practical terms, move the "query must contain metric name" check after the time checks, so that we may return with `shortcut=true` even on those queries.  The ingester query code is ok with queries that don't have a metric name.
Partial fix for #416
=> Don't block queries with no metric name if no-op

build-image/Dockerfile
Depends on https://github.com/cortexproject/cortex/pull/1206
=> Bump to go 1.12

README.md
Minor documentation improvements.
=> docs: minor improvements in the Cortex README

pkg/chunk/encoding/bigchunk.go
Currently we always copy the last chunk, even though it could be exactly the right size (e.g. after an ingester handover).  Change to copy only if the block is at least 32 bytes bigger than required.
(arbitrary choice - these blocks are usually in the low hundreds of bytes)
=> Reduce the amount of copying we do when adding to bigchunk

.circleci/config.yml, Makefile, cmd/lite/main.go, cmd/querier/main.go, pkg/chunk/aws/aws_autoscaling.go, pkg/chunk/cache/cache_test.go, pkg/chunk/chunk_store_test.go, pkg/chunk/chunk_test.go, pkg/chunk/fixtures.go, pkg/chunk/schema_test.go, pkg/chunk/schema_util_test.go, pkg/chunk/testutils/testutils.go, pkg/querier/frontend/query_range_test.go, pkg/querier/frontend/results_cache_test.go, pkg/querier/querier_test.go, pkg/querier/series_set_test.go, tools/lint
=> Update CI image to reference go 1.12 build image

pkg/ingester/user_state_test.go
=> Test more combination of batch size and num series.

cmd/alertmanager/main.go, cmd/configs/main.go, cmd/table-manager/main.go
Table-manager, alert-manager and configs.
=> Add tracing initialization to programs that lacked it

cmd/query-frontend/main.go, pkg/chunk/chunk_store.go, pkg/querier/frontend/frontend.go, pkg/querier/frontend/frontend_test.go, pkg/querier/frontend/query_range.go, pkg/querier/frontend/results_cache.go, pkg/querier/frontend/results_cache_test.go, pkg/querier/frontend/roundtrip.go, pkg/querier/frontend/roundtrip_test.go, pkg/querier/frontend/split_by_day.go, pkg/querier/frontend/split_by_day_test.go, pkg/util/validation/limits.go, pkg/util/validation/override.go, pkg/util/validation/validate.go
=> Limit number of days a query can be split into.

pkg/chunk/series_store.go
~We're not loading the chunks in the initial queries, instead just
figuring out which series have to be loaded. I don't think it makes
sense to enforce cardinality limits on queries that return seriesIDs
which will be intersected away.~
~Here, I made the changes to make sure only the final intersected result
is used for the cardinality limits. As only these chunks are loaded, I
think we should be good just checking the cardinality limits here.~
EDIT: Documented the logic behind cardinality limits.
=> Document the logic behind cardinality limits.

pkg/chunk/schema_config.go
Reading through this code I found it confusing that we had `tableForBucket()` and `TableFor()`, plus one more line that did the same thing with an outdated comment.
=> Refactor: do table names in just one place

pkg/chunk/chunk.go
One day I had some corrupted data and couldn't figure out what the problem was.
=> Wrap chunk errors to provide context when something breaks

pkg/util/flagext/url.go
=> Re-use Set() method in URLValue.UnmarshalYAML()

pkg/chunk/gcp/instrumentation.go
=> minor: Better buckets for GCS latency

pkg/chunk/chunk_store.go, pkg/chunk/series_store.go
This is shorter, more efficient, and less surprising.
=> Take UserID from chunk instead of context

pkg/ruler/scheduler.go
Found this can be simplified while reviewing https://github.com/cortexproject/cortex/pull/1258
=> Simplify logic by outdenting logic.

pkg/chunk/cache/background.go, pkg/chunk/cache/cache.go, pkg/chunk/cache/diskcache.go, pkg/chunk/cache/fifo_cache.go, pkg/chunk/cache/memcached.go, pkg/chunk/cache/memcached_client.go, pkg/chunk/chunk_store.go, pkg/chunk/storage/factory.go
Allow setting the fields of the cache config via YAML.
=> Expose the cache config as YAML

.circleci/config.yml
=> Update CI image to go 1.12.5

pkg/util/validation/limits.go
=> Expose the limits override config fields to YAML

pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/series_store.go
=> Limiting chunks query start time with config

pkg/chunk/cassandra/fixtures.go, pkg/chunk/cassandra/storage_client.go, pkg/chunk/cassandra/table_client.go
=> Allow Cassandra config to be passed as YAML.

README.md
=> Add kubecon talks.

README.md, cmd/cortex/Dockerfile, docs/getting_started.md, docs/single-process-config.yaml
These are the steps from the demos at KubeCon, showing basic operations, scalability and redundancy.
=> Add replication/HA demo to getting started guide.

pkg/chunk/gcp/gcs_object_client.go
We're seeing issues where GCS is rate-limiting our requests. Now the SDK keeps retrying the requests until the context is cancelled. And in this case the context is cancelled after 2mins, which means the query is stuck for 2mins and this causes a huge query queue pileup.
By setting a smaller timeout, we will fail the queries early atleast.
=> Add GCS object client specific timeout

pkg/querier/frontend/query_range.go, pkg/querier/frontend/query_range_test.go
=> frontend: Make sure no samples are repeating

pkg/chunk/cassandra/storage_client.go
Link to Issue https://github.com/grafana/loki/issues/628.
Please help to evaluate if this is a real issue.
=> Cassandra Client miss ConnectTimeout config

.circleci/config.yml, Makefile, build-image/Dockerfile, pkg/chunk/storage/caching_index_client.pb.go, pkg/ingester/client/cortex.pb.go, pkg/querier/frontend/frontend.pb.go, pkg/ring/ring.pb.go
=> Fix the version of protobuf and pin tools in the build image.

pkg/querier/correctness/runner.go
=> Ensure we propagate the trace correctly from test-exporter to querier.

docs/arguments.md
I found myself needing to explain these to someone, so am doing it via a PR.
=> Document ingester client grpc sizing args

.circleci/config.yml
It looks like it will be the same, but better to use a tag from master.
=> Use build image tag from master branch

pkg/chunk/chunk_store_utils.go
=> Document non-obvious function behaviour

pkg/chunk/aws/dynamodb_table_client.go
Fixes #1484 
Also wrap the error so next time we get a weird one it's easier to see where it came from.
=> Filter out "Tagging is not currently supported" errors from DynamoDB Local

docs/architecture.md
Just jotted down some minimal notes since the existing text is a misapprehension.
=> Minimal Ruler and AlertManager docs

ADOPTERS.md
Added with permission from @achilles42 who runs the cortex cluster there. They use it to collect their telegraf and prometheus metrics.
=> Add GoJek to the list of users

pkg/distributor/distributor.go
I wanted this to see what was a good value for `-ingester-client.expected-labels`.
Don't mind if this PR is never merged.
=> Add a histogram to observe number of labels received

CHANGELOG.md
I added some of the notable changes that have happend over the last 4 weeks. Let me know if there is anything else you would like added to the first changelog.
=> Cut release v0.1.0-rc.0

pkg/ring/kv/consul/client.go
=> Honour ConsistentReads in WatchPrefix.

pkg/alertmanager/multitenant.go
Seems odd to have a mutex and to use it in some places but not others.
=> Lock around alertmanagers map everywhere

pkg/distributor/distributor.go, pkg/distributor/ha_tracker.go, pkg/ring/kv/consul/client.go, pkg/ring/kv/etcd/etcd.go
=> Add HA tracker metrics

pkg/chunk/table_manager.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> table_manager.go: flagset help message typo fix

pkg/ingester/client/pool.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> pool.go: correct logging message words

ADOPTERS.md
Signed-off-by: Graham Rounds <graham@platform9.com>
=> add Platform9 to list of adopters

pkg/util/validation/override.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: override.go logging message typo

pkg/chunk/aws/metrics_autoscaling.go
Random overlaps of hash keys can cause small amounts of throttling when capacity is otherwise fine, so put a floor on the level we care about.
Note we don't apply this heuristic if the queue is at the 10x level - assume things are bad and scale up anyway.
=> In DynamoDB metrics autoscaling, ignore throttling below some level

integration-tests/common.sh
=> Make IMAGE_TAG honor CIRCLE_TAG

pkg/alertmanager/alertmanager.go
Fix #1659 
We have to pass a valid registry, otherwise it panics.
Then, it seems reasonable to use the same marker for alerts as we do for silences, even though we're not really getting anything out of it.
=> Fix up Alertmanager 'marker' object

go.mod, go.sum, vendor/github.com/bradfitz/gomemcache/memcache/memcache.go, vendor/modules.txt
This PR updates gomemcache, it adds a few performance improvements from the upstream lib.
=> update gomemcache to latest version

build-image/Dockerfile
Needs updation in the circle too. That's after this PR.
=> Update build image to golang 1.13 - part 1

docs/aws-specific.md, docs/running.md
This covers a few things I've been asked about in Slack and elsewhere.
=> Add AWS-specific points to docs

README.md, docs/running.md
Add some documentation to help new users avoid accidentally creating hundreds of dynamodb tables.
=> Add documentation for periodic table dates

pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant.go, pkg/ruler/notifier.go, pkg/ruler/ruler.go
* Enable the alertmanager v2 api
* Add config for the ruler to notify using the v2 api
=> Enable V2 Alertmanager API 

RELEASE.md
=> Mention the VERSION file in release instructions

pkg/ingester/transfer.go
I had an over-limit error reported in the logs, but didn't know which user it related to.
And once I was in there I figured I might as well wrap all the errors.
=> Wrap errors from TransferChunks to make troubleshooting easier

MAINTAINERS
=> Add Jacob (@jtlisi) as a maintainer!!

pkg/ring/batch.go, pkg/ring/ring_test.go
=> Guard agasint divide by 0 error when the rings ingester count is 0

build-image/Dockerfile
=> Upgrade to go v1.13.3

.circleci/config.yml
=> Update circle with the new 1.13.3 image

pkg/querier/queryrange/results_cache.go
=> Remove log line added for debugging #1698

pkg/alertmanager/alertmanager.go
Currently each user in cortex requires a reload channel that is essentially null to handle reload errors from the UI. This PR uses a global channel so a separate channel is not required for each users alertmanager.
=> use global channel for all alertmanager web reloads

docs/ha-pair-handling.md
=> docs: Add docs on how HA sample handling works.

CONTRIBUTING.md
I realised I was complaining about people doing it wrong and we haven't set down what 'good' looks like.
Probably there are some good versions of this in other projects, but I couldn't find one I liked on a quick Google.
=> Add some words about what makes a good PR

ADOPTERS.md
=> Add DigitalOcean to the adopters list.

pkg/cortex/modules.go, pkg/ingester/ingester_v2.go, pkg/querier/block.go, pkg/querier/block_store.go, pkg/storage/tsdb/backend/gcs/bucket_client.go, pkg/storage/tsdb/backend/gcs/config.go, pkg/storage/tsdb/backend/s3/bucket_client.go, pkg/storage/tsdb/backend/s3/config.go, pkg/storage/tsdb/bucket_client.go, pkg/storage/tsdb/bucket_client_test.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go, vendor/github.com/thanos-io/thanos/pkg/objstore/gcs/gcs.go, vendor/modules.txt
This PR adds GCS backend support to TSDB storage engine. I've both tested it with S3 (no regression) and GCS, and looks working as expected.
**Checklist**
=> Add GCS support to TSDB config

CHANGELOG.md, pkg/chunk/storage/factory.go
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
=> Remove `dynamo` as a valid storage option

pkg/ingester/ingester_v2.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go
Adds support for user defined tsdb block ranges.
=> blocks/tsdb: support block range lists

docs/arguments.md
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>
Corrects typo in Query-Frontend argugments
**Checklist**
=> docs: arguments: fix typo in query-frontend s/case/cause

pkg/ingester/transfer.go
It checked for the same condition as IF above it. Also removed "TransferChunks:" prefix from error messages, and added correct prefixes at calling sites.
=> Removed extra check from checkFromIngesterIsInLeavingState in transfer.go

pkg/distributor/distributor_test.go
Today I was investigating if the distributor's `MetricsForLabelMatchers()` looks susceptible of FNV-1a hash collisions and I believe it is. In this PR I'm not fixing it, but I'm adding some unit tests on it (I will try to fix it in a separate PR, but I would like to find a FNV-1a hash collision first).
_No issue_
**Checklist**
=> Add unit tests for distributor's MetricsForLabelMatchers()

CHANGELOG.md
Forgot to add a changelog note in #1726 @gouthamve 
=> Add changelog item for #1726

docs/running.md
Signed-off-by: canghai118 <zjy71055@gmail.com>
Just a typo in doc
No issue
**Checklist**
=> Fix anchor in doc

pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go, pkg/querier/queryrange/roundtrip.go
=> frontend to clean up cache on exit

pkg/ingester/flush.go
This is helpful when testing stuff, and also in general.
=> Log when flushing all the chunks

README.md
A general guide to running cortex & Information regarding the configuring cortex doesn't work.
Signed-off-by: vineeth <vineethpothulapati@outlook.com>
#1932
=> Corrected URL configuration in Readme.md

docs/getting_started.md
Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>
**Checklist**
=> docs: getting_started: correct tense 's/runs/run'

docs/guides/cortex-with-cassandra.md
Fixes #1985 
Signed-off-by: vineeth <vineethpothulapati@outlook.com>
@gouthamve @pracucci
=> Added the chunk prefix to the cassandra setup config file.

README.md
Added links to the google groups and meetings notes.
Signed-off-by: vineeth <vineethpothulapati@outlook.com>
@gouthamve
=> Added info on community meetings.

docs/guides/sharded_ruler.md
I had assumed rulers would work more like ingesters in this respect, so seems worth mentioning.
=> Add a note to docs about rulers re-sharding on rollout

pkg/querier/block.go, pkg/querier/block_store.go
**What this PR does**: Adds trace points to the user stores when running with the experimental TSDBs.
**Checklist**
=> tsdb/querier: add tracing to block stores

docs/apis.md
Add an example to POST alertmanager config and rules.
=> add example to POST alertmanager config and rules

pkg/ring/kv/kv_test.go
Test now uses longer waits between time updates, has longer total time (3s) and expects to see fewer values (75%).
At the same time, test uses same structure as TestWatchPrefix:
- start watcher early, before generator even starts
- report observed values through buffered channel
- end test early if we have seen enough values
Fixes issue #1800.
=> Modified TestWatchKey test to make it less strict.

go.mod, go.sum, vendor/github.com/opentracing/opentracing-go/ext.go, vendor/github.com/opentracing/opentracing-go/ext/field.go, vendor/github.com/opentracing/opentracing-go/ext/tags.go, vendor/github.com/opentracing/opentracing-go/go.mod, vendor/github.com/opentracing/opentracing-go/go.sum, vendor/github.com/opentracing/opentracing-go/gocontext.go, vendor/github.com/opentracing/opentracing-go/log/field.go, vendor/github.com/opentracing/opentracing-go/log/util.go, vendor/github.com/opentracing/opentracing-go/noop.go, vendor/modules.txt
I've had a look at the diff, nothing major has been changed they added new function that we don't use.
In vendor/github.com/opentracing/opentracing-go/log/util.go there is the change I made for #1712
Fixes https://github.com/cortexproject/cortex/issues/1712
=> Updates opentracing-go to latest/head

CONTRIBUTING.md, README.md, docs/getting_started.md
While reading through the docs noticed a few broken links and a spot that could have been a little clearer. This PR fixes those things.
No issue
**Checklist**
=> Docs update

CHANGELOG.md
As per the discussions on slack
/cc @pracucci @gouthamve
=> Mark WAL as EXPERIMENTAL

CHANGELOG.md, pkg/ingester/wal.go
Note that I have opened this for the release branch.
=> Fix WAL metric names

integration/e2e/service.go
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> e2e: Fixed TestWaitMetric_Nan test.

docs/apis.md
Adds a few more links and a little more exposition.
=> Expand on Cortex' write API a little more.

.circleci/config.yml
Don't repeat regex matcher for each job.
=> Make CircleCI config DRYer.

integration/alertmanager_test.go, integration/backward_compatibility_test.go, integration/e2e/scenario.go, integration/e2e/scenario_test.go, integration/e2e/service.go, integration/e2e/service_test.go, integration/ingester_flush_test.go, integration/ingester_hand_over_test.go, integration/integration_memberlist_single_binary_test.go, integration/query_frontend_test.go
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> e2e: Reduced number times the networkName variable is needed; Also allowed injecting different comparisons to WaitSumMetrics.

pkg/ring/kv/etcd/etcd.go
1. There is no need to use backoff in etcd watch api. and missing `Wait` in current implements.
2. check watch response error .
=> pkg/ring/kv/etcd: fix etcd watch api usage.

integration/api_config_test.go
Fixed linter in new integration test.
N/A
**Checklist**
=> Fixed linter in new integration test

integration/backward_compatibility_test.go, integration/configs.go, pkg/util/grpcclient/ratelimit_test.go
We've just merged PR #2008 which has done an amazing work to fix all linter issues. The linter in `master` fails because of changes introduced in the meanwhile, which this PR addresses.
N/A
**Checklist**
=> Fixed linter in integration tests

README.md
=> Add KubeCon talks, PromCon talks and blog post to README.

docs/configuration/config-file-reference.md, docs/configuration/config-file-reference.template, pkg/chunk/azure/blob_storage_client.go, pkg/chunk/cache/redis_cache.go, pkg/chunk/cassandra/storage_client.go, pkg/chunk/cassandra/storage_client_test.go, pkg/ingester/lifecycle_test.go, pkg/storage/tsdb/backend/azure/bucket_client.go, pkg/storage/tsdb/backend/azure/config.go, pkg/storage/tsdb/backend/gcs/bucket_client.go, pkg/storage/tsdb/backend/gcs/config.go, pkg/storage/tsdb/backend/s3/bucket_client.go, pkg/storage/tsdb/backend/s3/config.go, pkg/util/flagext/secret.go, pkg/util/flagext/secret_test.go, pkg/util/flagext/url.go, pkg/util/flagext/url_test.go, tools/doc-generator/parser.go
=> Hide passwords in URLs on the /config endpoint.

pkg/util/services/README.md, pkg/util/services/basic_service.go, pkg/util/services/basic_service_test.go, pkg/util/services/example_test.go, pkg/util/services/manager.go, pkg/util/services/manager_test.go, pkg/util/services/service.go, pkg/util/services/services.go, pkg/util/services/services_test.go
**What this PR does**: This is first half of PR https://github.com/cortexproject/cortex/pull/2166, it adds services package to Cortex. For design and rationale, please see that PR.
=> Added services package.

MAINTAINERS
Removes Cody Boggs from the maintainers list. Because let's be honest - I've not contributed. Ever. :-)
=> Remove Cody Boggs from maintainers

pkg/util/services/basic_service_test.go
AwaitRunning can observe either Stopping or Terminated, but we only checked for error message containing Terminated state before.
=> Fix flaky test for AwaitRunning.

pkg/querier/chunk_store_queryable.go, pkg/querier/chunk_store_queryable_test.go
This trivial PR just adds a comment to `chunkSeries` type about implementing SeriesWithChunks interface. It also adds a check.
=> Add comment and check for chunkSeries implementation of SeriesWithChunks

docs/guides/caching.md, docs/guides/running.md
=> Add documentation on configuring caching.

CONTRIBUTING.md, README.md, docs/_index.md, docs/contributing/how-to-run-website-locally.md, tools/website/web-pre.sh
In this PR I've attempted to document how to run the website locally, in order to allow everyone to have a quick feedback loop when writing the documentation.
It's worth to note that I've moved `CONTRIBUTING.md` into a folder but the URL in the website has **not** changed (https://cortexmetrics.io/docs/contributing/).
Preview:
N/A
**Checklist**
=> Documented how to run the website locally

.circleci/config.yml
This PR fixed the `build-image` version used across the CI.
N/A
**Checklist**
=> Fix build-image version used in CI

pkg/distributor/query.go
Following up #2238, we shouldn't track a failure when the context is cancelled. I manually tried it to verify the check works as expected.
N/A
**Checklist**
=> Do not track cortex_distributor_ingester_query_failures_total if context was canceled

pkg/cortex/modules.go, pkg/cortex/status.go
**What this PR does**: this trivial PR changes `moduleName` from number to a string, which allows us to remove some extra code.
**Checklist**
=> Convert module name to a string. It simplifies the code a bit.

docs/configuration/single-process-config-blocks.yaml, docs/getting-started/getting-started-blocks.md
Signed-off-by: Martin Schneppenheim <martin.schneppenheim@rewe-digital.com>
**What this PR does**: On top of https://github.com/cortexproject/cortex/pull/2257 this PR adds documentation about how to use other Bucket stores (GCS, Azure storage, local storage) for using the TSDB storage engine.
**Checklist**
=> Add documentation how to use other TSDB backends beside S3

RELEASE.md
Updated the release instructions to ensure the release tag is merged (without squash) into `master` to make sure `go` versioning works as expected.
N/A
**Checklist**
=> Updated RELEASE instructions

pkg/storage/tsdb/bucket_client_test.go
=> Fix the import for test for bucket_client

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/wal.go
WAL metrics are being not registered right now because of nil Registerer :/
=> Set the Registerer for the WAL

k8s/configs-db-dep.yaml, k8s/configs-dep.yaml
Signed-off-by: Weifeng Wang <qclaogui@gmail.com>
Updated `configs-dep.yaml`, make it work for demo deploy
**Checklist**
=> Updated latest stable version tag to 0.7.0

docs/configuration/arguments.md
=> Fix link to doc

docs/contributing/_index.md, docs/contributing/how-integration-tests-work.md, integration/README.md
Earlier today, I was giving some input to #1694 on how to run integration tests. I've realised we have no documentation for it, so I've sketched a basic documentation on how to run integration tests.
N/A
**Checklist**
=> Documented how to run integration tests

docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/getting-started/getting-started-blocks.md, docs/getting-started/getting-started-with-gossip-ring.md, integration/e2e/service.go, integration/getting_started_with_gossiped_ring_test.go
**What this PR does**: this PR adds quick-start guide for gossiped ring, with two example configuration files.
**Checklist**
=> Gettings started with gossip ring.

pkg/querier/astmapper/shard_summer.go, pkg/querier/queryrange/querysharding.go
There was recently a push to avoid package level instrumentation in favor of passing prometheus Registerers explicitly. The [implementation](https://github.com/cortexproject/cortex/commit/442db4be5f5864c2006b298cdec9d7f8e0f1124f#diff-a579bdd70930544d997eb4d6574deba4R49) of this in the querier accidentally had the side effect of causing the `frontend_sharded_queries_total` counter to be instantiated _per request_, resulting in panics when attempting to re-register the metric.
Now we create the counter in the middleware creation alongside other instrumentation and pass it explicitly to the `ShardSummer`.
/cc @pracucci 
**Former Stack trace**
```
goroutine 1379 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000fe550, …
```
=> astmapper shard metrics only instantiated once

pkg/cortex/cortex.go, pkg/cortex/cortex_test.go, pkg/cortex/module_service_wrapper.go, pkg/cortex/modules.go
All of the variables of the `moduleName` are already public. This makes the variable itself public.
=> Make `moduleName` -> `ModuleName`

pkg/chunk/schema_config.go, pkg/util/flagext/deprecated.go
Also, I couldn't find a better way to do this.
Fixes: https://github.com/cortexproject/cortex/issues/1425
**Checklist**
=> Add metric for deprecated flags set.

CHANGELOG.md
Had the incorrect PR number in the changelog entry.
=> Fix: Changelog entry for #2346

docs/guides/zone-replication.md
**What this PR does**: corrects some doc errors spotted by @pracucci 
**Checklist**
- [ x] Documentation added
=> doc update for zone awareness

pkg/chunk/azure/blob_storage_client.go, pkg/chunk/cache/fifo_cache.go, pkg/chunk/cache/memcached_client.go, pkg/chunk/cache/redis_cache.go, pkg/chunk/cassandra/storage_client.go, pkg/chunk/purger/purger.go, pkg/cortex/modules.go, pkg/ingester/ingester_v2.go, pkg/ingester/wal.go, pkg/querier/block.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/lifecycler.go, pkg/util/experimental.go
Based on https://github.com/cortexproject/cortex/pull/2360#discussion_r400335570
=> Print a warning when using an experimental feature

docs/configuration/config-file-reference.md, pkg/ingester/ingester.go
While going through the changelog I realised I missed this in a rebase :man_facepalming:
=> Actually set the chunk-age-jitter to 0

docs/configuration/config-file-reference.md, pkg/ring/lifecycler.go
Adjustment to the text of zone configuration.
Signed-off-by: Ken Haines <khaines@microsoft.com>
**Checklist**
- [ x ] Documentation added
=> Rewording the text for zone awareness setting

docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, tools/doc-generator/main.go
improve config file doc by move some big blocks to separated sections
**Checklist**
=> improve config file doc

pkg/chunk/local/boltdb_table_client.go, pkg/chunk/storage/factory.go, pkg/chunk/storage/factory_test.go
We had added support for registering custom index client. This PR also adds support for registering custom table client with it.
**Checklist**
=> support for registering custom table client with index client

CHANGELOG.md
Once merged, I will update the GitHub release notes accordingly.
N/A
**Checklist**
=> Mentioned blocks storage known issue in Cortex 1.0.0 release notes

go.mod, go.sum, vendor/github.com/golang/groupcache/singleflight/singleflight.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/objstore/inmem.go, vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go, vendor/github.com/thanos-io/thanos/pkg/store/proxy.go, vendor/modules.txt
While working on #2469 (still a draft PR), I've got some flaky integration tests due to missing memcached client metrics initialization in Thanos. This PR upgrades Thanos to master, in order to unblock #2469. Thanos changes are minimal.
N/A
**Checklist**
=> Updated Thanos to master

docs/production/ingesters-with-wal.md, tools/website/website.go
Docs were not updated after the flusher target was merged
=> Update docs for flusher target in WAL production guide

pkg/ingester/wal.go, pkg/ingester/wal_test.go
We were not testing the WAL enough before as we checkpoint when shutting down the ingester. I have added `checkpointDuringShutdown` in config just for tests and using it to test more of the WAL.
=> Enhance TestWAL to test more of WAL

pkg/storegateway/gateway_test.go
The `TestStoreGateway_BlocksSharding` is flaky ([example](https://app.circleci.com/pipelines/github/cortexproject/cortex/5123/workflows/1aad323d-7732-4101-a74d-bbba9b941c75/jobs/26720)). Looking at symptoms, I think it's due to the fact we're not waiting until the ring client has updated before continuing the tests (I've been able to reproduce it adding a 1s sleep in `WatchKey()`). This PR should fix it.
N/A
**Checklist**
=> Fixed store-gateway flaky test

docs/production/ingesters-with-wal.md
The changes are mostly geared towards non-kubernetes scenerio.
/cc @tomwilkie
=> Additional notes on running WAL in production

pkg/ingester/ingester_test.go, pkg/ingester/wal_test.go
This would enable us to compare any performance improvements in the future.
=> Add benchmark for WAL replay

docs/configuration/single-process-config.yaml, pkg/ingester/ingester.go
Signed-off-by: Ganesh Vernekar <cs15btech11018@iith.ac.in>
**Checklist**
=> Enable WAL by default in single process config

CHANGELOG.md, pkg/distributor/distributor_test.go, pkg/ring/kv/consul/client.go, pkg/ring/kv/consul/client_test.go, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/util/test/poll.go
=> cherry-pick #2503 into release-1.0

pkg/distributor/distributor_test.go
We've just merged #2459 which wasn't rebased with the latest version of `master` and distributor tests now don't compile because of some recent changes. This PR fixes it.
N/A
**Checklist**
=> Fixed distributor tests

development/tsdb-blocks-storage-s3-single-binary/compose-up.sh, development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml, development/tsdb-blocks-storage-s3/compose-up.sh, development/tsdb-blocks-storage-s3/docker-compose.yml
- Added CGO_ENABLED=0 to `compose-up.sh` to fix issues on Ubuntu
- Added Jaeger all in one
cc @pracucci
=> Local Development Improvements

docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go, tools/doc-generator/parser.go
My initial plan was to move the store-gateway ring config to the generic `tsdb.Config`. However, after I did it, I did sound weird too, because most of the ring config is actually required only by the store-gateway.
For this reason, I've picked a different path. The querier still needs a bit of store-gateway config but I've tried to clarify it in the config file documentation.
What do you think?
N/A
**Checklist**
=> Clarify store-gateway ring config

integration/chunks_storage_backends_test.go
Fixes broken integration test in Ci/CD
**Checklist**
=> fix integration test

pkg/ingester/metrics.go
This addresses https://github.com/cortexproject/cortex/issues/2530
@pracucci PTAL.
Any tests or docs we want to add here? Thanks!
=> cortex_ingester_chunk_size_bytes: add 2 buckets

docs/apis.md
Add some basic documentation on the Ruler API
**Checklist**
=> Documentation for the experimental ruler API

docs/proposals/scalable-query-frontend.md
Proposes a series of changes to improve the scalability of the query frontend.
Fixes #
**Checklist**
=> Proposal: Scalable Query Frontend

pkg/chunk/local/boltdb_index_client_test.go
We've just merged #2441 which apparently wasn't rebased. This PR fixes tests in master.
N/A
**Checklist**
=> Fixed tests

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/ingester/ingester_v2.go, pkg/storage/tsdb/config.go
Add option to enable TSDB WAL compression.
N/A
**Checklist**
=> Add option to enable TSDB WAL compression

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, docs/operations/blocks-storage.template, go.mod, go.sum, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/index_cache_test.go, pkg/storage/tsdb/memcache_client_config.go, pkg/storage/tsdb/memcache_client_config_test.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/cache/cache.go, vendor/github.com/thanos-io/thanos/pkg/cache/memcached.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go, vendor/modules.txt
**What this PR does**: this PR integrates latest Thanos master and allows bucket stores (used by querier and gateway) to be configured with "chunks caching bucket".
**Checklist**
=> TSDB: chunks caching

go.mod, go.sum, pkg/storage/tsdb/caching_bucket.go, vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_config.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go, vendor/modules.txt
**What this PR does**: This PR updates Thanos to latest master (762eb5e1dfab), which includes caching bucket changes.
**Checklist**
=> Update Thanos to latest master (with caching bucket changes)

CHANGELOG.md
This PR removes extra white space from CHANGELOG.md.
=> Remove extra whitespace

CHANGELOG.md
Signed-off-by: Gustavo Coelho <gutorc@hotmail.com>
It changes dynamodb provisioning link on changelog
Fixes #2422
=> Update dynamodb provisioning link on changelog

pkg/cortex/cortex.go, pkg/querier/blocks_store_queryable.go
In this PR:
- Fix trace propagation in `blocksStoreQuerier.selectSorted()`
- Disable Thanos span propagation because we're getting flooded by memcached spans (need to fix it)
N/A
**Checklist**
=> Fixed Thanos trace propagation

docs/apis.md
=> Improve Ruler API Documentation

.circleci/config.yml, integration/backward_compatibility_test.go
**What this PR does**: This PR adds Cortex 1.0 and 1.1 to the integration test .
=> Added Cortex 1.0 and 1.1 to integration test.

CHANGELOG.md, pkg/chunk/cassandra/storage_client.go
Fix query statement in cassandra storage
=> cassandra-cql-fixup

go.mod, go.sum, vendor/github.com/prometheus/prometheus/discovery/triton/triton.go, vendor/github.com/prometheus/prometheus/promql/engine.go, vendor/github.com/prometheus/prometheus/scrape/scrape.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_other.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_windows.go, vendor/modules.txt
Contains this fix https://github.com/prometheus/prometheus/pull/7306
As it was a small upgrade, I didn't feel the need to add an entry in changelog
=> Upgrade Prometheus to current master

go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go, vendor/modules.txt
It includes this fix https://github.com/prometheus/prometheus/pull/7314
=> Upgrade Prometheus to latest master

pkg/storegateway/bucket_stores.go
**What this PR does**: This PR fixes moves children spans under `BucketStores.Series` span.
=> Fix spans under BucketStores.Series span.

k8s/s3-dep.yaml
=> [1145] Replacing fake s3 with minio in s3-dep

Makefile
It requires a tool 'embedmd' which we make inside the build container.
=> Move 'make doc' inside containerised build

pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/roundtrip.go
This is useful for adding more informations depending on the implementation.
/cc @owen-d
=> Add the ability to customize the frontend request span log.

pkg/querier/block.go
The `blockQuerierSeriesSet.At()` could be called multiple times for the same item. Moving the `blockQuerierSeries` to `Next()` instead of `At()` saves a memory allocation and re-running a `sort.Slice()`. It's really a micro-optimization but shouldn't cause any harm having it.
N/A
**Checklist**
=> Micro-optimization in blockQuerierSeriesSet.At()

pkg/querier/queryrange/query_range.go
Add a span log for number of series in API response.
Fixes NA
**Checklist**
=> Log number of series in API response

docs/configuration/config-file-reference.md, pkg/querier/frontend/frontend.go
This PR updates the query logging functionality in the Frontend to log more details about the query. It now includes the `tenant id` and `method` of the request. It also consolidates form from the query parameters and post form into a single loop. This makes it easier to analyze queries the use different methods, POST or GET.
**Checklist**
=> more detailed slow query logging

website/config.toml, website/content/en/_index.html
I broke website when I upgraded hugo, config change makes everything shiny again :)
Also see google/docsy#174 and https://github.com/gohugoio/hugo/releases/tag/v0.60.0
=> Fix website

k8s/ingester-dep.yaml, k8s/querier-dep.yaml, k8s/ruler-dep.yaml, k8s/s3-dep.yaml, k8s/s3-svc.yaml, k8s/schema-config.yaml
I've tried to run distributor, ingester, querier and table-manager (plus their deps) on a local Kubernetes (using Docker for Mac) and fixed the issues I've found along the way, including the ones reported by #2727.
Fixes #2727
**Checklist**
=> Fixed S3 config in the k8s/ manifests

Makefile
We're currently releasing only the cortex binaries. Since we've got few users running the query-tee too, I would like to also build and release query-tee binaries along with Cortex releases.
N/A
**Checklist**
=> Added query-tee to the list of released binaries

docs/production/tls.md
Adds missing documentation.
Fixes NA
**Checklist**
=> Add missing docs for TLS config in Ingester Client

CHANGELOG.md
**What this PR does**: Adds missing CHANGELOG entry for PR #2571.
=> Add CHANGELOG.md entry for PR 2571

pkg/ingester/ingester_v2.go
**What this PR does**: This PR removes individual shipper's context, and uses shipper service's context instead.
If service is asked to stop (in ingester's own Stopping method), all shippers will stop. ShipBlocks method still waits for all shippers to stop before returning.
This simplifies the code slightly, and allows more incoming changes (flush and shipping of TSDB blocks on shutdown).
=> Don't use shipper context, but pass shipper service context instead.

RELEASE.md
During last Cortex community call, I've been asked to shepherd Cortex 1.3.0 release. In this PR I'm updating the doc accordingly.
N/A
**Checklist**
=> Update RELEASE doc with 1.3.0 shepherd

RELEASE.md
Lets remove the dependency on just 2 companies.
**Checklist**
=> Open up Release process to other end users.

docs/configuration/config-file-reference.md
I haven't rebased since the merge of #2831 on #2768 which triggered a
change in the config reference.
=> `make doc` to Fix master

docs/roadmap.md
Quickly jotted this down, as a follow up to https://github.com/cncf/toc/pull/315#issuecomment-651376899
Once I have consensus that these are the features we actually want and after incorporating more suggestions, I'll tighten up the language.
=> Public roadmap for the project

CHANGELOG.md, pkg/chunk/purger/purger.go, pkg/chunk/purger/purger_test.go
Fixed a race in purger while managing in process delete requests.
Refactored some code to manage them easily.
**Checklist**
=> fix a race in purger managing in process delete requests

docs/production/ha-pair-handling.md
Adds example minimal configuration requirements to properly enable HA Tracking.
N/A
**Checklist**
=> [Docs] HA Tracker: Add minimum configuration guide.

docs/configuration/config-file-reference.md, pkg/chunk/azure/blob_storage_client.go
=> Fix up;oads => uploads typo

pkg/ruler/rules/local/local.go, pkg/ruler/rules/local/local_test.go
I've just merged https://github.com/cortexproject/cortex/pull/2878, but unfortunately it wasn't rebased and Cortex `master` is broken now. This PR should fix it.
Fixes `master`
**Checklist**
- [c] Tests updated
=> Fixed rulefmt after merging PR #2878

CHANGELOG.md, go.mod, go.sum, pkg/cortex/modules.go, pkg/querier/querier.go, pkg/ruler/ruler.go, vendor/github.com/prometheus/prometheus/discovery/README.md, vendor/github.com/prometheus/prometheus/discovery/dockerswarm/dockerswarm.go, vendor/github.com/prometheus/prometheus/promql/engine.go, vendor/github.com/prometheus/prometheus/promql/test.go, vendor/github.com/prometheus/prometheus/rules/alerting.go, vendor/github.com/prometheus/prometheus/rules/manager.go, vendor/github.com/prometheus/prometheus/scrape/scrape.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/modules.txt
To include https://github.com/prometheus/prometheus/pull/7638
=> Upgrade Prometheus to master

docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
In the last 24h I received 2 requests to migrate TSDB blocks from Thanos/Prometheus to Cortex blocks storage. We don't provide any tool (yet), but at least we can document the procedure (which is fairy easy).
We also want some help to [build an automation](https://github.com/cortexproject/cortex/issues/2920).
N/A
**Checklist**
=> Documented how to migrate Thanos/Prometheus storage to Cortex

.circleci/config.yml, build-image/Dockerfile, docs/contributing/how-to-run-website-locally.md, website/package-lock.json, website/package.json
While reviewing the PR https://github.com/cortexproject/cortex/pull/2895 I've noticed there's no guarantee the website's local dev env runs the same dependencies version of CI. Unfortunately `npm install -g` (global) doesn't support `package.json` so with my limited JS knowledge I haven't found a way to use `website/package.json*` in the `build-image`, but if there's any I will be very happy to reiterate on this.
/cc @cyriltovena 
N/A
**Checklist**
=> Clarify local website setup and upgrade deps

development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml
In the PR #2937 I've introduced some breaking changes in the blocks storage config but I forgot to update the local dev environment config (actually I did, but I forgot to commit 🤦 ).
N/A
**Checklist**
=> Fixed local dev environment after blocks storage config changes

docs/governance/how-to-add-a-maintainer.md, website/config.toml
I would like to track the visits to the website as a data point to better understand how people navigates the doc and use this data for further doc navigation / structure improvements. In this PR I've configured google analytics for the website (I manually tested it and works).
A couple of important things:
- I disabled any privacy sensitive tracking in Google Analytics
- I configured Google Analytics for the lowest retention
- I invited all Cortex maintainers with full privileges (including add/remove users)
N/A
**Checklist**
=> Added Google Analytics tracking to website

docs/apis.md, docs/guides/deleting-series.md
Adds docs on how to perform deletion in Cortex with its features.
**Checklist**
=> docs for performing deletion in cortex chunks storage

pkg/querier/queryrange/query_range.go
Just update the comment.
**Checklist**
=> Chore: update logToSpan method comment

CHANGELOG.md, integration/asserts.go, integration/chunks_delete_series_test.go, integration/e2ecortex/client.go, integration/e2ecortex/services.go, pkg/chunk/purger/request_handler.go, pkg/testexporter/correctness/delete_series.go
Add integration tests for delete series, testing deletes for all index stores.
Fixes status code for add and cancel APIs to return `204` instead of `200`.
**Checklist**
=> integration test for deletion of series

pkg/chunk/cache/memcached.go, pkg/chunk/chunk_store.go, pkg/chunk/series_store.go, pkg/testexporter/correctness/runner.go
Correctly closes spanlogger in a handful of places where it was not closed.
=> Close spanlogger

docs/getting-started/getting-started-chunks.md
Signed-off-by: Brian Pham <brianpham827@gmail.com>
Fix typo in getting started doc
=> Fix typo in docs/getting-started/getting-started-chunks.md

integration/backward_compatibility_test.go
As part of the release process, I've added backward compatibility integration tests for Cortex 1.2.0 and 1.3.0.
N/A
**Checklist**
=> Added backward compatibility integration tests for Cortex 1.2.0 and 1.3.0

docs/guides/grpc-storage-plugin.md
**What this PR does**: Docs for gRPC storage plugin. 
Fixes #2664 
**Checklist**
=> gRPC storage plugin docs

docs/architecture.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, docs/production/ha-pair-handling.md, pkg/distributor/ha_tracker.go
Signed-off-by: Paul Sinaï <psinai@forepaas.com>
This PR fixes the issue with the documentation regarding KV store supported by the HA Tracker.
**Checklist**
=> Doc fixes for KV stores supported by HA Tracker

docs/configuration/arguments.md
**What this PR does**: This PR adds basic description of gossip algorithm, and some tuning options.
=> Explain how gossiping works, how to tune and monitor it.

integration/alertmanager_test.go, integration/api_config_test.go, integration/asserts.go, integration/backward_compatibility_test.go, integration/chunks_delete_series_test.go, integration/chunks_storage_backends_test.go, integration/configs.go, integration/getting_started_single_process_config_test.go, integration/getting_started_with_gossiped_ring_test.go, integration/ingester_flush_test.go, integration/ingester_hand_over_test.go, integration/integration_memberlist_single_binary_test.go, integration/kv_test.go, integration/package.go, integration/querier_remote_read_test.go, integration/querier_streaming_mixed_ingester_test.go, integration/querier_test.go, integration/query_frontend_test.go, integration/ruler_test.go, integration/s3_storage_client_test.go, integration/util.go
- I want to vendor these tests in an external project buta main package can't be vendored
=> change: rename integration test package from main to integration

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, pkg/ring/kv/etcd/etcd.go
Adds TLS support for **etcd** dependency
Fixes #3091 
**Checklist**
=> Issue #3091 - Add etcd dependency TLS support

go.mod, go.sum, pkg/api/api.go, vendor/github.com/felixge/fgprof/LICENSE.txt, vendor/github.com/felixge/fgprof/README.md, vendor/github.com/felixge/fgprof/fgprof.go, vendor/github.com/felixge/fgprof/format.go, vendor/github.com/felixge/fgprof/go.mod, vendor/github.com/felixge/fgprof/go.sum, vendor/github.com/felixge/fgprof/handler.go, vendor/github.com/felixge/fgprof/pprof.go, vendor/github.com/google/pprof/AUTHORS, vendor/github.com/google/pprof/CONTRIBUTORS, vendor/github.com/google/pprof/LICENSE, vendor/github.com/google/pprof/profile/encode.go, vendor/github.com/google/pprof/profile/filter.go, vendor/github.com/google/pprof/profile/index.go, vendor/github.com/google/pprof/profile/legacy_java_profile.go, vendor/github.com/google/pprof/profile/legacy_profile.go, vendor/github.com/google/pprof/profile/merge.go, vendor/github.com/google/pprof/profile/profile.go, vendor/github.com/google/pprof/profile/proto.go, vendor/github.com/google/pprof/profile/prune.go, vendor/modules.txt
Add fgprof to support I/O time profiler.
Fixes #2795  
**Checklist**
=> Support fgprof debug endpoint

pkg/cortex/modules.go, pkg/ring/kv/memberlist/kv_init_service.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go, pkg/ring/kv/memberlist/tcp_transport.go
**What this PR does**: This PR fixes two problems: race condition from issue #2884, caused by modifying logger between memberlist tests, and [integration test failure](https://app.circleci.com/pipelines/github/cortexproject/cortex/8081/workflows/90ea6173-242b-46f0-9364-fc187802c431/jobs/39962) caused by missing dependancy between store-queryable and memberlist-kv.
Fixes #2884 
**Checklist**
=> Fix failing integration tests

CHANGELOG.md, integration/e2ecortex/client.go, integration/querier_test.go, pkg/api/queryable.go, pkg/api/queryable_test.go, pkg/querier/querier.go, pkg/util/validation/limits.go
=> Fix the querier returning 500 status code on query range limit errors

docs/proposals/shuffle-sharding-and-zone-awareness.md, docs/proposals/shuffle-sharding-on-the-read-path.md, tools/cleanup-white-noise.sh
**What this PR does**: This PR adds two shuffle-sharding related proposal (previously internal).
=> Add design documents about shuffle-sharding on read path and zone awareness

pkg/chunk/local/boltdb_index_client.go
This is an optimization for `boltdb-shipper` in Loki to improve query performance by doing multiple queries in a single transaction.
`QueryWithCursor` is a new method for boltdb index client which would use passed cursor to perform the queries.
=> add a QueryWithCursor method for boltdb to help doing multiple queries in a single transaction

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Adds issues templates to gather all the required info in bug reports which otherwise requires going back and forth with users to get it.
This is how it would look like: https://github.com/sandeepsukhani/test-issues-template/issues/new/choose
=> issues templates to gather all the required information in bug reports

CHANGELOG.md, tools/blocksconvert/builder/builder.go
**What this PR does**: This PR modifies blocksconvert "builder" to retry block upload, if it fails.
**Checklist**
=> blocksconvert: Retry block upload.

CHANGELOG.md, pkg/chunk/gcp/gcs_object_client.go, pkg/ruler/rules/objectclient/rule_store.go
=> Speed up the listing of rule groups on the Ruler Configuration API

pkg/cortex/status.go
Make the services page identical upon refresh. No API changes.
Fixes #3251
**Checklist**
=> Sort the entries in Cortex Services Status by name

integration/backward_compatibility_test.go
I've just released Cortex 1.4.0, so adding it to backward compatibility tests.
N/A
**Checklist**
=> Added Cortex 1.4.0 to backward compatibility tests

pkg/chunk/chunk_store.go, pkg/chunk/series_store.go, pkg/querier/lazyquery/lazyquery.go
Clarify 'implements ChunkStore' doc comments
Fixes #3085 
**Checklist**
=> Clarify 'implements ChunkStore' doc comments

docs/configuration/config-file-reference.md, pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/gcp/gcs_object_client.go
It's not clear how to configure auth for BigTable and GCS. I think adding a reference to the GCP doc could help our users.
Fixes #3306
**Checklist**
=> Clarify how to configure auth for BigTable and GCS

docs/architecture.md
Correct link for Block Storage reference
=> Correct link for Block Storage reference

CHANGELOG.md, pkg/ruler/manager.go
Otherwise, is hard debug notification failures.
**Checklist**
- N/A Tests updated
- N/A Documentation added
=> Include the tenant ID as part of the notifier logs

integration/ingester_limits_test.go
The `TestIngesterGlobalLimits` is flaky. I suspect the reason is that in the test we're running with RF=3 and as soon as 1 write request fail we stop pushing more series. However, due to how the sharding works, we may have hit the limit on 1 ingester, but if we remote write more series these may be accepted if they get ingested by a different ingester. This PR fixes this specific scenario.
N/A
**Checklist**
=> Fixed TestIngesterGlobalLimits flakyness

pkg/ingester/limiter_test.go
In the PR #3369 I've received the comment:
> Would it be possible to refactor limiter code to avoid the same repeated tests? (In a follow-up PR, if at all).
This is the follow-up PR. The diff is not much readable (sorry), so I would suggest to just check out the actual code. Tests are the exact same, just refactored to avoid repeating all duplicated test cases.
N/A
**Checklist**
=> Refactored ingester Limiter tests

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/ring/model.go, pkg/ring/ring.go
This is an internal change with no user impact. Similarly to the ruler, I've added a ring operation dedicated for the `Compactor` to make it more clear and avoid misunderstanding in the future.
/cc @MichelHollands 
N/A
**Checklist**
=> Move the compactor to use its own ring operation

CHANGELOG.md, pkg/alertmanager/multitenant.go
Adds additional logging on Alertmanager UI / API requests. 
Fixes a small part of #3395 
**Checklist**
=> Improve Alertmanager logging when serving requests via API/UI

RELEASE.md
- Add myself as the 1.6.0 release shepherd
=> chore: designate @jtlisi as v1.6.0 release shepherd

CHANGELOG.md
First step of the release, show that we are doing a release.
=> Start 1.5 release

docs/configuration/v1-guarantees.md, docs/guides/glossary.md, docs/guides/limitations.md, docs/production/ingesters-with-wal.md
In this PR I'm proposing to introduce a couple of new documentation pages:
- Limitations
- Glossary
Fixes #3023
Fixes #3365
**Checklist**
=> Documented limitations and glossary

pkg/querier/frontend/frontend_test.go
**What this PR does**: This PR fixes race in `TestFrontend_LogsSlowQueriesFormValues`. Race is between `buf.String()` and writes to the buf from other goroutines. ([CI Failure](https://github.com/cortexproject/cortex/runs/1340754022?check_suite_focus=true))
**Checklist**
=> Fix race in TestFrontend_LogsSlowQueriesFormValues.

pkg/cortex/cortex.go, pkg/scheduler/scheduler.go
Earlier today I merged a pkg refactoring https://github.com/cortexproject/cortex/pull/3433 for the new query-scheduler, but I didn't realised I actually broke it. This PR fixes it.
N/A
**Checklist**
=> Fix query-scheduler after pkg refactoring

pkg/api/handlers.go
=> fix: register querier routes explicitly with handler for instrumentation

docs/api/_index.md
Signed-off-by: Jigar <chavada.jigar.3@gmail.com>
- Adds documentation of `/debug/*` endpoints
Fixes #3174 
**Checklist**
=> Add documentation for '/debug/*' endpoints

pkg/frontend/v2/frontend_scheduler_worker.go, pkg/querier/worker/worker.go
**What this PR does**: This tiny PR modifies Debug to Info in workers when adding/removing connection to frontend and scheduler.
**Checklist**
=> Use Info level for messages about adding and removing connection to scheduler and frontend.

README.md
Fixes documentation links
N/A
**Checklist**
=> Fixing README guide links

docs/guides/running-chunks-storage-in-production.md
=> Mention that blocks storage is ready for production use in guides

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> Add backwards compatability test for v1.5.0

CHANGELOG.md, docs/architecture.md, docs/configuration/config-file-reference.md, docs/operations/scalable-query-frontend.md, pkg/querier/worker/worker.go
**What this PR does**: This PR adds section about query scheduler to architecture overview.
**Checklist**
=> Document query scheduler

docs/getting-started/getting-started-blocks.md
Signed-off-by: Romain Meunier <romainmeunier@gmail.com>
Fix a broken link in Getting started / Blocks Storage page
=> Fix blocks operation doc broken link

pkg/chunk/chunk_store.go
I have a feeling we're stuck on #3499 so I'd like to get  improvement that are not controversial merged.
=> Use formatMatcher only once.

CHANGELOG.md
Use correct flag names, from https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_config
=> Update flag names in CHANGELOG.md

pkg/querier/blocks_scanner_test.go
Today I've noticied an issue which I haven't been able to reproduce yet: queriers didn't stop on `SIGTERM` while they were running the initial sync. In this PR I've added a couple of unit tests on that and they pass. I also tried to reproduce the issue locally injecting few `time.Sleep()` here and then, but I haven't reproduce it yet. I think unit tests are good anyway, so I would like to upstream them anyway.
N/A
**Checklist**
=> Added tests on BlocksScanner quick shutdown

development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml, development/tsdb-blocks-storage-s3-gossip/docker-compose.yml
**What this PR does**: This PR finished gossip setup in docker-compose. It sets node names, and configures memberlist for compactor, ruler and store-gateway rings and enables buffer for received and sent messages.
**Checklist**
=> Finish docker-compose gossip setup

docs/guides/ha-pair-handling.md
Signed-off-by: Nick Pillitteri <nick@tshlabs.org>
Fixes typo
**Checklist**
=> HA pair guide typo

docs/proposals/tenant-deletion.md
This is a proposal / design doc for tenant deletion data. Some parts of it have already been implemented (#3558 #3549), but not all.
=> Proposal for deletion of tenant data when using blocks storage.

pkg/ring/kv/memberlist/kv_init_service.go, pkg/ring/kv/memberlist/kv_init_service_test.go
Otherwise we get a panic.
Fixes #3621 
**Checklist**
- NA `CHANGELOG.md` updated  (don't think it merits a CHANGELOG)
=> Check if kv pointer is nil before casting it

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
In this PR I'm attempting one possible solution (there are multiples) to fix the race condition described in #3620.
Fixes #3620
**Checklist**
=> Do not close idle TSDBs while blocks shipping is in progress

development/tsdb-blocks-storage-s3-gossip/docker-compose.yml, development/tsdb-blocks-storage-s3/docker-compose.yml
Alertmanager fails to start otherwise
**Checklist**
=> Fix alertmanager config in development

MAINTAINERS
I moved from Splunk to Grafana Labs over the holiday, update the maintainers file to keep in sync.
=> Update Chris Marchbanks' affiliation

pkg/chunk/purger/tombstones.go
Signed-off-by: Christian Simon <simon@swine.de>
This makes the log messages added in #3640  consistent with others in Cortex.
**Checklist**
- ~[ ] Tests updated~
- ~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~
=> Log error tenant ID using the user label

.gitignore, pkg/cortex/runtime_config_test.go
Also we were git-ignoring that folder so fix config to ignore only the
binary in root folder.
=> Add test for anchored YAML loading.

.github/workflows/test-build-deploy.yml, SECURITY.md
=> Add AWS to the security announce list.

pkg/ruler/ruler.go
While investigating an issue I've noticed a wrong log message in the ruler. This PR fixes it.
N/A
**Checklist**
=> Fixed ruler error message on failure while checking ring

CHANGELOG.md
Quick fix of `CHANGELOG.md`. The conflict resolution for https://github.com/cortexproject/cortex/commit/aff3f0dff3184d54ec3bcba7a21e992d8084db0c seems to result in staled change log not being removed.
Didn't create a PR as this is a super simple fix.
**Checklist**
=> Quick fix of CHANGELOG.md to remove duplicate [CHANGELOG]

pkg/distributor/distributor.go
Removes unnecessary type casting
=> Removed unnecesarry typecasting

CHANGELOG.md
Signed-off-by: Ken Haines <khaines@microsoft.com>
**What this PR does**: Updates the changelog in master to note what is in the initial 1.7 release candidates
=> updating changelog in master to reflect start of 1.7 release process

pkg/distributor/distributor.go, pkg/distributor/query.go
**What this PR does**: This PR removes import of `github.com/cortexproject/cortex/pkg/ingester/client` package, if it is already imported with different package name.
**Checklist**
=> Remove double-import of github.com/cortexproject/cortex/pkg/ingester/client package.

pkg/cortex/modules.go
This allows to wrap the queryable before and after the tenant federation wrapping if required by external code.
**Checklist**
~- [ ] Tests updated~
~- [ ] Documentation added~
~- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~
=> Wrap queryable for tenant federation within a module

docs/proposals/tenant_retention.md
This is a proposal / design doc for tenant retention data.
=> Proposal for tenant retention

pkg/querier/queryrange/results_cache.go
Addresses comments on https://github.com/cortexproject/cortex/pull/3744
=> Log on parse error of @ modifier cache check

Makefile, pkg/cortex/modules.go, pkg/flusher/flusher.go, pkg/ingester/flush.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/lifecycle_test.go, pkg/ingester/mapper.go, pkg/ingester/mapper_test.go, pkg/ingester/transfer.go, pkg/ingester/user_state.go, pkg/ingester/wal.go
- Adds a logger field for both the ingester and flusher structs
A TODO already exists in the code base and I created an issue #3778 
**Checklist**
=> chore: use embedded logger for Ingester & Flusher structs

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
The downstream project I'm working on is not ready for #3765 yet. There was some misunderstanding. Reverting it.
=> Revert PR 3765

README.md, docs/_index.md
At Grafana Labs I've been asked to update the description of Grafana Cloud offering, with a fresher one.
N/A
**Checklist**
=> Update Grafana Cloud offering description

docs/getting-started/getting-started-with-gossip-ring.md
Signed-off-by: Saintmalik <msalawu5@gmail.com>
Easy navigation and easy reading for others
**Checklist**
=> Fix broken url in docs

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/compact/planner.go, vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go, vendor/github.com/thanos-io/thanos/pkg/pool/pool.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go, vendor/modules.txt
I've done few changes into Thanos, which are propaedeutic for upcoming work in Cortex (eg. S3 SSE with per-tenant key and experiment with some store-gateway optimisations). In this PR I'm upgrading Thanos.
N/A
**Checklist**
=> Upgrade Thanos

pkg/ingester/limiter.go, pkg/ingester/limiter_test.go
=> Better error messages for rate-limits hit

pkg/api/api.go, pkg/chunk/purger/tenant_deletion_api.go, pkg/chunk/purger/tenant_deletion_api_test.go, pkg/cortex/modules.go
**What this PR does**: This PR just renames "Blocks Purger" to "Tenant Deletion". It doesn't do anything else. Really. I hope.
**Checklist**
=> Rename Blocks Purger to Tenant Deletion.

docs/blocks-storage/migrate-from-chunks-to-blocks.md
A few small improvements based on my experience migrating.
=> Update migration doc

CHANGELOG.md, development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/rules.yaml, development/tsdb-blocks-storage-swift-single-binary/config/cortex.yaml, docs/guides/encryption-at-rest.md, docs/guides/encryption-at-rest.template
This PR adds the documentation for the S3 SSE support to ruler.
Based on #3869 (reason why it's a draft).
N/A
**Checklist**
=> Add documentation for S3 SSE support to ruler

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/chunk_bytes_pool.go, pkg/storegateway/chunk_bytes_pool_test.go
Similarly to #3877, we know very little about how the chunk bytes pool is performing. This PR adds a couple of basic metrics about it.
N/A
**Checklist**
=> Added metrics to track chunk bytes pool behaviour

docs/blocks-storage/production-tips.md
=> compactor: Add a note to know when the migration is done

CHANGELOG.md
**What this PR does**: This PR updates changelog to indicate that 1.8 release is in progress.
**Checklist**
=> Update changelog to indicate that 1.8 release is in progress.

MAINTAINERS
Hello all,
I have decided to step down as a maintainer of Cortex. My priorities have shifted, and though I still like the project and want to see it continue to grow and succeed, active work on Cortex is no longer a priority of mine. It is certainly possible I will do some dev work in Cortex again in the future, and I am sure I will see many of you around in the community still!
=> Step down as maintainer

pkg/chunk/cache/memcached.go
Fix typos in comments in Memcached code.
**Checklist**
=> Memcached: Fix comment typos

pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
Continuation from review comments: https://github.com/cortexproject/cortex/pull/3930#discussion_r590255705
**Checklist**
=> Remove channel in favour of using Service.AwaitReady.

pkg/alertmanager/alertmanager_metrics.go
https://github.com/cortexproject/cortex/pull/3839#discussion_r587584483
=> Add per-user versions of alertmanager state replication metrics.

docs/guides/ingesters-scaling-up-and-down.md
I guess we might want to offer https://github.com/cortexproject/cortex/issues/3294#issuecomment-788126349 as a temporary change?
=> Expand instructions on scaling up

docs/proposals/scalable-alertmanager.md, docs/proposals/shuffle-sharding-and-zone-awareness.md, docs/proposals/tenant-deletion.md
- Mark some implemented proposals as accepted
=> chore: mark implemnted proposals accepted

docs/guides/sharded_ruler.md
=> Fix bad link to HTTP API docs from ruler guide

pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/metrics.go, pkg/ingester/user_state.go, pkg/util/math/rate.go, pkg/util/math/rate_test.go
**What this PR does**: This PR moves `ewmaRate` from `ingester` to `util/math` package, and makes it public for reuse from other packages.
**Checklist**
=> Move ewmaRate into util/math package, and make it public.

docs/roadmap.md
Implemented since last update:
- Per-tenant retention,
- Soft Multitenancy,
- Prometheus metadata support,
- Bulk loading Thanos data,
- Alertmanager sharding
I also made some changes for better readability.
=> Update roadmap for 2021

pkg/compactor/compactor.go
Yesterday we had a consul issue during a rollout and this led to the
ring check being broken. We weren't alerted until 24hrs later when
queries started failing.
We had an alert on
`cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds`
but it wasn't even being set.
=> [compactor] Run blocks cleaner before ring ready.

integration/alertmanager_test.go, integration/e2ecortex/client.go
1) Small extension to the alertmanager integration to exercise the alert listing
endpoints when sharding is enabled (TestAlertmanagerSharding):
- `POST /alerts`
- `GET  /alerts`
- `GET  /alerts/groups`
2) Run test for replication factor of two and three, to better exercise
the quorum write path used by `POST /alerts`.
=> Expand endpoint testing in alertmanager integration test.

integration/util.go
Improves integration test project directory detection by using git.
**Checklist**
- ~[ ] Tests updated~
- ~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~
=> Using git to determine cortex project dir for integration tests

CHANGELOG.md
This PR updates changelog to indicate that 1.8 release is in progress.
**Checklist**
=> Update changelog for 1.9 release in progress.

pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
While profiling the store-gateway CPU and memory in a cluster running with a large number of tenants per store-gateway instance, I've noticed a small (but significative) % of CPU and allocated objects are due to `getMetricsWithLabelNames()`. In this PR I'm proposing some optimization.
Benchmark:
```
name                         old time/op    new time/op    delta
GetMetricsWithLabelNames-12     931µs ± 1%     225µs ± 2%  -75.86%  (p=0.008 n=5+5)
name                         old alloc/op   new alloc/op   delta
GetMetricsWithLabelNames-12     735kB ± 0%      89kB ± 0%  -87.88%  (p=0.008 n=5+5)
name                         old allocs/op  new allocs/op  delta
GetMetricsWithLabelNames-12     4.03k ± 0%     2.01k ± 0%  -50.10%  (p=0.008 n=5+5)
``` …
=> Optimized getMetricsWithLabelNames() helper

go.mod, go.sum, pkg/querier/queryrange/promql_test.go, vendor/github.com/prometheus/prometheus/config/config.go, vendor/github.com/prometheus/prometheus/discovery/README.md, vendor/github.com/prometheus/prometheus/promql/engine.go, vendor/github.com/prometheus/prometheus/rules/manager.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/modules.txt
Wanted to pull in https://github.com/prometheus/prometheus/pull/8770
=> Update Prometheus to latest

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> Add release 1.9 to the backwards compat matrix

MAINTAINERS
I am moving on from Weaveworks.
=> Update email address of Bryan Boreham as maintainer

CHANGELOG.md, pkg/ruler/ruler.go, pkg/ruler/store_mock_test.go
Signed-off-by: allenzhli <allenzhli@tencent.com>
Fixes #4177
**Checklist**
=> Fixe #4177: mockRuleStore require LoadRuleGroups, and fix ListAllRules

integration/alertmanager_test.go, integration/configs.go
Basic test which adds a number of instances and removes then again,
checking that state is maintained along the way. Also checks that
when shutting down all replicas, that state can be recovered from
remote storage.
**Checklist**
=> Add integration test for scaling alertmanager with sharding enabled.

pkg/distributor/ha_tracker.go
=> nit: fix typo in metric variable name

integration/querier_test.go, pkg/distributor/query.go
This PR fixes a regression introduced in #4240.
N/A
**Checklist**
=> Fixed regression introduced in #4240

.github/workflows/test-build-deploy.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/actions/virtual-environments/issues/3287
**Checklist**
=> Bump Ubuntu to 20.04 in CI

docs/guides/alert-manager-configuration.md
Signed-off-by: ShuzZzle <niclas.schad@gmail.com>
Update documentation on how to configure alertmanager_storage
Fixes #4206
**Checklist**
- [ NA ] Tests updated
- [ X ] Documentation added
- [ NA ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> docs: added alertmanager_storage docs

pkg/compactor/compactor.go, pkg/storegateway/gateway.go
While working on #4305, I've noticed we have a typo in the "wait ring stability" logs. This PR fixes it.
N/A
**Checklist**
=> Fixed 'wait ring stability' log

CHANGELOG.md, RELEASE.md
Update the release timeline, swap Bryan for Marco.
Tweak some CHANGELOG entries.
=> Prepare release 1.10

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> Add release 1.10 to the backwards compatibility matrix

go.mod, go.sum, integration/kv_test.go, pkg/alertmanager/distributor_test.go, pkg/alertmanager/multitenant_test.go, pkg/compactor/compactor_test.go, pkg/cortex/modules.go, pkg/distributor/distributor_test.go, pkg/distributor/ha_tracker_test.go, pkg/ingester/lifecycle_test.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/basic_lifecycler_test.go, pkg/ring/lifecycler_test.go, pkg/ring/ring_test.go, pkg/ruler/lifecycle_test.go, pkg/ruler/ruler_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/sharding_strategy_test.go, vendor/github.com/grafana/dskit/kv/client.go, vendor/github.com/grafana/dskit/kv/consul/client.go, vendor/github.com/grafana/dskit/kv/consul/metrics.go, vendor/github.com/grafana/dskit/kv/consul/mock.go, vendor/github.com/grafana/dskit/kv/memberlist/kv_init_service.go, vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go, vendor/github.com/grafana/dskit/kv/memberlist/metrics.go, vendor/github.com/grafana/dskit/kv/memberlist/tcp_transport.go, vendor/github.com/grafana/dskit/kv/multi.go, vendor/modules.txt
I suggest upgrading to latest dskit, which makes kv and memberlist metrics non-global.
**Checklist**
=> Chore: Upgrade dskit

pkg/querier/queryrange/split_by_interval.go
It should be 400 and was recently introduced by #4464.
**Checklist**
=> Fixes 500 in the frontend when a query is invalid.

MAINTAINERS
=> Update affiliation of Bryan Boreham in Maintainers list

MAINTAINERS
Replacement for #4552 with DCO sign-off
=> Update Jacob Lisi entry in MAINTAINERS file

CHANGELOG.md
Corrects the PR number in the latest merge.
**Checklist**
=> fix PR number

MAINTAINERS
Vote result: https://groups.google.com/g/cortex-team/c/7HHNN4YPucA
Welcome @alanprot !
(Let me know if you want a different email address - I took that one from your public GitHub profile)
=> Add Alan Protasio as maintainer

docs/contributing/how-to-add-a-maintainer.md
Update "How to add maintainer" doc to include step to submit a PR to [CNCF maintainer list](http://maintainers.cncf.io). I was asked to create the PR when adding Alan as maintainer.
Below is the resulting page: 
N/A
**Checklist**
=> Add step to submit PR to CNCF maintainer list

CHANGELOG.md
**What this PR does**: Just a small typo
=> Small typo

docs/architecture.md
Signed-off-by: Friedrich Gonzalez <fgonzale@adobe.com>
**What this PR does**: fixes a typo
Fixes #4657
**Checklist**
=> Docs update: the correct word is loses

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go
Tiny docs fix to answer I question I had on slack: https://cloud-native.slack.com/archives/CCYDASBLP/p1647355510496469?thread_ts=1647288995.139859&cid=CCYDASBLP
cc @nschad
=> docs: clarify store-gateway lazy-load behavior

MAINTAINERS
@friedrich-at-adobe I got your e-mail address from your commits, let me know if you would like to use different one.
=> Add Friedrich Gonzalez as maintainer

docs/contributing/how-to-add-a-maintainer.md
I have created bunched of Cortex-dedicated resource using maintainer's CNCF email-list to avoid bus factor. Updates in the how to add maintainer step reflects that.
=> Update how to add maintainer 

README.md, docs/contributing/how-to-add-a-maintainer.md
Update community meeting information with newly created calendar.
=> Update community meetings information

pkg/alertmanager/alertstore/local/store_test.go, pkg/alertmanager/multitenant_test.go, pkg/chunk/local/boltdb_index_client_test.go, pkg/chunk/local/fs_object_client_test.go, pkg/chunk/storage/factory_test.go, pkg/compactor/compactor_test.go, pkg/ingester/flush_test.go, pkg/ingester/ingester_test.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/wal_test.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/querier/chunk_tar_test.go, pkg/querier/querier_test.go, pkg/ruler/api_test.go, pkg/ruler/lifecycle_test.go, pkg/ruler/manager_test.go, pkg/ruler/ruler_test.go, pkg/ruler/rulestore/local/local_test.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway_test.go, pkg/util/process/collector_test.go, pkg/util/tls/test/tls_integration_test.go, pkg/util/tls/tls_test.go, tools/blocksconvert/builder/series_test.go, tools/blocksconvert/builder/tsdb_test.go, tools/blocksconvert/scanner/scanner_test.go
A testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
**Checklist**
=> test: use `T.TempDir` to create temporary test directory

README.md, docs/chunks-storage/_index.md
Add chunk storage removal notice in README as well as the in the Cortex website.
=> Add notice for chunk storage removal

CHANGELOG.md
Add missing PR id on changelog.
Reorganize order of changelog
**Checklist**
=> Organize changelog

CHANGELOG.md, RELEASE.md
Update CHANGELOG.md to announce start of 1.13.0 release.
=> Start 1.13.0 release

docs/configuration/v1-guarantees.md
=> Update 1.x Guarantees doc to call out compactor shuffle sharding is experimental

CHANGELOG.md, RELEASE.md, docs/configuration/v1-guarantees.md, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/distributor/distributor.go, pkg/util/limiter/query_limiter_test.go
Everything in main branch is improvement or bug fixes, so safe to port to 1.13 release branch.
=> sync between master and release 1.13

website/package-lock.json, website/package.json
Address https://github.com/cortexproject/cortex/security/dependabot/3
=> Fix dependabot issue in package-lock.json second try

pkg/util/services/basic_service.go
Signed-off-by: 3Xpl0it3r <shouc.wang@hotmail.com>
fix a mistake in commit ,as Stopping is a state, not function name
=> fix  commit

docs/blocks-storage/_index.md
**What this PR does**: Uses new valid url for `Thanos Filesystem` document page
**Which issue(s) this PR fixes**: Updates documentation
**Checklist**
=> Redirect to valid thanos filestystem doc page

pkg/compactor/block_visit_marker.go, pkg/compactor/shuffle_sharding_planner.go
Fix the build after merge https://github.com/cortexproject/cortex/pull/4841 on master.
**Checklist**
=> Fix Build after https://github.com/cortexproject/cortex/pull/4841

pkg/tracing/sampler/sampling.go
Just a tiny code doc update.
N/A
**Checklist**
=> Fix tiny issue of doc in RandomRatioBased

MAINTAINERS
I am no longer active in the Cortex project, so wish to step down as a maintainer.
=> Remove Bryan Boreham from MAINTAINERS file

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/modules.txt
Bring https://github.com/thanos-io/thanos/pull/5739 in so that we can log the compaction run duration.
**Checklist**
=> chore: update thanos to bring compaction run duration log

README.md
Thanks for all their contributions!
=> Add Emeritus Maintainer section to README

docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/configuration/single-process-config-blocks-local.yaml, docs/configuration/single-process-config-blocks-tls.yaml, docs/configuration/single-process-config-blocks.yaml
**What this PR does**: Remove default config from examples
**Which issue(s) this PR fixes**: None
**Checklist**
=> Remove default config from getting started examples

README.md
Signed-off-by: ampabhi-aws <97638593+ampabhi-aws@users.noreply.github.com>
This PR updates the README with references to the Kubecon NA talks that the Cortex Maintainers are holding to drive awareness.
=> Updated the README to Reference Kubecon talks!

docs/_index.md
Signed-off-by: ampabhi-aws <97638593+ampabhi-aws@users.noreply.github.com>
**Checklist**
=> Updated to have Kubecon NA Talks!

MAINTAINERS, README.md
I sent an email to Goutham and Tom on Oct 6th. Both Tom and Goutham replied that they intended to resign. 
@jtlisi I haven't got a response from you via e-mail yet, but I assumed you no longer have time to work on Cortex? Please do let me know if that's not the case and we can keep you as a maintainer.
=> New Emeritus maintainers

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/querier/querier.go
Signed-off-by: songjiayang <songjiayang1@gmail.com>
Fixes #4927 
**Checklist**
=> Enable PromQL `@` modifier always 

README.md, docs/_index.md
=> KubeCon NA 2022 is done, remove the info links

RELEASE.md
=> Add instruction on how to generate SBOM as part of release process

docs/getting-started/_index.md
1. change single-process-config-blocks.yaml to single-process-config-blocks-local.yaml
2. add specific tag for cortex docker image
Signed-off-by: songjiayang <songjiayang1@gmail.com>
=> update getting started doc

README.md
We should eventually get to 100%
=> Add OpenSSf badge

CHANGELOG.md, RELEASE.md
Following https://github.com/cortexproject/cortex/blob/master/RELEASE.md#show-that-a-release-is-in-progress
Preparing 1.14 release.
**Checklist**
=> Start 1.14 Release

README.md
=> Update README with KubeCon talk video and slides

CHANGELOG.md
**What this PR does**: chunks can be migrated on v1.13.1
**Checklist**
=> Chunks can be migrated on v1.13.1

README.md
=> Add clomonitor badge to README

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile
Build Cortex with Go 1.19.3
**Checklist**
=> Build Cortex with go 1.19.3

.github/dependabot.yml
=> Try out dependantbot auto dependencies update

pkg/distributor/distributor.go
Signed-off-by: wangguoliang <iamwgliang@gmail.com>
Merge background contexts of all ingester pushes into one in distributor.
**Checklist**
=> Merge background contexts of all ingester pushes into one in distributor

integration/getting_started_single_process_config_local_test.go
**What this PR does**: Test example config with filesystem backend
**Checklist**
=> Test example config with filesystem backend

.github/workflows/test-build-deploy.yml, .golangci.yml, Makefile, integration/alertmanager_test.go, integration/asserts.go, integration/backward_compatibility_test.go, integration/configs.go, integration/integration_memberlist_single_binary_test.go, integration/querier_remote_read_test.go, integration/querier_sharding_test.go, integration/querier_tenant_federation_test.go, integration/querier_test.go, integration/ruler_test.go, integration/util.go
**What this PR does**: Run integration tests in parallel which should reduce testing time from 32 minutes to 14 minutes.
=> Run integration tests in parallel

pkg/querier/querier_test.go
=> Fix Flaky Test

go.mod, go.sum, vendor/github.com/efficientgo/core/testutil/testutil.go, vendor/github.com/thanos-community/promql-engine/api/remote.go, vendor/github.com/thanos-community/promql-engine/engine/engine.go, vendor/github.com/thanos-community/promql-engine/execution/exchange/coalesce.go, vendor/github.com/thanos-community/promql-engine/execution/exchange/dedup.go, vendor/github.com/thanos-community/promql-engine/execution/execution.go, vendor/github.com/thanos-community/promql-engine/logicalplan/distribute.go, vendor/github.com/thanos-community/promql-engine/logicalplan/plan.go, vendor/modules.txt
Include https://github.com/thanos-community/promql-engine/pull/153 to avoid panic the new engine when query stats is enabled.
**Checklist**
=> Update promql engine to fix stats panic

pkg/frontend/transport/handler.go
This pr adds `status_code` field to Cortex query frontend logs.
Previously the status code is not included because the code is calcuated later if there is any error so we cannot get it. This PR just uses the same logic to get the status code.
**Checklist**
=> Include status code in query frontend query stats logs

pkg/frontend/transport/handler.go
Signed-off-by: Kama Huang <kamatogo13@gmail.com>
resp could be nil, accessing status code could cause panic.
**Checklist**
=> fix response status code panic

pkg/frontend/transport/handler.go
We found that, if a range query hits the limits and returns 422, query frontend will log the error along with `query stats`, for example,
```
level=error ts=2023-02-02T01:25:48.893994Z caller=handler.go:256 org_id=fake traceID=4963809a53af6718 msg="query stats" component=query-frontend method=GET path=/prometheus/api/v1/query_range response_time=430.152917ms query_wall_time_seconds=0.026935625 fetched_series_count=0 fetched_chunks_bytes=0 fetched_data_bytes=0 status_code=422 param_query=up param_start=1675297463.264 param_end=1675301063.264 param_step=14 grafana_dashboard_uid=- grafana_panel_id=- error="{\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"expanding series: failed to receive series from localhost:9008: rpc error: code = …
```
=> query frontend: get error message from response body if err is nil

docs/_index.md
**What this PR does**: Remove Weave cloud and Grafana Cloud Reference from docs page
Fixes #5137
**Checklist**
=> Remove Weave cloud and Grafana Cloud Reference from docs page

pkg/util/limiter/query_limiter.go
Remove unnecessary sprintf
**Checklist**
=> remove unnecessary sprintf

pkg/distributor/query.go
Same as https://github.com/cortexproject/cortex/pull/5172. The commit seems got mistakenly removed somehow.
**Checklist**
=> Add a trace span for merging series from ingesters

pkg/querier/tripperware/test_shard_by_query_utils.go
related to PR #5154 
**Checklist**
=> fixed data race check in querier/tripperware/

go.mod, go.sum, integration/query_fuzz_test.go, vendor/github.com/cortexproject/promqlsmith/README.md, vendor/github.com/cortexproject/promqlsmith/opts.go, vendor/github.com/cortexproject/promqlsmith/promqlsmith.go, vendor/modules.txt
Update promqlsmith to latest version. No functional changes.
=> Update promqlsmith version

CHANGELOG.md, integration/query_frontend_test.go, pkg/frontend/transport/handler.go, pkg/querier/tripperware/queryrange/split_by_interval.go
Cherry-pick https://github.com/cortexproject/cortex/pull/5260 for the new RC.
=> Cherrypick #5260 to release 1.15 branch

integration/query_fuzz_test.go
Fix log print in the fuzzer test.
=> Fix error log in query fuzzer testcase

CHANGELOG.md, pkg/alertmanager/distributor.go, pkg/alertmanager/distributor_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
**What this PR does**: 
Fixes #5090
**Checklist**
=> Test and fix alertmanager-ui with sharding

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
Last step of publishing the public release.
**Checklist**
=> Update 1.15 compatibility test image

CHANGELOG.md, integration/e2ecortex/client.go, integration/querier_test.go, integration/query_frontend_test.go, integration/zone_aware_test.go, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/error_translate_queryable.go
Cherry pick the following commits to the 1.15 branch:
https://github.com/cortexproject/cortex/commit/8e36c84f58ec6ba9d75a003c6010384b985a99ac
https://github.com/cortexproject/cortex/commit/2587e15039c1cd98e08cf2ee6f303db5af7e802a
**Checklist**
=> Release 1.15.1

CHANGELOG.md
**What this PR does**: Fixes the changelog
Fixes #5304
**Checklist**
=> Fix changelog for v1.14.0. flag ingester.chunk-encoding was removed too

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> Add cortex 1.15.1 to compatibility test

.gitignore
This is just a minor cleanup. The new binaries are named differently and are not Ignored by the `.gitignore`.
```
> ls cmd/cortex/
Dockerfile   cortex-amd64 cortex-arm64 main.go      main_test.go migrations
````
**Checklist**
=> Ignore arm64 and amd64 binaries in .gitignore

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/single-process-config-blocks-local.yaml, integration/configs.go, integration/runtime_config_test.go, pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/cortex/runtime_config_test.go, pkg/storage/bucket/client.go, pkg/util/runtimeconfig/manager.go, pkg/util/runtimeconfig/manager_test.go, tools/doc-generator/main.go
Support other storage backends (all options listed in the [storage bucket client](https://github.com/cortexproject/cortex/blob/master/pkg/storage/bucket/client.go)) for the runtime configuration file. For backwards compatibility, the default is filesystem.
Fixes #5292 
**Checklist**
=> Support other storage backend options for runtime configuration file

pkg/compactor/block_visit_marker.go
Before uploading block visit marker, check whether context is canceled or not.
Fixes #5332 
**Checklist**
=> Check context done when uploading visit marker

pkg/util/grpcencoding/encoding_test.go
=> fix grpc encoding BenchmarkCompress

go.mod, go.sum, vendor/modules.txt
This does not bring any change, just use the prometheus stable tag.
**Checklist**
=> Use prometheus stable tag

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go, vendor/github.com/thanos-io/thanos/pkg/store/opts.go, vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go, vendor/modules.txt
Changes:
* https://github.com/thanos-io/thanos/pull/6358
* https://github.com/thanos-io/thanos/pull/6363
* https://github.com/thanos-io/thanos/pull/6371
* https://github.com/thanos-io/thanos/pull/6376
* https://github.com/thanos-io/thanos/pull/6374
=> [chore] Update Thanos

pkg/ingester/ingester.go
This aligns with the current prometheus logic https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L810.
We don't have to sort in ingesters at all as we are not using this property anywhere. We rely on series label hash for deduplication https://github.com/cortexproject/cortex/blob/master/pkg/distributor/distributor.go#L1135.
**Checklist**
=> Don't sort get series in ingesters if one matcher set only

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go, vendor/modules.txt
Update Thanos commit to latest to bring https://github.com/thanos-io/thanos/pull/6405.
That pr changes the cache key for the new compression format.
**Checklist**
=> Update thanos version to latest to bring cache key fix

ADOPTERS.md
Adds entry in the ADOPTERS.md file
N/A
**Checklist**
=> Add PITS Globale Datenrettungsdienste as an adoper

pkg/querier/tripperware/instantquery/instant_query_test.go
Avoids flaky results when the time generated by Decode is different from beginning of test.
Example: https://github.com/cortexproject/cortex/actions/runs/5417560262/jobs/9848659893?pr=5432
**Checklist**
=> Mitigating flaky TestRequest

docs/contributing/how-integration-tests-work.md, integration/e2ecortex/client.go, integration/ruler_test.go
=> Minor refactoring and update documentation

CHANGELOG.md
**What this PR does**: Mention known issue with configsdb in v1.14.0
Fixes #5387
**Checklist**
=> Includes known issue in v1.14.0 changelog

pkg/frontend/transport/handler.go
Including user agent as part of the query log to help filter and classify user queries.
**Checklist**
=> Query Frontend: log request user agent

integration/querier_test.go, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/multilevel_cache_test.go
Fix error when configuring index cache with `inmemory/memcached` backend:
```
panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "thanos_memcached_dns_provider_results", help: "The number of resolved endpoints for each configured address", constLabels: {component="store-gateway",level="L1",name="index-cache"}, variableLabels: [{addr <nil>}]} has different label names or a different help string
```
This is caused because the memcache client is also used by other cache implementations and should have the same subset of labels.
**Checklist**
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, …
=> fix multilevel cache with inmemory and memcached

docs/guides/alert-manager-configuration.md
**What this PR does**: Fix Cortex Tools reference in docs
**Checklist**
=> Fix Cortex Tools reference in docs

website/layouts/partials/navbar.html
This PR updates the GitHub reference in the navbar from `Github` to `GitHub`.
~Fixes #<issue number>~
**Checklist**
=> Update GitHub wording in navbar

CHANGELOG.md, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/lifecycle_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/ruler/rulestore/bucketclient/bucket_client.go, pkg/ruler/rulestore/bucketclient/bucket_client_test.go, pkg/ruler/rulestore/configdb/store.go, pkg/ruler/rulestore/local/local.go, pkg/ruler/rulestore/store.go, pkg/ruler/store_mock_test.go
Implementing what is suggested in https://github.com/cortexproject/cortex/issues/4180#issuecomment-840573262
Fixes: https://github.com/cortexproject/cortex/issues/4180
**Checklist**
=> Fail to load singe rulegroup cause rulers to halt the sync of all rulegroups.

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/modules.txt
Upgrade Thanos library version to 728bda9c387a49c96ee706b4fbd31758712a6e48.
This includes https://github.com/thanos-io/thanos/pull/6787 and https://github.com/thanos-io/thanos/pull/6792
**Checklist**
=> Update thanos version to latest main branch

go.mod, go.sum, vendor/github.com/thanos-io/promql-engine/execution/storage/filter.go, vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/modules.txt
upgrade thanos to latest main
NA
**Checklist**
=> upgrade thanos to latest main

CHANGELOG.md, RELEASE.md
Start `1.16.0` release.
**Checklist**
=> Prepare 1.16.0 release

CHANGELOG.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storegateway/bucket_index_metadata_fetcher_test.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go
Continues the work on https://github.com/cortexproject/cortex/pull/5186
Fixes #5133
**Checklist**
=> add/support enabled_tenants and disabled_tenants feature in storegateway

pkg/ruler/manager.go
When Ruler evaluates rule groups, there are quite a few metrics and logs generated after evaluation. However, in some cases such as when a pod gets killed due to out of memory, it would be good to have visibility into what rule groups were in the process of evaluating before the pod was killed. This PR adds an info log prior to rule evaluation
**Checklist**
=> Log rule group info prior to rule group evaluation

go.mod, go.sum, vendor/google.golang.org/grpc/internal/transport/http2_server.go, vendor/google.golang.org/grpc/server.go, vendor/google.golang.org/grpc/version.go, vendor/modules.txt
Patches `google.golang.org/grpc` lib to a version that has a fix for `CVE-2023-44487`.
None
**Checklist**
I don't think any documentation is needed for this kind of change?
=> increase patch version for google.golang.org/grpc

pkg/util/log/wrappers.go
Logging traceID for OTEL span. The function from weaveworks/common only supports jaeger span.
Got code from https://github.com/thanos-io/thanos/blob/main/pkg/extprom/http/instrument_server.go#L98
Tested locally and it works to log traceID when I am using OTEL tracing.
```
ts=2023-11-30T21:43:05.224533Z caller=handler.go:360 level=info org_id=fake traceID=55b5bb68cc9b7d184b20b68bdf4e6457 msg="query stats" component=query-frontend method=GET path=/prometheus/api/v1/query_range response_time=26.313123875s query_wall_time_seconds=0.004587875 fetched_series_count=13 fetched_chunks_count=27 fetched_samples_count=866 fetched_chunks_bytes=2246 fetched_data_bytes=3085 status_code=200 response_size=1188 shard_by.is_shardable=false shard_by.num_shards=2 …
```
=> Log traceID when it is a OTEL span

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
Remove older Cortex compatibility test images before v1.13.1
**Checklist**
=> Clean up older compatibility test images

integration/query_fuzz_test.go
Rather than using `sameModelValue` to check results equality directly on matrix, vector and scalar types, this pr changes the results check function to compare each `float64` value instead. The previous implementation seems having some issues when comparing float values.
This implementation is the same as what Thanos promql-engine does https://github.com/thanos-io/promql-engine/blob/main/engine/engine_test.go#L4970.
**Checklist**
=> Improve query fuzzing tests with better promql result comparison

pkg/distributor/query.go, pkg/ingester/ingester.go
Added more tags to trace spans when querying ingester.
**Checklist**
=> Add more trace tags to ingester query

docs/getting-started/_index.md
Update the Getting Started doc to include removal of Grafana instance in [Single instance, Since Process](https://cortexmetrics.io/docs/getting-started/#single-instance-single-process) part. Other section have the docker stop part but not this. This PR adds that
None
**Checklist**
=> docs: update getting_started docs

docs/architecture.md
Updates architecture.md. There were some inclarity in the architecture doc. 
The phrase `long-term storage backend` was redirecting to `#storage` section on the page. But there is no storage section in the page. Instead it now redirects to `#block-storage`
This PR fixes the grammar as well as improves readability
none
**Checklist**
=> docs: update architecture.md

docs/architecture.md
**What this PR does**: fixing concern reported in Slack
https://cloud-native.slack.com/archives/CCYDASBLP/p1706357315008049
**Checklist**
=> Fix typo in hyperlink

go.mod, go.sum, vendor/github.com/thanos-io/objstore/objstore.go, vendor/modules.txt
Update thanos objstore https://github.com/thanos-io/objstore/commit/bdadaefbfe03c19165f0cd85986a6359043226a5
**Checklist**
=> Update objstore bdadaefbfe03c19165f0cd85986a6359043226a5

pkg/ring/kv/dynamodb/client.go
Added more error logs when ddb kv cas/watchkey retry fails.
**Checklist**
=> add error logs for cas and watchkey after retry failure

ADOPTERS.md
**What this PR does**: Include Adobe as adopter
There is enough information public information online to prove it.
https://github.com/thanos-io/thanos/blob/e78d86733377bfd958709343a17939976cfdafd0/website/data/adopters.yml#L39-L41
https://www.youtube.com/watch?v=Pl5hEoRPLJU
**Checklist**
=> Include Adobe as adopter

go.mod, go.sum, pkg/chunk/cache/memcached_client.go, vendor/github.com/bradfitz/gomemcache/AUTHORS, vendor/github.com/bradfitz/gomemcache/memcache/memcache.go, vendor/github.com/bradfitz/gomemcache/memcache/selector.go, vendor/modules.txt
Stop using gomemcache fork: https://github.com/bradfitz/gomemcache/pull/86 was implemented on https://github.com/bradfitz/gomemcache/pull/158
**Checklist**
=> Stop using gomemcache Fork

RELEASE.md, pkg/ha/ha_tracker_test.go, pkg/querier/batch/stream.go, pkg/ring/kv/client.go, pkg/ring/kv/etcd/etcd.go
=> chore: remove repetitive words

integration/e2e/db/db.go, integration/e2e/images/images.go, integration/e2ecortex/client.go, integration/e2ecortex/services.go, integration/query_fuzz_test.go
Add a fuzz integration test to compare responses from Prometheus and Store Gateway with lazy expanded postings enabled.
**Checklist**
=> Add store gateway lazy expanded postings fuzz tests against Prometheus

go.mod, go.sum, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/modules.txt
Upgrade promqlsmith to include https://github.com/cortexproject/promqlsmith/commit/5e341f0dd08e34c001de87690149c81094a341c7
**Checklist**
=> Upgrade promqlsmith to latest main to cover more testcase

integration/e2ecortex/client.go
Add default retry in the query client used in the integration test to retry transient network failures.
Fixes #5851 
**Checklist**
=> Add retry to query frontend integration test

integration/e2e/metrics_options.go, pkg/ingester/ingester.go
fix function names in comment 
**Checklist**
=> chore: fix function names in comment

pkg/storage/tsdb/bucketindex/block_ids_fetcher_test.go
Fix flaky test case in BlockIDsFetcherFetcher.
Fixes #5857 
**Checklist**
=> sort block ids in BlockIDsFetcherFetcher test

README.md
**What this PR does**: Include Kubecon talk 2024
**Checklist**
=> Include Kubecon talk 2024

ADOPTERS.md
For context, we've been using Cortex since 2020/2021 in production. It's the backbone for all the metrics we provide to customers ourselves and also for custom integrations (where customers run their own exporters, etc..).
Just saw the cnf issue about the project, and wanted to add us. We are not planning to switch to Mimir any time soon. :)
Add ourselves to adopters.
=> Update(ADOPTERS.md): add "us"

.github/workflows/test-build-deploy.yml
**What this PR does**: fix go version for integration tests. Follow up from https://github.com/cortexproject/cortex/pull/5879
**Checklist**
=> fix go version for integration tests

integration/querier_test.go
=> Integration test querier max samples

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> chore: add version 1.16.1 to compatibility test

CHANGELOG.md, RELEASE.md
Mark release 1.17.0 in progress
**Checklist**
=> Start preparing for release 1.17

CHANGELOG.md
Change the ring changes from ENHANCEMENT to FEATURE on the changelog
**Checklist**
=> Change the ring changes from ENHANCEMENT to FEATURE on the changelog

ADOPTERS.md
Reverting Apple as an adopter for now.
=> Removing Apple as adopters

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> chore: add version 1.17.0 to compatibility test

docs/blocks-storage/migrate-from-chunks-to-blocks.md, docs/configuration/arguments.md, docs/configuration/v1-guarantees.md
Update Cortex docs to remove already deprecated/removed features.
**Checklist**
=> chore: remove deprecated/removed features from docs

docs/proposals/auth-gateway.md
I wrote a proposal for [auth-gateway](https://cortexmetrics.io/docs/roadmap/#auth-gateway) project. If there is anything that needs to be improved or clarified, please let me know.
Fixes #5106
=> Add auth-gateway proposal

go.mod, vendor/modules.txt
**What this PR does**: Remove unneeded replace in go.mod
**Checklist**
=> Remove unneeded replace on kuberesolver

README.md
Improve README.md for clarity, detail, and structure.
=> docs: Improve README.md for clarity, detail, and structure

integration/ruler_test.go, pkg/ingester/ingester.go, pkg/util/time.go, pkg/util/time_test.go
* Trying to improve the following flaky tests:
* TestSlottedTicker
* TestRulerKeepFiring integ tests
**Checklist**
=> Improve flaky tests

.github/workflows/test-build-deploy.yml, integration/e2e/images/images.go
* Update minio image used on the e3e tests to try to fix: https://github.com/cortexproject/cortex/actions/runs/9310406874/job/25627858491
**Checklist**
=> Updating minio image on the e2e tests

pkg/ruler/manager.go
Logging the messages returned from alert manager for visibility
=> logging messages returned from alert manager

pkg/ingester/ingester_test.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
Follow up of https://github.com/cortexproject/cortex/pull/5986. Added more ingester tests on ingesting native histograms.
**Checklist**
=> Add more tests for native histogram push

.github/workflows-doc.md, .github/workflows/test-build-deploy.yml
**What this PR does**: v2 is deprecated and will not work after June 30
**Checklist**
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact
=> Update upload-artifact and download-artifact to v4

.github/workflows/test-build-deploy.yml, Makefile
**What this PR does**: Update build-image to https://github.com/cortexproject/cortex/commit/6dd64fcce93e87497f0e3f6594e74f030b4538b4
**Checklist**
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Update build-image to image built with github actions

docs/api/_index.md
**What this PR does**: Describe OTLP receiver in docs
Fixes #6012
**Checklist**
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Describe OTLP receiver in docs

go.mod, go.sum, vendor/github.com/hashicorp/go-hclog/README.md, vendor/github.com/hashicorp/go-hclog/intlogger.go, vendor/github.com/hashicorp/go-hclog/logger.go, vendor/github.com/prometheus/prometheus/discovery/manager.go, vendor/github.com/prometheus/prometheus/model/labels/labels_common.go, vendor/github.com/prometheus/prometheus/model/labels/labels_dedupelabels.go, vendor/github.com/prometheus/prometheus/model/labels/labels_stringlabels.go, vendor/github.com/prometheus/prometheus/model/labels/matcher.go, vendor/github.com/prometheus/prometheus/model/labels/regexp.go, vendor/github.com/prometheus/prometheus/notifier/notifier.go, vendor/github.com/prometheus/prometheus/promql/engine.go, vendor/github.com/prometheus/prometheus/storage/remote/client.go, vendor/github.com/prometheus/prometheus/storage/remote/codec.go, vendor/github.com/prometheus/prometheus/storage/remote/queue_manager.go, vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go, vendor/github.com/prometheus/prometheus/tsdb/compact.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/github.com/prometheus/prometheus/tsdb/index/index.go, vendor/github.com/prometheus/prometheus/tsdb/index/postings.go, vendor/modules.txt
Update prometheus version to latest main to pull https://github.com/prometheus/prometheus/pull/14213 and https://github.com/prometheus/prometheus/pull/14114
**Checklist**
=> Update prometheus version to latest main

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, cmd/thanosconvert/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile, packaging/fpm/Dockerfile
* Upgrade to Alpine 3.18 to fix some security vulnerabilities
* Upgrade (patch version) go
**Checklist**
=> Upgrade alpine, go, and github.com/Azure/azure-sdk-for-go/sdk/azidentity

pkg/querier/querier_test.go
It seems that I merged https://github.com/cortexproject/cortex/pull/6018 too fast and didn't realize that there is a merge conflict. It still went through and build failed.
This PR should fix it.
**Checklist**
=> Fix merge failure of querier test

docs/getting-started/_index.md
There's already a title at the top, so the H1 header is unneeded.
**Checklist**
=> docs: Fix Getting Started Title

pkg/ring/token_generator_test.go
Fix: https://github.com/cortexproject/cortex/actions/runs/9769799880/job/26969916599?pr=6054#step:6:89
**Checklist**
=> Fix Minimize Token flaky test

build-image/Dockerfile
- Upgrading golangci-lint to a version that support golang 1.22
**Checklist**
=> Upgrade golangci-lint to 1.59.1

CHANGELOG.md, pkg/cortexpb/histograms.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Reuse `ExponentialSchemaMax` and `ExponentialSchemaMin` const from upstream.
Also add missing changelog for https://github.com/cortexproject/cortex/pull/6108
**Checklist**
=> Cleanup native histogram validation const

README.md
Alvin has stepped down as a maintainer. #6082 
Adding him under emeritus maintainer. He has earned it :)
**Checklist**
=> Add Alvin under Emeritus Maintainers

CHANGELOG.md
Add missing changelog for native histogram changes before next release (1.18)
**Checklist**
=> Add missing changelogs for native histogram

docs/getting-started/_index.md, docs/getting-started/cortex-values.yaml, docs/getting-started/grafana-values.yaml, docs/getting-started/prometheus-values.yaml, docs/getting-started/seaweedfs.yaml
This change updates the Kubernetes example to match the Docker getting started example.
- Updates Cortex Helm chart to 2.4.0
- Sets up multi-tenancy
- Sets up Alertmanager and Ruler
- Sets up Grafana dashboards
**Checklist**
=> Update Kubernetes Getting Started

docs/api/_index.md, docs/configuration/v1-guarantees.md, docs/guides/limitations.md, pkg/ingester/ingester_test.go, pkg/querier/querier_test.go
Follow up of #5984. The config was removed but the flags still exist in docs.
**Checklist**
=> cleanup docs for query_store_for_labels_enabled config

CHANGELOG.md, RELEASE.md
Mark release 1.18.0 in progress
**Checklist**
=> Start preparing for release 1.18

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
=> add 1.18.0 to backward compatibility test

README.md
**What this PR does**: Updates Community Call Calendar and Zoom Links
=> Update Community Call Calendar and Zoom Links

build-image/Dockerfile
* Update golang patch version in build-image
**Checklist**
=> Update golang patch version in build-image

pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/results_cache_test.go
=> [Querier] Fix Flaky Response Compression Test

pkg/util/strings.go
- This context check was missed in the previous PR: https://github.com/cortexproject/cortex/pull/6159
**Checklist**
=> util: Check context cancellation every 128 iterations

build-image/Dockerfile
Upgrade golangci-lint to latest version to support Go 1.23.X
Trying to see if this could fix https://github.com/cortexproject/cortex/pull/6262#issuecomment-2408171801 or not.
**Checklist**
=> Upgrade golangci-lint to 1.61.0

README.md
=> Add Nov 2024 KubeCon talk

Makefile
=> Increase configs integration test timeout from 30s to 10m

.github/workflows/test-build-deploy.yml
See: https://github.com/cortexproject/cortex/pull/6362
**Checklist**
=> Update Build Image with `envsubst`

MAINTAINERS.md
Sungjin Lee is currently very active on cortex project with a total of 37 PR which the majority already accepted and merged. Sungjin Lee  seems to have an active interest in the project and will be a great addition to the team.
Per existing governance, 2/3 majority votes are required for the changes to pass.
**Checklist**
=> [Vote] Add Sungjin Lee (@SungJin1212) as Triager on cortex

README.md
**What this PR does**: We have been doing monthly community meetings for a while
**Checklist**
=> Fix text about cortex community calls

pkg/ingester/ingester_test.go
Fix Flaky test:
See https://github.com/cortexproject/cortex/actions/runs/12130677851/job/33823094444#step:6:62
**Checklist**
=> Fix flaky TestExpendedPostingsCacheIsolation test

go.mod, go.sum, vendor/github.com/thanos-io/promql-engine/logicalplan/distribute.go, vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go, vendor/modules.txt
This PR upgrades the Thanos version to v0.37.1
Change that can affect to Cortex:
- https://github.com/thanos-io/promql-engine/pull/499
**Checklist**
=> Upgrade thanos version to v0.37.1

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/modules.txt
Update Thanos version to pull https://github.com/thanos-io/thanos/pull/7979
**Checklist**
=> Store Gateway: fix merge fetched postings with lazy postings

integration/query_fuzz_test.go
Extend #6350 to the other fuzz tests.
**Checklist**
=> Change query fuzz test for bottomk, topk: take 2

RELEASE.md
=> Prep for v1.19.0

pkg/cortex/modules.go, pkg/querier/querier.go
- When Thanos engine is enabled, enable analysis.
- The analysis is required for gathering samples queried stats
**Checklist**
=> Enable analysis on Thanos PromQL engine

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_server_selector.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/matchers_cache.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/github.com/thanos-io/thanos/pkg/store/local.go, vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go, vendor/github.com/thanos-io/thanos/pkg/store/proxy.go, vendor/github.com/thanos-io/thanos/pkg/store/storepb/custom.go, vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
Upgrade thanos to latest main. Relevant changes:
- https://github.com/thanos-io/thanos/pull/8017
- https://github.com/thanos-io/thanos/pull/8036
- https://github.com/thanos-io/thanos/pull/8026
- https://github.com/thanos-io/thanos/pull/8039
- https://github.com/thanos-io/thanos/pull/8035
- https://github.com/thanos-io/thanos/pull/8025
**Checklist**
=> Update thanos version to latest main

push-images
**What this PR does**: Retries docker commands 3 times before failing
Mitigates https://github.com/cortexproject/cortex/issues/6485
**Checklist**
=> Retry 3 times before failing docker command

go.mod, go.sum, vendor/github.com/thanos-io/promql-engine/execution/aggregate/hashaggregate.go, vendor/github.com/thanos-io/promql-engine/execution/function/relabel.go, vendor/modules.txt
Updating Thanos engine package to latest
Changes: https://github.com/thanos-io/promql-engine/compare/9dbff30059cf...2414c3d2ab47
**Checklist**
=> Update thanos-io/promql-engine to 2414c3d2ab47

.github/workflows/test-build-deploy.yml, Makefile
**What this PR does**: Use new build image from https://github.com/cortexproject/cortex/commit/d96523a3257d3c7965be3b8850a9e1b483751d80
**Checklist**
=> Use new build image

.github/workflows/test-build-deploy.yml, Makefile
**What this PR does**: Update build image according to https://github.com/cortexproject/cortex/commit/03a8f8c9807e666b606a07bd2c5f4e29e18b0428
**Checklist**
=> Update build image according to 03a8f8c9807e666b606a07bd2c5f4e29e18b0428

CHANGELOG.md
https://github.com/cortexproject/cortex/blob/master/RELEASE.md#show-that-a-release-is-in-progress
=> Mark 1.19 release in progress

go.mod, go.sum, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/modules.txt
Updates Thanos dependency to latest main. Main changes are:
- https://github.com/thanos-io/thanos/pull/8084
- https://github.com/thanos-io/thanos/pull/8083
Also updated promqlsmith to latest main to pull https://github.com/cortexproject/promqlsmith/pull/144
**Checklist**
=> Update thanos latest main

MAINTAINERS.md
https://github.com/dsabsay has been contributing to Cortex for some time and his main focus has been fixing flaky tests and security patching.
I'd love to start a vote to add him to the triage team since he is willing to help with the project.
Daniel's commits can be found [here](https://github.com/cortexproject/cortex/commits?author=dsabsay)
Per existing governance, 2/3 majority votes are required for the changes to pass.
=> [Vote] add dsabsay as triager

pkg/frontend/transport/handler.go
Add the following fields to the query request log in query-frontend
- query_length
- user_agent
- accept_encoding
**Checklist**
=> Add more fields to query request log in query frontend

integration/query_fuzz_test.go
After upgrading prometheus version to v3.1.0, the behavior of `stdvar` and `stddev` has been changed due to this [PR](https://github.com/prometheus/prometheus/pull/14941).
In the Cortex e2e test, some tests compare query results between the old cortex and the new cortex version.
These tests are failing for the query which contains `stdvar` and `stddev`.
This PR adds flags for addressing these cases.
**Checklist**
=> Add skip std aggregations flag

integration/query_fuzz_test.go
This PR changes latest prometheus image in the `query_fuzz_test.go`.
**Checklist**
=> Change latest prometheus image (v3.2.1) in fuzz test

pkg/alertmanager/alertmanager.go
This PR fixes an error handling of the `ApplyConfig` function in the Alertmanager.
**Checklist**
=> Fix Alertmanager ApplyConfig func error handling

README.md
**What this PR does**: Include KubeCon London Talks 2025
**Checklist**
=> Include KubeCon London Talks 2025

go.mod, vendor/modules.txt
**What this PR does**: Updates Prometheus to latest
**Checklist**
=> Update prometheus to c3ce1f1

.github/workflows/scripts/install-docker.sh
This PR upgrades the Docker image to fix the CI test issue.
**Checklist**
=> upgrade docker image

build-image/Dockerfile
Upgrade the `golangci-linter` image to v2.1.6.
**Checklist**
=> Upgrade golangci linter image

.golangci.yml, pkg/ruler/storage.go
This PR deletes dead code at the `NewRuleStore`.
**Checklist**
=> chore: Delete dead code at ruler storage

build-image/Dockerfile
**What this PR does**: Update go to 1.24.3
**Checklist**
=> Update go to 1.24.3

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/resource_based_limiter_test.go, pkg/configs/resource_monitor.go, pkg/cortex/cortex.go, pkg/cortex/cortex_test.go, pkg/cortex/modules.go, pkg/cortex/modules_test.go, pkg/util/resource/monitor.go, pkg/util/resource/monitor_test.go
Updating config for resource monitor as follows:
```
resource_monitor:
resources: cpu,heap
interval: 100ms
cpu_rate_interval: 1m
```
n/a
**Checklist**
=> ResourceMonitor: Change configs

pkg/parquetconverter/converter.go
Fix a typo in the log message. 
**Checklist**
=> chore: fix typo at parquet converter

pkg/compactor/partition_compaction_grouper_test.go, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/ring/mock.go, pkg/ring/util_test.go
remove duplicate RingMock for unittest
**Checklist**
=> remove duplicate RingMock

go.mod, go.sum, vendor/github.com/prometheus-community/parquet-common/convert/convert.go, vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/search/rowrange.go, vendor/modules.txt
Update parquet common library to latest main. It mainly pulls https://github.com/prometheus-community/parquet-common/pull/86 and https://github.com/prometheus-community/parquet-common/pull/85.
https://github.com/cortexproject/cortex/pull/6879 might take longer to be merged due to correctness issue. To unblock other changes from the parquet library, create this PR to bump its version.
**Checklist**
=> Update parquet common to latest main

README.md
- **Hyphenation consistency**: Made sure "long-term" is consistently hyphenated throughout
- **Article usage**: Corrected the use of "the" before abbreviations where it wasn't needed
- **Completeness**: Added missing words to make sentences grammatically complete
=> docs: fix typos in main README.md

Makefile
This PR deletes unused proto-gen scripts.
**Checklist**
=> Delete unused proto gen script

ADOPTERS.md
=> docs: Add Open-Xchange to ADOPTERS.md

CHANGELOG.md
=> reoder changelog

pkg/engine/engine.go
Instead of redefining `promql.QueryEngine` interface in our own query engine interface, simply embed it.
**Checklist**
=> chore: Embed promql.QueryEngine interface

ADOPTERS.md
Twilio uses Cortex!
Adds Twilio to the list of Cortex adopters.
CHANGELOG was not updated as this is not a code change.
=> Add Twilio to list of adopters

.golangci.yml, Makefile
A new `integration_remote_write_v2` has been introduced at #6330; this PR adds it to `build-tags`.
**Checklist**
=> Add integration_remote_write_v2 to build-tags

pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Log engine type and block store headers in query stats
**Checklist**
=> Log engine type and block store headers in query stats

go.mod, go.sum, pkg/querier/parquet_queryable.go, pkg/querier/parquet_queryable_test.go, vendor/github.com/prometheus-community/parquet-common/convert/convert.go, vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go, vendor/github.com/prometheus-community/parquet-common/schema/schema.go, vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/iterators.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go, vendor/github.com/prometheus-community/parquet-common/util/fixtures.go, vendor/modules.txt
Update parquet common to pull some new improvements and fixes.
- https://github.com/prometheus-community/parquet-common/pull/101
- https://github.com/prometheus-community/parquet-common/pull/111
- https://github.com/prometheus-community/parquet-common/pull/112
- https://github.com/prometheus-community/parquet-common/pull/102
- https://github.com/prometheus-community/parquet-common/pull/113
- https://github.com/prometheus-community/parquet-common/pull/110
- https://github.com/prometheus-community/parquet-common/pull/109
- https://github.com/prometheus-community/parquet-common/pull/108
- https://github.com/prometheus-community/parquet-common/pull/105
- https://github.com/prometheus-community/parquet-common/pull/103
- …
=> Update parquet common to latest main to pull sort series fix

pkg/scheduler/fragment_table/fragment_table_test.go
After #7005 merged, I have found CI fails for modernization. The latest commits since #7005 haven’t been checked :(.
This PR applies modernization to some of the latest commits.
**Checklist**
=> chore: apply modernize for recent commits

ADOPTERS.md
=> Add Swiggy to Adopters list
