cortexproject/cortex

CHANGELOG.md, integration/backward_compatibility_test.go, integration/e2e/db/db.go, integration/e2e/service.go, integration/e2ecortex/services.go, pkg/cortex/cortex.go
**What this PR does**: This PR changes /ready endpoint to return status code 200 instead of 204. 200 is more common, and in some environments it's difficult to change the check from 200 to 204. In Kubernetes, [any code greater than or equal to 200 and less than 400 indicates success](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).
~This PR also fixes `TestBackwardCompatibilityWithChunksStorage` to start first ingester with old image. This same fix has now been posted as #2329, and I will rebase this PR when #2329 is merged.~ (Update: Rebased)
**Checklist**
=> /ready now returns 200, not 204

pkg/ingester/wal.go, pkg/ingester/wal_test.go
Due to a burst of disk writes during checkpoint, we were facing some heavy disk I/O throttling. This has a big effect on ingestion latency as we write to WAL (north of 60s in worst cases for around 500k series). Hence spread the writing of checkpoint to the entire checkpoint duration.
=> Spread checkpoint writing

pkg/chunk/fixtures.go, pkg/chunk/schema_config.go, pkg/chunk/schema_config_test.go
This fixes a bug where the default shard factors were not set properly on `PeriodConfigs`. It caused us to never update the period config’s shard factor (although the derived Schema, which is used in the store, has the default shard values applied — 16 starting in v10+).
I introduced this bug while addressing the following:
https://github.com/cortexproject/cortex/pull/1878#discussion_r363884225
**Discovery**
We discovered this bug when we tried to enable `querier.parallelise-shardable-queries`. It effectively turned that code path into a no-op because it didn't register any shard-able `PeriodConfigs` (we don't specify overrides and use the derived default).
**The Fix**
- Introduces a `func (cfg *PeriodConfig) applyDefaults()` function which mutates the associated …
=> enforce sharding defaults in period configs

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/cortex.yaml, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, docs/configuration/single-process-config.yaml, integration/configs.go, pkg/alertmanager/multitenant.go, pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/aws/metrics_autoscaling.go, pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/storage/factory.go, pkg/configs/client/client.go, pkg/ingester/ingester.go, pkg/querier/frontend/frontend.go, pkg/querier/frontend/worker.go, pkg/querier/querier.go, pkg/ring/kv/consul/client.go, pkg/ruler/ruler.go, pkg/util/backoff.go
=> Saner and consistent YAML fields in config

CHANGELOG.md, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/configuration/single-process-config-blocks.yaml, docs/configuration/single-process-config.md, docs/configuration/single-process-config.yaml, docs/guides/cortex-with-cassandra.md, k8s/ingester-dep.yaml, pkg/chunk/aws/metrics_autoscaling.go, pkg/chunk/chunk_store.go, pkg/distributor/distributor.go, pkg/ring/lifecycler.go
=> Remove deprecated flags from months ago

CHANGELOG.md, pkg/util/validation/validate.go
When enabled, in the distributors, we consider metrics with an invalid
metric name a failure and discard the corresponding sample. When it
happens for this reason, the discarded samples metric appears to not be
incremented.
This commit fixes that by incrementing the counter.
**Checklist**
=> Increment discarded samples for invalid metric names

CHANGELOG.md, pkg/chunk/table_manager.go
I've noticed that a couple of table-manager metrics have the `cortex_dynamo` prefix. I'm proposing to rename them to the `cortex_table_manager` prefix for clarity.
N/A
**Checklist**
=> Renamed table-manager metrics to remove cortex_dynamo prefix

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
This PR changes error checks to unwrap the error first. It also adds timestamp to the log message to provide more details when debugging problems.
**Checklist**
=> TSDB soft errors: check original error

integration/backward_compatibility_test.go, pkg/ring/ring.go
=> Fix pushes when ingesters don't have a zone.

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, docs/guides/running.md, integration/ingester_hand_over_test.go, pkg/chunk/cache/memcached.go, pkg/chunk/cache/memcached_client.go, pkg/distributor/distributor_test.go, pkg/ingester/client/pool.go, pkg/ingester/ingester.go, pkg/querier/querier.go, pkg/ring/kv/consul/client.go, pkg/ring/lifecycler.go
=> Saner defaults for configs

docs/configuration/schema-config-reference.md, docs/configuration/single-process-config.md, docs/configuration/v1-guarantees.md
=> Document the v1.x guarantees

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/backward_compatibility_test.go, integration/configs.go, pkg/chunk/table_manager.go
Fixes https://github.com/cortexproject/cortex/issues/2254
**Checklist**
=> Rename rest of the dynamodb flags

CHANGELOG.md, pkg/ingester/ingester_test.go, pkg/ingester/lifecycle_test.go, pkg/ingester/transfer.go, pkg/ingester/user_state.go, pkg/ingester/user_state_test.go, pkg/ingester/wal_test.go
This PR ensures the UserState metrics are updated if a transfer fails. A `teardown` function is added to the `userState` struct and it is called if a transfer fails.
Fixes #2337 
**Checklist**
=> Update metrics if transfer fails

docs/configuration/v1-guarantees.md
=> Reduce the headings in v1-guarantees from H1 to H2

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/series.go
**What this PR does**: This PR adds tracking of samples ingestion errors. It reuses existing `cortex_discarded_samples_total` metric, and reuses `out-of-bounds, new-value-for-timestamp, sample-out-of-order` reasons.
**Checklist**
=> TSDB: Metrics for discarded samples (soft errors)

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/cortex.yaml, pkg/querier/block_store.go, pkg/querier/block_store_metrics.go, pkg/querier/blocks_meta_fetcher_metrics.go, pkg/querier/blocks_meta_fetcher_metrics_test.go, pkg/querier/bucket_store_metrics_test.go
In this PR I'm decoupling blocks meta fetcher metrics mapping from bucket store metrics, as preliminary refactoring required by the on-going work to introduce the `store-gateway` service (because in the near future the querier will not run the bucket store anymore).
I've also took the chance to rename metrics to remove the `_bucket_store` portion from meta fetcher metrics, for the same reason.
N/A
**Checklist**
=> Decouple blocks meta fetcher metrics mapping from bucket store metrics

pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/cassandra/storage_client.go, pkg/chunk/gcp/bigtable_index_client.go
Implement the `Delete` methods for all the `IndexClient`s. As of now `Delete` methods are used by Purger which does the deletion of data requested by the users.
=> add delete index support for dynamodb, cassandra and bigtable

docs/operations/blocks-storage.md, docs/operations/blocks-storage.template
I've documented the known issue related to the issue #2366.
N/A
**Checklist**
=> Documented blocks storage limitation

pkg/chunk/chunk_store.go, pkg/chunk/storage/caching_index_client.go
It seems we are not calling `Stop` method on `IndexClient` while stopping the store.
This PR fixes that.
=> stop index client while stopping store

pkg/ingester/ingester_v2.go
Adds a histogram to record tsdb replay timings.
**Checklist**
=> tsdb: record a histogram of replay tsdb times

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
This commit changes which error we return on validation back to the
clients (Prometheus or Distributors).
The samples that do not pass validation at distributors and/or ingesters
now return the first validation error as opposed to the last.
Abstract from a conversation in #2336 
**Checklist**
=> Return first validation error on sample ingestion

pkg/querier/blocks_scanner.go, pkg/querier/blocks_scanner_test.go
According to the blocks sharding proposal, the querier needs to be able to scan the bucket to find blocks for a given user and time range. In this PR I'm introducing the `BlocksScanner` which periodically scans the bucket looking for new/deleted users/blocks and exposes a `GetBlocks()` function to find blocks.
Notes:
- I plan to work on the TODOs in `createMetaFetcher()` in a later stage
- The `BlocksScannerConfig` may be subject to change, based on the final design once we'll integrate the scanner
N/A
**Checklist**
=> Introduce BlocksScanner

CHANGELOG.md, pkg/querier/blocks_meta_fetcher_metrics.go, pkg/querier/blocks_meta_fetcher_metrics_test.go
**What this PR does**: this PR exposes `blocks_meta_synced` metric from Thanos meta fetcher component as `cortex_querier_blocks_meta_synced`.  In Cortex, this metric reflects current state of synced blocks over all tenants.
**Checklist**
=> Expose blocks_meta_synced metric.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
**What this PR does**: This PR adds `cortex_distributor_latest_seen_sample_timestamp_seconds` with latest timestamp of sample sent to Cortex. Useful for tracking how far behind prometheus servers are from Cortex point of view.
**Checklist**
=> Added cortex_distributor_latest_ingested_sample_timestamp_seconds metric

CHANGELOG.md
**What this PR does**: This PR moves changelog entry for https://github.com/cortexproject/cortex/pull/2319 to `master` section.
**Checklist**
=> Moved changelog entry to correct place.

CHANGELOG.md, pkg/querier/blocks_bucket_store_inmemory_server.go
In the PR #2324 I've introduced a severe issue affecting the blocks storage which cause corrupted chunk data when querying back series using the blocks storage. In this PR I'm picking the safest approach and copying the entire Series response.
The reason why I've not done any optimisation to reduce memory allocations is:
1. It's not worse than the state before PR #2324
2. The `store-gateway` (which we expect to merge in the next few weeks) will remove `bucketStoreSeriesServer` at all
Fixes #2396
**Checklist**
=> Fixed chunk data corruption when querying back series using the blocks storage

CHANGELOG.md, pkg/querier/block.go
While working on the fix for #2396 I've realised Cortex was returning `422` status code on error while iterating chunks. This PR fixes it, considering it a storage error, which leads to Prometheus engine returning `500` (manually tested).
N/A
**Checklist**
=> Fixed response status code while iterating chunks in the blocks storage

pkg/cortex/cortex.go, pkg/cortex/health_check.go, pkg/cortex/health_check_test.go, pkg/cortex/modules.go, pkg/ingester/ingester.go
In order to build the `store-gateway` service ([proposal](https://cortexmetrics.io/docs/proposals/blocks-storage-sharding/)), I would need to be able to do gRPC health checks against the `store-gateway` when running in microservices mode. However, the gRPC health check service is currently registered by the ingester so can't be also registered in other places (otherwise it clashes).
Given the `Ingester.Check()` implementation is not ingester-specific (it just checks if the ingester service is running/stopping), in this PR I'm proposing to generalise the gRPC health check service registration and mark the Cortex instance as healthy once all services are running, making it consistent with the `/ready` endpoint.
Notes:
- ~~`services.Manager.IsHealthy()` returns true …
=> Decouple gRPC health check service from ingesters

pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go
I was reading this code and realize that #1974 missed a place where we also query downstream for partial result in case of partial cache hit.
I've chatted about this with on Thanos dev and suggested to send a fix for them.
/cc @GiedriusS 
=> Handle cache-control headers also during a partial cache hit.

pkg/chunk/local/fs_object_client.go, pkg/chunk/storage/factory.go
We already implement `ObjectClient` for various storages but `NewObjectClient` was allowing them all. This PR adds support for them.
It also adds a call to `File.Flush` method in `PutObject` method of filesystem type to make it flush the file to disk immediately.
=> add support for creating more ObjectClient types and flush file immediately for filesystem type

pkg/querier/block_store.go, pkg/querier/block_store_metrics.go, pkg/querier/bucket_store_metrics_test.go
The upcoming `store-gateway` will internally run the `BucketStore` and, at some point, the querier will not run the `BucketStore` anymore (in favour of the `store-gateway`). While developing the `store-gateway`, `BucketStore` will co-exist both in the querier and store-gateway. Because of this, I would like to expose the `BucketStoreMetrics` from the querier so that the store-gateway can use them instead of duplicating code (the `BucketStoreMetrics` will be moved to the `storegateway` pkg once the querier will not run the `BucketStore` anymore).
N/A
**Checklist**
=> Expose BucketStoreMetrics for store-gateway too

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/compactor/compactor.go, pkg/storage/tsdb/config.go
**What this PR does**: this PR modifies default values related to delayed deletes in experimental blocks support. Current defaults are too high and lead to too many storage operations, especially in clusters with more users (see also https://github.com/thanos-io/thanos/issues/2389)
**Checklist**
=> Modify default values for deletion delays.

docs/proposals/api_design.md, docs/proposals/receiving_metadata.md
This PR adds an initial draft of a proposal to restructure and version the Cortex API.
=> API Design Proposal

CHANGELOG.md, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go
**What this PR does**: Corrects a bug reported by @pracucci when upgrading ingesters from pre-1.0, which causes the new ingesters to have their availability zone string overwritten by a blank value. This PR addresses the issue by having the ingesters update the ring data with their zone on every heartbeat, similar to what they do with address information.
Fixes #2401 
**Checklist**
- [ x ] Tests updated
- [ X ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> BugFix: 1.0 Ingesters having availability zone value erased by pre-1.0 ingesters during rolling upgrade.

pkg/ring/basic_lifecycler.go, pkg/ring/basic_lifecycler_delegates.go, pkg/ring/basic_lifecycler_delegates_test.go, pkg/ring/basic_lifecycler_metrics.go, pkg/ring/basic_lifecycler_test.go, pkg/ring/model.go, pkg/ring/tokens.go, pkg/ring/tokens_test.go
The upcoming `store-gateway` ([proposal](https://cortexmetrics.io/docs/proposals/blocks-storage-sharding/)) will use the ring as the foundation for the sharding.
However, the `store-gateway` ring lifecycle will be different than the ingesters one and unfortunately the current `ring.Lifecycler` logic doesn't fit (ie. we need to inject `store-gateway` custom logic between `JOINING` and `ACTIVE` state while continuing doing heatbeats, or we need a new `store-gateway` instance to always reset its state to `JOINING` even if already present within the ring).
I initially tried to change `ring.Lifecycler` to also add `store-gateway` use cases but I ended up with many hacks I wasn't comfortable with. This lead me to approach a different solution: build a ring lifecycler …
=> Introduced BasicLifecycler

pkg/ingester/ingester.go
Transfers are disabled with WAL, hence no need to wait for transfers. Makes restarts faster.
=> Set JoinAfter to 0 if WAL is enabled

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go
Previously, we had samples and metadata using the ring on their own to
send data to the ingesters. Since the `WriteRequest` supports metadata
alongside samples there's no reason to split the calls so we unify them. There's an
additional tiny refactor to inline the metadata validation as it is just
a single function call.
A follow up from #2336 
**Checklist**
=> Refactor: Unify metadata and samples sends to ingesters

pkg/querier/frontend/frontend.go, pkg/querier/frontend/queue_test.go
Small simplification to the logic in `getNextRequest` on the query frontend.  Maps are already returned in a random order when ranged over.  Removed code that attempted to pick a random spot in the map of queues to reduce code complexity.
It should be noted that the current code already relies upon the map range behavior in go.  Otherwise the first queue in the map would be underserviced.
=> Small logic simplification on the query-frontend

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/compat.go, pkg/ruler/ruler.go
This PR gives the operator the option to add an evaluation delay interval to the Ruler. This can be configured to ensure the ruler does not evaluate rules before the data required for the evaluation of those rules is written to Cortex.
Fixes #1723
**Checklist**
=> Configurable delay on rule evaluation

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, docs/production/ingesters-with-wal.md, pkg/ingester/wal.go
There is no mechanism to delete the old WAL yet if checkpoint is disabled. It should be clearly stated for `-ingester.checkpoint-enabled` so that it is not set to `false` for production or extended dev usage.
=> Enable WAL checkpoint by default

integration/kv_test.go, pkg/ring/kv/consul/mock.go, pkg/ring/kv/kv_test.go
Using List on the inmemory KV store always silently failed because the Consul WaitTime is always zero, which the mock implementation treated as already past the deadline.
Signed-off-by: Robert Fratto <robert.fratto@grafana.com>
/cc @pstibrany
=> Fix List in mock consul

pkg/api/api.go
This exports the register functions used by the API to register routes in Cortex. It makes the API struct a bit more flexible and allows external packages to register additional routes.
=> Export api register functions

pkg/cortex/cortex.go, pkg/util/grpc/healthcheck/health_check.go, pkg/util/grpc/healthcheck/health_check_test.go
In order to reduce the amount of code in `pkg/cortex` I moved the healthCheck grpc handler into a separate package located at `pkg/utils/grpc/healthcheck`. I think this makes sense since it has not dependencies on anything else in the `pkg/cortex` package and could be useful for anyone trying to utilize the `pkg/utils/services package`.
=> Move GRPC health check to separate package

pkg/querier/blocks_bucket_stores_service.go, pkg/querier/blocks_bucket_stores_service_test.go, pkg/querier/blocks_scanner.go, pkg/storegateway/bucket_store_inmemory_server.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/metadata_fetcher_metrics.go, pkg/storegateway/metadata_fetcher_metrics_test.go
As part of the work I'm doing on the `store-gateway`, for a while we'll have both the querier and `store-gateway` synching blocks (at the end, only the `store-gateway` will do). Currently the shared bucket store logic is in `pkg/querier` while we should transition to move all such logic to `pkg/storegateway`.
Conceptually (and also practically to avoid circular dependencies) the querier depends on the store-gateway but not viceversa, so in this PR I'm removing any `pkg/querier` dependency from `pkg/storegateway` moving the shared logic from the querier to the store-gateway (which is where it should live anyway once the querier will not sync blocks anymore).
N/A
**Checklist**
=> Removed querier dependency from storegateway pkg

pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_utils.go, pkg/chunk/composite_store.go, pkg/chunk/schema.go, pkg/chunk/schema_caching.go, pkg/chunk/schema_caching_test.go, pkg/chunk/schema_config.go, pkg/chunk/schema_test.go, pkg/chunk/series_store.go, pkg/chunk/storage/factory_test.go
While studying how schemas work, I've found some oddities, that this PR tries to address.
- some entries implementations having many methods that only returned "not supported" errors
- `seriesStore` embedding `store` to reuse some of the methods
- `Schema` having methods for supporting different stores
This PR splits `Schema` interface (and then also `entries`) into `StoreSchema` and `SeriesStoreSchema` plus shared `BaseSchema` supertype.
Similarly, `baseStore` was extracted from `store`, and `seriesStore` now uses that, instead of store directly.
This makes code more explicit about what is used where, or why some methods are not implemented in various schema / entries versions.
(I haven't reordered methods for to keep `baseStore` and `store` methods together, as that would increase diff …
=> Refactor Schema to make code more explicit about interface usage

.circleci/config.yml, CHANGELOG.md, Makefile, RELEASE.md, VENDORED_CODE.md, docs/case-studies/gojek.md, docs/configuration/arguments.md, docs/configuration/schema-config-reference.md, docs/configuration/single-process-config.md, docs/configuration/v1-guarantees.md, docs/contributing/how-to-upgrade-golang-version.md, docs/getting-started/getting-started-with-gossip-ring.md, docs/guides/sharded_ruler.md, docs/operations/query-tee.md, docs/proposals/api_design.md, docs/proposals/receiving_metadata.md, pkg/util/services/README.md, tools/cleanup-white-noise.sh
Sometimes we do receive PRs from people which (correctly) configure automatic trailing whitespaces removal in the IDE/text editor (ie. CHANGELOG edits in #2440).
I would suggest to solve this problem once and for all, forcing any PR to have no trailing whitespaces in markdown. In this PR I've added a linter check and a quick way to fix it (`make clean-white-noise`). I inherited the script from our Thanos friends ❤️ .
/cc @cyriltovena 
N/A
**Checklist**
=> Cleanup white noise in Markdown files

docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, tools/doc-generator/writer.go
This is something I wanted to work on since when I've introduced the config file reference generator and I never had time to do it.
The duration in the config is expressed at the `time.Duration` stringify, including unnecessary trailing `0m0s` or `0s`. In this PR I clean it up.
N/A
**Checklist**
=> Cleanup duration defaults in the generated config doc

docs/configuration/prometheus-frontend.md, docs/configuration/prometheus-frontend.yml
**What this PR does**: 
updating prometheus-frontend sample yaml to work with cortex v1.0.0 :
- memcached support (for hosted memcached and managed memcache)
- replacing deprecated field : split_queries_by_day
Document change to reflect the latest cortex version(v1.0.0)
**Checklist**
- [ X] Documentation added
=> updating prometheus-frontend sample yaml doc

pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go
The upcoming `store-gateway` will need a replication strategy different than the ingesters one. In this PR I've refactored the ring, extracting the replication strategy into an interface which can be plugged via `ring.NewWithStoreClientAndStrategy()` (this function is still unused, but will be used in a subsequent PR).
N/A
**Checklist**
=> Allow custom replication strategy in the Ring

pkg/chunk/composite_store.go, pkg/chunk/schema_config.go, pkg/chunk/schema_test.go
**What this PR does**: This simple refactoring PR moves schema validation code into `CreateSchema`, to keep schema-specific logic at one place only.
=> Move validation code into schema creation

pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/user_state.go
Hello everyone 👋,
As part of #2459, I plan to introduce ingester limits for Metadata. Instead of creating a new struct with similar attributes for limiting metadata, I thought about just changing the name of the current one to re-use it. Thus, this PR renames `SeriesLimiter` to `Limiter`.
How do maintainers feel about this?
The filename is already accurate, I see no tests that might need updating, and I don't think this is something we should add to the changelog but feel free to let me know if otherwise. I'll be happy to amend.
=> Rename ingester.SeriesLimiter to ingester.Limiter

CHANGELOG.md, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/composite_store.go, pkg/chunk/opts.go, pkg/chunk/opts_test.go, pkg/chunk/series_store.go
This PR implements "regex set" optimization when querying chunks in index. If label matcher is in form label=~"a|b", then we can simply query index for label=a, label=b. This reduces number of fetched chunk IDs and matching we need to do in memory. (This is similar optimization to what Prometheus has in TSDB layer)
**Checklist**
/cc @codesome
=> Regex set optimization when querying for chunks in index

.circleci/config.yml, go.mod, go.sum, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_scanner.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/user_bucket_client.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/metadata_fetcher_metrics.go, vendor/github.com/thanos-io/thanos/pkg/block/block.go, vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/json_reader.go, vendor/github.com/thanos-io/thanos/pkg/block/metadata/deletionmark.go, vendor/github.com/thanos-io/thanos/pkg/compact/blocks_cleaner.go, vendor/github.com/thanos-io/thanos/pkg/compact/clean.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/compact/retention.go, vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go, vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go, vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go, vendor/github.com/thanos-io/thanos/pkg/objstore/testing.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/postings_codec.go, vendor/github.com/thanos-io/thanos/pkg/testutil/testutil.go, vendor/modules.txt
**What this PR does**: This PR updated Thanos to just-released [Thanos v0.12.0](https://github.com/thanos-io/thanos/releases/tag/v0.12.0).
Note: `UserBucketClient` struct was split into `UserBucketReaderClient` and `UserBucketClient`. Reason is that new `ReaderWithExpectedErrs` method returns `BucketReader`, while `UserBucketClient` works with "full" `Bucket` only.
**Checklist**
=> Update Thanos to v0.12.0.

docs/production/caching.md
The documentation for the Query Results Cache was a bit outdated as it was pointing to an incorrect -frontend.cache prefix. I was unable to get the caching work without additional help. This change contains all the info to get the query result cache working.
Signed-off-by: Juho Makinen <juho.makinen@gmail.com>
=> Document Query Results Cache options in caching.md

CHANGELOG.md, pkg/distributor/distributor.go, pkg/ruler/compat.go, pkg/util/push/push.go, pkg/util/push/push_test.go
* Distributor: `/all_user_stats` now show API and Rule Ingest Rate correctly.
Fixes #2171
**Checklist**
=> Distributor: /all_user_stats now show API and Rule Ingest Rate correctly

pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go
While working on the `store-gateway` I found two issues related to the ring metrics:
1. `oldestTimestampDesc` was not included in the `Describe()`: fixed
2. It's not possible to export metrics from two different ring client instances because of clashing metrics: fixed moving the `name` label as a constant label instead of a dynamic one (constant labels are taken in account when building the desc ID, so solving the issue)
N/A
**Checklist**
=> Fixed ring metrics collection

docs/configuration/arguments.md
Signed-off-by: Yannick Kint <yannickkint@gmail.com>
Small documentation change to make it more clear that when using the "distributor.shard-by-all-labels" flag, this should be set on both the distributor and the querier.
=> Clarify documentation about distributor.shard-by-all-labels flag

CHANGELOG.md, pkg/chunk/chunk_store.go, pkg/chunk/opts.go, pkg/chunk/opts_test.go, pkg/ingester/index/index.go, pkg/ingester/index/index_test.go
Similar to https://github.com/cortexproject/cortex/pull/2446/
Super useful for templated grafana dashboards which send matchers such
as =~"a|b|c|d|e"
Fixes #1993 
**Checklist**
=> Regex set optimisation when looking series in ingester

CHANGELOG.md, Makefile, cmd/cortex/main.go
**What this PR does**: Adds the version,branch,revision to the build args, so that `cortex_build_info` correctly populates the version number.
Fixes #1709 
`cortex_build_info{branch="build-info-version",goversion="go1.13.3",revision="ca93c1b87",version="1.0.0"} 1`
**Checklist**
=> include Cortex version in cortex_build_info

CHANGELOG.md, integration/chunks_storage_backends_test.go, integration/query_frontend_test.go, pkg/chunk/chunk_store.go, pkg/chunk/storage/factory.go, pkg/chunk/storage/factory_test.go, pkg/chunk/storage/metrics.go, pkg/cortex/modules.go, pkg/ingester/flush.go, pkg/ingester/metrics.go, pkg/querier/querier.go, pkg/querier/queryrange/roundtrip.go
More will be added once the following is merged:
https://github.com/prometheus/prometheus/pull/6890
The idea is that we now have a ton of QPS and we don't know which tenants are using queries more than others. We want to add the samples/chunks loaded metrics as well so that we can come up with fair usage policy on the read path.
Ideally we'd add latency metrics as well, but the cardinality is just too much.
=> Add initial per tenant query and chunk metrics AND RENAME SOME EXISTING METRICS

CHANGELOG.md, pkg/querier/frontend/frontend.go
The feature of query-frontend to log slower queries is already amazing
but we can make it even better by logging the POST body as well. It is
not uncommon nowadays to use POST with the Prometheus API. All of the
data that is passed via POST is not visible via the URL. Thus, let's
also print the POST data if it is available.
Small testing shows that the message now looks like the following:
```
level=info ts=2020-04-17T16:34:51.200200445Z caller=frontend.go:174 msg="slow query" org_id=fake url=http://localhost:9009/api/prom/api/v1/query_range time_taken=1.638201ms body="end=1587141285&query=prometheus_http_requests_total&start=1587140385&step=15"
```
Signed-off-by: Giedrius Statkevičius <giedriuswork@gmail.com>
=> frontend: also log the POST data of long queries

CHANGELOG.md, pkg/querier/frontend/frontend.go
It fixes bug where query frontend ignores an error in HTTP handler and reports incorrect status code
Fixes #2482
**Checklist**
- [ x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> QueryFrontend sets incorrect status code on HTTP timeout

.golangci.yml, Makefile, integration/api_ruler_test.go, integration/asserts.go, integration/kv_test.go
While reviewing the `golangci-lint` config I've realized two things fixed in this PR:
1. It's configured via a mix of CLI flags and config file (moved everything to config file)
2. The `require_docker` build tags is wrong: should be `requires_docker`
N/A
**Checklist**
=> Cleanup and fix golangci-lint config

Makefile
While reviewing the PR #2220 I've seen that in a while was used `golang.org/x/net/context` instead of `context`. For recent versions of Go, `golang.org/x/net/context` is just a wrapper over `context` and I think we should check it with the linter.
N/A
**Checklist**
=> Added lint check to disallow golang.org/x/net/context

pkg/distributor/ingester_client_pool.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/store_gateway_client.go, pkg/ring/client/pool.go, pkg/ring/client/pool_test.go, pkg/ring/client/ring_service_discovery.go, pkg/ring/client/ring_service_discovery_test.go
While working on #2469, I received [this feedback](https://github.com/cortexproject/cortex/pull/2469#discussion_r410044504) from @pstibrany:
> I think we missed an opportunity here... client.Pool should not depend on ring. It only needs a function to get a list of all clients. (New PR)
In this PR I'm proposing a refactoring to decouple the client `Pool` from the `ReadRing`, just taking in input a function to run the service discovery.
N/A
**Checklist**
=> Refactored gRPC clients pool to not depend on ReadRing

pkg/compactor/compactor_ring.go, pkg/compactor/compactor_ring_test.go, pkg/cortex/modules.go, pkg/distributor/distributor_ring.go, pkg/distributor/distributor_ring_test.go, pkg/ingester/lifecycle_test.go, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go, pkg/ruler/ruler_ring.go
Looking at the current state of the code (including Loki) I can't see a good reason why `LifecyclerConfig.ListenPort` should be a pointer instead of `int`. In this PR I'm proposing to switch it to `int` to cleanup the config.
N/A
**Checklist**
=> Change LifecyclerConfig.ListenPort from pointer to int

pkg/chunk/aws/s3_storage_client.go, pkg/chunk/azure/blob_storage_client.go, pkg/chunk/gcp/gcs_object_client.go, pkg/chunk/inmemory_storage_client.go, pkg/chunk/local/fs_object_client.go, pkg/chunk/local/fs_object_client_test.go, pkg/chunk/purger/purger_test.go, pkg/chunk/storage_client.go, pkg/ruler/rules/objectclient/rule_store.go
Adds list of directories(synthetic directories in object stores like S3, GCS and Azure) in the response from List calls to `chunk.ObjectStore`.
This would be helpful in custom `TableClient` that I need to implement in Loki for BoltDB Shipper.
It would be used in `TableClient.ListTables` call for listing all the directories that are there in the store.
**Checklist**
=> return directories in respose from List calls to object stores

CHANGELOG.md, pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/cassandra/storage_client.go, pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/local/boltdb_index_client.go, pkg/chunk/util/util.go
The single query case is very common, e.g. for series-to-chunks lookup in schema v9.
[EDIT: is it? I may be confused about that]
Shortcutting it avoids the creation of two goroutines and associated data structures, and removes an uninteresting tracing span.
Before that, small refactor to make the code overall a bit simpler.
**Checklist**
=> Shortcut DoParallelQueries for single-query case

CHANGELOG.md, pkg/chunk/series_store.go
Signed-off-by: Ed Welch <edward.welch@grafana.com>
At the moment it's a bit tricky to understand how effectively chunks are being de-duplicated at the store with the cache based de-dupe code.
This PR adds a counter which explicitly increments when a chunk was not stored because it was already in the cache.  
This can be combined with `cortex_ingester_flush_reasons` to get a ratio of chunks flushed vs deduped to better tell how well the de-duplication is working.
**Checklist**
=> Add a counter to track chunks which were de-duplicated at store time.

CHANGELOG.md, pkg/ingester/wal.go
These metrics are very useful in resource estimations and WAL in general.
**Checklist**
=> Add metric for bytes logged in WAL and Checkpoints

CHANGELOG.md, pkg/distributor/distributor_test.go, pkg/ring/kv/consul/client.go, pkg/ring/kv/consul/client_test.go, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/util/test/poll.go
- Use a real ring with mock KV when testing distributor.  This is to tease out errors in the replication logic.
- Extend the distributor tests to cover the case of RF=3 with 2 ingesters.
- Fix ring.GetAll to correctly calculate maxErrors when RF=3 and 2 ingesters.
Fixes #2504
**Checklist**
=> Ensure queries return correctly during rolling upgrades of stateful cluster with RF 3 and only 3 nodes.

docs/production/ingesters-with-wal.md
This is will greatly in planning out the disk space requirement for WAL. The numbers would change a little with https://github.com/cortexproject/cortex/pull/2436, which I will take care in that PR.
/cc @tomwilkie
=> Add disk space requirement in WAL doc

CHANGELOG.md, pkg/util/log.go
This change the behaviour of the context logger, there is situation where we don't have an org_id and we would still want to log with the spanID.
I'm also renaming `span_id` to `spanID` because we have inconsistency  with weaveworks server which uses `spanID`. Wasn't sure if this would be welcomed change in weaveworks but I'm can send the PR there.
=> Add traceID if possible when using context logger.

development/tsdb-blocks-storage-s3-single-binary/compose-up.sh, development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml, development/tsdb-blocks-storage-s3/compose-up.sh, development/tsdb-blocks-storage-s3/docker-compose.yml, pkg/api/api.go
Returns the weaveworks/common server instead of the router. This restores the usage of weaveworks standard middleware/instrumentation in the querier.
Fixes #2507
**Checklist**
=> Querier Metrics Fix

pkg/util/spanlogger/spanlogger.go
I made this function a while ago to avoid creating a span but still keep logging to a span.
However I just realized this won't log the org id nor the trace id as the original SpanLogger.New
=> Fix logger context when creating a spanLogger from context.

CHANGELOG.md, pkg/querier/frontend/frontend.go
This will help for the log to be more readable, parsable. I've also added the traceID using the context logger.
=> Improve the frontend slow query logs.

pkg/compactor/compactor_test.go, pkg/distributor/distributor.go, pkg/distributor/query.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/client/ring_service_discovery.go, pkg/ring/client/ring_service_discovery_test.go, pkg/ring/model.go, pkg/ring/model_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ruler/ruler.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go, pkg/storegateway/gateway_test.go
When I've implemented the blocks sharding and replication in the store-gateway I was aware of an issue with the "ring topology change detection": the resync wasn't guaranteed to trigger when an instance change state (ie. JOINING -> ACTIVE).
In this PR I've fixed it following a different approach. I use `ring.GetAll()` to get a snapshot of the ring for a given operation (now configurable) and then I compare it with the last known snapshot.
N/A
**Checklist**
=> Fixed ring topology change detection in store-gateway

development/tsdb-blocks-storage-s3/config/cortex.yaml, pkg/ring/basic_lifecycler.go, pkg/ring/basic_lifecycler_delegates.go, pkg/ring/basic_lifecycler_delegates_test.go, pkg/ring/basic_lifecycler_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go
In this PR I've introduced the support to auto-forget a store-gateway instance in the ring, 10x after the heartbeat timeout period is expired.
N/A
**Checklist**
=> Added auto-forget to store-gateway ring instances

docs/proposals/version-documentation.md
Let's start a discussion about how to version documenation.
I have listed a few tools that can be used with their respective
pros and cons.
**Checklist**
=> Proposal: Versioning of Documentation

docs/architecture.md
Fix a typo in the architecture doc
=> Fix a typo in architecture doc

README.md
Closes #2529:
> Hi there! I wanted to propose adding the following badge to the README to indicate how many 
> TODO comments are in this codebase:
> 
> [![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/cortexproject/cortex)](https://www.tickgit.com/browse?repo=github.com/cortexproject/cortex)
> 
> The badge links to tickgit.com which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.
> 
> Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!
> 
> (full disclosure, I am the creator/maintainer of tickgit) …
=> Add TODOs badge to README

pkg/ingester/transfer.go, pkg/ingester/wal.go
Improves performance of ingester handover and WAL checkpoint by
reducing garbage.
Triggered by this memory allocation profile, taken mid-transfer:
```
Total:      3.81GB     4.07GB (flat, cum) 20.56%
349            .          .           } 
350            .          .            
351            .          .           // The passed wireChunks slice is for re-use. 
352            .          .           func toWireChunks(descs []*desc, wireChunks []client.Chunk) ([]client.Chunk, error) { 
353            .          .           	if cap(wireChunks) < len(descs) { 
354         30MB       30MB           		wireChunks = make([]client.Chunk, 0, len(descs)) 
355            .          .           	} 
356            .          .           	wireChunks = wireChunks[:0] 
357            .          . …
```
=> Re-use buffers when serialising chunks.

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/chunk/cache/cache.go, pkg/chunk/cache/fifo_cache.go, pkg/chunk/cache/fifo_cache_test.go, pkg/chunk/chunk_store.go, pkg/chunk/storage/factory.go, pkg/cortex/cortex.go, pkg/querier/queryrange/roundtrip.go
Allow using human-readable memory units (MB, GiB, etc.) for `max_size_bytes` in FiFoCache config
**Checklist**
- [ x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> allow human-readable memory size in FifoCache config

pkg/chunk/local/fs_object_client.go, pkg/chunk/local/fs_object_client_test.go
When using`filesystem` as ObjectClient we will not remove the directory as well when it is the last object that is being deleted.
This PR also excludes empty directories from the listing with `List` calls.
Both these changes make `filesystem` as ObjectClient consistent with hosted object stores like S3, GCS and Azure.
Changes inspired from filesystem as object store in Thanos.
**Checklist**
=> handling of empty directories in filesystem object client

CHANGELOG.md, pkg/ruler/api_test.go, pkg/ruler/mapper.go, pkg/ruler/mapper_test.go, pkg/ruler/ruler.go, pkg/ruler/store_mock_test.go
- Ensure the Ruler can properly handle rule Namespaces with special characters. E.G. `/+<>?`
**Checklist**
=> Handle forward slashes in ruler mapper/manager

pkg/util/module_service.go
**What this PR does**: While reviewing #2542, I've realized there is a small issue in `moduleService`: it waits for other modules to stop, even if underlying service is already stopping or terminated. This PR fixes that. It doesn't change much: it will log module error earlier, and transition to Terminated/Failed state faster. More importantly, I think it makes intent of the code clearer.
**Checklist**
=> Only wait for other modules if underlying service is still running.

pkg/ingester/wal.go
* Make the spacing between 2 series writes to be 95% of what it was before. I have seen checkpoints taking 3-5% more time than the checkpoint duration, so reducing the sleep time between 2 series to have checkpoint duration around the configured one.
* Using `time.After` instead of a ticker to ensure spacing between 2 series writes, else the ticker could be holding up an additional tick (micro-opt, but it also makes the code simpler).
* Batching up the checkpoint records upto 1 MiB to reduce the disk I/Ops (main aim of this PR).
**Checklist**
=> Better spread of checkpointing

pkg/chunk/local/boltdb_index_client_test.go, pkg/chunk/local/boltdb_table_client.go, pkg/chunk/local/fixtures.go
When using boltdb for index, calling create and update table doesn't have any action and this makes logs too much verbose.
Reference: https://github.com/grafana/loki/issues/1786
**Checklist**
=> Create index table from local table client for boltdb 

CHANGELOG.md, pkg/api/api.go, pkg/distributor/distributor.go, pkg/querier/distributor_queryable_test.go, pkg/querier/metadata_handler.go, pkg/querier/metadata_handler_test.go
Properly Implements the `/api/v1/metadata` endpoint. Up until now, we were using the default behaviour introduced by the Prometheus API in:
https://github.com/cortexproject/cortex/blob/d94cdce0aa46b69fff7cb40d1ad57e77b11b4ab0/pkg/api/api.go#L253-L268
To fetch this information the dummy struct `dummy. DummyTargetRetriever` was used which meant no records where ever returned. 
The reason for this implementation is two-fold:
- Given an implemented `dummy. DummyTargetRetriever`  does not support `context` passing, we're not able to extract the tenant ID. This was fixed in upstream Prometheus by https://github.com/prometheus/prometheus/pull/7125
- We vendor Prometheus through Thanos. By the looks of it is going to take a while before we upgrade based on …
=> Implement /api/v1/metadata

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cache/redis_cache.go
I think Redis cache configuration need some more options.
I added the configuration options used by Redigo.
(reference: https://godoc.org/github.com/gomodule/redigo/redis)
- `idle_timeout`
- `wait`
- `max_conn_lifetime`
**Checklist**
=> Add Redis cache options used by Redigo

development/tsdb-blocks-storage-s3-single-binary/.dockerignore, development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml, development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml, development/tsdb-blocks-storage-s3/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3/config/prometheus.yaml, development/tsdb-blocks-storage-s3/docker-compose.yml
We've just merged #2549 from @gotjosh but I've realised there's no easy way to test metadata ingestion in the local dev env. In this PR I'm suggesting to run the Grafana Agent alongside Prometheus (series differentiated by the `origin` label) in order to have an easy way to also manually test metadata ingestion in the future.
N/A
**Checklist**
=> Run Grafana Agent in the local dev env too

pkg/chunk/schema.go
This causes tombstones to be written to Cassandra, which causes excessive heap usage.:
We write empty values (just using the row and column value) for metric name and series rows.
These empty value cause tombstones to be written to Cortex (https://thelastpickle.com/blog/2018/07/05/undetectable-tombstones-in-apache-cassandra.html).  Tombstones make Cassandra slow(er).
**Checklist**
=> Don't write empty values to the index.

docs/proposals/generalize-modules.md
This PR adds an initial draft for a design document proposing generalizing the module service. 
Part of #2291 
**Checklist**
=> Design doc - Generalize Module Service

pkg/querier/astmapper/parallel.go, pkg/querier/astmapper/parallel_test.go, pkg/querier/astmapper/shard_summer_test.go, pkg/querier/queryrange/promql_test.go, pkg/querier/queryrange/querysharding_test.go
This PR fixes and issue where the groupings of sub-aggregations can cause query correctness issues. This only occurs  within a sharded sum aggregation (via the `querier.parallelise-shardable-queries` flag). This is because aggregations expose the `by (<labels...>)` syntax. Since the sharding optimizations [alter](https://github.com/cortexproject/cortex/blob/master/pkg/querier/astmapper/shard_summer.go#L123-L171) `sum` groupings,  we must be careful not to shard in such a way that will cause non-associative series merging due to `by` groupings. For an example, please see these [two new test cases](https://github.com/cortexproject/cortex/compare/master...owen-d:sharding-subaggregations?expand=1#diff-bef1fd1e4cc0b9ab1f9c4f205d7f2ca3R242-R281) which illustrate this.
There may be further …
=> Avoid sharding sub-aggregations in `querier.parallelise-shardable-queries`

.circleci/config.yml, Makefile, build-image/Dockerfile, docs/operations/requests-mirroring-envoy.yaml, docs/operations/requests-mirroring-to-secondary-cluster.md
We've successfully setup write-path traffic mirroring with Envoy and I would like to share an example config in our documentation.
I've introduced `embedmd` to have an easy way to embed a file (or a subset of it) inside our markdown, while keeping it synched. CI will ensure doc is synced (via `make check-doc`) and contributors can run `make doc` to compile the doc.
N/A
**Checklist**
=> Documented how to mirror traffic with Envoy

pkg/storage/backend/azure/config.go, pkg/storage/backend/filesystem/config.go, pkg/storage/backend/gcs/config.go, pkg/storage/backend/s3/config.go
This PR updates all of the config structs in the `pkg/storage/backend/*` packages to have a `RegisterFlagsWithPrefix` function. This is needed to make it easier to reuse the Thanos objstore client across our stack. Will help remove some code from #2489 
Related #2262
=> add registerwithprefix function for thanos objstore configs

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/chunk/cassandra/storage_client.go, vendor/golang.org/x/sync/semaphore/semaphore.go, vendor/modules.txt
Add an option to limit concurrent queries to Cassandra, to prevent us for DOSing the underlying clusters.
**Checklist**
=> Add option to limit concurrent queries to Cassandra.

pkg/compactor/compactor_test.go, pkg/compactor/syncer_metrics.go, pkg/compactor/syncer_metrics_test.go
In this PR:
- Fixed cortex_compactor_garbage_collected_blocks_total metric help 
- Removed 'TSDB Syncer:' prefix from metrics help
N/A
**Checklist**
=> Cleanup compactor metrics description

CHANGELOG.md, pkg/querier/frontend/worker.go
Currently, the querier will crash if a particular frontend instance is unresponsive because a client is created regardless. This PR ignores frontend instances that error out on `grpc.Dial`.
NA
**Checklist**
=> Ignore frontend instance on connect error

pkg/cortex/cortex.go, pkg/cortex/cortex_test.go, pkg/cortex/modules.go, pkg/cortex/status.go
Splitting PR #2559 to make it easily reviewable.
Since we are now passing parameter-less initialisation functions to the Module Manager, variable scope is being redefined to make these components easily testable and reusable. 
Fixes - NA
**Checklist**
=> Refactor Cortex struct as part of Generalising Module Service

docs/production/storage-aws.md
Table manager can automatically add AWS tags to created DynamoDB tables.
Previously this was done using a command line argument like “-dynamodb.index-table.tag=foo=bar” but this moved onto the schema configuration in PR https://github.com/cortexproject/cortex/pull/2221
This PR updates this old reference on the cli argument.
=> Update storage-aws.md on obsolete aws tags argument.

CHANGELOG.md, docs/architecture.md, docs/configuration/v1-guarantees.md, docs/production/ingesters-with-wal.md, pkg/ingester/wal.go
Signed-off-by: Ganesh Vernekar <cs15btech11018@iith.ac.in>
We at Grafana are running WAL in production and it is stable enough to remove the experimental tag.
**Checklist**
=> Remove experimental tag on WAL

CHANGELOG.md, pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/aws/fixtures.go, pkg/chunk/aws/mock.go, pkg/chunk/aws/retryer.go, pkg/util/backoff.go, pkg/util/backoff_test.go
Call `QueryPagesWithContext()` instead of iterating through `NextPage()`.
Use AWS-SDK `Handlers` for tracing each retry and reporting errors - trace output will be different with just one span for the whole query and span-log entries for each page and retried operation.
This is less code, and more robust when retrying requests.  I strongly suspect that before this change it could get into a state on network errors where it would fail every time until the max number of retrys was hit - error message looks like:
```
level=warn ts=2020-04-10T19:30:30Z msg="DynamoDB error" retry=19 table=prod_chunk_index2_2565 err="RequestError: send request failed\ncaused by: Post https://dynamodb.us-east-1.amazonaws.com/: net/http: HTTP/1.x transport connection broken: http: …
```
=> Use newer AWS API for paginated queries

CHANGELOG.md, pkg/ingester/ingester_v2.go
We're investigating performance issues related to the blocks storage write path. In this PR I'm proposing to track the timing of TSDB `Add()` and `Commit()` for each push request.
N/A
**Checklist**
=> Track TSDB appender timing

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
We're investigating latency spikes in ingesters when running the blocks storage and we've realised we don't expose enough metrics to better understand how the system behaves. In this PR I'm proposing to expose:
- TSDB metrics
- Ref cache purge duration
N/A
**Checklist**
=> Expose more TSDB metrics from ingesters when running blocks storage

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_bucket_stores_service.go, pkg/querier/blocks_bucket_stores_service_test.go, pkg/querier/blocks_scanner.go, pkg/querier/blocks_scanner_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway.go
While working on critical Cortex alerts for the blocks storage I've realised there's no reliable way to alert on few critical conditions: blocks are not successfully scanned, synched and compacted.
In this PR I propose the following metrics which allows to alert if a successful scan/sync/compact hasn't occurred in the last X time:
* `cortex_compactor_last_successful_run_time`
* `cortex_querier_blocks_last_successful_sync_time` (when store-gateway is disabled)
* `cortex_querier_blocks_last_successful_scan_time` (when store-gateway is enabled)
* `cortex_storegateway_blocks_last_successful_sync_time`
I've also removed the check on `io.EOF` because I can't see a good reason of having it. We can add it anytime if we figure out there's a good reason of having it, but …
=> Track metric with the last successful blocks sync, scan and compaction

CHANGELOG.md, pkg/cortex/cortex.go
Nowadays we're using Thanos for several things (ie. blocks storage, DNS service discovery, ...) but Thanos traces are not correctly collected because Thanos requires a custom key to be set on the gRPC context. I've added a middleware to inject it for any request.
N/A
**Checklist**
=> Inject Cortex tracer to Thanos gRPC context

pkg/chunk/util/parallel_chunk_fetch.go, pkg/chunk/util/parallel_chunk_fetch_test.go
I was seeing a lot of allocation in this code path and it turns out snappy reader is expensive to create.
This uses a pool in GetParallelChunks that way snappy reader are re-used.
benchmp:
```
❯ benchcmp before.txt after.txt
benchmark                         old ns/op     new ns/op     delta
BenchmarkGetParallelChunks-16     18147888      1483198       -91.83%
benchmark                         old allocs     new allocs     delta
BenchmarkGetParallelChunks-16     4214           9              -99.79%
benchmark                         old bytes     new bytes     delta
BenchmarkGetParallelChunks-16     146576089     127882        -99.91%
```
=> Reduces allocations in `GetParallelChunks`.

CHANGELOG.md, pkg/ingester/client/compat.go, pkg/ingester/client/compat_test.go
In a production cluster running the blocks storage we've seen a large portion of the inuse heap retaining memory allocate by `grpc.recvMsg()`. This is caused by the fact that `FromLabelAdaptersToLabelsWithCopy()` doesn't do a deep copy but reuse input strings (which are read-only slice pointers).
In this PR we're fixing it doing a deep copy.
**Credits: the root cause has been spotted and fixed by @pstibrany**. I've just done double checks and opening the PR for it.
Given the same exact test scenario, this is the `recvMsg()` allocations **before the fix**:
And this is **after the fix**:
N/A
**Checklist**
=> Fix memory leak in blocks storage ingesters

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
In the PR #2583 I forgot to expose checkpoint metrics. In this PR I'm amending it.
N/A
**Checklist**
=> Expose TSDB checkpoint metrics from ingesters

go.mod, go.sum, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/cortex/server_service.go, pkg/cortex/server_service_test.go, pkg/util/module_service.go, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
This PR integrates latest version of weaveworks/common library, which allows Cortex to [disable signal handling](https://github.com/weaveworks/common/pull/191) in `Server` module.
This simplifies module service setup, as we no longer need to make a distinction between [services when using the wrapper or not](https://github.com/cortexproject/cortex/pull/2542#discussion_r417884587). This also simplifies PR https://github.com/cortexproject/cortex/pull/2559.
**Checklist**
=> Move signal handling out of Server module.

CHANGELOG.md, pkg/ruler/lifecycle.go, pkg/ruler/lifecycle_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_ring.go, pkg/ruler/ruler_test.go
- Reuse pattern used by the store-gateway ring to enable the ruler to autoforget instances
Fixes #2058 
**Checklist**
=> Automatically forget unhealthy Rulers

pkg/api/api.go, pkg/chunk/purger/delete_requests_store.go, pkg/chunk/purger/purger.go, pkg/chunk/purger/request_handler.go, pkg/cortex/modules.go
Adds support for cancellation of delete requests. Delete requests can be cancelled only when they are in `RECEIVED` status i.e it is not picked up for processing.
**NOTE**: To avoid a race between cancellation of delete requests and `DataPurger` picking up the delete request, I have added a Mutex. This is based on the assumption that `DataPurger` would always run as a single instance and it is always going to be the case since it kind of works as an orchestrator to manage delete requests. We will be scaling deletes in future by scaling workers(running as a service) not `DataPurger` service.
Alternative:
Currently, delete requests are processed only after they have aged for 24 hours. It is a hardcoded value and we are going to make it configurable just for running …
=> support for cancellation of delete requests

tools/test
**What this PR does**: We're seeing test timeouts on CI in pkg/chunks package lately, bump test timeout to 5 minutes. (Running same test manually on circleCI machine takes about minute and passes)
=> Bump test timeout

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/compactor/blocks_sharding_filter.go, pkg/compactor/blocks_sharding_filter_test.go, pkg/compactor/compactor.go, pkg/ingester/ingester_v2.go, pkg/querier/block.go, pkg/querier/block_test.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/gateway_test.go
We're hitting some vertical scalability limits on the compactor. We have a large user with 30+M active series and compacting 2h blocks take more than 2h. The TSDB compactor uses a single CPU core (there's no parallelisation), so we can't really vertically scale up unless sharding blocks.
In this PR I'm introducing per-tenant in-process sharding support to the compactor, leveraging on the fact that Thanos compactor can parallelise compaction of different blocks groups.
The way it works is quite simple:
1. Add the ingester ID as external label to blocks uploaded by the ingester
2. Add a new metadata fetcher filter in the compactor which replaces the ingester ID label with a shard ID calculated on the hash of the ingester ID
Guaranteed properties:
- Same ingester …
=> Added per-tenant in-process sharding support to compactor

CHANGELOG.md, cmd/query-tee/proxy.go, docs/operations/query-tee.md, pkg/ruler/storage.go
Allows `query-tee` to support `/metadata`, `/alerts`, and `/rules` endpoints.
Instead of opening an issue, I decided to just go ahead and establish the discussion on this PR. This is a bit tricky given the `/metadata` and `/rules` endpoints don't really query Prometheus but instead are served from memory or a file, no "queries" are involved. Which makes this semantically incorrect.
However, `query-tee` is typically deployed as a shim - which means that if you're using something like Grafana, the endpoint of your data source will be the `query-tee` URL. Grafana will fail to access these endpoints given `query-tee` only proxies certain routes. 
An alternative to this might be to allow `query-tee` to operate in a whitelist or blacklist mode where URLs not supported can …
=> query-tee: Support metadata, rules and alerts routes

pkg/ingester/wal.go
Right now series are spread out across the WAL checkpoint duration using
a time.After() call, however that does not account for the amount of
time it may take to checkpoint the series in question. I am consistently
seeing a checkpoint take longer than the goal, and this will help
account for that difference.
**Checklist**
* Is this needed? Possibly ENHANCEMENT but I don't know if it needs mentioning. WDYT?
=> Use Ticker for WAL series spreading

CHANGELOG.md, pkg/cortex/modules.go
Ensure the default evaluation interval is set (promql uses a package-scoped mutable variable). This is important when `querier.parallelise-shardable-queries` is enabled because the frontend aggregates the sharded queries.
Closes https://github.com/cortexproject/cortex/issues/2603
=> Ensures promql's default evaluation interval is set for the query frontend

pkg/ring/kv/etcd/etcd.go
This commit adds the WithKeysOnly OpOption to the List function as we only care about the keys in
the operation.
=> pkg/ringkv/etcd: supply WithKeysOnly option in List operation

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/users_scanner.go, pkg/compactor/users_scanner_test.go, pkg/storage/tsdb/bucket_client_mock.go, pkg/util/services/manager.go
While running the blocks compactor at scale, we reliased that blocks marked for deletion could be potentially never deleted if the compactor is busy all the time compacting blocks.
In this PR I've decoupled blocks deletion from compaction, so that blocks deletion is not blocked by a busy compactor.
N/A
**Checklist**
=> Decoupled blocks deletion from compaction

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, docs/operations/blocks-storage.template, go.mod, go.sum, pkg/storage/tsdb/bucket_client_mock.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/caching_bucket_test.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/user_bucket_client.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go, vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go, vendor/github.com/thanos-io/thanos/pkg/objstore/gcs/gcs.go, vendor/github.com/thanos-io/thanos/pkg/objstore/inmem.go, vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go, vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go, vendor/github.com/thanos-io/thanos/pkg/objstore/swift/swift.go, vendor/github.com/thanos-io/thanos/pkg/objstore/testing.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_config.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go, vendor/modules.txt
**What this PR does**: This PR adds support for caching metadata (meta files, iteration results) to blocks storage, using caching bucket from Thanos. Caching bucket is configured with Cortex usage of blocks in mind (caching top level directory with users, list of blocks per user, content of meta.json and deletion mark files, list of chunks directory).
**Checklist**
=> Metadata caching

integration/querier_remote_read_test.go, pkg/api/api.go
- Ensure the `POST` method is set for the`/read` route registration to match the endpoint in Prometheus. 
Fixes #2619
**Checklist**
=> Fix remote read route registration

integration/e2ecortex/client.go, integration/querier_test.go, integration/query_frontend_test.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/series_store.go, pkg/querier/chunk_store_queryable.go, pkg/querier/chunk_store_queryable_test.go
This PR modifies how errors are reported from chunk store. Instead of using grpc errors with status codes, this PR introduces new QueryError type, which is then recognized by `chunkStoreQuerier` and translated to the appropriate error returned to promQL engine and API wrapper.
Prometheus API wrapper doesn't recognize grpc errors with status codes, but it does recognize some errors and adjusts status code based on them. Result of this PR is that `QueryError`s are translated to 422 (best that Prometheus has to offer).
Previously, our `httpgrpc.Errorf(http.StatusBadRequest, ...)` were actually translated to status code 500, despite the attempt to use `StatusBadRequest`.
**Checklist**
=> Translate internal store errors to prometheus API errors.

pkg/distributor/query.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go
**What this PR does**: This trivial PR finishes spans created by ingester, and logs number of series and samples returned by blocks ingester. It also logs number of returned time and chunk series in "Distributor.Query" and "QueryStream" spans.
=> Finish span created in ingester query stream

pkg/querier/distributor_queryable.go, pkg/querier/querier.go
Add a couple of more tracing spans to better understand where the time is being spent while executing a query.
N/A
**Checklist**
=> Add more tracing spans to read path

pkg/querier/block.go, pkg/querier/block_test.go
Since #2599 we don't need to use labels builder anymore. An unsafe conversion should just be fine.
```
BEFORE: Benchmark_newBlockQuerierSeries-4   	  921447	      1135 ns/op
AFTER:  Benchmark_newBlockQuerierSeries-4   	 9260770	       108 ns/op
```
N/A
**Checklist**
=> Micro optimization in newBlockQuerierSeries()

development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, docs/configuration/config-file-reference.md, pkg/querier/block_meta.go, pkg/querier/blocks_consistency_checker.go, pkg/querier/blocks_consistency_checker_test.go, pkg/querier/blocks_scanner.go, pkg/querier/blocks_scanner_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
In the PR #2593 I've introduced a basic version of the consistency check for the read path, introducing the "upload grace period" based on the "block creation time" instead of the "block upload completed time" because we didn't have a way to know when a block was shipped to the storage.
In this PR I'm fixing it.
N/A
**Checklist**
=> Remove upload grace period

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
While running the Cortex blocks storage we realized that we are not exposing from useful TSDB head metrics, which I've added in this PR:
* `cortex_ingester_tsdb_wal_truncate_duration_seconds`
* `cortex_ingester_tsdb_head_active_appenders`
* `cortex_ingester_tsdb_head_series_not_found_total`
* `cortex_ingester_tsdb_head_chunks`
* `cortex_ingester_tsdb_mmap_chunk_corruptions_total`
* `cortex_ingester_tsdb_head_chunks_created_total`
* `cortex_ingester_tsdb_head_chunks_removed_total`
/cc @codesome 
N/A
**Checklist**
=> Exported more TSDB head metrics from ingesters

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/querier/block_test.go, pkg/util/test/poll.go
Over the past few days I've tried to benchmark different parts of the write and read path used by the blocks storage. I didn't end up into any optimisation (sadly), but I would like to commit these benchmarks anyway for the future.
N/A
**Checklist**
=> Added benchmarks on blocks storage

integration/api_ruler_test.go, pkg/ruler/rules/objectclient/rule_store.go
This PR incorporates a small aspect of the #2543 that ensures rule group names and namespaces are base64 encoded when incorporated into the object key and written to disk. This fixes an issue where illegal characters such as `/` can be set in a rule group that affects the proper operation of the system. This can be seen by running the current integration test present in this PR against a current version of Cortex.
Base64 Encoding was chosen since it is a universally accepted format and fulfills all the naming requirements of common object storage backends:
- https://cloud.google.com/storage/docs/naming-objects
- https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
*Note: This is a breaking change for anyone with the `-experimental.ruler.enable-api` …
=> Ruler Object Storage Base64 Encoding

development/tsdb-blocks-storage-s3/compose-up.sh, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-s3/docker-compose.yml, development/tsdb-blocks-storage-s3/goland/compactor.run.xml, development/tsdb-blocks-storage-s3/goland/distributor.run.xml, development/tsdb-blocks-storage-s3/goland/ingester-1.run.xml, development/tsdb-blocks-storage-s3/goland/ingester-2.run.xml, development/tsdb-blocks-storage-s3/goland/querier.run.xml, development/tsdb-blocks-storage-s3/goland/query-frontend.run.xml, development/tsdb-blocks-storage-s3/goland/store-gateway-1.run.xml, development/tsdb-blocks-storage-s3/goland/store-gateway-2.run.xml
**What this PR does**: This PR modifies docker-compose for TSDB blocks in following ways:
- it modifies compilation of Cortex used by docker-compose to disable optimizations (for better debuggability) and inlining
- it adds Delve debugger to the image
- Cortex now runs under Delve debugger with remote debugging enabled
- Adds Goland configurations for connecting to individual components
=> Add debugger to Docker compose

CHANGELOG.md
I forgot to push the changelog update for #2646 before merging.
=> ChangeLog entry for #2646

docs/configuration/config-file-reference.md, pkg/chunk/aws/metrics_autoscaling_test.go, pkg/chunk/chunk_store_test.go, pkg/chunk/purger/delete_requests_store.go, pkg/chunk/purger/purger_test.go, pkg/chunk/purger/table_provisioning.go, pkg/chunk/purger/tombstones_test.go, pkg/chunk/schema_config.go, pkg/chunk/table_manager.go, pkg/chunk/table_manager_test.go, pkg/chunk/table_provisioning.go, pkg/chunk/testutils/testutils.go, pkg/cortex/modules.go, tools/doc-generator/parser.go
Adds support for provisioning tables for delete store using table manager.
Throughput settings for tables created for delete requests store are part of the store configuration itself.
I have refactored the code used for provisioning throughput for index and chunks tables in table manager to be able to reuse most of the code.
This also adds support for `map` type in doc generator.
**NOTE**: Since the refactoring of provisioning code in table manager changed the order of elements in configuration struct the order of the entries in configuration doc as well changed. There are no breaking changes in configuration.
**Checklist**
=> provisioning of table for delete requests using table manager

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cassandra/fixtures.go, pkg/chunk/cassandra/storage_client.go
Allow users to configure the number of TCP connections per host for Cassandra
This should increase the number of streams (concurrent Cassandra requests) available on the client side, and reduce the chance of getting "gocql: no hosts in pool" errors under load.
Also, use separate clients for reads and writes, to stop the two interferring.
=> Allow users to configure the number of TCP connections per host for Cassandra.

development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3/config/prometheus.yaml
This PR modifies docker-compose setup:
- It enables chunks and metadata caching (using same memcached)
- It modifies Prometheus and Grafana Agent config to add `cluster` and `namespace` labels, and to include namespace in the `job` label. This matches deployment in Kubernetes, and makes it easier to test dashboards from https://github.com/grafana/cortex-jsonnet/ repository.
=> Changes in docker-compose (multiservices) setup

CHANGELOG.md
**What this PR does**: This PR fixes changelog entry with correct metric names.
Metrics are defined here: https://github.com/cortexproject/cortex/blob/b129d25d97be4471855cc09cc19520a6c4a143a9/pkg/storegateway/bucket_store_metrics.go#L46
=> Fix CHANGELOG.md entry with correct metric names.

CHANGELOG.md, pkg/ingester/ingester_test.go, pkg/ingester/user_state.go
This refactoring will help in adding series limits to block based ingester. It also fixes a bug where the [series per metric is not incremented when recovering from WAL](https://github.com/cortexproject/cortex/blob/85f93ff4abd7af81a5eeeae0e07379dd6ff2071d/pkg/ingester/user_state.go#L225-L231).
**Checklist**
=> Dedicated struct and methods for metric counter

pkg/querier/batch/batch.go, pkg/querier/batch/batch_test.go, pkg/querier/batch/chunk.go, pkg/querier/batch/chunk_test.go, pkg/querier/batch/merge.go, pkg/querier/batch/merge_test.go, pkg/querier/batch/non_overlapping.go, pkg/querier/batch/non_overlapping_test.go
We would like to reuse the querier batch iterator in the blocks storage too because preminary tests showed to bring a significant speed up in the query execution (we're currently using the TSDB series merger and iterator, which is optimised for low memory consumption but is significantly slower).
In order to use it, we would need to make the batch iterator general purpose. I tried two approaches:
1. Define an interface for the Chunk used by the batch iterator
2. Define a minimal structure for the Chunk used by the batch iterator
It turned out that the penalty introduced by the interface is too high (see below), while using a minimal structure we make it even faster at the cost of having more allocation OPs (1 per chunk).
What's the general feeling about this change? …
=> Refactor querier batch iterator to make it general purpose

pkg/chunk/chunk_store.go, pkg/chunk/series_store.go
This is actually useful for boltdb shipper feature in Loki where we want to disable chunks write dedupe. The option to disable chunks write dedupe is not user exposed and defaults to false so there must be no visible change for Cortex users.
=> disabling of chunks write dedupe

Makefile
Use `-mod=vendor` when building, to prevent us downloading all the modules and make sure we build with the vendored files.
Fixes #1710
=> Use vendor deps when building.

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cassandra/storage_client.go
Sets the default reconnect interval to cassandra nodes to `1s`
Fixes NA
**Checklist**
=> Set cassandra default reconnect interval to 1s

pkg/ingester/ingester_v2_test.go
**What this PR does**: PR #2658 changed reported timestamps to UTC, but test was not updated.
**Checklist**
=> Fix ingester test when running on machine with non-UTC timezone.

pkg/chunk/cache/tiered.go, pkg/chunk/storage/caching_index_client.go
Signed-off-by: storyicon <storyicon@foxmail.com>
When the cache is not enabled, more query conditions are used to reduce query costs and increase query speed
Fixes #2644
=> improve query speed when does not enable caching

pkg/chunk/storage/factory.go
PR #2279 introduced invalidation of cache when the series deletion is requested. It invalidates results cache when delete request is received and all store caches(chunks, index and write-dedupe) when delete request is processed. It seems we need not invalidate chunks cache since we refer chunks by their ID and changing the content of the chunk requires changing its ID as well.
Also, a chunk is accessible only if it has an index entry for it which also means even though deleted chunks stay in cache until they are evicted, there should not be any harm since its index is already deleted and we would avoid clearing the whole cache containing non-deleted chunks as well.
Thanks to Bryan for pointing this out [here](https://github.com/cortexproject/cortex/pull/2279#issuecom …
=> do not invalidate chunks cache when series are deleted

CHANGELOG.md, cmd/cortex/main.go, cmd/cortex/main_test.go
This is small quality-of-life improvement to improve handling invalid flags and -help.
Invalid flags no longer trigger printing of all available flags (but is still printed to stderr):
```
$ ./cortex -asdasdsa > /dev/null
flag provided but not defined: -asdasdsa
Run with -help to get list of available parameters
```
Available flags are printed to stdout, so that extra redirection of stderr to stdout is not required to use with grep or less or other tools.
```
$ ./cortex -help | grep compactor.ring.consul
-compactor.ring.consul.acl-token string
-compactor.ring.consul.client-timeout duration
-compactor.ring.consul.consistent-reads
-compactor.ring.consul.hostname string
-compactor.ring.consul.watch-burst-size int
-compactor.ring.consul.watch-rate-limit float
```
Inspired by recent Slack …
=> Print usage on stdout, and only when asked with -help.

pkg/querier/blocks_consistency_checker.go, pkg/querier/blocks_store_balanced_set.go, pkg/querier/blocks_store_balanced_set_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go
What we learned running Cortex blocks storage at a medium scale is that store-gateway blocks sharding may lead to some inefficiencies at query time, having the same block unintentionally queried from multiple store-gateway (replicas) at the same time.
To improve this, we introduced in Thanos the ability to selectively pick which blocks should be queried (via block matchers) and in this PR I'm leveraging on this to selectively query blocks from each store-gateway instance.
~~Draft PR until~~:
- ~~https://github.com/cortexproject/cortex/pull/2688 gets merged and rebased here~~
- ~~Tests are done in our dev clusters~~
N/A
**Checklist**
=> Selectively query blocks from each store-gateway

CHANGELOG.md, pkg/querier/blocks_scanner.go, pkg/storegateway/gateway.go, pkg/util/time.go, pkg/util/time_test.go
Applied a jitter to the period bucket scans in order to better distribute bucket operations over the time and increase the probability of hitting the shared cache (if configured).
N/A
**Checklist**
=> Added jitter to blocks storage period bucket scans

.gitignore
Adds `dist/` directory to the `.gitignore` file. This ensures users don't accidentally commit distribution binaries they build.
=> add dist/ repo to gitignore

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/production/storage-cassandra.md, pkg/chunk/cassandra/storage_client.go, pkg/chunk/cassandra/table_client.go, pkg/chunk/cassandra/table_client_test.go
This PR adds `cassandra.table-options` flag and `storage.cassandra.table_options` configuration option to customize Cassandra table options when creating index or chunk table by table-manager.
**Configuration Example**
```yaml
storage:
engine: "chunks"
cassandra:
addresses: "127.0.0.1"
port: 9042
keyspace: "cortex"
consistency: "ONE"
auth: false
table_options: "CLUSTERING ORDER BY (range DESC)
AND comment = 'Important records'
AND compaction = { 'class' : 'LeveledCompactionStrategy' }"
```
EDIT: rename `table_with` -> `table_options`
Fixes #2453 
**Checklist**
=> Add Cassandra table options flag

CHANGELOG.md, go.mod, go.sum, pkg/querier/block_test.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/duplicates_test.go, vendor/github.com/prometheus/prometheus/storage/generic.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go, vendor/modules.txt
Fixed incorrect query results introduced in #2604 caused by a buffer incorrectly reused while iterating samples.
Draft PR until Prometheus upstream fix https://github.com/prometheus/prometheus/pull/7361 won't be merged.
N/A
**Checklist**
=> Fixed incorrect query results introduced in #2604

tools/querytee/proxy.go, tools/querytee/proxy_endpoint.go
`query-tee` was not checking `proxy.compare-responses` and doing the comparison of responses always. This PR fixes that behaviours. It also adds the `RawQuery` in logs when comparison fails.
=> check response comparison flag in query tee to compare responses

CHANGELOG.md, docs/operations/query-tee.md, tools/querytee/proxy.go, tools/querytee/proxy_endpoint.go, tools/querytee/proxy_endpoint_test.go, tools/querytee/proxy_metrics.go, tools/querytee/proxy_test.go
Currently, the `query-tee` waits all backend responses before sending back the response to the client. This means that the query performances, as perceived by the client, are always influenced by the slowest backend.
In this PR I'm fixing this. The `query-tee` now sends back to the client the first viable response received, where "viable" depends on whether the preferred backend is configured. If the preferred backend is configured we need to honor it, so we have to wait for the preferred backend response before sending back the response to the client, while if it's not configured then the first successful response will be picked.
/cc @sandeepsukhani 
N/A
**Checklist**
=> Do not wait for the slowest response in the query-tee

docs/configuration/arguments.md
=> Default value of -ingester.chunk-encoding  is actually Bigchunk starting 0.7.0

pkg/ingester/client/compat.go, pkg/ingester/client/compat_test.go
This PR makes a small optimization in `FromLabelAdaptersToLabelsWithCopy` method: instead of making a copy of each string individually, all strings are copied to the single buffer. This reduces number of allocations, and makes `FromLabelAdaptersToLabelsWithCopy` faster.
Furthermore, number of allocations is now constant.
Master:
```
BenchmarkFromLabelAdaptersToLabelsWithCopy
BenchmarkFromLabelAdaptersToLabelsWithCopy-4   	 3148969	       391 ns/op	     400 B/op	      13 allocs/op
BenchmarkFromLabelAdaptersToLabelsWithCopy-4   	 3164420	       394 ns/op	     400 B/op	      13 allocs/op
BenchmarkFromLabelAdaptersToLabelsWithCopy-4   	 3195446	       385 ns/op	     400 B/op	      13 allocs/op
BenchmarkFromLabelAdaptersToLabelsWithCopy-4   	 3314721	       370 ns/op	     400 B/op	      13 …
```
=> Small optimization for FromLabelAdaptersToLabelsWithCopy

cmd/query-tee/main.go, tools/querytee/proxy.go, tools/querytee/proxy_test.go
Currently, query tee supports only 1 method type per route. This PR adds support for multiple method types per route.
=> allow registering routes with multiple http methods with query tee

pkg/chunk/purger/purger.go
Purger checks for pending delete requests hourly and we only process only 1 delete requests for a user at a time to avoid some problems. This means we process only 1 delete request per user per hour. This should not be a problem for most of the time but it can for some cases. One problem I noticed is with test exporter which creates a delete request every 5 mins which means purger would never be able to catch up.
This PR loads more delete request as soon as a delete request gets processed which belonged to a user who has more pending requests.
=> load delete requests frequently if there are more pending requests for a user

CHANGELOG.md, pkg/chunk/chunk_store.go, pkg/chunk/composite_store.go, pkg/chunk/series_store.go
Redis chunks cache lookup can fail with the error `ERR wrong number of arguments for 'mget' command` if a query has no chunks to lookup from storage. This happens because we don't correctly handle the case `SeriesStore.GetChunkRefs()` returns no chunks.
Fixes #2133
**Checklist**
=> Fix Redis cache error when a query has no chunks to lookup

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
**What this PR does**: This PR adds ability for memberlist client to periodically rejoin the cluster. That can be useful in some configurations and scenarios (eg. when using only distributors as seed-nodes, and all distributors crash and restart and form their own memberlist cluster, ingesters can rejoin if configured with this option).
Related to #2638.
~Draft until #2713  is merged, since this PR builds on that.~
**Checklist**
=> Memberlist: added rejoin interval

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, docs/operations/blocks-storage.md, pkg/ring/kv/client.go, pkg/ring/kv/memberlist/memberlist_client.go
**What this PR does**: This PR adds missing flags from documentation, and marks Memberlist as no longer experimental. Note that this PR assumes #2713 and #2724 to be merged first.
Fixes #2638
**Checklist**
=> Unexperimentalize memberlist

CHANGELOG.md, integration/asserts.go, pkg/api/api.go, pkg/cortex/modules.go
When running cortex as a single binary the requests processed by the querier are not instrumented. This PR adds a separate histogram metric `cortex_querier_request_duration_seconds` that allows the operator to make this distinction.
The metric is registered in both single binary and microservice mode. This will allow the new metric to be used for dashboards/panels in both modes. 
Fixes #2707 
**Checklist**
=> Separate HTTP Instrumentation for Querier

pkg/configs/db/postgres/postgres.go, pkg/cortex/cortex.go, pkg/distributor/ha_tracker.go, pkg/querier/frontend/frontend.go
Yesterday I left a feedback to @jtlisi in https://github.com/cortexproject/cortex/pull/2722 to use "error" as log field name for consistency. I was wrong. There are more occurences of "err" then "error" in logs.
In this PR I'm uniforming it.
N/A
**Checklist**
=> Uniform error field name in logs

cmd/test-exporter/main.go, pkg/testexporter/correctness/case.go, pkg/testexporter/correctness/delete_series.go, pkg/testexporter/correctness/runner.go, pkg/testexporter/correctness/runner_test.go, pkg/testexporter/correctness/simple.go
Test Exporter to continuously test delete series. Here is how it would work:
1. A loop would keep sending delete request at a configured interval(default 5m) for the configured duration(default 2m). Deletion is done by slicing the time by the deletion interval from 0(i.e beginning of epoch) and then deleting data from last slice's end, for configured delete request duration. Following examples show for what interval data would be deleted based on when the deletion is happening(in UTC) with default config:
```
deletion happening at -> deletion interval
00:06:03              -> 00:03:00 to 00:05:00
12:24:30              -> 12:18:00 to 12:20:00
23:00:00              -> 22:58:00 to 23:00:00
```
2. When deleted series is being tested, we would calculate what all …
=> test exporter changes for testing delete series

CHANGELOG.md, pkg/chunk/purger/delete_requests_store.go, pkg/chunk/purger/purger.go, pkg/chunk/purger/purger_test.go
Adds the following 3 new metrics for monitoring the progress of the processing of delete request:
* `purger_load_pending_requests_attempts_total`: Number of attempts that were made to load pending requests with status.
* `purger_oldest_pending_delete_request_age_seconds`: Age of oldest pending delete request in seconds.
* `purger_pending_delete_requests_count`: Count of requests which are in process or are ready to be processed.
This PR also loads new delete requests for processing on startup instead of waiting for the first tick, which is an hour now.
=> more metrics in purger for monitoring delete requests processing progress

docs/production/ha-pair-handling.md
I found it confusing that the example doesn't use the default label names, and says the non-default (replica vs __replica__) is ideal. Made the documentation less confusing by giving example of the sensible default.
**Checklist**
=> Give example of default label keys for HA pair

docs/configuration/arguments.md
Mention that `-distributor.shard-by-all-labels` flag is used by querier too. Some people assume querier has its own version of this flag. That is not the case.
**Checklist**
=> Mention that -distributor.shard-by-all-labels is used by querier too.

CHANGELOG.md, development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml, development/tsdb-blocks-storage-s3/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3/config/prometheus.yaml, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
I've investigated #2748 and fixing it may be non trivial without a coordination between compactor and blocks cleaner. Another option to fix it would be disabling the compactor garbage collection at all, but would require a discussion in Thanos first and deeply understand the impact of it.
Since Thanos and the Cortex blocks storage can deal with partial blocks (it's an expected state because a block is partial also each time it's upload is in progress from the ingester) I propose to keep it simple and just add a cleanup of partial blocks marked for deletion in the blocks cleaner.
Fixes #2748
**Checklist**
=> Cleanup partial blocks with deletion mark expired

pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/inmemory_storage_client.go, pkg/chunk/series_store.go, pkg/chunk/storage_client.go
`DisableChunksDeduplication` was added for disabling chunks deduplication for boltdb shipper in Loki but the problem is it still makes us write an already written chunk again to the storage while the requirement is to not dedupe just the index.
This PR changes flag `DisableChunksDeduplication` to `DisableIndexDeduplication` to disable deduping of just the index and not both chunk+index. It also still writes the chunk to cache for write performance.
=> change flag DisableChunksDeduplication to DisableIndexDeduplication for disabling just index deduplication

CHANGELOG.md, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, docs/configuration/config-file-reference.md, pkg/querier/blocks_consistency_checker.go, pkg/querier/blocks_consistency_checker_test.go, pkg/querier/blocks_store_balanced_set.go, pkg/querier/blocks_store_balanced_set_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/querier/querier.go
_Take a deep breath..._
This should be the last missing piece in my original design when I've started working on introducing the store-gateway (doc excluded, will be done in a separate PR).
Due to the consistency check, a query may fail because some expected blocks are missing from the specific selected store-gateway. This is not a edge condition and could actually occur relatively frequently due to the resharding (ie. during a rolling update or scale up/down).
In this PR I'm introducing the ability to refetch series for missing blocks from different store-gateway replicas which are supposed to have these blocks. I've done some manual local tests and looks working as expected; further tests will be done on staging next Monday.
Draft until:
- Further tests are done …
=> Refetch series for missing blocks

CHANGELOG.md, Makefile, build-image/Dockerfile
Propagate configured GOPROXY value to build-image/Dockerfile so that we can build the code inside network that disallow access to default Go proxy server.
Fixes #2740
**Checklist**
- [Not applicable ] Tests updated
- I have tested the build still works on a vanilla Ubuntu box.
- I have tested my change works behind my company's network.
- [ Not applicable] Documentation added
- [ Done] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=>  Propgate GOPROXY value to build-image/Dockerfile

pkg/chunk/cache/memcached_client.go
Today we've experienced this error in prod:
` msg="failed to put to memcached" name=store.index-cache-read. err="memcache: unexpected response line from \"set\": \"SERVER_ERROR Out of memory during read\\r\\n\"`
And I've got an hard time figuring out which memcached server was returning the error. In this PR I propose to inject the server address to the `Set()` error.
Note: the same thing is difficult to do with the `GetMulti()` because we may potentially touch many (sometimes all) memcached server during a multi get request.
N/A
**Checklist**
=> Add memcached server address to Set() error

.circleci/config.yml, CHANGELOG.md
This PR fixes the Go version used to run integration tests in CI.
N/A
**Checklist**
=> Run integration tests with Go 1.14

pkg/ingester/limiter.go
Today an SRE in our company got confused by the series limit error and thought that "actual local" was the "actual number of series" and not the limit. Now, when the limit is reached they're the same thing but I'm proposing to clarify it anyway.
**Checklist**
=> Clarified actual limits in the series limit error

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/api/api.go, pkg/chunk/purger/purger.go, pkg/chunk/purger/purger_test.go, pkg/chunk/purger/request_handler.go, pkg/cortex/cortex.go, pkg/cortex/modules.go
Duration until which delete requests are allowed to be cancelled after creation is made configurable. This would help with integration tests and run this initially with a higher value until we have more confidence in its stability.
This PR also renames flags and references from datapurger to purger for simplicity and consistency. 
**Checklist**
=> make delete request cancellation duration configurable and rename data-purger to purger

go.mod, tools/test, vendor/modules.txt
**What this PR does**: After #2480, we can enable go 1.14 in go.mod. That enables -mod=vendor by default for all builds.
Requiring go 1.14 for builds also allows us to use new features from this version.
Pinging Loki team: @slim-bean @cyriltovena @owen-d.
**Checklist**
=> Set go version to 1.14, to enable vendor builds by default.

CHANGELOG.md, pkg/chunk/encoding/chunk_test.go, pkg/chunk/encoding/factory.go, pkg/chunk/encoding/varbit.go
It broke ingester hand-overs, and is not needed now we use BigChunk.
Fixes #1163
**Checklist**
=> Remove -store.fullsize-chunks option

CHANGELOG.md, pkg/ingester/wal.go, pkg/ingester/wal_test.go
If an ingester crashes while doing a checkpoint, which is likely as
checkpoints are almost always happening, then a checkpoint like
checkpoint.123456.tmp will be left on disk. When the next checkpoint
succeeds, the old .tmp checkpoints are not deleted even though it will
never be used. After enough crashes it is possible to fill the entire
disk with .tmp checkpoints, bringing down an ingester.
**Checklist**
=> Remove old temporary checkpoints

CHANGELOG.md, pkg/querier/queryrange/queryable.go, pkg/querier/queryrange/querysharding.go
We saw query frontend panicking with `fatal error: concurrent map iteration and map write` [here](https://github.com/cortexproject/cortex/blob/a92b613bc6a3ad8ce1080ae96b403fb2eb955968/pkg/querier/queryrange/querysharding.go#L327). It is possibly due to a race with finishing all the querying and processing of headers while the response headers from sharded queries are still not merged [here](https://github.com/cortexproject/cortex/blob/master/pkg/querier/queryrange/queryable.go#L99)
This PR takes care of that issue. 
Fixes: #2763
=> fix race in processing of headers in sharded queries

docs/proposals/ingesters-migration.md
**What this PR does**: This is a proposal for adding some options for making switch of ingesters and querier between chunks and blocks possible.
=> Added proposal for ingester+querier migration from chunks to blocks and back.

.circleci/config.yml
Was going through the circle config and realised that we're running lint because of an issue that has since been closed.
=> Remove additional step, the issue is closed?

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/ruler.go
Exposes the underlying Prometheus manager option, `OutageTolerance`. This is the lookback period for which the metric store can be queried for past alert evaluations. It's used when each rule group is initially run. In Cortex, this has implications not only during restarts, but also when the ring membership changes. Without this configuration, previous rule state cannot be restored, meaning that after re-sharding/restarts, we must wait the entire `ForDuration` until an alert may be considered firing.
edit: defaulted to prometheus defaults for these flags and included a total of 3 configs at Jacob's suggestion:
```
[for_outage_tolerance: <duration> | default = 1h]
[for_grace_period: <duration> | default = 10m]
[resend_delay: <duration> | default = 1m]
```
=> new flag: ruler.outage-tolerance

CHANGELOG.md, pkg/chunk/purger/purger_test.go, pkg/cortex/modules.go
1. Rename purger target flag from `data-purger` to `purger`.
2. Fix a flaky test in purger.
Fixes #2776 
**Checklist**
=> Rename purger target flag

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/config-file-reference.template, docs/configuration/v1-guarantees.md, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_utils.go, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/util/flagext/time.go, pkg/util/flagext/time_test.go, tools/doc-generator/parser.go
**What this PR does**: This PR adds support to Querier component to query multiple stores. This implements idea from #2717  proposal, and allows querying both blocks and chunk store at the same time. Secondary store can be further queried only for queries older than some timestamp.
Querier-specific configuration for second store engine consists of only backend type (chunks/tsdb) and that timestamp. The rest of the configuration is reused from standard chunks-store/tsdb-engine flags.
~Draft for now, documentation and changelog entry is missing.~ Also not sure if we want to merge #2717  first or not.
I think we should mark this experimental until we test it in production. (Although I've tested it and it worked nicely)
**Checklist**
=> Support querying multiple stores by Querier

pkg/chunk/local/boltdb_index_client.go, pkg/chunk/local/boltdb_index_client_test.go
This PR refactors batch writes in BoltDB by doing both inserts and deletes in the same transaction.
It also makes write batch and a method to write on passed db reference public which helps with boltdb shipper implementation in Loki.
**Checklist**
=> refactor processing of writes in boltdb index client

pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/util/runtimeconfig/manager.go
This PR is a follow up from #2092. Updated so that the `RuntimeConfig` module no longer initializes if the config path is empty.
**Checklist**
=> Initialize RuntimeConfig module only if config is specified

CHANGELOG.md
@bboreham 
I'm sorry... I made a mistake about CHANGELOG in #2575.
I have fixed invalid change log that exist in the wrong section.
The 1.2.0-rc.0 release note also needs to update list of changes.
- move the feature log about `-cassandra.table-options`
- `## 1.1.0 / 2020-05-21` ---> `## 1.2.0 / 2020-06-xx`
Signed-off-by: Kyeongwon Seo <ruddnjs1230@gmail.com>
Fixes 
**Checklist**
=> Fix invalid change log that exist in the wrong section (based on release-1.2 branch)

CHANGELOG.md
To put the CHANGELOG changes on master so further changes can go in the right section.
=> Fix up CHANGELOG for release 1.2 and after

pkg/distributor/distributor.go
introduces a new configuration parameter to allow the user to disable label name validation in the distributor.
the option to disable label name validation is useful for users who want to store non-prometheus data in cortex.
Fixes https://github.com/cortexproject/cortex/issues/2770
**Checklist**
=> make label name validation optional

CHANGELOG.md, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/chunk/series_store.go
This was introduce in #2700, more specifically this line https://github.com/cortexproject/cortex/pull/2700/files#diff-10bca0f4f31a2ca1edc507d0289b143dR537
This causes any query with the first label matcher not matching anything to return all matches of all other labels.
This is a nasty one since, the code was relying on empty slice, and so it would skip nil values instead of returning no matches. I've added a regression test proving this is fixed everywhere. I think in Cortex it probably affect performance (since you have to download all chunks not required) but not read integrity.
I have found this with @slim-bean while deploying Loki, we fought a lot to pin down this exact issue while all queriers where OOMing.
/cc @gouthamve @pracucci @pstibrany We need to put on hold all current …
=> Fixes an issue in the index chunks/series intersect code.

CHANGELOG.md, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
The ruler notifier is not instrumented at the moment. This commit wraps
around the Ruler registry with the userID as a label and `cortex_` as a
prefix and passes it to the notifier options.
The result? We have metrics.
Fixes #2193
**Checklist**
=>  Instrument the Ruler Notifier

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, go.mod, go.sum, pkg/ingester/ingester_v2.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/modules.txt
The store-gateway currently has a per-tenant query concurrency limit, but it's not much useful in a multi-tenant cluster because what we really want to protect is from the concurrent number of queries in a store-gateway instance. I've done this change into Thanos first and then in this PR I'm switching the limit from per-tenant to a shared one.
N/A
**Checklist**
=> Switched store-gateway query concurrency limit from per-tenant to shared

CHANGELOG.md
This PR aims to fix some final requests from https://github.com/cortexproject/cortex/pull/2783 regarding the changelog.
=> Fix ruler.outage-tolerance changelog entry and orders correctly

CHANGELOG.md, tools/querytee/proxy.go, tools/querytee/proxy_metrics.go
Few little improvements on the `query-tee` based on things learned on the field:
1. Refuse to start if the preferred backend is misconfigured
2. Add more granularity to response time buckets
3. Log when the proxy is up and running
N/A
**Checklist**
=> Little query tee enhancements

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/wal.go, pkg/ring/lifecycler.go
**What this PR does**: This PR adds flag to flush chunks to long-term storage even when using WAL. In addition to that, it fixes racy access to `flushOnShutdown` field in Ingester.
This flag follows the proposal from PR #2717. 
**Checklist**
=> Added flag to flush chunks to long-term storage even when using WAL.

CHANGELOG.md, pkg/chunk/cache/cache_gen.go, pkg/chunk/cache/cache_gen_test.go
Fixes a problem with removing cache generation number from keys prefixed with it.
Also adds required tests.
**Checklist**
=> fix cache generation keys prefix

CHANGELOG.md, pkg/ingester/flush.go, pkg/ingester/metrics.go
**What this PR does**: This PR changes `cortex_ingester_flush_reasons`. It is renamed to `cortex_ingester_series_flush_reasons` since it counts series and not chunks, and it is now updated when flushing, not enqueing. This fixes problem described in issue #2287, when idle series could have been enqueued, but then updated before flushing.
Fixes #2287 
**Checklist**
=> Update seriesFlushReason when flushing, not enqueing.

CHANGELOG.md, pkg/chunk/purger/purger.go, pkg/chunk/purger/purger_test.go, pkg/testexporter/correctness/runner_test.go
Changes the tracking of the age of delete requests from "since creation time" to "since they are over their cancellation period".
This would help with defining alerts and SLO/SLAs since the cancellation period is configurable now.
**Checklist**
=> track oldest delete request age since their cancellation period is over

CHANGELOG.md, cmd/query-tee/main.go, cmd/query-tee/main_test.go
**What this PR does**: This PR adds support for custom prefix for API calls supported by query-tee.
**Checklist**
=> Added support for path prefix to query-tee.

CHANGELOG.md, tools/querytee/proxy_backend.go
**What this PR does**: This PR adds support for forwarding `X-Scope-OrgId` header into query-tee.
**Checklist**
=> Add support for forwarding X-Scope-OrgId.

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go
**What this PR does**: This PR adds compaction of blocks that are idle for longer than specified timeout.
~Draft: needs tests.~
**Checklist**
=> Compact idle blocks.

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/ingester/flush.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go
**What this PR does**: This PR adds support for flushing blocks.
Flushing can be triggered by:
- using `-experimental.tsdb.flush-blocks-on-shutdown` option, honored when ingester shuts down
- using `/flush` endpoint (works for chunks too) -- this triggers flush and shipping (if enabled), but endpoint returns immediately. There are log messages written after flushing and shipping (if enabled) has finished
- using `/shutdown` endpoint (works for chunks too) -- this shuts down ingester with flush flag enabled. Endpoint waits until flushing and shipping has finished.
This follows the proposal from PR #2717.
**Checklist**
=> Added support for flushing blocks

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
Clarified that the `-ingester.min-chunk-length` CLI flag (and YAML config option) doesn't apply to blocks storage.
N/A
**Checklist**
=> Clarified that -ingester.min-chunk-length doesn't apply to blocks storage

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, pkg/ring/kv/memberlist/memberlist_client.go
This PR enables lookup for members to join via SRV records.
Follow-up on discussion thread [here](https://grafana.slack.com/archives/CEPJRLQNL/p1592313566141400)
**Checklist**
cc @pstibrany
=> [memberlist] Add support to join memberlist via SRV records

pkg/ingester/flush_test.go
To trigger the original bug, we need to push sample during sweep-flush (achieved by doing push from preFlushChunks).
Shutdown is used to trigger another sweep-flush, and not critical part of the test. Imporant part is that second flush doesn't ignore just-pushed sample (buggy version dropped it completely).
Flakiness was introduced by shutting down ingester too early (possibly before new sample was pushed). Now we wait with shutdown.
Fixes https://github.com/cortexproject/cortex/issues/2825
**Checklist**
=> Fix flaky test in issue 2825

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/docker-compose.yml, docs/configuration/config-file-reference.md, pkg/chunk/chunk_store_test.go, pkg/cortex/modules.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go, tools/doc-generator/main.go
The `-store.max-query-length` is currently enforced in the query-frontend (before splitting) and in the chunks store. In this PR I propose to validate it in the querier so that it applies both to the chunks and blocks storage.
However, I've noticed the limit in the chunks store is also used by Loki, reason why I haven't removed it from there. /cc @cyriltovena 
WDYT?
N/A
**Checklist**
=> Add -store.max-query-length support to blocks storage

docs/getting-started/getting-started-chunks.md
Changed "Promrtheus" to "Prometheus".
Signed-off-by: andynx90 <54808504+andynx90@users.noreply.github.com>
=> Fix typo in getting-started-chunks.md

pkg/ingester/client/timeseries.go
The purpose of this PR is to fix the memory leak of Cortex Ingester. After this PR is merged, it is expected to reduce the runtime memory of Ingester by at least 30%.
Fixes #2665 
Although the PR code looks very simple, the principle inside is more complicated. I try to make it as easy to understand as possible. If there are errors in some parts, please correct me.
When troubleshooting the memory problem of Ingester, I simplified Ingester.Push to make it do almost nothing. Like below：
```
// Push implements client.IngesterServer
func (i *Ingester) Push(ctx context.Context, req *client.WriteRequest) (*client.WriteResponse, error) {
defer client.ReuseSlice(req.Timeseries)
return &client.WriteResponse{}, nil
}
```
After the above …
=> Fix memory leak caused by object pool and zero copy

pkg/chunk/purger/purger_test.go
In `TestPurger_Metrics` test I was starting the purger service [here](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/purger/purger_test.go#L418) after pulling the delete requests for processing [here](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/purger/purger_test.go#L411) which usually should never happen because we always start the service first. This was done to capture an expected metric value.
This was causing Purger to work in an unexpected way causing it to fail the test sometimes. I have changed the test to stop existing purger and create a new one to start the service for delete request processing.
Fixes #2840 
**Checklist**
=> fix a flaky test in purger

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
Improved documentation about limits not supported by blocks storage.
N/A
**Checklist**
=> Improved documentation about limits not supported by blocks storage

pkg/distributor/distributor.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
This removes the `SkipLabelValidation` distributor config property again and introduces a new flag called `-validation.enforce-label-name-charset`. That config flag can be used to disable the enforcement of the prometheus character set restrictions when validating label names, to allow for a wider set of characters in label names. \
The advantage of doing it this way is that the enforcement of the label name charset can be disabled specifically, while all the other label limits (`-validation.max-length-label-name`, `-validation.max-length-label-value`, etc) remain in place.
=> Make label name character set validation optional

CHANGELOG.md, development/tsdb-blocks-storage-s3/.data-minio/.gitignore, development/tsdb-blocks-storage-s3/.data-minio/cortex-alertmanager/.gitignore, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/docker-compose.yml, docs/apis.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, go.sum, integration/alertmanager_test.go, integration/configs.go, integration/e2ecortex/client.go, integration/e2ecortex/services.go, pkg/alertmanager/alerts/compat.go, pkg/alertmanager/alerts/configdb/store.go, pkg/alertmanager/alerts/local/store.go, pkg/alertmanager/alerts/objectclient/store.go, pkg/alertmanager/api.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/alertmanager/storage.go, pkg/api/api.go, pkg/configs/client/client.go, pkg/cortex/modules.go
Similarly to the ruler, this PR introduces a "configuration" API for the Alertmanager. It is per tenant, accepts/takes YAML and is backed up by object storage.
While I cannot take credit for this PR (as it was done by @jtlisi), I'm happy to follow up on reviews to see if I can get this merged.
**Checklist**
=> Experimental Alertmanager API

CHANGELOG.md, pkg/ring/kv/client.go, pkg/ring/kv/client_test.go, pkg/ring/kv/metrics.go, pkg/ring/kv/mock.go
Signed-off-by: Kyeongwon Seo <ruddnjs1230@gmail.com>
This PR fixes a bug about failure to add metrics of multi KV store.
The multi KV store does not have to register metrics.
Because the metrics are registered when creating primary and secondary KV stores.
Fixes #2807
**Checklist**
=> Fix a bug about failure to add metrics of multi KV store

CHANGELOG.md, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile
@codesome noticed we are building some of our Docker images based on old version of Alpine, so I took the opportunity to upgrade them. I've run few smoke tests and it looks good.
N/A
**Checklist**
=> Upgraded Docker base images to alpine:3.12

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
**What this PR does**: This PR calls `Compact` method on newly openened TSDB. If there is data in head that needs to be cut into blocks, this will force it. If there is no such data, this is a noop.
Fixes #2869 
**Checklist**
=> Compact TSDB on open.

.circleci/config.yml, build-image/Dockerfile, tools/test
**What this PR does**: This PR updates is a follow-up for https://github.com/cortexproject/cortex/pull/2749#discussion_r443675025. It updates build-image to include [cover](github.com/weaveworks/tools/cover) tool, to avoid having to run go get and go mod vendor in the test script.
**Checklist**
=> Move cover to build image

docs/case-studies/_index.md, docs/configuration/_index.md, docs/getting-started/_index.md, docs/guides/_index.md, docs/operations/_index.md, docs/production/_index.md, docs/proposals/_index.md, docs/roadmap.md, website/layouts/partials/section-index.html
In this PR I'm proposing to change the way the section index is rendered, adding a title to it and using a normal list rendered with the default font size.
This PR also fixes the roadmap page.
**Before**:
**After**:
N/A
**Checklist**
=> Improved website section index

CHANGELOG.md, pkg/ruler/ruler.go
Adds a metric to track ruler update failures per user.
cc @gotjosh @jtlisi 
**Checklist**
=> Add a metric to track ruler update failures (errors in loading rules files).

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/notifier.go, pkg/ruler/notifier_test.go, pkg/ruler/ruler.go
At the moment, the Ruler only support sending alerts to multiple
Alertmanagers via DNS based service discovery. However, sending to
multiple Alertmanager groups is something that Prometheus allows.
I believe the Ruler should support this too and this commit introduces
that.
To keep backward compatibility we're reusing the same flag but allowing
a list of 1+. With this, we can treat each URL as an Alertmanager group
where multiple Alertmanagers per group is only supported if DNS service
discovery is enabled.
~~*Please note that this would be effectively a breaking change on the ruler flags. In the docs, the ruler API is currently listed as experimental but not the ruler itself. I assume meant we would still need to support the flag for at least 2 more versions should …
=> Support multiple Alertmanagers explicitly in the Ruler

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/operations/blocks-storage.md, pkg/cortex/modules.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/util/validation/limits.go
In this PR:
- Added `-store.max-chunks-per-query` limit support to blocks storage
- Removed `max-sample-count` support because it's flawed in Thanos (it's per block and not per query as documented). I will work on this in a subsequent PR (I need to fix it in Thanos first) and the limit in store-gateway will be based on `-store.max-chunks-per-query` too.
Out of the scope of this PR:
- Add the limit to the store-gateway too (will be done in a separate PR, because I need to refactor and [fix Thanos first](https://github.com/thanos-io/thanos/pull/2858))
- Add a negative cache to avoid running the same query for the same tenant if we already know it will hit the max chunks limit ([issue](https://github.com/cortexproject/cortex/issues/2853)) …
=> Added -store.max-chunks-per-query limit support to blocks storage

pkg/querier/lazyquery/lazyquery.go
This fixes a bug in the `lazySeriesSet` iterator.
The typical user of an iterator would first check whether an error has occurred via `.Err()`, if not they'd check if there's an object to consume via `.Next()`, if there is they'll obtain the object via `.At()`. If `.Err()` isn't using a pointer receiver for `s` then it consumes an object from the `s.future` chan and saves it in `s.next`, but because `s` is not a pointer that property doesn't persist until the following call to `.Next()`. The following `.Next()` will then try to consume another object from `s.future`, which is going to block.
=> use pointer receiver on lazySeriesSet methods

CHANGELOG.md, pkg/querier/frontend/frontend.go, pkg/querier/frontend/frontend_test.go
This change is necessary to correctly pass the Host Header to backend
service. The Host Header will be set by stdlib, so flushing them should
do the trick.
Fixes #2875
**Checklist**
=> Querier: Unset Host Header if DownstreamUrl is configured

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/flusher/flusher.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go, pkg/util/services/services.go
**What this PR does**: This PR makes Flusher mode to work with blocks: by starting Cortex with `flusher` target, it will open all existing local TSDBs, flush data to blocks, upload these blocks to the storage and then exit. Note that currently the only error reporting is via logs -- Cortex exits gracefully even if flushing fails.
**Checklist**
=> Make Flusher mode to work with blocks-engine

CHANGELOG.md, cmd/cortex/main.go, pkg/cortex/runtime_config.go, pkg/util/runtimeconfig/manager.go, pkg/util/runtimeconfig/manager_test.go
This adds metrics for exposing the the sha256 hash of the config files used (before expansion). This allows to monitor the roll-out of a new config file across the cluster and can help to detect a mismatch in active configuration files.
The metric would look like this:
```
cortex_config_info{hash="sha256:86ec4c62f1a0ecc2eb111b752d6aa06db0d361c9f8d8fa6fc703ce6b85532458"} 1
```
As no expansion is going on this matches with the local file:
```
86ec4c62f1a0ecc2eb111b752d6aa06db0d361c9f8d8fa6fc703ce6b85532458  ./docs/configuration/single-process-config.yaml
```
No issue yet
**Checklist**
=> Expose hashsum of the config files

pkg/testexporter/correctness/simple.go
Delete series test in test exporter expects sorted samples. When it is verifying samples for a duration which ranges across different series(due to restarts) the test fails because the samples are merged by simply concatenating them without considering the order. This PR sorts the sample batches belonging to different series before merging them.
=> sort samples from different series before checking for expected samples

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/backend/s3/config.go
In this PR I'm clarifying the supported S3 endpoint for the blocks storage.
Fixes #2885
**Checklist**
=> Clarified supported S3 endpoints for the blocks storage

pkg/chunk/aws/s3_storage_client.go, pkg/chunk/azure/blob_storage_client.go, pkg/chunk/gcp/gcs_object_client.go, pkg/chunk/inmemory_storage_client.go, pkg/chunk/local/fs_object_client.go, pkg/chunk/local/fs_object_client_test.go, pkg/chunk/openstack/swift_object_client.go, pkg/chunk/storage_client.go
Makes filesystem object client windows compatible by not using a hardcoded separator.
It also adds a method to `ObjectClient` to get what separator is being used by underlying storage.
**Checklist**
=> make fs object client windows compatible and add a method to get pathseparator from object clients

CHANGELOG.md, pkg/querier/remote_read.go, pkg/querier/remote_read_test.go
Some applications calling remote_read need to know what type of response to expect.
They may need to discriminate between x-protobuf and x-streamed-protobuf.
No open issues for it.
**Checklist**
=> Set a content type for the remote_read response

integration/e2ecortex/client.go, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/store_mock_test.go
Fixes an issue where recent changes prevented rules from being parsed properly.  This PR: https://github.com/cortexproject/cortex/pull/2878/files changed the way rules were being parsed which broke the ruler api.
POSTS with both cortextool and manually via curl resulted in:
```
cortex-1_1       | level=error ts=2020-07-21T16:32:43.8053596Z caller=api.go:462 org_id=fake traceID=58bf3378ad39cc93 msg="unable to unmarshal rule group payload" err="yaml: unmarshal errors:\n  line 4: cannot unmarshal !!str `test` into yaml.Node\n  line 5: cannot unmarshal !!str `` into yaml.Node\n  line 6: cannot unmarshal !!str `sum by(...` into yaml.Node"
```
This PR fixes the issue by using the correct yaml version in the ruler api.
=> Use correct version of yaml

pkg/chunk/schema_config.go
Fixes a small issue loading the `SchemaConfig` which used the global flagset instead of the passed flagset.
=> Loads schemacfg with correct flagset

docs/architecture.md, docs/configuration/schema-config-reference.md
The https://cortexmetrics.io/docs/architecture/ doc recommends schema v10, while https://cortexmetrics.io/docs/configuration/schema-configuration/ recommends v9. I'm proposing to be consistent and always recommend v10.
/cc @weeco 
N/A
**Checklist**
=> Recommend schema v9 and v10 for production

RELEASE.md
Update master as first step.
Never change the release branch directly.
=> Improve release instructions

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/util/log.go, tools/doc-generator/parser.go, vendor/github.com/weaveworks/common/logging/format.go, vendor/github.com/weaveworks/common/logging/gokit.go, vendor/github.com/weaveworks/common/logging/logrus.go, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
add support for logging in json
this can only happen if  weaveworks/common#184 is accepted and needs a version bump
Related grafana/loki#1885 and weaveworks/common#184
**Checklist**
=> add json log support

CHANGELOG.md, integration/chunks_storage_backends_test.go, pkg/chunk/cache/background.go, pkg/chunk/cache/background_test.go, pkg/chunk/cache/cache.go, pkg/chunk/cache/cache_test.go, pkg/chunk/cache/fifo_cache.go, pkg/chunk/cache/fifo_cache_test.go, pkg/chunk/cache/instrumented.go, pkg/chunk/cache/memcached.go, pkg/chunk/cache/memcached_client.go, pkg/chunk/cache/memcached_test.go, pkg/chunk/cache/redis_cache.go, pkg/chunk/cache/redis_cache_test.go, pkg/chunk/cache/snappy.go, pkg/chunk/chunk_store_test.go, pkg/chunk/storage/caching_fixtures.go, pkg/chunk/storage/caching_index_client.go, pkg/chunk/storage/caching_index_client_test.go, pkg/chunk/storage/factory.go, pkg/chunk/storage/factory_test.go, pkg/chunk/storage/index_client_test.go, pkg/cortex/modules.go, pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go, pkg/querier/queryrange/roundtrip.go
This pr removes global prometheus registries and util.logger in the `cache` package. This is good for reusing this package in other project like Thanos.
**Checklist**
=> Remove global metrics registry and global logger in cache package

docs/configuration/config-file-reference.md, pkg/querier/queryrange/limits.go, pkg/util/validation/limits.go
The issue #2924 made me realise that "0 to disable" is not correctly documented for all supported limits. I checked limits one-by-one and this PR should fix it for limits supporting it.
Fixes #2924
**Checklist**
=> Updated limits doc to reflect when 0 means disabled

pkg/ring/lifecycler.go
Currently an ingester will fail report a 200 on the /ready endpoint if there is a problem in the current state of the ring (stale entry or unhealthy entry), this is intentional, there are a few issues discussing this such as #1521. 
Leaving the debate of this behavior to another issue I think it would help if we logged a warning when this happens.  This still catches us by surprise sometimes when an ingester will not enter the ready state and there is nothing in the logs indicating an issue.
This PR will log a warning when the check of the current ring state fails, this will log over and over every time the /ready healthcheck is queried providing some slightly noisy but hopefully very obvious indication as to why the ingester will not provide a ready response to the …
=> Log a warning when checking the ring and finding a problem 

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/metadata_handler_test.go, pkg/querier/querier_test.go
When running the Cortex blocks storage, the blocks retention in the ingesters may be way higher than the configured `-querier.query-ingesters-within` (eg. in the cortex-mixin we do have a default of 4 days blocks retention in the ingesters, to give operators enough time to recover from any issue causing blocks not being shipped from ingesters to storage, in case of an outage).
Running the blocks storage with a `-querier.query-ingesters-within` significantly higher than the retention means that (under normal conditions) all samples older than `-querier.query-store-after` and more recent than `-querier.query-ingesters-within` are both fetched from ingesters and storage, causing an undesired extra load on ingesters.
Similarly to what we do with …
=> Manipulate ingesters query min time when -querier.query-ingesters-within is set

CHANGELOG.md, pkg/querier/frontend/frontend.go
To better track issues around queries being queued or backed up in the query frontend this PR adds a `user` label to the `cortex_query_frontend_queue_length` gauge.  This can be helpful in understanding if queues backing up are systemic or limited to a single user, as well as understanding if a particular user is regularly backing up a queue.
**Checklist**
Signed-off-by: Edward Welch <edward.welch@grafana.com>
=> Add a `user` label to the query_frontend_queue_length metric

CHANGELOG.md, pkg/ingester/flush.go, pkg/ingester/flush_test.go, pkg/ingester/metrics.go
**What this PR does**: Re-added `cortex_ingester_flush_reasons` under the name `cortex_ingester_enqueued_series_total`.
Added `cortex_ingester_dequeued_series_total`, with outcome label. Outcome is a super set of flush reason.
Follow-up to #2802 and #2811.
Fixes #2287
**Checklist**
=> Metrics for enqueue/flush reason, and dequeue/flush outcome.

pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/ruler/ruler.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
- Add a metrics struct that wraps the metrics registries passed to the Prometheus `rules.Manager` and collects metrics. Identical to the `alertmanagerMetrics` struct used by our multi-tenant alertmanager.
- Adds `SendSumOfCountersPerUserWithLabels` and `SendSumOfSummariesPerUser` functions to the metrics-helper w/ tests
**note**: This PR does not alter the rules exported by the ruler. However, as discussed in #2907, it will enable future changes to remove summary metrics that are not worth exposing. See #2944 
Fixes #2907
**Checklist**
=> bugfix(ruler): fix crashing when manager registers duplicate metrics

CHANGELOG.md, pkg/ring/basic_lifecycler.go, pkg/ring/basic_lifecycler_test.go
I think I've tried to be too smart in the `BasicLifecycler` instance registration to avoid CAS operation when not required. Before this PR, if an instance already exists in the ring, it's not updated at registration phase if only the address differs. This PR fixes it.
I'm not 💯  sure, but could fix #2950.
**Checklist**
=> Fixed basic lifecycler instance registration when only the address differs

Makefile, pkg/chunk/cache/memcached_test.go, pkg/ingester/mapper.go, pkg/ingester/rate.go, pkg/ingester/series_map.go, pkg/querier/frontend/frontend_test.go, pkg/querier/queryrange/retry_test.go, pkg/querier/queryrange/split_by_interval_test.go, pkg/ring/batch.go, pkg/ring/kv/memberlist/tcp_transport.go, pkg/storage/tsdb/ref_cache.go, pkg/storegateway/bucket_stores_test.go, pkg/util/events.go, pkg/util/services/services_test.go
**What this PR does**: Replaces all direct usages of `sync/atomic` with `go.uber.org/atomic`. That way we ensure that all access to variables that have atomic access is in fact always atomic.
Fixes https://github.com/cortexproject/cortex/issues/2923
**Checklist**
=> Replace usage of sync/atomic with uber-go/atomic

CHANGELOG.md, docs/configuration/v1-guarantees.md
Clarify documentation about the `/series` endpoint and adds a note about queries without `__name__` label to ingesters.
N/A
**Checklist**
- [] Tests updated
=> Clarify documentation on series endpoint

pkg/cortex/modules.go, pkg/ruler/compat.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
This PR creates a `TenantManager` interface and a default implementation (functionally equivalent to before) which allows different managers to be substituted (i.e. for Loki's ruler).
It also exposes the `SendAlerts` function for reuse in Loki and fixes some confusing naming issues with structs like `appender` which actually implemented `Appendable` and vice versa.
This also enables removing a few fields from the Ruler struct.
=> Ruler TenantManager interface

CHANGELOG.md, pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/query_range_test.go
Prometheus always returns a result and result type when executing ranged
queries. This was inconsistent in Cortex where no responses would return
`null` for these two values.
https://github.com/prometheus/prometheus/blob/f482c7bdd734ba012f6cedd68ddc24b1416efb35/web/api/v1/api.go#L461-L465
**Checklist**
=> Always return a result and result type in QueryRange

CHANGELOG.md, pkg/chunk/local/boltdb_index_client.go
We noticed a panic when running Loki with `boltdb-shipper` at scale with all the goroutines stack dumped. Following is the relevant stack trace:
```
/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go:292 +0x4aa
created by github.com/cortexproject/cortex/pkg/chunk.(*seriesStore).lookupSeriesByMetricNameMatchers
/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc017e79f88 sp=0xc017e79f80 pc=0x4677c1
runtime.goexit()
/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go:293 +0xe0 fp=0xc017e79f80 sp=0xc017e79ec8 pc=0xd40c20
github.com/cortexproject/cortex/pkg/chunk.(*seriesStore).lookupSeriesByMetricNameMatchers.func1(0xc000162600, 0xc07351f2a0, 0x173a5c99b80, 0x173a5d422d0, 0xc000cbf3fc, 0x2, 0x27e5a57, 0x4, 0x0, …
```
=> make a copy of KVs coming from boltdb which are only valid until the transaction is valid

go.mod, go.sum, pkg/ingester/ingester_v2.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go, vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go, vendor/github.com/thanos-io/thanos/pkg/store/limiter.go, vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go, vendor/modules.txt
**What this PR does**: This PR upgrades Thanos to latest master (https://github.com/thanos-io/thanos/commit/69b87607decf3ae84270ffd5944b519b5b252c76), mostly to get https://github.com/thanos-io/thanos/pull/2956 in. There are few other small changes, but nothing user-visible.
**Checklist**
=> Update Thanos to latest master

CHANGELOG.md, pkg/ingester/ingester_v2.go
Yesterday we had an outage in our staging environment running the blocks storage, caused by all ingesters going OOM while concurrently running several heavy `/api/v1/series` queries.
The problem is that we run ingesters with a TSDB retention of 4 days and we ignore the query time range when handling "metadata" API requests (series and labels). In this PR I'm proposing to mitigate the issue forcing the time range to the TSDB head only, regardless of the TSDB retention (which could be several days). The new logic in this PR is conceptually similar to the Cortex chunks storage, where we do query only in-memory series.
N/A
**Checklist**
=> Always query series and labels from TSDB head

CHANGELOG.md, pkg/ingester/wal.go
When checkpointing has started for a small number of series, a sudden surge in series can make the checkpointing running indefinitely because of the old estimation of the ticker which spreads the writes (actually faced it).
In this PR I am making checkpointing finish immediately without spreading the writes if it has already spent twice the checkpointing duration in the process. 
**Checklist**
=> Avoid indefinite checkpointing

CHANGELOG.md, integration/alertmanager_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Gives us a way to know whenever a tenant has an invalid configuration in
place.
**Checklist**
=> AM Metric: Add tenant label to valid/invalid configs

integration/alertmanager_test.go, integration/api_ruler_test.go, integration/e2e/composite_service.go, integration/e2e/metrics.go, integration/e2e/metrics_options.go, integration/e2e/service.go, integration/getting_started_with_gossiped_ring_test.go, integration/ingester_hand_over_test.go, integration/querier_test.go, integration/query_frontend_test.go
In #2515 (by Joe) I wanted to assert on `cortex_request_duration_seconds` in the integration tests, but I wasn't able because unable to assert on a histogram's count value.
In this PR I'm doing **baby steps** do add functional options support to metrics assection in integration tests. Could be improved in many ways (and I will do in subsequent PRs if this one is approved), but in this PR I would prefer to keep the change set as smallest as possible to validate the basic design.
/cc @bwplotka 
Fixes #2975.
**Checklist**
=> Basic functional options support to metrics assertion in integration tests

Makefile, RELEASE.md, packaging/deb/control/postinst, packaging/deb/control/prerm, packaging/deb/debian-systemd/Dockerfile, packaging/deb/default/cortex, packaging/deb/systemd/cortex.service, packaging/fpm/Dockerfile, packaging/fpm/package.sh, packaging/rpm/centos-systemd/Dockerfile, packaging/rpm/control/post, packaging/rpm/control/preun, packaging/rpm/sysconfig/cortex, packaging/rpm/systemd/cortex.service, tools/packaging/test-packages
Adds tooling that can be used to build RPM and deb packages for cortex configured using the single-process-config.yaml. Continuing the practice in the Makefile, building the packages only requires access to a Docker runtime.
It also includes makeshift integration tests that confirm that the packages can be installed on CentOS or Debian and that the cortex service can be started. Dockerfiles for these images are also included.
This PR achieves the goal of providing a mechanism for building packages for cortex but needs CI integration. I want to see if this is the direction we would like to head in.
**Checklist**
=> Add RPM and deb packaging for cortex binary

CHANGELOG.md, RELEASE.md
In this PR I'm preparing the CHANGELOG for the Cortex 1.3.0 release:
1. Renamed `-experimental.tsdb.*` flags mentioned in the CHANGELOG which have changed in #2937 
2. Move master CHANGELOG under `1.3.0 in progress`
**Checklist**
=> Prepare CHANGELOG for Cortex 1.3.0 release

Makefile
This morning I've merged https://github.com/cortexproject/cortex/pull/2838 which breaks the CI when running in master because it also tries to publish the Docker images used to test the rpm/deb packaging. In this PR I'm excluding them.
N/A
**Checklist**
=> Exclude packaging images from CI

Makefile
Originated from a need during the `1.3.0-rc.0` release, in this PR I'm adding the sha256 hash generation for .rpm and .deb packages too. I've switched to `sha256sum` which works on Linux and can be installed on OSX via `brew install coreutils`.
N/A
**Checklist**
=> Generate sha256 for .rpm and .deb packages too

CHANGELOG.md, pkg/ingester/flush.go
As requested by @bboreham, I'm cherry picking PR #2998 into release 1.3 branch.
N/A
**Checklist**
=> Cherry pick PR 2998 into release 1.3 branch

CHANGELOG.md, integration/e2ecortex/client.go, integration/query_frontend_test.go, pkg/util/time.go, pkg/util/time_test.go
The good @juliusv reported we're not rounding query start/end timestamps like Prometheus. This PR fixes it, specifically introduces the change done in Prometheus almost 3y ago https://github.com/prometheus/prometheus/pull/4941.
Fixes #2932
**Checklist**
=> Fixed query start/end timestamp rounding

pkg/querier/blocks_scanner.go
If the initial blocks scan fail, no specific log is logged, while the operator gets a very generic log message:
```
level=error ts=2020-08-06T20:23:30.893013454Z caller=cortex.go:319 msg="module failed" module=querier err="failed to start querier, because it depends on module store-queryable, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: unable to start blocks storage queryable subservices: not healthy"
```
In this PR I log the error that could occur while starting the `BlocksScanner`.
Fixes #2991
**Checklist**
=> Add a log if the initial blocks scan fail in the querier

docs/blocks-storage/migrate-from-chunks-to-blocks.md, docs/proposals/ingesters-migration.md, tools/migrate-ingester-statefulsets.sh
**What this PR does**: This PR adds document with some details for migrating existing chunks-based Cortex cluster running in Kubernetes to blocks.
It also shows Jsonnet-based configuration as an example.
=> Documented how to migrate a live cluster from chunks to blocks

.errcheck-exclude, pkg/chunk/cache/memcached.go, pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/util/parallel_chunk_fetch.go, pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/results_cache.go, pkg/testexporter/correctness/simple.go, pkg/util/spanlogger/spanlogger.go
It's very confusing to look at a trace UI for two traces that seemed to have failed for the same reason, yet one has error ! icons and the other doesn't. This seems to be a side effect of not setting `error=true` on all error cases, and one case where we had `error="a string"`.
There's also a change required in upstream weaveworks/common to add another `error=true`
cc @gouthamve @gotjosh @joe-elliott 
**Checklist**
=> Be consistent with span logging, set error=true and use otlog.Error

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/caching_bucket.go
The default `-experimental.blocks-storage.bucket-store.sync-interval` value is `5m` so, every 5 minutes, queriers and store-gateway re-iterate the bucket looking for new blocks. However, 2 out 3 times it will be useless because of the caching TTL, which defaults to 15m.
In this PR I propose to lower the default blocks listing and `meta.json` doesn't exist caching to 5m, to match the bucket sync interval.
N/A
**Checklist**
=> Lower default blocks listing and meta.json not exist TTL to 5m

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/aws/dynamodb_table_client.go, pkg/chunk/aws/fixtures.go
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
Exposes the `storage.aws.dynamodb.backoff_config` configuration file so that administrators may configure the DynamoDB backoff without the need for flags.
**Checklist**
=> Expose dynamodb backoff config

CHANGELOG.md, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, integration/e2ecortex/client.go, integration/query_frontend_test.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go
In https://github.com/cortexproject/cortex/pull/2904 I've introduced a bug which prevents `/series` requests to be sent to ingesters if the request time range is older then `-querier.query-ingesters-within`. This is an unintended regression which this PR should fix.
I've run both new unit test and integration test with `master`, and they both break (both for chunks and blocks storage).
Fixes #3032
**Checklist**
=> Query /series from ingesters regardless the -querier.query-ingesters-within setting

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
While working on #2794, I've compared our implementation to fetch series with Prometheus one and I've noticed Prometheus is easier. I've done the refactoring and written and benchmark and turned out it performs better too.
```
benchmark                                           old ns/op     new ns/op     delta
Benchmark_Ingester_v2MetricsForLabelMatchers-12     250057594     226011946     -9.62%
benchmark                                           old allocs     new allocs     delta
Benchmark_Ingester_v2MetricsForLabelMatchers-12     1104071        800196         -27.52%
benchmark                                           old bytes     new bytes     delta
Benchmark_Ingester_v2MetricsForLabelMatchers-12     62724828      51382654      -18.08%
```
**Which issue(s) …
=> Optimised /api/v1/series for blocks storage

CHANGELOG.md, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, integration/e2ecortex/client.go, integration/query_frontend_test.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go
This PR cherry picks the fix done in https://github.com/cortexproject/cortex/pull/3035 into the Cortex 1.3 release branch.
N/A
**Checklist**
=> Cherry pick PR #3035 into release-1.3

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
**What this PR does**: This PR modifies batching in blocks-based ingester, when it is streaming results back. Instead of using only number of series for batching, it also considers how much data is buffered in memory, and flushes batch if it get too big. This is to prevent problems with too large gRPC messages. "Too big" is hardcoded to 1 MiB, to comfortably fit into grpc default, and also to avoid using too much memory.
Note that if *single* series returns too much data, it can still reach gRPC limit for sending messages. Solution to that would be splitting single timeseries into multiple messages, but querier doesn't support that at the moment.
Fixes #2945 
**Checklist**
=> Batch series in streaming ingester based on message sizes.

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/chunks_delete_series_test.go, integration/chunks_storage_backends_test.go, pkg/chunk/cassandra/storage_client.go
- Increase the default Cassandra replication factor to 3
Fixes #2993 
**Checklist**
=> change: increase default cassandra RF to 3 and update docs

pkg/chunk/cache/memcached_test.go, pkg/chunk/schema_test.go, pkg/util/time_test.go
My machine was upgraded to go1.15 and tests were failing with
`conversion from int to string yields a string of one rune, not a string
of digits (did you mean fmt.Sprint(x)?)`
=> Make tests build on go1.15

CHANGELOG.md, pkg/chunk/cache/memcached.go
Previously it would record a `Memcached.Get` operation with a nested `Memcached.GetMulti`; since they are in one-to-one correspondance this is pointless.
Skip the outer data collection for the non-batched case, and rename the batched one to `Memcached.GetBatched` which is more descriptive.
These names are used for metric labels and for tracing span names.
**Checklist**
=> Simpler instrumentation for non-batched memcached

pkg/distributor/distributor.go, pkg/ring/ring.go, pkg/ring/ring_test.go
While working on the shuffle sharding in the store-gateway, I've realised it's quite annoying that the `Ring.Subring()` can return an error. My take is that if the subring can't be constructed (for any reason) we shouldn't fail, but we should fallback to the full ring. In this PR I'm proposing it.
N/A
**Checklist**
=> Do not return error from Ring.Subring()

pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
This pr adds support for dynamic split interval based on the current request. This is useful in the Thanos downsampling use case.
For more details, please check https://github.com/thanos-io/thanos/issues/1651.
**Checklist**
=> Use intervalFn to support dynamic split interval in query frontend

CHANGELOG.md, integration/alertmanager_test.go, integration/e2ecortex/client.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Two really small improvements, and a precedent to start the discussion around automatic fallback configuration.
Fixes #2704 
**Checklist**
=> Fixes the Alertmanager panicking when no external URL is provided

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/ruler/manager.go, pkg/ruler/ruler.go
Also, add a metric for when creation of rules manager would fail.
=> Add integration label to notification metrics

CHANGELOG.md, integration/alertmanager_test.go, integration/e2ecortex/client.go, pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant_test.go
Fixes the registration of the Alertmanager API metrics for receiving alerts. Additionally, it removes a couple of TODOs I noticed along the way - they should be a no-op.
**Checklist**
=> Fixes the registration of the Alertmanager alert receiving API metrics

CHANGELOG.md, docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, integration/e2e/service.go, integration/getting_started_with_gossiped_ring_test.go, pkg/cortex/modules.go, pkg/ring/basic_lifecycler.go, pkg/ring/lifecycler.go, pkg/ring/model.go
This PR should fix the memberlist support for the store-gateway ring.
Fixes #3057
**Checklist**
=> Fixed memberlist for store-gateway ring

docs/api/_index.md
In this PR I'm doing a couple of fixes following up #3050:
1. Documented `/metrics` endpoint
2. The [comment](https://github.com/cortexproject/cortex/pull/3050#discussion_r473025579) did raise the point that the pipe in a table breaks the layout if not correctly escaped. I wanted to see if it was just the GitHub PR preview diff or the GitHub website rendering too. Turned out it's also when the markdown is rendered on GitHub, so in this PR I'm fixing it changing the pipe to comma (we can't use the `\|` because it doesn't render correctly in the Hugo website...)
N/A
**Checklist**
- [x Documentation added
=> Fixed HTTP API documentation

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/wal.go, pkg/ingester/wal_test.go
Fixes #3059
I plan to add test for this on Monday.
**Checklist**
=> Dont skip WAL logging for validation errors

CHANGELOG.md, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go
fixes #2906
When we use the caching client (which is what is used in most cases), we
load the entire row (tableName+HashKey) irrespective of what the
rangeKey parameters are. Which means with the optimisation, we are
loading the same row multiple times and then operating on the same data.
This PR moves the optimisation to after the data is loaded which should
be faster.
**Checklist**
=> Move regex opt to after lookup

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/chunk/cache/memcached_client.go, vendor/github.com/bradfitz/gomemcache/memcache/memcache.go, vendor/github.com/sony/gobreaker/.travis.yml, vendor/github.com/sony/gobreaker/LICENSE, vendor/github.com/sony/gobreaker/README.md, vendor/github.com/sony/gobreaker/go.mod, vendor/github.com/sony/gobreaker/go.sum, vendor/github.com/sony/gobreaker/gobreaker.go, vendor/modules.txt
If the server is unavailable, this will avoid Cortex hammering it with new connection requests and flooding the log.
We use a 3rd-party fork of the gomemcached library so we can set a custom dialer function - see https://github.com/bradfitz/gomemcache/pull/86 (this branch is slightly behind the version we used before, but only in code we don't call)
Fixes #1821
This is an alternative to #3045 
**Checklist**
=> Add a circuit-breaker to memcached dial calls

pkg/cortex/cortex.go
When using block storage, schema-related configuration is not used. This PR adds a warning if schema has been configured anyway.
N/A
**Checklist**
=> Add warning that schema configuration is not used in blocks storage mode

CHANGELOG.md, docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, integration/getting_started_with_gossiped_ring_test.go, pkg/ruler/ruler.go
Signed-off-by: lahsivjar <lahsivjar@gmail.com>
**What this PR does**: Currently ruler doesn't publish it's ring metrics since it is not registered. Also, the ruler ring is currently named as `ring` which has been changed in this MR to `ruler` so that the metrics is understandable.
**Checklist**
=> Publish ruler's ring metrics

CHANGELOG.md, cmd/cortex/main.go
old:
```
% docker run --rm  quay.io/cortexproject/cortex:v1.3.0 -config.expand-env
flag needs an argument: -config.expand-env
Run with -help to get list of available parameters
```
new:
```
-> % docker run --rm quay.io/cortexproject/cortex -config.expand-env
level=info ts=2020-08-25T08:41:46.0276577Z caller=main.go:162 msg="Starting Cortex" version="(version=1.3.0, branch=master, revision=2cbf61af6)"
level=info ts=2020-08-25T08:41:46.0283108Z caller=server.go:223 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-08-25T08:41:46.0287076Z caller=modules.go:488 msg="RulerStorage is not configured in single binary mode and will not be started."
level=error ts=2020-08-25T08:41:46.0300884Z …
```
=> Fixes `-config.expand-env` requires argument

docs/configuration/config-file-reference.md, pkg/chunk/cache/memcached_client.go
In #3051 we introduced memcached circuit breaker. For new config options, we try to keep YAML and CLI flags naming specular, so in this PR I'm fixing the new CLI flags to match YAML (`-` in CLI are `_` in YAML).
N/A
**Checklist**
=> Fixed CLI flags for memcached circuit breaker

CHANGELOG.md, pkg/cortex/modules.go
Similarly to #3058, in this PR I'm fixing memberlist for the compactor ring. We don't have any integration test on compactor yet, so I've manually tested it. Will create an issue about adding compactor integration tests too.
Fixes #3084
**Checklist**
=> Fixed memberlist support for the compactor ring

development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/configuration/single-process-config-blocks-tls.yaml, docs/configuration/single-process-config-blocks.yaml, docs/configuration/single-process-config.md, docs/configuration/single-process-config.yaml, docs/production/storage-cassandra.md
The config option `use_gzip_compression` has been deprecated in favour of `grpc_compression: gzip` in #2940, but we forgot to update the examples/doc. In this PR I'm fixing it.
N/A
**Checklist**
=> Do not mention deprecated config option use_gzip_compression in the doc

integration/e2e/service.go
- Returns both the standard out and standard error when running the exec command on a concrete service.
In some cases the standard error output can be desired when running a service.
**Checklist**
=> feat: return stdout and stderr from all concrete service exec commands

CHANGELOG.md, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Opening this in the form a proposal to see what others think cc: @pracucci @gouthamve @bboreham 
Currently, fallback configurations work in the form of:
- Poll for all config in the object storage
- If the user has an empty config file and we have a fallback config, then use the fallback to start a new Alertmanager
With this PR, we start the am and upload an empty config if the alert manager path is hit (either by accessing the UI or receiving an alert). There are some downsides with this approach:
- If the user uploads a config and accesses the UI before we poll its config will be overwritten (although a check can be added as part of this process?)
- there's no way to know when an Alertmanager has gone "stale" and remove it from memory (although this might not be a concern of cortex?) …
=> Start an Alertmanager when it is requested if we have a fallback config

pkg/ruler/api.go, pkg/ruler/manager.go, pkg/ruler/ruler.go
Prometheus was refactored to support [arbitrary rule loading](https://github.com/prometheus/prometheus/pull/7569), but we currently bind incoming rule groups to promql via the underlying `rulefmt` package implementation. This PR extracts said validation functionality into an interface method on the pre-existing `MultiTenantManager` interface which will allow plug-able implementations (attractive in my case for logql expressions in Loki).
=> makes rule group validation an interface

CHANGELOG.md, pkg/cortex/cortex_test.go, pkg/cortex/modules.go
- Decouples the distributor service from the API
Fixes #3109 
TLDR: Querier will no longer host distributor endpoints
**Checklist**
=> change: separate distributor into api and service module

CHANGELOG.md, docs/api/_index.md, integration/e2ecortex/client.go, integration/ruler_test.go, pkg/api/api.go, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/rules/compat.go, pkg/ruler/rules/local/local.go, pkg/ruler/rules/objectclient/rule_store.go, pkg/ruler/rules/store.go, pkg/ruler/store_mock_test.go
Allow the Ruler API to delete a whole namespace. There's also a small bugfix that fixes responses in the ruler API.
Needs:
**Checklist**
=> Allow the Ruler to delete a whole namespace

CHANGELOG.md, pkg/chunk/inmemory_storage_client.go, pkg/chunk/objectclient/client.go, pkg/chunk/purger/purger.go, pkg/chunk/purger/purger_test.go, pkg/chunk/testutils/testutils.go
Adds retries for processing of failed delete requests.
It also fixes a bug in `chunk.Client` which was not encoding keys in `DeleteChunk` but it was in `PutChunk` and `GetChunk` causing it to fail during deletes.
**Checklist**
=> retry processing of failed delete requests

CHANGELOG.md, pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go, pkg/cortex/modules.go
**What this PR does**: This PR fixes index page, and adds configured HTTP path prefix to all internal links it renders.
Fixes #3118.
**Checklist**
=> Index page should honor configured HTTP path prefix.

CHANGELOG.md, pkg/querier/querier.go
**What this PR does**: This PR removes obsolete `-promql.lookback-delta` option, deprecated since Cortex 1.2.
Fixes #3116 
**Checklist**
=> Removed promql.lookback-delta option.

CHANGELOG.md, docs/configuration/prometheus-frontend.md, docs/configuration/prometheus-frontend.yml, pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go
**What this PR does**: This PR removes obsolete `results_cache.max_freshness` from YAML config.
Fixes #3117.
**Checklist**
=> Remove obsolete `results_cache.max_freshness` from YAML config.

pkg/cortex/cortex_test.go, pkg/cortex/modules.go
I'm in a situation where i would like to be able to instantiate an Ingester without registering its API endpoints and without registering the GRPC service, because I want to embed it in a struct to override some of its methods and then register that outer struct as the GRPC service. 
Currently `Cortex.initIngester()` contains quite a lot of logic which is private to the package (in `multiClientRuntimeConfigChannel()`) and the same method also registers the API endpoints and the GRPC service. So if I want to init the Ingester in the same way as `initIngester()` does it, then I have to re-implement (copy-paste) the logic in `multiClientRuntimeConfigChannel()`, which is not very nice.
I saw how the Distributor got split into two modules `DistributorService` and `Distributor`, I think if we'd …
=> split ingester module into ingester and ingesterService

integration/configs.go
Appends a randomly generated test ID string at launch of the integration tests to the network name used by each scenario. On linux, Docker bridge networks are implemented using IP tables and there should not be any issues with additional networks being created. The will only persist after tests that fail to shut down correctly.
Fixes #3146 
**Checklist**
=> test: provide unique network name for docker tests

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
I would like to add an additional GRPC call to the Ingester service, to query that additional call it would be nice if I could re-use the existing Ingester querying code in the Distributor. To make that possible the following two properties would need to be exported:
`Distributor.forAllIngesters()` 
By exporting this method I'll be able to query all Ingesters by calling `distributor.ForAllIngesters()` with a custom function which type-casts the Ingester client to one that supports my additional call, like this:
```
responses, err := dist.ForAllIngesters(ctx, true, func(client ingesterClient.IngesterClient) (interface{}, error) {
extendedClient := client.(extendedIngester.ExtendedIngesterClient)
resp, err := extendedClient.MyCustomCall(ctx, req)
if err != nil {
return nil, err
}
return …
```
=> export distributor properties to make ingester extendable

.gitignore
**What this PR does**: This PR removes `blocksconvert` binary from the tree, and adds it to `.gitignore`.
**Checklist**
=> Remove blocksconvert binary from the tree.

tools/blocksconvert/builder/tsdb.go, tools/blocksconvert/builder/tsdb_test.go
**What this PR does**: This PR fixes meta.json file of converted blocks.
Without correct `sources` in `meta.json`, compactor will treat blocks as subsumed by any other block that exists, and delete it eventually.
**Checklist**
=> blocksconvert: Set compaction sources correctly

CHANGELOG.md, pkg/configs/api/api.go, pkg/configs/api/api_test.go
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
The Configs API was missing the default funcs when validating templates, this lead to Configs returning an error when trying to set templates using any of those default funcs
Fixes #2490
**Checklist**
=> Added default template funcs to templates validation

pkg/chunk/chunk_store.go, pkg/chunk/composite_store.go, pkg/chunk/composite_store_test.go, pkg/chunk/schema_config.go, pkg/chunk/schema_config_test.go
Adds a new store method called `GetChunkFetcher` which helps to get a chunk fetcher for a chunk.
I have used end time of the chunk to find the store for it.
This helps with a use-case where Loki has a bunch of chunk ids which would be converted to chunkref using `ParseExternalKey` and passed to this method to get a fetcher for it.
**Checklist**
=> add store method for getting fetcher for a chunk

CHANGELOG.md, pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go
**What this PR does**: This PR makes index page dynamic. Cortex will now only show links that are valid for running instance.
Fixes #3128
**Checklist**
=> Index page should only show links that are valid for running Cortex

CHANGELOG.md, go.mod, go.sum, vendor/github.com/weaveworks/common/aws/config.go, vendor/github.com/weaveworks/common/httpgrpc/README.md, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
In this PR I'm upgrading `weaveworks/common` to bring in https://github.com/weaveworks/common/pull/198, which fixes an issue with the S3 URL contains `@` but no username and password.
Fixes #3034
**Checklist**
=> Fix @ in the S3 URL without username and password

docs/blocks-storage/store-gateway.md, docs/blocks-storage/store-gateway.template, docs/production/running.md, k8s/query-frontend-svc.yaml
Fix a link to `block storage` on:
https://cortexmetrics.io/docs/production/running-in-production/
Also fix a spelling error in store-gateway docs, and a port name in
`query-frontend-svc.yaml`.
Signed-off-by: Andrew Seigner <andrew@sig.gy>
**Checklist**
=> Doc fixes related to block storage

pkg/ring/lifecycler.go
Signed-off-by: Edward Welch <edward.welch@grafana.com>
**Checklist**
=> Improve the error message in readiness check when unhealthy ingesters are in the ring.

pkg/cortex/cortex.go, pkg/cortex/tracing.go
@bboreham reported in #3168 that we have some double tracing spans, due to how we inject the tracer for Thanos. According to my investigation, the issue is caused by the usage of `grpc_tracing.UnaryServerInterceptor()` and `grpc_tracing.StreamServerInterceptor()` (respectively called by Thanos `UnaryServerInterceptor()` and `StreamServerInterceptor()`) which create a new span.
This PR should fix it. I've manually tested it (both for unary and stream interceptors) and looks fixing the issue.
Fixes #3168
**Checklist**
=> Fixed double tracing spans

pkg/util/services/manager.go, pkg/util/services/manager_test.go
**What this PR does**: This PR modifies `(*services.Manager).AwaitHealthy` method to return more descriptive error message, including the failure cases of failed services.
Fixes #3124 
**Checklist**
=> AwaitHealthy now returns more descriptive error message

CHANGELOG.md, cmd/cortex/main.go, cmd/cortex/main_test.go, docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, pkg/util/modules/modules.go, pkg/util/modules/modules_test.go
**What this PR does**: This PR enhances output of `-modules` option to mark which modules are part of "All":
```
$ ./cmd/cortex/cortex -modules
alertmanager
all
compactor
configs
distributor *
flusher
ingester *
purger *
querier *
query-frontend *
ruler *
store-gateway *
table-manager *
Modules marked with * are included in target All.
```
Inspired by https://github.com/cortexproject/cortex/issues/3041#issuecomment-689886482.
**Checklist**
=> Make it possible for user to discover which modules are included in "All" target.

docs/contributing/how-integration-tests-work.md, integration/configs.go
- Reverts the network name used by default in integration tests to be static
- Allow for users to override the network name using the `E2E_NETWORK_NAME` env variable
Related Comment: https://github.com/cortexproject/cortex/pull/3147#issuecomment-692158510
**Checklist**
=> feat(e2e): set network name in e2e tests using env variable

tools/blocksconvert/allowed_users.go, tools/blocksconvert/builder/builder.go, tools/blocksconvert/scanner/scanner.go, tools/blocksconvert/scanner/scanner_processor.go, tools/blocksconvert/scanner/scanner_processor_test.go, tools/blocksconvert/scheduler/scheduler.go, tools/blocksconvert/scheduler/scheduler_test.go
**What this PR does**: This PR adds some improvements to blocksconvert suite:
- builders now export timestamp of current plan (each plan is for single day, this day's timestamp is exported)
- obsolete progress files now end up converted to error files by scheduler, not just deleted. This avoids crash looping of builders trying to build the same plan.
- scheduler now exports metrics about its queue: length, oldest/newest plan day timestamp
- scanner has new `-scanner.allowed-users` flag to only generate plans for selected users
**Checklist**
=> Improvements to blocksconvert

CHANGELOG.md, pkg/ruler/rules/local/local.go, pkg/ruler/rules/local/local_test.go
**What this PR does**: This PR changes how rules are loaded from local directory. If directory entry is a symlink, it now first resolves the symlink before doing the directory check.
Fixes #3136 
**Checklist**
=> Follow symlinks and ignore target directories.

docs/getting-started/getting-started-with-gossip-ring.md, pkg/ring/kv/memberlist/memberlist_client.go
We marked gossip/memberlist support as stable in 1.2.0 but we forgot to update all the doc and remove the experimental warning from logs. This PR fixes it.
N/A
**Checklist**
=> Fixed doc about Gossip/memberlist support no more experimental

docs/blocks-storage/convert-stored-chunks-to-blocks.md, docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
**What this PR does**: This PR adds documentation for `blocksconvert` tools.
**Checklist**
=> Document blocksconvert tools.

CHANGELOG.md, docs/api/_index.md, integration/e2ecortex/client.go, integration/ruler_test.go
A couple of micro fixes to doc:
1. CHANGELOG entries for #3180 was missing the PR number
2. PR #3120 removed a couple of info from "Delete rule group" API doc
N/A
**Checklist**
=> Micro fixes to CHANGELOG and API doc

.circleci/config.yml, build-image/Dockerfile
Update the base image in the build-image to the latest golang 1.14 release.
Changelog:
https://github.com/golang/go/issues?q=milestone%3AGo1.14.9+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.8+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.7+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.6+label%3ACherryPickApproved+
https://github.com/golang/go/issues?q=milestone%3AGo1.14.5+label%3ACherryPickApproved+
**Checklist**
- [] Tests updated
- [] Documentation added
- [] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Update golang to 1.14.9 in build-image

CHANGELOG.md, RELEASE.md
I'm about to cut `1.4.0-rc.0`. As a preliminary step, I'm cutting the CHANGELOG to simplify conflicts management.
N/A
**Checklist**
=> Cutting CHANGELOG before next release

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cache/memcached_client.go
With these settings it will Will trip after 10 failures within 10 seconds
Also change circuit-breaker log fields to avoid clash: the names 'from' and 'to' are used elsewhere as dates, so avoid re-using them here as strings
**Checklist**
=> Turn memcached circuit-breaker on by default

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cache/memcached_client.go
As requested by @bboreham, in this PR I'm cherry-picking PR #3189 before cutting `1.4.0-rc.0`.
N/A
**Checklist**
=> Turn memcached circuit-breaker on by default (#3189)

pkg/ingester/active_series.go
**What this PR does**: This PR adds pooling to `xxhash.New()`, which helps to reduce allocations on `Push`-path in ingester.
```
name                                  old time/op    new time/op    delta
ActiveSeriesTest_single_series/50-4     86.2ns ± 2%    78.1ns ± 1%    -9.41%  (p=0.000 n=10+8)
ActiveSeriesTest_single_series/100-4    86.5ns ± 1%    80.0ns ±10%    -7.42%  (p=0.002 n=9+10)
ActiveSeriesTest_single_series/500-4    87.3ns ± 6%    90.1ns ±33%      ~     (p=0.393 n=10+10)
ActiveSeries_UpdateSeries-4              736ns ±19%     718ns ±12%      ~     (p=0.953 n=9+10)
name                                  old alloc/op   new alloc/op   delta
ActiveSeriesTest_single_series/50-4      80.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
ActiveSeriesTest_single_series/100-4 …
```
=> Pool hash to reduce allocations on Push.

CHANGELOG.md, integration/ruler_test.go, pkg/ruler/manager.go, pkg/ruler/mapper.go
On startup and shutdown the Ruler will clean up any directories in it's configured `rule-path`
Fixes #3008 
**Checklist**
=> fix: cleanup tempoary ruler files on startup and shutdown

CHANGELOG.md, integration/querier_test.go, pkg/distributor/query.go, pkg/distributor/query_test.go, pkg/ingester/client/compat.go, pkg/ingester/client/compat_test.go, pkg/querier/chunk_store_queryable.go
This fixes #717
We hit issue in production when our customer issued a query that issued
a simple query that touched 20K series, many of which had hash
collisions on `client.FastFingerprint`. This made our querier code
merge multiple series together which caused counters to go up
and down and caused rate() to return weird artifacts.
It is quite tricky to debug and I now have a test up which proves that
we will suffer if we don't handle collisions explicitly. After looking
at several solutions for fixing that, I've finally settled on something
super simple, just use a string as the map key.
Here is a benchmark where I insert and lookup 100K series:
```
goos: linux
goarch: amd64
pkg: github.com/cortexproject/cortex/pkg/distributor
BenchmarkSeriesMap-8         842          91633894 ns/op
PASS …
```
=> Dont rely on hashes for collecting chunks together

CHANGELOG.md
I merged PR #3178 too quickly, before CHANGELOG entry was fixed. This PR fixes it.
N/A
**Checklist**
=> Fixed changelog entry for PR 3178

CHANGELOG.md, pkg/configs/db/postgres/postgres.go
Signed-off-by: Ben Wells <b.v.wells@gmail.com>
This PR checks for errors when reading postgress rows. The rows.Next() method may encounter an error when reading the next row. In this case a false value is returned and it is important to call rows.Err() to see whether an error was encountered.
N/A
**Checklist**
=> Check for postgres rows errors

CHANGELOG.md, docs/configuration/v1-guarantees.md
**What this PR does**: This PR marks TLS configuration for gRPC, HTTP and etcd clients as experimental. This feature was introduced without experimental flag, and while it works, there are some edge cases that will require introduction of breaking changes. (see https://github.com/cortexproject/cortex/pull/3156 for discussion).
=> Mark TLS Configuration in gRPC, HTTP and etcd clients as experimental.

docs/configuration/arguments.md
Bryan correctly [reported on Slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1600429290009800) that the documentation for the SRV DNS-based service discovery is wrong. In this PR I'm fixing it based on his input.
N/A
**Checklist**
=> Fixed DNS-based service discovery doc

CHANGELOG.md, pkg/alertmanager/multitenant.go
We get one of these messages for every tenant every 15 seconds, and none of them are very interesting in normal operation.
**Checklist**
=> Drop alertmanager message about blank config to debug

CHANGELOG.md, docs/configuration/v1-guarantees.md
As agreed on CNCF Slack, I'm cherry picking PR #3198 to explicitly mark TLS support experimental in 1.4.0.
N/A
**Checklist**
=> Cherry picked PR 3198

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/alertmanager/multitenant.go
=> Alertmanager Config API: Do not allow empty configurations

CHANGELOG.md, integration/querier_test.go, pkg/distributor/query.go, pkg/ingester/client/compat.go, pkg/ingester/client/compat_test.go, pkg/querier/chunk_store_queryable.go
I propose to backport the hash collisions bug fix (#3192) to `1.4` branch and then cut `1.4.0-rc.1`.
N/A
**Checklist**
=> Backported PR 3192

CHANGELOG.md, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/manager.go
Fixed a few cases where the API would allow us to submit a bad rule group payload which would end up overwriting existing ones.
In our case, this is pretty egregious given we operate against individual rule groups you could end up in a situation where you have overwritten a working rule group by mistake. 
Fixes #2942 
**Checklist**
=> Ruler Experimental API: Fix rule group validation

CHANGELOG.md, integration/querier_sharding_test.go, pkg/querier/frontend/frontend.go
It's rare but I've noticed some flake on an integration test that is caused by a querier's worker not connecting to the frontend before the test finishes. This should help solve that issue.
Fixes #3206 
**Checklist**
=> feat: add metric and fix querier int test flake

docs/configuration/v1-guarantees.md
**What this PR does**: Marks blocksconvert as experimental.
=> Mark blocksconvert tools as experimental.

CHANGELOG.md, docs/blocks-storage/store-gateway.md, docs/blocks-storage/store-gateway.template, docs/configuration/config-file-reference.md, docs/guides/zone-replication.md, pkg/distributor/distributor_test.go, pkg/ring/lifecycler.go, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/storegateway/gateway_ring.go, pkg/storegateway/replication_strategy.go, pkg/storegateway/sharding_strategy_test.go
In this PR:
- As agreed in the discussion we had in the PR #3090, I've added a flag to explicitly enable zone-awareness replication
- Added zone-awareness replication support to store-gateway
- Updated doc
N/A
**Checklist**
=> Added flag to explicitly enable zone-awareness replication and added store-gateway support

pkg/chunk/aws/dynamodb_storage_client.go
DynamoDB can be used for storing either or both chunks and indexes.
This change improves the error messages in `BatchWrite()` method by using
`items` instead of `chunk` and also adds `DynamoDB` to the error message.
The previous error message was misleading as a failed index write can produce
an error message about chunks:
```
caller=flush.go:199 org_id=fake msg="failed to flush user"
err="failed to write chunk, 1 values remaining: context deadline exceeded"
```
**Checklist**
=> Improve DynamoDB BatchWrite error messages

.gitignore, tools/auth-injector/main.go
I had this simple tool in my local repository since a while and I thought to propose to upstream it. It's just an HTTP reverse proxy offering a quick way to inject `X-Scope-OrgID` header.
For example, the following command listens on `8081` and proxies all requests to `8080` injecting `X-Scope-OrgID: load-balancer-1`:
```
go run ./tools/auth-injector -local-address=localhost:8081 -remote-address=http://localhost:8080 -tenant-id=load-balancer-1
```
Do you think it make sense to upstream it?
N/A
**Checklist**
=> Share auth-injector tool

integration/chunks_storage_backends_test.go, pkg/cortex/modules.go, pkg/ruler/ruler_test.go, pkg/ruler/rules/local/local.go, pkg/ruler/rules/local/local_test.go, pkg/ruler/storage.go
**Allow arbitrary group loading from local rule storage**:
This PR passes the upstream [GroupLoader](https://github.com/prometheus/prometheus/blob/master/rules/manager.go#L992-L996) interface to the local rules storage backend. This interface is already used in the Ruler API via the Prometheus rules manager to validate rules. This PR aims for parity with that and avoids hardcoding the implementation which allows downstream projects (Loki) to use the local backend store.
=> Arbitrary group loading in local rules backend

docs/blocks-storage/_index.md, docs/configuration/schema-config-reference.md, pkg/chunk/schema_config.go
We recently received a question on CNCF Slack asking if the schema config was used by the blocks storage too. It not, but the doc is not much clear about it, so in this PR I'm improving the doc.
Fixes #3006
**Checklist**
=> Clarify that schema config is used only by the chunks storage

CHANGELOG.md, docs/configuration/arguments.md, pkg/chunk/schema_config.go
The `-config-yaml` was deprecated in Cortex `0.7.0` (by @gouthamve in this commit https://github.com/cortexproject/cortex/commit/9cf31fe5dfee841309e94050b116b4e4fe233211) in favour of `-schema-config-file`.
In this PR I'm removing the support for the deprecated flag.
N/A
**Checklist**
=> Removed the deprecated flag -config-yaml

tools/blocksconvert/scanner/bigtable_index_reader.go, tools/blocksconvert/scanner/scanner.go
**What this PR does**: This PR adds support for specifying date-range when scanning for tables. It also adds metrics to scanner to better track its progress.
Tables ignored due to range are logged:
```
level=info ts=2020-09-23T06:17:18.034230103Z caller=scanner.go:264 msg="table starts after period-end, ignoring" table=index_2646 table_start="2020-09-17 00:00:00 +0000 UTC" table_end="2020-09-24 00:00:00 +0000 UTC" period_end=2020-09-17T00:00:00Z
level=info ts=2020-09-23T06:17:18.034241493Z caller=scanner.go:259 msg="table ends before period-start, ignoring" table=index_2613 table_start="2020-01-30 00:00:00 +0000 UTC" table_end="2020-02-06 00:00:00 +0000 UTC" period_start=2020-02-06T00:00:00Z
```
=> Blocksconvert: added support for specifying date range for tables scan

CHANGELOG.md, cmd/cortex/main.go, cmd/cortex/main_test.go, pkg/cortex/cortex.go
**What this PR does**: This PR adds `-version` command line flag to Cortex which prints version and exits.
(This PR also moves printModules flag to main.go instead of having it in Cortex config.)
Fixes #3219.
**Checklist**
=> Added -version flag to Cortex.

integration/s3_storage_client_test.go, pkg/alertmanager/alerts/objectclient/store.go, pkg/alertmanager/storage.go, pkg/chunk/aws/fixtures.go, pkg/chunk/aws/s3_storage_client.go, pkg/chunk/aws/s3_storage_client_test.go, pkg/chunk/azure/blob_storage_client.go, pkg/chunk/gcp/fixtures.go, pkg/chunk/gcp/gcs_object_client.go, pkg/chunk/inmemory_storage_client.go, pkg/chunk/local/fixtures.go, pkg/chunk/local/fs_object_client.go, pkg/chunk/local/fs_object_client_test.go, pkg/chunk/openstack/swift_object_client.go, pkg/chunk/purger/purger_test.go, pkg/chunk/storage/factory.go, pkg/chunk/storage_client.go, pkg/ruler/rules/objectclient/rule_store.go, pkg/ruler/storage.go
**What this PR does**: This PR refactors `ObjectClient` interface to explicitly pass `delimiter` to `List` method. Previously delimiter was property of `ObjectClient` passed to it when created, but that doesn't work if code using `ObjectClient` wants to do both recursive and non-recursive calls.
This PR also changes `FSObjectClient` such that it always expects paths using `/` separator, but maps it to `\` on Windows internally. Code using `FSObjectClient` will only see `/` returned.
This is a pre-requisite for PR #3235.
**Checklist**
=> ObjectClient List refactoring

pkg/ring/kv/consul/client.go, pkg/ring/ring_test.go
**What this PR does**: This PR modifies flaky `TestShuffleShardWithCaching` test to use fewer lifecyclers to avoid CAS operation failures. That should make test more stable.
Fixes #3241 
**Checklist**
=> Fix TestShuffleShardWithCaching

CHANGELOG.md, integration/api_endpoints_test.go, integration/e2e/util.go, pkg/api/api.go, pkg/cortex/index.go
We had some API endpoints which allowed any HTTP method, while they were clearly only `GET` and/or `POST`. This is particularly insidious if someone misconfigure Prometheus and remote writes to `/` because that POST requests will succeed while they shouldn't.
In this PR I'm fixing it.
Fixes #3227
**Checklist**
=> Enforce HTTP method required by most API endpoints

docs/guides/zone-replication.md
In this PR I'm documenting the impact of running an unbalanced number of instances across different zones, when zone-aware replication is enabled. This originated from a comment left in another PR https://github.com/cortexproject/cortex/pull/3236#discussion_r494809135.
N/A
**Checklist**
=> Document impact of unbalanced zones on zone-aware replication

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/backend/s3/bucket_client.go, pkg/storage/backend/s3/config.go
- Expose additional HTTP configuration parameters for the Minio S3 client vendored from Thanos
**Checklist**
=> feat: expose S3 HTTP configs for TSDB S3 client

pkg/ring/lifecycler.go
- the address and ID are applicable to both concel, etcd, and memberlist
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Fix help message in for lifecycler config

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, docs/guides/shuffle-sharding.md, integration/querier_sharding_test.go, pkg/util/validation/limits.go
**What this PR does**: This PR renames ` -frontend.max-queriers-per-user` to `-frontend.max-queriers-per-tenant` to be consistent with other sharding flags. This isn't a breaking change, since this flag was not part of stable release yet, and the feature is marked as experimental.
**Checklist**
=> Change -frontend.max-queriers-per-user to -frontend.max-queriers-per-tenant

pkg/ingester/wal.go
Signed-off-by: Brett Snyder <bsnyder@digitalocean.com>
Replaces SegmentRange with upstream TSDB wal.Segments
Fixes #3114
**Checklist**
=> Replace SegmentRange with upstream wal.Segments

CHANGELOG.md, pkg/configs/client/client.go
=> Set cortex as user agent for requests

pkg/ruler/api.go
Prometheus now allows context, but the problem is the interface
`RulesRetriever` can never fail rule lookups. I can't see a good fix for
it right away, so decided to fix the comment for now.
=> Update comment to reflect current state.

.gitignore, Makefile, Makefile.local.example
**What this PR does**: This PR modifies `Makefile` to include `Makefile.local` if it exists, so that it is possible to extend it with custom settings and rules without committing those in shared repository. Example `Makefile.local.example` is included for inspiration.
If `Makefile.local` is missing, nothing changes.
=> Make it possible to extend Makefile with custom settings.

CHANGELOG.md, integration/chunks_storage_backends_test.go, pkg/chunk/inmemory_storage_client.go, pkg/ruler/api.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/ruler/rules/local/local.go, pkg/ruler/rules/local/local_test.go, pkg/ruler/rules/objectclient/rule_store.go, pkg/ruler/rules/objectclient/rule_store_test.go, pkg/ruler/rules/store.go, pkg/ruler/rules/store_test.go, pkg/ruler/storage.go, pkg/ruler/store_mock_test.go
**What this PR does**: This PR splits listing and loading rules in `rules.RuleStore` interface and most importantly `objectclient.RuleStore` implementation. This makes it more efficient, since we don't need to load rules that ruler doesn't own. Other implementations (local, configdb) still combine listing and loading.
**Checklist**
=> Split listing and loading rule groups in rules.RuleStore interface

CHANGELOG.md, pkg/chunk/gcp/gcs_object_client.go
**What this PR does**: This PR modifies GCS object client to avoid asking for selected attributes when using `List` with delimiter. Problem is that using both delimiter and selected attributes returns empty result, because `cloud.google.com/go/storage` package doesn't put `prefixes` into list of returned fields.
**Checklist**
=> Don't set selected attributes when using delimiter.

CHANGELOG.md, pkg/cortex/modules.go
This pull request returns an explicit error if the user asks to start
the store gateway but omits to set the storage type to `blocks`.
The previous behaviour was to silently ignore the -target=store-gateway
argument.
Note that this does not apply when target is `all`.
**Checklist**
=> Error if the store gateway is run on an invalid engine

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/ruler/ruler_ring.go, pkg/storegateway/gateway_ring.go
The config documentation for `instance_interface_names` was intentionally hidden to keep it simple, but there are legit use cases where our default interfaces don't cover actual ones.
Fixes #3293
**Checklist**
=> Expose doc for instance_interface_names

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/production/caching.md, pkg/chunk/cache/redis_client.go
Added configuration parameter to disable SSL certificate verification in Redis client.
Related to #3290
**Checklist**
=> Redis cache: added parameter to disable SSL certificate verification

pkg/storage/tsdb/bucket_client.go, pkg/storage/tsdb/config.go
- This adds a config field for injecting middlewares when creating a bucket client to allow for the clients created within modules to be created with these middlewares.
- This approach is overtly simple and a factory approach similar to the Ruler may be preferable.
=> Add injectable middlewares to bucket client

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cache/redis_client.go
Based on what we learned in #3290, I would suggest relax a bit the default Redis timeout, increasing it from `100ms` to `500ms`. Cortex users (especially during an initial phase, while evaluating it) should have a smooth experience (work at first time) and then they can fine-tune settings based on their needs.
N/A
**Checklist**
=> Increase -<prefix>.redis.timeout default from 100ms to 500ms

pkg/ingester/ingester_v2.go
**What this PR does**: [compactionLoop](https://github.com/cortexproject/cortex/blob/e26519995ae889d0f7a187a1e74dde99571fa39d/pkg/ingester/ingester_v2.go#L1194) method in blocks-ingester can ignore finished context if compaction takes too long. On next iteration, if multiple `select` cases are active (eg. both cancellation and ticker), Go runtime will [randomly](https://golang.org/ref/spec#Select_statements) select one. If it selects the ticker again, another compaction will run and block the shutdown.
This PR modifies the compaction loop to stop faster if context is cancelled.
=> Blocks compactionLoop: Respect context cancellation faster.

CHANGELOG.md, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go
Whilst building new dashboards for the ruler I noticed no data was being reported via this metric, turns out it was a bug.
Fixes a small bug in the ruler metrics, where we used the wrong name to
match against the upstream metric. This caused the metric to not report
any data at all.
**Checklist**
=> [BUGFIX] Fix reporting of `cortex_prometheus_rule_group_duration_seconds`

CHANGELOG.md, pkg/util/extract_forwarded.go
Signed-off-by: Michel Hollands <michel.hollands@grafana.com>
Fix the incorrect grpc header used for IP logging. As per https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests the header cannot contain slashes.
Tested by running the steps in #3286 (without HAproxy even).
Fixes #3286
**Checklist**
=> Use valid grpc header

CHANGELOG.md, pkg/ruler/ruler.go
We just found out that the ruler is leaking gRPC connections when rulers sharding is enabled and APIs called. This is an hot fix. The proper fix (that will be done later) is to use the gRPC clients pool like we do in any other place.
N/A
**Checklist**
=> Fixed gRPC connections leaking in rulers when rulers sharding is enabled and APIs called

tools/auth-injector/main.go
**What this PR does**: This PR improves auth injector tool a bit:
- It changes default :80 to :8080
- It checks for empty remote address explicitly, since otherwise proxy would start forwarding to empty URL.
- It prints address that it's listening on, and forwarding to
=> Auth injector defaults

CHANGELOG.md, pkg/ingester/active_series.go, pkg/ingester/active_series_test.go, pkg/querier/frontend/frontend_querier_queues.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ruler/ruler_test.go, pkg/util/shard.go, pkg/util/yolo.go, pkg/util/yolo_test.go
While working on #3252 I found an issue in the shuffle sharding implementation. When zone-awareness is enabled and the shard size is increased (or instances in a new zone are added) the "consistency" property is not guaranteed, and the returned shard may drop instances which were present in the previous shard (before increasing the shard size). On the contrary, when we increase the shard size, we do expect that the new shard includes all previous instances + new ones.
The problem is due to the fact that the algorithm consider each zone like a separate subring but we're sharing the same pseudo-random generator to select instances in different zones. If you select +1 instance from the 1st zone, the instances selection in the following zone will be based on a different …
=> Fixed shuffle sharding consistency when zone-awareness is enabled and the shard size is increased or instances in a new zone are added

pkg/ring/kv/consul/client.go, pkg/ring/ring_test.go
**What this PR does**: This PR attempts to fix flaky test in `ring_test.go` by adding more CAS retries and using randomized delay between CAS retries.
~This PR will fix flaky test in ring_test.go. For now it just captures and logs output when test fails to get full understanding on what's going on.~ (I couldn't reproduce failure on CI machine)
=> Fix flaky test.

.github/README.md, .github/workflows/test-build-deploy.yml
This is PR 1/3 of migrating Cortex's CI from CircleCI to GitHub Actions: 
**[Part 1/3](https://github.com/cortexproject/cortex/pull/3302)** 👈 
* create `test-build-deploy` workflow under `.github/workflows`
* add README
* adding the 3 base jobs
* `lint`
* `test`
* `build`
* these jobs are run async and share no dependencies with each other
* workflow is run when a commit is pushed to `master` or when any PR is opened. However CD jobs will only run on the master branch and will be skipped otherwise
* all jobs in following PRs are dependant on one or more of these jobs finishing
**Part 2/3** 
* adding jobs dependant on `build`
* `integration`
* `integration-config-db`
* This PR completes the CI portion of migration. The following PR will finish the remaining CD portion of the migration …
=>  Migrate CircleCI workflows to GitHub Actions (1/3)

.github/workflows/test-build-deploy.yml
As discussed in #3302, we shouldn't need anymore uploading artifacts in CI. Removing from GitHub actions workflow we're working on.
/cc @AzfaarQureshi 
N/A
**Checklist**
=> Remove artifacts upload from GitHub actions

integration/configs.go, integration/ruler_test.go
- This PR adds an integration test that ensures the ruler evaluation delay functionality works as expected.
**Checklist**
=> test: add integration test for ruler evaluation delay

pkg/ingester/client/client_test.go, pkg/querier/remote_read.go, pkg/util/http.go, pkg/util/push/push.go
It's never used.  Noted in #3188
**Checklist**
- NA `CHANGELOG.md` updated
=> Don't return raw buffer from util.ParseProtoReader()

docs/api/_index.md
Signed-off-by: Stan Kwong <stanley.kwong@robinhood.com>
Adds more documentation on how to import template files into your Alertmanager configuration.
Fixes https://github.com/cortexproject/cortex/issues/3194
**Checklist**
- [documentation changes don't seem to fix into any of these?] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Add more documentation on AM templates

.circleci/config.yml, integration/backward_compatibility_test.go
The more integration tests we add, the longer they take and we're now seeing CI hitting the 20m timeout when running integration tests. In this PR:
- Increased timeout from 20m to 30m
- Removed backward compatibility tests for Cortex versions < 1.0
N/A
**Checklist**
=> Increase integration tests timeout

pkg/chunk/table_manager.go, pkg/compactor/syncer_metrics.go
Also ensures that other standalone objects are registered by adding a
registerer to their New() function.
Partially #2204 (still miss the default registry metrics)
**Checklist**
=> Use Promauto.With() where possible

pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/results_cache.go
This pr extends the query frontend `Response` interface with a new method.
```go
GetHeaders() []*PrometheusResponseHeader
```
This is useful when I need to extend the results cache to other types of responses. Like `Series` and `Labels`. I still want to check the response HTTP headers but the casting is not necessary.
**Checklist**
=> add GetHeaders to the Response interface

pkg/api/api.go, pkg/cortex/modules.go, pkg/ruler/api.go, pkg/ruler/api_test.go
This PR decouples the ruler and rule store API into separate components and allow for their configuration and usage to be decoupled. In a later PR if the ruler is fully decoupled from the API, it will be possible to run the rules API as a standalone service which will make it easier to deal with the challenges of using an eventually consistent object storage backend.
**Checklist**
=> feat: separate ruler into ruler and rulerAPI components

CHANGELOG.md, tools/blocksconvert/scanner/scanner.go, tools/blocksconvert/scanner/scanner_test.go
**What this PR does**: PR modifies Scanner tool in `blocksconvert` to upload generated plan files concurrently. This help in case when large number of files is generated from the scan.
**Checklist**
=> blocksconvert: Scanner uploads files concurrently

CHANGELOG.md, integration/alertmanager_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Signed-off-by: Stan Kwong <stanley.kwong@robinhood.com>
- Changes `cortex_alertmanager_config_invalid` to `cortex_alertmanager_config_last_reload_successful`, such that the nomenclature matches that of the [ruler](https://github.com/jpdstan/cortex/blob/ca35f4a9943e003056a6c2bc0767d48fb26b2442/pkg/ruler/manager.go#L77-L77) and the [upstream alertmanager](https://github.com/jpdstan/cortex/blob/ca35f4a9943e003056a6c2bc0767d48fb26b2442/vendor/github.com/prometheus/alertmanager/config/coordinator.go#L63-L63)
- Adds the `alertmanager_config_last_reload_successful_seconds` metric
**Checklist**
=> Modify Alertmanager config metrics

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, integration/e2e/metrics_options.go, integration/e2e/service.go, integration/ingester_sharding_test.go, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/query.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/ring/model.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, tools/test
This PR aims to implement the ingesters shuffle sharding on the read path, as described in [this design doc](https://cortexmetrics.io/docs/proposals/shuffle-sharding-on-the-read-path/#querier-ingesters-shuffle-sharding).
The idea is that, when distributors/ingesters shuffle sharding is enabled, we only query data from the subset of ingesters holding the data for a specific tenant.
This PR builds on top of #3299.
_Documentation has not been updated yet._
N/A
**Checklist**
=> Add ingesters shuffle sharding support on the read path

tools/test
This PR adds a condition in `tools/test.sh` to add `-race` and code coverage flags when running tests in GitHub Actions. This is accomplished by checking the existence of `$CI` which is a [default env variable](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables) in GitHub Actions and is always set to `true`
Fixes https://github.com/cortexproject/cortex/issues/3337
**Checklist**
cc: @alolita
=> BugFix: setting -race and code coverage flags for GitHub Actions workflow

docs/blocks-storage/convert-stored-chunks-to-blocks.md
**What this PR does**: Adds short documentation on `blocksconvert` Cleaner from https://github.com/cortexproject/cortex/pull/3283.
**Checklist**
=> Added section on Cleaner.

pkg/distributor/distributor.go, pkg/distributor/query.go
I'd like to query all Ingesters of a replication set for some data, to do this I can use the distributor method `ForReplicationSet()`. But to obtain the replication set which I need to query I'd need to be able to call the distributor method `getIngestersForMetadata()`, which is currently not exported. Would it be fine for you to export that method, or is there a better way for me to obtain the replication set that I need to query?
=> Export distributor method to get ingester replication set

CHANGELOG.md, pkg/ring/kv/memberlist/memberlist_client.go
Last weekend I prepared a talk and I've realised memberlist members joining doesn't work when addresses are configured using the DNS-based service discovery (eg. `dns+cortex:1234`). This PR fixes it.
N/A
**Checklist**
=> Fixed Gossip memberlist members joining when addresses are configured using DNS-based service discovery

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
Tonight we had an issue in one ingester which had TSDB head chunks corrupted (root cause will be discussed separately). When a similar issue happen, the ingester skips the corrupted TSDB at startup, it joins the ring with `ACTIVE` state and, as soon as receive any write request from the tenant with the corrupted TSDB it will try to reopen the TSDB for *every single write request*. This leads to an undesirable situation, which will soon get the ingester to get killed (due to OOM).
In this PR I'm proposing to fail fast the ingester if unable to load an existing TSDB. It's a loud and clear signal to the Cortex cluster operator and, in my opinion, it's better to fail fast an ingester before it start receiving write requests instead of having it failing few minutes after …
=> Fail fast an ingester if unable to load existing TSDBs

pkg/api/api.go
I would like to extend the Ingester by wrapping it in another struct, which overrides some methods and does additional work before calling the original Ingester methods.
Currently the API method `.RegisterIngester()` expects the concrete type `*ingester.Ingester`, so I can't pass it the extended ingester type. Outside the `api` package I also can't easily re-implement the `.RegisterIngester()` method, because it uses an unexported property of the API (`sourceIPs`). 
By changing the API method `RegisterIngester()` to expect an interface I'll be able to pass it the extended Ingester type and register its methods on the HTTP and the GRPC server.
What do you think about this approach?
An alternative to creating an Ingester interface would be to export that unexported property `.sourceIPs` …
=> add ingester interface

pkg/distributor/ha_tracker.go
Remove comment that doesn't seem to describe wha the actual code is doing. I did not attempt to add new comment because the code is pretty self-explanatory.
I did not create a PR as the fix is too simple. 
**Checklist**
- [ N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Remove comments that doesn't seem right

.github/workflows-doc.md, .github/workflows/scripts/install-docker.sh, .github/workflows/test-build-deploy.yml
This is PR 2/3 of migrating Cortex's CI from CircleCI to GitHub Actions: 
**[Part 1/3](https://github.com/cortexproject/cortex/pull/3302)** 
* create `test-build-deploy` workflow under `.github/workflows`
* add readme
* adding the 3 base jobs
* `lint`
* `test`
* `build`
* these jobs are run async and share no dependencies with each other
* workflow is run when a commit is pushed to `master` or when any PR is opened. However CD jobs will only run on the master branch and will be skipped otherwise
* all jobs in following PRs are dependant on one or more of these jobs finishing
**[Part 2/3](https://github.com/cortexproject/cortex/pull/3341)**  👈 
* adding jobs dependant on `build`
* `integration`
* `integration-config-db`
* This PR completes the CI portion of migration. The following PR will …
=>  Migrate CircleCI workflows to GitHub Actions (2/3)

integration/alertmanager_test.go, integration/backward_compatibility_test.go, integration/chunks_delete_series_test.go, integration/chunks_storage_backends_test.go, integration/configs.go, integration/ingester_flush_test.go, integration/ingester_hand_over_test.go, integration/ingester_sharding_test.go, integration/integration_memberlist_single_binary_test.go, integration/querier_remote_read_test.go, integration/querier_sharding_test.go, integration/querier_streaming_mixed_ingester_test.go, integration/querier_test.go, integration/query_frontend_test.go, integration/ruler_test.go
In https://github.com/cortexproject/cortex/issues/3367 (still open) I did a mistake and, in a specific integration test, I've overwritten the global variable `BlocksStorageFlags` causing another unrelated test to fail.
In this PR I'm proposing an approach to enforce default flags to never be overwritten, switching them to a function returning `map[string]string` instead of a global variable.
N/A
**Checklist**
=> Enforce integration tests default flags config to never be overwritten

CHANGELOG.md, pkg/chunk/aws/s3_storage_client.go
AWS SDK returns a type called `CommonPrefix` which is a struct and inside it there is a Prefix field which holds the actual common prefix value. I was by mistake using `String` method on  `CommonPrefix` instead of accessing the `Prefix` field for building the response from `List` call.
This PR fixes the issue by returning the correct value instead of marshalled `CommonPrefix` type.
I have verified this fix with an s3 bucket, now it works fine as expected.
**Checklist**
=> fix common prefixes returned by List method of s3 client

CHANGELOG.md, pkg/alertmanager/alerts/objectclient/store.go, pkg/chunk/azure/blob_storage_client.go, pkg/chunk/gcp/gcs_object_client.go, pkg/chunk/storage_client.go, pkg/chunk/util/util.go
When a timeout is configured for gcs and azure object clients the `GetObject` function(which returns a reader) cancels the context in defer which means we return a reader with a cancelled context. This is causing the download operation to fail.
I think it was a mistake done by me when I refactored the code to split `GetChunk` method to have a `GetObject` method in object store clients which otherwise was downloading the chunks within the functions and not returning an object reader.
I have changed the code to not cancel the context and just set the timeout in context.
**Checklist**
=> fix timeout handling in GetObject for azure and gcs

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/compat.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/ruler/store_mock_test.go, pkg/util/validation/limits.go
Limits the number of rules per rule group, total rule groups and rules a particular tenant can create. 
**Checklist**
=> Per tenant ruler rule group limits

CHANGELOG.md, docs/configuration/arguments.md, integration/ingester_limits_test.go, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/query.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go, pkg/ring/ring.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go, pkg/util/math.go, pkg/util/shard.go, pkg/util/shard_test.go
The max global series per user/metric limit doesn't work correctly when shuffle sharding and shard-by-all-labels are both enabled because it considers series to be distributed across all ingesters, while actually series are only distributed across a subset of ingesters (the shard size).
Fixes #3367
**Checklist**
=> Fixed max global series per user/metric limit when shuffle sharding is enabled

.circleci/config.yml, .github/workflows/test-build-deploy.yml
This is PR 3/3 of migrating Cortex's CI from CircleCI to GitHub Actions: 
**[Part 1/3](https://github.com/cortexproject/cortex/pull/3302)** 
* create `test-build-deploy` workflow under `.github/workflows`
* add readme
* adding the 3 base jobs
* `lint`
* `test`
* `build`
* these jobs are run async and share no dependencies with each other
* workflow is run when a commit is pushed to `master` or when any PR is opened. However CD jobs will only run on the master branch and will be skipped otherwise
* all jobs in following PRs are dependant on one or more of these jobs finishing
**[Part 2/3](https://github.com/cortexproject/cortex/pull/3341)** 
* adding jobs dependant on `build`
* `integration`
* `integration-config-db`
* This PR completes the CI portion of migration. The following PR will …
=> Migrate CircleCI workflows to GitHub Actions (3/3)

.github/workflows/test-build-deploy.yml
The new GitHub actions workflow "deploy" job (see #3368) is broken because of an issue with secrets/env variables name. In this PR I'm fixing it.
N/A
**Checklist**
=> Fixed deploy via GitHub actions

pkg/api/api.go
I'd like to be able to use the `Ingester` interface outside of this package. 
Would it be ok with everyone to export that?
=> export Ingester interface

.circleci/config.yml, .github/workflows/test-build-deploy.yml, integration/e2e/db/db.go, integration/e2e/images/images.go, integration/e2e/service.go
I've noticed the integration test `` is flaky ([see here](https://github.com/cortexproject/cortex/runs/1293159338)) and my suspect is that we may start testing against etcd/consul after the container is running but before the service is actually ready.
In this PR I've:
- Added readiness probes for consul and etcd
- Took the opportunity to upgrade consul used in integration tests (was very old)
N/A
**Checklist**
=> Fixed TestKV_List_Delete flakyness

docs/blocks-storage/production-tips.md
Based on a question received on Slack, I'm proposing to mention the file description limits affecting ingesters too (especially after TSDB chunks files have been introduced).
/cc @codesome 
N/A
**Checklist**
=> Clarify FD limits for blocks storage

integration/getting_started_single_process_config_test.go, integration/query_frontend_test.go, pkg/api/api.go, pkg/api/handlers.go, pkg/api/middlewares.go, pkg/cortex/cortex.go, pkg/cortex/modules.go
- Simplify the querier handler code by consolidating the querier specific latency metrics and the custom handler for the internal querier into a single function.
- Separates the `querier` module into two modules: `querier` and `queryable`.
- Decouples the instantiation of the `queryrange` tripperware from the `query-frontend`
The goal of this PR is to simplify the setup of the querier and make it clearer how requests are routed to the querier when running with or without the query-frontend enabled simultaneously and to decouple the initialization of the default queryable and the initialization of the request processing/handling code.
I did my best in this PR to comment/clarify how the routing for the querier is instantiated when running standalone or as a part of …
=> feat: simplify query related modules

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/prometheus-frontend.yml, pkg/querier/frontend/frontend.go, pkg/querier/frontend/frontend_test.go
Golang `http.RoundTripper` requires to close request body (https://golang.org/pkg/net/http/#RoundTripper), so accessing request body after running roundtrip can result in two scenarios:
a) silent - Body is NopReader and no form values is reported
b) warning - Body is ReadCloser and warning pops up about accessing closed body
This PR attempts to capture form values before running roundtrip which allows us to report form values and prevents us from breaking http (content length is X but body len is 0). 
Fixes #3111
**Checklist**
PS. Let me know if I should put something in CHANGELOG regarding this.
=> Fix for #3111 Read form values and request body before sending request to RoundTripper 

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/ruler/api.go, pkg/ruler/api_test.go
**What this PR does**:  
Previously the `/prometheus/api/v1/{rules|alerts}` endpoints used
`user.ExtractOrgIDFromHTTPRequest` to read the tenant id directly from
the HTTP request headers.
This however only works in multi-tenant mode. When auth is disabled, no
such headers are needed to be set and above function returns no value.
By directly reading from the request, the HTTP auth middleware which
usually catches such cases is bypassed.
This PR changes the behavior to always read from the context instead of
the request, which always holds the correct org id as set by the middleware.
Also does these changes for the alertmanager routes.
Thanks @cyriltovena for helping me figure this out :heart: 
Fixes #3300 
Fixes #3260
**Checklist**
/cc @gotjosh @pstibrany
=> fix(ruler): properly read OrgID from context

integration/e2e/service.go, integration/e2e/util.go
**What this PR does**: this PR modifies integration tests to wait for container to be in Running state, and not just created. I've observed up to 30 seconds between container was created and actually running. Problem is that when integration tests try to get ports for container, and it's only in Created state, getting ports fails. In Running state, it succeeds.
=> Wait until container is actually running, not just created.

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go
This is an internal refactoring with no user impact. In the PR #3354 I received the feedback:
> feel like error-handling code could be clearer by using errgroup. Also splitting the concerns would help -- one goroutine doing the scan, other N goroutines doing opening. Now both are mixed.
In this PR I'm addressing this feedback splitting the logic between the "scan" and the "opening".
N/A
**Checklist**
=> Refactored TSDB opening concurrency at startup

CHANGELOG.md, tools/blocksconvert/builder/tsdb.go, tools/blocksconvert/builder/tsdb_test.go
**What this PR does**: On recent Prometheus Storage Working Group meeting, @brian-brazil has pointed out that chunks should be stored in the same order as series. While this isn't a requirement for current Prometheus, it is what Prometheus does and future optimizations may require it.
This PR fixes blocksconvert Builder to reorder chunks correctly. Unfortunately it also doubles the disk space required during the block build process (chunks are first stored randomly as they are downloaded, and reordered in the second phase).
**Checklist**
=> Blocksconvert: Fix chunks ordering in the block.

pkg/ingester/ingester_v2_test.go
Fixes the flaky test `TestIngester_flushing`
Fixes #3404
**Checklist**
=> Fix flaky TestIngester_flushing

README.md, docs/_index.md, docs/blocks-storage/learn-more.md
During the 2020 we shared a lot about Cortex, but we haven't updated the list of external resources in our doc. I'm doing it in this PR.
N/A
**Checklist**
=> Update list of talks and articles in the doc

.github/workflows/test-build-deploy.yml
When releasing 1.5.0-rc.0 the docker image is not being created, nor is the website updated. It appears that github actions is skipping the deploy job for tags, this tries to fix that.
I have no idea what I am doing with github actions, so please tell me if this is totally off base.
=> Deploy when running github action on a tag

CHANGELOG.md, pkg/ingester/ingester_v2_test.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
In past few days we experienced TSDB WAL corruption twice. Given the root cause investigation (and possible fix) is a separate issue, I've also realised we're not mapping all TSDB metrics so in this PR I'm fixing this gap.
N/A
**Checklist**
=> Expose all TSDB metrics in the ingester

CHANGELOG.md, integration/alertmanager_test.go, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go, pkg/alertmanager/multitenant.go, pkg/util/metrics_helper.go
If there is a config drift, then we won't dedupe metrics. This can be
used to monitor things. See: https://github.com/prometheus/alertmanager/issues/596
This is set by the config coordinator upstream which we dont use, hence
we're setting it manually.
**Checklist**
=> Expose the config hash as a metric.

pkg/alertmanager/alertmanager_metrics.go
Some time ago I encountered a weird bug causing not all metrics to be exposed because the order of metrics in `Collect()` and `Describe()` was not the same. Starting that time, I've always made sure they're sorted the same way, but while reviewing the PR #3388 I've noticed the alertmanager metrics are not sorted correctly, so I'm fixing it in this PR.
N/A
**Checklist**
=> Fix alertmanager metrics Describe() ordering

.github/workflows/test-build-deploy.yml, Makefile
Create a new makefile command for getting the image-tag that will accurately calculate the tag in GitHub actions or locally.
Make sure that this actions run properly deploys v1.5.0-test.1: https://github.com/cortexproject/cortex/actions/runs/336168200
=> Properly calculate image tag in GitHub Actions

Makefile, pkg/chunk/table_manager.go, pkg/compactor/blocks_cleaner.go, pkg/compactor/compactor.go, pkg/ingester/wal.go, pkg/querier/blocks_scanner.go, pkg/storegateway/bucket_stores.go, pkg/util/errors.go, tools/blocksconvert/builder/series.go, tools/blocksconvert/builder/series_iterator.go, tools/blocksconvert/builder/symbols_iterator.go, tools/blocksconvert/scanner/files.go
Cortex and Thanos vendoring are a circular dependency. Cortex depends on Thanos (for blocks storage) and Thanos depends on Cortex (for query-frontend). This is currently blocking Prometheus upgrade in both projects.
The reason is that Prometheus `MultiError` has been refactored. We can't upgrade Prometheus in Cortex because it breaks Thanos, but can't upgrade Prometheus in Thanos too because breaks Cortex. In this PR I'm interning the `MultiError` into Cortex to unblock this annoying situation and being able to upgrade Prometheus in Thanos first, and then upgrade Prometheus + Thanos in Cortex.
N/A
**Checklist**
=> Intern Prometheus MultiError to solve blocking circular dependency between Cortex and Thanos

ADOPTERS.md
Add EverQuote, Inc. to Adopters.md.  
We have been running Cortex in Production (self-hosted) for several months now.  Previously we used Cortex (hosted by Grafana Cloud) for several months as part of the POC.
=> Add EverQuote to ADOPTERS.md

CHANGELOG.md, pkg/chunk/grpc/grpc_client.go, pkg/util/grpcclient/grpcclient.go
We're not enabling gRPC keepalive for inter-service gRPC connections 😱  I guess it's time to do it. A sane hardcoded default should be fine for all cases. The gRPC storage plugin also had a timeout of 10m which looks a mistake.
_New gRPC clients introduced for the query-scheduler (https://github.com/cortexproject/cortex/pull/3374) will benefit this too._
N/A
**Checklist**
=> Ensure grpc keepalive on all clients

pkg/querier/frontend2/scheduler.go, pkg/querier/frontend2/scheduler_test.go
The test `TestSchedulerEnqueueWithFrontendDisconnect` is flaky ([CI failed here](https://github.com/cortexproject/cortex/runs/1332670597?check_suite_focus=true)). The reason is that there's no guarantee that the query-frontend disconnected from the scheduler and its request canceled before `verifyQuerierDoesntReceiveRequest` is called. The change done in this test should help to reduce this likelihood.
I also took the opportunity to:
1. Rename the metric `cortex_query_scheduler_connected_workers` to `cortex_query_scheduler_connected_querier_clients`, because:
- Now it's more clear which workers we're talking about
- In the frontend v1 the metric is called `_clients`, so I've renamed for consistency
2. Add the metric …
=> Fixed TestSchedulerEnqueueWithFrontendDisconnect flakyness

Makefile
Faillint didn't run on integration tests. Was a known issue, but didin't know how to fix. The good @fatih showed me the solution https://github.com/fatih/faillint/issues/20 and in this PR I'm fixing it. I've tried to manually introduce a failure in `./integration` and `faillint` correctly fails.
Fixes #3024
**Checklist**
=> Fixed faillint for ./integration tests

integration/asserts.go, integration/backward_compatibility_test.go, integration/e2ecortex/services.go, integration/querier_sharding_test.go, integration/query_frontend_test.go, pkg/querier/frontend2/querier_scheduler_worker.go
In this PR I've added integration tests for the query-scheduler. The diff will be easier to review if you enable "hide whitespace changes".
N/A
**Checklist**
=> Add integration test on query-scheduler

CHANGELOG.md, pkg/api/handlers.go
- Registers the Querier internal routes explicitly to ensure the instrumentation utilizes the correct route names
Fixes #3432 
**Checklist**
=> fix: register querier routes explicitly with handler for instrumentation

docs/configuration/config-file-reference.md, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
If query-frontend fails to send request to querier, or querier disconnects before sending response, scheduler now forwards error directly to frontend.
**Checklist**
=> query-scheduler: forward error directly to frontend

pkg/api/api.go, pkg/cortex/modules.go
This PR ensures the authentication middleware used by the internalQuerier is the same that is used by the API struct. I was worried this might be causing an issue with queries for single binary users with `no org id` errors, however, I manually verified it is not. Currently, this isn't causing an issue because the query-frontend will create the `x-scope-orgid` header with `fake` as a value so the `AuthenticateUser` middleware is valid. However, this will ensure any changes made to the auth middleware used by the API in the future will also be added to this internalHandler..
=> chore: ensure internalQuerier utilizes identical authMiddleware to API

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/chunk_store.go, pkg/cortex/cortex.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/util/spanlogger/spanlogger.go, pkg/util/validation/limits.go
Currently, the only option to limit the time range of queries is `-store.max-look-back-period`, but it suffers the following issues:
1. Applies to chunks storage only
2. Applies to instance/range queries only (not a strict requirement today, but we'll soon work on querying series/labels from storage in the blocks storage)
3. Can't be overridden on a per-tenant basis
In this PR I'm adding `-querier.max-query-lookback` which is expected is superseed `-store.max-look-back-period` solving the issues above. While working on tests, I've also noticed that `-querier.max-query-into-future` is currently broken (doesn't really enforce it), so I've fixed it in this PR.
Out of the scope of this PR:
- Enforcing the limit in the query-frontend too (will be done in a separate PR) …
=> Added -querier.max-query-lookback and fixed -querier.max-query-into-future

pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/frontend/frontend_test.go, pkg/frontend/v1/frontend_test.go, pkg/querier/worker/config.go, pkg/querier/worker/querier_scheduler_worker.go, pkg/querier/worker/worker.go, pkg/querier/worker/worker_frontend_manager.go, pkg/querier/worker/worker_frontend_manager_test.go, pkg/querier/worker/worker_test.go, tools/doc-generator/main.go
This is first step in querier workers refactor. There are two workers (one using frontend, one using scheduler) with lot of copied code. End-goal is to refactor common parts.
First step is only moving `querier_scheduler_worker.go` to `pkg/querier/frontend` package, and then renaming `pkg/querier/frontend` to `pkg/querier/worker`, all done via Goland refactoring. No change in logic was done.
**Checklist**
=> Querier workers refactor, step 1

pkg/compactor/compactor_test.go, pkg/distributor/distributor.go, pkg/distributor/query.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/client/ring_service_discovery.go, pkg/ring/client/ring_service_discovery_test.go, pkg/ring/model.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ruler/ruler.go, pkg/storegateway/gateway.go
In the PR #3414 we're working to add zone-awareness support to `Ring.GetAll()`. The new logic (which triggers when zone-awareness replication is enabled) is not safe to apply in all contexts where `GetAll()` is used.
The reason is that `GetAll()` is currently used for two very distinct purposes:
1. Get a view over the ring (all healthy instances)
2. Get the set of instances (ingesters) to query for a given operation
The zone-awareness logic should apply to (2) but not to (1).
In this PR, I'm proposing to split `GetAll()` into `GetAllHealthy()` (to cover case 1) and `GetReplicationSetForOperation()` (to cover case 2). The reason why I renamed `GetAll()` into `GetReplicationSetForOperation()` is so that we can signal downstream projects about this change and let them …
=> Split ReadRing.GetAll() into two functions

pkg/querier/worker/worker.go, pkg/querier/worker/worker_test.go, pkg/util/test/poll.go
**What this PR does**: This PR fixes flaky `TestResetConcurrency` test ([failure](https://github.com/cortexproject/cortex/pull/3405/checks?check_run_id=1357010241)). It has used "localhost" as address to resolve, which could add additional unexpected targets to the worker.
=> Disable DNS resolution for testing.

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/querier/querier.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/queryable_test.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/results_cache_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/split_by_interval_test.go, pkg/querier/queryrange/util.go, pkg/storage/tsdb/memcache_client_config.go, pkg/util/time.go, pkg/util/validation/limits.go
In the PR #3452 I've introduced `-querier.max-query-lookback` but I've intentionally skipped enforcing the limit in the query-frontend, in order to keep the change  set smaller. In this PR I'm enforcing it in the query-frontend too, for range queries.
The main benefit of enforcing it in the query-frontend too is to reduce the number of query range requests enqueued for a tenant, if such queries cover a range outside the max lookback. Without this PR, the limit would be enforced anyway in the querier, but we may end up with a large number of splitted queries in the query-frontend/query-scheduler queue which would be noop once executed in the querier.
N/A
**Checklist**
=> Enforced -querier.max-query-lookback in the query-frontend for range queries

CHANGELOG.md, docs/api/_index.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, docs/guides/limitations.md, integration/querier_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/querier.go
=> Query store for series lookups

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester_v2.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go
There are some use cases (eg. Cortex clusters with very small tenants) where reducing the WAL segment size may reduce the disk requirements. In this PR I'm proposing to allow to customise it.
N/A
**Checklist**
=> Expose WAL segment size setting

pkg/chunk/chunk.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_test.go, pkg/chunk/encoding/bigchunk.go, pkg/chunk/encoding/chunk.go, pkg/chunk/encoding/chunk_test.go, pkg/chunk/encoding/doubledelta.go, pkg/chunk/encoding/varbit.go
We slice a chunk when deletion interval covers a chunk partially. This PR adds support for slicing off a chunk in encodings which helps add support for deletion in Loki because it implements its own encoding for storing logs in chunks. 
There was existing `Slice` method in chunk encoding interface which is specifically built for query optimization and is a noop for some of the encodings so instead of changing that function, I have added a new method called `Rebound` which slices a chunk for a given time range.
**Checklist**
=> add support for slicing of chunk in encodings

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/frontend/frontend_test.go, pkg/ingester/ingester_v2.go, pkg/util/concurrency/buffer.go, pkg/util/concurrency/runner.go
I'm testing the compactor in a cluster with a large number of tenants (6K) and I've found out the blocks cleaner doesn't scale. The problem is that cleaning 1 tenant at a time is too slow, so I'm proposing to add concurrency to it.
N/A
**Checklist**
=> Improve compactor blocks cleaner when running with a large number of tenants

pkg/util/spanlogger/spanlogger.go, pkg/util/spanlogger/spanlogger_test.go
This PR adds functionality to the `spanlogger` package to support passing in custom log.Logger instances. This will be useful for me within [grafana/agent](https://github.com/grafana/agent) where loggers with different labels are passed around to various components. 
Signed-off-by: Robert Fratto <robertfratto@gmail.com>
=> Support custom log.Logger instances in spanlogger

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/blocks-storage/compactor.template, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_ring.go, pkg/compactor/compactor_test.go, pkg/ring/util.go, pkg/ring/util_test.go
This is like https://github.com/cortexproject/cortex/issues/2827 but for the compactor. The idea is to add the ability to wait for a stable ring at compactor startup. If this proposal is accepted, I will then work on the same for the store-gateway.
N/A
**Checklist**
=> Wait for a stable ring at compactor startup

docs/proposals/cross-tenant-query-federation.md
Signed-off-by: Christian Simon <simon@swine.de>
Add cross tenant query federation proposal
Proposal to work on a fix for #923
**Checklist**
=> Add cross tenant query federation proposal

pkg/scheduler/scheduler.go
**What this PR does**: This PR ignores `io.EOF` in FrontendLoop of query-scheduler. This is expected behaviour when query-frontend closes connection due to restart.
We see `grpc_logging.go` logging EOF error unnecessarily. When trying to add unit test for this,  instantiating `GRPCServerLog` and correct logging setup in the unit test was too much for this trivial change, so I haven't included it in the PR. It seemed that test complexity outweighed the benefit.
**Checklist**
- [no] Tests updated 
- [no] Documentation added
- [no] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Don't report io.EOF as error from FrontendLoop.

Makefile
Changes in the makefile how containers are used to mount volumes into contianer, break on my SELinux enabled Fedora workstation. This changes ensure, that the volumes are mounted using the 'z' label, which makes sure to configure them correctly to work with SELinux
**Checklist**
=> Fix makefile for SELinux enabled machines

CHANGELOG.md, tools/blocksconvert/builder/tsdb.go
**What this PR does**: when blocksconvert builder is finishing block, it needs to reorder chunks in the final block. It does that by reading chunks for each appended series (series are iterated in correct order), and writing those chunks again in correct order. This PR modifies reading process to use multiple goroutines. This was motivated by observing slowness in this phase of the process.
**Checklist**
=> blocksconvert: read chunks concurrently when finishing block

SECURITY.md
This is an RFC and no finalised. Inviting all the opinions! This is based on https://github.com/kubernetes/security/blob/master/private-distributors-list.md
=> [security] Add details about vendor announce list

development/tsdb-blocks-storage-s3/docker-compose.yml, development/tsdb-blocks-storage-s3/goland/TSDB Query-frontend (using scheduler).run.xml, development/tsdb-blocks-storage-s3/goland/TSDB Query-scheduler.run.xml, pkg/frontend/v2/frontend_scheduler_worker.go
**What this PR does**: Small fixes to query-frontend code:
- use context from the stream, not just worker context (in practice, it doesn't make a difference – it doesn't detect closed connection to the scheduler earlier)
- check for returned status when forwarding cancellation request
- fix docker-compose config for querier-with-scheduler
- added GoLand launch configs for querier-scheduler and query-frontend-with-scheduler
**Checklist**
=> Query frontend with scheduler fixes

pkg/chunk/aws/s3_storage_client.go
It seems that some client might not returns those properties.
see  https://github.com/grafana/loki/issues/2912
=> Safely check pointer in aws client before using them.

pkg/chunk/chunk_store.go, pkg/chunk/schema_test.go, pkg/chunk/schema_util.go, pkg/chunk/schema_util_test.go
This uses a buffer pool for when we parse the chunk time range value.
```
❯ benchcmp before.txt after.txt
benchmark                                      old ns/op     new ns/op     delta
BenchmarkParseIndexEntries500-16               265343        232446        -12.40%
BenchmarkParseIndexEntries2500-16              1393835       1232639       -11.56%
BenchmarkParseIndexEntries10000-16             5741372       5032199       -12.35%
BenchmarkParseIndexEntries50000-16             30158888      27272835      -9.57%
BenchmarkParseIndexEntriesRegexSet500-16       79101         50394         -36.29%
BenchmarkParseIndexEntriesRegexSet2500-16      386920        246015        -36.42%
BenchmarkParseIndexEntriesRegexSet10000-16     1570068       957154        -39.04% …
```
=> Reuse components slice when parsing chunk time range value.

pkg/chunk/aws/s3_storage_client.go
the current dummy credentials deny using EKS IAM service accounts, removing this line fallback to the AWS SDK default which is the following:
* Environment Variables
* Shared Credentials file
* Shared Configuration file (if SharedConfig is enabled)
* EC2 Instance Metadata (credentials only)
reference: https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#NewSession
**Checklist**
=> Remove dummy credentials from AWS config

CHANGELOG.md, docs/guides/zone-replication.md, integration/e2e/service.go, integration/e2ecortex/client.go, integration/zone_aware_test.go, pkg/distributor/distributor_test.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/replication_set_tracker.go, pkg/ring/replication_set_tracker_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go
Add zone awareness to the read path. A `MaxUnavailableZones` field is added to the `ReplicationSet` struct. The value of that field is derived from the number of zones.
In `ReplicationSet.Do()` the zones of the of the failing requests is taken into account for zone aware requests. If too many zones have failures then the request fails.
Unit tests for the non-zone aware invocations of `ReplicationSet.Do()` are added as well.
**Checklist**
=> Add topology aware read

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/compactor/syncer_metrics.go, pkg/ingester/metrics.go, pkg/ruler/manager.go, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/gateway_test.go, pkg/storegateway/metadata_fetcher_metrics.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
I'm testing a cluster with 3K tenants per ingester and I've noticed some wrong query results when querying some of such cluster metrics. The problem is that when we internally aggregate multiple registry metrics, the order with which such values are summed is not stable and this could lead to slightly different values returned by `/metrics` which are then detected as counter resets (eg. 1st scrape from `/metrics` returns a metric with value `13304.675369502014` then 2nd scrape returns the same metric with value `13304.67536950197` even if internally the value hasn't changed).
The fix done in this PR is basically switching from `map` to `[]` (iteration order stability is not guaranteed for maps). The remaining `map` usage in `pkg/util/metrics_helper.go` should be …
=> Fixed false counters resets for aggregated metrics

integration/zone_aware_test.go
**What this PR does**: Fixes zone_aware_test.go, to make it an integration test, and skip when running `go test ./...`.
**Checklist**
=> Added missing requires_docker tag to zone_aware_test.go

pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
This is in anticipation of thanos-io/thanos#3469 where we would need to
utilise the consistency check to query for labels as well.
=> Refactor consistency check so it can be reused

CHANGELOG.md, pkg/ruler/manager_metrics.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
**What this PR does**: This PR enhances `UserRegistries` to support "soft" removal of user-specific registry, and registration of new registry for user. Soft-removal preserves latest metric values (except for gauges) in order to avoid counter resets. This is required to keep metrics consistent when moving user around different components due to resharding.
It could be argued that once we have this, we don't need "hard" delete, as used now by Ruler.
**Checklist**
=> Support removal of registry from UserRegistries

pkg/chunk/purger/delete_requests_store.go
At first I thought `queryDeleteRequests` was creating a race because it can be called with multiple index query and querypage from the index client can run in parallel.
However then I realized that it is always used with a single query and so it will always run sequentially.
So I changed the signature to make sure we never use this with multiple queries in the future.
=> Improve delete index query signature.

pkg/alertmanager/multitenant.go
Adds a new metric to keep track of when was the last uploaded configuration successfully applied to the Alertmanager. Also, improves documentation.
**Still needs a test but wanted to see whenever this was an acceptable solution - An alternative here is that we stop the Alertmanager completely if we fail to load the last configuration and symbolise the user the configuration did not work.** 
**Checklist**
=> Alertmanager: Remove outdated comment

CHANGELOG.md, docs/api/_index.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/lifecycle_test.go, pkg/ring/lifecycler.go, pkg/ring/replication_strategy.go, pkg/ring/ring.go, pkg/ring/ring_test.go
By keeping an ingester in the ring and not writing to additional
ingesters while it is being restarted, will stop small chunks from being
persisted to other ingesters. This will allow users running with a WAL
to avoid excess load and memory during a rolling restart.
I am curious what others think of this, if accepted, I think a similar
approach could be applied to the store-gateway (issue #2823). The
downside is that scaling a cortex cluster down while running with skip
unregister will involve manual forgetting of the ingester (or automation
to do this).
Fixes: #3304
**Checklist**
=> Allow ingesters to stay in the ring during restart

docs/api/_index.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/ingester/ingester.go, pkg/ingester/lifecycle_test.go, pkg/ring/lifecycler.go, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util_test.go
@csmarchbanks did a great job in #3305 to introduce an option to avoid unregistering ingesters on shutdown. I would like to propose a couple of small changes:
1. Mark it experimental (while we gain some confidence about side effects of it)
2. Rename `-ingester.unregister-from-ring` to `-ingester.unregister-on-shutdown` for better clarity (does it?)
3. Introduce a `NewDefaultReplicationStrategy()` and unexport `defaultReplicationStrategy` to make sure whoever uses it outside the `pkg/ring` package doesn't forget to correctly configure the new `extendWrites` option
**Checklist**
=> Refactored do not unregister ingester on shutdown option

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/caching_bucket.go
I just realised we issue `Attributes()` calls on `meta.json` but we don't cache it. This PR adds support for caching `meta.json` attributes API call too, other than increasing the default attributes TTL from 1d to 7d.
N/A
**Checklist**
=> Added support to cache meta.json attributes

CHANGELOG.md, pkg/querier/blocks_store_queryable.go
I just realised the config option used to create the meta syncher was `-blocks-storage.bucket-store.block-sync-concurrency` instead of `-blocks-storage.bucket-store.meta-sync-concurrency`. In this PR I'm fixing it. I do not consider it a real breaking change because defaults are the same.
N/A
**Checklist**
=> Fixed meta.json sync concurrency config option

pkg/chunk/chunk.go
Useful if you want to re-use memory after flushing data.
=> Add chunk.EncodeTo to allow to pass your own buffer.

pkg/ring/util_test.go
The test `TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached` is flaky. I added few prints to see why it is and I found out. The output of the prints:
```
=== RUN   TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached
=== PAUSE TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached
=== CONT  TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached
2020-11-23 19:23:00.470076 +0100 CET m=+6.016058520 new check - same state since 1.000763607s
2020-11-23 19:23:01.470597 +0100 CET m=+7.016606163 new check - same state since 2.001311481s
2020-11-23 19:23:01.470643 +0100 CET m=+7.016651378 added new instance
2020-11-23 19:23:02.470561 +0100 CET m=+8.016592519 new check - different state
2020-11-23 19:23:03.469636 +0100 CET …
```
=> Fixed TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached flakyness

pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/querier/blocks_scanner.go, pkg/querier/blocks_scanner_test.go, pkg/storage/tsdb/users_scanner.go, pkg/storage/tsdb/users_scanner_test.go
A "list objects" API call is called once the iteration is done, but it's cached with the timestamp of when the iteration has started. If the iteration is slow, the caching of the "list objects" API response is not much effective. Similarly to what we already did in other components, I would like to propose to get the full list of tenants upfront in the querier (so that the response will be cached) and then sync each tenant blocks.
N/A
**Checklist**
=> Scan tenants upfront in the querier.BlocksScanner in order to improve its cacheability

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/cortex/cortex.go
Running a compactor with block range periods which are non divisible is not an issue per se, but doesn't bring the result the user may expect. To avoid mistakes, I would suggest to take a bold position in this case and do not allow block range periods which are not divisible by the previous one. I got tricked by this too and I would prefer to avoid our users get tricked too.
N/A
**Checklist**
=> Validate block range periods config in the compactor

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go, pkg/storage/tsdb/config.go
**What this PR does**: This PR adds ability for ingester to close idle TSDB and delete local data when TSDB is idle for a long time (no data is appended to it). Closing/deletion only happens if head is empty (possibly thanks to previous force-compaction due to being idle), and all blocks were shipped.
~This PR also takes care of hiding user metrics, while keeping the registry to avoid breaking the counters over all users.~ Support for metrics removal has been extracted to separate PR, https://github.com/cortexproject/cortex/pull/3511.
**Checklist**
=> Close TSDB and delete local data when TSDB is idle for a long time.

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/backend/s3/bucket_client.go, pkg/storage/backend/s3/config.go, pkg/storage/tsdb/config.go, vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go, vendor/modules.txt
- This allows to configure the block store client to use V2 signatures for S3 authentication. 
- This updates thanos to include https://github.com/thanos-io/thanos/pull/3496
**Checklist**
=> Add option to use v2 signatures for S3 blocks store

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, pkg/ruler/ruler.go
**What this PR does**: This PR exposes gRPC client configuration in ruler.  It also changes limits from previously used gRPC-[client defaults](https://github.com/cortexproject/cortex/blob/8cfa79c9265492fbd78a3d89d29e526d35e3db9b/vendor/google.golang.org/grpc/clientconn.go#L97) to Cortex-specific default values.
Fixes #3503 
**Checklist**
=> Expose gRPC client configuration in ruler

CHANGELOG.md, pkg/compactor/compactor.go
Currently we don't have a way to track the progress of on-going compaction when there are many tenants. In this PR I'm proposing to add metrics to be able to track such progress (metrics are reset to 0). I haven't added any unit test because they're pretty hard to write, given these metrics track progress and get reset 0 once the compaction run is done.
I manually tested it in a staging env.
N/A
**Checklist**
=> Added metrics to track on-going compaction

CHANGELOG.md, tools/blocksconvert/builder/builder.go, tools/blocksconvert/builder/builder_test.go
**What this PR does**: During conversion of some old data, we have found chunks that have duplicate labels written in them. As long as label values are the same, we can still convert such data.
This PR implements chunks label normalization – makes sure that labels are sorted, and removes duplicate labels. If duplicate labels have different values, it will error out.
**Checklist**
=> blocksconvert: Normalize labels from chunks.

CHANGELOG.md, pkg/ingester/ingester_v2.go
**What this PR does**: When opening existing TSDB, set last update time of TSDB to oldest timestamp from the head. This will make ingester to flush and close it sooner (unless more data is pushed to TSDB).
**Checklist**
=> Close old TSDB faster.

CHANGELOG.md, pkg/util/modules/modules.go, pkg/util/modules/modules_test.go
**What this PR does**: This PR fixes initialization order of Cortex internal module services. Recently introduced "queryable" (internal) module broke initialization of "querier", because "queryable" doesn't have any service that "querier" could wait for. But "querier" should really wait for all services that "queryable" depends on. This PR does that.
Fixes #3550
**Checklist**
=> Module needs to wait for services from all of its dependencies.

CHANGELOG.md, docs/api/_index.md, docs/configuration/v1-guarantees.md, pkg/api/api.go, pkg/chunk/purger/blocks_purger_api.go, pkg/chunk/purger/blocks_purger_api_test.go, pkg/chunk/purger/purger.go, pkg/cortex/modules.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/tenant_deletion_mark.go, pkg/storage/tsdb/tenant_deletion_mark_test.go
**What this PR does**: This PR introduces new API for tenant deletion when using blocks storage. There are two API endpoints: one to trigger tenant deletion (it really only writes mark file with tenant prefix), another one to check for status (= check for blocks).
In this PR ingester checks for tenant deletion mark, and 1) stops shipping blocks for such tenant, and 2) closes TSDB faster (if closing is enabled).
In subsequent PRs, more components will react on deletion mark:
- compactor will clean up blocks in the bucket
- ruler will clean up rule groups, and stop rule evaluation [ruler will use separate marker in its own bucket]
- alertmanager will clean up its per-tenant config and state [alertmanager will use separate marker in its own bucket]
**Checklist**
=> Tenant deletion when using blocks storage

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, pkg/alertmanager/multitenant.go, pkg/alertmanager/storage.go, pkg/chunk/aws/dynamodb_storage_client.go, pkg/chunk/aws/s3_storage_client.go, pkg/chunk/storage/factory.go, pkg/cortex/cortex.go, pkg/ruler/storage.go, vendor/modules.txt
* This allows to configure the chunks S3 client to use V2 signatures for S3 authentication (is also used for the alertmanager and ruler store).
* This follows the interface of #3540 for the blocks client
**Checklist**
=> Add signature v2 support for S3 chunks client

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_scanner.go, pkg/querier/blocks_scanner_test.go, pkg/storage/bucket/client_mock.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/users_scanner.go, pkg/storage/tsdb/users_scanner_test.go
**What this PR does**: This PR builds on #3549. In this PR, compactor component checks for tenant deletion marker, and 1) it will skip such users when doing compaction, and 2) its blocks cleaner component will actually remove all blocks for such users.
~Draft until #3549 is merged.~ Rebased on top of master.
**Checklist**
=> Tenant deletion: compactor changes

docs/proposals/blocks-storage-bucket-index.md
As previously shared in the CNCF Slack channel, I'm proposing to add a per-tenant bucket index to improve scalability of Cortex blocks storage when running a cluster with thousands of tenants. This PR is contains the design doc originally shared via [google doc](https://docs.google.com/document/d/1XCUc7Z6rWqETNZpnVvG05Axzbd--Rm_smDeknTJre2M/edit).
N/A
**Checklist**
=> Proposal: introduce bucket index for the blocks storage

pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_scanner_test.go, pkg/storage/tsdb/bucketindex/index.go, pkg/storage/tsdb/bucketindex/markers.go, pkg/storage/tsdb/bucketindex/markers_bucket_client.go, pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go, pkg/storage/tsdb/bucketindex/markers_test.go, pkg/storage/tsdb/bucketindex/reader.go, pkg/storage/tsdb/bucketindex/reader_test.go, pkg/storage/tsdb/bucketindex/writer.go, pkg/storage/tsdb/bucketindex/writer_test.go, pkg/storage/tsdb/testutil/block_mock.go
This is another preliminary step required to implement the bucket index, as designed in https://github.com/cortexproject/cortex/pull/3554. In this PR:
- Introduce bucket index reader and writer (but not plugged in yet)
- Introduce a bucket client wrapper used to store block deletion marks in the per-tenant global location too
- Plug the bucket client wrapper in the compactor (which is the component deleting blocks)
N/A
**Checklist**
=> Write block deletion marks in the global location too

CHANGELOG.md
As described in `RELEASE.md`, I'm cutting the changelog to reduce the chance of conflicts
=> chore: cut CHANGELOG for 1.6.0-rc0

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/frontend/config.go
Deprecate `-querier.compress-http-responses-deprecated` In favour of `-api.response-compression-enabled` which applies to every other API endpoint we register.
A follow up from #3536 
**Checklist**
=> [Querier] Deprecate `-querier.compress-http-responses-deprecated`

CHANGELOG.md, pkg/api/api.go, pkg/cortex/modules.go, pkg/ring/kv/memberlist/kv_init_service.go, pkg/ring/kv/memberlist/kv_init_service_test.go, pkg/ring/kv/memberlist/memberlist_client.go
**What this PR does**: This PR adds memberlist status page to Cortex. Status page shows memberlist cluster members, and some details about KV store that members are gossiping about. There is also possibility to inspect values in JSON or Go struct format, or download for offline inspection.
**Checklist**
=> Memberlist status page

docs/configuration/arguments.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go
In this PR I try to clarify that the ingester WAL config applies only to chunks storage.
N/A
**Checklist**
=> Clarify that ingester WAL config applies only to chunks storage

Makefile, website/layouts/partials/navbar.html
I finally understood the root cause of the truncated Cortex logo in the published website:
It's caused by the minification. Wasn't able to reproduce it locally because minification was disabled. I've now enabled `--minify` in `make web-serve` too and removing the minification fixes it:
N/A
**Checklist**
=> Fix Cortex logo in the website

pkg/ring/basic_lifecycler_delegates.go, pkg/ring/basic_lifecycler_delegates_test.go, pkg/ring/lifecycler.go
When we start a new replica (eg. scale up) and it's configured to load ring tokens from file we're used to log the error "error in getting tokens from file", but I believe we shouldn't log error just because the file does not exist (it's an expected case).
N/A
**Checklist**
=> Do not log error if tokens file does not exist

ADOPTERS.md
https://aws.amazon.com/prometheus/faqs/ mentions that Cortex powers the service. I'm curious if you'd be open to being listed as an adopter @ranton256
=> Add AWS to adopters list

CHANGELOG.md, pkg/ring/merge_test.go, pkg/ring/model.go
**What this PR does**: This PR fixes bug in "forget" feature when using memberlist.
When using memberlist (gossip), "forgetting" an entry doesn't delete it from the KV store, but sets entry to the "LEFT" state instead. Reason is that memberlist needs something to gossip about, and it can gossip about "LEFT" entry but not deleted entry. Unfortunately during this step, we didn't set Timestamp to current time, but reused last Timestamp of the entry. If there was already another message in the gossip network with higher timestamp, such message would eventually propagate everywhere, "resurrecting" the forgotten entry (because of higher timestamp, even though it's still in the past).
Solution is to set entry timestamp to "now" when setting entry to LEFT state.
**Checklist**
=> Memberlist: fix "forget"

pkg/ring/kv/consul/client.go
Avoids log lines like this:
```
level=error ts=2020-12-18T13:11:21.058904011Z caller=client.go:212 msg="error while rate-limiting" key=store-gateway err="context canceled"
```
**Checklist**
- NA `CHANGELOG.md` updated - don't think this merits a changelog entry.
=> Exit Consul watch on context canceled

pkg/ruler/manager.go, pkg/ruler/notifier.go
I was checking the issue reported at https://github.com/cortexproject/cortex/issues/3624. I've not been able to reproduce it (I tried adding few `time.Sleep()`), but something that popped my eyes is that `rulerNotifier.run()` should be called synchronously and not via `go n.run()`.
Maybe #3624 but not sure.
**Checklist**
=> Synchronous call to rulerNotifier.run()

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
- Final step in the 1.6.0 release
=> chore: add 1.6.0 to backwards compatibility tests

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/docker-compose.yml, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/chunk/purger/blocks_purger_api.go, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/ingester/ingester_v2_test.go, pkg/storage/bucket/bucket_util.go, pkg/storage/bucket/bucket_util_test.go, pkg/storage/tsdb/tenant_deletion_mark.go
**What this PR does**: This PR implements final tenant cleanup after some delay since last tenant's block has been deleted. Cleanup will remove all remaining marker files (including tenant deletion), and meta.json files stored under `<tenant>/debug/meta` prefix.
**Checklist**
=> Perform final tenant cleanup after last block is deleted.

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Currently, the compactor re-run compaction for all tenants in case at least 1 tenant failed. Despite re-running the compaction for a previously succeeded tenant doesn't redo the work, but considering each single compaction run needs to re-scan the bucket, this ends up to be pretty inefficient for Cortex clusters running with a large number of tenants.
In this PR I'm proposing to retry compaction on failure only for the failed tenants.
N/A
**Checklist**
=> Compactor: retry compaction of a single tenant on failure instead of re-running compaction for all tenants

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
We recently introduced a feature to close idle TSDBs ingester. Today, we realised that we were not correctly updating `cortex_ingester_memory_users` and `cortex_ingester_active_series` metrics when a tenant's TSDB is closed because idle. This PR should fix it.
N/A
**Checklist**
=> Fix metrics when a tenant TSDB is closed because idle

CHANGELOG.md, docs/guides/limitations.md, pkg/api/middlewares.go, pkg/chunk/composite_store.go, pkg/chunk/purger/tombstones.go, pkg/chunk/purger/tombstones_test.go, pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go, pkg/util/validation/limits.go
Tenant query federation PR #3250 did skip result caching for tenant query federation. This PR will implement it.
**Checklist**
=> Implement result cache for tenant query federation

pkg/querier/distributor_queryable.go
Illustration of the problem lots of spans apparently at the same level:
This PR puts `Distributor.QueryStream` under `distributorQuerier.Select`.
`distributorQuerier.Select` should really go under `querier.Select`, but that's harder to fix because we are using a Prometheus interface that doesn't have a Context parameter.
**Checklist**
- NA `CHANGELOG.md` updated
=> Put trace span from QueryStream under Select

pkg/chunk/purger/purger_test.go
Adds polling for a metric update which otherwise causes a race resulting in falky test.
Fixes #2776 
**Checklist**
=> poll for metric update to avoid race causing a flaky test

docs/blocks-storage/bucket-index.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/querier/blocks_store_queryable.go, pkg/storage/tsdb/config.go
We currently have 2 options to configure how frequently the bucket should be synced:
- `-blocks-storage.bucket-store.bucket-index.update-on-stale-interval`: used only by the querier when bucket index is enabled
- `-blocks-storage.bucket-store.sync-interval`: used by store-gateway in any case, and also by querier when bucket index is disabled
I believe this would lead to misunderstandings, so in this PR I'm proposing to remove the `update-on-stale-interval` config at all and always use `sync-interval`. The bucket index is marked as experimental, so this is not a breaking change.
_No CHANGELOG entry because bucket index was introduced after cutting `1.6.0`._
N/A
**Checklist**
=> Fix bucket index sync interval config inconsistency

CHANGELOG.md, pkg/cortex/modules.go
The issue introduced in https://github.com/cortexproject/cortex/commit/eba13a81e73d9835a9adaf29ce6d8cd0d385c44f that causes `Worker.FrontendAddress` to be overridden by the default even when set by user.
Resolves: https://github.com/cortexproject/cortex/issues/3644
Ping: @pstibrany
=> fix default incorrectly overriding FrontendAddress

pkg/ingester/ingester_v2.go
**What this PR does**: This tiny change removes initialization of `userStates` in blocks-based ingster. From what I can see, this isn't used on code paths in blocks ingester.
**Checklist**
=> Don't initialize ingester userStates in blocks ingester.

docs/configuration/arguments.md
The mirror enabled option uses `mirror_enabled` as key as you can see [here](https://github.com/cortexproject/cortex/blob/6165acfd5dcfc99aca631fce2601b2e6e663c12f/pkg/ring/kv/multi.go#L72)
No issue attached 
**Checklist**
=> Fix typo in the runtime configuration example

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_ring.go, pkg/compactor/compactor_ring_test.go, pkg/distributor/query.go, pkg/querier/blocks_store_replicated_set.go, pkg/ring/batch.go, pkg/ring/http.go, pkg/ring/lifecycler.go, pkg/ring/model.go, pkg/ring/model_test.go, pkg/ring/replication_strategy.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util.go, pkg/ring/util_test.go, pkg/ruler/lifecycle.go, pkg/ruler/ruler.go, pkg/ruler/ruler_replication_strategy.go, pkg/ruler/ruler_ring.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go, pkg/storegateway/replication_strategy.go, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go
We've been reported an high memory utilisation in the store-gateway when shuffle-sharding is enabled and the cluster has a large number of tenants and replicas. This memory utilisation increase is caused by the in-memory subring cache used by the shuffle-sharding, which is used to reduce the CPU utilisation due to the expensive computation of the subring. 
However, store-gateway, ruler and compactor use `Ring.ShuffleShard()` only to check whether a tenant/block/rulegroup belongs to their own shard and this operation is run, for each tenant, only at a regular interval (it doesn't depend on QPS). 
Disabling subring cache is a possible solution (proposed in this PR), but then CPU utilisation is expected to increase. For this reason, in this PR I've also worked to …
=> Optimised Ring.ShuffleShard() and disabled subring cache in store-gateway, ruler and compactor

CHANGELOG.md, docs/api/_index.md, docs/configuration/arguments.md, pkg/api/api.go, pkg/api/handlers.go, pkg/cortex/modules.go
This PR introduces a new endpoint that would retrieve the override configuration, per tenant, that is loaded as part of the runtime configuration
Fixes #1324
**Checklist**
=> Add HTTP endpoint to show overrides (#1324)

development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml, development/tsdb-blocks-storage-s3-gossip/config/runtime.yaml, development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-s3-single-binary/config/runtime.yaml, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/runtime.yaml, development/tsdb-blocks-storage-swift-single-binary/config/cortex.yaml, development/tsdb-blocks-storage-swift-single-binary/config/runtime.yaml
**What this PR does**: This PR adds empty runtime configuration file to devel cortex. It is done to showcase how to set it up, and to make `/runtime_config` enabled.
**Checklist**
=> Add empty runtime configuration file.

pkg/compactor/compactor.go, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/querier/blocks_store_replicated_set.go, pkg/ring/batch.go, pkg/ring/model.go, pkg/ring/model_test.go, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_replication_strategy.go, pkg/storegateway/gateway.go, pkg/storegateway/replication_strategy.go, pkg/storegateway/replication_strategy_test.go, pkg/storegateway/sharding_strategy.go
**What this PR does**: This PR refactors `ring.Operation` ~to interface~, which allows us to define new ring "operations" in packages where they are used. "Extension of replica set" logic has been moved from "replication strategy" to operation itself. "Replication strategy" is now only filtering unwanted instances.
Inspired by another operation being added in #3664.
**Checklist**
=> Move ring operations to packages where they are used.

CHANGELOG.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant_test.go
**What this PR does**: This PR disables access to `/alertmanager/metrics` path, which exposes default registerer = all Cortex metrics on given instance.
**Checklist**
=> Disable access to /alertmanager/metrics, which exposes default registerer

CHANGELOG.md, pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go
Quick but effective workaround for the case where cache contains many small extents, leading to tiny subqueries which are expensive.
The minimum allowed is passed into `partition()` so that the unit test doesn't need extensive changes.
Also added a couple of comments.
It's not really a fix, but it cures the symptom of #3648
**Checklist**
=> Query-frontend: discard cache extents under 5 minutes

.github/stale.yml
Stalebot triggers more frequently than we're able to address issues. I would propose to increase the threshold from 60d to 90d.
N/A
**Checklist**
=> Increase stalebot threshold from 60d to 90d

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/querier/store_gateway_client.go, pkg/ruler/ruler.go, pkg/util/grpcclient/grpcclient.go
In Cortex 1.3.0 and 1.4.0 we deprecated a couple of CLI flags. According to our deprecation policy, we keep the deprecated flags for 2 releases after the announcement. Given 1.6.0 has been released, we can now remove them.
N/A
**Checklist**
=> Remove flags deprecated in Cortex 1.3.0 and 1.4.0

CHANGELOG.md, integration/configs.go, integration/ruler_test.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go
When ruler evaluation delay is enabled, the upstream rule evaluation logic adds staleness markers for missing series at the actual timestamp when the evaluation is run rather than the timestamp when the series was missing: (see:
https://github.com/prometheus/prometheus/blob/6c56a1faaaad07317ff585bda75b99bdba0517ad/rules/manager.go#L647-L660).
This can cause larger gaps than there actually are, as once the data becomes available again it can't be written as it would be out-of-order.
This fix shifts those staleness marker back in time by the evaluation delay set for the individual tenant.
**Checklist**
=> fix: Stale series with ruler evaluation delay

CHANGELOG.md, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
**What this PR does**: This PR disables access to user's Alertmanager (by user, or services trying to send alert) until `MultitenantAlertmanager` has started and synced configuration for each user.
Call to tenant's AM before `MultitenantAlertmanager` is running may result in loss of configuration for this tenant.
**Checklist**
=> Disable access to Alertmanager (user, or sending alerts), if it is not running.

CHANGELOG.md, pkg/util/runtimeconfig/manager.go, pkg/util/runtimeconfig/manager_test.go
Currently, Cortex can successfully startup if the provided runtime config (typically limits overrides) is invalid. We recently had an incident because of this: we rolled out ingesters with an invalid runtime config, ingesters start up correctly, but overrides were missing causing an impact on customers. Other alerts fired pretty soon, so the impact of the incident was limited.
As a retrospective, I believe we should fast fail Cortex at startup if the provided runtime config is invalid. For example, in the case of a rolling update, ingesters would stop to rollout until fixed.
I haven't changed the behaviour of an invalid config loaded while Cortex is running because, in that case, we keep the previous config and we definitely don't want to shutdown all ingesters …
=> Fail to startup Cortex if provided runtime config is invalid

CHANGELOG.md, pkg/frontend/transport/handler.go
We learned that formatting the `query_wall_time` with the go duration unit makes harder to parse it by log aggregation and querying systems (except Loki which rocks 😄 ), so in this PR I'm changing it to seconds unit (float with nanos precision).
N/A
**Checklist**
=> Enforce seconds unit in the querier wall time log

docs/guides/authentication-and-authorisation.md
Adds a section in Auth guide that mentions cortex-tenant proxy that can be used to add tenant headers to Prometheus write requests based on labels.
**Checklist**
=> Add info about cortex-tenant to the docs in Auth guide

CHANGELOG.md, pkg/distributor/distributor_test.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Prometheus truncates remote write errors displayed in logs at 512 bytes (was increased from 256 to 512 in this [PR](https://github.com/prometheus/prometheus/pull/8017)). An user privately reported me that wasn't understanding why some series were rejected and Prometheus was logging the following:
```
ts=2021-01-19T14:30:48.352Z caller=dedupe.go:112 component=remote level=error remote_name=45f6d9 url=https://prometheus-us-central1.grafana.net/api/prom/push msg="non-recoverable error" count=99 err="server returned HTTP status 400 Bad Request: sample for 'istio_response_bytes_bucket{app_kubernetes_io_instance=\"infrabin\", app_kubernetes_io_name=\"infrabin\", connection_security_policy=\"unknown\", destination_app=\"unknown\", destination_canonical_revision=\"latest\", …
```
=> Change 'too many labels' error message to play nicely with Prometheus logs

CHANGELOG.md, pkg/storage/tsdb/bucketindex/loader.go, pkg/storage/tsdb/bucketindex/loader_test.go
While rolling out the bucket index in our of our clusters I've noticed that we have some tenants with rules but not remote writing the cluster (or started very soon to remote write so their blocks haven't been uploaded to bucket yet). Since there are no blocks in the bucket, their bucket index doesn't exist and this leads the `bucketindex.Loader` to continuously try to load their bucket index.
In this PR I'm proposing 3 changes that should relief the pressure when such edge case happens:
- Keep cached the "bucket index not found" error during background checks
- Don't increase `cortex_bucket_index_load_failures_total` on `ErrIndexNotFound` error (we already didn't do in the background check)
- In case of `ErrIndexNotFound`, update it every `UpdateOnStaleInterval` …
=> Improve bucket index loader to handle edge cases

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go
While rolling out the bucket index in our cluster we've realised the default value of `-blocks-storage.bucket-store.sync-interval` (5m) doesn't play nicely with the consistency check. The consistency check gives a grace period for blocks recently uploaded (and potentially not yet discovered by store-gateway) which is equal to 3x the sync-interval (so 15m by default). Considering a default caching TTL for the bucket index of 5m, there may be edge cases where the querier is including a recently uploaded block in the consistency check but the store-gateway hasn't loaded it yet.
To fix the default config, in this PR I'm proposing to increase the default value of `sync-interval` from 5m to 15m (which also look a better default value anyway). …
=> Changed default value of -blocks-storage.bucket-store.sync-interval from 5m to 15m

CHANGELOG.md, pkg/cortex/runtime_config.go, pkg/cortex/runtime_config_test.go, pkg/util/runtimeconfig/manager.go
We recently introduced an empty `runtime.yaml` in the local dev env setup `development/tsdb-blocks-storage-s3/config/`, but I've just realised the config fails to load because empty (no YAML node). Should an empty config be legit? If so, then this PR fixes it.
N/A
**Checklist**
=> Do not log "failed to load config" if runtime config file is empty

CHANGELOG.md, go.mod, go.sum, vendor/github.com/armon/go-metrics/.gitignore, vendor/github.com/armon/go-metrics/metrics.go, vendor/github.com/armon/go-metrics/prometheus/prometheus.go, vendor/github.com/armon/go-metrics/start.go, vendor/modules.txt
It was reported an ingester panic (https://github.com/cortexproject/cortex/issues/3721). According to the stack trace, it should be a race condition in `armon/go-metrics` which was fixed in https://github.com/armon/go-metrics/pull/109.
This PR upgrades `armon/go-metrics` to the latest version.
Fixes #3721
**Checklist**
=> Fix panic caused by race condition in armon/go-metrics used by memberlist client

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
**What this PR does**: This PR modified ingester to not update "lastUpdate" time if push request didn't contain any sample that was appended to TSDB.
Without doing this change, continuous push of bad samples will keep TSDB in memory with unflushed data. If "good" sample arrives much later, all old data will be finally put to block.
With this change, ingester will eventually flush and close such TSDB, and remove local data. After closing, next push of valid or invalid sample will reopen TSDB again (and then later close, if no valid samples arrive), but at least old samples will not be kept in the memory for a long time.
**Checklist**
=> Don't update lastUpdateTime if TSDB isn't updated.

CHANGELOG.md, pkg/ingester/ingester_test.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/storage/tsdb/config.go
Currently, there's no way to alert if any compacted block is not shipped from ingester to storage within a reasonable time. In this PR I'm proposing to introduce a new metric `cortex_ingester_oldest_unshipped_block_timestamp_seconds` tracking the unix timestamp of the oldest TSDB block not shipped to the storage yet.
N/A
**Checklist**
=> Expose a metric tracking the oldest timestamp of unshipper block in ingester

CHANGELOG.md
In the PR https://github.com/cortexproject/cortex/pull/3705, after rebasing `master`, I forgot to move the CHANGELOG entry under "master / unreleased". This PR fixes it.
N/A
**Checklist**
=> Fixed CHANGELOG entry order

CHANGELOG.md, pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go, pkg/ring/kv/metrics.go, pkg/util/metrics_helper.go
The PR https://github.com/cortexproject/cortex/pull/3668 introduced a little regression causing intentionally aborted CAS operations (by HA tracker) to be tracked as `500` in the `cortex_kv_request_duration_seconds` metric instead of `200`. The reason of this subtle bug is in the introduction of `replicasNotMatchError` (which can be returned by the `CAS()` operation function), while the previous version was returning a `httpgrpc.Errorf(http.StatusAccepted)` which is correctly converted into a `200` error code by `pkg/ring/kv/metrics.go`.
N/A
**Checklist**
=> Don't track as error an HA tracker CAS operation intentionally aborted

CHANGELOG.md, integration/query_frontend_test.go, pkg/frontend/transport/handler.go
* Creates a Util class that can be used on any handler to add server side performance information on [server-timing](https://www.w3.org/TR/server-timing/) http header 
* Return `server-timing` header with querier wall time information on query requests when `-frontend.query-stats-enabled=true`
* Return `server-timing` header with `request_duration` on any request on query-frontend
We may want to create a config to enable this feature.
Result on chrome:
Enhancement of #3595
**Checklist**
- [✓] Tests updated
- [✓] No Documentation needed
- [✓] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> QueryFrontend: Return server side performance information on server-timing header

CHANGELOG.md, pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go, pkg/ring/kv/metrics.go, pkg/util/metrics_helper.go
**What this PR does**: Picks the following bugfix PR from master and adds it to the 1.7 release branch:
- Don't track as error an HA tracker CAS operation intentionally aborted (#3745)
Signed-off-by: Ken Haines <khaines@microsoft.com>
=> Picking PR #3745 into Release-1.7 

CHANGELOG.md, docs/api/_index.md, docs/configuration/arguments.md, pkg/api/api.go, pkg/api/handlers.go, pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/util/config.go, pkg/util/yaml.go
This PR introduces a new parameter for the `/runtime_config` endpoint that will allow the user to filter the outcome and just get the non-default values of the runtime configuration.
I've tried to add tests for the `runtimeConfigurationHandler` but given that the handler depends on `runtimeConfigManager`  the tests become very complex unless we're able to mock the `runtimeConfigManager`
Fixes #3672
**Checklist**
=> Runtime config endpoint now supports diff parameter

docs/guides/shuffle-sharding.md
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
Adds a small tweak to the shuffle sharding documentation to clarify that in general, no more resources are required than the default sharding strategy.
**Checklist**
=> doc: Note on trade off between sharding strategies

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, integration/util.go, pkg/chunk/gcp/bigtable_index_client.go, pkg/chunk/gcp/bigtable_object_client.go, pkg/chunk/gcp/table_client.go, pkg/frontend/v2/frontend.go, pkg/ingester/client/client.go, pkg/querier/blocks_store_balanced_set.go, pkg/querier/blocks_store_balanced_set_test.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/querier/querier.go, pkg/querier/store_gateway_client.go, pkg/querier/store_gateway_client_test.go, pkg/querier/worker/frontend_processor.go, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/worker.go, pkg/ring/kv/etcd/etcd.go, pkg/ruler/ruler.go, pkg/scheduler/scheduler.go, pkg/util/grpcclient/grpcclient.go, pkg/util/tls/test/tls_integration_test.go, pkg/util/tls/tls.go, pkg/util/tls/tls_test.go, tools/blocksconvert/planprocessor/service.go
Increase TLS test coverage and support other TLS modes than mutual auth in Client by implementing explicit TLS enable flag.
This also adds a `tls-server-name` flag to require a specific server name instead of the hostname on the certificate.
Fixes #3062 #3063 
**Checklist**
=> Support other TLS modes than mutual auth in Client

pkg/distributor/distributor_test.go, pkg/ring/batch.go, pkg/ring/replication_strategy.go, pkg/ring/ring.go, pkg/ring/ring_test.go
The ring is currently used by a large number of services, not just ingesters, but the ring codes (and some errors) still mention "ingester". For the new logic we've added, we've named it "instance" (instead of "ingester") in recent times, but all old code still calls it "ingester".
In this chore PR I'm renaming some occurrences of "ingester" to "instance" in `pkg/ring/`. Protobuf has not been touched and same for config because LifecyclerConfig and RingConfig is actually used only by ingesters (other services use the new basic lifecycler and a custom ring config).
N/A
**Checklist**
=> Chore: renamed some pkg/ingester ingester occurrences to instance

CHANGELOG.md, pkg/api/api.go, pkg/util/push/push.go, pkg/util/push/push_test.go
Summary:
Introduces `PushFunc` and `PushWrapper` types which are used to defined a
configurable wrapper around the push function of the distributor. It is
similar to an HTTP middleware but receives the already deserialized
write request.
**Checklist**
=> Enable wrapping of distributor push.

docs/blocks-storage/production-tips.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/blocks-storage/store-gateway.template, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go
The index-header lazy loading was built in #3498 and released in Cortex 1.6.0, but we never exposed its config because we were dubious about potential side effects. We're now running in production and looks fine, so I would suggest to expose its config option.
Moreover, our confidence on bucket index has increased, so I would start recommending it in our production tips.
N/A
**Checklist**
=> Expose index-header lazy load option and recommends bucket index

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Was moved to a `WriteRequest` parameter in https://github.com/cortexproject/cortex/pull/3736
Signed-off-by: Trevor Whitney <trevorjwhitney@gmail.com>
Remove `SkipLabelNameValidation` from the distributor config as it can now be configured per request.
**Checklist**
=> skipLabelNameValidation can now be set per request so no longer needed in config

CHANGELOG.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/ruler/manager.go
Completely removes a tenant's Alertmanagers when synchronising configurations.
Before, we would "pause" the Alertmanager which would never free up the resources, and leave the Alertmanager running in-memory. 
I've also bundled a small change to a logger in the ruler that was double-logging the userID. 
NA/NA
**Checklist**
- N/A Documentation added
=> Alertmanager: Remove alertmanager instead of pausing

CHANGELOG.md, pkg/ring/client/ring_service_discovery.go, pkg/ring/client/ring_service_discovery_test.go
While checking https://github.com/cortexproject/cortex/issues/3743 I've noticed that the `ErrEmptyRing` is treated as an error, but it's actually a valid state with regards to the ring service discovery, because it just means the ring is empty. This PR fixes it.
N/A
**Checklist**
=> Fix RingServiceDiscovery logic on empty ring

CHANGELOG.md, pkg/util/log.go
We have two global loggers in Cortex. However, only one is being set. This is causing `CheckFatal` error messages in the main.go file to not be logged.
A more permanent fix is to consolidate on a single global logger or remove the use of a global logger entirely. This PR ensures they are both set to the same underlying logger as a quick fix to this issue.
**Before PR:**
```sh
$ cortex git:(fix_logger) ✗ ./cmd/cortex/cortex
level=info ts=2021-02-02T23:31:35.982989857Z caller=main.go:188 msg="Starting Cortex" version="(version=1.6.0, branch=fix_logger, revision=972bb3b1e)"
```
**After PR:**
```sh
$ cortex git:(fix_logger) ✗ ./cmd/cortex/cortex
ts=2021-02-02T23:26:24.904426209Z caller=log.go:49 test=test
level=info …
```
=> fix: ensure global loggers are set

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
In this PR I've refactored a bit the compactor to allow downstream projects to customise the compactor, specifically the grouper, planner and compactor. This refactoring is expected to be a no-op for Cortex (unless I'm introducing any bug).
N/A
**Checklist**
=> Allow downstream projects to customise compactor

pkg/ring/kv/kv_test.go
Similarly to @jtlisi, I just experienced this flaky test https://github.com/cortexproject/cortex/issues/3786 too. I noticed that the failing test is `TestList` but the rate condition is in `TestWatchPrefix`:
```
Read at 0x00c0000e4043 by goroutine 135:
testing.(*common).logDepth()
/usr/local/go/src/testing/testing.go:725 +0x151
testing.(*common).log()
/usr/local/go/src/testing/testing.go:712 +0x77
testing.(*common).Log()
/usr/local/go/src/testing/testing.go:751 +0x1d
github.com/cortexproject/cortex/pkg/ring/kv.TestWatchPrefix.func1.2()
/__w/cortex/cortex/pkg/ring/kv/kv_test.go:204 +0x3a2
```
I'm not sure of this PR fixes the flaky test, but one cause could be that `TestWatchPrefix` doesn't wait until its goroutines terminate. This means that …
=> Fix concurrency in TestWatchPrefix

CHANGELOG.md, go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/modules.txt
I fixed a 2nd race condition in the index-header lazy loader in Thanos (https://github.com/thanos-io/thanos/pull/3759) and this upgrades Thanos. It's the only change we're bringing in.
N/A
**Checklist**
=> Upgrade Thanos

docs/configuration/arguments.md
The issue #3788 may me realised that's not clear that the DNS service discovery also support "no prefix", which means the provided IP or hostname is used as is. This PR tries to clarify the doc.
Fixes #3788
**Checklist**
=> Clarify DNS service discovery

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/metrics.go, pkg/ingester/user_metrics_metadata.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
**What this PR does**: This PR does additional cleanup of in-memory data when tenant's TSDB is closed in ingester. Specifically:
- We now remove tenant's metadata still in memory, and update metadata-related metrics
- We remove all validation metrics for removed tenant.
**Checklist**
=> Cleanup tenant data in ingester

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go, pkg/util/active_user.go, pkg/util/active_user_test.go, pkg/util/metrics_helper.go, pkg/util/validation/validate.go
**What this PR does**: This PR adds tracking of active tenants to distributor. Inactive tenants will have their metrics unexported by distributor. Inactivity limit is currently hardcoded to 15 mins.
(I plan to use same technique in querier and query-frontend, but that will be separate PR)
**Checklist**
=> Cleanup metrics exported by distributor for inactive tenants

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
This PR update the ingester to emit some metrics defined in [TSDB's db.go](https://github.com/prometheus/prometheus/blob/fbe960f2c1ad9d6f5fe2f267d2559bf7ecfab6df/tsdb/db.go#L257). 
I did not emit compaction related metrics because ingester already emit compaction metrics (`prometheus_tsdb_compactions_total` and `prometheus_tsdb_compaction_duration_seconds`) from TSDB's compactor, which is enough to get an over view of the compaction status. 
For `prometheus_tsdb_symbol_table_size_bytes` and `prometheus_tsdb_storage_blocks_bytes` I decided to emit per user metric because it can help to identify "top talker" and react accordingly. 
Fixes #3799
**Checklist**
=> Add more TSDB metrics for ingester to emit

CHANGELOG.md, pkg/cortex/cortex.go, pkg/cortex/cortex_test.go
http_prefix setting doesn't have validation so in case a user sets that
setting to a value without stating with / or empty value that would prevent
cortex to start with a panic coming from the router
Signed-off-by: Mario de Frutos <mario@defrutos.org>
This PR validates the `http_prefix` setting to avoid issues passing not valid values. The original issue talked about not able to reach the enpoint if the settings was `-http.prefix='""'` but right now that returns a panic from the router:
```
panic: path must begin with '/' in path '""/api/v1/*path'
goroutine 1 [running]:
github.com/julienschmidt/httprouter.(*Router).Handle(0xc000a2e720, 0x2603f7b, 0x7, 0xc0001aea80, 0xf, 0xc0000a9c80)
/home/ethervoid/development/cortex/vendor/github.com/julienschmidt/httprouter/router …
```
=> Add validation to http_prefix setting

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
errors.Wrapf prints the message first and error later. If the message is
long then the client never prints the error itself. This fixes it.
=> Don't truncate error on long series

CHANGELOG.md, pkg/storage/tsdb/bucketindex/markers_bucket_client.go
Thanos has a function `TryToGetSize()` used by some object store clients to detect the size of the upload:
https://github.com/thanos-io/thanos/blob/c1bb8ad5fc3ebdf491aa712493da930830de27dd/pkg/objstore/objstore.go#L108
When this function is not able to guess it, upload is less performant for some backends and the application logs "could not guess file size".
In this PR I've fixed the detection of the size when we upload the deletion marks in the global markers location.
Fixes #3766
**Checklist**
=> Fixed 'could not guess file size' when uploading global deletion marks

CHANGELOG.md, cmd/thanosconvert/Dockerfile, cmd/thanosconvert/main.go, docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md, docs/configuration/v1-guarantees.md, tools/thanosconvert/thanosconvert.go, tools/thanosconvert/thanosconvert_test.go
thanosconvert is a small tool to iterate over a bucket and convert block-level metadata (in meta.json) so that it is readable by Cortex. This tool assumes that users have already copied Thanos blocks over to a destination bucket, with blocks organised by user at the top level.
This is a relatively simple serial implementation - it's pretty quick to run so making it concurrent is probably unnecessary, at least for a v1. I've only tested this with S3, but since it uses `github.com/thanos-io/thanos/pkg/objstore` it should work with all the other supported block stores. It reuses the same `pkg/storage/bucket.Config` struct for bucket configuration so should be easy to configure for users who already have the store-gateway/querier running.
It's idempotent so is safe to …
=> thanosconvert: convert block meta from Thanos to Cortex

integration/kv_test.go, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go
**What this PR does**: This PR does some small code "cleanup" in HA tracker (metrics as fields, logger), and tests (removes usage of `mtime`, uses `test.Poll`). In addition to that, there is new integration test which doesn't verify behaviour, only logs it -- it shows differences in WatchPrefix and Delete behaviour between Consul (existing keys are returned via WatchPrefix, Delete doesn't send "notification" to WatchPrefix) and etcd (existing keys are not returned via WatchPrefix, but Delete "sends" notification).
**Checklist**
=> Small HA tracker cleanup

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, integration/s3_storage_client_test.go, pkg/chunk/aws/s3_storage_client.go, pkg/chunk/aws/sse_config.go, pkg/chunk/aws/sse_config_test.go, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go
In the PR https://github.com/cortexproject/cortex/pull/3651 we've added S3 server-side encryption support for the chunks storage client. This PR adds the support (with same exact CLI flags / YAML config naming) to the blocks storage client too.
N/A
**Checklist**
=> Add S3 KMS support to blocks storage client

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, pkg/querier/queryrange/roundtrip.go
We deprecated `-querier.split-queries-by-day` in Cortex 0.4.0 but we never removed it. I guess it's time to do it.
N/A
**Checklist**
=> Removed deprecated -querier.split-queries-by-day

pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go
We noticed that we were ignoring samples if the step is 24h and this
fixes it.
=> Handle the case of large step causing single pt extents

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/limiter/rate_limiter.go, pkg/util/limiter/rate_limiter_test.go
Change the handling of the rate limiting in the distributor such that when the ingestion fails, the reservation in the rate limiter is canceled, returning the tokens for future use in the proceeding requests.
In the process, a change was made to the `util/limiter` package to use `ReserveN`. To match the semantics of `ApplyN`, we have to check the `Delay()` on the returned `rate.Reservation` is zero. I also chose to only expose a limited subset of the rate.Reservation struct (to use `CancelAt`), following from how the existing code does not expose the `x/time/rate` package.
Unit tests added to `rate_limiter_test.go` and `distributor_test.go` to check the cancel behaviour.
Fixes #3804
**Checklist**
=> Prevent failed ingestion from affecting rate limiting in distributor.

CHANGELOG.md, pkg/ingester/errors.go, pkg/ingester/ingester_test.go
Changes ingester to return error code 400 instead of 429 when per-user/per-tenant series/metadata limits are reached.
Fixes #3827
**Checklist**
=> Change ingester to return 400 instead of 429 on series/metadata limits.

pkg/querier/queryrange/results_cache.go, pkg/querier/queryrange/results_cache_test.go
* Handle the case of large step causing single pt extents
We noticed that we were ignoring samples if the step is 24h and this
fixes it.
* Handle the case of start == end better
* Address feedback
(cherry picked from commit e10ccda947f795296f501881d35631345caa7cd7)
=> (1.7 release) Handle the case of large step causing single pt extents (#3818)

pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go
We're doing experiments to reduce the store-gateway memory utilisation at query time. We would like to be able to customise the partitioner max gap size. In this PR I've exposed an option, but didn't document it until experimental.
N/A
**Checklist**
=> Allow to configure the partitioner max gap size

pkg/util/services/basic_service.go, pkg/util/services/basic_service_test.go, pkg/util/services/failure_watcher.go, pkg/util/services/service.go, pkg/util/services/services.go
**What this PR does**: This PR introduces `NamedService` interface, which extends Service with a name. `BasicService` implements this, and has new `WithName` method to set the name while service is still in `New` state. Failure watcher reports the name for failed services, if one is available.
**Checklist**
=> Introduce NamedService interface that allows service to return a name.

pkg/ingester/index/index.go, pkg/ingester/index/index_test.go
We noticed a panic in one of the Loki ingesters when flushing chunks. The stack trace was 
```
panic: runtime error: slice bounds out of range [3:2]
goroutine 114 [running]:
github.com/cortexproject/cortex/pkg/ingester/index.(*indexShard).delete(0xc004bee870, 0xc005c82340, 0xd, 0xd, 0xdd5778b83ef6a735)
/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/index/index.go:247 +0x4f6
github.com/cortexproject/cortex/pkg/ingester/index.(*InvertedIndex).Delete(0xc00090f540, 0xc005c82340, 0xd, 0xd, 0xdd5778b83ef6a735)
/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/index/index.go:85 +0x85
github.com/grafana/loki/pkg/ingester.(*Ingester).removeFlushedChunks(0xc000701400, 0xc000477040, 0xc01d7fc3c0)
/src/loki/pkg/ingester/flush.go:305 +0x245 …
```
=> fix panic in inverted index delete operation when expected fp is not present

pkg/ring/client/pool.go, pkg/ring/kv/memberlist/kv_init_service.go, pkg/ring/lifecycler.go, pkg/ring/ring.go
I've got a failure while starting an ingester (was testing a change) and the related log message was this one:
```
level=error ts=2021-02-15T16:33:16.109587214Z caller=cortex.go:412 msg="module failed" module=ingester-service err="ingester subservice failed: service &{0xc00098ad80 {{{memberlist  {{consul.cortex-tsdb-dev.svc.cluster.local:8500  20000000000 false 1 1 0 0} {[] 10000000000 10 false {    false}} {  false 2000000000 0x1ecd770} 0x1ece9c0} <nil>} 600000000000 3 false false} 512 5000000000 0 0 60000000000 [eth0 en0] 30000000000 /data/tokens  false  0 ingester-5 9095} 0xc0009c2a80 0xc0009c93c0 0xc0009f6cc0 ingester-5 10.33.2.240:9095 ingester ring  0xc0003ae7b0 0xc0003ae7b8 {{0 0} 0 0 0 0} 2 [12255184 13449740 32266504 62155055 79422406 94121876 107746039 …
```
=> Name services for better logging on failure

docs/guides/shuffle-sharding.md
Adds an FAQ section for shuffle sharding with a question about KV store overhead.
Question was originally answered in Slack: https://cloud-native.slack.com/archives/CCYDASBLP/p1613606128352500
**Checklist**
=> doc: add shuffle sharding FAQ

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/query.go
**What this PR does**: This PR moves globally-registered metrics used by Distributor to Distributor struct. 
**Checklist**
=> Move distributor metrics to Distributor struct.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go
**What this PR does**: This PR implements deletion of cached shuffle-sharded subring in distributor, when user is inactive. In other components we don't need to do this, since we don't cache shuffle-sharded subrings in them.
**Checklist**
=> Delete cached shuffle-shard subring when user is inactive.

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/configs.go, integration/ruler_test.go, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/ruler/rulestore/bucket_client.go, pkg/ruler/rulestore/bucket_client_test.go, pkg/ruler/rulestore/config.go, pkg/storage/bucket/client.go, pkg/storage/bucket/prefixed_bucket_client.go
- Implement a rulestore client using the Thanos objstore client
Related #2262 
**Checklist**
=> RuleStore: implementation using thanos objstore bucket client

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
**What this PR does**: This PR implements cleanup of meta-sync files on compactor, after compactor discovers that it no longer "owns" the given user.
**Checklist**
=> Cleanup meta sync files in compactor for un-owned users.

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/metadata_fetcher_metrics.go
**What this PR does**: This PR implements cleanup of local sync directories for users that no longer belong to store-gateway shard. (~Tests are still missing here, but logic should be solid.~ Added tests.)
Fixes #3698
**Checklist**
=> Cleanup local sync dirs for users that don't belong to store-gateways shard anymore.

docs/blocks-storage/production-tips.md
The issue #3841 made me realise we haven't added an entry about disabling global markers migration in the production tips, so this PR adds it.
N/A
**Checklist**
=> Mention to disable marks migration in compactor production tips

CHANGELOG.md
Warn louder about the problem in #3841 and #3794
=> Warn in CHANGELOG to disable mark migration

Makefile, cmd/cortex/main.go, pkg/api/handlers.go, pkg/cortex/modules.go, pkg/querier/astmapper/parallel.go, pkg/querier/blocks_store_balanced_set.go, pkg/querier/chunk_tar_test.go, pkg/querier/duplicates_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/queryrange/promql_test.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/results_cache_test.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/remote_read.go, pkg/querier/remote_read_test.go, pkg/querier/worker/frontend_processor_test.go, pkg/querier/worker/worker_test.go
- Remove the util_log.Logger from all files in the querier package and subpackages.
- Add a faillint rule to trigger when the global logger is used in the querier package.
Related #3779
=> chore: remove global logger from the querier package

Makefile, integration/chunks_storage_backends_test.go, pkg/chunk/purger/tenant_deletion_api_test.go, pkg/cortex/modules.go, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/ruler_ring.go, pkg/ruler/ruler_test.go, pkg/ruler/rules/objectclient/rule_store.go, pkg/ruler/rules/objectclient/rule_store_test.go, pkg/ruler/storage.go
- Removes the global logger from the ruler package
- Adds a faillint rule for usage of the global logger in the ruler package
Slowly working to complete #3779
=> chore: remove global logger from the ruler package

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
**What this PR does**: Adds v1.7.0 to the back-compatibility tests executed by the build pipeline
=> Adding v1.7.0 to back-compat tests & github actions

integration/e2e/util.go, integration/e2e/util_test.go
I've got an integration test failing because of the timestamp comparison (the expected timestamp was diff by 1 millis). After some investigation I've found out there 1 case where `TimeToMilliseconds()` used in integration tests doesn't actually match the rounding done in Prometheus. The case is when the nanoseconds part of the timestamp is like `xxx500000`.
This PR fixes it, using the same exact formula used by Prometheus. The test cases have been created running the Prometheus code.
N/A
**Checklist**
=> Fixed TimeToMilliseconds() used in integration tests

pkg/cortexpb/compat.go, pkg/cortexpb/timeseries.go, pkg/cortexpb/timeseries_test.go
This commit adds functions to retrieve items from both poolsi in `cortexpb` package.
`ToWriteRequest` already exposes entities (slice of PreallocTimeseries and \*TimeSeries) retrieved from the pool, and encourages usage of ReuseSlice on them, however there was no way to obtain them without using that function.
If that package's user wants to build a WriteRequest itself (for example, if more than one Sample per metric is desired) then it's useful to retrieve those slice and struct pointers from the pool.
**Checklist**
=> Add functions to access cortexpb pool

pkg/storage/bucket/prefixed_bucket_client.go, pkg/storage/bucket/user_bucket_client.go
This is just an internal refactoring PR to use `PrefixedBucketClient` in `UserBucketClient`.
N/A
**Checklist**
=> Refactoring: use PrefixedBucketClient in UserBucketClient

CHANGELOG.md, pkg/ruler/rulestore/bucket_client.go, pkg/ruler/rulestore/bucket_client_test.go
In the PR https://github.com/cortexproject/cortex/pull/3867 I've backported the recursive `bucket.Iter()` support. In this PR I'm using it to optimise `BucketRuleStore` implementation.
Few other changes done along the way to `BucketRuleStore`:
- Refactored generateRuleObjectKey() for better clarity
- Updated functions comments
- Added 'user' to all logs
N/A
**Checklist**
=> Use recursive iter in ruler store client

pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
**What this PR does**: it avoids allocation a new `label.Builder` in the loop when `GetLabels` is called. This small change improves runtime for this particular method up to 50%:
```
pkg: github.com/cortexproject/cortex/pkg/util
BenchmarkGetLabels_SmallSet
BenchmarkGetLabels_SmallSet-8   	  273496	      3827 ns/op
PASS
pkg: github.com/cortexproject/cortex/pkg/util
BenchmarkGetLabels_MediumSet
BenchmarkGetLabels_MediumSet-8   	     654	   1624579 ns/op
PASS
```
```
pkg: github.com/cortexproject/cortex/pkg/util
BenchmarkGetLabels_SmallSet
BenchmarkGetLabels_SmallSet-8   	  407936	      2681 ns/op
PASS
pkg: github.com/cortexproject/cortex/pkg/util
BenchmarkGetLabels_MediumSet
BenchmarkGetLabels_MediumSet-8   	    1357	    853821 ns/op
PASS
```
**Checklist**
- ~[ ] …
=> avoid allocating new label Builder in loop

.gitignore
To tidy up my screen.
There is a second group of lines with comment `# Binaries built from ./cmd`, but I couldn't work out what that was for so I left it alone.
=> Add thanosconvert binary to .gitignore

pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This allows Limits objects to be included in JSON HTTP APIs by
downstream Cortex consumers.
Command run to update the tags:
```
perl -pi -e 's/`yaml:"([\w,\-]+)"/`yaml:"$1" json:"$1"/' pkg/util/validation/limits.go
```
**Checklist**
=> Add JSON tags to Limits object for JSON serialization

go.mod, go.sum, vendor/modules.txt
In the PR #3379 I've switched to forked version of opentracing instrumentation to fix a panic. The PR https://github.com/opentracing-contrib/go-grpc/pull/12 has been just merged, so we can remove the fork and get back to the upstream one. No code changes because only my commit has been merged since then.
N/A
**Checklist**
=> Upgrade opentracing dependency to remove fork

docs/guides/ingesters-rolling-updates.md, docs/guides/ingesters-scaling-up-and-down.md
Scaling up ingesters is easy, but scaling down is tricky, especially when running the blocks storage. This PR attempts to document it.
Fixes #3104
**Checklist**
=> Documented how to scale up / down ingesters

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/util/validation/limits.go
Implement per-tenant retention periods by performing block deletion in the Compactor.
Note that I've split the change into three commits to make reviewing it easier:
1) Add the new configuration
2) Add the new metrics
3) The change + unit tests
Fixes #3622 
**Checklist**
=> Per-tenant retention periods

go.mod, go.sum, pkg/storegateway/bucket_index_metadata_fetcher.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/chunk_bytes_pool.go, pkg/storegateway/chunk_bytes_pool_test.go, pkg/storegateway/metadata_fetcher_filters.go, pkg/storegateway/metadata_fetcher_filters_test.go, vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go, vendor/github.com/thanos-io/thanos/pkg/pool/pool.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/modules.txt
In the PR https://github.com/cortexproject/cortex/pull/3625 I had to duplicate some internal Thanos code to track metadata fetcher metrics. I then submit a couple of Thanos PRs (https://github.com/thanos-io/thanos/pull/3660 and https://github.com/thanos-io/thanos/pull/3842) to expose it and in this PR I'm upgrading Thanos to reuse it.
N/A
**Checklist**
=> Reuse FetcherMetrics from Thanos

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
Hi, i think we should return 422 instead of 500 when a query hits the max_chunks_per_query limits
Return 422 instead of 500 when a query hits the max_chunks_per_query limits
Same type of error is used [here](https://github.com/cortexproject/cortex/blob/master/pkg/querier/querier.go#L339) with `max_query_length` limit and this error is translated to 422 as explained [here](https://github.com/cortexproject/cortex/blob/master/pkg/api/queryable.go#L35)
**Checklist**
=> Returning 422 (instead 500) when query hit max_chunks_per_query limit with block storage

CHANGELOG.md, pkg/frontend/v1/frontend.go, pkg/frontend/v1/frontend_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/scheduler.go
Instrument the query-frontend and query-scheduler to track the queries that were discarded because of the configured outstanding queries rate limiter. I pre-emptively added a reason label to allow for flexibility in adding other reasons for why a query may be discarded.
**Checklist**
=> feat: instrument the query layer to track rate-limited queries

pkg/alertmanager/distributor.go
At the moment the error ends up getting overwritten/obscured by the `This should not happen` error handling a few lines further down. This ensures that the original error isn't stomped on.
**Checklist**
=> Fix missing return after writing sharding error

CHANGELOG.md, pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/alertmanager/alertstore/configdb/store.go, pkg/alertmanager/alertstore/local/store.go, pkg/alertmanager/alertstore/local/store_test.go, pkg/alertmanager/alertstore/objectclient/store.go, pkg/alertmanager/alertstore/store.go, pkg/alertmanager/alertstore/store_test.go, pkg/alertmanager/api_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/ruler/rulestore/store.go, pkg/util/concurrency/runner.go, pkg/util/concurrency/runner_test.go
There are two bottlenecks in the alertmanager configs loading from the object storage:
1. Configs are loaded sequentially
2. When alertmanager sharding is enabled, we load configs for all users, regardless they're owned by the alertmanager replica
This PR addresses both issues. To do it I had to refactor the `AlertStore` interface to split between the listing of users and loading of configs for the owned users:
1. Removed `ListAlertConfigs`
2. Added `ListAllUsers` and `GetAlertConfigs` (reason why I've added `GetAlertConfigs` instead of calling `GetAlertConfig` for every user is because with `GetAlertConfigs` the configdb implementation is optimised)
3. Added concurrent fetching to `GetAlertConfigs` in the object store client implementations …
=> Optimise alertmanager config loading

CHANGELOG.md, docs/configuration/v1-guarantees.md, integration/querier_streaming_mixed_ingester_test.go, pkg/chunk/encoding/chunk_test.go, pkg/chunk/encoding/factory.go, pkg/chunk/encoding/prometheus_chunk.go, pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/ingester/lifecycle_test.go, pkg/querier/batch/batch_test.go, pkg/querier/batch/chunk_test.go, pkg/querier/distributor_queryable.go, pkg/querier/querier_test.go
**What this PR does**: This PR implements streaming of TSDB chunks from blocks-based ingester to querier. It reuses chunks-based querier, and just introduces new type of chunk: read-only wrapper around TSDB chunk.
~State of PR: manual testing shows that it works, unit tests not updated yet.~
PR is ready for review. Feature is currently protected by the flag (both CLI and runtime-config to avoid rollout of ingesters when playing with this), but will be enabled by default in the future.
Fixes #3831
**Checklist**
=> Stream chunks from blocks-ingester to querier

docs/chunks-storage/ingesters-with-wal.md
User did not understand that the page on WAL storage does not apply to blocks.
Ref https://cloud-native.slack.com/archives/CCYDASBLP/p1614849933207700?thread_ts=1614828385.205500&cid=CCYDASBLP
=> Clarify that chunks WAL is different to blocks

CHANGELOG.md, pkg/api/api.go
If the legacy prefix is an empty string, it's interpreted as a handler for `/*`. Any handlers added afterwards are silently ignored, so requests to `/api/v1/alerts` are routed to the legacy handler, rather than to `am.*UserConfig` as would be expected. Meanwhile any handlers added BEFORE the `/*` legacy handler still work as expected - making this very difficult to debug!
Signed-off-by: Nick Parker <nick@nickbp.com>
**Checklist**
=> alertmanager: Avoid breaking /api/v1/alerts if legacy prefix is empty

CHANGELOG.md, docs/guides/encryption-at-rest.md, docs/guides/encryption-at-rest.template, pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/alertmanager/alertstore/store_test.go
After preliminary refactoring PRs, we can finally add S3 SSE support to alertmanager with per-tenant key support.
Due to the special nature of the objects structure used by `AlertStore` (the user ID is not a prefix but the object, so the alertmanager config for user-1 is stored in the object `alerts/user-1`) I had to some refactoring in `UserBucketClient` and `PrefixedBucketClient`.
_I've manually tested it with S3 + KMS and looks working fine._
N/A
**Checklist**
=> Added S3 SSE support to alertmanager storage

pkg/ruler/ruler.go
The grpc upgrade in #3884 has broken the ruler rules API endpoint:
```
msg="GET /api/prom/api/v1/rules (500) 4.012183ms Response: \"{\\\"status\\\":\\\"error\\\",\\\"data\\\":null,\\\"errorType\\\":\\\"server_error\\\",\\\"error\\\":\\\"unable to retrieve rules from other rulers, rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil\\\"}\"
```
This PR fixes it. An integration test will be added once #3916 gets merged, but this PR has been manually tested.
N/A
**Checklist**
=> Fix ruler API

CHANGELOG.md, docs/api/_index.md, pkg/alertmanager/alertstore/store.go, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/api/api.go
**What this PR does**: This PR adds new endpoints in alertmanager for deleting user's configuration.
**Checklist**
=> Expose deletion of AM config via /multitenant_alertmanager/delete_tenant_config

CHANGELOG.md, integration/configs.go, integration/e2ecortex/client.go, integration/ruler_test.go, pkg/ruler/api_test.go, pkg/ruler/client_pool.go, pkg/ruler/client_pool_test.go, pkg/ruler/ruler.go
The ruler `/api/prom/api/v1/rules` is pretty slow in our clusters:
The `/api/prom/api/v1/rules` endpoint is handled by the ruler's `API.PrometheusRules()`. When sharding is enabled, rules are fetches sequentially from rulers so in this PR I'm proposing to concurrently fetch them from all rulers. Along the way, I've also introduced the usage of a clients pool (like we already have in other places) and an integration test.
N/A
**Checklist**
=> Ruler: optimised <prefix>/api/v1/rules and <prefix>/api/v1/alerts

integration/alertmanager_test.go
Most CI runs fail because of `TestAlertmanagerSharding` which is showing the replication logic is buggy (see https://github.com/cortexproject/cortex/issues/3927). Sharding is still under development and not ready yet, so I think it's better to skip that test to unblock other PRs.
N/A
**Checklist**
=> Skip TestAlertmanagerSharding to unblock Cortex development

pkg/alertmanager/alertmanager.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
Use BasicService in state_replication.go for replication loop.
Original discussion:
https://github.com/cortexproject/cortex/pull/3839#discussion_r587597694
**Checklist**
=> Use BasicService in state_replication.go for replication loop.

go.mod, go.sum, pkg/alertmanager/alertmanager.go, pkg/alertmanager/state_replication.go, vendor/github.com/prometheus/alertmanager/cluster/cluster.go, vendor/github.com/prometheus/alertmanager/notify/notify.go, vendor/modules.txt
Pass context to WaitReady of alertmanager Peer interface.
Original discussion:
https://github.com/cortexproject/cortex/pull/3839#discussion_r586179451
Depends on: https://github.com/prometheus/alertmanager/pull/2509
**Checklist**
~~- [X] Tests updated~~
~~- [X] Documentation added~~
~~- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~
=> Pass context to WaitReady of alertmanager Peer interface.

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/rules.yaml, pkg/alertmanager/alertmanager.go, pkg/alertmanager/api.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
**What this PR does**: This PR implements cleanup of local files on alertmanager when AM is no longer running for given user.
**Checklist**
=> Cleanup obsolete local files for alertmanager.

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/cache/memcached_client.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Add `max_item_size` support to Cortex Memcached client.
**Checklist**
=> Support memcached max_item_size

pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
To replicate state using the ring, the `state` struct needs to make
calls back into MultitenantAlertmanager. Currently there are only two
calls, but more will be needed shortly. This commit passes an interface
instead of the functions.
**Checklist**
=> Use an interface for callbacks into MultitenantAlertmanager.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/limiter/rate_limiter.go, pkg/util/limiter/rate_limiter_test.go
We had an incident with a customer remote writing an high volume of out of order samples, which basically bypassed the rate limit because of the changes done in #3825 and the issue described in #3890.
Given we want to improve the rate limit, I would suggest to quickly rollback #3825 and take more time to properly address the ingestion rate limit. I think we should backport this rollback to 1.8 too. /cc @pstibrany 
N/A
**Checklist**
=> Revert "Prevent failed ingestion from affecting rate limiting in distributor. (#3825)"

pkg/alertmanager/distributor.go, pkg/alertmanager/multitenant.go, pkg/compactor/compactor.go, pkg/distributor/distributor.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/batch.go, pkg/ring/client/ring_service_discovery.go, pkg/ring/client/ring_service_discovery_test.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ruler/ruler.go
As part of my low priority work on https://github.com/cortexproject/cortex/issues/2723, in this PR I've removed the "ingester" naming from `ReplicationSet`.
N/A
**Checklist**
=> Chore: remove ingester naming from ReplicationSet

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, docs/guides/sharded_ruler.md, pkg/alertmanager/multitenant.go, pkg/ruler/ruler.go, pkg/ruler/storage.go, tools/doc-generator/main.go
We've rolled out the new ruler storage config in our cluster and so far looks good. I would like to do the next step which is marking the old config as deprecated and the new one as stable (will be effective only once 1.9 will be released so about 5 weeks from now).
N/A
**Checklist**
=> Deprecate old ruler storage config

pkg/alertmanager/multitenant_test.go
Allow testing of alertmanager gRPC replication in multitenant_test.go.
Use a fake implementation of the alertmanager ClientPool to connect
together the alertmanager instances in the multitenant_test.go unit
test. This allows testing of the replication logic without relying on
doing do at integration test level, and without having the weight of the
gRPC server running.
**Checklist**
=> Allow testing of alertmanager gRPC replication in multitenant_test.go.

pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/ingester/user_state.go, pkg/util/validation/validate.go
Given Prometheus truncate logs to the first 512 characters (see https://github.com/prometheus/prometheus/pull/8017) it's important to put most valuable information at the beginning of the error messages. I took another look if it's true for all distributor and ingester errors and I think it is.
I've just found the timestamp too new/old error format which could be reversed (done in this PR). I also took the opportunity to:
- Directly return the TenantID() error instead of generating a new one
- Reuse a shared error for 'ingester stopping'
N/A
**Checklist**
=> Improve formatting of timestamp too new/old error

pkg/alertmanager/multitenant.go
Propagate error returned from TenantID().
=> Propagate error returned from TenantID().

pkg/alertmanager/alertmanager.go
Check a type assertion in alertmanager.go which could fail if one alertmanager was configured with ring-based replication (sharding) enabled, and another configured without it enabled.
=> Check type assertion in alertmanager.go

CHANGELOG.md, pkg/ingester/errors.go, pkg/ingester/ingester_test.go, pkg/ingester/ingester_v2.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/user_metrics_metadata.go, pkg/ingester/user_state.go
Following up the PR https://github.com/cortexproject/cortex/pull/3969, in this PR I'm optimizing the `v2Push()` when an high volume of per-user/series limit is reached.
In the profile I've seen much CPU and memory is consumed formatting the `Limiter` error. The idea in this PR is to return static errors from `Limiter`, offer a `FormatError()` function and then format only the 1st partial error in `v2Push()`.
_Metadata and chunks storage hasn't been changed._
**Benchmark:**
The benchmarks are on top of https://github.com/cortexproject/cortex/pull/3969 (I merged #3969 first and then worked on this PR):
```
_Ingester_v2PushOnError/failure:_per-user_series_limit_reached,_scenario:_no_concurrency-12        1.19ms ± 0%    0.63ms ± 1%  -46.91%  (p=0.008 n=5+5) …
```
=> Optimize ingester Push() on blocks storage when the per-user or per-metric series limit is reached

CHANGELOG.md, go.mod, go.sum, pkg/api/handlers.go, pkg/api/queryable_test.go, pkg/ruler/compat.go, vendor/github.com/prometheus/prometheus/pkg/exemplar/exemplar.go, vendor/github.com/prometheus/prometheus/promql/parser/ast.go, vendor/github.com/prometheus/prometheus/promql/test.go, vendor/github.com/prometheus/prometheus/rules/manager.go, vendor/github.com/prometheus/prometheus/rules/recording.go, vendor/github.com/prometheus/prometheus/scrape/scrape.go, vendor/github.com/prometheus/prometheus/storage/fanout.go, vendor/github.com/prometheus/prometheus/storage/interface.go, vendor/github.com/prometheus/prometheus/storage/remote/client.go, vendor/github.com/prometheus/prometheus/storage/remote/write.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/exemplar.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/github.com/prometheus/prometheus/util/teststorage/storage.go, vendor/github.com/prometheus/prometheus/web/api/v1/api.go, vendor/modules.txt
I've got an optimization merged in Prometheus https://github.com/prometheus/prometheus/pull/8620, so in this PR I'm upgrading it to pick up the benefits:
```
name                                                                                             old time/op    new time/op    delta
_Ingester_v2PushOnError/failure:_out_of_order_samples,_scenario:_no_concurrency-12                  284µs ± 1%     296µs ±10%     ~     (p=0.222 n=5+5)
_Ingester_v2PushOnError/failure:_out_of_order_samples,_scenario:_low_concurrency-12                6.08ms ± 6%    6.34ms ± 9%     ~     (p=0.548 n=5+5)
_Ingester_v2PushOnError/failure:_out_of_order_samples,_scenario:_high_concurrency-12               70.1ms ±21%    71.4ms ± 4%     ~     (p=0.310 n=5+5) …
```
=> Upgraded Prometheus to further optimize ingester Push() on limits exceeded

CHANGELOG.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
Fix race condition when opening and closing tsdb concurrently.
Before this change, we had a potential race condition where we released the userState lock before actually deleting the local directory, while ingester received a new request and is trying to create a new TSDB.
We could see on our log the following errors/warns:
```
level=error ts=2021-03-13T17:35:58.129738177Z caller=ingester_v2.go:1759 msg="failed to delete local TSDB" user=tenant_id err="unlinkat /data/tsdb/tenant_id/wal: directory not empty"
...
...
level=warn ts=2021-03-13T17:35:58.424349159Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=303.330741ms err="user=tenant_id: failed to open TSDB: /data/tsdb/tenant_id: repair corrupted WAL: cannot handle error: open WAL segment: 412: …
```
=> Fix race condition when opening and closing tsdb concurrently

go.mod, go.sum, vendor/github.com/prometheus/prometheus/config/config.go, vendor/github.com/prometheus/prometheus/promql/engine.go, vendor/github.com/prometheus/prometheus/storage/interface.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/modules.txt
Another PromQL engine optimization https://github.com/prometheus/prometheus/pull/8594 has been merged, which I would like to pick up in Cortex.
N/A
**Checklist**
=> Upgrade Prometheus to pick 8594

CHANGELOG.md, pkg/frontend/transport/roundtripper.go, pkg/querier/queryrange/marshaling_test.go, pkg/querier/queryrange/query_range.go, pkg/querier/queryrange/query_range_test.go
I took a quick look at #3963 to see if there was any low-hanging fruit. In this PR I'm reducing the memory allocations when deserializing the `PrometheusResponse`. Not a big win, but still worthwhile.
```
name                               old time/op    new time/op    delta
PrometheusCodec_DecodeResponse-12     246ms ± 2%     241ms ± 0%   -1.95%  (p=0.008 n=5+5)
PrometheusCodec_EncodeResponse-12     314ms ±10%     308ms ± 2%     ~     (p=1.000 n=5+5)
name                               old alloc/op   new alloc/op   delta
PrometheusCodec_DecodeResponse-12     134MB ± 0%      96MB ± 0%  -28.31%  (p=0.008 n=5+5)
PrometheusCodec_EncodeResponse-12     229MB ±26%     248MB ±32%     ~     (p=0.690 n=5+5)
name                               old allocs/op  new allocs/op …
```
=> Small optimization to PrometheusResponse marshalling

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/validation/errors.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Following up the work done in ingesters to optimize the unhappy path (#3969 #3971 #3973), in this PR I'm introducing a benchmark for the `Distributor.Push()` on validation error and optimizing it.
Contrary to the ingester, for the distributor I didn't pick the path of returning static errors from `ValidateLabels()` and `ValidateSample()` and then offer a function to format them because the formatting function ended up to replicate the validation logic too. What I'm proposing in this PR is returning a `ValidationError` which can be converted to HTTPGRPC error. We still have 1 allocation for each series/sample but, as you can see from the benchmark, the impact is minimal: the real optimization is not having to format an httpgrpc error each time.
**Benchmark:**
``` …
```
=> Optimize distributor push on error

pkg/api/api.go, pkg/api/handlers.go
Signed-off-by: ChinYing-Li <chinying.li@mail.utoronto.ca>
Properly concatenates url
Fixes #2643.
I am not sure whether this counts as a BUGFIX or a ENHANCEMENT.
Any suggestion is appreciated!
**Checklist**
=> Use path.Join to concatenate prefix and folder string (#2643)

CHANGELOG.md, pkg/ring/ring.go, pkg/ring/ring_test.go
Fix an issue where extended write does not return all the available instances.
If we checked ingester-1 that's in `az-A`, and it's not active. We'll add `az-A` to distinct zones in the subsequent loops, we'll never check ingesters in  `az-A` again.
**Checklist**
=> fix issue where we are not returning all the available ingesters in the ring

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/extract/extract.go, pkg/util/validation/validate.go
https://github.com/cortexproject/cortex/pull/3990 had the subtle con that the series labels are retained in the `ValidationError`. Instead of trying to solve it (which could undo the performance benefit got in that PR) I'm proposing to document it and leverage on it to further optimize the metric name extraction.
```
name                                                      old time/op    new time/op    delta
Distributor_Push/too_many_labels_limit_reached-12           1.26ms ± 1%    1.23ms ± 0%   -2.13%  (p=0.008 n=5+5)
Distributor_Push/max_label_name_length_limit_reached-12     4.97ms ± 1%    4.95ms ± 0%     ~     (p=0.190 n=5+4)
Distributor_Push/max_label_value_length_limit_reached-12    2.96ms ± 0%    2.94ms ± 2%     ~     (p=0.190 n=4+5) …
```
=> Optimized metric name extraction in distributor

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertstore/config.go, pkg/alertmanager/multitenant.go, tools/doc-generator/main.go
In #3888 we introduced the new alertmanager storage config. In this PR I'm proposing to deprecate the old storage config, so that it will be officially marked as deprecated in Cortex 1.9 and then removed in 1.11.
N/A
**Checklist**
=> Deprecated old alertmanager storage config

integration/alertmanager_test.go, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanagerpb/alertmanager.pb.go, pkg/alertmanager/alertmanagerpb/alertmanager.proto, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go
Implements setting the alertmanager state by obtaining copies of the full state from replicas over gRPC. This is only used when the new "Sharding" mode of alertmanager is enabled, and is otherwise unused.
The work is broken up into commits, which can be broken out into separate PRs if preferred, as each change is tested independently with unit tests.
Depends on: #3958 
Fixes: #3927
**Checklist**
=> Implement gRPC based initial state settling in alertmanager.

CHANGELOG.md
Following up the comment https://github.com/cortexproject/cortex/pull/3989#issuecomment-803920425 by @bboreham, in this PR I'm adding a CHANGELOG entry to group PromQL engine optimizations. Not sure if we should be more specific or a generic message is enough.
N/A
**Checklist**
=> Added CHANGELOG entry for PromQL engine optimizations

CHANGELOG.md, tools/blocksconvert/builder/builder.go, tools/blocksconvert/builder/tsdb.go, tools/blocksconvert/builder/tsdb_test.go
Run with `-builder.timestamp-tolerance=5` to adjust sample timestamps by up to 5ms to align them to an exact number of seconds apart, thereby reducing the size of blocks in memory or on disk.
Prometheus started doing this in version 2.22, so this option is most useful for data gathered from older versions.
See https://github.com/prometheus/prometheus/issues/7846 for background info.
I have not run before/after tests with this code; I didn't know how to re-run over the same data and keep both versions for comparison.
=> blocksconvert: optionally reduce timestamp jitter

pkg/alertmanager/multitenant.go
Apply some review comments to the `UpdateState` code in `multitenant.go` as were applied to `ReadState`.
https://github.com/cortexproject/cortex/pull/3925#discussion_r596228171
https://github.com/cortexproject/cortex/pull/3925#discussion_r596232220
https://github.com/cortexproject/cortex/pull/3925#discussion_r596233748
=> Apply review comments consistently to alertmanager/multitenant.go

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
**What this PR does**: This PR adds Cortex 1.8.0 to backwards compatibility test.
=> Add Cortex 1.8.0 to backward_compatibility_test.go.

RELEASE.md
**What this PR does**: This PR updates release document, to make sure that merging of release branch to master is done via PR.
=> Update release document on merging release branch to master

development/tsdb-blocks-storage-s3-gossip/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3-gossip/config/prometheus.yaml, development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml, development/tsdb-blocks-storage-s3/config/grafana-agent.yaml, development/tsdb-blocks-storage-s3/config/prometheus.yaml, development/tsdb-blocks-storage-swift-single-binary/config/grafana-agent.yaml, development/tsdb-blocks-storage-swift-single-binary/config/prometheus.yaml, docs/chunks-storage/aws-tips.md, docs/chunks-storage/chunks-storage-getting-started.md, docs/chunks-storage/running-chunks-storage-with-cassandra.md, docs/configuration/v1-guarantees.md, docs/getting-started/_index.md, docs/guides/gossip-ring-getting-started.md, docs/operations/query-auditor.md, k8s/alertmanager-dep.yaml, k8s/nginx-config.yaml, k8s/retrieval-config.yaml, k8s/ruler-dep.yaml, tools/query-audit/example-config.yaml
- Update all documentation to use the `/api/v1/push` and `/prometheus` routes where relevant
- Example Nginx configs have been updated to support both endpoints
=> chore: update documentation to use new API paths

CHANGELOG.md, integration/e2ecortex/client.go, integration/ruler_test.go, pkg/ruler/api.go
- Fixes #4012 
- Add check in e2e `TestRulerAPI` to ensure proper behavior
**TODO**
=> fix: ensure ruler returns 404 when getting missing rule group

Makefile
Fix `Makefile` so that changes to `alerts.proto` causes the `alerts.pb.go` to be rebuilt during `make protos`.
=> Fix Makefile dependency for alerts.proto.

docs/architecture.md
Signed-off-by: Nicolai von Neudeck <nicolai@vonneudeck.com>
Fixes a typo
none
**Checklist**
Does not apply - [ ] Tests updated
Does not apply - [ ] Documentation added
I did not see any typos as [BUGFIX] in the changelog and assume it does not apply - [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Fixed typo

pkg/alertmanager/multitenant_test.go, pkg/querier/querier_test.go
Just applying boy scout rule here; I was constantly committing test generated files (yes, I like `git add  --all`) and had to use git-fu-that-I-never-rememeber to revert the commit. 
I didn't create issue nor update CHANGELOG.md because 
1. I am feeling a bit lazy :-)
2. It's a minor change in test only
Let me know if this is not acceptable.
Didn't create PR.
**Checklist**
=> Fix issue where some test generate test data under src directory

pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
Ensures the Ruler evaluates and fires alerts to Alertmanager with identical behavior to Prometheus.
Fixes #4016
=> fix: ensure ruler forwards alerts with proper EndsAt

integration/alertmanager_test.go, pkg/alertmanager/multitenant_test.go
Disable alertmanager sharding unit test and integration tests while investigating them.
=> Disable alertmanager sharding tests.

pkg/ruler/ruler.go
While reviewing #4017, I've compared our `SendAlerts()` implementation with Prometheus one and I've noticed we do filter out pending alerts while Prometheus doesn't. The reason why Prometheus doesn't do it in its `sendAlerts()` is because pending alerts are now filtered out before calling it, so we can remove it from Cortex too. I've also took the opportunity to 
N/A
**Checklist**
=> No need to check alert state in sendAlerts()

pkg/storegateway/bucket_stores.go
Adds retries to `BucketStore.SyncBlocks` with `BucketStores.syncUsersBlocksWithRetries`.
Although this fixes one part of #3802, I think that the bigger issue may be the initial sync (`BucketStores.InitialSync`), which also ends up calling `BucketStore.SyncBlocks`, but after going through `BucketStore.InitialSync` in Thanos. Maybe retries should be added there in some fashion.
https://github.com/cortexproject/cortex/blob/c28d326289ee186f18c3149a452fea12ca3007e2/pkg/storegateway/bucket_stores.go#L138-L143
https://github.com/cortexproject/cortex/blob/c28d326289ee186f18c3149a452fea12ca3007e2/vendor/github.com/thanos-io/thanos/pkg/store/bucket.go#L463-L466
Fixes #3802
**Checklist**
=> Add Retries to Sync Blocks

CHANGELOG.md, pkg/util/validation/limits.go
**What this PR does**: This PR changes type of `-compactor.blocks-retention-period` to `model.Duration` to support extended duration format.
**Checklist**
=> Use model.Duration for -compactor.blocks-retention-period.

pkg/ingester/ingester_v2.go
**What this PR does**: This PR removes `error` return value from `shouldCloseTSDB` method. After #3705 this return value was always `nil`.
**Checklist**
=> Remove error return value, which was always nil.

docs/api/_index.md
Adds a note about sending the Alertmanager configuration body with `curl`. I was initially unaware that `curl` stripped carriage returns and newlines from files when using `-d @<file>` and was confused to find posting JSON data worked but YAML data didn't. Knowing that information now makes this obvious but I wouldn't be surprised if someone else may experience the same confusion.
**Checklist**
=> doc: Add note about use of curl for experimental Alertmanager API

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/chunk/chunk_store_test.go, pkg/chunk/testutils/testutils.go, pkg/cortex/modules.go, pkg/distributor/distributor_test.go, pkg/querier/querier_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Use the prometheus/common model.Duration for all duration related
limits instead of the standard library time.Duration type. This works
around an issue with the JSON representation of the standard library
type.
For example:
* The YAML representation of `time.Duration(1 * time.Second)` is the string `1s`
* The JSON representation of `time.Duration(1 * time.Second)` is the integer `1000000000`
By contrast:
* The YAML representation of `model.Duration(1 * time.Second)` is the string `1s`
* The JSON representation of `model.Duration(1 * time.Second)` is the string `1s`
The first commit in this PR demonstrates this issue with a unit test.
Note that the `Overrides` struct still converts `model.Duration` to `time.Duration`
for each respective limit method (the same way …
=> Convert all validation.Limits durations to model.Duration

CHANGELOG.md, cmd/blocksconvert/Dockerfile, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, cmd/thanosconvert/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
- Upgrades the Alpine image to the latest minor version `3.13`
Fixes #4041
[**Alpine Release Notes**](https://alpinelinux.org/posts/Alpine-3.13.0-released.html) <-- _for anyone interested_
=> chore: update Dockerfiles to use Alpine 3.13

pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
Reads the `alertmanager` state (silences, notification log) from storage if obtaining state from a running peer fails.
=> Read alertmanager state from storage if peer settling fails.

docs/guides/capacity-planning.md
Signed-off-by: Richard N Anton <ranton@amazon.com>
Update capacity planning guide for WAL replay and resharding effects on ingester.
N/A
**Checklist**
=> Update capacity planning guide for WAL replay and resharding effects on ingester

CHANGELOG.md, pkg/chunk/storage/factory.go
Signed-off-by: ChinYing-Li <chinying.li@mail.utoronto.ca>
Use enums (type string) to represent the name of clients.
If this is what @gouthamve meant by using "enums", should we also replace the case conditions with enums? e.g. 
`case "aws":` to `case AWS:`?
Fixes #1395
**Checklist**
=> Use enums to represent the clients (#1395)

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Adds a metric to the compactor that exposes the configured `CompactionInterval` as a gauge, in seconds. The intention is to be able to use this metric, the last successful compaction timestamp metric, and `time()` to more accurately calculate the # of compactions in a row that have failed. This would improve [this](https://github.com/grafana/cortex-jsonnet/blob/main/cortex-mixin/alerts/compactor.libsonnet#L66-L80) alert in cortex-jsonnet which is hardcoded to look for > 1 failures in a 2h time period.
I added a quick check to the first test I found that actually started the compactor, just to confirm the metric was being set. If you'd like a more indepth test, or to move that check to it's own test, just let me know.
**Checklist**
=> Add a metric for the compaction interval config value.

CHANGELOG.md, pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/ruler.go
Fixes an off by one error where rules in a rule group were not able to be equal to the limit.
https://github.com/cortexproject/cortex/issues/3615
**Checklist**
=> Small fix for off-by-one rules limit enforcement

docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/alertmanager/state_persister.go, pkg/alertmanager/state_persister_test.go
When ring-based/sharding replication is enabled, the alertmanager state
(silences, notification log) is periodically written to object storage
so that it can be used to recover from an all-replica outage. Only one
of the replicas is responsible for writing the state (position 0).
**Checklist**
=> Implement periodic writing of alertmanager state to storage.

CHANGELOG.md, pkg/cortex/cortex.go, pkg/cortex/cortex_test.go
**What this PR does**: This PR allows querier to call `/frontend.Frontend/NotifyClientShutdown` and `/schedulerpb.SchedulerForQuerier/NotifyQuerierShutdown` without authentication.
Fixes #4064
**Checklist**
=> Querier can now notify about its shutdown without providing any authentication in the context.

.github/workflows/test-build-deploy.yml, CHANGELOG.md, build-image/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, go.mod, go.sum
- Updates Cortex to use Go 1.16 to match Prometheus.
Fixes #4061 
**Checklist**
=> chore: update Go to use Go1.16

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/integration_memberlist_single_binary_test.go, pkg/ring/kv/memberlist/tcp_transport.go
- Adds TLS configuration options for the memberlist transport layer.
- Add an integration test to verify memberlist when TLS is configured.
Fixes #4045
**Checklist**
=> Add memberlist TLS configuration options

CHANGELOG.md, integration/e2ecortex/services.go, integration/ruler_test.go, pkg/ring/ring.go
We just experienced a query failing with "empty ring" right after the querier has started. This is caused by the fact that the querier worker may connect to the query-frontend (or query-scheduler) and get a job before the ring client has initialised its state (which is when the `WatchKey()` callback is called for the first time).
In this PR I'm proposing to fix it introducing a `starting()` function to the `Ring` client service and read the initial read state while in the starting phase. Due to how dependencies are started and given the ring is a dependency of the querier, the ring is started before the querier worker service and this guarantees that, when the querier worker will be started, the ring has already initialised.
I've also made a change to fast fail the …
=> Fixed race condition causing queries to fail right after querier startup with the "empty ring" error

pkg/ring/kv/memberlist/tcp_transport.go
**What this PR does**: Removes unused field from memberlist package. It was not possible to set it via config.
Fixes #4060
**Checklist**
=> Remove ReportWriteToErrors field.

CHANGELOG.md, docs/api/_index.md, pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go, pkg/util/allowed_tenants.go, pkg/util/allowed_tenants_test.go
**What this PR does**: This PR adds `tenant` parameter to `/flush` handler. When used, only specific tenant is flushed and only this tenants' blocks are shipped. `tenant` parameter may be used multiple times to specify many tenants at once.
This PR also adds `wait` parameter to `/flush` method, which makes the method synchronous -- it only returns when compact + ship cycle have finished. Note that `/flush` still only returns 204, no matter the result of compaction or shipment.
These two enhancements are only available when using blocks storage.
**Checklist**
=> Ingester can now flush only specified users.

pkg/alertmanager/multitenant_test.go
The test had two issues:
1. The most common issue was that replicating the silence sometimes
took a small amount of time, as it happens asynchronously. Replacing
Equal with Eventually when checking the replication metrics is enough
to make the tests reliable.
2. The second issue was more rare: When a particular shard does not have
any users assigned to it, _and_ the test randomly picks _that_ shard
to write the silence to, the test would panic (in rand.Intn). Due to
the alertmanagersMtx being held, the test actually just hung up while
trying to shutdown the alertmanagers.
=> Fix TestAlertmanager_StateReplicationWithSharding.

integration/alertmanager_test.go
In rare cases the test can fail when creating the silence with the
message:
> `creating the silence failed with status 404 and error the Alertmanager is not configured`
The checking of the metric later on also fails:
> ```unable to find metrics [cortex_alertmanager_silences] ...```
This appears to be because the alertmanager has not fully configured the
user yet. The `tenants_owned` metric is polled before beginning the
test, but this metric gets updated _before_ the call to `setConfig()`,
where the `Alertmanager` instance for the user is created.
To try and make the test more reliable, we can intead check the
`last_reload_successful` metric. This metric is per-user, so does not
exist for until `setConfig()` has completed, when it is set to `1`.
Additionally, the failure is very hard to …
=> Fix TestAlertmanagerSharding integration test.

integration/alertmanager_test.go, integration/e2ecortex/client.go, pkg/alertmanager/distributor.go, pkg/alertmanager/distributor_test.go, pkg/alertmanager/multitenant_test.go
Add and test the following routes to the alertmanager distributor (in use only when sharding is enabled):
- `POST   /alertmanager/api/v1/silences`
- `GET    /alertmanager/api/v1/silences`
- `GET    /alertmanager/api/v1/silence/{id}`
- `DELETE /alertmanager/api/v1/silence/{id}`
- `GET    /alertmanager/api/v1/status`
- `POST   /alertmanager/api/v1/receivers`
All requests are simply forwarded to a single randomly chosen replica
of the shard which contains the user.
~~Note I've had to incorporate the fix from https://github.com/cortexproject/cortex/pull/4083 in this PR.~~ Rebased.
**Checklist**
=> Add minimal support for missing routes in alertmanager distributor.

CHANGELOG.md, development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml, development/tsdb-blocks-storage-s3-gossip/docker-compose.yml, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/config/rules.yaml, development/tsdb-blocks-storage-s3/docker-compose.yml, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Earlier this week I was testing the alertmanager in the local setup and I've learned the hard way that ruler->alertmanger notification doesn't work in the local dev setup and that if you configure `-alertmanager.web.external-url` with an ending `/` the routing doesn't work as expected.
This PR fixes the local dev env and adds a validation rule on `-alertmanager.web.external-url`.
N/A
**Checklist**
=> Validate configured -alertmanager.web.external-url and fail if ends with /

docs/guides/capacity-planning.md
I was doing the math to check how much CPU and memory a distributor takes by sample/sec and my math doesn't match with our documentation, so I'm updating it (don't know where 100K samples/sec per core did come from).
@bboreham what do you see in your clusters?
N/A
**Checklist**
=> Update distributors CPU usage in capacity planning doc

CHANGELOG.md, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go
In #3975 we introduced a retry on blocks synching but this didn't apply to initial sync (we missed it). This PR fixes it, adding retries to initial sync as well, covering the regression with a test too.
N/A
**Checklist**
=> Fix retries on store-gateway initial sync failure

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Signed-off-by: Roy Chiang <roychi@amazon.com>
In a previous change, the behavior of cortex_compactor_runs_failed_total was updated. Originally this metric is incremented when it a single tenant is failed to be compacted. The new behavior will only increment this metric if the compactor failed to discover users.
This change updates the behavior back to how it was originally.
**Checklist**
=> Increment cortex_compactor_runs_failed_total if compactor fails to compact a single tenant

pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/alertmanager/alertstore/local/store.go, pkg/alertmanager/alertstore/objectclient/store.go, pkg/ruler/rulestore/bucketclient/bucket_client.go, pkg/ruler/rulestore/local/local.go, pkg/ruler/rulestore/objectclient/rule_store.go
If the alertmanager config directory contains unexpected or invalid files, mention the problematic file path alongside the underlying error.
Without the path, the problem effectively turns into a landmine, blocking even listing the contents of the bucket, with no indication of where the problem is coming from. For example this was the error on alertmanager startup when a `bucket-index.json.gz` file had gotten into the `alerts/` directory:
> level=error ts=2021-03-03T00:28:49.126516247Z caller=cortex.go:419 msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: proto: wrong wireType = 7 for field Templates"
This was originally encountered with alertmanager, but the corresponding ruler storages were updated as well for good measure. …
=> alertmanager/ruler: Include affected path upon config access failure

CHANGELOG.md, go.mod, go.sum, vendor/github.com/weaveworks/common/middleware/counting_listener.go, vendor/github.com/weaveworks/common/middleware/instrument.go, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
Update to latest github.com/weaveworks/common in order to inherit `tcp_connections` metric.
**Checklist**
=> Update to latest github.com/weaveworks/common

integration/e2e/service.go, integration/e2e/service_test.go
Integration tests are failing with the error:
```
unable to get mapping for port 9000 (output: 0.0.0.0:49159
:::49160); service: minio-9000
```
Looking at the output, I believe GitHub actions enabled IPv6 on the runners and so we're both getting IPv4 and IPv6 port mapping, which is breaking the parsing.
If my hypothesis is correct, this PR should fix it.
N/A
**Checklist**
=> Fix docker port parsing in integration tests

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/chunk/aws/s3_storage_client.go, pkg/chunk/chunk_store.go, pkg/chunk/chunk_store_test.go, pkg/cortex/modules.go, pkg/frontend/config.go, pkg/storage/tsdb/index_cache.go
We're about to cut Cortex 1.9.0, so it's time to remove config options which were deprecated in Cortex 1.6. I've also took the opportunity to mark some features we're using in prod since a long time (and that we don't expect their config to change) as stable.
I've spoken to Josh and he mentioned Alertmanager and Ruler API may still be subject to change so I haven't marked them as stable even if we're running them in prod since months.
N/A
**Checklist**
=> Remove config options deprecated in Cortex 1.6

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/util/validation/limits.go
**What this PR does**: This PR removes obsolete options to configure runtime config file and reload period. They were deprecated since Cortex 0.6.0.
**Checklist**
=> Remove deprecated options for setting runtime config file and reload period.

CHANGELOG.md, docs/blocks-storage/production-tips.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/firewall.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/util/flagext/cidr.go, pkg/util/flagext/cidr_test.go, pkg/util/net/firewall_dialer.go, pkg/util/net/firewall_dialer_test.go, tools/doc-generator/parser.go
In this PR I'm proposing a solution to introduce a sort a firewall for HTTP-based alertmanager receiver integrations to block private/local addresses and a set of configurable CIDRs. 
This PR doesn't address the email receiver (would be a follow up work).
Fixes #2036
**Checklist**
=> Add firewall support to http based alertmanager receiver integrations

pkg/alertmanager/alertmanager_ring.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
(Only applies to sharding operation)
Currently when the alertmanager joins the sharding ring, it tries to
load user configurations, and checks the ring to see what users it
should be servicing. Once finished, the alertmanager changes it's state
to ACTIVE.
However, when performing this initial sync of user configurations, the
alertmanager is in the JOINING state, but checking if a user is owned
requires an instance to be in the ACTIVE state. Therefore, the initial
sync will _never_ configure any users, but the instance will be
considered ACTIVE.
This change fixes the initial sync by considering a user to be owned by
the instance if it is in either the ACTIVE or JOINING state.
Note this fix should address the sporadic integration test failures:
The distributor …
=> Fix for alertmanagers not configuring users before becoming ACTIVE.

pkg/chunk/local/boltdb_index_client.go
Based on the prefix built from query params we can break the loop early in boltdb index client.
**Checklist**
=> stop the index search early based on query params

pkg/alertmanager/multitenant_test.go
We've seen `TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled` failing in this CI run https://github.com/cortexproject/cortex/runs/2436609218:
```
--- FAIL: TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled (9.33s)
--- FAIL: TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled/wechat_firewall:_false (1.31s)
multitenant_test.go:446: 
Error Trace:	multitenant_test.go:446
Error:      	Not equal: 
expected: true
actual  : false
Test:       	TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled/wechat_firewall:_false
```
The failing test was testing the case firewall is disabled and so, we expect the notification to be sent. The test currently has a max waiting time of …
=> Try to fix TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flakyness

docs/contributing/how-integration-tests-work.md
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
Fixes two typos in the [How integration tests work](https://cortexmetrics.io/docs/contributing/how-integration-tests-work/) documentation that was preventing the environment variable list being rendered correctly.
=> doc: Fix formatting of environment variable list

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/cortex/cortex_test.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/chunk_bytes_pool.go, pkg/storegateway/chunk_bytes_pool_test.go
Currently, the min/max bucket size for the store-gateway chunks pool is **not** configurable. Hard coded values are expected to be good enough but we never did any testing in production with different values. I would like to run such experiment, so in this PR I'm proposing to allow to configure it. I propose to keep these 2 new config options hidden in the doc for now.
N/A
**Checklist**
=> Allow to configure min/max bucket size for the store-gateway chunks pool

CHANGELOG.md, pkg/querier/tenantfederation/merge_queryable.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/util/concurrency/runner.go, pkg/util/concurrency/runner_test.go
This should significantly parallelize tenant federation queries. This also extends and aligns the error and warning wrapping and adds tests for those cases.
**Checklist**
=> Add concurrency to the mergeQueryable

CHANGELOG.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
This is the public PR for the CVE-2021-31232 fix.
N/A
**Checklist**
=> Fix for CVE-2021-31232: Alertmanager can expose local files content via specially crafted config

integration/e2e/service.go, integration/e2e/service_test.go
Cherry-pick cf1c444e09054a793e026a714cf10009627df2ac from master to fix integration tests.
=> Fix docker port parsing in integration tests (#4103)

integration/alertmanager_test.go, pkg/alertmanager/distributor.go, pkg/alertmanager/distributor_test.go, pkg/alertmanager/merger/merger.go, pkg/alertmanager/merger/v1_alerts.go, pkg/alertmanager/merger/v1_alerts_test.go
Reading alert listings via /v1/alerts will now read from a quorum of
replicas and return a merged response. The merging logic returns a union
of the alerts from all responses. When the same alert is returned by
multiple replicas, one is just chosen arbitrarily. This should be
sufficient as alerts posted to each replica should be identical.
The replicas may have some disagreement on the alert status, but this
should become consistent over time. For the /v2 API, we can use the
"updatedAt" timestamp to choose the most up-to-date status, but this
field is not available for the /v1 API.
Merging for /v2/alerts and /v2/alerts/groups to follow.
**Checklist**
=> Implement quorum reads and response merging for /v1/alerts.

CHANGELOG.md, cmd/cortex/main.go
We're rolling out ingesters in a production cluster and we've found a critical issue causing them getting stuck indefinitely while shutting down. The issue is related to the jaeger client and [described here](https://github.com/jaegertracing/jaeger-client-go/issues/577). In this PR I'm proposing an hot fix: do not call `tracer.Close()` at shutdown. Since the process is exiting anyway, it shouldn't cause any real issue.
N/A
**Checklist**
=> Hot fix to avoid process to block indefinitely on shutdown

pkg/util/http_test.go
The `TestStreamWriteYAMLResponse` is flaky when `rand.Intn(100)` returns `0`. This PR fixes it making sure we always have at least 1 entry in the map to serialize.
N/A
**Checklist**
=> Fix TestStreamWriteYAMLResponse flakyness

pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
I can't understand why `TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled` is flaky in CI (see #4138). I've run it with `-count=100` locally and succeeded.
In this PR I'm proposing to add alertmanager logs to test output, so I can see if the alert gets received by the dispatcher and if the dispatcher succeed/fail sending it.
N/A
**Checklist**
=> Add logs to investigate TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flaky in CI

pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go
So I have a feeling we didn't do `rule_group` for those metrics on purpose. The metric output doesn't have the iterations metrics anymore.
=> Make iterations metric per rule_group

go.mod, go.sum, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, vendor/github.com/prometheus/common/config/http_config.go, vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go, vendor/modules.txt
`prometheus/common` has just been released with OAuth2 support and a new config option to read secret from file which I've added to the validation we do in the Alertmanager.
_I haven't added a CHANGELOG entry because it's not actually a change for the user, given it's a new option, but I'm open to feedback on this._
N/A
**Checklist**
=> Upgrade prometheus/common and disallow new OAuth2 client_secret_file in Alertmanager

pkg/storage/tsdb/bucketindex/markers.go, pkg/storage/tsdb/bucketindex/markers_test.go
we've seen `thanos_objstore_bucket_operation_failures_total` increment without an error log,
and we suspect this is related to deletion marker migration.
this change prevents the metric from incrementing as not found values is actually expected in this
code path.
I've added a test case to ensure the particular metric stays 0 as it is expected behaviour.
=> prevent not found objects from incrementing thanos_objstore_bucket_operation_failures_total during deletion marker migration

pkg/alertmanager/multitenant_test.go
I've finally found the root cause of `TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled` flakyness. It's a (not easy to trigger) race condition in the Alertmanager which causes the `GroupWait` to get ignored on the 1st alert of a group and actually trigger once `GroupInterval` is hit.
I've opened an [issue in the Prometheus Alertmanager](https://github.com/prometheus/alertmanager/issues/2562). In the meanwhile this is a PR to fix the flakyness just setting `group_interval` to a very low value too.
Fixes #4138
**Checklist**
=> Fixed TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flakyness

pkg/alertmanager/alertstore/bucketclient/bucket_client.go
This error is expected when a new user is configured and has not
persisted any state yet, or if an alertmanager is being transitioned
from non-sharding to sharding operation.
**Checklist**
=> Supress counting not-found as an error when reading alertmanager state.

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
I was investigating some working set memory spikes in ingesters while serving heavy queries to `/api/v1/series`. In the ingester the logic is in `v2MetricsForLabelMatchers()` (when running the blocks storage) and I've noticed that we're not passing any `storage.SelectHints` to `db.Select()`.
I thought it could help but, looking at the benchmark, it doesn't. Further investigating in TSDB, I don't see a good reason why passing `Func: "series"` should help, considering chunks are lazy fetched when iterating samples (and we don't iterate samples). I think it was different in the past, maybe before `ChunkQuerier()` was introduced.
However, I believe it's better to implement series fetching the same way as Prometheus, so in this PR I'm proposing to pass hints anyway.
``` …
```
=> Specify hints to TSDB querier when querying series

integration/e2e/service.go
By adding the `io.drone.expires` label to all e2e containers, they will be cleaned up if they are left dangling following a failed test
drone-gc cleanup code: https://github.com/drone/drone-gc/blob/3ac5240928e6f6b00d1930262d2f833e36c8dfcb/gc/util.go#L55
None
**Checklist**
=> Expire long-running e2e containers in Drone CI

CHANGELOG.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go, pkg/alertmanager/state_persister.go, pkg/alertmanager/state_persister_test.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
This commit adds a number of metrics to help track the operation of the
alertmanager sharding, specifically around the handling of the state.
- `cortex_alertmanager_state_fetch_replica_state_total`
- `cortex_alertmanager_state_fetch_replica_state_failed_total`
- `cortex_alertmanager_state_initial_sync_total`
- `cortex_alertmanager_state_initial_sync_completed_total`
- `cortex_alertmanager_state_initial_sync_duration_seconds`
- `cortex_alertmanager_state_persist_total`
- `cortex_alertmanager_state_persist_failed_total`
Note this complements the already existing metrics:
- `cortex_alertmanager_partial_state_merges_total`
- `cortex_alertmanager_partial_state_merges_failed_total`
- `cortex_alertmanager_state_replication_total`
- …
=> First cut at metrics for alertmanager sharding operation.

pkg/cortex/modules.go, pkg/querier/tenantfederation/merge_queryable.go, pkg/querier/tenantfederation/merge_queryable_test.go
This change allows to use a mergeQueryable (by external projects), to aggregate results from multiple underlying Queryables.
**Checklist**
=> Make mergeQueryable more generically usable

CHANGELOG.md, pkg/chunk/purger/delete_requests_store.go
Fixes following error:
```
msg="error adding delete request to the store" err="Invalid null value in condition for column range"
```
Resolves: https://github.com/cortexproject/cortex/issues/3237
=> purger: fix nil value in column range for BatchWrite query

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, pkg/cortex/cortex_test.go
**What this PR does**: This PR changes default value of `-server.grpc.keepalive.min-time-between-pings` to `10s` and `-server.grpc.keepalive.ping-without-stream-allowed` to `true`. This is in line with ping timeouts used by gRPC client in Cortex.
See https://github.com/cortexproject/cortex/issues/3606#issuecomment-745179803 for rationale.
**Checklist**
=> Change default values for gRPC keepalive ping options.

pkg/util/modules/modules.go, pkg/util/modules/modules_test.go
Add new method for checking if a module has previously been registered
with the module Manager. This helps in cases where downstream consumers
of Cortex are conditionally adding new modules.
**Checklist**
~- [ ] Documentation added~
~- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~
=> Add IsModuleRegistered method to modules.Manager

development/tsdb-blocks-storage-s3-gossip/compose-up.sh, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-single-binary/compose-up.sh, development/tsdb-blocks-storage-s3/compose-up.sh, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/compose-up.sh
**What this PR does**: This PR removes setting of `GOARCH=amd64` in devel environments. This makes go to use the same architecture as host system, instead of emulating amd64 when running Docker in different environment. (eg. on Apple Silicon)
=> Don't force amd64 arch when building docker image for development

pkg/chunk/cassandra/storage_client.go, tools/blocksconvert/scanner/cassandra_index_reader.go, tools/blocksconvert/scanner/scanner.go
This is early work on a Cassandra scanner for blocksconvert. I'm looking for comments to help me shape this commit. Among other things, I didn't want to duplicate the code that sets up the Cassandra connections, but wasn't sure how to go about re-using it, hence the `GetReadSession()` :(
There are no tests as both functions depend on Cassandra, and I wasn't sure if I should create a Cas mock interface.
I copied the BigTable scanning logic, but it doesn't react well when Cassandra times out during scanning, and I'm unsure how to handle that case.
Please have a look and let me know what sucks about it this code.
Signed-off-by: Benjamin Charron <benjamin.charron@ubisoft.com>
Adds support for scanning Cassandra indexes in tools/blocksconvert …
=> Add Cassandra support to blocksconvert

tools/blocksconvert/scanner/scanner.go
Signed-off-by: Benjamin Charron <benjamin.charron@ubisoft.com>
**What this PR does**: Retry block uploads in blocksconvert/scanner
Fixes #4187
**Checklist**
=> scanner: Retry failed uploads

RELEASE.md
In this PR I'm proposing next Cortex releases schedule. 1.10 has been scheduled 6 weeks after from 1.9 release candidate, which was delayed by few weeks compared to the original schedule.
N/A
**Checklist**
=> Schedule next Cortex releases

CHANGELOG.md, pkg/querier/tenantfederation/merge_queryable.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/util/spanlogger/spanlogger.go, pkg/util/spanlogger/spanlogger_test.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mocklogrecord.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mockspan.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mocktracer.go, vendor/github.com/opentracing/opentracing-go/mocktracer/propagation.go, vendor/modules.txt
1. added logic to add tag `tenant_id` to tracing spans if tenant is defined in context.
2. added additional tracing spans to merge_querier's methods
Fixes #4147
**Checklist**
=> #4147 added `tenant_id` tag to tracing spans

docs/api/_index.md
This fixes the documentation to point to the new location of the remote write Protobuf location.
**Checklist**
=> Update remote write protobuf definition location

pkg/chunk/azure/blob_storage_client.go
When `GetObject` method is called on any of the object stores and the object is not there in the storage then we return `ErrStorageObjectNotFound` which is not the case for azure blob storage. This PR makes the required changes to make it consistent with other stores.
I have copied some of the code from thanos for the checks https://github.com/thanos-io/thanos/blob/main/pkg/objstore/azure/azure.go#L179
=> return ErrStorageObjectNotFound when object requested for download is not found in Azure blob storage

.github/workflows/test-build-deploy.yml
@damnever correctly pointed out in https://github.com/cortexproject/cortex/pull/4184#discussion_r636086842 that we're not running integration tests with go 1.16, like the rest of the project. This PR fixes it.
N/A
**Checklist**
=> Upgrade the go version used in integration tests

.github/workflows/test-build-deploy.yml, Makefile, build-image/Dockerfile, docs/contributing/how-to-update-the-build-image.md
Build-image can be built for linux/amd64 (as before) and also linux/arm64 platform.
Added new Makefile target to build multi-arch build image. Such image can only be pushed to repository, and not used locally by Docker. Docker only fetches platform-specific image, when it doesn't have one locally.
To use the feature, one needs to [enable `buildkit` feature](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds) in docker config. Building amd64 and arm64 should work regardless of host platform -- docker will simply run non-native platform under qemu.
=> Build image now supports linux/arm64 as well

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/util/validation/limits.go
**What this PR does**: This PR introduces new limit in Alertmanager: limit for size of configuration file that tenant can upload.
**Checklist**
=> Added limit for size of configuration file that tenant can upload to Alertmanager.

pkg/chunk/azure/blob_storage_client.go
This is a similar change as PR https://github.com/cortexproject/cortex/pull/4200 for the `DeleteObject` method where it would return `ErrStorageObjectNotFound` error when a non-existent object is being deleted. Sorry, I missed seeing that we do it for `DeleteObject` while working on the previous PR.
=> return ErrStorageObjectNotFound when a non-existent object is being deleted

pkg/ring/kv/memberlist/memberlist_client.go
Add missing return statement in memberlist code. Unlikely to happen but would be great fun to debug if it did.
**Checklist**
=> Add missing return statement in memberlist code.

pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go
In order to be able to extend or replace the default handler function for the
`/config` endpoint, the registered handler evaluates whether a handler override
is set. If so, the custom handler function is invoked, otherwise the default
handler is used.
An example for this use-case is, that a downstream project extends the Cortex
configuration with additional configuration options, which should also be
exposed in the `/config` endpoint.
**Checklist**
=> Make handler function for `/config` endpoint overrideable

CHANGELOG.md, integration/alertmanager_test.go, integration/e2ecortex/client.go, pkg/alertmanager/alertmanager_http.go, pkg/alertmanager/alertmanager_http_test.go, pkg/alertmanager/multitenant.go
**What this PR does**: status page not working if cluster disabled or sharding enabled, maybe we should hide the status page.
**Checklist**
=> Fix status page if cluster is disabled or sharding is enabled

CHANGELOG.md, pkg/alertmanager/multitenant.go
- Add changelog for alertmanager sharding now the implementation is complete
- Add experimental warning log for the feature
**Checklist**
=> Add changelog for alertmanager sharding and add experimental warning log.

Makefile, tools/packaging/test-packages
**What this PR does**: This PR adds support for building arm64 binary when running `make dist` (for linux and macos), and also deb/rpm packages for linux/arm64 when running `make packages; make test-packages`. 
**Checklist**
=> Build arm64 binaries and packages

CHANGELOG.md, integration/integration_memberlist_single_binary_test.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go, pkg/ring/kv/memberlist/mergeable.go, pkg/ring/kv/memberlist/metrics.go, pkg/ring/model.go
Add new metrics to aid troubleshooting tombstone convergence.
- `memberlist_client_kv_store_value_tombstones`
Expose the number of tombstones currently in the value for each key
in the store. If the tombstones are being propagated as expected,
then each instance should have the same value for this metric.
- `memberlist_client_kv_store_value_tombstones_removed_total`
Count the number of tombstones which have been removed because they
aged out. This can be used to troubleshoot whether tombstones are
being removed too soon (i.e. before the state is converged).
- `memberlist_client_messages_to_broadcast_dropped_total`
Count occurrences of messages being quietly dropped when they were
expecting to have been broadcast. As log messages already existed
for these events, the …
=> Add new metrics to aid troubleshooting tombstone convergence.

integration/querier_test.go, pkg/distributor/query.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/util/limiter/query_limiter.go
Signed-off-by: Tyler Reid <tyler.reid@grafana.com>
This is an internal refactor to return an Error from the query limiter and wrap to be returned as a validation error in the ingester and blocks storage queryables. 
Fixes comments from PR  #4216
**Checklist**
- [-] Tests updated
- [-] Documentation added
- [-] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Replace validation error with error in query limiter

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
- Clarifies that the global active series limits flags are post replication
=> Clarify limits flags
