cortexproject/cortex

- vendor/github.com/prometheus/prometheus/storage/local/frankenstein.go
- vendor/manifest
This one depends on prism, not frankenstein, thus obsoleting our
non-upstreamed changes in the vendor directory.
Part of #28. Made possible by tomwilkie/prometheus#78
> Use latest version of prometheus fork

- server.go
We had a production incident where we couldn't readily identify the cause of 500s because we weren't logging them. This hopefully fixes that.
> Log grpc write error

- ingester/ingester.go
The necessary method has been added upstream and vendored in in a
previous PR.
> Reenable chunk utilization monitoring

- ring/ingester_lifecycle.go
When the ingester restarts, it will always claim numTokens new tokens from the ring.
It will do this even if it happens to already own tokens.
This can result in it owning many, many more times the number of tokens than it should.
This can't happen if everything shuts down gracefully, since it will delete all its tokens first. However it can and does happen easily when it respawns after a crash. We had an issue where all our ingester instances had this occur many times, until the ring grew too large to fit within consul length limits and caused the entire ingester cluster to fail.
Note that fixing https://github.com/weaveworks/frankenstein/issues/25 will likely not fix this, since it is likely that a single hostname could die and respawn within any timeout that you set for declaring an …
> Ingester can end up owning > numTokens tokens after a restart

- cmd/prism/main.go
- distributor.go
It's possible to provide a replication configuration that's guaranteed to never work. If that happens, we should fail fast, triggering a crashloop backoff and thus a deployment fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/56)
> Check replication config at startup

- ingester/ingester.go
Only close the head chunk if its own first sample is too old, not if the
first sample of the entire series before it is too old.
> Fix chunk max age handling

- ingester/ingester.go
There's an OBOB in there. According to my understanding, it would
currently keep one already persisted chunk in memory and then persist it
again every minute, until there's another full chunk (then the old one
would finally get dropped).
Indeed, looking at how many series the ingester has in memory:
prism_ingester_memory_series
...and comparing that to how many chunks are being written out per
minute:
rate(prism_ingester_chunk_utilization_count[1h]) * 60
The number of chunks being persisted every minute is coming quite close
to the number of series in memory. We should watch for a sharp drop of
the latter rate after merging this.
> Fix removal of persisted chunks from memory

- distributor.go
- ring/ring.go
Fixes #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/65)
> Rename failure metrics

- distributor.go
- ring/ring.go
I guess this fixes #60. Gives us a measure of non-dead ingesters. 
Also, I noticed that the reason we'd be getting `nil` errors on query failures is that we haven't got enough ingesters, so I added an early failure path with a better error message.
I thought about adding a crappy status page at `/ringz` or something, but I would have had to pierce through a layer or two of abstraction and decided that it wasn't worth the effort. Happy to revisit if people think otherwise.
Assumes #65 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/prism/68)
> More visibility on ingesters

- cmd/cortex/main.go
- querier/iterator.go
- querier/querier.go
- server.go
Started working on recording rules, wanted to:
- put it in a separate package to `cortex`
- use querier
Thus, split it to `querier` package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/cortex/76)
> Move querier to separate package

- chunk/chunk.go
- distributor.go
- ingester/ingester_test.go
- querier/querier.go
- util/util.go
As promised in https://github.com/weaveworks/cortex/pull/78...
This also gets rid of any `sort.Sort` usage for merging&sorting incoming samples, which *should* be ok if we can assume that the samples in any chunks we read (as well as data from the ingesters) are already sorted. Then we just merge their samples together linearly, which includes deduplication.
Since `MergeSamples` is now being used by different packages and there was no natural other home for it, I started a `util` package.
> Refactor chunks-to-matrix code and its deps

- cmd/cortex/main.go
- distributor.go
- ring/ring.go
Also, break `cortext_ring_ingesters` down by state - `healthy` or `unhealthy`.  This involved moving the ingester heartbeat timeout into the ring struct.
> Move all ring-related metrics into ring.go; prefix them with cortex_ring

- cmd/cortex/main.go
- ingester_client.go
- server.go
Part of #72 
I don't really like the approach and can't see a not terrible way to do this for the distributor, so I thought I'd put it up for feedback.
> Report bad samples as 400s (ingester)

- cmd/cortex/main.go
- cortex-build/Dockerfile
- distributor.go
- ring/ingester_lifecycle.go
- ring/model.go
- ring/ring.go
Fixes #87
- Mark tokens as Active or Leaving
- Do not include Leaving tokens in a write operations replica set
- For any operation, if you hit a Leaving token, increase size of replication group by 1.
> Add per-token state, and use it to not write to Leaving ingesters

- circle.yml
To speed up builds, so I can haz faster iterations
> Add boilerplate for caching the build image on circle

- ring/model.go
- ring/ring.go
Now the graph will have Active, Leaving and unhealthy in it.
> Expose different ring states in the metrics

- ingester/ingester.go
- vendor/github.com/prometheus/prometheus/storage/local/chunk/chunk.go
- vendor/github.com/prometheus/prometheus/storage/local/chunk/delta.go
- vendor/github.com/prometheus/prometheus/storage/local/chunk/doubledelta.go
- vendor/github.com/prometheus/prometheus/storage/local/chunk/varbit.go
- vendor/manifest
Add `cortex_ingester_chunk_length` (the number of samples per chunk) and `cortex_ingester_chunk_age_seconds` (the age in seconds of the chunk, where ages is now - first sample).
Should help with #11 and #84.  Will need post-merge review #97.
> Add more chunk metrics

- cmd/cortex/main.go
- distributor/distributor.go
- distributor/ingester_client.go
- server.go
Fixes #16
Will need post-merge review #97
> Move distributor to its own package

- ingester/ingester.go
- ingester/priority_queue.go
Should address issues found in #11 (high variance in chunk age at flush), and pave the way for a higher max chunk age.
> WIP Flush series in priority order; where priority is oldest first.

- ingester/ingester.go
- ingester/priority_queue.go
- ingester/priority_queue_test.go
> Add metric for flush queue length

- ingester/ingester.go
- ingester/series.go
Part of #11 
Idea is to get rid of the saw-tooth in total number of chunks in the system caused by all chunks getting closed every 10mins:
> Don't close chunks on GC thread, close chunk on flush

- ingester/ingester.go
Seeing # chunks back up and thing not getting scheduled for flush:
> Use age of oldest chunk when deciding to flush

- chunk/dynamo_client.go
- cmd/cortex/main.go
Part of https://github.com/weaveworks/monitoring/issues/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/cortex/89)
> Metrics for Dynamo capacity

- cmd/cortex/main.go
- ingester/ingester.go
Also, schedule series for flushing if it has >1 chunk.
> Make max chunk size 1hr

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- ingester/ingester.go
We're battling with overloading dynamoDB, so anything that makes it easier to understand...
> Remove chunk store parallelisation; I want this controlled by the ingester

- server.go
Post-merge review for #92.
Couldn't think of a place to say "All ingesters are considered not ready if one ingester is considered not ready. This is so Kubernetes will only roll out one ingester at a time, and more importantly, only shut ingesters down one at a time, as our ring consistency depends on graceful shutdown."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/cortex/109)
> Spelling fix

- ring/ingester_lifecycle.go
We track ingester state now, not token state.
Follow-up to #96, merged without review.
> Update comments to match code

- ingester/ingester.go
Document assumptions of function by expressing them in the type signature.
> Remove "shouldn't happen" condition

- ingester/ingester.go
Fixes #121 
Buckets are capped/maxing out, as seen by the avg exceeding the 99th (but otherwise tracking the 50th):
Turns out `LinearBuckets` is exclusive, so `LinearBuckets(0.1, 0.1, 9) = [0.1 ... 0.9]`.
> Tweak chunk stats buckets

- chunk/dynamo_client.go
- cmd/cortex/main.go
- Don't gather account limits (needs more permissions)
- Don't collection anything by default: make it flag controlled (so we don't have to give permissions to ingester and distributor)
> Fix up DynamoDB Watcher

- cmd/cortex/main.go
> Fix up gorilla mux handling and test locally.

- chunk/chunk_store.go
Part of https://github.com/weaveworks/monitoring/issues/40
> Tidy up and add more query metrics

- cmd/cortex/main.go
- querier/querier.go
- ruler/ruler.go
- user/id.go
aka "jml and the terrible, horrible, no good, very bad single-tenancy recording rules server".
Part of #4 
Simplest thing I could come up with that got recording rules working. There are many, many things wrong with it, but hopefully enough there to start generating extra query traffic and dogfooding grafana.
Big problems are:
* not multi-tenant
* doesn't have any mechanism for updating rules once it gets them
After deploying this to dev, next coding steps are:
* fork and/or patch Prometheus `rules` module to let us:
* evaluate a rule ourselves (rather than delegating to manager)
* use an appender with a context (if query has one, why not appender?)
* parse a rules file into its constituent rules
* change ruler to have a queueing model: one thing that pops rules/configs/whatever from a …
> Single-tenant recording rules server

- chunk/chunk.go
- chunk/chunk_store.go
- chunk/chunk_store_test.go
> Don't fetch chunks outside our timerange

- cmd/cortex/main.go
- ring/http.go
- ring/ingester_lifecycle.go
- ring/model.go
- ring/ring.go
> Add /ring to ingester & distributor, ability to remove token

- .gitignore
- Makefile
- cmd/cortex/main.go
- distributor/distributor.go
- ring/consul_client.go
- ring/http.go
- ring/ingester_lifecycle.go
- ring/model.go
- ring/ring.go
- ring/ring.proto
Fixes #156 
<s>(Includes #162 and #161 for now, until they are merged)</s>
- The ring can read and write json and proto
- Internal representation is all proto, and there is a translation between the two (`ring.go:MarshalJSON`)
- Ingesters will always try to read json first, fallback to proto if that fails
- Once ingester fails to read json, it will always write proto
- Ingester will also start writing proto once it has detected all ingesters can read it
Have testing upgrades from master to this locally
> Switch to snappy/proto for encoding ring in consul

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- cmd/cortex/main.go
There can be slight overlap around the switchover time, but I deemed it
safer (and not incorrect) than risking gaps due to some calculation
error.
> Allow switching to daily instead of hourly index buckets

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- cmd/cortex/main.go
Second attempt at #178, part of #10
> Daily buckets

- cmd/cortex/main.go
- ingester/ingester.go
Fixes #127 
This is needed by #181, as the table manager needs a hard limit on chunk age so it knows when its safe to remove write capacity from a table.
Includes some refactoring to ensure the tests used to decide when to flush is consistent over the sweep and flush phases.
> Flush chunks older than 12hrs

- cmd/cortex/main.go
- distributor/http_server.go
**Update:** Now the response looks like this:
In case of a good expression:
HTTP status code: 200 OK.
```json
{
"status": "success"
}
```
In case of an error:
HTTP status code: 400 Bad Request.
```json
{
"error": "parse error at line 1, char 4: could not parse remaining input \",expr\"...",
"errorType": "bad_data",
"location": {
"line": 1,
"pos": 4
},
"status": "error"
}
```
Fixes https://github.com/weaveworks/cortex/issues/176
> Add distributor endpoint for validating PromQL expressions

- chunk/dynamo_table_manager.go
Found when deploying to dev.
Part of #158
> Prevent infinite loop in the table manager

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- chunk/dynamodb_client.go
- cmd/cortex/main.go
> Split out the dynamodb client from chunk_store.go

- chunk/chunk.go
- chunk/chunk_store_test.go
- ingester/ingester.go
- ingester/series.go
- ingester/series_map.go
Fixes #201 
Also:
- stop using upstream chunk.Desc, use our own (slightly simplier) one
- move logic for detecting duplicate or historic appends into series.go, so it encapsulates with the required state
- more `samplesForRange` into series.go, where is seems to more naturally belong
- use series's first time as the sort key for the flush queue, not last time - should flush old chunks first!
- when flushing, consider the head (ie newest) chunk when deciding if to close the head...
- move seriesMap into its own file (series_map.go)
> Ensure desc.LastTime is always up to date

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- chunk/dynamodb_client.go
- cmd/cortex/main.go
- ingester/ingester.go
> Remove dynamo client goroutine pool

- ingester/ingester.go
With varbit, we'll get ~800 samples per chunk, or 3:20hrs sized-chunks (at 15s scrape periods).
> Tweak histogram buckets as chunks are bigger than previously

- chunk/chunk_cache.go
Also works around the issue where returning `nil, nil, err` was the wrong thing to do here, should have been `nil, chunks, err`.
Fixes #215
> Don't completely fail the cache lookup if we fail to decode one chunk.

- ring/ingester_lifecycle.go
On a previous upgrade, new ingesters came up, added itself (with grpc hostname), but existing ingesters (who didn't know about this field) rewrote the ring on heartbeat, erasing the grpchostname.
This PR adds the grpc hostname to the ingester desc on heartbeat, to pave the way for removing the old http interface.
> Populate grpc hostname on heartbeat.

- ingester/ingester.go
- ingester/user_state.go
Fixes #183 
Previously, there was a race condition where `append` would get the user state, the user state could be GC'd, then `append` would create a new series in this user state that would get lost.
This change makes the creation and addition of new series to user states happen under the user state lock, as does GC.  To make this all clearer, the user state tracking has been broken out into a separate file.
> Add the new series to the seriesMap whilst holding the user state mutex.

- ring/consul_client.go
- ring/ingester_lifecycle.go
- ring/ring.go
Fixes #224.
Includes #218, will have to wait until thats merged.
> Remove code to migrate from json to proto ring.

- ruler/ruler.go
Should hopefully fix this:
```
$ kubectl logs --namespace=cortex ruler-3206392647-mx1tj 
time="2017-01-24T15:21:19Z" level=info msg="Ruler up and running" source="ruler.go:140" 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x730b04]
goroutine 168 [running]:
panic(0xab2f20, 0xc420016050)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0xc42037cd10, 0xb7ac25, 0x9, 0xc4203d9720, 0x159d1112813, 0x10f4de0, 0xc4203db290)
/go/src/github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:263 +0x194
created by github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group) …
```
> Initialise ruler's cfg.ExternalURL to a valid, empty URL.

- ingester/ingester.go
- ring/ingester_lifecycle.go
- ring/ring.go
- Forgot to actually instantiate the ring in the ingester struct
- Was a copy of the struct, not a pointer
- Proto ring can be nil at startup (is a pointer to a proto), so make all the functions deal with this gracefully.
Tested locally, have successfully transitioned a ingester to ready state.
> Fix ingester readiness handler, that was completely broken.

- cmd/distributor/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- distributor/distributor.go
This only closes connections to ingesters which are unhealthy or gone, not for leaving ones, so this *should* be ok.
Fixes https://github.com/weaveworks/cortex/issues/217
> Clean up stale ingester connections

- ingester/ingester.go
Fixes #86 
This is a particularly naive solution, but I think simpler is better.  I considered only trying a fixed number of times; problem is we might still fail to flush some chunks but exit cleanly and never know, which I'd like to avoid.
The problem with this approach is if, because of some bug / logical error, the first chunk fails to flush and always fails to flush, we'll never try to flush any of the other chunks even if they might succeed.  I'm tempted to put all the failing flushes on a second list and try them at the end, in a loop, to work around this.  WDYT?
In the long run the real solution here is the WAL.
> Try and flush failed chunks repeatedly when we're shutting down.

- distributor/distributor.go
And allow calls to forAllIngesters to succeed even if `d.cfg.ReplicationFactor - d.cfg.MinReadSuccesses` (ie 1) calls to an ingester failed.
> Honor distributor.remote-timeout in the ingester gRPC client

- distributor/http_server.go
The use of this type was removed when the HTTP ingester client was
removed. Not sure if the 4xx passthrough as the result of the
distributor's HTTP response made sense in the first place, since I'd see
it as an internal server error from the user's point of view if we
encode something wrong to the ingester internally.
> Remove obsolete IngesterError type

- distributor/distributor.go
- distributor/http_server.go
- vendor/golang.org/x/time/rate/LICENSE
- vendor/golang.org/x/time/rate/rate.go
- vendor/manifest
This is the simplest version for now, just based on flag-configured
rate limits per distributor process and no knowledge about total
(cross-distributor rates) yet.
Fixes https://github.com/weaveworks/cortex/issues/128
> Implement per-user rate limits

- chunk/dynamodb_client.go
Also, include table name in the dynamodb error metric.
Part of #254
> Limit number of retires when we get ProvisionedThroughputExceededException

- chunk/dynamo_table_manager.go
- chunk/dynamo_table_manager_test.go
Previously, table manage would use same read throughput for all tables.  Want to differentiate as part of #254, so the head table can have same throughput for reads and writes.
> Have table manager accept flags for read/write throughput on inactive tables.

- ruler/ruler.go
Fixes #253. Tested locally.
Introduces a new warning in the logs:
```
time="2017-02-01T11:54:00Z" level=warning msg="Alert batch larger than queue capacity, dropping 21 alerts" source="notifier.go:230"
```
But that's OK, because we _are_ dropping alerts and that is worthy of warning.
Time to fix: 5m
Time to test locally: 95m
> Provide a do-nothing notifier for alerts

- ingester/ingester.go
This, combined with setting max surge to 0 in k8s, fixes #114
> Have ingesters only ever transition for not ready to ready, and never back

- chunk/chunk_store.go
- util/hash_bucket_histogram.go
> Track distribution of row write rates with new HashBucketHistogram.

- cmd/distributor/main.go
- cmd/ingester/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- distributor/distributor.go
- ingester/ingester.go
Since a metric cannot be registered twice, it's otherwise not possible
to instantiate one of these types multiple times (e.g. for tests).
> Move metrics registration out of Collector types

- chunk/chunk_store.go
- chunk/chunk_store_test.go
- chunk/chunk_test.go
- chunk/dynamo_table_manager.go
- chunk/dynamo_table_manager_test.go
- chunk/schema.go
- chunk/schema_test.go
- cmd/ingester/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- util/flags.go
Part of #254 
- Define a Schema interface for calculating the hash and range keys to use.
- Make implementations of this interface for all the different schema's we've had.
- Make a "CompositeSchema" which delegates to various schema's depending on when they we activated.
- Update chunk store to use this; in particular, invert the order of the merge and intersect in the query path.
- Bunch of testing
TODO:
- deployed to dev on Jan 17th https://github.com/weaveworks/service-conf/commit/d5535139413137b71740d1e925b09052690eaf18
- deployed to prod on Jan 18th https://github.com/weaveworks/service-conf/pull/510
> Make the schemas declarative, add a new schema for better load balancing.

- chunk/chunk_store.go
- util/hash_bucket_histogram.go
See #261 for original PR.
- Dump the bucket values into the histogram once per second
- Normalise the bucket values such that 1 is balanced
> Review feeback for the HashBucketHistogram

- chunk/chunk_store.go
- ingester/ingester.go
- util/matchers.go
...to match the underlying sharding of the index.  Part of #254.
The idea being, if we do hotspot a partition in the index, then lets not hotspot it with all 50 flush threads.  At least this will give the other series a chance to flush, and hopefully get us closer to saturating the provisioned capacity.
> Shard ingest flush queue by username and metric name 

- chunk/chunk_store.go
- distributor/distributor.go
- distributor/distributor_test.go
- util/matchers.go
When enough samples succeed (or fail), return the rpc - don't wait for all of them.
This should massively reduce the 99th percentile latency (currently up in the 200ms), and bring it a lot closer to the average (of 40ms).
> Short cut distributor sample pushes.

- distributor/http_server.go
- ingester/ingester.go
- ingester/ingester_test.go
- ingester/user_state.go
- util/error.go
- util/validate.go
When a series limit is reached, samples for existing series should still
be stored, so this is treated as a partial failure.
I tried various approaches to error propagation and handling, including
more complicated ones, but went for this medium-simple approach in the
end that uses gRPC errors to communicate a series-exceeded error from
the ingester back to the distributor, still manages to only partially
fail for the affected series, and communicates the specific error back
to the user. Due to only returning the last error encountered when
writing to multiple ingesters, this may at times cover up the
series-exceeded error if there is another error afterwards.
> Implement per-user series limits

- distributor/distributor.go
- distributor/distributor_test.go
> Parallelise and short cut distributor queries.

- README.md
- k8s/consul-dep.yaml
- k8s/consul-svc.yaml
- k8s/distributor-dep.yaml
- k8s/distributor-svc.yaml
- k8s/dynamodb-dep.yaml
- k8s/dynamodb-svc.yaml
- k8s/ingester-dep.yaml
- k8s/ingester-svc.yaml
- k8s/memcached-dep.yaml
- k8s/memcached-svc.yaml
- k8s/nginx-config.yaml
- k8s/nginx-dep.yaml
- k8s/nginx-svc.yaml
- k8s/querier-dep.yaml
- k8s/querier-svc.yaml
- k8s/retrieval-config.yaml
- k8s/retrieval-dep.yaml
- k8s/retrieval-svc.yaml
- k8s/ruler-dep.yaml
- k8s/ruler-svc.yaml
- k8s/s3-dep.yaml
- k8s/s3-svc.yaml
- k8s/table-manager-dep.yaml
> Dev cortex env behind a nginx

- ingester/ingester.go
See #316 
Had a stab at fixing this. Ended up coming up with two different solutions (commit 1 & commit 2 of this PR). One was to have a new slice-as-queue for storing failures, the other is to put the items back into the priority queue with an exponential "backoff". Not sure which I dislike least.
> Retry failed terminal flushes at end of queue

- ruler/ruler.go
@jml Let me know if I am wrong here, but rule seems to be not processed if err != nil here.
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
> Removed recording metric in error case for ruler group.

- chunk/chunk_store_test.go
- chunk/schema.go
- chunk/schema_test.go
- chunk/storage_client_mock_test.go
Should potentially help with #304 (missing data reported by @rade and @juliusv, but not @Bplotka as he is on v4 schema).
Unfortunately, the way I calculated the relative timestamp of chunks within buckets was wrong, causing overflow of a uint32.  The data written by the v5 schema is incorrect.  This PR adds tests to expose it, and fixes.
The situation is salvageable though - I have made the v5 schema ignore the timestamps for reads.   This will have a performance regression, but I will make a new v6 schema that takes them into account (to help with #199).
> Address some correctness issues with the v5 schema

- alertmanager/multitenant.go
- configs/api/api.go
- configs/api/api_test.go
- configs/client/configs.go
- ruler/ruler.go
- ruler/scheduler.go
No behavioural changes to the API (as much as I'd like to). Instead, fairly mechanically create new endpoints—public and private—and update the internal clients of the private endpoints to use the new one.
Thus:
* `/api/configs/org/cortex` becomes `/api/prom/rules` and `/api/prom/alerts` (although the old endpoint is still around to help with backwards compatibility)
* `/private/api/configs/org/cortex` becomes `/private/api/prom/rules` and `/private/api/prom/alerts`
I want to change the private APIs to be gRPC, but I also want to change the semantics of the rules config API, which I think is best reserved for a separate change.
@davkal You should probably be aware that this PR deprecates the old `/api/configs/org/cortex` route.
> Separate routes for alert configs and rules

- Makefile
- chunk/chunk_store.go
- chunk/chunk_store_test.go
- chunk/dynamodb_client.go
- chunk/dynamodb_client_test.go
- chunk/schema.go
- chunk/schema_test.go
- chunk/storage_client.go
- chunk/storage_client_mock_test.go
- util/error.go
- util/validate.go
Fixes #316 (ValidationError because range value was too long) and reenabled the v5 query optimisation with the fixed timestamps.
> v6 Schema; move label value out of range key, and re-enable chunk timestamp optimisation.

- chunk/chunk_store_test.go
- chunk/schema.go
So we don't fetch too much from DynamoDB.
Didn't affect data we wrote or query correctness - only made DynamoDB queries slower.
> V6 Schema: actually set RangeValueStart to the start of the time range

- configs/api/api.go
These have been deprecated in favour of routes specific to rules &
alertmanager.
> Remove old routes

- util/matchers.go
- util/matchers_test.go
The passed-in matchers slice got mutated by the copies, leading to the
metric name being removed from the original matchers *iff* the metric
name was not the last element in the slice already. By pure luck, PromQL
only creates LabelMatcher lists where the metric name is the last
element. But in my remote query testing, I ended up constructing
matchers with the metric name somewhere in the middle. The result was
that the metric name was removed from the matchers and all kinds of
metrics (not just the ones for the right metric name) were being
returned for a query.
> Fix mutation bug in ExtractMetricNameFromMatchers()

- ruler/ruler.go
- ruler/ruler_test.go
https://github.com/weaveworks/cortex/pull/312 broke user ID handling for
the ruler alert notifications.
> Fix ruler userID injection regression

- cmd/querier/main.go
- cortex.proto
- distributor/http_server.go
- querier/querier.go
- util/http.go
This allows querying Cortex via Prometheus's new generic remote read
protocol.
See https://github.com/prometheus/prometheus/pull/2499
Fixes https://github.com/weaveworks/cortex/issues/226
> Add Prometheus remote read support

- chunk/aws_storage_client.go
Can be useful when debugging issues such as "no such table".
> Say which table errored during query

- chunk/aws_storage_client.go
- chunk/inmemory_storage_client.go
- chunk/table_manager.go
- chunk/table_manager_test.go
Move instrumentation to the dynamo table manager client.
This came up in #357.
> Add context to table manager interface

- chunk/chunk_store.go
- distributor/distributor.go
- lock.json
- manifest.json
- querier/querier.go
- vendor/github.com/prometheus/prometheus/promql/engine.go
- vendor/github.com/prometheus/prometheus/retrieval/scrape.go
- vendor/github.com/prometheus/prometheus/retrieval/scrape_test.go
- vendor/github.com/prometheus/prometheus/storage/local/codable/codable.go
- vendor/github.com/prometheus/prometheus/storage/local/heads.go
- vendor/github.com/prometheus/prometheus/storage/local/persistence.go
- vendor/github.com/prometheus/prometheus/storage/local/storage.go
- vendor/github.com/prometheus/prometheus/storage/storage.go
- vendor/github.com/prometheus/prometheus/web/api/v1/api.go
- vendor/github.com/prometheus/prometheus/web/api/v1/api_test.go
Fixes #382 
Uses fork of Prometheus container weaveworks/prometheus/2571-propagate-api-error until https://github.com/prometheus/prometheus/issues/2571 is fixed.
> Propagate promql.ErrStorage on the query path, so the user gets 500s where appropriate.

- ingester/ingester_test.go
- ingester/series.go
This fixes the tracking of the last sample time and value, which is
needed to detect duplicate or out-of-order samples upon ingestion.
To be totally correct, we would also need to set seriesLastSampleValue
in the transfer receiver code, but there's no good way to get at it, and
apparently we have had the same problem after unarchiving series or
after restoring from a checkpoint at startup:
https://github.com/prometheus/prometheus/issues/2602
But that is only a minor problem, as it only means that we will
misreport duplicate samples (same timestamp *and* same value) as
duplicate timestamp, but different value (error instead of silent noop).
Before trying to fix that here, I'd want to see what the reaction to the
upstream issue is, and whether that results in us adding an efficient
way to …
> Fix tracking of last sample time and value

- ingester/ingester.go
- ingester/ingester_test.go
- ingester/series.go
We're still getting errors about duplicate and out-of-order samples in dev, so we need to log more to find out what series are the culprits.
> Log details about out-of-order and duplicate samples

- alertmanager/multitenant.go
- configs/api/api.go
- configs/api/api_test.go
- configs/api/helpers_test.go
- configs/client/configs.go
- configs/client/configs_test.go
- configs/configs.go
- configs/db/db.go
- configs/db/memory/memory.go
- configs/db/postgres/postgres.go
- configs/db/timed.go
- configs/db/traced.go
- ruler/scheduler.go
Now that the configuration DB, API, and client lives in Cortex, we
should consolidate the various config types to only use the more typed
versions.
> Consolidate /configs and /configs/api Config types

- chunk/aws_storage_client.go
- chunk/aws_storage_client_test.go
- chunk/inmemory_storage_client.go
- chunk/schema.go
Fixes #398 
- Created some extra tests for the aws storage client and started filtering by range key.
- Added simple field to `IndexEntry` which is then used to add the filter condition to dynamo if it exists
> Filter equality matchers on the dynamo side

- chunk/aws_storage_client.go
- chunk/aws_storage_client_test.go
- chunk/by_key.go
- chunk/by_key_test.go
- chunk/chunk_store.go
- chunk/chunk_store_test.go
- chunk/inmemory_storage_client.go
- chunk/schema.go
- chunk/schema_config.go
- chunk/schema_config_test.go
- chunk/schema_test.go
- chunk/schema_util.go
- chunk/schema_util_test.go
- chunk/storage_client.go
- distributor/distributor.go
- distributor/distributor_test.go
- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- k8s/table-manager-dep.yaml
- util/matchers.go
- util/matchers_test.go
Add support for queries with no metric names. e.g. `{foo="bar"}` or `count({job="foo"}) by (__name__)`
Fixes #313 
- Add support to distributor and chunk store
- Create `v7Schema` to support writing metric name entries
- Refactor `IndexEntry` into `IndexEntry` and `IndexQuery` to make separation clearer
- Create a new range value type for metric names and split the code paths so we now support different types of range values
- Change `ExtractMetricNameFromMatchers` to `ExtractMetricNameMatcherFromMatchers` to support optimistations such as matching NotEqual metric name matchers. e.g. `{foo!="bar"}`
- Update bucket functions to return `Bucket`s instead of using callbacks
- Fix bug in hourly bucket where it was offsetting time by day not hour - created a test for this
> Support queries with no metric name

- alertmanager/mesh.go
- alertmanager/multitenant.go
- alertmanager/peers.go
- configs/client/configs.go
- ruler/ruler.go
- ruler/ruler_test.go
- Set alertmanager peers based on k8s SRV lookup
- `meshWait` doesn't need updating because it's already dynamically operating on the sorted list of mesh peers, which is what we're using for service discovery
- Update ruler to use DNS service discovery to send alerts to all alertmanagers
Tested with a script that's available in https://github.com/weaveworks/test-alertmanager 
See #50 
TODO:
> Multiple alertmanagers in a mesh

- pkg/ingester/client/cortex.proto
> Don't rename proto package name, as its part of the contract.

- cmd/table-manager/main.go
- pkg/chunk/aws_storage_client.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
- pkg/chunk/schema_test.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- pkg/ingester/client/dep.go
(Motivation: tidying a few things up before handling #141)
- Move /dep.go into /pkg/ingester/client, where is belongs.
- Rename DynamoTableManager to TableManager, as there is nothing DynamoDB-specific about it - it would be useful to BigTable too.
- Rename DynamoTableClient interface to TableClient, as there is nothing DynamoDB-specici about it - it would be useful to BigTable too.
- Move dynamoTableClient (implementation of TableClient) into /pkg/chunk/table_manager.go, where it belongs.
- Delete chunk.DynamoTableClientConfig, as the table-manager-specific in-memory construction wasn't used.
- Move warning about unused DynamoDB table name in path to dynamoClientFromURL.
- Move duplicated OriginalTableName into PeriodicTableConfig, as per comment.
- Fix usage of flag.StringVar - should …
> Various chunk store / DynamoDB config refactorings.

- README.md
Attempting direct access to Cortex from browser results in failed requests due to CORS. Changing the default to proxy through the Grafana backend is more reliable.
Before:
After:
> Avoid CORS errors

- cmd/ingester/main.go
- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- k8s/table-manager-dep.yaml
- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_test.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/schema.go
- pkg/chunk/storage_client.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- pkg/ingester/BUILD
- pkg/ingester/client/BUILD
- pkg/ingester/ingester_flush.go
Part #141 
- After a certain time, store chunks in DynamoDB.
- Use the table manager to regularly rotate this table, and provision its capacity.
- Fetch chunks for DynamoDB in batches of 100.
> Store chunks in DynamoDB

- build-image/Dockerfile
As mentioned on https://github.com/weaveworks/build-tools/pull/99#issuecomment-302365357 and raised on https://github.com/mvdan/sh/issues/107 `gopkg.in` currently does not behave as it should for `shfmt`, which leads to build failures like:
```
Step 4/6 : RUN go get -tags netgo     github.com/fzipp/gocyclo    github.com/golang/lint/golint     github.com/kisielk/errcheck     github.com/mjibson/esc    github.com/client9/misspell/cmd/misspell    github.com/jteeuwen/go-bindata/go-bindata     github.com/golang/protobuf/protoc-gen-go    github.com/gogo/protobuf/protoc-gen-gogoslick     github.com/gogo/protobuf/gogoproto    gopkg.in/mvdan/sh.v1/cmd/shfmt &&   rm -rf /go/pkg /go/src
---> Running in 05f8079c66fb
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:26: undefined: …
```
> Use shfmt v1.3.0 instead of gopkg.in's v1

- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
- pkg/chunk/dynamodb_table_client.go
Should prevent it from backing off so often.
> Rate limit DynamoDB API requests in the table manager.

- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
Also, alter the unit test to pick this up.
Previously you'd get this traceback:
```
$ ./table-manager -dynamodb.table.tag=foo=bar
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/weaveworks/cortex/pkg/chunk.(*Tags).Set(0xc42007bfa0, 0x7fff5fbffc04, 0x7, 0x0, 0x0)
/Users/twilkie/Documents/src/github.com/weaveworks/cortex/pkg/chunk/table_manager.go:92 +0x9c
flag.(*FlagSet).parseOne(0xc42006e060, 0xc42007bfa0, 0x1773370, 0x12)
/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:894 +0x3c2
flag.(*FlagSet).Parse(0xc42006e060, 0xc420080070, 0x1, 0x1, 0x3, 0xc420287cb0)
/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:913 +0x60
flag.Parse()
/usr/local/Cellar/go/1.8/libexec/src/flag/flag.go:941 +0x72
main.main()
/Users/twilkie/Documents/src/github.com/weaveworks/cortex/cmd/ta …
```
> Test that the map itself is nil, not the pointer to it!

- pkg/chunk/dynamodb_table_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/table_client.go
- pkg/chunk/table_manager.go
Turns out `UpdateTable` is not idempotent, and errors when trying to 'update' the provisioned throughput to something thats the same:
```
time="2017-05-24T13:07:58Z" level=error msg="Error syncing tables: ValidationException: The provisioned throughput for the table will not change. The requested value equals the current value. Current ReadCapacityUnits provisioned for the table: 300. Requested ReadCapacityUnits: 300. Current WriteCapacityUnits provisioned for the table: 300. Requested WriteCapacityUnits: 300. Refer to the Amazon DynamoDB Developer Guide for current limits and how to request higher limits.
```
> Only change provisioned capacity and tags if they have changed.

- pkg/chunk/aws_storage_client_test.go
- pkg/chunk/dynamodb_table_client.go
DynamoDB raises an exception if you try to set empty tags. We have empty tags if they are not set via config (e.g. local).
> Only set DynamoDB table tags if they exist

- Makefile
Needs trailing `;` for shells where time is a reserved word (builtin command).
Full error:
make: time: Command not found
See also weaveworks/billing#84
> Fix builtin `time` command not found

- pkg/util/http.go
> We should actually try and decompress the requests if reading the body succeeds.

- pkg/ingester/ingester_claim.go
- pkg/ingester/ingester_lifecycle.go
> Make ingesters go back to PENDING state if a transfer fails.

- pkg/chunk/schema_config.go
> Restore -dynamodb.*-table.start as a deprecated flag

- pkg/ruler/ruler.go
Identified by @bboreham, all credits go to him :+1:.
This is a quick change to (hopefully) help identify an issue with alerts periodically going back to pending, and not firing; and reduce the likelihood of the race condition interfering with this investigation.
Alternatives considered: 
- add half-an-interval to, but this would still lead to a race 50% of the time,
- add one second, but this would still lead to a race every 15 seconds (the current default interval),
- randomise, but could actually make it harder to identify issues,
- add 10 ms (current state): this should be long enough to avoid a race condition, and short enough to maximise the time before the two schedules overlap again (if the race is happening 100% of the time every 15 seconds, then, with 10 ms offset, it would only …
> Reduce likelihood of a race between rules evaluation and alerts scheduling

- pkg/chunk/schema_config.go
Deprecated flag means we can roll out new version of Cortex (that includes #463) without configuration change.
Not particularly proud of this. Haven't tested locally.
> Allow tags to be set on tables globally

- build-image/Dockerfile
It has a few fixes, and other things I'm building use 1.8.3 so I don't want to download 1.8.1 as well.
> Bump golang version to 1.8.3

- pkg/ruler/scheduler.go
I'm half convinced that this won't show anything interesting, since it's a less indirect version of 
`rate(cortex_request_duration_seconds_count{job="cortex/configs", method="POST"}[1m])` but I thought I'd post it anyway!
> Add counter for number of config updates the sheduler has made

- pkg/alertmanager/multitenant.go
- pkg/configs/client/configs.go
- pkg/ruler/scheduler.go
If no config changes happened since last poll, we'd have an empty response, and revert to 0.
> Fix latest config id reverting to 0

- Makefile
- circle.yml
- push-images
Reverts weaveworks/cortex#491
After adding `IMAGE_PREFIX=quay.io/weaveworks/cortex-` to the build environment variables, got the following error:
```
./push-images "$NOQUAY"
./push-images (-noquay)
./push-images "$NOQUAY" returned exit code 2
Action failed: ./push-images "$NOQUAY"
```
Reverting for now. Will try to look into this later today / this week.
> Revert "Allow pushing images from a fork"

- pkg/chunk/aws_storage_client.go
Metric for the number of pages we see per query inside QueryPages.
Test plan: `rate(cortex_dynamo_query_pages_count_sum[1m]) / rate(cortex_dynamo_query_pages_count_count[1m])` locally shows average page size of 1 which is expected.
> Add dynamoQueryPagesCount metric

- pkg/querier/querier.go
- pkg/querier/querier_test.go
Nothing was closing the channel, causing the call to block forever.  Fix it by only reading a fixed number of errors off the channel.
> Prometheus remote read handler probably never worked.

- pkg/distributor/http_server.go
If the ingester has returned a properly-formed error then it will have logged what happened; the distributor only needs to log if something went wrong in talking to the ingester.
> Move logging of valid http errors from Error to Debug

- pkg/chunk/gcp/instrumentation.go
- pkg/chunk/gcp/storage_client.go
@tomwilkie, thank you for adding support for Bigtable in https://github.com/weaveworks/cortex/pull/468!
This is just a pet peeve of mine—I'm the PM for Bigtable at Google. :-)
> Fix capitalization of "Bigtable".

- pkg/chunk/iterator_test.go
Fixes #505.
`dummyChunks` creates a sample at `model.Now()` however the test case creates a query with range `model.Now()`-`model.Now()` which is evaluated afterwards. In most cases, the local machine is fast enough for `model.Now()` to be the same which was enough for the mistake not to be caught during development.
> Fix TestLazySeriesIterator_RangeValues intermittent test failure

- pkg/ring/consul_client_mock.go
The entire, encoded, value was being dumped into the log.
As an improvement, get Go to quote unprintable characters and truncate at 40 chars.
> Make consul mock debug logs readable

- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
Fixes part of #516.
`numRetries` was not checked against `maxRetries` which meant it was possible for requests to backoff indefinitely.
> Check numRetries for getDynamoDBChunks

- pkg/chunk/aws_storage_client.go
Create DynamoDB retry count metric to get visibility into how many retries we are doing.
> Create DynamoDB retry count metric

- pkg/chunk/aws_storage_client.go
The retry maxRetries change https://github.com/weaveworks/cortex/commit/0502e4400a0112ac4500e49c6a90f1075028012f alerted to us with a problem with RequestErrors when talking to DynamoDB. Some queries are now reaching the maxRetry limit of 20 and fail.
After investigation https://github.com/weaveworks/service-conf/issues/1066 we believe these are caused by the sheer number of requests we are making due to non-persistent connections.
There is a bug in golang where the maximum idle connections per a host does not work as expected and golang kills idle connections aggressively https://github.com/golang/go/issues/13801
This PR sets `MaxIdleConnsPerHost` explicitly to 100.
---
This change has been tested locally where we have seen Request Errors reduced from a constant stream to none.
Fixes …
> Use custom http.Client for AWS

- pkg/chunk/schema_config.go
Rename `write-scale` to `write-throughput-autoscale` to make it clear that it relates to the `write-throughput` flag.
Ok to rename as it is currently not in use (we only merged it a couple of hours ago).
> Rename write throughput autoscale flags

- cmd/table-manager/main.go
Fix flag check merged in https://github.com/weaveworks/cortex/pull/507.
Should raise an error if autoscaling is enabled and the application auto scaling url **is** nil.
> Fix table manager autoscaling flag check

- pkg/chunk/table_manager.go
Currently we get logs like this:
```
time="2017-08-25T08:47:26Z" level=info msg="Checking provisioned throughput on table prod_chunk_data_weekly_2482" source="table_manager.go:266" 
time="2017-08-25T08:47:28Z" level=info msg="  Provisioned throughput: read = 300, write = 1, skipping." source="table_manager.go:281" 
```
which is not too useful when you are grepping for a particular table
And the update was a little on the enigmatic side too.
> Include more info when logging capacity

- pkg/chunk/aws_storage_client.go
Use linear buckets as there are only 20 options. Include 21 so we can see how many hit 20 retries.
> Update dynamo_query_retry_count bucket sizes

- pkg/chunk/aws_storage_client.go
Looking at [the code](https://github.com/aws/aws-sdk-go/blob/353c163/aws/request/request.go#L452-L480) it is evident that somebody has to clear the value in `r.Error` before calling `Send()`.
This is important in the `pageQuery()` case, where we re-use the same request each time round the loop.  However, inside `pageQuery()` we don't have direct access to `Error`, so it seemed simplest and safer to clear on every `Send()`.
It does not seem particularly clear from the docs, or from the aws sdk itself.  I believe when they do retries it gets cleared [here](https://github.com/aws/aws-sdk-go/blob/353c1631448a44b91547377df96451e3de718490/aws/corehandlers/handlers.go#L229)
I really need to try forcing an error and see what happens, to prove out this theory.
> Clear error before re-sending request

- BUILD.bazel
- Makefile
- WORKSPACE
Add gazelle rule and use them from makefile
Update rules_go to a much newer version needed for photo rules, and use an http archive rule with a commit id instead of a git rule with a tag.
> Minor preparatory updates

- cmd/table-manager/main.go
- pkg/chunk/schema_config.go
- pkg/chunk/table_manager_test.go
Small change to allow us to enable write autoscaling for the last N inactive tables. This is to clear any old metrics, resolving https://github.com/weaveworks/cortex/issues/518 for now.
> Autoscale last N inactive DynamoDB tables

- README.md
If you don't do this, all the `.bazel` files will show up as deleted, which confused me for a while
the second one could be made more efficient - it's running a second `dep ensure`.
> Update vendor instructions in README

- Gopkg.lock
- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
- vendor/github.com/weaveworks/common/aws/config.go
- vendor/github.com/weaveworks/common/aws/config_test.go
- vendor/github.com/weaveworks/common/user/id.go
- vendor/github.com/weaveworks/common/user/logging.go
The code for `awsConfigFromURL()` moves verbatim with the exception of the `.WithMaxRetries(0)`
This update to `weaveworks/common` picks up a couple of logging fixes too.
> Extract awsConfigFromURL function to weaveworks/common

- pkg/ring/consul_client.go
- pkg/ring/consul_client_mock.go
To reduce log spam, allow `longPollDuration` to be configured per-client, and set it to a minute when the 'mock consul' is in operation (e.g. in `lite`).
> Slow down Consul operations in 'lite' mode

- pkg/chunk/dynamodb_table_client.go
This is to please our linter, which was throwing errors like:
```
./pkg/chunk/dynamodb_table_client.go:332:2: 
redundant if ...; err != nil check, just return error instead.
```
```
./pkg/chunk/dynamodb_table_client.go:381:2: 
redundant if ...; err != nil check, just return error instead.
```
> Remove redundant nil checks

- pkg/chunk/aws_storage_client_test.go
The test creates tables for every period from the beginning of the day to now; with a 1 min period that means between 1 and 1440 tables.
Changing to 10 min cuts the number of tables hence number of log lines, etc., and makes finding issues much easier.
I looked for a way to make the overall interval fixed-length, but it seems you can only start from a day-value and you can only sync up to now.
> Use longer period in test to make troubleshooting easier

- pkg/alertmanager/multitenant.go
Marshal/unmarshal json to deep copy config
> Add function to copy struct of amconfig.Config

- pkg/ingester/ingester.go
- pkg/ingester/ingester_flush.go
> Add a flush operation timeout.

- pkg/alertmanager/multitenant.go
Fixes #591 
Triggering off an error was a bad idea - error could be for other reasons.
Also we were returning with the error after first time through `setConfig`, ~thus ignoring any rules changes~ this doesn't actually seem to have any negative effect.
> Use fallback config only if supplied config is blank

- pkg/ruler/scheduler.go
Fixes #482 
We hold on to the parsed rules for each instance instead of having them live entirely in the queue, so that we can use the latest set of rules when we reschedule.
This requires that we lock around the `cfgs` map, so the existing lock was re-purposed to do that.
> Use latest configured rules when rescheduling work

- cmd/querier/main.go
- pkg/chunk/aws_storage_client.go
Similar to #597.  
Note it is inappropriate to route via `nethttp.Middleware` for the httpgrpc routes, since httpgrpc already sets up the opentracing context.  And I didn't need any of the http routes instrumented.
> Add Jaeger to querier

- pkg/chunk/aws_storage_client.go
- pkg/chunk/chunk_store.go
If the chunk store has, say, 1,000 chunks to fetch, it will do them in a loop in batches of 100.  Suppose it gets 900 fetched ok, then the next call hits an error: we should save the 900 to cache.
Reason is the client may be on a retry loop and come straight back with the same request.  So we should cache what we did get, and hence do better next time.
Note we do not retain any chunks obtained by a call which did error; just the ones from earlier successful calls.
> Save chunks to cache if GetChunks returns partial result

- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
Run multiple goroutines in parallel to drive DynamoDB harder: group chunk fetches into "gangs" to allow some configuration over how hard we hit DynamoDB
This is a very simple scheme; it could be done much more intelligently but I think it's worth deploying something simple 
Example query shown below, run against dev: although the overall time is only a little shorter this includes one DynamoDB batch fetch that took 3 seconds, similar to what is described at #602.  In the presence of throttling it gets more efficient to run several queries in parallel which may hit different tables or shards.
Query is `sum(rate(container_cpu_usage_seconds_total{image!="",namespace!=""}[5m])) BY (namespace)` start=1510770800 end=1510770830
Trace before:
and after:
> Parallel chunk fetching from DynamoDB

- pkg/chunk/aws_storage_client.go
- pkg/chunk/backoff.go
- pkg/chunk/dynamodb_table_client.go
1. Put unprocessed requests at the back of the queue on retry: this should maximise the chance that we can get some other work done, especially in the case that DynamoDB is throttling one area of the DB but not another.
2. Don't sleep after the last retry in backoff loop: this just delays reporting errors back
Also some refactoring
> Improve dynamodb retry

- pkg/ruler/ruler_test.go
As seen [here](https://circleci.com/gh/weaveworks/cortex/1471) and [here](https://circleci.com/gh/weaveworks/cortex/1464)
The initialization of the set of Alert Managers by service discovery is async, so the `Send()` can happen before there are any to deliver to.
> Fix race condition in TestNotifierSendsUserIDHeader

- pkg/alertmanager/multitenant.go
- pkg/chunk/aws_storage_client.go
- pkg/chunk/dynamodb_table_client.go
- pkg/ring/consul_client.go
- pkg/ruler/scheduler.go
- pkg/util/backoff.go
Fixes #609 
As an added bonus the wait in `aws_storage_client` ends early if the `Context` is cancelled.
> Unify four backoff implementations

- pkg/ruler/ruler.go
Work-around was added in #484 and made unnecessary by #596
> Remove the work-around for a race condition

- pkg/alertmanager/multitenant.go
- pkg/chunk/aws_storage_client.go
- pkg/chunk/dynamodb_table_client.go
- pkg/ring/consul_client.go
- pkg/ring/ring.go
- pkg/ruler/scheduler.go
- pkg/util/backoff.go
Previously we would only stop if the `Context` signalled cancellation while we were in a sleep. Now, loops that check `backoff.Ongoing()` will end if the `Context` is terminated any time.
A new `backoff.Err()` function is added to report back the reason for termination.
This required reworking the Consul client to use a `Context`, but I think it ends up ok.  I took the opportunity to remove an unused function rather than fix it up.
> Break out of backoff loop if Context is terminated

- pkg/chunk/aws_storage_client.go
- pkg/chunk/chunk.go
- pkg/chunk/chunk_cache.go
- pkg/chunk/chunk_test.go
- pkg/chunk/gcp/storage_client.go
- pkg/chunk/inmemory_storage_client.go
Part of #624 
Calling `Reset()` rather than discarding and creating a new one allows buffers to be re-used, which reduces garbage-collection.
The benefit comes when you decode more than one chunk in a row - 55%-60% less time in these benchmarks:
before:
```
BenchmarkDecode1-2       	  200000	    102466 ns/op	  155771 B/op	     117 allocs/op
BenchmarkDecode100-2     	    2000	  10742609 ns/op	15577124 B/op	   11632 allocs/op
BenchmarkDecode10000-2   	      20	 829417236 ns/op	1557639768 B/op	 1163165 allocs/op
```
after:
```
BenchmarkDecode1-2       	  200000	    113408 ns/op	  155772 B/op	     117 allocs/op
BenchmarkDecode100-2     	    3000	   4202005 ns/op	  967774 B/op	   11335 allocs/op
BenchmarkDecode10000-2   	      30	 378176958 ns/op	82100856 B/op	 1133154 allocs/op
```
> Reuse Snappy decoder, for performance

- Gopkg.lock
- vendor/github.com/weaveworks/common/instrument/instrument.go
So we get to see the error message in the trace when something goes wrong
> Update weaveworks/common to pick up tracing improvement

- pkg/chunk/by_key.go
- pkg/chunk/by_key_test.go
- pkg/chunk/chunk.go
- pkg/chunk/chunk_test.go
Part of #624 
Chunks are sorted, merged and uniq-ified by comparing their key metadata.
Previously this went via `Sprintf()` with six memory allocations per call. 
The replacement is a bit long-winded, but very fast in operation.
Benchmarks:
before (commit 2472029f12a604967a5f17f3591d2a8e5adf2ff5)
```
BenchmarkByKeyLess-2        	 2000000	       681 ns/op	     224 B/op	      12 allocs/op
BenchmarkByKeySort100-2     	    5000	    347669 ns/op	  109587 B/op	    5869 allocs/op
BenchmarkByKeySort1000-2    	     200	   6100690 ns/op	 1931639 B/op	  103466 allocs/op
BenchmarkByKeySort10000-2   	      20	  84477998 ns/op	26671429 B/op	 1428771 allocs/op
BenchmarkEncode-2           	   50000	     22729 ns/op	   85125 B/op	      27 allocs/op
BenchmarkDecode1-2          	   30000	     52825 ns/op …
```
> Avoid memory allocations when comparing chunk keys

- pkg/chunk/chunk.go
The comment would have made sense attached to `metadataInIndex`, but that's special-cased earlier.
> Rewrite out-of-place comment

- pkg/chunk/chunk.go
Since every `Chunk` is created with a `Metric` and a `Fingerprint` at the same time, we should use the latter rather than recomputing it.
Impact of this change is fairly small, generally dwarfed by `Samples()` when we use varbit encoding.
> Use existing Fingerprint value instead of recomputing

- pkg/ingester/ingester.go
The default max chunk age is 12 hours, so we really ought to cover that in our buckets.
If the metric repeats (all zeros, say, and with regular timestamps) then we will can easily fit 12 hours in a 1K chunk.  12 hours of 15-second samples is 2880 samples, so I extended the length buckets to cover that.
> Increase histogram buckets to cover typical scenarios

- pkg/chunk/chunk.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_test.go
- pkg/ingester/ingester_test.go
It's good to discard data we don't need as soon as possible.
This speeds things up when the query time interval does not cover the whole of a chunk.
It will be slightly slower than before when the interval does cover the whole chunk - we could have both variants if that shows up as a problem.
Since `RangeValues()` already does what we need, we save code too.
Part of #624 - if you look closely you will see my sample query covers just 30 seconds; it dates from a time when I was trying to shrink the task to make it easier to see what was happening.
> Restrict to time interval when pulling samples from a chunk

- pkg/chunk/aws_storage_client.go
- pkg/util/backoff.go
As described at https://www.awsarchitectureblog.com/2015/03/backoff.html
Fixes #638 
The bump in config is to address the point that we used to sleep 50 ms then random between 50 and 150, so if this was unchanged we would sleep rand(0-50) then rand(0-100) which is quite a bit less.
With this change it will sleep rand(0-100) then rand(0-200).
(Although my gut feel is this is still too low)
> Change backoff algorithm to "full jitter"

- pkg/chunk/aws_storage_client.go
- pkg/chunk/aws_storage_client_test.go
I think I went too far in #603 - if someone sends a query that requires 260,000 chunks we don't want to hit DynamoDB from 260 goroutines in parallel.
(Ideally there would be a global pool of workers for each table)
> Limit parallelism when fetching chunks from DynamoDB

- pkg/util/validate.go
More specifically, Go regexps have a mutex which means using the same regexp from multiple threads kills performance.
> Use faster validation routines for metric and label names

- Gopkg.lock
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_lifecycle.go
- pkg/ingester/ingester_lifecycle_test.go
- vendor/github.com/weaveworks/common/instrument/instrument.go
- vendor/github.com/weaveworks/common/server/server.go
We see about a 85% reduction in network traffic from distributor to ingester when we try this in our dev environment.
This is good if your network traffic costs more than the CPU it takes to compress it.
> Optionally compress gRPC calls from distributor to ingester

- Makefile
- cmd/lite/main.go
- cmd/ruler/main.go
- pkg/configs/client/configs.go
- pkg/configs/configs.go
- pkg/configs/db/db.go
- pkg/configs/db/memory/memory.go
- pkg/configs/db/postgres/postgres.go
- pkg/configs/db/timed.go
- pkg/configs/db/traced.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/configs.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
Part of #619 
- creates new endpoints for getting & setting ruler configs; puts these endpoints on the ruler itself
- these endpoints only exposed if db flags provided
- creates new database methods that use the existing data structure but mask the fact that ruler & alertmanager configs are mushed together
- updates ruler to use database for getting rules if provided right flag; falls back to config server otherwise
I was going to do alertmanager in the same PR, but this got big quickly.
I'm not wedded to putting the endpoints on the ruler itself.
Pros:
- we can delete the configs service
- the ruler scheduler doesn't need to poll the database
Cons:
- if the ruler scheduler slows down, setting & getting configs on the UI will be slower (although given they both talk to the same DB, their …
> New ruler endpoints

- Makefile
- cmd/lite/main.go
- cmd/ruler/main.go
- pkg/configs/client/configs.go
- pkg/configs/configs.go
- pkg/configs/db/db.go
- pkg/configs/db/memory/memory.go
- pkg/configs/db/postgres/postgres.go
- pkg/configs/db/timed.go
- pkg/configs/db/traced.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/configs.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
Repeat of #620 with a bug fix.
- Adds new CAS endpoints for ruler, addressing part of #330 
- Allows ruler to get configs directly from database, addressing part of #619 
What was the bug fix?
In #620 (and in this PR), the ruler can get configs either from the configs server or directly from the DB. If the configs DB URL flag is set, the ruler will get the configs from the DB. Unfortunately, the DB URL flag is *always* set, due to defaults. This means we try to get configs from a nonexistent database. Ugh.
This PR changes the check to be for _absence of configs API_ setting, rather than _presence of configs DB setting_. This works because the URL flag has no default value. 
The test failure appears to be unrelated flakiness.
> New CAS endpoints for ruler configs on ruler itself

- WORKSPACE
- pkg/ingester/client/BUILD.bazel
- pkg/ingester/client/cortex.proto
- pkg/ring/BUILD.bazel
- pkg/ring/ring.proto
- tools/build/bazel/BUILD.bazel
- tools/build/bazel/gogo.bzl
This uses the gogo repository and new proto rules to generate the .pb.go
files on demand.
Note that this has to use my fork of gogo/protobuf (the bazel rules are not in a good enough shape to ask them to accept them yet, just good enough to use the plugins) and my fork of rules go (although the changes are already in a pull request so that won't be for long)
> Generate .pb.go files

- pkg/ingester/mapper_test.go
These were generating a cyclomatic complexity warning due to the proliferation
of `if` statements.
I've extracted the `if` statement into a function, making the tests more
readable (IMO) and fooling the complexity checker into thinking things are now
simpler.
> Simplify mapper tests

- tools/README.md
- tools/bazel-rules/BUILD.bazel
- tools/bazel-rules/gogo.bzl
Pulls in changes from https://github.com/weaveworks/build-tools/pull/125. See that PR for justification.
Doing as standalone PR because there were conflicts (again).
> Rename tools/bazel to tools/bazel-build

- pkg/chunk/aws_storage_client_test.go
- pkg/chunk/by_key_test.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_test.go
- pkg/ingester/ingester_lifecycle.go
- pkg/ingester/ingester_lifecycle_test.go
`dummyChunkFor` was consulting the system clock itself. This meant that tests
like `TestChunkStore_Get` would intermittently fail, because _sometimes_ the
created chunks would have timestamps outside the window chosen within
`TestChunkStore_Get` (which itself consults the system clock).
This fixes the tests by making `now` a parameter of `dummyChunkFor`, which
makes the created chunks deterministic.
It also adds a `now` parameter to `dummyChunk`, which isn't strictly
necessary, but I believe is less error prone.
Fixes #646 
Thanks to @bboreham for the hint about `chunksToMatrix`, which helped narrow this down.
> Fix flaky chunk tests by being explicit about `now`

- pkg/ingester/client/client.go
The grpc library implementation creates and discards a compressor on every call, and the gzip buffers add up to hundreds of kilobytes, so this is quite an overhead.
> Keep a pool of compressors to save garbage-collection

- Gopkg.lock
- cmd/ingester/main.go
- pkg/ingester/client/client.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/google.golang.org/grpc/encoding/gzip/gzip.go
Depends on https://github.com/weaveworks/common/pull/83; I will fix up when that is merged.
The limit on message size came with the new gRPC.
New-style compression options because the old ones are now deprecated.
> Set gRPC compression and max message options

- pkg/ingester/ingester_claim.go
- pkg/ingester/ingester_lifecycle.go
- pkg/ring/consul_client.go
This fixes the intermittently failing `TestIngesterTransfer`.
The issue was that the `TransferChunks` method (called as an RPC by the departing ingester) would signal that it was complete (`SendAndClose`) *before* it claimed the ring and updated its state to active.
The test, however, runs a query immediately after the departing ingester has shut down.
Thus, there's a very small window after `Shutdown` has terminated but before `ClaimTokensFor` and `ChangeState` have run. When we run the query in this window, we get no results, because there are no ingesters that have the chunks we need.
I've fixed this by moving the call to `SendAndClose` to the end of `TransferChunks`. I *think* this is the right approach, but am not 100% sure.
An alternative would be to prevent the race in the test …
> Fix intermittently failing TestIngesterTransfer

- cmd/ruler/main.go
- pkg/ingester/ingester_lifecycle.go
Current code gives you this kind of thing:
```
ts=2018-01-15T15:01:20.02110214Z caller=log.go:108 level=error msg="Error looking for pending ingester: %v"
ts=2018-01-15T15:01:20.021162734Z caller=log.go:108 level=error msg="Failed to transfer chunks to another ingester: %v"
```
> Fix typos in error logging

- pkg/alertmanager/multitenant.go
This PR moves alertmanager's "logging to stderr" to using our global `util.Logger`.
PR #658 has switched from logrus to go-kit. Logrus' default log level is
INFO while go-kit's is DEBUG. Since the alertmanager hasn't been using
our global logger its log level wasn't set.
> Use our global logger for the alertmanager

- pkg/configs/api/api.go
- pkg/configs/configs.go
- pkg/configs/db/db.go
- pkg/configs/db/memory/memory.go
- pkg/configs/db/postgres/postgres.go
- pkg/configs/db/timed.go
- pkg/configs/db/traced.go
- pkg/ruler/scheduler.go
should call this to deactivate config after instance deletion
> Add endpoints to deactivate and restore config

- build-image/Dockerfile
> Update to go 1.9.3

- k8s/nginx-config.yaml
To change the value of resolver in nginx-config.yaml since the address of kube-dns changed.
I derived the following errors.
```
...
172.17.0.14 - - [27/Jan/2018:16:53:38 +0000]  499 "POST /api/prom/push HTTP/1.1" 0 "-" "Go-http-client/1.1" "-"
172.17.0.14 - - [27/Jan/2018:16:53:38 +0000]  499 "POST /api/prom/push HTTP/1.1" 0 "-" "Go-http-client/1.1" "-"
...
```
I followed the instruction documented in README.md to build development environment on my MAC.
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", …
```
> Change the value of resolver in nginx-config.yaml

- pkg/chunk/gcp/storage_client.go
Send in a lexicographically greater-than string to ReadRows and let the bigtable server
stop sending rows when's its finished.
We measured a 25-30% reduction in response time on the p90.
Some code for testing the queries outside of cortex: https://gist.github.com/bcotton/c76a9efc394d442b7d3689f8a8b7e2ca
> Teach storage_client.QueryPages to use a RowRange that filters on the server.

- cmd/ingester/main.go
This relates to #672 - believe that limiting the number of streams would stop the infinite blow-up of goroutines, though not really fix the underlying problem.
Plausibly this should be in weaveworks/common/server, but I wanted to try it out more locally first.
> Add gRPC MaxConcurrentStreams limit and flag

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_lifecycle.go
- pkg/ingester/ingester_lifecycle_test.go
- pkg/ruler/ruler.go
Remove code that appears to set a timeout but actually does nothing, set a timeout on each call to `Push()` in the distributor, and set a timeout on entire rule-group evaluation in the ruler.
This is a plausible fix for #672, but see also #679
> Fix Ingester timeouts

- pkg/configs/db/postgres/postgres.go
- pkg/ruler/scheduler.go
Add `deleted_at` to `GetConfig`, `findConfigs` and `findRulesConfigs` functions so they can return actual value of `deleted_at` for later use in ruler. Otherwise, ruler never discoveries deleted configs and never delete them from the map.
By default `deleted_at` column in DB set to `NULL` so we scan this into `pq.NullTime` variable (because we cannot store `nil` value into type `time.Time`).
To restore config we set `deleted_at` column in DB to `NULL`.
fixes https://github.com/weaveworks/service-conf/issues/1859
> Scan deletedAt (time or null) in findConfigs, findRulesConfigs and GetConfig

- pkg/configs/configs.go
- pkg/ruler/scheduler.go
I was puzzled why we are still getting errors in the logs from deleted instances - they will run once then stop, but the notifier created for them will carry on.
> Don't run deleted rules

- cmd/ruler/main.go
Given that the ruler pulls triple (quadruple?) duty as a querier, distributor, alerter, etc., it seems helpful to have Jaeger traces enabled. Particularly as we're investigating some sneaky query slow-downs that seem to be isolated to the ruler.
> Enable Jaeger tracing in the ruler

- cmd/distributor/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
This PR is a partner of https://github.com/weaveworks/common/pull/87.
This commit adds runtime configuration env vars to allow each system that's Jaeger-enabled to specify its own sampling strategy and parameters. We chose defaults of `jaeger.SamplerTypeRateLimiting` and `10.0` to yield an intuitive default behavior of "send ~10 traces per second to the collector". Other strategies are certainly usable here, however, and I'd happily entertain different default behaviors.
To test this independent of the state of the weaveworks/common PR referenced above, you can add these lines to your local Cortex repo's `Gopkg.toml`:
```
[[override]]
name = "github.com/weaveworks/common"
source = "github.com/Fresh-Tracks/weaveworks-common"
revision = "e6856c7a5d16d9525051dc8daf3ce5399e5a9384"
```
With …
> Enable configurable Jaeger sampling strategies (with defaults)

- cmd/lite/main.go
- cmd/ruler/main.go
- pkg/configs/db/db.go
- pkg/ruler/configs.go
Remove the default for database flags, requiring database flags to be specified in order to be used.
Why? So we can serve new ruler config endpoints only if the ruler has information about the database, which is necessary to serve the endpoints.
In #649, I submitted a PR which added new config endpoints and only served them if the ruler was *not* configured with configs API endpoints. This is a bit silly, as we want the ruler to be able to talk to the configs server during the migration process. i.e. we want the ruler (temporarily) to have both a configs API URL and a database URL.
The reason we used "absence of configs API" rather than "presence of DB" is that there was no way to detect presence of DB, because the default URL value meant it was always present.
Thus, we change the default …
> Remove default for database flag

- cmd/lite/main.go
- cmd/ruler/main.go
- pkg/configs/db/db.go
- pkg/ruler/configs.go
Reverts weaveworks/cortex#708
```console
$ kubectl get po --namespace=cortex
...
ruler-85f79bb777-l2nmt           0/1       CrashLoopBackOff   6          6m
...
$ kubectl logs --namespace=cortex ruler-85f79bb777-l2nmt
ts=2018-02-15T14:40:02.482696195Z caller=log.go:108 level=error msg="error initializing rules API" err="Unknown database type: "
> Revert "Remove default for database flag"

- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/table-manager/main.go
- pkg/chunk/aws_storage_client_test.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/schema_config.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
Fixes #621 
`TableManager` uses `MaxChunkAge` to hold off scaling back the previous table, and in #583 this was moved to `ingester.Config` but not removed from the previous place.  Moving the value to a parameter means you can't forget to copy it from `ingester.Config` to `chunk.SchemaConfig`.
(We can't just pass `ingester.Config` in, because package `ingester` imports package `chunk`, so there would be a cycle)
> Move SchemaConfig.MaxChunkAge to NewTableManager()

- pkg/ruler/ruler.go
Using `weaveworks/common/instrument` in `Evaluate()` gives us a tracing span which ties together all the sub-operations for that rule group.
It would be better to have a span per rule, but that is inside Prometheus.
I also changed the histogram buckets for eval duration to go up to 25 seconds, and drop the low end below 100ms.
> Improve ruler tracing

- pkg/util/hash_bucket_histogram.go
The observed issue is that `cortex_chunk_store_row_writes_distribution_sum` is all NaNs, although the buckets have reasonable values.
I'm not 100% sure this is the cause, but there's only so much time in the day.
> Don't divide by zero in hash bucket histogram

- pkg/configs/configs.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
Instead of having to evaluate all rules sequentially for each tenant, instead evaluate the rules sequentially for each file, but allow the files to be done in parallel. This allows tenants with large numbers of rules to have their rules evaluated more efficiently. We saw a significant improvement in rule evaluation durations upon deploying this code.
Are there any concerns with this approach?
It looks like this PR will end up with a lot of merge conflicts with https://github.com/weaveworks/cortex/pull/689, if that is going in soon it may be worthwhile to wait to merge this until afterward.
> Evaluate Ruler files in parallel

- pkg/ruler/ruler.go
The `blocked_workers` metric can't give us a good indication of how busy the ruler is, because work happens every 15s and we sample every ~15s.
The `evalLatency` metric indicates when evaluations are late, i.e. when we have reached/exceeded our capacity, but doesn't indicate how close we are to it in normal circumstances.
Using an idle time counter should give us an idea of how much slack we have in the queue processing; if it approaches 0, then we know our workers are at capacity.
Since counters are monotonic, this should allow us to measure utilisation without hitting the same sampling issue.
> Add a worker time-spent-idle counter to the ruler

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_lifecycle.go
- pkg/ingester/ingester_lifecycle_test.go
We have some data scenarios where the amount of data exceeds the 64MB fixed size that the grpc client was set to for a max message size (added in [#660](https://github.com/weaveworks/cortex/pull/660)). This update changes that to a configurable command arg flag, with the default being set to 64MB.
> Updating IngesterClient MaxCallRecvMsgSize to be configurable vs fixed size

- pkg/chunk/aws/storage_client.go
To help investigate #733.  From existing log lines I know we very commonly get just 1 item remaining at the timeout, so I want to know what it is.
Also some drive-by comments because I needed to figure out what was going on.
> Log outstanding writes in DynamoDB

- pkg/ring/ring.go
If we don't emit anything for a metric then Prometheus takes the last value until it is stale, i.e. for 5 minutes.
> Fix distributor state metric showing PENDING and JOINING way too long

- pkg/distributor/distributor.go
Use a background context for the pushes to the ingester. This allows the context to continue after the request is returned in order to finish writing to `replicas` ingesters, rather than stopping after a quorum. 
Solution to: https://github.com/weaveworks/cortex/issues/730
Alternative to: https://github.com/weaveworks/cortex/pull/732
Jaeger trace showing the third push finishing after the request is done:
> Perform ingester pushes in a background context rather than the request context

- pkg/chunk/chunk_store.go
- pkg/chunk/gcp/storage_client.go
Adds tracing to the BigTable backend for getting chunks, and adds a higher level span to the `ChunkStore.Get` function to make jaeger traces more clear on the difference between distributor and chunk store paths.
Before:
After:
> Add additional jaeger spans to the query path

- pkg/ingester/ingester.go
More detail on small chunk lengths, since I think I'm seeing a lot of them, and focus the 'age' buckets around the two extremes we expect.
> Tweak ingester histogram buckets

- pkg/chunk/schema_config.go
- pkg/chunk/table_manager.go
When you have a problem, set `-table-manager.throughput-updates-disabled=true` and manually tweak the settings in your cloud console.
Currently we scale it down to zero while tweaking, which means we lose the reporting of metrics and creation of new tables.
>  Add master 'off-switch' for table capacity updates

- cmd/distributor/main.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/http_admin.go
- pkg/ingester/client/cortex.proto
- pkg/ingester/ingester.go
This adds a web page a bit like the 'ring' page, but showing what different instances are using across all ingesters.
On the day when we suddenly had N million extra timeseries, I really wanted this feature.  But looking at the amount of code I'm not so sure I like it.  I'm open to suggestions.
> Add admin http page to view stats across all users

- README.md
With Bazel completely broken, I guess it's best not shown on the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/cortex/756)
> Update README for clearer dev. env setup

- cmd/ingester/main.go
- pkg/ingester/ingester_flush.go
- pkg/util/events.go
Log-like API to generate events, plus simple implementation dumping to stderr.
Only wired into ingester for now.
You would turn this on via command-line parameter `-event.sample-rate=1000`, for example, then one in every 1000 "events" will appear in your log file, and you can extract them for analysis in your favourite tool.
> Basic event logging for observability

- pkg/ingester/ingester_claim.go
- pkg/ingester/ingester_flush.go
- pkg/ingester/series.go
Use our own idea of time received to compare against `Now()` when computing age and idle time. The sender may have a clock skew, or may be in catch-up mode sending older data.
Fixes #757
> Separate the time on this server from the time in received samples

- cmd/distributor/main.go
Related to #666 
Looks like this was left over when the overlapping functionality was added in `cortex/pkg/util/log.go`
I'm not 100% sure what this would have done, but in any case, it doesn't make sense to do this in one server and not the others.
> Don't add promrus hook in distributor main

- Gopkg.lock
- cmd/distributor/main.go
- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- vendor/github.com/weaveworks/common/logging/logging.go
- vendor/github.com/weaveworks/common/middleware/grpc_logging.go
- vendor/github.com/weaveworks/common/middleware/logging.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/github.com/weaveworks/common/tracing/tracing.go
EDIT: Please see #703 for description
@JML - I'm not entirely sure that adding an override to Gopkg.toml was the proper fix, so if I got it wrong, let me know what the proper method is and I'll fix it up. :-)
Thanks!
> Re-try addition of configurable trace sampling strategy

- cmd/lite/main.go
- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
lite uses both ingester.Config and distributor.Config. Both of them has IngesterClientConfig, so calling RegisterFlags on them triggers panic.
This fix ignores second call to RegisterFlags on IngesterClientConfig and then populates it manually
Was broken in https://github.com/weaveworks/cortex/commit/6191d41c5a99e6f89fbd1877afc8805ab0c3ffbd
> Fix panic in lite

- pkg/chunk/aws/storage_client.go
- pkg/ingester/ingester_flush.go
- pkg/ingester/series.go
- pkg/ingester/user_state.go
- pkg/util/priority_queue.go
Fleshing out the "event sampling" with more detail on chunks flushed, DynamoDB retries and series creation.
Also stop logging/eventing in the case where all retries are exhausted - this isn't useful if you sample all retries.
While I was in here I created a metric for chunks created - so you can see the rate of creation compared to the rate of flushing.  Fixes #567
> More ingester events

- pkg/ingester/ingester_lifecycle.go
- pkg/ingester/series.go
Fixes #776 
Not sending an empty series is a tiny optimisation.
> Check for empty series during ingester chunk transfer

- pkg/ingester/ingester_claim.go
- pkg/ingester/ingester_lifecycle.go
One message said "to ingester" when it meant "from ingester", which was confusing.
I have corrected that and changed all of them to a more structured-logging style.
> Improve log messages on chunk transfer

- pkg/chunk/cassandra/storage_client.go
`gocql.NewBatch` is deprecated and doesn't register the observer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/cortex/782)
> Use the right Batch creator to register stats.

- pkg/chunk/chunk.go
- pkg/chunk/chunk_test.go
Fixes #769 
Now we need to copy the buffer in `TestChunkCodec()` so we can change it without changing the original.  And blank out the encoded data in `BenchmarkEncode()` otherwise it just copies the pointer.
> Retain encoded version of chunk so we don't have to re-encode it.

- pkg/chunk/chunk_store.go
- pkg/ingester/ingester_flush.go
Fixes #715 
I added a separate parameter to set on the ruler and querier, as this seems cleaner.  Needs to be at least a bit higher than the Prometheus "stale" time (5 minutes), and also lower than the ingester idle time.
Also a small addition to the OpenTracing data which I found useful to check whether it was working.
> Retain chunks in ingester for idle time, so 'now' queries don't hit the store

- pkg/chunk/schema_config.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
Fixes #749 
Most of this PR is setting up the unit test.
> Fix auto scaling - don't set inactive write scaling on active tables

- pkg/ingester/ingester_lifecycle.go
- pkg/util/priority_queue.go
Fixes #427.  When the reader calls `Dequeue()` after the queue is empty we will set the `closed` flag so subsequent calls to `Enqueue()` still panic.
Also a drive-by renaming since to me "drain" implies we will read all the data from the queue, not throw it away.
> Allow ingester to re-enqueue data while closing down

- pkg/chunk/aws/dynamodb_table_client.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/mock.go
- pkg/chunk/aws/storage_client.go
- pkg/chunk/storage/storage_client_test.go
We will put the chunks fetched so far into the cache, so if the client retries we will probably get a bit further next time.
This change was already made by #605, but it was broken about an hour later by merging #603 which was created before.
> Return chunks fetched by GetChunks on error

- pkg/chunk/aws/storage_client.go
- pkg/util/backoff.go
The code has a bad smell - a comment saying we don't know why it's there. 
Empirical evidence from tracing shows that we end up waiting so long that a higher-level timeout will kick in and kill the whole operation, even though DynamoDB is reporting some progress.
If it turns out waiting was necessary, DynamoDB will tell us next time round the loop and we'll crank up the backoff again, so no harm done.
Part of #792
> Remove backoff.WaitWithoutCounting()

- .gitignore
- Makefile
- build-image/Dockerfile
- We use various `find` commands to figure out what to build; stop these traversing various large directories they shouldn't.
- Update to go 1.10 and start using its build caching.
Before these changes:
```
$ make clean
$ time make cmd/distributor/distributor
...
real	1m26.436s
user	0m0.848s
sys	0m0.699s
```
After:
```
$ make clean
$ time make cmd/distributor/distributor
...
real	0m35.185s
user	0m0.813s
sys	0m0.379s
```
> Various minor improvements to the Makefile

- cmd/configs/main.go
- cmd/lite/main.go
- cmd/ruler/main.go
- pkg/configs/api/api.go
- pkg/configs/api/helpers_test.go
- pkg/configs/client/configs_test.go
- pkg/configs/configs.go
- pkg/configs/configs_test.go
- pkg/configs/db/memory/memory.go
- pkg/configs/db/postgres/postgres.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
The binary-wide rule format version flag is now removed in favor of
a per-user format version stored in the user's config JSON blob. That
JSON blob is created by the web UI and sent to the config API, so it's
now up to components outside of the Cortex backend (e.g. the Weaveworks
service UI) to set what rule format version they would like to set. If
the new JSON field for the version is omitted, it will default to 1.x
format upon unmarshaling.
This change can be rolled back safely to an older version of Cortex as
long as no 2.x rule files have been created.
> Allow setting rule format version per user

- pkg/chunk/chunk_store.go
This is to address logs like these:
```
ts=2018-04-30T12:00:37Z caller=log.go:112 level=error org_id=123 msg="adjusting end timerange from future to now" old_through=1525089638 new_through=1525089637.71
ts=2018-04-30T12:00:38Z caller=log.go:112 level=error org_id=123 msg="adjusting end timerange from future to now" old_through=1525089639 new_through=1525089638.425
```
> Allow client time to be slightly in the future without moaning

- pkg/ingester/index.go
Couple of small changes which will trim some fat from this operation.
We saw `MetricsForLabelMatchers` taking up to 3 seconds on Sunday, which I think has to have a deeper root cause, but every little helps.
> Optimise ingester index lookup

- pkg/util/log.go
- pkg/util/promlog.go
Fixes #655 by making `DefaultCaller` the last wrapping function.
`promlog.go` copy-pasted from prometheus/common/promlog until https://github.com/prometheus/common/pull/116/files is merged
> Fix reporting of code location in log lines

- pkg/chunk/aws/dynamodb_table_client_test.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/storage_client_test.go
- pkg/chunk/cassandra/fixtures.go
- pkg/chunk/gcp/fixtures.go
- pkg/chunk/storage/storage_client_test.go
- pkg/chunk/storage/utils_test.go
- pkg/chunk/storage_client.go
- pkg/chunk/table_manager_test.go
- pkg/chunk/testutils/testutils.go
Clean up the test added in #791 by adding another package that both users can import.
Cuts out a check on the test name string, and an interface.
The `mtime.NowReset()` lines are needed to meet the assumption of the chunk fixture.
> Move DynamoDB-specific test to aws directory

- pkg/distributor/http_server.go
- pkg/querier/querier.go
- pkg/util/http.go
Makes the function more general and reusable for HTTP responses.
> Don't pass a http.Request to ParseProtoRequest; pass an io.Reader 

- pkg/querier/querier.go
- pkg/ruler/ruler.go
I have tested this change in our environment and it fixed the missing data while the latest datapoint is older than 5m.
> added missing lookback-delta parameter (#820)

- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
Deprecate v7 and v8 schema versions since they don't really work. Make it more obvious in the example k8s configuration that v6 should be used.
> Deprecate v7 and v8 schema versions

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/http_server.go
When the distributor's push handler hits the ingestion rate limit due to
prom clients sending too much data consistently, we are unlikely to
catch up.
If we return a 429 here, the client will discard the congested data.
> Return HTTP 429 if ingestion rate limit exceeded

- cmd/distributor/main.go
Currently getting 200K+ log lines which are no use to anyone.
Similar action was taken in #709 for the ingester.
> Remove grpc request from distributor logs

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/series.go
- pkg/ingester/validate.go
- pkg/ingester/validate_test.go
We would like to limit the number of label names in a series.
`metric{l1=v1, l2=v2, ..., lN=vN}`
With the current schema, we create an `IndexEntry` for every label name in a series. A metric with 1000's of label names in one series can lead to a single chunk having 1000's of index entries associated with it.
Is this the right approach to preventing this?
cc @tomwilkie
> Limit number of label names in series

- pkg/chunk/aws/storage_client.go
addresses #846 
The counter should be generic enough to be used in any other exceptional case where we have to drop the entire request, instead of retrying it.
> Adding counter for dropped dynamo requests

- .circleci/config.yml
- Makefile
We had a bunch of rules in `Makefile` insisting the build image was up-to-date in the `else` clause of `BUILD_IN_CONTAINER`, and a matching bunch of CI instructions to `touch` the file.
Lose (almost) all of this.
> Don't check the build image is up-to-date when not using it

- pkg/ruler/compat.go
- pkg/ruler/group.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
- pkg/ruler/scheduler_test.go
Instead of storing an array of rules, store a prometheus rule group on the work item. This allows the ruler to keep a history of previous results, and mark series stale if they disappear.
I am interested in feedback about the approach/any downsides. However, it needs some more time for testing before merging.
Fixes #838
> Ruler will add stale markers to stale series

- pkg/ingester/flush.go
Go treats the whole underlying array as live, so chunks that are to the left of the start of the slice hang around in memory until the next time the slice is extended by allocating a new array.  Defeat this by zeroing the pointers.
I couldn't find a great reference for this behaviour, but it does match what I see in profiles: there are about 1.7 times as many memory blocks as there are chunks reported by the ingester.
Some less-great references:
http://grokbase.com/t/gg/golang-nuts/14a6c2z17b/go-nuts-unreachable-elements-in-slice-and-garbage-collection
https://stackoverflow.com/a/28432812/448734
> Erase references to flushed chunks so they can be garbage-collected

- docs/arguments.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/pool.go
- pkg/ingester/client/pool_test.go
- pkg/util/matchers.go
Stop sharding amongst ingesters by metric name; use all the labels.
Sharding by metric name was designed to reduce the number of ingesters you need to hit on the read path; the downside was that you could hotspot the write path.
In hindsight, this seems like the wrong choice: we do many orders of magnitude more writes than reads, and ingester reads are in-memory and cheap. It seems the right thing to do is to use all the labels to shard, improving load balancing and support for very high cardinality metrics.
And check for sorted labels.
> Stop sharding amongst ingesters by metric name; use all the labels.

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/pool.go
- pkg/ingester/client/pool_test.go
- pkg/util/matchers.go
Makes the ingester client pool only rely on grpc_health_v1 interface; I've found this code useful in other projects after reducing this coupling.
Also move the cleanup loop into `pool.go`, and do some tidy ups: rename pool method target to p, remove to stuttering.
> Uncouple ingester/client/pool from the ingester client, so it can be used elsewhere.

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/validate.go
- pkg/ingester/validate_test.go
Also make the error string a const for consistency and shorten it for readability
> Include metric name in error message for too many labels

- pkg/ingester/ingester.go
- pkg/ingester/user_state.go
As suggested here: https://github.com/weaveworks/cortex/issues/858#issuecomment-401445831
Hoping this will give better concurrency than map+RWMutex.
The docs say:
> sync.Map is optimized for use [...] with keys that are stable over time
We will tend to have a steady set of users sending data, with lots of additions at startup and very few deletions.
The first commit is an extension in the same vein as #861; it is included here because it simplifies the changes needed for `sync.Map`.
I renamed `unlockedGet()` to `getSeries()` since we no longer have a lock; I confess I don't see why it was named that way anyway.
> Use sync.Map in ingester userStates

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/client.go
- pkg/ingester/client/pool.go
- pkg/util/flags.go
Its quite brittle to have the test specify default config values; when you add a new config value in one package, some random test in another package could start failing.
Also helps weed out places where we've used `flag` instead of the passed `f`.
> Start using the flag's default values in tests.

- cmd/alertmanager/Dockerfile
- cmd/configs/Dockerfile
- cmd/distributor/Dockerfile
- cmd/ingester/Dockerfile
- cmd/lite/Dockerfile
- cmd/querier/Dockerfile
- cmd/ruler/Dockerfile
- cmd/table-manager/Dockerfile
I needed to exec in and curl the queriers to test some timeouts, and this was hard with the busybox image.  Using alpine is much easier.
> Use alpine:3.8 as a base image, install ca-certs.

- .circleci/config.yml
Only login to docker hub if a docker hub password is specified. This allows someone to only upload to quay if they want.
> Only login to docker hub if you provide the secret

- README.md
Adds the CNCF TOC presentation for people to look at when learning about Cortex
> Add the CNCF TOC presentation to the README

- pkg/ring/consul_client.go
Consul can optionally restrict changes to clients with ACL tokens. This allows using cortex if consul is configured that way.
> allow specifying an ACL token for consul interaction

- Gopkg.lock
- cmd/distributor/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- pkg/distributor/distributor.go
- pkg/distributor/http_admin.go
- pkg/ingester/client/pool.go
- vendor/github.com/prometheus/client_golang/prometheus/collector.go
- vendor/github.com/prometheus/client_golang/prometheus/doc.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/http.go
- vendor/github.com/prometheus/client_golang/prometheus/metric.go
- vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
- vendor/github.com/prometheus/client_golang/prometheus/registry.go
- vendor/github.com/prometheus/client_golang/prometheus/summary.go
- vendor/github.com/prometheus/client_golang/prometheus/value.go
- vendor/github.com/prometheus/client_golang/prometheus/vec.go
Also:
- use global metrics in the distributor
- update prometheus/client-go to latest master (bcbbc08eb2ddff3af83bbf11e7ec13b4fd730b6e)
- instead of counting number of clients for `cortex_distributor_ingester_clients`, keep a counter which we increment when we create a client and decrement when we remove one.
- use promauto so we don't forget to register them.
Fixes #888, fixes #868
> Expose replication factor as a metric and on the admin page.

- pkg/distributor/distributor.go
- pkg/ingester/ingester.go
- pkg/ingester/series.go
- pkg/util/validation/validate.go
- pkg/util/validation/validate_test.go
When a customer configures things incorrectly they can swamp our service logs fairly easily if we log each time they send us bad data.
NB: adds the userID to a service-level metric
Related to #577, #849
>  Record validation errors in metrics, not log lines

- pkg/chunk/cassandra/storage_client.go
This is helpful when hosted services (e.g. Azure CosmosDB) provide a non-standard port for connection.
> allow specifying the port that cassandra is listening on

- pkg/ring/lifecycler.go
I have to run the ingesters in a port mapped setup, so this allows passing in the actual external port so they can register in consul correctly.
> allow specifying ingester port for registration

- k8s/nginx-config.yaml
To fix this:
```
$ kubectl logs nginx-55b9f744d5-bhrtd
2018/08/02 10:37:04 [emerg] 1#1: open() "/etc/nginx/nginx.pid" failed (30: Read-only file system)
nginx: [emerg] open() "/etc/nginx/nginx.pid" failed (30: Read-only file system)
```
> Put the nginx pid in /tmp

- Gopkg.lock
- cmd/table-manager/main.go
- pkg/chunk/aws/aws_autoscaling.go
- pkg/chunk/aws/dynamodb_table_client.go
- pkg/chunk/aws/dynamodb_table_client_test.go
- pkg/chunk/aws/metrics_autoscaling.go
- pkg/chunk/aws/metrics_autoscaling_test.go
- pkg/chunk/aws/storage_client.go
- pkg/chunk/cassandra/table_client.go
- pkg/chunk/gcp/table_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/schema_config.go
- pkg/chunk/table_client.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- vendor/github.com/prometheus/client_golang/api/client.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
Fixes #735 
To use this feature, set `-dynamodb....scale.enabled` on in command-line args but do not supply an AWS autoscaler `-applicationautoscaling.url`.
Also set `-metrics.url` to point at a Prometheus API-compatible server which will serve the metrics.
(at the time of writing this can't be a multi-tenant server because I didn't put in an option for the tenant)
PR also includes much refactoring of existing tests because I couldn't stand so much repetition.
Outstanding things I should do:
For extra credit:
>  Auto-scale DynamoDB provision based on Prometheus metrics

- pkg/ingester/ingester.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/user_state.go
This is Conference Driven Development from #PromCon2018 :) 
We had an outage where a very large query took out the ingesters.  Quick patch protecting it.
> Protect ingester against very large queries.

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
- pkg/util/validation/limits.go
- pkg/util/validation/override.go
- pkg/util/validation/validate.go
- pkg/util/validation/validate_test.go
This allows us to set relatively low default limits for most users, and then on a per-case basic raise them for individual users.  This allows us to run a more tightly-provisioned cluster without fear a single user will 10x their load and bring the cluster down.
> Run-time reloadable per-user overrides for the various limits in Cortex.

- pkg/ingester/index.go
- pkg/ingester/ingester_test.go
- pkg/ingester/series_map.go
- pkg/ingester/user_state.go
- vendor/github.com/segmentio/fasthash/.gitignore
- vendor/github.com/segmentio/fasthash/LICENSE
- vendor/github.com/segmentio/fasthash/README.md
- vendor/github.com/segmentio/fasthash/fasthash.go
- vendor/github.com/segmentio/fasthash/fasthash32.go
- vendor/github.com/segmentio/fasthash/fnv1a/hash.go
- vendor/github.com/segmentio/fasthash/fnv1a/hash32.go
Adding a new user with ~15m series, saw the ingesters latency go through the roof.
Benchmarked series creation and saw it doesn't parallelise.   Made series creation scale better with number of cores (up to ~16 cores).
This is achieved by sharding many of the datastructures on the series creation path, such as the seriesMap, the inmemory index et
Graph of test run time vs parallelisation for 1 to 32 goroutines.  Test was run on a 32 vCPU-optimised droplet.
> Make series creation scale better with number of cores

- COPYING.LGPL-3
- VENDORED_CODE.md
Once #904 is fixed, this PR should be merged to fix the current license information.
Regarding assert.sh, we follow https://github.com/weaveworks/build-tools/pull/138
Regarding the MPL licensed code, I followed https://www.apache.org/legal/resolved.html#category-b
>    license: document vendored code which is under LGPL3 and MPL-2.0

- pkg/querier/chunk_queryable_test.go
> Reduce size of TestChunkQueryable so it doesn't intermittently timeout.

- pkg/ingester/client/timeseries.go
Small typo; hoping to get this in as a breaking change since it's only two weeks since the flag was added.
> Typo: expecter->expected

- pkg/configs/configs.go
Fix ALERTS series not being output. As @gouthamve suggested, use restored=true when creating alerting rules.
Fixes: https://github.com/weaveworks/cortex/issues/944
> Set restored=true for alerting rules

- pkg/chunk/series_store.go
> logging: kitlog drops keys with space. fix some debug logs

- pkg/distributor/distributor.go
- pkg/querier/chunk_queryable.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_test.go
This behaviour was  lost when I moved us to using upstream iterators.
> Parallelise queries between the chunk store and the ingester.

- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
Fixes #954
We don't know how we got in this state initially, but I suspect it was caused by an ingester being killed quickly - it started a transfer, but didn't actually get a chance to send any series.  This triggered the EOF break, and the new ingester joined the ring with 0 tokens.  
These checks should cause the new ingester to reject the transfer request if it doesn't receive a ingester ID or any series, leaving the ingester to join the ring itself.
> Don't succeed a transfer if no series are received.

- pkg/chunk/cache/fifo_cache.go
- pkg/chunk/cache/fifo_cache_test.go
- pkg/chunk/fifo_cache.go
- pkg/chunk/fifo_cache_test.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_fixtures.go
- pkg/chunk/storage/caching_storage_client.go
- pkg/chunk/storage/factory.go
- pkg/chunk/storage/index_test.go
- pkg/chunk/storage/utils_test.go
An in-process cache for index queries to accelerate queries.
Cache entries are valid for 15mins as thats how long the ingester will hold flushed chunks for.
> Cache index queries for up to 15mins

- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/ingester/client/client.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/cortex.proto
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/querier/chunk_queryable.go
- pkg/querier/config.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_test.go
- pkg/querier/ingester_streaming_queryable.go
- pkg/querier/ingester_streaming_queryable_test.go
- pkg/ring/replication_set.go
- pkg/ring/ring.go
- pkg/ruler/ruler_test.go
- pkg/util/chunkcompat/compat.go
Should reduce CPU load on ingesters & network load as chunks as compressed; generally allows us to do much bigger queries without risk of OOMing the ingester.
Also:
- factor out the replication/consistency handling logic onto a method of `replicationSet`.
- move distributor query methods to separate file, in preparation for removing them from the distributor all together.
Fixes #913
> Stream chunks from ingester to querier on queries.

- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_test.go
As discussed in the community call ~a month ago.  Removed the flags as well, so the jobs won't start if you are using these schemas.
Fixes #876
> Remove v7 & v8 deprecated schemas.

- pkg/chunk/storage/factory.go
Returning an error is preferable to crashing.
> Check -dynamodb.url is set in aws mode

- pkg/chunk/aws/storage_client.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk_store.go
- pkg/chunk/gcp/storage_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/storage/caching_storage_client.go
- pkg/chunk/storage/index_test.go
- pkg/chunk/storage_client.go
- pkg/chunk/util/util.go
With the series index, resolving series ID to chunk IDs can issues 100s of thousands of queries to the index.  The cache does a good job of handling most of these, but we should batch the rest.
As part of this I changes the BigTable backend to only read full rows - this shouldn't impact performance, as the index cache was forcing us to only read full rows anyway.  I also changed the ReadBatch interface to be iterator-style, so we can filter it down without copies.
Fixes #969
> Batch index lookups on BigTable

- pkg/ingester/ingester.go
This is a small optimisation, particularly for queries which are in the past.
> Make Ingester.Query() drop empty timeseries from results

- Gopkg.lock
- pkg/querier/frontend/frontend.go
- pkg/util/log.go
- vendor/github.com/weaveworks/common/middleware/http_tracing.go
- vendor/github.com/weaveworks/common/middleware/logging.go
- vendor/github.com/weaveworks/common/server/server.go
~(WIP, don't merge as it modifies vendored libraries - see https://github.com/weaveworks/common/pull/123)~ merged and vendored properly.
> Log trace IDs, correctly propagate trace IDs from frontend to querier

- pkg/util/validation/limits.go
After some discussion on the channel.  They were too low to begin with.
> Raise default series-per-query limit to 100K, and samples-per-query limit to 1M.

- pkg/prom1/storage/local/chunk/chunk.go
- pkg/prom1/storage/local/chunk/varbit.go
- pkg/querier/batch/batch.go
- pkg/querier/batch/chunk.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/batch/merge.go
- pkg/querier/batch/merge_test.go
- pkg/querier/batch/non_overlapping.go
- pkg/querier/batch/non_overlapping_test.go
- pkg/querier/batch/stream.go
- pkg/querier/batch/stream_test.go
- pkg/querier/benchmark_test.go
- pkg/querier/chunk_iterator.go
- pkg/querier/chunk_merge_iterator.go
- pkg/querier/chunk_queryable_test.go
- pkg/querier/config.go
The idea here is that instead of fetching 1 sample per iteration, fetch N.  This should reduce the amount of work we have to do in the heap etc.  The tradeoff is you have to fetch and repeatedly merge/dedupe "a bunch" of batches each time round.
To find the "optimal" batch size I ran `BenchmarkChunkQueryable/batches/DoubleDelta/foo-4` for all sizes between 1 and 128 (three runs, blue&red with go1.10 and yellow with go1.11):
The batches themselves are designs to be passed by value; the various helpers we use to merge them are designs to be used in such a way that doesn't require any allocations.  Various optimisations have been put in place, such as pushing the building of the batch into the chunk iterator.  See changesets for more details.
```
$ go test -v -run BenchmarkChunkQueryable …
```
> Batch iterators

- docs/arguments.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/ring/replication_set.go
If one of the initial queries fails, or takes a long time, then the extra queries will be executed.
Will also reduce the number of context cancelled "errors" we get in traces/logs.
Implements the query side of: https://github.com/weaveworks/cortex/issues/100
> Delay more than the minimum ingester queries

- pkg/chunk/chunk_test.go
- pkg/chunk/fixtures.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/fnv.go
- pkg/ingester/flush.go
- pkg/ingester/index.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/mapper.go
- pkg/ingester/mapper_test.go
- pkg/ingester/series.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
Since we average hundreds of samples to a chunk, it saves a lot of work to leave label name/value sets as the slice they come in as, rather than converting to the map type that Prometheus uses.
They are converted on flush, to avoid changing the chunk store.
The cost of running a matcher is a bit higher, as we have to ~linear~ binary-search for the right label.
Also in `mapper.go` we are now converting to a string each time.
Both of these could be improved by sorting the labels alphabetically.
> Ingester: Defer converting from LabelPairs to Metric until flush

- pkg/chunk/aws/storage_client.go
`Log()` takes name/value pairs.
> Fix Log() calls for validation exceptions

- pkg/ring/replication_set.go
As it says in the comment on [`time.After`](https://golang.org/pkg/time/#After):
```
// The underlying Timer is not recovered by the garbage collector
// until the timer fires. If efficiency is a concern, use NewTimer
// instead and call Timer.Stop if the timer is no longer needed.
```
(not a major concern, considering the rate at which we do queries, but it's only two lines)
> Clean up Timer objects quicker on ingester calls

- pkg/chunk/aws/storage_client.go
- pkg/chunk/chunk_test.go
- pkg/chunk/fixtures.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/fnv.go
- pkg/ingester/flush.go
- pkg/ingester/index.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/label_pairs.go
- pkg/ingester/mapper.go
- pkg/ingester/mapper_test.go
- pkg/ingester/series.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
Another go at #997 , in which the code to delete blank labels was wrong.
I have added a unit test with ~a blank label~ _two_ blank labels, since I got it wrong for that case the second and third attempt.
Also added a `String()` function so `labelPairs` print out like Metrics.
> Ingester: defer converting labelPairs to Metric until flush

- pkg/ingester/index.go
It's more efficient to `append()` the fingerprints then sort them all at the end, than to copy the whole set in 
`merge()` every time round the inner loop.
Since the only other use of `merge()` was degenerate, remove the whole thing.
> Accumulate Fingerprints by append() in ingester index lookup

- code-of-conduct.md
Shamelessly copied the format from other CNCF projects
> Add a Code of Conduct referencing the CNCF Code of Conduct

- pkg/querier/chunk_store_queryable.go
- pkg/querier/distributor_queryable.go
- pkg/querier/ingester_streaming_queryable.go
- pkg/querier/unified_querier.go
TLDR; So turns out, if there was query like `up offset 4w` but `start-end = 15s`, we would end up getting all the chunks from `start-4w` to `end`. This PR makes sure only the relevant chunks are requested.
This is because when we create a `Querier` due to TSDB constraints (and maybe for other reasons), we need a single querier for a query. Which means if we `X / Y` where `X` has `offset 4w` and `Y` doesn't, the `q.minTime`, and `q.maxTime` will need to span the entire `4w`.
But this is mitigated by setting the appropriate parameters on `SelectParams` which this PR makes sure we use.
Relevant promQL code:
https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L465-L467
https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L472 …
> querier: Use select params for mint and maxt

- pkg/chunk/cache/background.go
- pkg/chunk/cache/background_test.go
- pkg/chunk/cache/cache.go
- pkg/chunk/cache/cache_test.go
- pkg/chunk/cache/diskcache.go
- pkg/chunk/cache/fifo_cache.go
- pkg/chunk/cache/fifo_cache_test.go
- pkg/chunk/cache/instrumented.go
- pkg/chunk/cache/memcached.go
- pkg/chunk/cache/memcached_test.go
- pkg/chunk/cache/tiered.go
- pkg/chunk/cache/tiered_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_storage_client.go
- pkg/chunk/storage/factory.go
Batch up the cache put interface, so traces are not completely dominated by cache puts.
Also, don't return errors from caches - just log (and add them to traces) in the leafs.
Fixes #1003
> Batch cache puts, simplify instrumentation, and don't return errors.

- Makefile
Also, remove the `cortex-` prefix from the image names - they'll now be eg `quay.io/cortexproject/ingester`.
Fixes #1027 
> Update Makefile to push to quay.io/cortexproject.

- .circleci/config.yml
- push-images
This way, it should fail correctly.  Also, remove email addresses from the docker login, that deprecated.
> Remove parallelism from push-images.

- pkg/util/validation/override.go
Before:
```
(pprof) top10
Showing nodes accounting for 4343572166, 59.54% of 7295471498 total
Dropped 557 nodes (cum <= 36477357)
Showing top 10 nodes out of 116
flat  flat%   sum%        cum   cum%
1061747260 14.55% 14.55% 1061747260 14.55%  github.com/weaveworks/cortex/pkg/util/validation.(*Overrides).getInt
709873883  9.73% 24.28%  709874396  9.73%  github.com/weaveworks/cortex/pkg/ingester/client.(*PreallocTimeseries).Unmarshal
496604314  6.81% 31.09% 3511179146 48.13%  github.com/weaveworks/cortex/pkg/distributor.(*Distributor).Push
356625027  4.89% 35.98%  356625027  4.89%  github.com/weaveworks/cortex/pkg/ring.(*Ring).replicationStrategy
356440563  4.89% 40.86%  356440563  4.89%  github.com/weaveworks/cortex/pkg/util/validation.(*Overrides).getDuration
355942406  4.88% 45.74% …
```
> Reduce allocations in validation.

- pkg/chunk/cache/background.go
- pkg/chunk/cache/background_test.go
- pkg/chunk/cache/cache.go
- pkg/chunk/cache/diskcache.go
- pkg/chunk/composite_store.go
- pkg/chunk/storage/factory.go
Under high query load the disk-cache has been observed locking for a substantial amount of time. This PR retools the Disk-cache to use a sharded locking mechanism. It also stores the key name for each bucket in memory. This allows missed reads to never access the mmap buffer, which reduces the number of unnecessary page faults. 
Summary of Changes:
- Sharded Locks
- Keys in-memory index
- Added additional metrics to determine disk-cache usage
> Update disk cache to shard lock, store keys in memory

- Gopkg.lock
- cmd/test-exporter/main.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/series_store.go
- pkg/querier/correctness/case.go
- pkg/querier/correctness/runner.go
- pkg/querier/correctness/simple.go
- pkg/util/spanlogger/spanlogger.go
Also:
- Move `SpanLogger` out of `chunk` package and reuse it.
- Update the logging in the test-exporter to use gokit.
~Vendor modified in place, don't merge until https://github.com/prometheus/client_golang/pull/469/files is in.~
> Instrument test exporter for OpenTracing.

- pkg/chunk/cassandra/storage_client.go
Simply add a -cassandra.timeout option to Cortex, to handle slow table creations
> Add a timeout option for Cassandra access

- cmd/querier/main.go
- pkg/chunk/util/util.go
Limit the number of queries we will send in parallel to the back-end, in case we have tens of thousands of series to fetch.
In my tests, the DynamoDB back-end cannot be used with schema v9 without a change like this.
I couldn't see a nice way to make the "100" limit configurable.  Suggestions welcome.
> Bounded parallelism for DoParallelQueries

- pkg/chunk/schema_config.go
- pkg/chunk/table_manager.go
This was added in July 2017 as a backwards-compatibility measure; removing now everybody is in the new world.
> Remove deprecated global tags setting

- Gopkg.lock
- vendor/github.com/weaveworks/common/middleware/http_tracing.go
- vendor/github.com/weaveworks/common/middleware/instrument.go
- vendor/github.com/weaveworks/common/server/server.go
~DON'T MERGE, depends on https://github.com/weaveworks/common/pull/126~
It separates the `/metrics` calls from queries now.
> Better trace op names for querier

- pkg/querier/frontend/results_cache.go
@jtlisi  I've been away for last few days so don't know the background on this one.  I believe we were seeing a frequent query for the last ~5mins of data that was _very_ large (ie 30MB) in cache, and taking a few seconds to decode the JSON.   Can you confirm?
This change skips the cache lookup for very recent queries.
> Avoid query results cache for very recent queries

- pkg/util/spanlogger/spanlogger.go
Otherwise we get thousands of log lines like this:
```
ts=2018-10-16T12:54:33.484363284Z caller=spanlogger.go:35 org_id=1 trace_id=768be160665ad7d6 method=SeriesStore.lookupSeriesByMetricNameMatcher metricName=kube_pod_container_status_restarts_total matcher=null
ts=2018-10-16T12:54:33.503513416Z caller=spanlogger.go:35 org_id=2 trace_id=234771d1d0ad5b5f method=SeriesStore.lookupSeriesByMetricNameMatchers metricName=kube_pod_container_status_restarts_total matchers=0
ts=2018-10-16T12:54:33.503567361Z caller=spanlogger.go:35 org_id=2 trace_id=234771d1d0ad5b5f method=SeriesStore.lookupSeriesByMetricNameMatcher metricName=kube_pod_container_status_restarts_total matcher=null
ts=2018-10-16T12:54:33.524284935Z caller=spanlogger.go:35 org_id=2 trace_id=4695890a7cda052c …
```
> Log opening of span at debug level

- pkg/chunk/storage/storage_client_test.go
To remove confusion over which loop counter is which, I renamed both of them.
Previously it was only checking one chunk per batch, and relying on the number of trials to be no larger than the batch size.
> Fix TestChunksBasic() to check all chunks returned

- pkg/chunk/cache/background.go
- pkg/chunk/cache/diskcache.go
- pkg/chunk/cache/memcached.go
We just had an outage where ingester crashed with:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xa0a5a2]
goroutine 566 [running]:
github.com/cortexproject/cortex/pkg/chunk/cache.(*backgroundCache).Store(0xc4200e2ba0, 0x11c05a0, 0xc51b5758c0, 0xc6ec69cbd0, 0x1, 0x1, 0xc44d14a880, 0x1, 0x1)
/go/src/github.com/cortexproject/cortex/pkg/chunk/cache/background.go:103 +0x252
github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).writeBackCache(0xc42083a6c0, 0x11c05a0, 0xc51b5758c0, 0xc7e6bd25b0, 0x1, 0x1, 0x0, 0x0)
/go/src/github.com/cortexproject/cortex/pkg/chunk/chunk_store_utils.go:155 +0x3a6
github.com/cortexproject/cortex/pkg/chunk.(*seriesStore).PutOne(0xc42074c000, 0x11c05a0, 0xc51b5758c0, …
```
> Make sure span exists when logging

- cmd/distributor/main.go
- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/series_store.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/override.go
Fixes #1057 
When combined with day-by-day query parallelism in the query frontend, this limit in the chunk store will limit vector windows (ie `rate(foo[20d])`) whilst not limit query lengths (ie still being able to do 1yr range queries).
> Optionally limit size of queries to the chunk store.

- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/ruler/main.go
- cmd/table-manager/main.go
- pkg/chunk/aws/dynamodb_table_client_test.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/metrics_autoscaling_test.go
- pkg/chunk/aws/storage_client.go
- pkg/chunk/aws/storage_client_s3.go
- pkg/chunk/cassandra/fixtures.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/fixtures.go
- pkg/chunk/gcp/fixtures.go
- pkg/chunk/gcp/storage_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
- pkg/chunk/schema_test.go
- pkg/chunk/storage/factory.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- pkg/chunk/testutils/testutils.go
Fixes #1014 
Fixes #320 
The schema config in yaml looks like this:
```
configs:
- from: 0
store: aws
schema: v1
index:
prefix: dev_chunks_2
- from: 1484006400000
store: aws
schema: v2
index:
prefix: dev_chunks_2
- from: 1486339200000
store: aws
schema: v4
index:
prefix: dev_chunks_weekly_
period: 168h
- from: 1502928000000
store: aws-dynamo
schema: v9
index:
prefix: dev_chunk_index_
period: 168h
chunks:
prefix: dev_chunk_data_weekly_
period: 168h
- from: 1508371200000
store: aws-dynamo
schema: v6
index:
prefix: dev_chunks_weekly_
period: 168h
chunks:
prefix: dev_chunk_data_weekly_
period: 168h
```
If you don't specify a `Period` then all data goes in one table and `prefix` is the entire name of that table.
At present `model.Time` does not unmarshal from a human-readable format. …
> Flexible schema config in yaml

- pkg/configs/api/api.go
Otherwise we use err from inner block with `ParseUint` instead of err from `a.db.GetConfigs`
Signed-off-by: Elena Morozova <lelenanam@gmail.com>
> Fix wrong err check

- pkg/ingester/flush.go
- pkg/ingester/ingester.go
When there are a lot of timeseries that go on for days, all of them will age out at around the same time, 12 hours after the ingester started.
This change smears out that timing, using the series fingerprint as a handy random number, so the effect isn't so pronounced.  At the cost of slightly more chunks saved.
> Apply jitter to chunk ages so the queue doesn't jump instantly

- cmd/lite/main.go
Sets the middleware for /api/prom/push in cortex-lite to the middleware enabled by the `unauthenticated` command flag. Fixes #1087
Signed-off-by: Ken Haines <khaines@ea.com>
> Improve `unauthenticated` mode in cortex-lite for devbox use 

- pkg/chunk/composite_store.go
- pkg/chunk/schema_config.go
yyyy-mm-dd instead of Unix epoch milliseconds
This was noted as something I should do in #1072
> Yaml schema config dates in human-readable form

- pkg/ingester/user_state.go
`cortex_ingester_memory_series_removed_total` might never be created if a user's series' never expire. Also, this reduces the lock contention around the metrics.
> Reduce lock contention on series creation and del

- pkg/ingester/flush.go
This reverses the change made in PR #764 to retain all chunks for the idle time - #1077 gives explicit retention of chunks after flushing, so we can flush quicker and simplify the logic.
> Flush full or aged chunks as soon as possible

- pkg/chunk/cache/memcached_client.go
I noticed we had a long tail of timeouts in ingester index cache writes, which are tiny, so guessed this setting is implicated.
Default in the library is 2, with a comment "This should be set to a number higher than your peak parallel requests.".  I went with 16 as the Cortex default.
> Allow the memcache connection pool to be controlled

- docs/arguments.md
- pkg/distributor/distributor.go
- pkg/util/validation/limits.go
Periodically clear out any cached ingestion rate limiters, such that updates to the overrides YAML take ~5mins to apply.
Fixes #1095
> Periodically clear out limiters in the distributor.

- pkg/chunk/aws/dynamodb_table_client.go
- pkg/chunk/aws/storage_client.go
- pkg/chunk/aws/storage_client_s3.go
- pkg/chunk/cache/stop_once.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk_store.go
- pkg/chunk/gcp/storage_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/storage/caching_storage_client.go
- pkg/chunk/storage/factory.go
- pkg/chunk/storage/factory_test.go
- pkg/chunk/storage_client.go
> When we share a cache amongst multiple stores, ensure it is only stopped once.

- cmd/ingester/main.go
- pkg/chunk/chunk_test.go
- pkg/chunk/encoding/bigchunk.go
- pkg/chunk/encoding/chunk.go
- pkg/chunk/encoding/chunk_test.go
- pkg/chunk/encoding/delta.go
- pkg/chunk/encoding/delta_test.go
- pkg/chunk/encoding/doubledelta.go
- pkg/chunk/encoding/varbit.go
Fixes #631 
~Note we had not previously edited the chunk code copy-pasted from Prometheus (v1).~
Only fully implemented for varbit chunks at present; I don't think we're intending to use other kinds.
Varbit chunks hold metadata in a header and a footer at the end of the chunk, however the footer is only used while appending more samples, so can be discarded when the chunk is "closed" and written to store.
A flag is added to make the new behaviour optional on writing, since shorter chunks cannot be read by older versions of Cortex so if you roll back after turning it on, you lose the ability to query any data written with short chunks.
The shorter encoding is also used when transferring chunks from one ingester to another on rolling updates.
>  Write only as many chunk bytes as needed

- pkg/chunk/encoding/varbit.go
The flag `-store.fullsize-chunks` should control writing only; on the reading side either size should be allowed.
Fixes the problem observed at https://github.com/cortexproject/cortex/pull/1044#issuecomment-443133535
> Allow smaller varbit chunks on read

- pkg/querier/chunks_handler.go
- pkg/querier/lazy_querier.go
- pkg/querier/querier.go
This allows for queries like `foo{bar="baz"} / blip{glib="glob"}` to process the the `foo` and `blip` queriers in parallel.
> Lazy Querier: return from Querier.Select early, processing the query in the background.

- pkg/alertmanager/multitenant.go
- pkg/chunk/aws/aws_autoscaling.go
- pkg/chunk/aws/dynamodb_table_client.go
- pkg/chunk/aws/storage_client.go
- pkg/chunk/aws/storage_client_s3.go
- pkg/chunk/cache/instrumented.go
- pkg/chunk/cache/memcached.go
- pkg/chunk/table_manager.go
- pkg/configs/db/timed.go
- pkg/distributor/distributor.go
- pkg/distributor/query.go
- pkg/ring/consul_client.go
- pkg/ring/consul_metrics.go
- pkg/ruler/scheduler.go
- pkg/util/http.go
New version should be slightly more efficient as it avoids creating an object on every call.
> Update instrumentation calls to remove deprecated interface

- pkg/ingester/client/compat.go
- pkg/querier/frontend/frontend.go
- pkg/querier/frontend/instrumentation.go
- pkg/querier/frontend/marshaling_test.go
- pkg/querier/frontend/query_range.go
- pkg/querier/frontend/query_range_test.go
- pkg/querier/frontend/results_cache.go
- pkg/querier/frontend/roundtrip.go
- pkg/querier/frontend/split_by_day.go
- pkg/querier/frontend/split_by_day_test.go
- pkg/querier/frontend/step_align.go
We were seeing the query frontend adding 500ms - 1s to some queries, for instance when the query results JSON is large (1-5MB).  The query itself is only taking ~200ms on the querier.
- Add various spans to the query frontend to see where the latency was.  Its mostly in the JSON marshaling / unmarshaling.
- Switch some more JSON code over to jsoniter, and write a zero-copy marshal / unmarshal function for Samples.
End result is reducing query latency of this particular case by about 50%.
> Query frontend optimisations.

- pkg/chunk/cache/cache.go
- pkg/chunk/cache/cache_test.go
- pkg/chunk/cache/memcached.go
- pkg/chunk/cache/memcached_test.go
- pkg/chunk/storage/factory.go
We were seeing this in the logs:
```
level=error ts=2018-12-31T15:26:44.021869855Z caller=memcached.go:216 msg="failed to put to memcached" name=store.index-cache-read. err="memcache: unexpected response line from \"set\": \"SERVER_ERROR object too large for cache\\r\\n\""
```
And it wasn't clear whether this was the chunk memcache or the index memcache.  So I added the "cache name" to the logs and metrics.
> Add a name parameter to the memcache client, so we can see where the errors come from.

- pkg/chunk/chunk.go
- pkg/ingester/flush.go
The value of `cortex_ingester_chunk_size_bytes` will be a few hundred bytes higher after this change.
I am open to creating a new metric for this, but don't really want to since the old one is not very useful compared to this one.
> Change chunkSize metric to include metadata overhead

- pkg/ingester/user_state.go
> Ensure ingester.QueryStream stops early when the RPC is cancelled.

- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- k8s/table-manager-dep.yaml
If I understand correctly, support for .start has been removed in
6e923f31d1678612faf39ca120f7178a6463a568, so examples should use
.from.
Signed-off-by: Mateusz Gozdek <mateusz.gozdek@dunnhumby.com>
> k8s: fix dynamodb.periodic-table.start parameters

- pkg/chunk/gcp/bigtable_index_client.go
- pkg/ingester/client/client.go
- pkg/querier/frontend/worker.go
- pkg/util/grpcclient/grpcclient.go
We're hitting this limit and `100 << 20` is the default in the bigtable SDK anyways.
> Make the max grpc receive message size configurable, in Bigtable client

- pkg/distributor/distributor.go
- pkg/ingester/user_state.go
- pkg/util/validation/validate.go
We alert on our customers hitting limits but they don't trigger when the sample is dropped due to series limits being hit.
> Track dropped metrics due to series limits too

- pkg/ingester/flush.go
Small (v1) chunks are all around 1100-1500 bytes; bigchunks (v2) start around 400 bytes and go up to around 8K. Make the buckets provide more resolution around these sizes.
(also the comment was incorrect previously)
> Make chunk size histogram buckets more useful

- pkg/ingester/client/compat.go
- pkg/ingester/client/fnv.go
This was missed from #1007: the conversion to string was unnecessary but forced an allocation.
Before:
BenchmarkIngesterPush-2   10	 113901108 ns/op	 7113553 B/op	   79116 allocs/op
After:
BenchmarkIngesterPush-2   20	  95770295 ns/op	 2313013 B/op	   19108 allocs/op
> Reduce allocations during fingerprint hash

- pkg/ingester/index/index.go
- pkg/ingester/user_state.go
Slightly flying a kite to get reactions...
I took a heap profile right after transfer, and about 20% of the allocations were in these lines.
The same pattern doesn't show up in current benchmarks.
The event log on new series was never hugely useful, and we have a metric now for the broad-brush picture.
> Reduce transfer allocations

- docs/arguments.md
Triggered by me realising I didn't know whether I wanted `-querier.batch-iterators` or `-querier.iterators`
> Document some more Querier command-line arguments

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/s3_storage_client.go
- pkg/chunk/cache/cache_test.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/chunk_test.go
- pkg/chunk/gcp/bigtable_object_client.go
- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/local/fs_object_client.go
- pkg/chunk/series_store.go
- pkg/chunk/testutils/testutils.go
- pkg/ingester/flush.go
- pkg/querier/chunks_handler.go
Remove all the scary comments and make it more obvious where encoding happens
This should make the code in #1164 work again (has since been reverted)
> Make chunk encoding an explicit operation

- cmd/test-exporter/main.go
- pkg/querier/correctness/runner.go
Call `t.UnixNano()` instead of `t.Unix()`.
`t.Unix()` truncates to seconds, so if the scraping process and the checking process have slightly different time they may expect a value a whole second off. This truncation also defeats `timeEpsilonCorrect()`.
(full disclosure: [I broke it](http://github.com/weaveworks-experiments/prometheus-benchmarks/commit/e4cc465919e819bc5f926bc50eb86d24f1723679))
Also print the timestamp corresponding to the value, for ease of debugging next time.
> Stop quantizing test sinewave to seconds

- pkg/chunk/aws/dynamodb_storage_client.go
The request `Send` function can return an error with `nil` Retryable. Test the value of the field using the same helper function used internally by the client library.
Fixes #1211.
> Protect against nil when dereferencing request Retryable field

- k8s/query-frontend-svc.yaml
The [code](https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/worker.go#L110) connects once per address returned from DNS, so we need a headless service.
The example config only has 1 replica so it works either way, but it should illustrate what to do in larger deployments.
> Make query-frontend service headless in example config

- cmd/ingester/main.go
- docs/arguments.md
- pkg/chunk/encoding/bigchunk.go
- pkg/chunk/encoding/factory.go
- pkg/chunk/encoding/varbit.go
- pkg/ingester/ingester.go
Only check the size when adding a new sub-chunk, to limit the cost of checking.
Fixes #1201 
Also consolidate existing chunk-encoding flags `-store.fullsize-chunks` and `-ingester.chunk-encoding` in one place.
> Add a cap on bigChunk size

- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/querier/unified_querier.go
- pkg/ruler/ruler_test.go
Closes https://github.com/cortexproject/cortex/issues/984
A rather small PR.
There can be better way to pass `IngesterMaxChunkAge` to the querier, but this is what I have come up with for now.
TODO
> Historical queries shouldn't hit the ingesters

- pkg/querier/querier_test.go
Tests started breaking when #1190 was merged.
> Add mock LabelNames() method to fix broken test

- Gopkg.lock
- pkg/chunk/gcp/bigtable_index_client.go
- pkg/chunk/gcp/bigtable_object_client.go
- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/gcp/instrumentation.go
- pkg/chunk/gcp/table_client.go
- pkg/ingester/client/client.go
- pkg/querier/frontend/worker.go
- pkg/util/backoff.go
- pkg/util/grpcclient/backoff_retry.go
- pkg/util/grpcclient/grpcclient.go
- pkg/util/grpcclient/ratelimit.go
The Bigtable table client does O(n) `TableInfo` calls for every `ListTables`, to check the column family exists.  Run it for long enough and Google starts rate limiting you when you have 100s of tables.
> Add options for client-side rate limiting and backoff on all gRPC clients.

- pkg/ring/lifecycler_test.go
- pkg/ring/model.go
I started looking at this code because I saw ingesters reporting their tokens were half-owned by the new ingester and half by the old, at the end of handover.
If the ingester we are claiming from is normalising, we need to blank out its tokens.
Simplify the rest of the claim logic since we hold a denormalised ring all the time - `loop()` calls `migrateRing()` to make it, and the `get()` functions depend on it.
Stop checking for an empty denormalised ring after migration in unit test.
> Improve ClaimTokens() code for normalised case

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/dynamodb_storage_client_test.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/cassandra/fixtures.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/gcp/bigtable_object_client.go
- pkg/chunk/gcp/fixtures.go
- pkg/chunk/schema_config.go
- pkg/chunk/storage/object_client_test.go
- pkg/chunk/testutils/testutils.go
The current cassandra fixture is causing cassandra storage tests to fail. The schema is being set to current time but the chunks used in the test have a start timestamp of current time minus an hour. This commit updates the cassandra fixture to use a schema with an acceptable timestamp.
> fix cassandra storage test fixture, set a correct From parameter

- pkg/ruler/ruler.go
Noticed this little surprise when troubleshooting some rule evaluation failures. This really large and complex change permits the undying prometheus rule processing code to log information out via the logger instance used by the ruler.
> Connecting the logger instance used in Ruler to the underlying prom code

- pkg/chunk/util/parallel_chunk_fetch.go
Signed-off-by: Patrick McIlroy <patrick@platform9.com>
This change flips the logic in GetParallelChunks() to make `maxParallel` a hard maximum number of concurrent goroutines for chunk fetching rather than a minimum, which the surrounding comments indicate is its intention. Because there was no limit on the number of goroutines spawned for chunk fetching (rather, a minimum of 1000), we were seeing querier memory usage consistently balloon beyond what we allocate it (we run cortex in a kubernetes environment), resulting in them frequently getting OOMKilled. Applying this patch kept the memory footprint of fetching data for our longer 3 day graphs from 13GB to about 2GB.
> fix logic in determining maximum concurrent chunk fetches

- .circleci/config.yml
It may be difficult to recreate those files exactly at a later date, so save what was used in the build.
> Save generated files in CI

- pkg/querier/frontend/results_cache.go
- pkg/querier/frontend/split_by_day.go
There is a limit of 100 outstanding queries at once per customer.  Due to day splitting, this makes queries longer than 100 days fail.
This PR limits the number of 'sub queries' per query that can be executed in parallel to 14.
Fixes #1148
> Limit parallelism in a single query to 14 sub queries.

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/multitenant.go
- pkg/configs/api/api.go
- pkg/configs/api/api_test.go
- pkg/configs/configs.go
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
> adding alert templates support for AlertManager

- pkg/ingester/client/compat.go
- pkg/ingester/flush.go
- pkg/ingester/index/index.go
- pkg/ingester/ingester.go
- pkg/ingester/label_pairs.go
- pkg/ingester/mapper.go
- pkg/ingester/series.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
This should reduce the memory size of ingesters a bit: slices are 24 bytes plus contents while strings are 16 bytes.
It might not seem like much but there are typically 40 of them per series, so 300MB saved per million series.
This change does put more work onto the query side, where we will allocate byte slices in the process of serialising the answers.  Also when transferring chunks from a leaving to a joining ingester.
> Store series label-value sets as strings rather than slices

- k8s/ingester-dep.yaml
By setting `-ingester.claim-on-rollout=true`.  I don't know why this flag was ever specified as `false` in the file, as it defaults that way.
Note that the bit in this file about stopping one ingester before starting another doesn't contradict this - Kubernetes will send SIGTERM to the old one before starting the new one, but it doesn't wait for it to stop. SIGTERM triggers the old ingester to look for a new one to hand over to.
> Allow ingesters to hand over chunks in example config

- k8s/nginx-config.yaml
Expose `/ring` and `/all_user_stats` in the nginx config, so they can be called from outside the cluster.
Also drop a comment that doesn't apply - seems to be left over from somewhere else.
> Add admin pages to example proxy config

- pkg/ingester/transfer.go
- pkg/ring/lifecycler.go
If an ingester has no chunks to transfer, do nothing explicitly.
(actually this is a check for a simpler condition - no user states)
Previously this would trigger a "no ingester id" error from the receiving end, so it's better to check for no series first.
And log the number of series received, which may be of interest.
> Small improvements to logging and error reporting of ingester transfers

- pkg/ingester/ingester.go
- pkg/ring/lifecycler.go
- pkg/ring/model.go
Fixes #1112 
Also state the reason why an ingester is not reporting ready - the reason will be visible if you curl the `/ready` endpoint. This is to remove some head-scratching when debugging.
> Check ingester has tokens before reporting ready

- cmd/alertmanager/main.go
- cmd/configs/main.go
- cmd/distributor/main.go
- cmd/ingester/main.go
- cmd/lite/main.go
- cmd/querier/main.go
- cmd/query-frontend/main.go
- cmd/ruler/main.go
- cmd/table-manager/main.go
- cmd/test-exporter/main.go
- pkg/util/log.go
Errors created with `github.com/pkg/errors` may have extra info such as a stack trace, but we need to ask for it specially.
Localise this code in one place in the `utils` package.
Sweet sweet -145 lines of code.
> Report the stack-trace from errors at top level

- pkg/chunk/encoding/delta.go
- pkg/chunk/encoding/delta_test.go
- pkg/chunk/encoding/doubledelta.go
- pkg/chunk/encoding/varbit.go
- pkg/querier/frontend/results_cache.go
"unmarshaling" to "unmarshalling".
"TestUnmarshalingCorruptedDeltaReturnsAnError" to "TestUnmarshallingCorruptedDeltaReturnsAnError".
> Fix fmt.Errorf() error message

- pkg/ring/model.go
Having both old and new tokens in the ring gives a confusing picture to distributors.
Fixes #1251
Small extra comment to head off future me from getting confused the same way I did in #1203
> After ingester hand-over in normalised mode, erase old ring tokens

- pkg/ingester/ingester.go
- pkg/ingester/user_state.go
`stream.Send` here https://github.com/cortexproject/cortex/blob/05b35bbf0d9e545c58de0acce47b94983d567fc1/pkg/ingester/ingester.go#L411-L413 is time consuming, in-turn blocking the lock in `forSeriesMatching`. 
This PR breaks the callbacks into 2 callbacks, where second callback is called in intervals outside the critical sections of the lock. 
/cc @tomwilkie
> Don't block lock in forSeriesMatching callback

- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
We have some very-high-cardinality series; 300k+ series per metric.  This results in bigtable rows that are over 100MB in size.  This change splits all rows into 16 rows, distributing entries based on the series ID.  Each read becomes 16 reads, done in parallel.
> v10 schema builds on v9 but shards index rows to break up very big rows.

- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
- pkg/ring/lifecycler.go
- pkg/ring/lifecycler_test.go
> When searching for an ingester to send chunks to, ensure we can actually connect to it.

- pkg/ingester/label_pairs.go
- pkg/ingester/label_pairs_test.go
Many `remote_write` clients (including Prometheus) will send samples with labels already sorted, and we can do the comparison much faster in that case. 
If they are not in order we do one extra name comparison.
Added a test.
Benchmarks (Go 1.12; best of 5 runs):
Before:
```
BenchmarkIngesterPush-2   	      20	  87524048 ns/op	 3086538 B/op	   13751 allocs/op
```
After:
```
BenchmarkIngesterPush-2   	      20	  56911377 ns/op	 3041616 B/op	   13759 allocs/op
```
> Speed up labelPairs.equal() when sorted

- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
When `Chunk.From` and `Config.From` are same, then the current code fails with:
```
msg="failed to flush user" err="no chunk table found for time 1551830400"
```
> Fix table lookup when chunk time aligns with table

- pkg/ingester/user_state.go
- pkg/ingester/user_state_test.go
Previously would only call send at the end of the function, causing the batches to be massive.
> Fix modulo arithmetic to prevent ingesters OOMing.

- pkg/chunk/encoding/bigchunk.go
As noted at #1220, after a transfer of chunks from one ingester to another, a new `smallChunk` is created immediately for any new samples that arrive. Allowing room for this avoids a copy and doubling in size of the slice of `smallChunk`s.
We go through the same code path on queries, so they will get slightly larger in memory - 24 bytes per chunk.
This change wouldn't be so useful if #1221 could be made to work.
> Allow extra space to add new bigchunk data after Unmarshal

- pkg/ingester/index/index.go
- pkg/ingester/label_pairs.go
- pkg/ingester/mapper_test.go
- pkg/ingester/series.go
- pkg/ingester/user_state.go
Fixes #1257 (mostly)
Currently, we have a separate copy of each label names and value string (e.g. `instance`, `kubernetes_namespace`, `get`) for each timeseries.  This consumes about 25% of all ingester memory in profiles I've looked at.
The inverted index is keyed by those strings, so we have a ready-made place to reduce down to one copy (per index shard per user). 
Unfortunately Go doesn't let us access the key of a map on lookup, so we have to add another reference to the string in the map value.  This makes data access a bit more ugly, and also costs another 16 bytes per index entry, but unless you have a shedload of unique short label values I think we'll come out ahead.
Benchmarks (Go 1.12; best of 5 runs):
Before:
```
BenchmarkIngesterPush-2   	      20	  87524048 ns/op	 3086538 …
```
> Intern label strings

- Makefile
- README.md
- k8s/retrieval-config.yaml
- k8s/retrieval-dep.yaml
- k8s/retrieval-svc.yaml
This change modernizes the version of Prometheus used in the manifests and updates the configuration to match. It also adds RBAC to run it on modern k8s, and moves Prometheus back to its standard port.
Finally, update the Makefile with a rule to make it easier to prime the minikube Docker with images built locally and reflect the changes in README.md.
Signed-off-by: Christian Funkhouser <cfunkhouser@heroku.com>
> Make it nicer to test locally with minikube in 2019

- pkg/ingester/index/index.go
- pkg/ingester/index/index_test.go
- pkg/ingester/ingester.go
> Simplify index by using 'string' instead of LabelValue/LabelName types

- pkg/querier/frontend/split_by_day.go
- pkg/querier/frontend/split_by_day_test.go
Fixes #1287
Find the time which is before the beginning of the next day, and a
multiple of `step` away from the start time.
> Improve nextDayBoundary calculation

- README.md
Explains that Minikube might not be using 192.168.99.100 and how to find the correct ip address.
> Use the correct ip address for minikube

- pkg/util/validation/limits.go
- pkg/util/validation/override.go
Not to command line defaults.  Eg if I specify `-validation.reject-old-samples=true` on the CLI, I want this to apply to all users unless explicitly disabled.   
> Default per-user limits to those specified on the command line.

- Makefile
- pkg/chunk/chunk_store.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_fixtures.go
- pkg/chunk/storage/caching_index_client.go
- pkg/chunk/storage/caching_index_client.proto
- pkg/chunk/storage/caching_index_client_test.go
- pkg/chunk/storage/factory.go
- pkg/chunk/storage/index_client_test.go
- pkg/util/flagext/deprecated.go
- pkg/util/validation/limits.go
- pkg/util/validation/override.go
We currently have a way of limiting load on the backends by caching the size of rows and preventing re-reading of very large rows. This is called the cardinality cache, and is currently in-process. As you add more queriers, it becomes less useful.
This PR adds support for "external" cardinality caching using the index read cache.  We also make query cardinality limit configurable per user. 
> Improve index cardinality limiting.

- pkg/chunk/gcp/bigtable_object_client.go
"recievedChunks" to "receivedChunks".
> Fix variable spelling error

- pkg/querier/querier.go
When you have a subquery of the form `[1h:]`, the second parameter is substituted to be the default evaluation interval by Prometheus. We don't set that in Cortex.
This is a little contentious, because if users change the default in their prometheus, their graphs in local vs cloud would be different.
Fixes #1265
> Set the default interval for promql to eval subqueries.

- pkg/chunk/storage/caching_index_client.go
With us caching entries for 15mins only and doing client side
validation after introducing permanent caching of older entries, this
debug is expected to print for millions of keys. It's not a very useful
line.
> Remove a very spammy debug line

- pkg/ingester/client/fnv.go
#1306 moved the hash implementation, but at the same time flipped it from FNV-1 to FNV-1a.
Put it back the way it was before, and add some comments noting the difference.
Note: without this, the effect is to re-shard all series to a different ingester, causing a spike in active series and (in shard-by-metric-name mode) breaking queries.
> Put Distributor hash algorithm back the way it was before 922a3b989a

- pkg/chunk/chunk_store_test.go
By running the different test cases as the inner loop we can re-use the same store multiple times, saving a lot of CPU.
Test run on CircleCI took 13.745s compared to 50-60s before.
Review with "Hide whitespace changes" to make it easier to see what happened.
Fixes #1289
> Flip the ordering of schema, store and query so tests run faster

- pkg/chunk/chunk_store_test.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_fixtures.go
- pkg/chunk/storage/caching_index_client.go
- pkg/chunk/storage/index_client_test.go
> Include metric name, label name, number of entries and limit in cardinality errors.

- pkg/chunk/table_manager.go
> Updated table deletes to ignore empty prefixes

- pkg/querier/frontend/query_range.go
- pkg/querier/frontend/roundtrip.go
This is to help with debugging: the top-level request that comes in and what is sent to queriers are logged to the current span, so you can see the effects of splitting, caching, etc.
> In query-frontend, log details of each request to OpenTracing

- Gopkg.lock
- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/util/spanlogger/spanlogger.go
Use `spanLogger` to unify logging and tracing, then pass it errors so they can be viewed in the trace.
Also stop sending `ValidationException` to event-logging, since the info is in tracing now.
> Improve tracing info on DynamoDB query errors

- pkg/chunk/chunk_store.go
The comment was wrong before, see: https://github.com/cortexproject/cortex/pull/1320/
> Make sure the deprecation points to right flag

- pkg/chunk/gcp/bigtable_index_client.go
- pkg/chunk/storage/factory.go
- pkg/chunk/storage/factory_test.go
- pkg/ingester/client/client.go
- pkg/ingester/ingester.go
We have some deprecated flags in our code base for long and I think it's time we cleaned up some of them :)
Deleted the useless flags (they do nothing even if set):
```
bigtable.max-recv-msg-size
ingester.client.max-recv-message-size
ingester.client.compress-to-ingester
distributor.compress-to-ingester
ingester.search-pending-for
ingester.reject-old-samples
ingester.reject-old-samples.max-age
ingester.validation.max-length-label-name
ingester.validation.max-length-label-value
ingester.max-label-names-per-series
```
Other flags (use `-store.index-cache-read.*`):
```
store.index-cache-size
index.memcached.*
```
```
> Nuke some old deprecated flags

- pkg/chunk/table_manager.go
- pkg/chunk/tags.go
Includes drive-by refactoring since it seemed odd to have schema_config.go depend on table_manager.go, and `tags.go` works ok as a self-contained file.
> Support setting table tags in yaml

- pkg/chunk/aws/dynamodb_storage_client.go
Because the backoff is reset on any successful query, almost every data point is 0 and the histogram is not useful.
> Remove cortex_dynamo_query_retry_count histogram

- docs/configs-api.md
Signed-off-by: Graham Rounds <graham@platform9.com>
---
Wrote this when exploring ruler/configs functionality and figured it would be valuable the official repo. Please correct anything incorrect and/or misleading I may have overlooked.
> add configs api docs

- pkg/util/validation/override.go
This metric should not be registered by default. It is an important metric that signals an error and it is in a widely imported package. This code ensure this metric is not registered automatically. It allows for mutliple calls to NewOverrides instead of causing a panic to allow for tests to function correctly. However, it signals a warning because multiple override structs should not be instantiated since they act as a singleton.
> Ensure Limits Overrides metric is registered explicitly once

- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
This is required to advance https://github.com/grafana/loki/issues/453 in Loki.
I also need to add `LabelNames(metricName, start, end)` but since this is my first PR I wanted to have a quick feedback on this first.
> Adds the ability the fetch label values from the store

- Makefile
Add a new phony target `generated` so we can save time by not starting and stopping a bunch of containers to run make N times.
Do the same for compilation of `exes` under the default `all` target.
> Run all proto generation in a single container

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/querier/ingester_streaming_queryable.go
- pkg/querier/ingester_streaming_queryable_test.go
Could fix https://github.com/cortexproject/cortex/issues/1354
> Make sure only series with chunks are sent

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/series_store.go
- pkg/chunk/storage_client.go
A call to `PutChunks()` is always followed by a call to `BatchWrite()`; we can save CPU time and network roundtrips by putting both into the same batch sent to DynamoDB.
This brought CPU usage down around 20% when I tried it in a batch process.
> Send chunks writes to DynamoDB in the same request as index entries

- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/series_store.go
@bboreham This is the interface change I was thinking of making to make it possible to lazy load chunks. While this was made for Loki, we can use the lazy loading in cortex and also for APIs like `GetLabelNames` (For supporting `GET /api/v1/labels`).
For `GetLabelNames` we will need to load only one chunk for each series to get the `labelNames`, and it's only possible if return a reference the `Fetcher` and the Chunks it loads. Further, this can used to lazy load chunks during query time.
If this makes sense, I'll implement it for `chunk_store.go` too.
> Add ability to lazy load chunks

- pkg/chunk/storage/factory.go
This means we don't crash when users specify `store: bigtable-hashed`.
> Make sure ObjectClient also support bigtable-hashed

- CONTRIBUTING.md
- README.md
- docs/architecture.md
- Explain a bit more what Cortex is useful for.
- Move developer details to contributor guide.
- Link to new docs.
- Consolidate all the further reading into the readme, add a bunch more.
> Update README with more description and links.

- pkg/cortex/cortex.go
- pkg/cortex/modules.go
- pkg/ingester/ingester.go
- pkg/ingester/lifecycle_test.go
- pkg/ring/consul_client.go
- pkg/ring/lifecycler.go
- pkg/ring/lifecycler_test.go
- pkg/ring/replication_strategy_test.go
- pkg/ring/ring.go
- pkg/ring/ring_test.go
- pkg/ring/testutils/testutils.go
- pkg/ruler/lifecycle.go
- pkg/ruler/lifecycle_test.go
- pkg/ruler/notifier.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
- pkg/ruler/scheduler.go
- pkg/ruler/scheduling_queue.go
- pkg/ruler/worker.go
This PR provides a flag that allows the ruler to shard ownership of which rule groups to evaluate by re-using the ring code. When enabled each ruler will act as a Lifecycler and interact with consul to create a ring.
> Horizontally Scalable Ruler

- pkg/chunk/aws/dynamodb_table_client_test.go
- pkg/chunk/aws/metrics_autoscaling_test.go
- pkg/chunk/bucket_client.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/local/boltdb_index_client.go
- pkg/chunk/local/boltdb_reload_test.go
- pkg/chunk/local/boltdb_table_client.go
- pkg/chunk/local/fixtures.go
- pkg/chunk/local/fs_object_client.go
- pkg/chunk/local/fs_object_client_test.go
- pkg/chunk/storage/factory.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- pkg/chunk/testutils/testutils.go
- pkg/cortex/modules.go
Currently, retention does not delete expired data from boltdb and filesystem.
Added retention support for boltdb by implementing methods in table client.
Table manager enforces retention periodically in a goroutine by checking mtime of all the files in the configured directory.
For object stores(GCS and S3), there is another issue open [here](https://github.com/cortexproject/cortex/issues/1381) which is under discussion.
> Retention changes for boltdb and filesystem

- pkg/chunk/cache/cache_test.go
- pkg/chunk/chunk.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/chunk_test.go
- pkg/chunk/fixtures.go
- pkg/chunk/json_helpers.go
- pkg/chunk/schema.go
- pkg/chunk/schema_caching.go
- pkg/chunk/schema_caching_test.go
- pkg/chunk/schema_test.go
- pkg/chunk/schema_util.go
- pkg/chunk/series_store.go
- pkg/chunk/testutils/testutils.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/fnv.go
- pkg/ingester/flush.go
- pkg/ingester/ingester_test.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/chunk_store_queryable.go
- pkg/querier/chunk_store_queryable_test.go
- pkg/querier/ingester_streaming_queryable.go
- pkg/querier/iterators/chunk_merge_iterator_test.go
- pkg/querier/remote_read.go
- pkg/querier/series_set.go
- pkg/util/chunkcompat/compat.go
- pkg/util/labels.go
This continues what was started in #1007, so now we never create a `map` for labels in the ingester.
I started on this when I noticed that index caching was taking a lot of time in `Metric.String()`.  This PR reduces that a bit, but there are further improvements that can be made to `Labels.String()`.
While fixing up the tests I noticed we go through all kinds of indirections, from chunks to matrix to series set and back again, and I started to remove some of those.  That's a tough job though, so I stopped after a few.
Benchmarks (best of 3):
Before:
```
BenchmarkEncode      	  300000	      4137 ns/op	    2978 B/op	      10 allocs/op
BenchmarkDecode1     	   50000	     29984 ns/op	  152483 B/op	      57 allocs/op
BenchmarkDecode100   	    2000	    692953 ns/op	  619859 B/op	    5234 …
```
>  Change Chunk.Metric from a map to a slice, for performance

- cmd/cortex/single-process-config.yaml
Small change to fix a fatal error in the default/demo yaml config for cortex. 
Addresses #1403
> Updating default/example yaml file with expected ring config structure

- pkg/ring/lifecycler.go
Ringname is used in metrics and right now, we just don't set it.
/cc @cstyan
> Make sure we assign the ringname properly.

- pkg/configs/legacy_promql/engine_test.go
We don't use the legacy promql engine; we just use the parser.  This test is flaky, and instead of figuring out why, I suggest we just delete it.
Examples:
- https://circleci.com/gh/cortexproject/cortex/6459
- https://circleci.com/gh/cortexproject/cortex/6029
- https://circleci.com/gh/cortexproject/cortex/5861
> Remove flaky TestQueryTimeout test.

- pkg/chunk/table_manager.go
> Expose table manager config for yaml

- k8s/alertmanager-dep.yaml
- k8s/configs-dep.yaml
- k8s/distributor-dep.yaml
- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/query-frontend-dep.yaml
- k8s/ruler-dep.yaml
- k8s/table-manager-dep.yaml
This will not work until https://github.com/cortexproject/cortex/pull/1413 is merged due to breaking changes of flags.
> Use single image for demo manifests

- pkg/alertmanager/multitenant.go
- pkg/configs/api/api.go
- pkg/configs/client/client.go
- pkg/configs/client/config.go
- pkg/configs/db/db.go
- pkg/configs/db/memory/memory.go
- pkg/configs/db/postgres/postgres.go
- pkg/configs/db/timed.go
- pkg/configs/db/traced.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/ruler_test.go
- pkg/ruler/scheduler.go
This does not change the functionality of the DB in any way. It only passes the context as a parameter. I am working on an object store backend for rules files in GCS and want to pass a context variable. I also think it is useful to have the context in postgres if we want to add lower level instrumentation.
> Add context parameter to DB interface functions

- pkg/chunk/schema.go
- pkg/chunk/series_store.go
This simplifies the code and avoids some allocations.
I suspect it can be simplified further because it's just the SHA that needs encoding, but if we change the encoding that would trigger extra work on rollout as the existing cache wouldn't match.
> Encode write-dedupe keys as they are created

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/metrics_autoscaling.go
- pkg/chunk/aws/metrics_autoscaling_test.go
By using a rate-limiter we can slow down in proportion to the amount we are being throttled - when approaching its capacity limit DynamoDB may only reject one or two items out of a batch but previously we were not slowing down until the entire batch was rejected.
DynamoDB internal metrics refer to "Throttled events" being part of a batch and "Throttled requests" meaning the entire batch was rejected. `ThrottleLimit` in the code effectively becomes the rate at which "Throttled events" will be seen when under load, per process.
This change makes the ingester behave much more nicely when throttled, to the extent that we see hardly any `ProvisionedThroughputExceeded` errors, which means that the auto-scaling driven by those errors no longer works.  Add a metric for throttling and use that …
> Use a rate-limiter to back off on DynamoDB throttling

- pkg/chunk/series_store.go
Simpler, more efficient, less surprising.
> Pass userID explicitly to lookup functions

- pkg/ruler/ruler.go
- pkg/ruler/worker.go
This fixes a bug in the ruler which caused it to panic when shutting down and not exit the ring. When I rebased the HA ruler PR onto the single binary PR I added back a channel that wasn't meant to be added.
This PR refactors the ruler shutdown to use a WaitGroup to ensure all of the workers can complete before returning. Instead of having a shutdown process for each worker, the workers will be signaled to shutdown by the scheduler.
> Fix Rulers Lifecycle

- pkg/chunk/schema.go
- pkg/chunk/schema_util.go
- pkg/chunk/schema_util_test.go
#1377 caused an unforseen change in the formatting of label strings, which in turn means that the SHA is different so the series ID changes.  It's more efficient to continue with the same IDs across an
upgrade.
I noticed there was an unused function `metricSeriesID()` and a test for backwards-compatibility which would have caught this mistake, so have pressed them back into service.
> Make series IDs backwards-compatible again

- pkg/chunk/aws/dynamodb_storage_client.go
Slight bug in #1361: the `UnprocessedItems` field that comes back is a map from table to items, so we need to count all the items and wait that long, rather than just waiting one unit per table.
> Fix wait time on DynamoDB throttling

- pkg/ingester/flush.go
- pkg/ingester/ingester.go
Fixes #1412 
This makes the load on the DB less bursty, at the cost of some smaller chunks being flushed the first time round the cycle after a cold start.
I should really do some unit tests...
> Add an option to spread ingester flushes evenly over time

- pkg/chunk/series_store.go
- pkg/ingester/ingester.go
Previously we aren't having as many buckets as we wanted to have in the comments.
> Fix bucket bounds on query metrics

- pkg/cortex/modules.go
It moved accidentally to distributor in the single-binary change https://github.com/cortexproject/cortex/pull/1262
I don't think it would work without the "authenticator" wrapper, so have removed the incorrect version.
> Add user_stats handler back on querier

- pkg/ingester/ingester_test.go
- pkg/ingester/user_state.go
- pkg/ingester/user_state_test.go
Fixes #1457 
Triggering the bug requires a "filter", i.e. a condition that will match the empty string, so I extended the test and test data to allow that.  Also made the test check that the batches added up to the expected total.
Then in `forSeriesMatching()`, simply counting series _sent_ instead of _checked_ gives the correct result in all the cases I could think of.
> Fix querystream batching

- pkg/chunk/schema.go
- pkg/chunk/series_store.go
Fixes #1428 
Move the write dedupe cache lookup down to `schema` so the labels for each bucket can be omitted if they've already been done.  This avoids re-writing yesterday's labels when we write a chunk that spans the day boundary.
It's now calling the cache separately for each bucket, but I felt the loss of clarity wasn't worth optimising this.
>  Avoid duplicate label index writes by combining LabelEntryCacheKeys and LabelWriteEntries

- docs/tracing.md
I have noticed some questions around configuring Jaeger recently so decided to add a doc as I did it.
> Add documentation for how to configure Jaeger

- pkg/cortex/cortex.go
The weaveworks/common already has the middleware on by default.
See: https://github.com/weaveworks/common/blob/master/server/server.go#L162-L164
and https://github.com/weaveworks/common/pull/126
Else we are ending up URIs in the op names.
> Remove redundant op name middleware.

- pkg/querier/frontend/worker.go
While this is not super ideal, we will still catch 99% of the cases
through this.
Fixes: https://github.com/cortexproject/cortex/issues/1450
> Make sure we send a 400 for large responses.

- pkg/cortex/cortex.go
Fixes #1447 
We want the process to answer requests (including status and metrics) until it has finished shutting down.
Every target depends on Server, so it will get shut down as a dependency.
> Leave Server module running until end of shutdown

- docs/getting_started.md
Signed-off-by: paliwalpriyank <paliwal.priyank2001@gmail.com>
> getting started: correcting remove docker network command

- pkg/chunk/encoding/bigchunk.go
This is an alternative to #1355 
Fixes #1354 (although that is already marked as fixed)
> Return a NopIterator when bigchunk is empty

- pkg/ring/lifecycler_test.go
- pkg/ring/model.go
- pkg/ring/ring.go
> Fix ingester startup with a normalised ring

- pkg/chunk/series_store.go
In the case where two ingesters have chunks for the same series, with the same start and end times and same contents, this change will skip one of the writes, which saves effort, and money with DynamoDB.
How often does this happen?  It depends on the type of timeseries data Cortex is handling.  It is most likely for short chunks, e.g. cAdvisor metrics from containers that run just a few minutes.  It is least likely for long-running series as they will be flushed at a time relative to the start of the ingester process, so the end-time is unlikely to match.  (But I'm working on that via `-ingester.spread-flushes`).
I thought about adding a metric to count the chunks saved, but you can see this via the hit-rate of the cache inside ingesters.
> Avoid writing duplicate chunks by checking the cache first

- pkg/chunk/local/boltdb_index_client.go
As part of solution for https://github.com/grafana/loki/issues/685, the purpose is to avoid opening boltdb fall into dead loop.
> add options for boltdb_index_client to avoid dead loop

- pkg/querier/chunk_tar_test.go
- pkg/querier/querier_benchmark_test.go
`BenchmarkChunkQueryableFromTar` is same as `TestChunkTar` in `pkg/querier/chunk_tar_test.go`. This benchmark would come handy in investigating a query offline.
> Add BenchmarkChunkQueryableFromTar

- docs/arguments.md
- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/s3_storage_client.go
Feature for https://github.com/grafana/loki/issues/699, support custom endpoint which is using `Path Style URL` of S3.
> Support custom endpoint for S3

- k8s/dynamodb-dep.yaml
Necessary for #1486 to work as intended.
This is the version and arguments that I used while developing integration tests.
It gives a better error message than `deangiberson/aws-dynamodb-local` in #1484
> Use Amazon's own dynamodb-local image in example config

- pkg/ingester/lifecycle_test.go
- pkg/ingester/series.go
The `lastSampleValue` member may not be initialized, e.g. after a transfer from one ingester to another.  We already have a flag which is set when the value is valid, so use it.
Fixes #1438
>  Check that the last sample value is valid before complaining about it

- docs/arguments.md
- pkg/chunk/cache/cache_test.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/series_store.go
This an optional optimisation for #1475 - if we have a dedicated cache just for de-duplicating writes then we don't need to store the chunk data in it, just a placeholder for the key.
> Optionally write stub entries to the chunk cache from ingesters

- cmd/cortex/main.go
This is a terrible, terrible thing.  I apologise.
It allows the heap size to be made bigger, to make Go's GC run less often and use less CPU.  See https://github.com/golang/go/issues/23044
Particularly aimed at distributors.
> Add optional "Heap ballast" to alter GC behaviour.

- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/series_store.go
This adds LabelNamesForMetricName for the series store only, I wanted to first get your feedback if this seems correct.
- I'm getting all series ids for a given metric name
- lookupSingleChunkBySeries which takes the first index query and lookup index entries then take the first index entry and parse the chunk key.
- fetch a single chunk for each series
- merge all label names possible except metric name.
I would like a special attention to that lookupSingleChunkBySeries and its usage, not sure if this is the right way to approach the problem. (May be I should loop though queries and entries until I get a result ?)
I still need to implement this for the chunk store but I'm not sure what would be the most efficient way of doing this.
The PR is rebased on my other work to include the split …
> Add LabelNamesForMetricName for the series store

- docs/architecture.md
Before, it was saying the index could be in S3.
> Correct text about which stores are supported

- docs/arguments.md
- pkg/chunk/encoding/factory.go
I started to document this flag, but it was too embarrassing that it only accepts a number so I fixed that.
> Accept the symbolic name for a chunk encoding type

- pkg/chunk/storage/factory.go
Loki depends on Cortex. When loki is started without `-dynamodb.url` (or a properly configured config file) it panics in `NewTableClient()` (`aws` is the default mode). This PR fixes it.
Fixes https://github.com/grafana/loki/issues/714.
> Ensure -dynamodb.url is set when calling NewTableClient() in aws mode

- pkg/ring/consul_client.go
We're only run Consul now - don't need the HA as its ephemeral state, and more outages came from consul clusters outages than anything else.
-consul.consistent-reads=false massively reduces the load on the Consul server, but most of GET load is from watches.  So we should honor this flag there.
> Honor -consul.consistent-reads on watches too.

- pkg/ring/consul_client.go
If you specify RequireConsistent: false, then you actually saying use the default - which is consistent. You need to set AllowState: true.
> AllowStale and RequireConsistent are mutually exclusive.

- pkg/distributor/distributor.go
`sampleTracker` has moved inside `ring.DoBatch()`, so the comment doesn't make sense any more.
To replace it, I tried to summarise what goes on in the loop.
> Replace outdated comment in Distributor.Push()

- pkg/ingester/ingester.go
- pkg/ingester/user_state.go
Pre-create a vector of counters per user, so we don't lock across all users when the counts are increased.
This should help #1301
> Reduce contention on discarded samples counters

- pkg/ingester/ingester.go
- pkg/ingester/series.go
Make sure all cases where ingesters discard data are covered in counters.
I have a case where distributors are seeing data but it's not showing up in queries, so trying to cover all possibilities I can think of why it could be discarded.
> Count samples silently discarded for duplicate timestamp

- pkg/ring/kv/client.go
NB the flag name used to be -consul.prefix, and is now -ring.prefix.
> Restore previous default for Consul key prefix.

- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/gcp/instrumentation.go
To use GCP service accounts, the scope needs to be provided in the transport options.
Currently when trying to use this GCS client via Loki, by mounting the service account `credentials.json` file from a secret and using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, results in the following error response:
```
err="Post https://www.googleapis.com/upload/storage/v1/b/my-loki-bucket/o?alt=json&prettyPrint=false&projection=full&uploadType=multipart: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\n  \"error\": \"invalid_scope\",\n  \"error_description\": \"Empty or missing scope not allowed.\"\n}"
```
Signed-off-by: Graham Rhodes <1964861+grahamar@users.noreply.github.com>
> feat(gcs): Add Service Account Support

- ADOPTERS.md
Some inspiration from: https://github.com/rook/rook/blob/master/ADOPTERS.md and https://github.com/jaegertracing/jaeger/blob/master/ADOPTERS.md
We can also split it into service providers and end users, but I prefer it this way tbh. I've added Aspen Mesh (blog post), EA and MayaData (CNCF presentation) as they are already public but, pinging @nrjpoddar @khaines @kmova for permission.
I'll ping others I know are using it for permission too.
> Add an ADOPTERS.md

- pkg/querier/frontend/frontend.go
- pkg/querier/frontend/frontend_test.go
- pkg/querier/frontend/worker.go
Should mostly be a simplification of the frontend.Process method's concurrency.  And an extra goroutine in the client for this (worker.go).
And a unit test to show it works now.
> Ensure queries are cancelled correctly via the frontend.

- pkg/util/http.go
Change the sub-span into an event to reduce clutter.
The log lines show up as small black vertical lines in Jaeger - example of how it looks:
> Add more tracing detail when parsing incoming requests

- pkg/ruler/lifecycle.go
- pkg/ruler/lifecycle_test.go
- pkg/ruler/scheduler_test.go
This just removes some unused variables from the Ruler.
> remove unused variables from the ruler package

- pkg/distributor/ha_tracker.go
Only check the value in Consul when the cached elected entry is not found or is older than the UpdateTimeout.
cc @cstyan @tomwilkie
> Reduce extra calls to Consul in HA mode

- pkg/cortex/modules.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
Relates To: #1512
This PR embeds the metrics from the ingester into the ingester struct. This means they will only be initialized if an ingester struct is initialized.
I avoided embedding a prometheus Registerer into the config and passing it because we do not currently use non-default registerers anywhere in cortex. Down the line we may want to consider this approach.
> Embed Ingester metrics into struct

- pkg/ring/kv/etcd/etcd.go
I think the etcd `!result.Succeed` case (the revision/key comparison failing) is the same case as this in Consul: https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/consul/client.go#L158-L162 Though I'm not 100% sure, I haven't tracked all the way through the Consul API to say for certain what CAS is supposed to return if the modify indexes don't match.
In any case, this doesn't need to be an error log. The distributors in the cluster where we're testing HA tracking with etcd are spamming this log line.
cc @tomwilkie @gouthamve @csmarchbanks  
> Log as debug if etcd CAS comparison does not succeed.

- pkg/alertmanager/mesh.go
`Log()` requires that arguments are name-value pairs.
> Fix calls to Log() from Alertmanager mesh

- .circleci/config.yml
- RELEASE.md
- push-images
Lets just do it!
These instructions are based on the Prometheus instructions with a few small modifications according to https://github.com/cortexproject/cortex/issues/1402. I set the first release date to be on Tuesday in order for to collect some feedback.
Updated the circle ci deploy job to use the `CIRCLE_TAG` env var if it is present rather than generating the image name from the commit sha.
> Provide instructions and ci job for releases

- .circleci/config.yml
- Makefile
The deploy job for the tag failed because the images were built without the proper IMAGE_TAG (they were HEAD-<sha>), and the deploy job tried to upload them as v0.1.0-rc.0
See https://circleci.com/gh/cortexproject/cortex/8195
> Make build job will use IMAGE_TAG if present

- .circleci/config.yml
- Makefile
There are other steps in the build and deploy jobs that need IMAGE_TAG set to the CIRCLE_TAG. It will be easiest if the Makefile just knows to use CIRCLE_TAG if it is present.
> Set IMAGE_TAG to CIRCLE_TAG in Makefile

- docs/architecture.md
It's ok as it stands, and nobody is actively working on it.
> Remove 'work in progress' from architecture doc

- pkg/chunk/composite_store.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_test.go
It is handy to export the createSchema function so that I can make tools that can interact with cortex chunks and index entries with only a PeriodConfig yaml file required to configure it. Exporting this makes building tools for interacting with cortex storage backends much easier.
> Export createSchema function

- pkg/alertmanager/multitenant.go
- pkg/configs/configs.go
- pkg/ruler/ruler.go
- pkg/ruler/scheduler.go
- pkg/ruler/scheduler_test.go
Also shut down `Notifier` when user is deleted in ruler.
Fixes #692 
Improves #676
> Remove deleted users from AlertManager

- pkg/querier/batch/merge.go
- pkg/querier/batch/stream.go
- pkg/querier/batch/stream_test.go
In my quest of optimizing query performance, I found that `result.append` was taking a significant amount of time in `mergeStream` (2s+ of around 4s of `mergeStream`).
The query and data in action is described here https://github.com/prometheus/prometheus/pull/5707#issuecomment-505440230
In this PR I have inlined the appending logic with the merging logic. This saves anywhere from `1s-2.5s` for the above data.
> Optimize mergeStream

- pkg/chunk/series_store.go
So Jaeger traces get the right parent.
> Pass context to index write cache

- pkg/ingester/flush.go
- pkg/ingester/ingester.go
Allow a user to configure the minimum number of samples needed for a
chunk to be flushed to the store. This is to avoid your store being
overloaded by lots of tiny chunks that are unlikely to have useful
information.
> Drop chunks with less than min samples

- pkg/distributor/distributor.go
- pkg/ingester/client/timeseries.go
- pkg/ring/batch.go
- pkg/util/http.go
Motivated by:
```
(pprof) top
Showing nodes accounting for 12563.18GB, 75.10% of 16728.81GB total
Dropped 686 nodes (cum <= 83.64GB)
Showing top 10 nodes out of 107
flat  flat%   sum%        cum   cum%
3033.42GB 18.13% 18.13%  3033.42GB 18.13%  github.com/cortexproject/cortex/pkg/ingester/client.(*PreallocTimeseries).Unmarshal
2412.37GB 14.42% 32.55%  2412.37GB 14.42%  github.com/cortexproject/cortex/pkg/ingester/client.(*WriteRequest).Marshal
2264.33GB 13.54% 46.09%  2270.93GB 13.57%  github.com/cortexproject/cortex/vendor/google.golang.org/grpc/internal/transport.(*http2Client).Write
1579.87GB  9.44% 55.53%  1579.87GB  9.44%  github.com/cortexproject/cortex/vendor/github.com/golang/snappy.Decode
874.42GB  5.23% 60.76%   874.42GB  5.23%  bytes.makeSlice
814.28GB  4.87% 65.63%   814.28GB …
```
> Use pools to reduce allocs in distributor write path

- pkg/chunk/cache/instrumented.go
- pkg/chunk/chunk_store_utils.go
> Add a histogram for cached value sizes.

- CHANGELOG.md
- go.mod
- go.sum
- pkg/chunk/cache/memcached_client.go
- pkg/chunk/cache/memcached_client_selector.go
- pkg/chunk/cache/memcached_client_selector_test.go
- vendor/github.com/facette/natsort/LICENSE
- vendor/github.com/facette/natsort/README.md
- vendor/github.com/facette/natsort/natsort.go
- vendor/modules.txt
This PR adds support for consistent hashing of memcached servers by server DNS name. 
Support for this is behind a boolean configuration variable in the client config, available in the flags as `-memcached.consistent-hash` 
The use of jump hash enables consistent hashing when adding or removing a memcached server only requires 1/N keys being moved. A downside to jump hash in particular is that the order of DNS names used for the servers must be predictable to maximize efficiency. A good example of a predictable DNS name is `memcached-[pod index].cortex.svc.cluster.local`, which is what Kubernetes would create when running memcached as a StatefulSet on a headless service. 
/cc @tomwilkie
> Support consistent hashing in cache.NewMemcachedClient

- CHANGELOG.md
- pkg/cortex/modules.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_http.go
- pkg/distributor/ha_tracker_test.go
It wasn't clear to me what the right way to serve the page was, and whether for other pages (ex: the ring pages) if we serve the page from every distributor/ingester or not.
> Add admin page for HA tracker information.

- CHANGELOG.md
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
When the retention period is not a multiple of periodic table duration, we need to error out since Cortex doesn't yet support partial deletion of tables.
Added a check to validate retention against the latest config(assuming the last one is the latest) and relevant test.
> check for retention period to be a multiple of periodic table duration and relevant test

- docs/architecture.md
- docs/arguments.md
- docs/ingester-handover.md
Suggested at https://github.com/cortexproject/cortex/pull/1553#discussion_r310160832
> Document the ingester hand-over process

- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/series.go
- pkg/ingester/user_state_test.go
So that all ingesters will make the same decision, hence chunks flushed to the DB are more likely to overlap.  This is a replacement for #1414, keeping the option name but implementing it differently.
Also add a test and fix an incorrect comment on `memorySeries.add()`.
Trying this out in staging environment, I see that the 'reason' stats are less helpful because the chunks that hit their timeslot are reported as "multiple chunks in series".  We could add more metadata to report the different cases accurately.
> Move ingester.spread-flushes from flush time to sample add time

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/override.go
- pkg/util/validation/override_test.go
- pkg/util/validation/validate.go
- pkg/util/validation/validate_test.go
This would be useful to define limits specific to Loki while still being able to use the same code for managing limits and per tenant overwrites.
Changes include:
1. Limits are now stored as key-value pairs, where the key is a string and values are interfaces for being able to support dynamic limits
2. Limits need to be registered before being able to use them
3. Sample and Labels validation methods now accept any type which implements required methods to get required limits for validation
4. Added Setter methods to change default limit values at runtime for testing purpose
> Refactored limits to be able to define them dynamically when Cortex is vendored in another project

- cmd/cortex/main.go
- pkg/chunk/table_manager.go
If we have several table-managers that start at the same time, they will all start syncing at once causing limits to be hit. This adds some randomness so that the load is spread evenly.
> Spread the sync load over time

- docs/auth.md
- docs/running.md
This is something a lot of people ask about.
Probably it will take months to get into decent shape but the sooner we get started the better, so I jotted down some points.
> A start at a guide to running Cortex in production

- go.mod
- go.sum
- vendor/github.com/weaveworks/common/aws/config.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/modules.txt
go mod vendor
Adds support for respecting https for s3 urls
> go mod update github.com/weaveworks/common

- pkg/util/validation/override.go
- pkg/util/validation/override_test.go
OverridesManager was crashing while stopping because its quit channel was not initialized. Fixed it and updated some tests including calling Stop method of OverridesManager
> fix crashing OverridesManager and updated the tests

- pkg/ruler/notifier.go
> Use v1 endpoint for Ruler to talk to Alertmanager, for compatibility

- pkg/alertmanager/alertmanager.go
Fixes #1592
We need to wire up the notification log to gossip to share state with peers.
Also avoid creating two throwaway metrics registries, since one will do.
> Fix duplicate alertmanager notifications

- CHANGELOG.md
- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
- pkg/ring/lifecycler.go
- pkg/ring/lifecycler_test.go
As discussed in [Slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1565106143201700)
> **Chris Marchbanks**   Related to #1560, What do people think of defaulting the flag `-ingester.claim-on-rollout` to true, maybe even deprecating the flag. Does anyone run with that flag off?
> **Bryan Boreham**  I've just looked back to see that the flag came in with #325, where the whole rolling updates thing was added.
> So it was reasonable at the time to have a way to turn it off, but I think it's past its usefulness.
Leave the flag and yaml names for now to avoid crashing.
> Remove claim-on-rollout option

- .circleci/config.yml
- Makefile
- integration-tests/common.sh
- integration-tests/schema1.yaml
- integration-tests/start-components.sh
- integration-tests/stop-components.sh
- integration-tests/test-flush.sh
- integration-tests/test-handover.sh
A first cut.  Attempting to keep things lightweight, e.g. no Kubernetes.
The test client is at https://github.com/bboreham/avalanche/tree/remote-write
You may say "that's an ugly pile of shell script, Bryan", and I might well agree with you.
It lets me iterate quickly.
> Integration test running ingesters

- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/util/validation/limits.go
For the case where we have one tenant that we want to treat differently - we want it to store very short chunks, or we want it to drop a lot more small chunks.
> Make MinChunkLength settable per-user

- pkg/ring/http.go
This PR colors alternate table rows of the ingesters table on the ring status page.
Signed-off-by: Ankit Goel <ankit.goel@go-jek.com>
> Use different colors for table rows on ring status page

- pkg/util/backoff.go
- pkg/util/backoff_test.go
The current backoff algorithm doesn't honor `MinBackoff` and each sleep is basically a random between zero and a max range value starting from `MinBackoff` and doubling up to `MaxBackoff`.
Following up the discussion in https://github.com/cortexproject/cortex/issues/792, in this PR I'm proposing to switch to a different algorithm with both honors min and max, while keeping some jitter.
The proposed idea is to work with a ranged jitter. For each consecutive retry, the delay is picked as a random value between a range whose boundaries doubles each time.
I've run a simulation of 100 clients all starting the backoff at the same time `0` (should be the worst case scenario) with `10` max retries. The following chart shows the distribution over time (Y-axis, in milliseconds) of the retries, …
> Switch backoff implementation from a 'Full Jitter' to a 'Ranged Jitter'

- CHANGELOG.md
Making my life as a release shepherd easy.
> Update the changelog to reflect recent PRs

- pkg/chunk/chunk_store.go
- pkg/chunk/composite_store.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_index_client.go
- pkg/chunk/storage/factory.go
`NewStore` method in `pkg/storage` uses Overrides type defined in Cortex itself.
Added an interface to let consumers of that method pass any type which implements required methods returning Store specific limits.
This is done as part of way to let projects using Cortex, define their own limits
> added interfaces for store specific limits

- go.mod
- go.sum
Based on https://github.com/jenkins-x/jx/pull/3321
Thrift docs are at https://thrift.apache.org/lib/go
> Override since git.apache.org is down

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/series_store.go
- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/query_test.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
- pkg/querier/chunk_store_queryable.go
- pkg/querier/chunk_store_queryable_test.go
- pkg/querier/chunks_handler.go
- pkg/querier/ingester_streaming_queryable.go
- pkg/querier/lazy_querier.go
- pkg/querier/querier.go
- pkg/querier/unified_querier.go
Pull the extract of userID from context up as close as possible to where the request comes in, so we can error immediately if it's not there and avoid looking for userID at multiple points in the call stack.
Also avoid creating temporary contexts in chunk transfers.
This covers all of the write path, but some of the query path still fetches userID at a lower level.
>  Pass userID explicitly, not via context

- pkg/chunk/cache/memcached_client.go
- pkg/chunk/cache/memcached_test.go
bugfix: memcachedClient.updateLoop() does not exit infinite loop
when the client is stopped.
> bugfix: memcachedClient.updateLoop() does not exit infinite loop

- pkg/ruler/ruler.go
I found this useful when debugging #1592
> Add a tracing span for ruler calling Alertmanager

- pkg/util/validation/limits.go
I'm not sure this wording is entirely accurate, but it's better than what we had before.
> Fix comment on CardinalityLimit()

- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/ring/batch.go
- pkg/ring/replication_strategy.go
- pkg/ring/ring.go
- pkg/ring/ring_test.go
- pkg/ruler/ruler.go
`ring.DoBatch` contributes 20% of the memory allocation in my production distributors.
I started looking at this and realised the existing benchmark was not exercising the functionality - the `cas()` didn't update the ring so it was actually empty, and some test fixture code was also quite far up the profile.
Having fixed all that and made the benchmark call the higher-level function `DoBatch()`, the numbers before are:
```
BenchmarkBatch10x100-2     	   10000	    175156 ns/op	   56648 B/op	     334 allocs/op
BenchmarkBatch100x100-2    	    5000	    256146 ns/op	   87675 B/op	     720 allocs/op
BenchmarkBatch100x1000-2   	    1000	   1838020 ns/op	  578726 B/op	    3278 allocs/op
```
after:
```
BenchmarkBatch10x100-2     	   10000	    149385 ns/op	   12061 B/op	      29 allocs/op …
```
> Optimise ring.DoBatch()

- pkg/ring/batch.go
Fixes #1640 
`batchTracker.record()` is written so there will only be one send on each chan, but if `ctx.Done()` happens before either then `DoBatch()` returns so we need 1 slot in each chan to be able to send without blocking when nobody is receiving.
> Stop blocking batchTracker on chan when DoBatch() gets cancelled

- pkg/ingester/query_test.go
- pkg/ingester/series.go
It was erroring, and I couldn't see why until I made the error code more helpful.
This told me the benchmark was sending all samples with the same value and timestamp so it wasn't testing what it claimed.  And when I fixed that it ran for several minutes so I cut the size of the test data.
> Fix BenchmarkQueryStream

- Makefile
This should help speed up all the go module fetch. It is the default proxy from go1.13 onwards but would be good to have now this till we switch to go1.13.
> Use golang proxy for go modules

- pkg/distributor/distributor_test.go
- pkg/ingester/client/compat.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
- pkg/ruler/compat.go
Because `Distributor.Push()` returns them to the pool (after #1526).
In a typical deployment this doesn't actually break, since nothing in `Ruler` gets things out of the pool and the pool is emptied on GC, but it's clearly wrong and also inefficient.
The main change in this PR is to make `ToWriteRequest()` get from the pool - besides the one call in Ruler this is only used in tests, where it doesn't matter that the memory is never returned to the pool.
Along the way I re-coded `ToWriteRequest()` to not go via `Metric` - we were creating a map on every ruler sample just to read the data back out again.
Oh, and a drive-by spelling correction.
> Make Ruler Push() call get timeseries from the pool

- pkg/ring/util.go
- pkg/ring/util_test.go
GenerateTokens could generate duplicate tokens previously, which kind of defeats the purpose I guess. This patch fixes it.
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>
> Make sure generated tokens are unique

- pkg/querier/remote_read.go
Construct the QueryResponse directly from the values we have, thereby avoiding a lot of conversion and garbage.
> Stop going via Matrix in RemoteRead

- pkg/ingester/ingester.go
* Protect two data structures with one lock - since `stopped` is only used in one place, that is already taking a lock, re-use `userStatesMtx` and skip the effort to check the `stopLock` and `defer Unlock` it.
* Combine two `defer`s into one - each `defer` involves some memory allocation and housekeeping so we can save half the effort.
> Small optimisations to Ingester.append()

- go.mod
- go.sum
- vendor/modules.txt
The k8s.io/client-go v12 go.mod file has an error.
See https://github.com/golang/go/issues/33558
> Override reference that causes an error from Go proxy

- integration-tests/common.sh
- integration-tests/start-components.sh
- integration-tests/test-flush.sh
- integration-tests/test-handover.sh
This PR makes the image prefix configurable for the integration test scripts. The default will remain `quay.io/cortexproject/`. However, if the `IMAGE_PREFIX` is set in the env, that will be used instead. This was causing issues for PRs from the grafana/cortex repo which uses a different image prefix in circleci.
> fix integration tests for alternative image prefixes

- MAINTAINERS
I have discussed offline with @jml - he is no longer at Weaveworks and not planning further work on Cortex.
> Jonathan Lange is no longer a maintainer

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/client_test.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/timeseries.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
After #1526 the unmarshall code is trying to get memory out of the pool, but in ingesters it is never returned so the `pool.Get()` call just slows things down.
After making this change it still wasn't that great, because the pool was boxing `TimeSeries` objects.  So change those to `*TimeSeries`.
before:
```
BenchmarkIngesterPush-2   	     100	  23525939 ns/op	 3881766 B/op	   42317 allocs/op
```
after:
```
BenchmarkIngesterPush-2   	     100	  22937648 ns/op	 3273382 B/op	   32482 allocs/op
```
(note out of the 3-4MB per iteration, 1MB is overhead from the `FingerprintLocker`)
>  Return request data to the pool in Ingester.Push()

- k8s/nginx-config.yaml
the proxied destinations for the requests `/ring` and `/all_user_stats` were 502-ing.
With this patch, they are working again. 
Since it's my first contribution, feel free to tell me if I'm doing something wrong ;) 
Cheers
Signed-off-by: Guillaume Winter <gwinter@heroku.com>
> fix k8s nginx config

- CHANGELOG.md
- pkg/chunk/table_manager.go
We've made a lot of efficiency improvements, so reduce the default capacity.
No single figure will work for everyone, but we can assume most people running with the default are running a small installation to check it out, so let's give them a smaller bill.
(3000 units times 2 tables is about $6,000 per month)
> Reduce default DynamoDB write capacity from 3000 to 1000

- pkg/alertmanager/alertmanager.go
#1597 ended up breaking the routing in the alertmanager. This because the route prefix provided in the function is only meant to be . added to the `v2` alertmanager api. In the cortex use case both `v1` and `v2` need to be prefixed with the external url. This pr fixes the issue.
> fix routing change for alertmanager

- pkg/distributor/ha_tracker.go
If the ring and the HA tracker share the same prefix then we will end up
handling invalid keys.
Fixes #1652 and #1628
> Make sure the HA tracker only handles valid keys

- docs/arguments.md
Currently the documentation implies that we should specify "replica" for `distributor.ha-tracker.replica` but use the  `__replica__` name as external label in your prometheus config. That is because the defaults in the documentation currently do not represent the actual defaults, see: https://github.com/cortexproject/cortex/blob/3c4f80441910cb4b5d9f94f939e257cf365d8e84/pkg/util/validation/limits.go#L51-L52
Signed-off-by: unknown <weeco91@gmail.com>
> Clarify HA options for prometheus config

- pkg/alertmanager/multitenant.go
- pkg/ruler/scheduler.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
fix #1683
> remove _total suffix for some gauge metrics

- pkg/chunk/encoding/bigchunk.go
- pkg/chunk/encoding/bigchunk_test.go
- pkg/chunk/encoding/chunk_test.go
Remove pointer indirection on the underlying `XORChunk`, which will save memory and a few CPU cycles.
We have to be careful to create the Appender after the chunk is appended to our slice, since it has a pointer to the chunk memory.
And stop storing the end time of every small chunk - we can look at the start time of the next one since they don't overlap. This makes the data structure slightly smaller, and speeds up unmarshalling since we don't need to seek through every value.
We don't _need_ to store the start time either, since it can be fetched from the underlying chunk, but that takes longer.
Estimate of the impact:  Suppose chunks are avg 6 hours long then each one has 12 smallchunks and we save 16 bytes per = 192MB per million series, plus Go heap overheads.
> Shrink bigchunk data structure

- pkg/chunk/chunk_store_test.go
- pkg/chunk/schema_caching.go
- pkg/chunk/schema_caching_test.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
Fixes #1522 "ChunkStoreRandom Flake".
I believe this was a real bug - queries that ended on exact day boundaries wouldn't query chunks which started on exact day boundaries.
> Chunk time ranges are inclusive.

- pkg/chunk/encoding/bigchunk.go
`append()` doubles the size every time it needs more space, which is quite noticeable after #1649.
These slices are only extended every 120 samples, which is 30 minutes at 15-second sampling, and we're already copying the chunk buffer itself for similar reasons.
> Explicitly reallocate bigchunk slice to avoid up to 2x overhead

- pkg/chunk/encoding/factory.go
I did this so I could get nicer test names, but it also changes the help text from:
```
-ingester.chunk-encoding value
Encoding version to use for chunks. (default 1)
```
to:
```
-ingester.chunk-encoding value
Encoding version to use for chunks. (default DoubleDelta)
```
> Use human-readable names for chunk encodings

- pkg/util/validation/limits.go
- pkg/util/validation/override.go
Otherwise the program will operate with default values for the first ten seconds.
Given this, we don't need to fake the 'success' metric.
> Load overrides from file during initialisation

- pkg/chunk/aws/dynamodb_table_client.go
There's a Loki issue https://github.com/grafana/loki/issues/1101 reporting that on DynamoDB table creation, the table is always created with the provisioned billing mode, even if the on-demand one has been enabled in the config (then, the next table manager loop reconcile will fix it).
This PR fixes it.
> Fixed on-demand billing mode on DynamoDB table creation

- pkg/chunk/gcp/bigtable_index_client.go
- pkg/chunk/gcp/table_client.go
Continuation of #1648 which I closed because I didn't fully understand the issue I was trying to solve.
* Bigtable has a global rate limit for admin operations across a project.
* Each operation counts towards this limit which can very quickly choke the endpoint if multiple . table managers request info within a few minutes.
* To ensure a schema is properly constructed in bigtable, a call to bigtable is required per table.
* We utilize a static consistent schema config across all of our services and creating a one off schema for the table manager is not desirable
* Once created a cortex table in bigtable does not need to be updated unless it is changed externally
Based on these parameters, caching is the best solution because it dramatically reduces the number of admin operations to …
> Cache Bigtable Table Info

- cmd/cortex/main.go
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
- pkg/cortex/cortex.go
The `schema_config` uses `dailyBuckets()` (starting from `v2`) to generate the buckets where indexes/chunks should be stored. The bucket also contains `tableName`, so it effectively drives to which table data is read//written.
Due to how `dailyBuckets()` is implemented, it constructs the `tableName` as function of the day bucket (with time `00:00:00`). Because of this, reads/writes occurs on index/chunk tables whose name is constructed with a daily-approximated numbering.
If the table period is not a multiple of `24h`, the table manager will create/update/delete tables with a naming not matching the real one (generated by `dailyBuckets()`).
After a [brief discussion with Brian on Slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1570008064266600), in this PR I'm proposing to …
> Validate schema config to ensure table period is a multiple of buckets period

- pkg/alertmanager/multitenant.go
- pkg/chunk/cache/redis_cache.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk_test.go
- pkg/chunk/encoding/chunk.go
- pkg/chunk/gcp/bigtable_index_client.go
- pkg/chunk/local/boltdb_index_client.go
- pkg/chunk/testutils/testutils.go
- pkg/distributor/distributor.go
- pkg/distributor/ha_tracker.go
- pkg/ingester/ingester.go
- pkg/querier/batch/non_overlapping.go
- pkg/querier/batch/stream.go
- pkg/querier/correctness/runner.go
- pkg/querier/frontend/frontend.go
- pkg/querier/queryrange/results_cache_test.go
While reviewing the distributor implementation, I've noticed the `sendDuration` metric was defined but unused. I've took the chance to quickly run a linter to remove unused variables and code.
_Don't know how this kind of PRs are seen, but in case there's any interest, here it is._
> Removed unused code

- pkg/distributor/distributor.go
- pkg/distributor/http_server.go
- pkg/ingester/client/client_test.go
- pkg/querier/remote_read.go
- pkg/util/http.go
ReadAll() will start at 512 bytes then successively double the buffer, copying the contents each time. If the caller supplies a size we can be much more efficient. It's not a massive win, but every little helps.
(However, doing this creates a new DoS vector - supplying an fake size that is way too big. I'm thinking we should have a max input size, similar to gRPC)
> In Distribtor, pre-allocate buffer for reading protobufs

- pkg/distributor/distributor.go
The PR https://github.com/cortexproject/cortex/pull/1719 introduced a typo in the name of the YAML config option (send instead of recv). This PR fixes it.
> Fixed max_recv_msg_size distributor config option

- docs/architecture.md
- docs/single-process-config.yaml
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/schema.go
- pkg/chunk/schema_caching.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_test.go
- pkg/chunk/series_store.go
We ran Loki for a while using the new `LabelNamesForMetricName` to retrieve all possibles labels. Turned out that it does pull too many chunks for a single query spanning over 6h (12k~)
This introduces a new schema where we store the metric (labels set) within the `IndexEntry.Value`. Other schema keep the same implementation.
Design doc & reason for this change: https://docs.google.com/document/d/1sVZHtQACLQZfiKnnFhXSiqyRx6YSX945s9jPjc2js6o/edit?usp=sharing
/cc @gouthamve
> Adds v11 schema

- pkg/ring/kv/consul/client.go
- pkg/ring/kv/consul/client_test.go
- pkg/ring/kv/consul/mock.go
- pkg/ring/kv/etcd/mock.go
- pkg/ring/kv/kv_test.go
- Added tests for WatchKey and WatchKeyPrefix kv.Client methods.
- Removed backoff from Consul client when Consul reports no value for given key or prefix. Since Consul also reports index, next query blocks as expected, and no backoff is necessary. (Introduced by #560, see also next item)
- Fixed Get call in mockKV to block for non-existant key if WaitIndex > 0. This is how Consul works, and this inconsistency was primary reason for PR #560, which introduced backoff in such case instead (which then delays everything, especially tests). Added test for this.
- Changed WatchKeyPrefix in Consul client to not report values that were not modified. Consul returns them even if they haven't changed.
- Fixed mockKV to always start with Index 1. This in line with how Consul works and what our client …
> Various fixes in Consul client and mockKV ("inmemory" KV store)

- Makefile
Go caches builds for different tag sets now, so we don't need to pre-build or check this has been done.
> Remove check for 'netgo' build of standard library

- pkg/querier/queryrange/roundtrip.go
Seeing the individual request parameters is helpful to understand how what query-frontend has done.
Code was removed [here](https://github.com/cortexproject/cortex/pull/1437/files#diff-a3c5f793878e4a5ee5d4ebdbbf81a8c0L130) without explanation.
> Add back some logging on each request in query-frontend

- CHANGELOG.md
- docs/arguments.md
- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/series.go
> Ability to flush chunks with stale markers early.

- pkg/ring/kv/kv_test.go
Test failure reported by @gouthamve, after recent merge of PR #1756:
```
--- FAIL: TestWatchPrefix (3.86s)
--- FAIL: TestWatchPrefix/etcd (1.86s)
kv_test.go:191: key test/97 has incorrect value 0
kv_test.go:191: key test/98 has incorrect value 0
kv_test.go:191: key test/99 has incorrect value 0
```
~Test was too strict. Now it checks that we receive most notifications, but not necessarily all.~
Test watches for changes under prefix "test/" and expect single change in every key between 0-100. 
It failed because it didn't wait long enough. Now it waits for longer time, but stops as soon it receives all notifications. Also watching for changes starts before generator starts, so that first changes can't possibly be missed.
> Fix for flaky test.

- pkg/chunk/chunk.go
- pkg/chunk/schema.go
- pkg/chunk/schema_util.go
Empirically, from data stored at Weaveworks, the code used a different version marker and a different size calculation.
Allow that data to be read without affecting chunks written more recently.
> Fix chunk reading from ancient v3 schema

- pkg/ingester/flush.go
- pkg/ingester/series.go
This PR implements a simple addition: export of timestamp of oldest unflushed chunk in memory. This can be used for alerting, if timestamp is older than expected.
Fixes #1386
> Export Unix timestamp of oldest unflushed chunk in the memory.

- pkg/ingester/ingester.go
Suspect the culprit was copy-paste.
> Fix typo in max-stale-chunk-idle flag

- CHANGELOG.md
- docs/prometheus-frontend.yml
- pkg/querier/frontend/frontend.go
This PR has a feature to log slow queries in Frontend based on `querier.log-queries-longer-than` parameter. As per this discussion on issue [1567](https://github.com/cortexproject/cortex/issues/1567)
cc @gouthamve
> Add support to log slow queries in Frontend

- CHANGELOG.md
- pkg/cortex/cortex.go
- pkg/distributor/distributor.go
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
addresses #1534, adds a new `distributor.ha-tracker.update-timeout-jitter` config to add a +/- jitter to the UpdateTimeout for the HA dedupe heartbeat.
> Add jitter to HA deduping heartbeats (#1543)

- CHANGELOG.md
- docs/arguments.md
The PR #1760 (merged) introduced a global limit on the max series per user/metric, without updating the documentation. This PR does it.
**Checklist**
> Improve doc for max series per user/metric global limit

- pkg/ring/kv/metrics.go
CAS calls to the KV store can return HTTP status codes since the addition of the HA tracking code. 
If the return error of the CAS has an HTTP status code, we should return that. This will resolve the issue of the KV metrics showing 500's for all writes from the non-elected Prometheus replicas.
@tomwilkie
> Don't return 500's for KV CAS calls if the CAS returned an HTTP status code.

- pkg/storage/tsdb/config.go
In the PR #1772 I've introduced GCS config support to TSDB shipper, but I've forgot to register the cli flags (the config was working via yaml, but not flags). In this PR I'm fixing it.
**Checklist**
> Fixed TSDB shipper GCS cli flags registration

- pkg/chunk/chunk.go
- pkg/chunk/schema_test.go
- pkg/chunk/schema_util.go
I felt the need for this when working on #1779.
`%q` is better than `'%v'` because it will show unprintable characters as escape sequences.
> Improve reporting of some chunk errors

- .github/pull_request_template.md
It's quite common that PRs add entries to the changelog in the wrong order. I would suggest to add the order directly in the PR template, to hopefully help remember the correct one.
**Checklist**
> Added changelog entries order to PR template

- pkg/ingester/ingester_v2.go
- pkg/querier/block.go
- pkg/querier/block_test.go
- pkg/storage/tsdb/labels.go
- pkg/storage/tsdb/labels_test.go
The current (experimental) TSDB integration has two issues related to the external label added by the shipper:
1. The label name is `"user"`, which can overlap with a metric label
2. The external label is not removed when querying the TSDB storage, thus leading to duplicated series: the series read from the storage have the `"user"` label, while the series read by ingesters don't
In this PR, I'm proposing to:
1. Rename `"user"` external label to `__org_id__` to avoid collisions
2. Remove the external label when querying the storage
3. Abort a TSDB query in case of partial response (we want full consistency)
**Checklist**
> Fix duplicated series when querying both ingesters and TSDB storage

- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/series_store.go
- pkg/chunk/strings.go
When we query label names or values across multiple stores from different schema period we can lose the unicity or ordering.
This changes sort and filter label in the composite store. I've also added some test to verify the output.
> Fixes store duplicate label names and values.

- pkg/ring/kv/memberlist/memberlist_client.go
Since #1727  ARM build fails with an error:
```
--
130 | vendor/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/memberlist_client.go:619:21: constant 4294967295 overflows int
```
see https://github.com/grpc/grpc-go/pull/1471, it seems that this is cause by missing int conversion with MaxUint32.
I also run all tests `GOARCH=386 make test` all good now.
> Fixes ARM build with const overflow.

- docs/prometheus-frontend.yml
Config for the frontend pipeline stages moved to separate config, this fixes it.
> Update the example frontend config, the fields have moved.

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/s3_storage_client.go
This PR replaces the deprecated session.New with session.NewSession which will enable support for using IAM roles for service accounts in AWS EKS
Fixes #1797, https://github.com/grafana/loki/issues/1241
> Use session.NewSession in order to use AssumeRoleWithWebIdentity

- build-image/Dockerfile
Required for https://github.com/cortexproject/cortex/pull/1851
> Add tools to the build image to build the website

- pkg/ring/http.go
This PR improves the ring status page. It shows the ingester tokens only when a button is pressed.
Fixes #759
> Show ingester tokens after button click in ring status page

- pkg/chunk/chunk_store.go
If a query contains an "out of bounds" time range, we currently log with the error level, but it's not something actionable. For this reason, I propose to lower these two log messages to info level.
_No issue_
**Checklist**
> Lower log level for query time range validation

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
Today me and @pstibrany spent few hours debugging an expected pattern on the number of CAS operations done by the distributors when the HA tracker is enabled.
We found out that the PR #1748 - which introduced the update timeout jitter - also introduced a time window (long as much as the jitter) during which every request does a CAS but the CAS operation itself doesn't update the replica updated timestamp, because the CAS is triggered if `now - receivedAt >= updateTimeout` but then the CAS function is a noop if `now - receivedAt < updateTimeout + jitter`.
While adding tests, I've also realized that the `checkReplicaTimestamp()` was broken (tests were actually failing) so I've fixed it.
_No issue_
**Checklist**
> Fixed HA Tracker jitter causing unnecessary CAS operations

- go.mod
- pkg/ring/kv/memberlist/memberlist_client.go
- pkg/ring/kv/memberlist/metrics.go
- pkg/ring/kv/memberlist/tcp_transport.go
- vendor/modules.txt
This PR fixes some metrics names used by `memberlist.Client` (eg. `_size` -> `_bytes`), and configures "github.com/armon/go-metrics" library used by memberlist to write its metrics to Prometheus.
> memberlist: fix metric names and expose internal memberlist metrics

- pkg/ring/kv/memberlist/memberlist_client.go
- pkg/ring/kv/memberlist/memberlist_client_test.go
Enhance error message in `memberlist.Client.CAS` method to include why CAS failed.
While doing that, this change also makes logic around retries more consistent (eg. if `f` or merge returned error, there was no retry, even if `retry` was true). Furthermore fixes bug when context was done -- previously, iteration continued because `break` only broke select statement, but not `for`.
Added tests.
[This code only affects memberlist-based KV client, which is still marked as experimental]
> Memberlist: Include reason for CAS failure in the error message.

- pkg/ingester/flush.go
Apparently I have periods when the _average_ number of labels goes over 20, and I'd love to be able to dig into who is doing this.
> Add number of labels to event sampling logs

- pkg/ingester/mapper.go
We're aware that there are fingerprint hash collisions and we handle them through the mapper. Is it really worth log them as Info level or can we declass it to Debug?
_A train of these logs is quite common during ingesters rollout, logged by the joining ingester while receiving all series from the leaving one._
_No issue_
**Checklist**
> Declass ingester fingerprint hash collision log to debug level

- pkg/ingester/client/compat_test.go
This PR adds one test, which shows collisions in Fingerprint function. We knew that Fingerprint function has collisions, but now we have specific examples, and simple way to generate more.
> Added fingerprint collisions to the test.

- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- vendor/modules.txt
Earlier this week I found an issue on our TSDB test cluster where an out of order sample was rejected by the ingester with a 5xx error, causing Prometheus to continuously retry it. In this PR I'm handling "soft errors" and track Prometheus metrics like we do for the chunks storage.
_No issue_
**Checklist**
> Fix handling of out of order/bound samples in TSDB ingestion

- pkg/ring/kv/memberlist/memberlist_client.go
- pkg/ring/kv/memberlist/tcp_transport.go
Change TCP transport to use advertised address when sending "packets" (term used by memberlist lib). This was needed to stop memberlist complaining about not being able to ping other members of the cluster when running on internal Grafana k8s cluster.
(Memberlist is still experimental)
> memberlist: Use advertised address when sending packets

- pkg/chunk/chunk.go
- pkg/chunk/chunk_store.go
- pkg/chunk/schema_test.go
- pkg/chunk/schema_util.go
- pkg/chunk/schema_util_test.go
Removed `Chunk.metadataInIndex` because unused (it's never set since https://github.com/cortexproject/cortex/pull/873).
Fixes #1795
**Checklist**
> Removed chunk.metadataInIndex because unused

- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
Uses a temp directory when writing a transfer, to avoid corruptions errors. Will use a different temp dir during each xfer retry.
> use tempdir when xfering tsdb

- docs/arguments.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/util/validation/limits.go
Fixes #1724 
Adds an optional flag per user to drop the cluster label, in addition to dropping the replica label, when ingesting HA samples. Should only be used if that user has their own set of more than two labels that they use to uniquely identify Prometheus replicas.
There's a bit of a refactor here as well:
- I noticed that in the config the ordering of the values was cluster label then replica label, but in RegisterFlags the order is replica then cluster. I moved them around in RegisterFlags to match the order in the struct.
- `distributor.Push` was getting pretty long, I moved the internals of the validation loop into a function `validateSeries`. This also had the side effect of making that portion of the code testable. I've only added tests for the label removal bits. I assume the …
> Add a limits config option to allow for dropping of the cluster label

- pkg/querier/block.go
- pkg/querier/block_test.go
While doing tests on Cortex TSDB, I've realized a query doesn't fail if some series fail to be converted to chunks. There are a couple of warning logs, but from the user perspective we end up with a partial query result, which we would like to avoid in favour of correctness.
In this PR:
- Fail a query if an error occurs while converting TSDB series to chunks
- Handle `chunkend.Iterator.Err()` (was unchecked)
_No issue was created_
**Checklist**
> Fail query if an error occurs while converting TSDB series to chunks

- pkg/cortex/modules.go
- pkg/querier/block.go
- pkg/querier/block_store.go
- pkg/storage/tsdb/config.go
**What this PR does**: Exposes the bucket store configuration that was previously hardcoded to configurable values.
**Checklist**
> tsdb/block_store: expose block store config settings

- pkg/ingester/ingester_v2_test.go
While working on PR #1830 I've realized we don't have any test on the TSDB read path in the ingester. In this PR I'm adding them.
_No issue for this_
**Checklist**
> Added tests covering TSDB read path in the ingester

- pkg/util/extract/extract.go
This relates to #1852 - not sure if it's the only problem but I think this will help.
The chain of ownership:
Strings are pulled directly from the gRPC buffer without copying: https://github.com/cortexproject/cortex/blob/fcbc186d495aea15650d353775677b787d53863c/pkg/ingester/client/timeseries.go#L188
This value is pulled out by `MetricNameFromLabelAdapters()`:
https://github.com/cortexproject/cortex/blob/fcbc186d495aea15650d353775677b787d53863c/pkg/util/extract/extract.go#L15
`metricName` is passed down: https://github.com/cortexproject/cortex/blob/fcbc186d495aea15650d353775677b787d53863c/pkg/ingester/user_state.go#L209
and used as a key into a map:
https://github.com/cortexproject/cortex/blob/fcbc186d495aea15650d353775677b787d53863c/pkg/ingester/user_state.go#L236
> Ensure metric name is not pointing into gRPC buffer

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
The PR #1726 introduced some changes in the distributor to allow to drop labels on a per-tenant basis. These changes also unintentionally changed the actual per-series sharding token: we noticed it while rolling out in one of our clusters, where an almost full resharding occurred (switching the cluster from 5M active series to 9M active series until the old sharing chunks have been flushed).
Before the PR #1726, the token was generated based on the labels **without** the HA replica label. After the PR #1726, the token is generated based on the labels **with** the HA replica label.
In this PR I'm fixing it, rolling back to the old behaviour, while honoring the intention of the PR #1726: the token should be generated based on the labels **without** the HA replica …
> Fixed per-series sharding token generation in the distributor

- pkg/distributor/distributor.go
While investigating the issue #1895, I've realized the request slice is not reused in case the request gets skipped because of HA dedup or rate limiting. In case all incoming requests have the HA enabled, it's 50% of requests. This PR fixes it.
_No issue_
**Checklist**
> Fix reuse slice in distributor.Push()

- CHANGELOG.md
- pkg/ring/http.go
**What this PR does**: This PR changes redirects from /ring page to use relative links, instead of path-absolute. This is useful when running distributor HTTP server behind reverse proxy, which maps it to a different path than root.
**Checklist**
> Fix redirects on /ring page by using relative targets.

- pkg/querier/queryrange/limits.go
- pkg/querier/queryrange/results_cache.go
- pkg/querier/queryrange/split_by_interval.go
This makes the function `doRequests` externally accessible and reusable by the Loki frontend.
> Export queryrange doRequests.

- pkg/ingester/transfer.go
While rolling out ingesters it's usual to get a train of errors `no pending ingesters` while the leaving ingester has started the shutdown procedure but there's still no joining ingester. This is not really an issue, as far as the joining ingester is found before the end of all retries.
In this PR I'm suggesting to lower the log level to Warn while retrying, while logging it as error if persists once all retries have been done.
_No issue_
**Checklist**
> Lower log level on ingester transfer failed because no pending ingester is found

- pkg/ring/tokens.go
I got the following error with the tokens on disk
```
level=error ts=2019-12-06T11:11:31.769733413Z caller=lifecycler.go:268 msg="error storing tokens to disk" path=/wal_data/tokens err="rename /tmp/tokens513306766 /wal_data/tokens: invalid cross-device link"
```
So would be better to use the same volume/directory to have the temporary file as well.
> Use same directory for temporary tokens file

- pkg/ring/model.go
- pkg/ring/model_test.go
Inspired by PR #1866, this PR changes `IsHealthy` function to be explicit about which states are healthy. There is no change in functionality.
There is no bug.
**Checklist**
> Explicit healty states

- pkg/querier/queryrange/marshaling_test.go
- pkg/querier/queryrange/query_range.go
- pkg/querier/queryrange/query_range_test.go
- pkg/querier/queryrange/roundtrip.go
Loki has the concept of log Direction which is essential to know when
merging responses. This change allows Loki to inject the direction in the
response which can be then used when merging multiple responses.
Cortex doesn't need to use this.
> Pass Request to DecodeResponse in case it is required.

- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/lifecycle_test.go
- pkg/storage/tsdb/labels.go
- pkg/storage/tsdb/labels_test.go
Currently the `/series` API endpoint doesn't work with the TSDB storage, due to missing implementation of `MetricsForLabelMatchers()`. In this PR I'm addressing this issue.
_No issue created._
**Checklist**
> Add /series support to TSDB storage

- pkg/ingester/ingester_v2.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
- pkg/util/sync.go
- pkg/util/sync_test.go
The Cortex TSDB experimental integration currently close all TSDBs during the ingester shutdown, before blocks and WALs are transferred to a joining ingester. This has two main issues:
1. Query requests received while closing TSDBs fail with error `open index reader: block is closing`
2. Query requests received after the TSDBs have been closed issue a re-opening of TSDBs, which means re-playing the WAL (expensive operation)
Me and @codesome checked out the TSDB implementation and came to the conclusion which is safe to transfer blocks as WAL without closing the TSDB as far as:
1. No more writes occur
2. No compaction is on-going or will occur
In this PR I've introduced some changes to avoid closing and re-opening TSDBs on queries received during ingester blocks/WAL …
> Do not close and re-open TSDBs during ingester transfer

- CHANGELOG.md
- docs/configuration/arguments.md
- pkg/ring/lifecycler.go
- pkg/ring/lifecycler_test.go
- pkg/ring/model.go
- pkg/ring/model_test.go
- pkg/ring/ring_test.go
- pkg/ring/testutils/testutils.go
Removed support for writing denormalised tokens in the ring.
Still supported:
- claiming tokens from another ingester, that is using denormalised tokens
- finding denormalised tokens in the ring, when joining
Other ingesters can still use denormalised tokens, migrateRing takes care of that.
Targeted for Cortex 0.5.0. ~No changelog written yet.~
Issue #1787
Fixes #1877
> Removed support for writing denormalised tokens in the ring.

- pkg/ring/kv/memberlist/memberlist_client.go
- pkg/ring/kv/memberlist/memberlist_client_test.go
Make max CAS retries configurable for tests. Default value is fine for normal usage where updates are coming from network, but when running tests with many goroutines using same KV, default can be too low. Fixes failed tests seen in CI system.
**Checklist**
> pkg/ring/kv/memberlist: Increase max number of CAS retries when running with multiple goroutines using same KV.

- README.md
Signed-off-by: Matt Mendick <matt.mendick@gmail.com>
Changing the readme logo path from `imgs` to `images` after the new website changes.
This seems to be the only such issue after the website changes, all the other docs paths were updated.
> Updating logo path in README to correct images folder

- pkg/querier/queryrange/roundtrip.go
- pkg/querier/queryrange/roundtrip_test.go
This is now done in the queryrange tripperware, the idea is to be able to reuse
the roundtripper code for other endpoint like labels.
I think a natural next step would be to move all this generic code, that can be reused outside of the queryrange package.
This include interfaces like `Codec`,`Request`,`Middlewares`,`Reponse`, at the I was thinking inside the package frontend.
> Removes check for path in queryrange roundtripper.

- pkg/distributor/distributor_test.go
Hardcoding interface names cause the tests to fail on systems that have interface names different than the ones hardcoded.
> Replace interface names with local ip in distributor tests

- pkg/ingester/transfer.go
- pkg/ring/flush.go
- pkg/ring/lifecycler.go
If transfers are disabled, a skipped transfer could result in a fake alert if alerting on the metric.
In this PR: If transfers are disabled, don't count that as a failure in the metric.
/cc @pracucci
> Do not consider disabled transfer as failed transfer

- pkg/ingester/errors.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/series.go
- pkg/ingester/user_state.go
Fixes #1301 
There is quite a lot of refactoring here, pulling out various things into helper functions in a new file `errors.go`.  Also I moved a couple of places that the discarded samples metric is incremented for consistency.
I'm not very clear why we need "httpgrpc" at all here, as `Push()` is only called over gRPC, but left that for another day.
Benchmark before:
```
BenchmarkIngesterPushErrors  10  154925847 ns/op  137223744 B/op  516830 allocs/op
```
after:
```
BenchmarkIngesterPushErrors  50  33549567 ns/op    4411341 B/op    64796 allocs/op
```
> Reduce memory usage from ingester Push() errors

- docs/guides/running.md
No issue has been submitted for this
**Checklist**
As discussed via Slack we want to add this piece of information so that it's available for everyone. Specifically that resharding in Prometheus can be buggy at the moment which causes high delays (1-5 minutes) until metrics land in Cortex and how one could work around this issue.
cc @bboreham @csmarchbanks
> Adds documentation about configuring prometheus

- CHANGELOG.md
- pkg/cortex/modules.go
- pkg/querier/block.go
- pkg/querier/block_store.go
The querier - when running with the TSDB experimental storage - does the initial sync of all TSDB blocks' index header, which may take some time (order of minutes). Until successfully completed, it will not be ready to serve queriers.
In this PR:
- Add `/ready` endpoint to the querier, which always return `204`, once the initialization has been done
- Start the query frontend worker only after the store and querier have been successfully initialized
_N/A_
**Checklist**
> Added /ready endpoint to queriers

- docs/configuration/arguments.md
Upon @gouthamve suggestion, I've improved the ingestion rate global limit documentation to make it clear it requires evenly balanced traffic in front of distributors (which is a desired thing anyway, but required to have the global limit working as expected).
N/A
**Checklist**
> Make it clear ingestion rate global limit requires evenly balanced traffic to distributors

- CHANGELOG.md
- docs/architecture.md
- docs/operations/_index.md
- docs/operations/blocks-storage.md
In this PR:
- Added missing TSDB-related changes (already merged) to changelog
- Updated Cortex architecture doc 
- Documented the experimental blocks storage
**Notes to the reviewer:**
- I suggest to read the updated architecture doc entirely and not from the diff, to have a better overview of how has been covered
- Mentioned the WAL, since I do expect to be merged soon.
- Mentioned the blocks compactor, which I hope to see merged soon (PR https://github.com/cortexproject/cortex/pull/1942).
- I've specified the blocks storage config giving preference to YAML and mentioning each related CLI flag. I've used the Prometheus config documentation syntax (also used by Loki). If there are no objection, I would like to submit a subsequent PR to document the entire Cortex …
> Updated Cortex architecture doc and documented the experimental blocks storage

- pkg/configs/db/postgres/postgres.go
Ensures the proper file URI scheme for the provided migrations directory.
Fixes https://github.com/cortexproject/cortex/pull/1802#issuecomment-562556715
> prefix migrations dir to URI

- pkg/ingester/ingester.go
Today I've been tricked by the `state = nil` statement in `ingester.append()` and thought it could be worth to better explain it.
N/A
**Checklist**
> Improved comment explaining an unlock logic in the ingester

- website/config.toml
I shared a link on Twitter and I've realized there's no image in the Twitter Card (see below). This PR fixes it, displaying the Cortex logo.
N/A
**Checklist**
> Website: fix Twitter / Facebook link image

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
`shardByAllLabels` had a check to verify if labels are sorted properly, but it didn't set `lastLabelName`, so it was comparing label names against empty string only.
> pkg/distributor: shardByAllLabels didn't check for label names order correctly

- website/assets/scss/_styles_project.scss
In this PR I'm proposing to style the doc website's left sidebar (and top navigation) with a ligther style that - in my opinion - helps the readability.
Before:
After:
N/A
**Checklist**
> Doc website: lighter left sidebar

- pkg/ingester/errors.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
Today I was investigating the cause of the error `sample with repeated timestamp but different value for series` and I couldn't find the related user because it's not logged. In this PR, I'm suggesting to wrap any ingester Push error with the user ID.
N/A
**Checklist**
> Added user ID to ingester push soft/hard errors

- GOVERNANCE.md
This PR makes a change to the Cortex project voting rules: to avoid having a single company dominate the project, at most two votes from maintainers working for the same company will count.
Other projects such as Thanos and CNI have similar rules.
> Change governance to cap voting at 2 per company

- MAINTAINERS
With the recent change in governance to limit votes for each company, it
is important for these affiliations to be officially recorded.
> Change affiliation to Splunk for Chris and Cody

- CHANGELOG.md
- pkg/ingester/ingester_v2.go
- pkg/storage/tsdb/config.go
**What this PR does**: Uses a negative or 0 value of `TSDBConfig.ShipInterval` as an indicator to disable shipping instead of allowing `timer.NewTicker` to panic.
**Checklist**
> tsdb: optionally turn off shipper

- CHANGELOG.md
as requested in this PR: https://github.com/cortexproject/cortex/pull/1975/files/09e37606e8f5bb3c0ff23759bd786cb4ed34e007#r366242541
**What this PR does**: Updates the internal name in the changelog to the external flag.
**Checklist**
> CHANGELOG: changed ShipInterval to the cli flag

- README.md
- docs/guides/cortex-with-cassandra.md
This PR contains step by step guide for running cortex as a single binary and configuring cassandra as backend storage.
Signed-off-by: vineeth <vineethpothulapati@outlook.com>
@gouthamve
> Adding docs for running cortex with cassandra

- CHANGELOG.md
- cmd/cortex/migrations/002_immutable_configs.up.sql
This allows for migrations from v1 migrate to the current version of migrate
https://github.com/mattes/migrate/tree/master/database/postgres#upgrading-from-v1
Helps Fix #1972 
**Checklist**
> wrap migration commands

- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
I'm assisting an user on Slack, and I've realized we don't log the series whose sample fails to be appended to TSDB. I've switched the logic from "last partial error" to "first partial error" in order for performance reasons (in case many samples fail in a single write request).
N/A
**Checklist**
> Added the series to the error when a sample fail to be appended to TSDB

- website/assets/scss/_styles_project.scss
In this PR I did a couple of minor styling touches to the website:
1. Fixed a margin in the left-sidebar, erroneously introduced by PR #1946 
2. Slightly smaller `h4` font to help the reader better distinguish between sections
After changes:
N/A
**Checklist**
> Websyte: minor styling touches

- CHANGELOG.md
- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/series.go
This improves observability of flushing, creating separate labels for chunks that overflowed versus to series that reached their time under spread-flushes behaviour.
Fixes the point noted in #1578 "the 'reason' stats are less helpful".
The flushReason type shrinks to int8 to avoid bloating the chunk desc object.
**Checklist**
> Report chunks flushed by spread-flushes option under separate label

- CHANGELOG.md
- pkg/ingester/ingester_v2.go
This PR updates some existing ingester metrics from blocks code. Specifically:
We already update ingestion metrics from blocks code (`cortex_ingester_ingested_samples_total`, `cortex_ingester_ingested_samples_failures_total`)
Querying:
- `cortex_ingester_queries_total` (this was already tracked before this PR)
- `cortex_ingester_queried_samples` (added by this PR)
- `cortex_ingester_queried_series` (added by this PR)
- Ignored metric: `cortex_ingester_queried_chunks` – chunks-specific
User state:
- `cortex_ingester_memory_users` (~added by this PR~ [update: now removed again, in favor of PR #1982), basically equals to number of open TSDB databases in Cortex)
- Ignored: `cortex_ingester_memory_series` – cannot see easy way to get this, not even in TSDB metrics
- Ignored: …
> TSDB: metrics for queries

- CHANGELOG.md
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/storage/tsdb/config.go
**What this PR does**: Experimental TSDB change only. On startup walk the TSDB dir, and open a TSDB under each user dir. Limiting the number of concurrently opening TSDB. 
Large memory spikes were observed when Ingesters would startup that had a large number of users with WALs. 
This was causing oom kills on ingesters that would otherwise be able to run just fine. This change limits the number of TSDBs that can be opening at once, by opening all pre-existing user TSDBs at startup.
It does not open a TSDB for an empty user dir, which means it has no interaction with a transfer, since transfers delete empty dirs, and error out on non-empty user dirs.
Edit: While this change is still useful it doesn't address the memory usage spikes seen above, and because of a missed lock when looking over …
> Limit concurrent replays of TSDB on startup

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/transfer.go
- pkg/ingester/user_state.go
In this PR I've implemented the following two metrics for TSDB storage:
- `cortex_ingester_memory_series`
- `cortex_ingester_memory_users`
I've also moved the 4 metrics globally registered in `user_state.go` to the `ingesterMetrics` struct to ease testing.
This PR complements #1981 by @pstibrany.
N/A
**Checklist**
> Fix ingester_memory_series/users metrics for TSDB storage

- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
This defers putting a slice back into the pool (ingester push path) to prevent panicking Error() calls which reference the underlying labels.
This defers returning an allocated slice to its pool until after use. Previously we saw panics on `Error()` calls which held references to the underlying timeseries label set.
> Prevents panic using freed slice in pool

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
When using TSDB, we get per-user created and removed series from TSDB metrics.
This affects `cortex_ingester_memory_series_created_total` and `cortex_ingester_memory_series_removed_total`.
This PR also renames `shipperMetrics` to `tsdbMetrics`, and registers the same registry to TSDB and TSDB shipper component.
Registration of prometheus registry now happens only after TSDB initialization is finished, in order to fix a panic where metrics were collected while TSDB was still initialized.
This PR builds on PR #1983, so "Files changed" also shows changes from there. I'll rebase once (if) #1983 is merged. Update: now rebased.
> TSDB: fix user metrics when using blocks storage

- CHANGELOG.md
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
- pkg/querier/block.go
- pkg/querier/block_store.go
- pkg/querier/block_store_metrics.go
- pkg/querier/bucket_store_metrics_test.go
- pkg/util/metrics_helper.go
- pkg/util/metrics_helper_test.go
This PR adds export of aggegate metrics from TSDB's `store.BucketStore` and `storecache.InMemoryIndexCache`, used by Querier component.
This PR uses same approach as #1990 and #1983 before that. It builds on #1990, and moves code related to aggegating and sending metrics into pkg/util/metrics_helper.go file.
**Checklist**
> TSDB: add bucket store metrics in querier

- cmd/cortex/main.go
- cmd/cortex/main_test.go
This PR fixes regression introduced by #1997.
When using `flag.ContinueOnError`, `Parse()` method on `*flag.FlagSet` returns errors, instead of panicking or exiting the program.
My assumption was that it actually continues, but that's not the case. When cortex was called with `./cortex -target=distributor -server.http-listen-port=8001 -server.grpc-listen-port=9001 -config.file=./config.yaml`, `Parse()` method returned error on first unknown parameter (which is `-target=...` here, as we only look for `-config.file` at first), and then config file parameter was not found.
To actually find the `-config.file` parameter, we now call flag.Parse repeatedly with reduced set of arguments, until configFile is set to non-zero string or we run out of arguments.
> Fixes regression introduced by recent change to avoid double call to flag.Parse()

- .circleci/config.yml
- Makefile
- build-image/Dockerfile
While reviewing the PR #1941, I've realized we don't run any validation on K8S spec files in CI. I think it could be useful as signal to spot trivial issues during the review process.
In this PR, I'm proposing to run [`kubeval`](https://kubeval.instrumenta.dev/installation/) in CI. This would require to publish a new `build-image` (for which I don't have privileges), but first I would like to scout if this is a desired change.
N/A
**Checklist**
> Run kubeval to validate K8S spec files

- CHANGELOG.md
- docs/operations/blocks-storage.md
- pkg/querier/block.go
- pkg/querier/block_store.go
- pkg/querier/block_store_test.go
- pkg/storage/tsdb/bucket_client_mock.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
Currently, there's an hardcoded `30s` as blocks sync interval (TSDB storage). It's quite a lot. I believe we don't even need such an high-frequency sync interval (at least, not as default) so I'm proposing to allow to configure it and set an higher default (Thanos' default is `3m`, I've set `5m` which should be more than enough for the Cortex use case).
I've also received an error from the linter because the `rununtil.Repeat()` error wasn't checked, so I took the change to refactor it (moved to `UserStore` since it belongs to it), renamed `cortex_querier_sync_seconds` to `cortex_querier_blocks_sync_seconds` and customized the buckets: default values are too low for this operation in a medium/large cluster.
N/A
**Checklist**
> Improve TSDB blocks sync

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- docs/guides/sharded_ruler.md
- pkg/cortex/modules.go
- pkg/ruler/lifecycle_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_ring.go
- pkg/ruler/ruler_test.go
The current ruler config exposes a number of flags that should be set to default values. For instance the ruler should never be run with a replication factor >1. However, as things stand currently the flag defaults to 3 which makes configuring the sharded ruler quite difficult. This PR adds a Ruler RingConfig struct based on the Distributor RingConfig that simplifies the ring flags for the ruler.
* Adds a guide on how to set up a sharded ruler
* Add custom ruler ring config to remove unused/dangerous lifecylcer flags
Fixes #1986 
**Checklist**
> 20190115 ruler better flags

- CHANGELOG.md
- pkg/chunk/schema_config.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
This PR includes following to fixes:
1. Fix calculation of expected tables:
While calculating periodic tables for a given duration, the end time of the duration was used to find what the last table number would be. To avoid creating an extra table, there was a check whether end duration was ending exactly at end of the day which was causing the whole table to be omitted. Instead of checking against a days duration, this PR uses periodic table duration to check whether we have an extra table.
2. Create tables from upcoming schema considering grace period:
We skip creating tables for configs whose start time is after `now()` which means tables would not be created until we already are past the start time of config. This can cause writes to fail since tables won't be …
> fix calculation of expected tables and create tables from upcoming schema considering grace period

- pkg/ingester/flush.go
Pass the reason from `shouldFlushChunk()` to `closeHead()`; sending `reasonImmediate` was a bug introduced in #1978.
We don't need to check `len(chunks)` is non-zero, since that would return `noFlush` from `shouldFlushSeries()`.
Also close the gap where `reasonImmediate` could be returned on an empty series, which would then have crashed.  Don't know if it's possible in practice to get that state.
> Fix some cases where flush reason is recorded as 'Immediate'

- pkg/chunk/cache/background.go
- pkg/chunk/cache/cache.go
- pkg/chunk/cache/fifo_cache.go
- pkg/chunk/cache/instrumented.go
- pkg/chunk/cache/memcached.go
- pkg/chunk/cache/mock.go
- pkg/chunk/cache/redis_cache.go
- pkg/chunk/cache/snappy.go
- pkg/chunk/cache/stop_once.go
- pkg/chunk/cache/tiered.go
- pkg/cortex/modules.go
All code paths return nil as the error, so we can simplify the code.
(Redis is the only one that looks as if it might, but if you go one level down it doesn't)
> Remove error return from Cache.Stop()

- CHANGELOG.md
- docs/operations/blocks-storage.md
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/transfer.go
- pkg/ingester/transfer_test.go
- pkg/querier/block_store.go
- pkg/querier/block_store_test.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
Currently there's no limit on the number of tenants concurrently synchronizing blocks in the querier and shipping blocks in ingester. This can lead to unpredictable high spikes in CPU and memory utilization when new blocks are compacted (remember that all blocks are compacted from the head nearly at the same time - see issue https://github.com/cortexproject/cortex/issues/2003).
In this PR I've introduced two flags to limit the concurrency:
- `-experimental.tsdb.ship-concurrency` to limit the number of tenants concurrently shipping blocks in the ingester
- `-experimental.tsdb.bucket-store.tenant-sync-concurrency` to limit the number of tenants concurrently synchronizing blocks in the querier
_I've also introduced `UserTSDB` and kept a similar design to the one …
> Limit max number of concurrent tenants shipping and synchronizing TSDB blocks

- pkg/compactor/compactor_test.go
In the PR #1942 I did a mistake in the compactor tests which cause some flaky tests. The compactor tests mock the bucket client **after** the compactor is started and this leads to flaky tests (unfrequent, but seen in CI). This PR fixes it.
N/A
**Checklist**
> Fix flaky tests in compactor

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- pkg/chunk/chunk_store.go
- pkg/cortex/cortex.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/querier/unified_querier.go
- pkg/ruler/ruler_test.go
**What this PR does**: Moves the MinChunkAge option from chunk store into the querier to allow that behaviour regardless of store backend.
N/A
**Checklist**
> querier: option to skip sending queries to long term storage

- Makefile
- RELEASE.md
As requested by @tomwilkie, I've built the binaries for the Cortex `0.6.0` and added an entry to the `Makefile` to easily do it next time.
N/A
**Checklist**
> Make Cortex release binaries

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/rate.go
- pkg/ingester/rate_test.go
Make `/all_user_stats` page available when using BlocksStorage.
Fixes #1825
**Checklist**
> ingester v2: supports statistics in blocks storage

- pkg/ingester/lifecycle_test.go
- pkg/ingester/transfer.go
- pkg/ingester/wal_test.go
In the local development environment may happen that a spurious file is in the TSDB blocks directory. This shouldn't happen in production, but if that happens for any reason I believe it's safer to just skip it instead of having the ingester transfer breaking.
In this PR:
- Ensure TSDB blocks transfer work even if a spurious file is in the TSDB blocks directory
- Wrap more errors that could occur during the transfer, in order to easily identify issues
N/A
**Checklist**
> Ensure TSDB blocks transfer work even if a spurious file is in the TSDB blocks directory

- pkg/alertmanager/multitenant.go
- pkg/cortex/modules.go
Instead of calling `os.Exit` the Alertmanager will return an error when it is being initialized.
> Return error instead of os.Exit when initializing Alertmanager

- CHANGELOG.md
- cmd/cortex/main.go
- docs/configuration/config-file-reference.md
- pkg/cortex/cortex.go
- pkg/querier/queryrange/results_cache.go
- pkg/querier/queryrange/results_cache_test.go
- pkg/querier/queryrange/roundtrip.go
This PR deprecates `frontend.cache-split-interval` in favor of using `querier.split-queries-by-interval`, reducing the configuration burden. Additionally, these two configurations should be in alignment when both splitting and caching middlewares are enabled, which is now ensured. In order to not cause compatibility issues, it will continue to use the old `frontend.cache-split-interval` when specified, but log a deprecation message.
closes https://github.com/cortexproject/cortex/issues/2038
> Deprecate cache interval

- pkg/ingester/wal_test.go
As per the #2048 discussion, I'm removing the override to log to stdout in `pkg/ingester` tests. If required, we'll figure out a better way to conditionally turn on the stdout logger in unit tests.
Fixes #2048
**Checklist**
> Do not log to stdout in ingester tests

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ring/ring.go
- pkg/ring/ring_test.go
- pkg/util/validation/limits.go
**Experimental TSDB Change Only**
**What this PR does**:  Opening a TSDB per user on each Ingester presents a problem with memory consumption. The series hashtable that TSDB pre-allocates per user is roughly 1.5MB.
Which means that at a large user count it eats up a large amount of memory per Ingester. More importantly when the number of ingesters/nodes are scaled out the memory consumption stays the same per node since the same number of TSDB's are allocated on each node. 
Just as a demonstration I reduced the stripe size in the TSDB code. 
```
+++ b/vendor/github.com/prometheus/prometheus/tsdb/head.go
@@ -1465,7 +1465,7 @@ type stripeSeries struct {
}
const (
-       stripeSize = 1 << 14
+       stripeSize = 1 << 8
stripeMask = stripeSize - …
```
> limits: distributor user subrings

- pkg/ring/replication_strategy.go
- pkg/ring/replication_strategy_test.go
This error will appear in contexts where we are not talking about ingesters, e.g. when running sharded rulers.
An example of the error message is at #2058 .
(Do we need to mention this in CHANGELOG?  Do we care about people parsing the text of error messages?)
> Replace 'ingesters' with 'replicas' in error message

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- pkg/chunk/cassandra/storage_client.go
**What this PR does**: Add options to the cassandra storage for retrying error conditions that are recoverable.
Fixes #2010 
**Checklist**
- [ x] Documentation added
- [ x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
Signed-off-by: Ken Haines <khaines@microsoft.com>
> adding retry options for cassandra and updating docs

- .github/stale.yml
In this PR I propose to setup the stale bot for the Cortex project, with the following relaxed settings:
- 60 days with no activity before an issue or PR is considered stale
- 15 days with further no activity before an issue or PR is automatically closed
- Never stale issues with the labels `type/security` or `keepalive` (this is a new label we can use to mark an issue/PR to never go stale)
N/A
**Checklist**
> Setup stale bot

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- go.mod
- go.sum
- vendor/github.com/weaveworks/common/aws/config.go
- vendor/github.com/weaveworks/common/httpgrpc/server/server.go
- vendor/github.com/weaveworks/common/middleware/http_tracing.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/github.com/weaveworks/common/signals/signals.go
- vendor/modules.txt
Following up the PR https://github.com/weaveworks/common/pull/174 merged in `weaveworks/common`, we update the dependency in order to allow to configure gRPC keepalive settings.
Other than the new gRPC flags, the `weaveworks/common` update introduce the following changes, which look safe to me:
- Added support to `AWS_REGION` env var (if not set, the default behavior hasn't changed)
- `server.http-listen-address` and `server.http-conn-limit` and the same for gRPC (if not set, the default behaviour hasn't changed)
N/A
**Checklist**
> Allow to configure server gRPC keepalive

- pkg/querier/lazy_querier.go
**What this PR does**: This PR makes `lazyQuerier` cancellable via context.
Fixes #1832
**Checklist**
> Use buffered channel to unblock lazySet's goroutine

- .github/stale.yml
The stale bot comment is inaccurate in terms of number of days.
N/A
**Checklist**
> Fixed stale bot comment

- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/schema.go
- pkg/chunk/schema_test.go
- pkg/chunk/schema_util.go
- pkg/chunk/schema_util_test.go
I was concerned that `parseChunkTimeRangeValue()` is getting slower and slower as it linear-searches the choices with the newest ones at the end.
This is more idiomatic Go and more efficient because it doesn't have to loop over the slice.
> Refactor: change index key markers from slice to single byte

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/wal.go
- pkg/ingester/wal_test.go
Fix bug: `walconfig` on config file don't work
YAML library use reflect to assign fields, but reflect can't access private fields.
This PR make all ingester.WALConfig public so that `walconfig.*` can work without error.
**Checklist**
> fix wal config not work on config.yml

- pkg/ring/kv/consul/mock.go
- pkg/ring/testutils/testutils.go
- pkg/ruler/api_test.go
- pkg/ruler/lifecycle_test.go
- pkg/ruler/pusher_mock_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
- pkg/ruler/store_mock_test.go
Recent changes to the ruler have apparently introduced flaky tests. This PR should fix them, at least fixes the one I've seen.
1. `TestNotifierSendsUserIDHeader` fails because multiple requests can be sent to the HTTP endpoint, one for each tenant. There were 3 in the test: "1", "user1", "user2". The last two were configured in the mocked store.
```
2020-02-04 17:32:30.918777 I | http: panic serving 127.0.0.1:34862: sync: negative WaitGroup counter
goroutine 546 [running]:
net/http.(*conn).serve.func1(0xc000151180)
/usr/local/go/src/net/http/server.go:1767 +0x147
panic(0x3032f20, 0x3accee0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*WaitGroup).Add(0xc000855e90, 0xffffffffffffffff)
/usr/local/go/src/sync/waitgroup.go:74 +0x22f
sync.(*WaitGroup).Done(...) …
```
> Fix ruler flaky tests

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/wal.go
- pkg/ingester/wal_test.go
The PR #2071 has fixed the WAL config file. I would like to backport it to the `release-0.6` and release Cortex `0.6.1`.
N/A
**Checklist**
> Backport WAL config fix (#2071) to release 0.6.1

- CHANGELOG.md
- pkg/chunk/azure/blob_storage_client.go
**What this PR does**:  Main change was to fix an annoying bug noted in #2024 where the checksum of the downloaded blob was not valid. The underlying problem was that a buffer was passed by value instead of value. The secondary change here is to use a simpler API for downloading blobs from Azure. The previous used API used, opened multiple connections to download blobs in parallel, however this is somewhat unneeded. Even with BigChunk encoding, a given chunk is still measured in KB, plus the chunk store package already manages parallel downloading of separate chunk files. 
Fixes #2024
**Checklist**
- [ x ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
> Fixing & Simplifying Azure Blob Download

- CHANGELOG.md
- docs/architecture.md
- docs/operations/blocks-storage.md
- pkg/storage/tsdb/backend/azure/bucket_client.go
- pkg/storage/tsdb/backend/azure/config.go
- pkg/storage/tsdb/bucket_client.go
- pkg/storage/tsdb/config.go
- vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go
- vendor/github.com/thanos-io/thanos/pkg/objstore/azure/helpers.go
- vendor/modules.txt
**What this PR does**: Adds the needed cortex structs and configuration to enable azure storage usage with the experimental tsdb engine. 
I've got a small cluster using this currently as it's storage backend, but it's still relatively new so I would say testing for this over the long term is still ongoing.
**Checklist**
> Experimental TSDB: Enable Azure Storage Backend

- pkg/ingester/ingester_v2_test.go
Today I've seen the test `TestIngester_v2Push_ShouldNotCreateTSDBIfNotInActiveState` failing with a panic. This PR fixes it.
```
--- FAIL: TestIngester_v2Push_ShouldNotCreateTSDBIfNotInActiveState (0.04s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17ffd57]
goroutine 1506 [running]:
testing.tRunner.func1(0xc00017ee00)
/usr/local/go/src/testing/testing.go:874 +0x69f
panic(0x19c1480, 0x2910650)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cortexproject/cortex/pkg/ingester.TestIngester_v2Push_ShouldNotCreateTSDBIfNotInActiveState(0xc00017ee00) …
```
> Fixed flaky test

- pkg/querier/frontend/frontend.go
- pkg/querier/queryrange/retry.go
- pkg/querier/queryrange/retry_test.go
This stops retries if a middleware in the chain request for cancellation by testing the original context between each retry.
> Frontend: Adds a check for cancellation between each retries.

- CHANGELOG.md
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/storage/tsdb/ref_cache.go
- pkg/storage/tsdb/ref_cache_test.go
In this PR I'm proposing a solution to reduce memory allocations in the ingesters for the blocks storage, introducing `RefCache` to hold TSDB series references.
Looking at our blocks storage test cluster, we can observe 25% of memory allocations is done by `FromLabelAdaptersToLabelsWithCopy`. Contrary to the chunks storage, whenever we call TSDB `appender.Add()` we have to pass a copy of the labels because they may be retained by TSDB (the request labels are reused to reduce memory allocations).
This PR introduces a series reference cache, so that we can use `appender.AddFast()` instead of `Add()` passing the series reference ID (which is a `uint64`) instead of the labels each time we have the reference cached.
Some notes about the `RefCache` design:
1. It's …
> Reduced memory allocations in the ingesters for the blocks storage

- pkg/util/spanlogger/noop.go
- pkg/util/spanlogger/spanlogger.go
- pkg/util/spanlogger/spanlogger_test.go
This allows to safely logs data inside a parent span without creating a new one, and to just log to the logger if no parent span exists.
> Adds FromContext to spanlogger package.

- pkg/chunk/chunk_store_test.go
- pkg/distributor/distributor_test.go
- pkg/ingester/client/pool_test.go
- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/ingester_v2_test.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/query_test.go
- pkg/ingester/transfer_test.go
- pkg/ingester/user_state_test.go
- pkg/ruler/ruler.go
- pkg/storage/tsdb/user_bucket_client.go
- pkg/util/log.go
- pkg/util/middleware/grpc.go
This package simply aliases its `Context` type to `context.Context` from stdlib.
> Remove usage of "golang.org/x/net/context"

- CHANGELOG.md
- development/tsdb-blocks-storage-s3/.data-configstore/api/prom/configs/rules
- development/tsdb-blocks-storage-s3/.data-configstore/api/prom/configs/rules.yaml
- development/tsdb-blocks-storage-s3/config/cortex.yaml
- development/tsdb-blocks-storage-s3/docker-compose.yml
- pkg/cortex/cortex.go
- pkg/cortex/modules.go
The ruler currently panics with the following trace when running with the experimental blocks storage because the querier is initialized with a `nil` store instead of blocks querier store. This PR fixes it.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2834554]
goroutine 397 [running]:
github.com/cortexproject/cortex/pkg/querier.(*chunkStoreQuerier).Select(0xc000af1600, 0xc00064a500, 0xc00017e370, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00029d5c0, ...)
/workspace/src/github.com/cortexproject/cortex/pkg/querier/chunk_store_queryable.go:42 +0xa4
github.com/cortexproject/cortex/pkg/querier.querier.Select.func1(0xc00064a500, 0xc00017e370, 0x1, 0x1, 0xc000088600, 0xc000088240, …
```
> Fixed ruler to run with blocks storage

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/cassandra/instrumentation.go
- pkg/chunk/gcp/instrumentation.go
We see bigtable requests longer than 1s and it's hard to get a good idea with the current histogram buckets just how long these requests are taking, adding a few more buckets.
Signed-off-by: Edward Welch <edward.welch@grafana.com>
> Add additional buckets to Bigtable request duration histogram

- integration/backward_compatibility_test.go
- integration/framework/service.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
I've just merged the PR #1839 (whose tests in CI didn't run after the recent changes to `goimports`) and now the linter on `master` fails because of the `goimports` changes. This PR should fix it.
N/A
**Checklist**
> Fixed linter

- CHANGELOG.md
- development/tsdb-blocks-storage-s3/config/cortex.yaml
- development/tsdb-blocks-storage-s3/docker-compose.yml
- docs/operations/blocks-storage.md
- pkg/compactor/compactor.go
- pkg/compactor/compactor_http.go
- pkg/compactor/compactor_ring.go
- pkg/compactor/compactor_ring_test.go
- pkg/compactor/compactor_test.go
- pkg/cortex/modules.go
- pkg/ring/http.go
- pkg/ring/ring.go
This PR introduces the support to horizontally scale the compactor, when using the experimental blocks storage.
I've also took the change to remove `ingester` references from the ring HTTP page, given it's now used by multiple components (ingesters, ruler, compactor). The refactoring done here should be safe, given we've recently removed support for denormalised tokens.
N/A
**Checklist**
> Add support to horizontally scale blocks compactor

- CHANGELOG.md
- pkg/cortex/modules.go
- pkg/util/runtimeconfig/manager.go
- pkg/util/runtimeconfig/manager_test.go
From the commit message:
```
There seem to be code paths where the overridesReloadSuccess gauge
gets initialized, but `NewRuntimeConfigManager()` never is called
(absence of both log lines: "failed to load config", "runtime config
disabled: file not specified").
promauto.NewGauge() seems to initialize the gauge with the value 0
(that seems to be common in Prometheus client libs).
In the current code, the value 0 is associated with the error
state, and the value 1 is associated with the success state.
Likewise, https://github.com/grafana/cortex-jsonnet/ defines
an alert that fires when this gauge is set to 0 for an extended
period of time.
That is, when `NewRuntimeConfigManager()` never gets called
the gauge indicates a false negative error state.
Starting in the success state is a …
```
> runtimeconfig: initialize overridesReloadSuccess gauge in success state

- integration/framework/service.go
- pkg/chunk/table_manager.go
This is trivial fix that helps integration tests to run slightly faster, as discussed at https://github.com/cortexproject/cortex/pull/2016#pullrequestreview-357570026.
If table-manager is stopped during initial wait, it now exits early.
> Stop table-manager loop early, if it is done

- CHANGELOG.md
Backport PR #2120 to master, because I can't directly push to `master` (protection hook).
N/A
**Checklist**
> Backport PR #2120 to master

- .circleci/config.yml
If a CircleCI setup customize the `IMAGE_PREFIX`, then integration tests fail. This PR fixes it.
N/A
**Checklist**
> Fixed integration tests with a custom IMAGE_PREFIX

- CONTRIBUTING.md
- docs/contributing/vscode-goimports-settings.json
Don't know what you think about this PR, but I've spent a good amount of time configuring VSCode to make it happy with the new `goimports` settings (because `goimports` clashes with `gopls` which is used for code intelligence), so I'm proposing to share the settings publicly.
N/A
**Checklist**
> Share goimports settings for VSCode

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- pkg/chunk/cassandra/authenticator.go
- pkg/chunk/cassandra/storage_client.go
This PR optionally allows users to specify Authenticators for Cassandra that are not including in the default approved `gocql` list. The same password workflow that is used in `gocql` is used by the custom authenticator. It will just utilize a user provided set of approved authenticators.
**Checklist**
> add option to configure approved password authenticators in Cassandra

- Makefile
A couple of days ago PostgreSQL `9.6.17` has been pushed out and its Docker image has changed (requires `POSTGRES_PASSWORD`). Since then, all config db integration tests are failing. I would suggest to get stick to `9.6.16` for the tests to unlock other PRs.
N/A
**Checklist**
> Fixed integration-configs-db

- CHANGELOG.md
- pkg/configs/client/client.go
Put back a metric that got lost in #1571.
Note I used `promauto` for shorter diff but most `HistogramCollector`s in the code registered via `init()` functions.  It's kinda relying on an implementation detail but `distributor.go` is already doing it and yolo.
**Checklist**
> Register a histogram that was omitted

- tools/website/web-pre.sh
- website/layouts/partials/page-meta-links.html
The `edit this page` link as shown below
was broken since I've started the website.
This fixes it and also introduces a way to override the page original path `originalpath` using front matter variable. This is useful for files that are not using the same destination path.
> Fix website documentation edit links

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- go.sum
- pkg/chunk/cache/cache.go
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Fixes a typo in the YAML configuration for caches. Currently, the setting is `defaul_validity`, but it should be `default_validity`.
Fixes #1842 
**Checklist**
> Fix default_validity cache setting typo

- CHANGELOG.md
- docs/configuration/arguments.md
- docs/configuration/config-file-reference.md
- pkg/ring/kv/memberlist/memberlist_client.go
**What this PR does**: This PR exposes `-memberlist.gossip-to-dead-nodes-time` and `-memberlist.dead-node-reclaim-time` options to control how memberlist library handles dead nodes and name reuse.
Fixes https://github.com/cortexproject/cortex/issues/2130
**Checklist**
> Memberlist: Options to control handling of dead nodes and name reuse

- integration/README.md
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/e2e/db/db.go
- integration/e2e/scenario.go
- integration/e2e/scenario_test.go
- integration/e2e/service.go
- integration/e2e/service_test.go
- integration/e2ecortex/services.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/integration_memberlist_single_binary_test.go
* New code also allows the different implementation of service (e.g you will see why it's needed for Thanos).
* Make more things type safe now instead of fragile handwritten strings as references.
* Also added customizing `networkName`. This allows using `t.Parallel` :heart: 
* Added tests to e2e package. 
...because testing, a testing package makes sense right? ;p
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
> e2e: Simplifying and making tests more reliable (by using structs vs handwritten names in string).

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/s3_storage_client.go
- pkg/chunk/azure/blob_storage_client.go
- pkg/chunk/cassandra/fixtures.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/gcp/bigtable_object_client.go
- pkg/chunk/gcp/fixtures.go
- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/local/fixtures.go
- pkg/chunk/local/fs_object_client.go
- pkg/chunk/objectclient/client.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/caching_fixtures.go
- pkg/chunk/storage/chunk_client_test.go
- pkg/chunk/storage/factory.go
- pkg/chunk/storage/index_client_test.go
- pkg/chunk/storage/utils_test.go
- pkg/chunk/storage_client.go
- pkg/chunk/testutils/testutils.go
* Rename the chunk `ObjectClient` to `Client` 
* Create a new ObjectClient interface with simple methods implemented in #2049 
* Create generic object store chunk client in `pkg/chunk/object`
* Update fixtures to detect and utilize generic chunk object client during tests
* Utilize the generic `object.ChunkClient` when S3/GCS/AzureBlobStore/LocalFS is specified as a chunk store, all of these backends already implement the `ObjectClient` interface.
Fixes #2107 
**Checklist**
> Rename chunk.ObjectClient and implement generic object store chunk client

- .circleci/config.yml
- docs/configuration/single-process-config.yaml
- integration/README.md
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/e2e/service_test.go
- integration/e2ecortex/services.go
- integration/getting_started_single_process_config_test.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/integration_memberlist_single_binary_test.go
- integration/util.go
In this PR I've added a simple integration test to run Cortex with the getting started single binary config file and verify that the happy path works (push a metric, read it back).
Fixes #2136
**Checklist**
> Add integration test to run Cortex with the getting started single binary config file

- .circleci/config.yml
- integration/e2e/service.go
- integration/e2e/service_test.go
- tools/test
In this PR:
- Run integration tests framework's unit tests along with integration tests (cause some of them require Docker)
- Remove `grep -v` from unit tests discovery (may be risky)
- Fixed `WaitSumMetric()` flaky tests
Here is the proof that the list of unit tests hasn't changed:
```
$ git ls-files -- '*_test.go' | grep -vE '^(vendor|experimental|integration)/' > before.txt
$ git ls-files -- 'cmd/*_test.go' 'pkg/*_test.go' 'tools/*_test.go' > after.txt
$ diff before.txt after.txt
No diff
```
N/A
**Checklist**
> Fixed execution of integration tests framework's unit tests in CI

- pkg/querier/queryrange/limits.go
- pkg/querier/queryrange/query_range.go
- pkg/querier/queryrange/results_cache.go
- pkg/querier/queryrange/retry.go
- pkg/querier/queryrange/retry_test.go
- pkg/querier/queryrange/roundtrip.go
There were some places where the frontend and middlewares were not using httpgrpc.Errorf which causes some 500 instead of 400.
I'm also wondering if the frontend should really send back a 500 in case of cancellation. Couldn't not find a status quo on this.
> Ensure frontend response status code are correct.

- CHANGELOG.md
- pkg/cortex/modules.go
- pkg/distributor/http_server.go
**What this PR does**: This PR removes unused `/validate_expr` endpoint, introduced by https://github.com/cortexproject/cortex/pull/184. It has never been used, and is not documented, and its output is changing because of changes in Prometheus error reporting (https://github.com/cortexproject/cortex/pull/2088 for details). Instead of fixing it, let's remove it. (If we need it again, we can introduce it again).
> Remove unused /validate_expr endpoint.

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- tools/doc-generator/parser.go
git push --set-upstream origin fix-docs-url
AS IS:
```
externalurl:
[url: <url> | default = ]
```
TO BE:
```
[externalurl: <url> | default = ]
```
**Checklist**
> Fix wrong syntax for `url` in config-file-reference.

- pkg/cortex/cortex.go
- pkg/cortex/modules.go
- pkg/querier/block.go
- pkg/querier/block_test.go
This rewrites BlocksQuerier to implement `Queryable` interface. It does that by implementing `storage.SeriesSet` on top of returned ~streamed~ response from `StoreClient.Series` call.
**Checklist**
> Blocks querier: don't reencode TSDB chunks to Cortex chunks during querying

- integration/alertmanager_test.go
- integration/backward_compatibility_test.go
- integration/e2ecortex/services.go
- integration/ingester_flush_test.go
- integration/query_frontend_test.go
Today @pstibrany was working on #2088 and while testing it in a dev cluster we realized the read path wasn't working despite all unit tests and integration tests passed. The issue was caused by the `query-frontend --> querier worker` which is currently not tested by integration tests. This PR adds such test.
To prove this test would have spotted the issue in #2088:
```
$ hub pr checkout 2088
$ git merge --squash add-query-frontend-integration-test
$ git diff
diff --git a/pkg/cortex/modules.go b/pkg/cortex/modules.go
index 81c715036..e1aa7c695 100644
--- a/pkg/cortex/modules.go
+++ b/pkg/cortex/modules.go
@@ -260,7 +260,7 @@ func (t *Cortex) initQuerier(cfg *Config) (err error) {
api.Register(promRouter)
subrouter := t.server.HTTP.PathPrefix("/api/prom").Subrouter() …
```
> Added query-frontend integration test

- docs/configuration/config-file-reference.md
- integration/e2e/util.go
- integration/query_frontend_test.go
- pkg/querier/frontend/frontend.go
- pkg/querier/frontend/queue_test.go
- tools/doc-generator/main.go
This PR does two things to improve scheduling for the per tenant queues in the query frontend. This is important for two reasons:
1)  To avoid certain cases where expired requests can hamper the fairness of scheduling in the frontend across multiple tenants. 
2) To short circuit expired requests and prevent them from being pulled by the querier workers.
**Checklist**
> Ignore expired requests in frontend scheduling

- integration/integration_memberlist_single_binary_test.go
Let cortex-2 and cortex-3 start only after cortex-1 runs, so that 2 and 3 can connect to cortex-1.
Previously, cortex-1, 2 and 3 were started at the same time, but if cortex-1 was too slow, cortex-2 was unable to connect to it and fail.
> Fix flaky memberlist test.

- CHANGELOG.md
- pkg/querier/frontend/frontend.go
- pkg/querier/frontend/frontend_test.go
As discussed with @pracucci , This change how the frontend handle cancellation/timeout. 
If the user request/upstream cancellation, then we don't throw a 5xx but a 499 instead (I'm happy to choose another code).
However in case of deadline exceeded/timeout, or unknown error we're sending back a 500.
The reason for this change is because if a user quickly cancel a request (page refresh) before it has time to answer the frontend will register this as an error (500) which I don't think we should.
> Frontend: do not return 500 if the user request cancellation.

- .circleci/config.yml
As there is no good Cassandra mock, the Cassandra index client fixture relies on an actual Cassandra instance, the address of which is passed in via CASSANDRA_TEST_ADDRESSES.   The unit tests are skipped if no such environment variable is passed.
This PR adds a Cassandra container so those unit are no longer skipped.
> Run a Cassandra container so the Cassandra unit tests run.

- .gitignore
- integration/e2e/scenario.go
Otherwise, you get the following error when using docker for mac:
```
alertmanager: docker: Error response from daemon: Mounts denied:
alertmanager: The path /var/folders/g5/3pb5_td927l61zm9xfmmtcp80000gn/T/e2e_integration_test388308663
alertmanager: is not shared from OS X and is not known to Docker.
alertmanager: You can configure shared paths from Docker -> Preferences... -> File Sharing.
alertmanager: See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
alertmanager: .
alertmanager: time="2020-02-19T10:32:42Z" level=error msg="error waiting for container: context canceled"
```
> Use current directory for integration test shared dir.

- pkg/chunk/chunk.go
- pkg/chunk/chunk_test.go
Adds support for slicing chunks for the given time range.
`Chunk.Slice` method iterates through the data to build a new chunk out of it with the same encoding.
This PR lays foundation for #2103 and helps reduce its size.
**Checklist**
> chunk slice support

- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/s3_storage_client.go
- pkg/chunk/azure/blob_storage_client.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/composite_store.go
- pkg/chunk/composite_store_test.go
- pkg/chunk/gcp/bigtable_index_client.go
- pkg/chunk/gcp/bigtable_object_client.go
- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/inmemory_storage_client.go
- pkg/chunk/local/boltdb_index_client.go
- pkg/chunk/local/fs_object_client.go
- pkg/chunk/objectclient/client.go
- pkg/chunk/schema.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
- pkg/chunk/series_store.go
- pkg/chunk/storage_client.go
This is another smaller PR from #2103 which includes just the functionality to allow deletion of chunks and seriesIDs(series store only) for the given time range.
This includes the implementation for just `filesystem` object store and `boltdb` index store. Separate PRs will follow for other stores. 
**Checklist**
> delete chunk and seriesIDs

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- docs/configuration/config-file-reference.template
- integration/api_config_test.go
- pkg/cortex/modules.go
- pkg/ring/lifecycler.go
- pkg/util/flagext/day.go
- pkg/util/flagext/day_test.go
- pkg/util/flagext/url.go
- pkg/util/flagext/url_test.go
> Add /config handler which exposes the current YAML config of cortex.

- pkg/alertmanager/alertmanager.go
> Remove tight loop from alertmanager init()

- development/tsdb-blocks-storage-s3/config/cortex.yaml
- development/tsdb-blocks-storage-s3/docker-compose.yml
- integration/alertmanager_test.go
- integration/api_config_test.go
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/e2e/util.go
- integration/e2ecortex/service.go
- integration/e2ecortex/services.go
- integration/getting_started_single_process_config_test.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/integration_memberlist_single_binary_test.go
- integration/query_frontend_test.go
- integration/util.go
While reviewing the PR #1878 it popped up that the PR may change the `query-frontend` config requirements (discussion still on-going). This made me realise that we don't have any integration test running with the config instead of CLI flags.
This PR is a first step to ease writing tests where Cortex gets started with a config file (CLI flags are still used for some overrides).
In particular:
- Added `query-frontend` support to local `tsdb-blocks-storage-s3` dev env
- Introduced `CortexService` to have cleaner integration tests 
- Added to `writeFileToSharedDir()` the ability to create the path of directories
- Enhanced `query-frontend` tests to run with config file too
N/A
**Checklist**
> Add config file support to integration tests

- .circleci/config.yml
- integration/README.md
- integration/alertmanager_test.go
- integration/api_config_test.go
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/e2e/scenario_test.go
- integration/e2e/service_test.go
- integration/getting_started_single_process_config_test.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/integration_memberlist_single_binary_test.go
- integration/package.go
- integration/query_frontend_test.go
- integration/util.go
**What this PR does**: This PR adds `integration` tag to Cortex integration tests, so that they don't run by default when doing simple `go test ./...` in main Cortex directory.
To run integration tests too, one needs to use `-tags=integration` flag to `go test`.
**Checklist**
> Added integration build tag to integration tests.

- Makefile
- docs/configuration/config-file-reference.md
- docs/configuration/config-file-reference.template
- docs/operations/blocks-storage.md
- docs/operations/blocks-storage.template
- pkg/compactor/compactor.go
- pkg/cortex/cortex.go
- pkg/storage/tsdb/backend/s3/config.go
- pkg/storage/tsdb/config.go
- tools/doc-generator/main.go
- tools/doc-generator/writer.go
Currently, the blocks storage config documented in `docs/operations/blocks-storage.md` was manually generated. This is error prone and drifted a bit.
In this PR I'm introducing the templating support to the doc generator tool, switching the config file reference specified in `docs/operations/blocks-storage.md` to the auto-generated one as well.
Notes:
- Blocks storage config has been added to the config file reference doc too
- The changes to the doc generator tool have been made to try to keep the changeset small, but some refactoring would be probably required at some point
_Please enable "hide whitespace changes" when reviewing this._
N/A
**Checklist**
> Generate blocks storage config file doc

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- docs/operations/blocks-storage.md
- integration/configs.go
- integration/querier_test.go
- pkg/querier/block_store.go
- pkg/querier/block_store_metrics.go
- pkg/querier/bucket_store_metrics_test.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/index_cache.go
In this PR I propose to shift to a shared in-memory index cache for queriers with blocks storage. The problem with per-tenant caches is that the total max cache size linearly increase with the number of tenants, while with a single cache it's easier to keep the max memory used under control.
Fixes #2069
**Checklist**
> Shared in-memory index cache for queriers with blocks storage

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- pkg/chunk/cache/background.go
- pkg/chunk/cache/cache_test.go
Improves parallelism and observability of the background cache writes.
Fixes #2134
**Checklist**
> Break background cache writes into batches of 100

- pkg/ingester/errors.go
- pkg/ingester/index/index.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/user_state.go
This is roughly what I was suggesting at #2000 to warn future maintainers.
~I have left (what I assume is) the bug unchanged.~
I have changed the way errors are wrapped to make it clearer how we avoid retaining references to unsafe data inside errors.
> Comment unsafe memory usage in ingester push path

- CHANGELOG.md
- go.sum
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_metrics.go
- pkg/alertmanager/alertmanager_metrics_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/cortex/modules.go
- pkg/util/metrics_helper.go
- pkg/util/metrics_helper_test.go
Moved from #2116 because integration tests don't work for Grafana org repo PRs due to `NOQUAY` being set as an environment variable.
This PR takes advantage of the `util.MetricFamiliesPerUser` struct to provide per-tenant Alertmanager metrics.
Fixes #1631 
**Checklist**
> add per-tenant alertmanager metrics

- docs/governance/how-to-add-a-maintainer.md
- tools/website/web-pre.sh
- Add governance to the doc website
- Add "How to add a maintainer" to doc
This will add a new "Governance" menu item in the website. The "Governance" index page is the `GOVERNANCE.md` content, while there's a sub-page "How to add a maintainer":
N/A
**Checklist**
> Documented how to add a new maintainer

- docs/governance/how-to-add-a-maintainer.md
Added Docker Hub invitation to the 'How to add a maintainer' checklist.
N/A
**Checklist**
> Updated 'How to add a maintainer' doc

- cmd/query-tee/proxy.go
When the `query-tee` is deployed with a load balancer in front of it, it needs a route that return 200 for health checking.
N/A
**Checklist**
> Added / support to query-tee for health checking

- pkg/chunk/aws/dynamodb_table_client_test.go
- pkg/chunk/aws/metrics_autoscaling_test.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/table_manager.go
- pkg/chunk/table_manager_test.go
- pkg/chunk/testutils/testutils.go
- pkg/cortex/modules.go
Expose metrics with count of the number of errors in the creation and deletion of tables.
It is the same code from PR #1409 which got closed due to accidental deletion of its branch.
> add metrics for number of failures in creation and deletion of tables

- pkg/ingester/wal_test.go
#2105 got merged recently which was using `Shutdown` method from `Ingester` in tests. The `Shutdown` method was removed recently by Services PR merged before that. This PR fixes the broken tests.
**Checklist**
> fix broken tests in wal

- integration/e2ecortex/storage.go
- integration/querier_test.go
- pkg/querier/block.go
- pkg/storage/tsdb/backend/s3/bucket_client.go
While testing the blocks storage with the `query-tee` I've realized that if a query fails because of missing block, the query API returns `422` status code. The logic is deep into Prometheus API engine and, in order to have the API returning `500`, we need the error to be a `promql.ErrStorage`.
This PR is 2 lines of code for a fix, and few hundreds for an integration test (because I didn't find a safe way to test it just with unit tests, given the logic is deep into Prometheus).
N/A
**Checklist**
> Fixed HTTP status code on failed query because missing block

- .circleci/config.yml
- docs/contributing/how-to-upgrade-golang-version.md
- go.mod
In this PR:
- Upgrade Golang version used in integration tests
- Bump minimum go version from `1.12` to `1.13`
- Added doc how to upgrade Golang version
N/A
**Checklist**
> Upgrade Golang version used in integration tests

- pkg/ingester/ingester.go
- pkg/ring/flush.go
- pkg/ring/lifecycler.go
- pkg/ring/lifecycler_test.go
- pkg/ruler/lifecycle.go
Lifecycler was recently refactored (by #2166), which unfortunately breaks some expectations in Loki. This PR makes fixing Loki possible.
Before #2166, [Lifecycler's `Shutdown` method](https://github.com/cortexproject/cortex/blob/f0fb4b7eb50a60b848b6b685c29b445be15134ac/pkg/ring/lifecycler.go#L330) called `flushTransferer.StopIncomingRequests()` and only then stopped lifecycler's loop.
After #2166, this has been modified. Lifecycler is now stopped via `StopAsync` method (through embedded BasicService), which cancels context used by `loop()` method, which makes `loop()` exit. [`stopping()` method](https://github.com/cortexproject/cortex/blob/9c1f44d0900649f9a78de1b796fdd65df76d250e/pkg/ring/lifecycler.go#L428) is called afterwards. This method still calls …
> Move call of stopIncomingRequests before lifecycler shutdown.

- .gitattributes
This excludes all generated proto files from the Pull Request Size bot we run on this repo. #2226 is marked XXL despite most of the LOC being generated files. This PR will ensure the PR Bot ignores generated protos.
> exclude generated protos from PR size bot

- cmd/cortex/main.go
- pkg/cortex/cortex.go
Cortex used to exit with status code 1 before (when its "Stop" method reported error). Now it exits with code 1 if it fails to start, or any service fails during running or stopping state.
> Exit with status code 1 if Cortex fails to start or any service fails

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
**What this PR does**: This PR moves WAL replays into Ingester's Starting method. Ingester cannot operate until these are finished, so all public methods now check if Ingester is in Running or Stopping state. Why Stopping? Because querying methods still work while it is stopping.
**Checklist**
/cc @codesome
> Move WAL replays (chunks / tsdb) into ingester's Starting state.

- CONTRIBUTING.md
- Makefile
- RELEASE.md
- k8s/alertmanager-dep.yaml
- k8s/configs-dep.yaml
- k8s/distributor-dep.yaml
- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/query-frontend-dep.yaml
- k8s/ruler-dep.yaml
- k8s/table-manager-dep.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
The manifests in /k8s don't have tag in the cortex image, and in quay.io/ortexproject/project there is no tag `latest`. Here add the tag v0.2.0 so users can deploy directly.
> add tags in manifests

- pkg/alertmanager/multitenant.go
- pkg/chunk/purger/purger.go
- pkg/chunk/table_manager.go
- pkg/compactor/compactor.go
- pkg/cortex/module_service_wrapper.go
- pkg/cortex/modules.go
- pkg/cortex/server_service.go
- pkg/distributor/distributor.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/querier/block.go
- pkg/querier/block_store.go
- pkg/ring/lifecycler.go
- pkg/ruler/ruler.go
- pkg/util/runtimeconfig/manager.go
- pkg/util/services/basic_service.go
- pkg/util/services/basic_service_test.go
- pkg/util/services/services_test.go
**What this PR does**: While working on a change to remove `os.Exit` from lifecycler, I came across a need to know (in stopping fn) whether lifecycler's running function has failed or not. This PR adds `failureCase` parameter to the stopping function. Since stopping function is used at many different places in Cortex now, this PR changes all those places, but code logic is unchanged – failureCase is simply ignored everywhere (for now).
**Checklist**
> services: add failure case to Stopping function

- .gitattributes
Following what @jtlisi did in #2227, I would suggest to not consider the whole `vendor/` when calculating the PR size.
N/A
**Checklist**
> Exclude vendor/ from PR size

- pkg/querier/queryrange/retry.go
- pkg/querier/queryrange/roundtrip.go
Extract `RetryMiddlewareMetrics` from `NewRetryMiddleware`. This makes it possible to share same  metrics between multiple instances of "retry middleware". (Loki does this)
> Extract RetryMiddlewareMetrics from NewRetryMiddleware.

- CHANGELOG.md
- docs/configuration/single-process-config.yaml
- pkg/chunk/cache/cache_test.go
- pkg/chunk/encoding/factory.go
- Make spread flush the default using the example single binary config (not the flag)
- Make bigchunk the default encoding in the code
Fixes #2202 
**Checklist**
> Update the default configs for spread flush and bigchunks

- docs/configuration/config-file-reference.md
- docs/operations/blocks-storage.md
- pkg/storage/tsdb/config.go
@weeco correctly pointed that that the doc for `-experimental.tsdb.retention-period` is incorrect: it mentions "ingesters" while it should be "queriers".
N/A
**Checklist**
> Fixed typo in -experimental.tsdb.retention-period doc

- CHANGELOG.md
- docs/configuration/schema-config-reference.md
- docs/guides/aws-specific.md
- docs/guides/running.md
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/e2e/util.go
- k8s/ingester-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- k8s/schema-config.yaml
- k8s/table-manager-dep.yaml
- pkg/chunk/schema_config.go
- pkg/cortex/modules.go
Also rename the schema config file flag to something sane.
Fixes #2208 
**Checklist**
> Remove support schema flags, only use config file.

- pkg/distributor/query.go
Fixed `cortex_distributor_ingester_query_failures_total` metric if an error occurr in the `stream.Recv()`.
N/A
**Checklist**
> Fixed cortex_distributor_ingester_query_failures_total metric if an error occurr in the stream.Recv()

- pkg/distributor/query.go
- pkg/ingester/client/cortex_mock_test.go
- pkg/ingester/client/cortex_util.go
- pkg/ingester/client/cortex_util_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/transfer.go
- pkg/ingester/transfer_test.go
- pkg/util/grpc/util.go
- vendor/github.com/weaveworks/common/grpc/cancel.go
- vendor/google.golang.org/grpc/test/bufconn/bufconn.go
- vendor/modules.txt
Today I investigated the following warning log we see quite frequently on high-traffic clusters:
```
level=warn ts=2020-03-10T09:19:42.839335323Z caller=grpc_logging.go:54 method=/cortex.Ingester/QueryStream duration=981.401µs err="rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" msg="gRPC\n"
```
After some investigating, I found out this happens whenever a gRPC server calls `Send()` on a closed stream because the context has been closed (canceled / deadline exceeded). In this PR I propose to wrap the `Send()` in order to check whether the context has an error and, if so, returning that error instead of the cryptic `Send()` error.
After this PR changes the log is the following:
```
level=debug …
```
> Ingester gRPC servers should return context error if any

- CHANGELOG.md
- pkg/cortex/cortex.go
- pkg/cortex/modules.go
- pkg/querier/frontend/frontend_test.go
- pkg/querier/frontend/worker.go
Issue: The query frontend worker in the querier was previously (before this PR) started in the init function. The side effect was that it started pulling jobs from the queue before the queryable is ready. This means queries fail during the rollout, until the queryable is ready.
This PR changes that. Frontend worker is now a service, and it is only started after all Querier module dependencies are started. This includes queryable.
**Checklist**
> Converted frontend worker to a service.

- pkg/cortex/modules.go
- pkg/cortex/server_service.go
- pkg/cortex/server_service_test.go
**What this PR does**: this PR removes Cortex-specific bits from NewServerService, so that it can be reused by Loki. Config and index handlers are now simple functions.
**Checklist**
> Make NewServerService generic again

- CHANGELOG.md
- docs/architecture.md
- docs/configuration/config-file-reference.md
- docs/operations/blocks-storage.md
- docs/operations/blocks-storage.template
- pkg/storage/tsdb/backend/filesystem/bucket_client.go
- pkg/storage/tsdb/backend/filesystem/config.go
- pkg/storage/tsdb/bucket_client.go
- pkg/storage/tsdb/config.go
- vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go
- vendor/modules.txt
Add support for TSDB blocks to be saved to the local filesystem via the implementation which already exists for this in Thanos.
Used #2083 as a template
**Checklist**
Signed-off-by: Edward Welch <edward.welch@grafana.com>
> Experimental TSDB: Add support for local filesystem backend

- pkg/chunk/aws/s3_storage_client.go
- pkg/chunk/gcp/gcs_object_client.go
This PR implements the `DeleteObject` method for both the S3 and GCS object clients. It also ensures the generic `chunk.ErrStorageObjectNotFound` error is returned for both of these clients in the get and delete functions to allow for more refined error handling.
> 404 handling and DeleteObject implementations (GCS & S3)

- .circleci/config.yml
- integration/README.md
- integration/alertmanager_test.go
- integration/api_config_test.go
- integration/backward_compatibility_test.go
- integration/chunks_storage_backends_test.go
- integration/configs.go
- integration/e2e/scenario_test.go
- integration/e2e/service.go
- integration/e2e/service_test.go
- integration/getting_started_single_process_config_test.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/integration_memberlist_single_binary_test.go
- integration/metrics_test.go
- integration/querier_test.go
- integration/query_frontend_test.go
- integration/util.go
- pkg/alertmanager/multitenant.go
- pkg/chunk/table_manager.go
Hello Busy Cortexianians :wave: 
This is kind of tricky as logically sum of non-existing is 0, but also it's super easy to make a
mistake and put the wrong metric and sneakily introduce bug... so I think being strict makes sense here? WDYT?
Alternative is to extend `isExpected func(sums ...float64) bool` to something like `isExpected func(exists bool, sums ...float64) bool`
but I think the proposed simplification makes sense here. (:
Also, I think the e2e base unit test should be run all the time not only on integration build,
remove the tag from those in the main e2e core package.
cc @pstibrany @pracucci 
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
> e2e: Fixed WaitSumMetrics to fail on non existing metric

- pkg/distributor/query.go
- pkg/distributor/query_test.go
- pkg/querier/duplicates_test.go
**What this PR does**: this PR adds deduplication of streamed samples coming from different ingesters that use blocks storage.
Merge function stores result into first slice to avoid extra allocations if not needed. We can use more straightforward merge implementation.
**Checklist**
> Deduplicate streamed samples from ingesters using blocks storage

- pkg/cortex/cortex.go
- pkg/cortex/cortex_test.go
- pkg/cortex/module_service_wrapper.go
- pkg/flusher/flusher.go
- pkg/util/errors.go
- pkg/util/module_service.go
This PR moves `moduleServiceWrapper` from Cortex main package to util package. It is now available via `NewModuleService` function, which is also bit more generic, to make it reusable between projects. (Going to use it in Loki)
**Checklist**
> Make module service wrapper reusable from other projects

- CHANGELOG.md
- docs/configuration/config-file-reference.md
- docs/configuration/config-file-reference.template
- docs/configuration/schema-config-reference.md
- docs/configuration/single-process-config.md
- docs/configuration/single-process-config.yaml
- integration/configs.go
- pkg/chunk/schema_config.go
- pkg/chunk/schema_config_test.go
- pkg/chunk/table_manager.go
- pkg/cortex/cortex.go
- tools/doc-generator/parser.go
Support 1w and 1y for retention and table period. Will change docs and add changelog entries if this approach looks good as opposed to #2244 
**Checklist**
> Support 1w, 1y for retention and table period take 2

- CHANGELOG.md
> Update breaking change around mixed time units

- docs/configuration/config-file-reference.md
- tools/doc-generator/main.go
- tools/doc-generator/parser.go
- tools/doc-generator/writer.go
The issue #2253 made me think we could actually list the CLI flags `<prefix>` for each root config block which does have multiple prefixes. This PR does not solve #2253 (that issue mention the caching doc) but applies a similar concept to the config file reference doc.
N/A
**Checklist**
> Reference CLI flags <prefix> in generated doc

- .circleci/config.yml
- Makefile
- build-image/Dockerfile
A common mistake (I did it too) is to import `github.com/bmizerany/assert` instead of `github.com/stretchr/testify/assert`. In this PR I've introduced `faillint` as further lint step to ensure no blacklisted package is imported. Of you try to use `github.com/bmizerany/assert` the linter will fail, suggesting which package should be used instead:
```
/go/src/github.com/cortexproject/cortex/pkg/storage/tsdb/config_test.go:8:2: package "github.com/bmizerany/assert" shouldn't be imported, suggested: "github.com/stretchr/testify/assert"
```
`faillint` will also be useful in the future to enforce some design patterns (ie. once completed the Prometheus metrics refactoring, we'll be able to forbid the usage of `prometheus.NewGauge()` in favor of …
> Introduce faillint in the CI workflow

- CHANGELOG.md
- pkg/chunk/aws/dynamodb_storage_client.go
- pkg/chunk/aws/s3_storage_client.go
We will connect many times in parallel to the same DynamoDB server, and with default settings Go will close and re-open connections; see https://github.com/golang/go/issues/13801
Raise MaxIdleConnsPerHost to avoid this.
**Checklist**
> Allow more connection reuse for DynamoDB and S3 calls

- pkg/chunk/cache/memcached.go
The `keys requested`, `keys found` and any error messages were going on the parent span which, when you turn on batching, makes them hard to interpret.
> Attach memcached span logs to the correct span

- CHANGELOG.md
- pkg/ring/kv/etcd/etcd.go
Today we experienced a (likely short) outage in one of our production clusters, due to some distributors unable to operate on etcd. The distributors where continuously logging this:
```
level=error ts=REDACTED caller=etcd.go:64 msg="error getting key" key=prom_ha/REDACTED/REDACTED err="context canceled"
```
After a long investigation, it turned out the issue has been caused by a dead TCP connection between the etcd client and the server which wasn't gracefully closed. The problem is that when the TCP connection is stuck (ie. the VM where etcd is running dies), the client will detect it only once the TCP keepalive will expire which (by default) is about 2 hours ([some ref](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html)).
Likely, the etcd client …
> Fixed etcd client keepalive settings

- .circleci/config.yml
- integration/backward_compatibility_test.go
- integration/chunks_storage_backends_test.go
- integration/e2e/db/db.go
- integration/e2e/service.go
- integration/e2ecortex/service.go
- integration/e2ecortex/services.go
Adds support of cassandra in integration tests
I have used an optimized docker image for integration tests. Here is the repo for it https://github.com/saidbouras/cassandra-docker-unit.
There is also a community maintained docker image https://hub.docker.com/_/cassandra, which is slow to start and takes about 10-15 additional seconds.
Cassandra version in image built by saidbouras is 3.11 while community build docker has 3.11.6 which I feel is okay. We can use community maintained docker image as well if we want if that is not okay.
Since Cassandra is slow to start and does not have an HTTP readiness probe, I have added support for command based probe. An example of readiness probe for Cassandra can be found here: …
> support for cassandra in integration tests

- CHANGELOG.md
- pkg/chunk/cache/background.go
- pkg/chunk/cache/cache.go
- pkg/chunk/cache/fifo_cache.go
- pkg/chunk/cache/memcached.go
- pkg/chunk/cache/memcached_client.go
- pkg/chunk/cache/redis_cache.go
- pkg/chunk/cassandra/storage_client.go
- pkg/chunk/chunk_store.go
- pkg/chunk/schema_config.go
- pkg/chunk/storage/factory.go
- pkg/compactor/compactor_ring.go
- pkg/cortex/cortex.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_ring.go
- pkg/distributor/ha_tracker.go
- pkg/flusher/flusher.go
- pkg/ingester/client/pool.go
- pkg/ingester/ingester.go
- pkg/ingester/wal.go
- pkg/ring/kv/client.go
- pkg/ring/lifecycler.go
- pkg/ring/ring.go
- pkg/ruler/api.go
- pkg/ruler/legacy_rulefmt/rulefmt.go
- pkg/ruler/ruler_ring.go
This PR removes all the occurences of omitempty
from structs.
Signed-off by Jay Batra <jaybatra73@gmail.com>
Fixes #2173
**Checklist**
> Removes all the occurences of omitempty

- .circleci/config.yml
- integration/e2e/logger.go
- integration/e2e/scenario.go
- integration/e2e/service.go
We have some flaky integration tests in `query_frontend_test.go`. I can't understand the root cause but I've the feeling it's a timing issue. In this PR I'm adding a very simple logger to prefix each log with the time, so that we can have a better idea where the time is being spent when running in CI.
An example of the tests output is:
```
=== RUN   TestQueryFrontendWithChunksStorageViaConfigFile
10:00:47 Starting consul
10:00:48 consul: ==> Starting Consul agent...
10:00:48 consul: ==> Consul agent running!
10:00:48 consul: Version: 'v0.9.4'
10:00:48 consul: Node ID: 'b67d8cc8-029c-d764-dc65-a7205203b3cd'
10:00:48 consul: Node name: 'consul'
```
N/A
**Checklist**
> Introduced a basic logger to the integration tests framework

- .circleci/config.yml
- RELEASE.md
- integration/backward_compatibility_test.go
Now that Cortex `0.7.0` we can add an integration test to check backward compatibility with that as well, like we had for `0.6.0`.
N/A
**Checklist**
> Added integration test for Cortex 0.7.0 backward compatibility

- development/tsdb-blocks-storage-s3-single-binary/.dockerignore
- development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml
- development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml
- development/tsdb-blocks-storage-s3/.dockerignore
- development/tsdb-blocks-storage-s3/config/prometheus.yaml
- development/tsdb-blocks-storage-s3/docker-compose.yml
The easiest way to locally run Cortex with the experimental blocks storage is using the development setup and running `./development/tsdb-blocks-storage-s3/compose-up.sh`. This is also the same way I use to locally run Cortex while developing it.
A missing thing is that the local dev setup doesn't scrape Cortex metrics itself, so it's not easy to manually test exported metrics. In this PR I'm setting up Prometheus to scrape Cortex metrics from containers and push them to Cortex via remote write.
Notes:
- I've added some `.dockerignore` to speed up building the Cortex container on OSX if the volumes are big (because the entire content of shared dirs need to be transferred to the Docker context if not ignored)
N/A
**Checklist**
> Add Prometheus to local dev env setup

- integration/querier_test.go
- integration/query_frontend_test.go
- pkg/chunk/cache/cache.go
- pkg/chunk/cache/memcached_client.go
> Make each DNS provider register a diff metric

- pkg/testexporter/correctness/runner.go
- pkg/testexporter/correctness/runner_test.go
Adds a new flag to test-exporter to restrict the range to a certain time in the past: `-test-query-since`
There is no test-exporter documentation so I made no changes.  Additionally I did not feel this was worth a changelog entry, but I would be glad to add one if we'd like it.
**Checklist**
> Add ability for test-exporter to only query a specified duration in the past

- CHANGELOG.md
- Makefile
- docs/configuration/config-file-reference.md
- integration/alertmanager_test.go
- integration/api_ruler_test.go
- integration/backward_compatibility_test.go
- integration/chunks_storage_backends_test.go
- integration/configs.go
- integration/e2ecortex/client.go
- integration/e2ecortex/services.go
- integration/getting_started_single_process_config_test.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- integration/metrics_test.go
- integration/querier_test.go
- integration/query_frontend_test.go
- pkg/chunk/aws/fixtures.go
- pkg/chunk/aws/s3_storage_client.go
- pkg/chunk/azure/blob_storage_client.go
- pkg/chunk/gcp/fixtures.go
- pkg/chunk/gcp/gcs_object_client.go
- pkg/chunk/storage/factory.go
- pkg/cortex/modules.go
- pkg/ruler/api.go
- pkg/ruler/ruler.go
- pkg/ruler/rules/objectclient/rule_store.go
- pkg/ruler/rules/store.go
- pkg/ruler/storage.go
- pkg/ruler/store_mock_test.go
This PR adds an API to the ruler service based on this design document (https://docs.google.com/document/d/1gNKiC5L_zWQ4GGgtdhJJ6FnaZXyJJBvdGTUmF0wgEFg/edit?usp=sharing)
* It creates a generic storage client for rules based on our `chunk.ObjectClient` interface
* The delimiter was made a configurable option for the object storage clients to make this possible. The delimiter is set at the construction of the object storage client
* A ruler integration test was added that ensures a rule group can be set, is running in a Prometheus manager, and can be deleted
* A ruler address was added to the integration test cortex client
Related #1547 #1244
**Checklist**
> Ruler API and ObjectStore Backend

- integration/asserts.go
- pkg/alertmanager/alertmanager_metrics_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
In this PR I've switched `pkg/alertmananger` metrics to `promauto.With(reg)`.
N/A
**Checklist**
> Switched pkg/alertmanager metrics to promauto

- pkg/chunk/cache/cache_test.go
- pkg/chunk/cache/memcached_client.go
- pkg/chunk/cache/mock.go
- pkg/chunk/chunk_store.go
- pkg/chunk/chunk_store_test.go
- pkg/chunk/chunk_store_utils.go
- pkg/chunk/composite_store.go
- pkg/chunk/series_store.go
- pkg/chunk/storage/factory.go
- pkg/chunk/testutils/testutils.go
Fixes #2302 
@bboreham Can you test if this actually fixes the issue?
> Fix multiple registrations with multi schema

- pkg/cortex/modules.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
To continue the effort of picking the `prometheus.Registerer` as function input and not passed as part of the config, I've removed `metricsRegisterer` from `querier.Config`.
N/A
**Checklist**
> Removed metricsRegisterer from querier config

- integration/asserts.go
- integration/configs.go
- integration/ingester_flush_test.go
- integration/ingester_hand_over_test.go
- pkg/ingester/flush.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_v2.go
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
- pkg/ingester/series.go
- pkg/ingester/transfer.go
- pkg/ingester/transfer_test.go
- pkg/ingester/user_state.go
- pkg/ingester/wal.go
Following the work related to https://github.com/cortexproject/cortex/issues/2204 to get rid of global metrics and registerer, in this PR I've migrated `pkg/ingester` metrics to `promauto.With(registerer)`.
Few notes:
- There's still a global metric in `pkg/ingester/client` which I will address in a separate PR
- Not much happy with the path followed for the WAL and `memorySeries`. The problem is that the initial design doesn't look much clean in regards of global variables and I had to deal with that in order to keep the changeset small (but I admit there's much room for improvement design-wise there)
N/A
**Checklist**
> Switch pkg/ingester to promauto.With(reg)

- docs/proposals/receiving_metadata.md
**What this PR does**: Introduces a proposal for a feature of Cortex
Hi everyone 👋,
Loving the work done on Cortex! As of lately, I've been trying to do some work on Prometheus that enables users to consume the metadata of their metrics. Now that the work there is done (or close to 🤞), I would like to discuss the possibility of bringing this into cortex too.
I have briefly discussed this with @pracucci, and he kindly asked to kick-start the discussion in the form of a proposal so that everyone can get involved. I know that at some point, I have also briefly discussed this with @tomwilkie, so I've added them both as reviewers, but if anyone else has comments, they're very welcome.
I understand the proposal is a bit light on the details, this is intentional, and it was encouraged upon me. …
> Proposal: Implement Prometheus Metadata API

- CHANGELOG.md
- docs/configuration/arguments.md
- docs/configuration/config-file-reference.md
- docs/guides/caching.md
- docs/guides/running.md
- k8s/ingester-dep.yaml
- k8s/memcached-dep.yaml
- k8s/querier-dep.yaml
- k8s/ruler-dep.yaml
- pkg/chunk/cache/background.go
- pkg/chunk/cache/memcached_client.go
- pkg/chunk/chunk_store.go
Fixes https://github.com/cortexproject/cortex/issues/2191 #553 
**Checklist**
> Prefix chunks cache flags.

- pkg/querier/block.go
- pkg/querier/block_store.go
- pkg/querier/blocks_bucket_store_inmemory_server.go
Currently, the querier starts a gRPC server binded to localhost just to talk to the Thanos `BucketStore` (which is running within the same process). In this PR I'm proposing to get rid of this hack and just use a mocked `storepb.Store_SeriesServer` buffering the response `storepb.Series` in memory (which is what we were already doing anyway).
Notes:
- I haven't added new tests cause the existing ones should already cover it.
- `Info()`, `LabelNames()` and `LabelValues()` have been removed because unused (metadata is fetched from ingesters only, `Info()` is a Thanos-specific thing)
N/A
**Checklist**
> Removed gRPC server to communicate between querier and BucketStore

- development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
- development/tsdb-blocks-storage-s3/docker-compose.yml
- docs/configuration/config-file-reference.md
- docs/operations/blocks-storage.md
- docs/operations/blocks-storage.template
- pkg/cortex/cortex.go
- pkg/cortex/modules.go
- pkg/ring/ring.go
- pkg/storegateway/gateway.go
- pkg/storegateway/gateway_http.go
- pkg/storegateway/gateway_ring.go
- pkg/storegateway/gateway_ring_test.go
As a first step to build the blocks sharding for the read path (#2315), in this PR I'm introducing the scaffolding for the `store-gateway` service.
Notes:
- In order to keep PRs easier to review and quicker to iterate on, I propose to build the sharding in incremental PRs
- The `store-gateway` runs within the `all` target (only when the blocks storage is used) because it will be essential for the querier
N/A
**Checklist**
> Store gateway service scaffolding

- integration/backward_compatibility_test.go
**What this PR does**: This PR fixes `TestBackwardCompatibilityWithChunksStorage` -- it actually starts first ingester with old image, as comment suggests.
> Fix TestBackwardCompatibilityWithChunksStorage: Start first ingester with old image.
