Makefile, docs/contributing/how-to-update-the-build-image.md
**What this PR does**: This PR adds `fetch-build-image` target to Makefile, for fetching latest build image. This can be faster than building the image locally. Image can still be built locally by running `rm build-image/.uptodate && make build-image/.uptodate` as usual.
**Checklist**
=> Added target to fetch build image, instead of building it locally.

CHANGELOG.md, pkg/cortex/runtime_config.go, pkg/cortex/runtime_config_test.go
Make sure that omitted or missing ingester configuration that is
part of runtime configuration is treated as `nil` instead of an
empty object. This fixes an issue where the settings in the empty
object were overriding global default ingester limits.
Fixes #4228
**Checklist**
=> Ensure missing runtime ingester settings are nil

CHANGELOG.md, docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/configuration/single-process-config-blocks-tls.yaml, docs/configuration/single-process-config-blocks.yaml, docs/configuration/single-process-config.md, docs/configuration/single-process-config.yaml, integration/ruler_test.go, pkg/cortex/modules.go, pkg/cortex/modules_test.go, pkg/ruler/rulestore/config.go, pkg/ruler/rulestore/config_test.go
In #3805 we've introduced `-ruler-storage.*` and then we depreacted the old `-ruler.storage`.
We have a check in `initRulerStorage()` to not start the ruler at all when Cortex has been started in single-binary mode and the ruler hasn't been configured. However, we forgot to add a check in the new ruler storage config, which should be fixed by this PR.
Fixes #4239
**Checklist**
=> Fix ruler storage single binary mode

docs/configuration/v1-guarantees.md
After cutting Cortex 1.9 we've introduced few new querier limits. Since we're still working on it and we may soon change `-querier.max-fetched-chunks-per-query` (see #4255), in this PR I'm proposing to mark them as experimental until the config will be stable.
N/A
**Checklist**
=> Mark new querier limits as experimental

CHANGELOG.md, pkg/querier/blocks_store_replicated_set_test.go, pkg/storegateway/gateway_ring.go
This PR fixes the issue described in #4224.
When scaling up a number of store-gateways >= replication factor, if a block (+ its replicas) belongs to all JOINING instances, then the query will fail with the "at least 1 healthy replica required, could only find 0" error until at least 1 of these store-gateway instances is ACTIVE.
The issue is caused by `storegateway.BlocksRead` operation because it doesn't extend the replication set for non-ACTIVE instances, while it should (given we do extend it in the `BlocksSync` operation to keep blocks loaded in the original instance until the new instance holding that block is ACTIVE).
I've been able to manually reproduce it in a testing Cortex cluster, while I can't reproduce it anymore after this PR change.
**Which issue(s) …
=> Fix queries failing right after scaling up store-gateways

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/util/validation/limits.go
**What this PR does**: This PR exposes new alertmanager limit: number of active dispatcher groups in Alertmanager.
This PR builds on top of #4237, and will be rebased once #4237 is merged.
**Checklist**
=> Dispatcher groups limits

CHANGELOG.md, integration/integration_memberlist_single_binary_test.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
If configuration is not explicitly given for RetransmitMult (via
`-memberlist.retransmit_factor`), then it is intended to be picked up
from `DefaultLANConfig`. However, though the correct value was being
used to configure `memberlist` itself, zero would be passed into the
`TransmitLimitedQueue` used for broadcasting ring updates. This
essentially means that ring updates are only ever gossiped once.
Fixes #4010 (unconfirmed)
**Checklist**
=> Fix default memberlist configuration value for RetransmitMult.

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ring/kv/etcd/etcd.go
To use etcd with user & password when it should auth
=> Added etcd username and userpassword from config

pkg/querier/batch/batch.go, pkg/querier/iterators/chunk_merge_iterator.go
While reviewing #4218 I've noticed `iteratorAdapter` comments says it implements `storage.SeriesIterator` but, after many refactoring iterations in Prometheus, it currently implements `chunkenc.Iterator`. This PR fixes the comments accordingly.
N/A
**Checklist**
=> Chore: fix chunkenc.Iterator comment

docs/configuration/arguments.md, docs/configuration/config-file-reference.md, pkg/chunk/storage/factory.go
In this PR I'm addressing the feedback received in https://github.com/cortexproject/cortex/pull/4268#issuecomment-856942861.
N/A
**Checklist**
=> Updated doc about chunks storage deprecation

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/ingester_v2.go, pkg/ingester/user_state.go, pkg/ingester/user_state_test.go
**What this PR does**: This PR adds new option `-ingester.ignore-series-limit-for-metric-names` to ignore specific metric names when checking series-per-metric limits.
This is useful under some very specific scenarios, when small number of metric names is used for ingesting series from non-Prometheus system. This is unlikely to be used in generic Cortex configurations.
**Checklist**
=> Added option to ignore specific metrics when checking max-series-per-metric limit.

CHANGELOG.md, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Main problem is currently we cannot strict unmarshal JSON for `Limits` struct using [json.DisallowUnknownFields()](https://golang.org/pkg/encoding/json/#Decoder.DisallowUnknownFields). Because custom `UnmarshalJSON` uses simple `json.Unmarshal()` function. (is it intentional?)
This PR Adds ability to support strict JSON unmarshal for `limits` struct
This is the default behaviour for YAML now.
```
in := `{"unknown_fields": 100}`
l := validation.Limits{}
fmt.Println(yaml.UnmarshalStrict([]byte(in), &l))
// yaml: unmarshal errors:
// line 1: field unknown_fields not found in type validation.plain
```
This PR adds same behaviour if unmarshalled from JSON input as well.
Fixes NA
**Checklist**
=> Add ability to support strict JSON unmarshal for `limits`

pkg/api/api.go, pkg/api/handlers.go
This allows reusing the API handler while swapping out the Distributor
implementation.
In my use case I would like to use NewQuerierHandler with my own queryable, but not provide a "real" distributor implementation.
Signed-off-by: Christian Simon <simon@swine.de>
**Checklist**
- ~[ ] Tests updated~
- ~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~
=> chore: Define interface api.Distributor

pkg/storegateway/gateway_test.go
The `TestStoreGateway_InitialSyncWithWaitRingStability` is flaky and fails with this error:
```
=== RUN   TestStoreGateway_InitialSyncWithWaitRingStability/shuffle_sharding_strategy,_20_gateways,_RF_=_3,_SS_=_3_(bucket_index_enabled_=_false)
gateway_test.go:300: random generator seed: 1624370314782121000
gateway_test.go:347:
Error Trace:	gateway_test.go:347
invalid service state: Failed, expected: Running, failure: unable to start store-gateway dependencies: not healthy, 0 terminated, 1 failed: [register instance in the ring: failed to CAS store-gateway]
Test:       	TestStoreGateway_InitialSyncWithWaitRingStability/shuffle_sharding_strategy,_20_gateways,_RF_=_3,_SS_=_3_(bucket_index_enabled_=_false)
```
We've experienced a …
=> Fix TestStoreGateway_InitialSyncWithWaitRingStability flakyness

pkg/ruler/compat.go, pkg/ruler/compat_test.go
**What this PR does**: This trivial PR exposes some internal ruler types, to ease reuse by other projects.
**Checklist**
=> Expose some ruler types to ease reuse.

pkg/distributor/distributor_test.go
Signed-off-by: Tyler Reid <tyler.reid@grafana.com>
Add replication factor flag to the prepConfig Struct. Use replication factor 2 in TestDistributor_QueryStream_ShouldReturnErrorIfMaxChunkBytesPerQueryLimitIsReached test to make the test stable
**Checklist**
- [ X ] Tests updated
- [-] Documentation added
- [-] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Fix flakey MaxChunkBytesPerQueryLimit test

docs/architecture.md
I understand that any should be all when talking about queries when using the metric name, labels and Tenant ID as the hashing strategy.
**Checklist**
=> Fix any should be all in docs/architecture.md

CHANGELOG.md, pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go
**What this PR does**: This PR fixes a bug when HA tracker in distributor got confused about number of cluster that a user has.
When user stops sending samples for some cluster, and HA tracker removes elected replica from its KV store (implemented in #3809), it wouldn't correctly update in-memory number of clusters that a user has. If user later started to send samples for this cluster again, the cluster would be counted in number of clusters twice, which could eventually lead to user hitting limit for number of HA clusters.
**Checklist**
=> Fix bug with counting of clusters for deleted elected replicas.

CHANGELOG.md, pkg/querier/batch/batch_test.go, pkg/querier/batch/chunk_test.go, pkg/querier/batch/merge.go
We were allocating 24x the number of streams of batches, where each batch holds up to 12 samples.
By allowing `c.batches` to reallocate when needed, we avoid the need to pre-allocate enough memory for all possible scenarios.
Also fix innacurate end time on chunks test data, which was throwing off the benchmark, and add more realistic test sizes - at 15-second scrape intervals a chunk covers 30 minutes, so 1,000 chunks is about three weeks, a highly un-representative test.
Fixes #1195
**Benchmarks**
```
name                                                                                                                             old time/op    new time/op    delta
NewChunkMergeIterator_CreateAndIterate/chunks:_1000_samples_per_chunk: …
```
=> MergeIterator: allocate less memory at first

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/cortex.go, pkg/ring/kv/memberlist/kv_init_service_test.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
Set the defaults for various memberlist configuration values based on
the "Default LAN" configuration. The only result of this change is that
the defaults are now visible and are in the documentation. This also
means that if the default values change, then the changes are visible
in the documentation, where as before they would have gone unnoticed.
Note: The existing behaviour of a zero value is not retained. If a
configuration is explicitly set to zero, the default is not used.
**Checklist**
=> Expose default configuration values for memberlist.

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertmanager_ring.go, pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/ring/model.go, pkg/ring/model_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ruler/ruler_ring.go, pkg/storegateway/gateway_ring.go
This change allows the various ring heartbeat timeouts to be configured
with zero, as a means of disabling the timeout. This is expected to be
used with a separate enhancement to allow disabling heartbeats. When the
heartbeat timeout is disabled, instances will always appear as healthy
in the ring.
**Checklist**
=> Allow setting ring heartbeat timeout to zero to disable timeout check.

docs/_index.md, docs/guides/security.md
I thought it would be good to put a security page into the docs, so that it shows up in a search.
Content is just pointing at other resources.
=> Add a security doc

CHANGELOG.md, pkg/ring/kv/memberlist/kv_init_service.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go, pkg/ring/kv/memberlist/mergeable.go, pkg/ring/kv/memberlist/metrics.go, pkg/ring/model.go
The following profile data was taken from running 50 idle ingesters with
memberlist, with almost everything at default values (5s heartbeats):
```
52.16% mergeBytesValueForKey
+- 52.16% mergeValueForKey
+- 47.84% computeNewValue
+- 27.24% codec Proto Decode
+- 26.25% mergeWithTime
```
It is apparent from the this that a lot of time is spent on the memberlist
receive path, as might be expected, specifically, the merging of the update
into the current state. The cost however is not in decoding the incoming
states (occurs in `mergeBytesValueForKey` before `mergeValueForKey`), but
in fact decoding _current state_ of the value in the store (as it is stored
encoded). The ring state was measured at 123K (50 ingesters), so it makes
sense that decoding could be costly.
This …
=> Optimise memberlist kv store access by storing data unencoded.

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertmanager_ring.go, pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/ring/basic_lifecycler.go, pkg/ring/lifecycler.go, pkg/ruler/ruler_ring.go, pkg/storegateway/gateway_ring.go, pkg/util/time.go, pkg/util/time_test.go
Allow disabling of ring heartbeats by setting relevant options to zero.
Depends on https://github.com/cortexproject/cortex/pull/4342
**Checklist**
=> Allow disabling of ring heartbeats by setting relevant options to zero.

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/integration_memberlist_single_binary_test.go, pkg/ring/kv/memberlist/memberlist_client.go
Allows manually specifying whether memberlist should compress packets
via a new configuration flag: `-memberlist.enable-compression`.
This typically has little benefit for Cortex, as the ring state messages
are already compressed with Snappy, the second layer of compression does
not achieve any additional saving. It's not clear cut whether there
might still be some benefit for internal memberlist messages; this needs
to be evaluated in a environment of some reasonable scale.
**Checklist**
=> Expose configuration of memberlist packet compression.

pkg/alertmanager/multitenant_test.go
Attempt at making SyncOnRingTopologyChanges test more reliable.
It was only waiting one second for the second sync to complete, which is
probably too harsh a deadline than necessary for overloaded systems.
Fixes #4229
**Checklist**
=> Attempt at making SyncOnRingTopologyChanges test more reliable.

pkg/alertmanager/multitenant_test.go
Fix StateReplicationWithSharding_InitialSyncFromPeers flaking.
The test is writing a single silence and  checking a metric which
indicates whether replicating the silence has been attempted yet.
This is so we can check later on that no replication activity
occurs. The assertions later on in the test are passing, but the
first one is not, indicating that the replication doesn't trigger
early enough. This makes sense because the replication is not
synchronous with the writing of the silence.
Fixes #4160
**Checklist**
=> Fix StateReplicationWithSharding_InitialSyncFromPeers flaking.

integration/alertmanager_test.go
Fix integration TestAlertmanagerSharding flaking.
This change will make the test reliable until I can spend more time
investigating. It seems that posting alerts is not fully synchronous
as was expected when writing the test, so the test can be fixed by
waiting for all instances to receive the alert.
Fixes #3927 
**Checklist**
=> Fix integration TestAlertmanagerSharding flaking.

integration/integration_memberlist_single_binary_test.go
Fix integration TestSingleBinaryWithMemberlistScaling flaking.
This appears to be highlighting an issue - raised as #4360.
This change just stops the test flaking until it can be fixed.
Though the change essentially reduces the usefulness of the test, I would rather keep the test running as-is instead of skipping it or changing it too much, to avoid the test rotting.
Fixes #4351 
**Checklist**
=> Fix integration TestSingleBinaryWithMemberlistScaling flaking.

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, build-image/Dockerfile, docs/contributing/how-to-upgrade-golang-version.md
Update go version in build image to 1.16.6. This addresses CVE-2021-34558.
https://github.com/golang/go/issues/47143
This now needs a maintainer to push a build image and update references  (see https://cortexmetrics.io/docs/contributing/how-to-update-the-build-image/)
=> Update go version in build image to 1.16.6

pkg/ingester/user_metrics_metadata.go
Currently our errors look like this:
```
level=warn ts=2021-07-14T09:33:02.743961441Z caller=ingester.go:681 org_id=XXXX traceID=3224439dfe4ee37c msg="failed to ingest some metadata" err="per-metric metadata limit of 10 exceeded, please contact administrator to raise it (local limit: 10 global limit: 0 actual local limit: 10)"
level=warn ts=2021-07-14T09:33:02.743862184Z caller=ingester.go:681 org_id=XXXX traceID=3224439dfe4ee37c msg="failed to ingest some metadata" err="per-metric metadata limit of 10 exceeded, please contact administrator to raise it (local limit: 10 global limit: 0 actual local limit: 10)"
level=warn ts=2021-07-14T09:33:02.743728652Z caller=ingester.go:681 org_id=XXXX traceID=3224439dfe4ee37c msg="failed to ingest some metadata" err="per-metric metadata limit of 10 …
```
=> Add metric name to metadata error

CHANGELOG.md, integration/e2e/db/db.go, integration/e2ecortex/client.go, integration/ruler_test.go, pkg/api/handlers.go, pkg/querier/error_translate_queryable.go, pkg/querier/error_translate_queryable_test.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go
**What this PR does**: This PR fixes problem described in issue https://github.com/cortexproject/cortex/issues/4333. It does so by wrapping errors returned by supplied `Queryable` into special wrapper, that is then recognized and unwrapped by `MetricsQueryFunc`. This allows "failures" metric to be updated only if error was actually caused by internal Cortex error, and not by PromQL engine failure during evaluation (this fixes #4333), or by hitting limits.
This PR also adds integration test to check for these scenarios.
Fixes https://github.com/cortexproject/cortex/issues/4333
**Checklist**
=> Fix ruler query failure reporting

CHANGELOG.md, Makefile, docs/guides/limitations.md, pkg/tenant/resolver.go, pkg/tenant/resolver_test.go
This prevents paths derived from TenantIDs to become vulnerable to path traversal attacks. CVE-2021-36157
=> Restrict path segments in TenantIDs (CVE-2021-36157)

CHANGELOG.md, Makefile, docs/guides/limitations.md, pkg/tenant/resolver.go, pkg/tenant/resolver_test.go
Pulling #4375 into release-1.10 branch so I can make a new RC
=> Cherry pick #4375 - security fix

pkg/distributor/distributor.go
Small thing that caught my eye - it is no longer true that clients always discard.
Also move the comment next to the error.
=> Update comment on rate-limit error

CHANGELOG.md, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go
Address problem state on https://github.com/cortexproject/cortex/issues/4365
Fixes #4365
**Checklist**
=> Fix Ingesters unable to re-join the cluster then `unregister_on_shutdown=false` + `-ingester.heartbeat-period=0`

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
**What this PR does**: Before this PR, compactor would consider blocks that has been marked for deletion recently (within  `-compactor.deletion-delay / 2` period) as eligible for compaction. This PR changes that, and makes compactor completely ignore blocks marked for deletion.
Under normal Cortex run this is not a problem, because blocks only get marked for deletion after they are compacted to larger blocks (or when retention period hits), and compactor would also find this "larger" block and avoid compacting the smaller ones.
However there is a scenario, where this original behavior of compactor turned out problematic. Let's say we have a block "A" for some day. After manually marking block "A" for deletion, and then running a backfill for the very same day, new block "B" is created for …
=> Don't try to compact blocks marked for deletion.

CHANGELOG.md, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
**What this PR does**: This PR modifies memberlist KV client such that when it receives message via `NotifyMsg`, which changes current state of the KV store, it doesn't forward entire message, but only sub-message with changes. This helps in some clusters to get rid of unwanted messages with tombstones, which currently DO generate a change (this is bug, PR incoming) and then retransmit even the part of message that hasn't changed anything. This can in some situations bring back ingester instances in the ring, which should be long forgotten.
**Checklist**
=> Memberlist now forwards only changes, not full original received message

CHANGELOG.md, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
**What this PR does**: This PR modifies memberlist KV store to avoid "accepting" old tombstones as a change, and avoid forwarding them to other gossip members. Before this PR, if there was a message with old tombstone in a gossip network, such message would basically never "die".
This PR builds on top of #4419, and will be rebased once #4419 is merged. **Update: Rebased.**
**Checklist**
=> Memberlist ignore old tombstones

pkg/cortex/modules.go, pkg/util/module_service.go, pkg/util/modules/module_service_wrapper.go, pkg/util/modules/modules.go, pkg/util/modules/modules_test.go
In prep for moving the "modules" package to dskit, replace uses
of the global Cortex logger with an injected one.
**Checklist**
=> Replace use of global loggers in the module subsystem

CHANGELOG.md, pkg/querier/worker/worker.go, pkg/querier/worker/worker_test.go
This PR fixes https://github.com/cortexproject/cortex/issues/4391
Fixes #4391
**Checklist**
=> Fix bug where querier may not be able to achieve max-concurrent

pkg/ingester/ingester_test.go
While running ingester tests locally I would get occasional failures in these tests.
The thinking was: we are flushing every 20ms, so wait 40ms to be sure that one cycle has happened. 
However if you log the times at which things happen, it is fairly common to see 100ms delay on the flush ticker. 
So wait a lot longer to be sure.
Also close down the ingester that we created for the test, and improve the error message on failure.
**Checklist**
- NA `CHANGELOG.md` updated
=> Reduce flakiness on chunk flush tests

pkg/frontend/config.go, pkg/frontend/downstream_roundtripper.go
Allow passing a custom http.RoundTripper in `downstreamRoundTripper` so
that it would be possible to pass something else other than
`http.DefaultTransport` which is limited to only two idle connections
per host.
Part of https://github.com/cortexproject/cortex/issues/4428.
**Checklist**
=> frontend: permit passing a custom http.RoundTripper

pkg/querier/queryrange/roundtrip.go
Exhaust the whole body of the response before closing to facilitate
re-use of keep-alive connections as per the documentation here:
https://pkg.go.dev/net/http#Client.Get
```
Caller should close resp.Body when done reading from it.
```
Also some discussion here:
https://groups.google.com/g/golang-nuts/c/148riho42sU
https://github.com/cortexproject/cortex/issues/4428
It fixes a part of https://github.com/cortexproject/cortex/issues/4428.
**Checklist**
Not sure if any CHANGELOG changes are needed :thinking:
=> querier: exhaust response body before closing

docs/configuration/arguments.md, docs/guides/zone-replication.md
I think we might want to add that notice to the docs, because I have seen a real world user who disabled `-distributor.shard-by-all-labels` due to this paragraph in the docs without being aware that this may lead to other issues.
=> point out that disabling shard-by-all-labels has down-sides

CHANGELOG.md
=> Put CHANGELOG entries in prescribed order

CHANGELOG.md
Improve wording, remove duplicates, don't list enhancements or bugfixes as changes.
("CHANGE" is meant to be something that will impact the person running Cortex, that's why we put them first)
=> Clean up some changelog entries

CHANGELOG.md, go.mod, go.sum, pkg/chunk/cache/memcached.go, pkg/chunk/cache/redis_cache.go, pkg/querier/queryrange/instrumentation.go, pkg/util/log/wrappers.go, vendor/github.com/weaveworks/common/instrument/instrument.go, vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go, vendor/github.com/weaveworks/common/middleware/http_tracing.go, vendor/github.com/weaveworks/common/middleware/instrument.go, vendor/github.com/weaveworks/common/middleware/logging.go, vendor/github.com/weaveworks/common/server/server.go, vendor/github.com/weaveworks/common/tracing/tracing.go, vendor/modules.txt
I suggest we upgrade weaveworks/common dependency to [1fa3f9fa874c](https://github.com/weaveworks/common/commit/1fa3f9fa874c).
The key changes in the new version of weaveworks/common are that `instrument.Collector.Before` and `instrument.Collector.After` now take a context argument and that `ExtractTraceID` was moved to the `tracing` package. Also, `server.New` takes a new configuration parameter `cfg.GRPCListenNetwork`.
I think the only change that could have any practical effect would be the switch to `cfg.GRPCListenNetwork` in `server.New`. I frankly don't know if that would affect Cortex.
**Checklist**
=> Chore: Upgrade weaveworks/common

CHANGELOG.md, pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
This will replace `start` and `end` at (`@`) modifier with the actual constant values based on the original queries.
Meaning subqueries will not wrongly use their own query start and end time.
Fixes #4463
Fixes #4463 
**Checklist**
=> Fixes @ modifier when splitting queries by time.

CHANGELOG.md, tools/querytee/proxy_endpoint.go, tools/querytee/proxy_test.go
This was happening because of a race.
I've change the test suite to cover the code and the race detector shows it up.
The panic:
```
panic: runtime error: index out of range [1] with length 1
goroutine 26118 [running]:
github.com/cortexproject/cortex/tools/querytee.(*ProxyEndpoint).executeBackendRequests(0xc0003160c0, 0xc0002c2600, 0xc0004c44e0)
/__w/cortex/cortex/tools/querytee/proxy_endpoint.go:122 +0x5a5
created by github.com/cortexproject/cortex/tools/querytee.(*ProxyEndpoint).ServeHTTP
/__w/cortex/cortex/tools/querytee/proxy_endpoint.go:57 +0x25b
```
=> Fixes a panic in the query-tee.

CHANGELOG.md, pkg/distributor/query.go
What this PR does:
fix querier panics when query exemplars
Which issue(s) this PR fixes:
Fixes #4469
The panic:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14497b5]
goroutine 1295 [running]:
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0xc000a1fc08, 0x2d46780, 0xc00113f560)
/data/fuxi_ci_workspace/612d9ff956bed87ff117ab16/cmd/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:150 +0x1ab
panic(0x242fb40, 0x3e2f400)
/data/fuxi_ci_workspace/612d9ff956bed87ff117ab16_cache/buildbox/go-1.16.3/src/runtime/panic.go:965 +0x1b9 …
```
=> fix querier panics when query exemplars

CHANGELOG.md, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
GetRules API should call only the rulers on the tenant's subring when sharding strategy is set to `ShardingStrategyShuffle`.
Right now we are calling all rulers in the `GetRules` api even if the   sharding strategy is set to `ShardingStrategyShuffle`. In this case, we should only call the rules in the tenant subring as those rules are the only ones that can load rules from this tenant.  This change is specially important as right now we need all the rulers in the [ring to be available](https://github.com/cortexproject/cortex/blob/master/pkg/ruler/ruler.go#L763) or cortex will return an error - this means that if we have shardSize = 3 but 100 rulers in total, we will return 5xx if any of the 100 rules are down (for instance during deployment), even though the callers …
=> Using subring on getShardedRules when shuffle sharding

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Add new label `status` to metric `cortex_distributor_ingester_append_failures_total`
This is intended to differentiate errors sent from ingester
Fixes #4441
**Checklist**
=> Send new label 'status' for ingester failures

docs/proposals/parallel-compaction.md
* address comments made in the original PR #4272
**Checklist**
=> address comments for parallel compaction proposal

CHANGELOG.md, pkg/util/metrics_helper.go
`HistogramData.buckets` must be immutable after `HistogramData.Metric()`
has been called, so take an extra copy.
Fixes #4480
**Checklist**
=> Fixed panic while collecting Prometheus metrics

pkg/ring/ring.go
Signed-off-by: lanmengran1 <lanmengran1@jd.com>
Remove redundant 'LEAVING' status in Operation construction
NA
**Checklist**
=> Ring: remove redundant 'LEAVING' status in Operation construction

CHANGELOG.md
See discussion in #4489 and #4505.
=> Start 1.11 release; add changelog entries for #4505

docs/configuration/arguments.md
=> Documentation for ingester instance limits in runtime configuration

go.mod
This PR only adds comment go go.mod about pinning Thanos version. There are no other changes.
=> Added comment for Thanos pin.

integration/s3_storage_client_test.go
We have our CI blocked because of #4543. I propose to disable S3 SSE integration tests until we have a better solution (in the meanwhile we shouldn't block all PRs).
N/A
**Checklist**
=> Disable S3 SSE integration tests

integration/certs.go, integration/e2e/db/db.go, integration/e2e/images/images.go, integration/s3_storage_client_test.go
Instead of calling out to play.min.io, run the KES service locally in a container.
Generate its key and cert instead of downloading them from GitHub.
By depending on fewer third-party services we reduce test failures.
Extract function to generate PKI certificates.
Update to more recent Minio image; not using the very latest KES because it removed `--root` which is useful.
Re-enable the SSE tests (see #4545)
Fixes #4543 
**Checklist**
- NA CHANGELOG.md - not a user-visible change.
=> Run local KES for S3 integration tests

pkg/chunk/cache/redis_client.go
Signed-off-by: georgehao <haohongfan@gmail.com>
Enhance redis mset, this may panic.
NO
**Checklist**
=> Enhance: redis MSet check the length of keys and values is equal

CHANGELOG.md, pkg/querier/queryrange/retry.go
My Thanos instance is spamming this whenever the user cancels a query
that is being executed:
```
{"caller":"retry.go:73","err":"context canceled","level":"error","msg":"error processing request","org_id":"anonymous","try":0,"ts":"2021-11-23T13:35:09.275914072Z"}
```
It doesn't mean anything bad so let's stop the spam. Thus, do not perform the
retrying logic if the context has been canceled. Later on this is handled in:
```go
resp, err := f.roundTripper.RoundTrip(r)
queryResponseTime := time.Since(startTime)
if err != nil {
writeError(w, err)
return
}
```
N/A
**Checklist**
=> queryrange: retry: do not retry if context is canceled

pkg/querier/distributor_queryable_test.go
Conventionally the minimum time would be before the maximum.
Apparently none of the tests were depending on this.
**Checklist**
- NA `CHANGELOG.md` updated - test-only change
=> distributor-queryable tests: make time go forward

CHANGELOG.md, pkg/distributor/query.go, pkg/distributor/query_test.go
We need to add the merged value back to the map.
Extract merging as a separate function so it can be tested.
Adapt the existing test to cover multiple series.
**Checklist**
=> Distributor: fix bug in merging exemplars

CHANGELOG.md
Rearrange `CHANGELOG.md` to conform to instructions in
`pull_request_template.md`.
Also add a `-` to a CLI flag to conform to instructions in
`design-patterns-and-conventions.md`.
Signed-off-by: Andrew Seigner <andrew@sig.gy>
**Checklist**
=> Changelog: cleanup

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/validation/validate.go
**What this PR does**: As described in #3954, this PR adds a new metric `distributor_discarded_samples_total` to represent 
the number of dropped samples due to relabeling configuration.
**Which issue(s) this PR fixes**: 
Fixes #3954
**Checklist**
=> Adds new metric for dropped samples in ingester

docs/guides/ha-pair-handling.md
Add a note about remote read in HA Pair handling
**Checklist**
=> Add a note about remote read in HA Pair handling

.github/workflows/test-build-deploy.yml, build-image/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile
Upgrade Go to 1.17.5 for integration tests and Dockerfiles.
**Checklist**
=> Upgrade Go to 1.17.5 for integration tests + Dockerfiles

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile
**What this PR does**: This PR updates build image from master. Follow-up from https://github.com/cortexproject/cortex/pull/4602.
**Checklist**
=> Rebuild and update build image from master.

pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/util/runtimeconfig/manager.go, pkg/util/runtimeconfig/manager_test.go, vendor/modules.txt
Reintroduce util/runtimeconfig package, in place of dskit/runtimeconfig.
**Checklist**
=> Reintroduce util/runtimeconfig package

docs/proposals/federated-ruler.md
Proposes a solution to allow federated rules, rules which query data from multiple tenants
Proposes a solution for cortexproject/cortex#4403
**Checklist**
=> Federated ruler proposal

docs/proposals/tenant_retention.md
I was recently very confused by the existence and status of this tenant retention proposal document. Since the creation of this proposal, PR #3879 was implemented and now this document just adds confusion.
Sets the status of the "tenant_retention.md" document to accepted and implemented.
**Checklist**
=> update tenant retention proposal doc with implemented status

docs/architecture.md
Docs-only update to reconcile the list of services in architecture.md with the output of `cortex -modules`. Sorry if I missed this elsewhere, but I hadn't seen a list of all cortex services in one place in the docs.
**Checklist**
=> docs: reconcile service list with `cortex -modules`

pkg/ruler/ruler.go
I believe this can often be a source of confusion during initial
configuration because even though the implicit HTTP API prefix set
when using `--alertmanager.external-url` is documented, it is non
obvious behavior.
For example, in https://github.com/cortexproject/cortex/issues/3919.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
**Checklist**
=> doc: Add note about the Alertmanager URL path

CHANGELOG.md, pkg/util/validation/errors.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
This PR adds length and limit to labelNameTooLongError and labelValueTooLongError, so it will be easier to know what values should be set.
**Checklist**
=> Add length and limit to error messages when label names and values are too long

pkg/distributor/distributor_test.go, pkg/ring/batch.go
Fixes cases where a single ingester outage cause 5XXs.
Fixes https://github.com/cortexproject/cortex/issues/4381
**Checklist**
=> distributor: don't return 5xx on a single ingester outage

CHANGELOG.md, pkg/frontend/frontend_test.go, pkg/frontend/transport/handler.go
Signed-off-by: Matej Gera <matejgera@gmail.com>
Fixes the behavior of Query Frontend when it comes to logging slow queries - if the parameter is set to < 0, all queries should be logged, as is described in the documentation. However, presently, the opposite is true - if set to < 0, logging is disabled altogether.
Leaving the parameter at `0` should still retaing the same behavior, i.e. disabling slow query logging.
Fixes #4610
**Checklist**
=> Query Frontend: Fix slow query logging if 'LogQueriesLongerThan' is set to < 0

CHANGELOG.md, pkg/ring/replication_strategy.go, pkg/ring/replication_strategy_test.go
Instead of calculating replication factor in the beginning, calculate it after unhealthy instances have been filtered out. This avoid failure where we have a replication factor of 3, and we have a single unhealthy ingester.
Fixes #4626
**Checklist**
=> update defaultReplicationStrategy to not fail with extend-write when a single instance is unhealthy

CHANGELOG.md, RELEASE.md, pkg/ruler/manager_metrics.go
=> Prep release 1.12.0

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/manager.go, pkg/ruler/notifier.go, pkg/ruler/notifier_test.go, pkg/ruler/ruler.go, tools/doc-generator/parser.go
Add an `external_labels` option for the ruler, to tag all alerts emitted by the ruler with a given set of labels.
**Checklist**
=> pkg/ruler: Add external_labels option

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, build-image/Dockerfile
To address https://github.com/advisories/GHSA-6685-ffxp-xm6f "stack exhaustion via a deeply nested expression".
This is for an upcoming patch release v1.11.1.
Note we always recommend that Cortex is run behind an authenticating front-end; if this front-end restricts queries (or all requests) to a moderate length before they reach Cortex then attackers cannot exploit this vulnerability which uses a message of over 2MB.
For example if Nginx is used as a front-end, it limits requests to 1MB by default.
**Checklist**
=> [Release 1.11] Update to Go v1.16.15

go.mod, go.sum, integration/integration_memberlist_single_binary_test.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/modules.txt
Updating memberlist with Grafana's fork to fix the broadcast of messages larger than 64KB which is causing pods to crash (OOM killed).
More details in this previous PR: https://github.com/cortexproject/cortex/pull/4669
Fixes #4668
**Checklist**
=> Fix broadcast of messages larger than 64KB

integration/alertmanager_test.go, integration/s3_storage_client_test.go, pkg/chunk/aws/s3_storage_client.go, pkg/chunk/aws/s3_storage_client_test.go, pkg/ring/kv/consul/client.go
Remove consul ACLToken and S3 secret_access_key (chunk storage) from output of /config endpoint
=> Avoid leaking secrets on /config HTTP API endpoint

CHANGELOG.md, pkg/chunk/cache/instrumented.go
The following query-frontend cache metrics are incorrectly named.
```
cortex_cache_fetched_keys{name="frontend.memcache"} 872
cortex_cache_hits{name="frontend.memcache"} 869
```
These counter metrics are not ending in `total` as per the convention. 
Fixes #4685
**Checklist**
=> Fix incorrectly named cache metrics

CHANGELOG.md, pkg/storegateway/bucket_stores.go, pkg/storegateway/gateway_test.go
Currently we're only enforcing the `max_fetched_series_per_query` limit on querier. Not enforcing the series limit on store-gateways could potentially OOM kill them when a large query is executed. This PR enables the Thanos series limiter in store-gateway.
**Checklist**
=> Enable thanos series limiter in store-gateway

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
This PR enforces the `max_fetched_series_per_query` limit for `/api/v1/series` API.
Fixes #4667
**Checklist**
=> Implement max series limit in distributor for `/series` API

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/shuffle_sharding_planner.go, pkg/compactor/shuffle_sharding_planner_test.go
This PR allows user to configure if they want to skip out of order chunks during compaction (special thanks to @alanprot working on https://github.com/cortexproject/cortex/pull/4706 concurrently). 
This PR also allows manual creation of `no-compact-mark.json`. 
Fixes #4692
Partially addresses #4705 - this change will allow manual creation of `no-compact-mark.json`
**Checklist**
=> Introduce SkipBlocksWithOutOfOrderChunksEnabled feature

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/guides/shuffle-sharding.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/util/validation/limits.go
Adds shuffle-sharding for the plans generated by the grouper. Depends on #4432. Once #4432 is merged the diff for this PR will be reduced.
Implements Proposal [Parallel Compaction by Time Interval](https://cortexmetrics.io/docs/proposals/parallel-compaction/)
**Checklist**
=> Add shuffle-sharding for the compactor

README.md
Let's just have one source of truth for community meeting invite, which is the Google group.
=> Remove mention of CNCF calendar for community meetings, which is usually out of sync

CHANGELOG.md, RELEASE.md
Abandoning release 1.12 per public Slack channel post: 
> Hi folks, I would like to propose to abandon the current 1.12 release because we are currently working on getting some highly asked features (like parallel compactor) into the main branch. I think it would be a more useful release if the release contains those features. I will apply [lazy consensus](https://community.apache.org/committers/lazyConsensus.html). Please do give me a shout if you feel release 1.12 should go ahead as it is. If no strong objection, then I will start the abandoning process on Thursday April 14 2022. 
I had 4 thumbs up and no push back by the time I submit this PR.
=> Abandoning release 1.12

CHANGELOG.md
Signed-off-by: Friedrich Gonzalez <fgonzale@adobe.com>
**What this PR does**: Fixes CHANGELOG entry for #4499 #4601 #4707 #4708
**Checklist**
=> Include changelog number for #4499 #4601 #4707 #4708

CHANGELOG.md, pkg/distributor/ha_tracker.go, pkg/util/strings.go
The HA cluster label is exposed through the distributor metrics. This can cause memory leak when one tenant sends a lot of different clusters. The metrics is only cleaned up after 30 mins.
The memory is leaked because the the `yoloString` in the request is kept alive for a longer period.
The following is the memory consumed by the distributor over time without cloning the cluster label.
The following is the memory consumed by distributor when cluster label was cloned.
The above leak in `snappyDecode` appears to have disappeared.
**Checklist**
=> Fix memory leak in distributor due to cluster label

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor_test.go, pkg/storage/tsdb/bucketindex/index.go, pkg/storage/tsdb/bucketindex/markers.go, pkg/storage/tsdb/bucketindex/markers_bucket_client.go, pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go, pkg/storage/tsdb/bucketindex/markers_test.go, pkg/storage/tsdb/bucketindex/storage_test.go, pkg/storage/tsdb/bucketindex/updater.go, pkg/storage/tsdb/bucketindex/updater_test.go, pkg/storage/tsdb/testutil/block_mock.go, pkg/storegateway/gateway_test.go, pkg/storegateway/metadata_fetcher_filters_test.go
Follow up of https://github.com/cortexproject/cortex/pull/4707.
* Upload the `no-compact` marks to the global marks location
* Introduce a new metric to show how many blocks are marked for no compact on store.
Fixes: https://github.com/cortexproject/cortex/issues/4727
**Checklist**
- [] Documentation added
=> Upload blocks no compaction marks to the global location and introduce a new `cortex_bucket_blocks_marked_for_no_compaction_count` metric

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/client/cortex_mock_test.go, pkg/ingester/client/cortex_util.go, pkg/ingester/client/cortex_util_test.go, pkg/ingester/client/ingester.pb.go, pkg/ingester/client/ingester.proto, pkg/ingester/ingester.go, pkg/ingester/ingester_v2.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/testutils.go
Currently, the `MetricsForLabelMatchers`, `LabelNames`, `LabelValues` APIs doesn't support streaming. Because of this queriers have to load all the time-series into memory before the `max_fetched_series_per_query` limit can be applied. This causes queriers to OOM when a sufficiently large query is made. This PR introduces streaming for this API reducing the amount of data that must be fetched before the limit should be applied.
**Checklist**
=> Add streaming for ingester metadata APIs

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
It re-enables the `proxy_url` option for alertmanager receivers.
⚠️ Reverts part of a security change! Review well ⚠️ 
Originally introduced with #4129 . We believe this might have been an overly cautious fix and propose to re-enable this option again. This seems to be the consensus in the follow-up discussion. https://github.com/cortexproject/cortex/pull/4129#issuecomment-1120097455 by @alvinlin123 
Fixes #4680 
**Checklist**
=> Re-enable proxy_url for alertmanager receivers

CHANGELOG.md, pkg/cortexpb/compat.go, pkg/distributor/distributor.go
Addresses an issue where the stream response is left in the memory which increases the overall memory consumption.
Keeping a reference to `resp` will also mean that 3x the series (duplicate data fetched from all ingesters) is kept in memory.
Before this fix:
After this fix:
**Checklist**
=> Reduce the number of series that are kept in memory while streaming from ingesters

CHANGELOG.md, pkg/ring/kv/memberlist/memberlist_client.go
When scaling pods simultaneously, we have a chance of then rejoining together. This can cause CPU instability with spikes around the time pods are rejoining. The PR try to mitigate the issue distributing the requests adding a jitter to reset the initial time for each pod.
**Checklist**
=> Add rand to sparse requests for rejoin memberlist cluster

CHANGELOG.md, pkg/ruler/manager.go, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/ruler/manager_test.go, pkg/ruler/ruler_test.go
Stops notifier when a user is removed from ruler.
Currently if a user is removed from ruler, the notifier keeps on accumulating. If a cluster has high churn, memory will grow at a faster pace
**Checklist**
=> fix leaking notifier in ruler when user is removed

CHANGELOG.md, pkg/ring/merge_test.go, pkg/ring/model.go
Add a 30min window as max time to accept gossip updates. It avoids the possibility of a clock skew that can cause a non health pod to be available longer than expected.
Fixes #4461 
**Checklist**
=> Add limit time for gossip on ring

CHANGELOG.md, pkg/compactor/shuffle_sharding_planner.go, pkg/compactor/shuffle_sharding_planner_test.go
Currently the shuffle-sharding compactor will continuously compact a single block into a new block, if there is another compactable block marked for no compaction.
The compactor will skip compaction groups with only 1 block, after checking for blocks marked for no compact.
**Checklist**
=> skip compaction if there is only 1 block available for shuffle-sharding compactor

pkg/distributor/distributor.go, pkg/util/limiter/query_limiter_test.go
Removes the series fingerprint calculation from the locked code.
We are sorting the series labels and calculating the hash to get the fingerprint. This code can be a little heavy and there is no reason to be locked.
This changed improved the latency on retrieving 1M series from ~37 seconds to ~29 seconds.
**Checklist**
=> Removing fingerprint calculator from the lock on the GetSeries API

CHANGELOG.md, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go
This PR tries to address an edge case where compaction stops when a tenant stops ingesting samples. The blocks with incomplete `maxTime` will never be compacted.
Fixes #4770
**Checklist**
=> Ensure that compaction continues for block with incomplete time-range

CHANGELOG.md, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go
`cortex_compactor_remaining_planned_compactions` is not getting set as plans are generated. This PR fixes the issue
**Checklist**
=> fix cortex_compactor_remaining_planned_compactions not set after plan generation

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/compactor/compactor.go, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go, vendor/github.com/thanos-io/thanos/pkg/block/block.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go, vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go, vendor/modules.txt
Update Thanos to bring https://github.com/thanos-io/thanos/pull/5475 and introduce a new compactor config to upload/download blocks in parallel.
**Checklist**
=> Compactor: Download and Upload block files in parallel

CHANGELOG.md, integration/querier_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
Previously, if a single store-gateway fails to return data, the whole function fails. This causes queries to fail without reattempting other available store-gateways.
Now, the function responsible for fetching data returns whatever was retrieved, and relies on the caller to determine whether all the necessary blocks were gathered.
Fixes #4529 
**Checklist**
=> Return data fetched from a subset of store-gateways instead of returning error if a single store-gateway fails

pkg/chunk/cache/redis_cache.go, pkg/chunk/cache/snappy.go, pkg/querier/queryrange/results_cache.go
Signed-off-by: Mengmeng Yang <mengmengyang616@gmail.com>
Improve redis cache logging, let it log with context for redis cache files, so that it's easier to figure out the errors are thrown from which request.
No
**Checklist**
=> let redis cache logs log with context

CHANGELOG.md, pkg/distributor/distributor_test.go, pkg/ring/batch.go
After https://github.com/cortexproject/cortex/pull/4388, we started returning the error which most failed. This CR improves the logic to also prioritize 4xx if it was the same amount of 5xx errors. The logic being that in a case of 4xx and 5xx, we are predicting the customer was close to their limits and 4xx is more relevant than 5xx. The change also creates more consistency in responses.
If we had a 3 quorum
Before:
2xx, 5xx, 4xx -> returns 4xx
2xx, 4xx, 5xx -> returns 5xx
5xx, 4xx, 5xx -> returns 5xx
4xx, 5xx, 4xx -> returns 4xx
After change:
2xx, 5xx, 4xx -> returns 4xx
2xx, 4xx, 5xx -> returns 4xx
5xx, 4xx, 5xx -> returns 5xx
4xx, 5xx, 4xx -> returns 4xx
**Checklist**
=> DoBatch preference to 4xx if error

pkg/ingester/ingester_v2.go, pkg/ingester/ingester_v2_test.go
Fixing updateCachedShippedBlocks function.
With the thanos update, we started to see the following error:
```
level=error ts=2022-07-28T02:35:59.814001241Z caller=ingester_v2.go:1753 org_id=blah msg="failed to update cached shipped blocks after shipper initialisation" err="failed to read /data/tsdb/blah/thanos.shipper.json: open /data/tsdb/blah/thanos.shipper.json: no such file or directory"
```
As thanos changed the error type:
https://github.com/thanos-io/thanos/pull/5174
It does not seems to be a big issue (or not a issue at all) as when the file does not exists there is nothing to update anyway - but the log line is ugly!
**Checklist**
=> Fix updateCachedShippedBlocks - Thanos Update

CHANGELOG.md, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go
Add logic to join memberlist while starting also avoiding 'empty ring'. On startup we dont have retry or failure to not block start of service. We leave these responsibilities to running as it was before.
Fixes #4798
**Checklist**
=> Join memberlist on starting with no retry

pkg/alertmanager/multitenant.go
=> Fix alertmanager log message

README.md, docs/_index.md
As announced back in March, [Grafana Lab uses Mimir](https://grafana.com/blog/2022/03/30/announcing-grafana-mimir/), a fork of Cortex, for their cloud offering.
=> Grafana Cloud uses Mimir now, so remove Grafana Cloud as hosted service in documents

build-image/Dockerfile
This PR is a prerequisite for https://github.com/cortexproject/cortex/pull/4814/files. 
* Upgrading to Hugo 0.94.X because later version requires Go 1.18; we shall upgrade to Go 1.18 separate as there may be quite a bit of work. 
* I am using my personal Hugo fork because the official repo causes checksum error. See https://github.com/gohugoio/hugo/pull/10154. I will switch back to official repo when my PR is mreged.
=> Upgrade Hugo

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/bucket/azure/bucket_client.go, pkg/storage/bucket/azure/config.go, pkg/storage/bucket/azure/config_test.go
This PR adds configuration for azure bucket client (ruler/block-storage/alert-manager) to use MSI, by propegating the config to thanos code, which already supported MSI.
**Checklist**
=> add support for msi in bucket client

pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
Signed-off-by: Roy Chiang <roychi@amazon.com>
When a user is removed, instead of keeping the registry in memory, we now merge all the gathered metrics. This helps to avoid the build up of registries(memory leak), and speeds up the computation of metrics.
Fixes #4451
**Checklist**
=> merge Prometheus metrics for removed user to avoid having to recompute metrics from scratch everytime

docs/contributing/how-to-update-the-build-image.md
I was notified that after [my change to upgrade Hugo](https://github.com/cortexproject/cortex/commit/234bddec3cfa591ff65158ab5ffc13868846a2a1), *Check Vendor Directory* build step started to take a lot longer (from 4 min to 40 min...). 
The reason was because the new build image I published had `GOPROXY=direct`, which was caused by the machine I build the build image is configured to not use any proxy. 
I thought it'd be nice to add this to doc so that next time I build a build image, I will remember this issue.
=> Upate update build image instruction with things to note about GOPROXY

CHANGELOG.md, pkg/ingester/ingester.go
Disables TSDB Isolation.
As describe on https://github.com/prometheus/prometheus/issues/9265 and https://github.com/prometheus/prometheus/issues/9265#issuecomment-910199494 , this isolation is not bringing much on cortex as it is a distributed system.
**Checklist**
=> Disable TSDB Isolation

build-image/Dockerfile
Upgrade build image to use Go 1.19 so we can start using new language features like generic. 
Example build workflow run using the new build image can be found at https://github.com/alvinlin123/cortex/pull/3
Fixes #4817
=> Upgrade build image to use go 1.19

website/layouts/partials/search-input.html
After upgrading Docsy in https://github.com/cortexproject/cortex/commit/96d1d7cdd725ab6066e33728813685674810f72a search stopped working because the `search-input.html` needed to be updated. Instead of updating Cortex's local copy, I thought it's better to just remove it and use the partial from Docsy, so we are more upgrade-proof next time.
=> Fix Cortex website search function

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
Just doing the same logic of #4532 when receiving the streams from store-gateways.
As this code run on a err group, an error on 1 store gateway will cause a retry on all store-gateways.
**Checklist**
=> Follow up of 4532 - Return data fetched from a subset of store-gateways instead of returning error if a single store-gateway fails

pkg/querier/queryrange/results_cache.go
Signed-off-by: Mengmeng Yang <mengmengyang616@gmail.com>
Add few more logs to cache results file so that it's easier to figure out a request is skipped cache, cache hit, cache miss when a request split to multiple ones.
**Checklist**
=> add log to identify request cache hit and cache miss

MAINTAINERS
I use both but it's clearer for everybody if I just stick to one for cncf things
**What this PR does**: Updates my username in maintainers file
=> Update my username

CHANGELOG.md, pkg/compactor/compactor.go, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go, pkg/ring/ring_test.go
We can have ingesters becoming unhealthy during startup if the wall replay takes longer than the `heartbeat_timeout`.
The reason for that is that the lifecycle service is started only after ingesters open all TSDBs:
https://github.com/cortexproject/cortex/blob/b855a2573be098cbb2921aec5e48ae565b616e66/pkg/ingester/ingester.go#L708-L719 
This adds an option on the `lifecycle` service to configure if the ingester should AutoJoin the ring (flip his state to active).
If the option is set to false, the ingester will only join the ring after the "Join" method is called.
This change allow us to start the `lifecycle` before executing the wall replay (so the heart will start to beat) but only flip its state to active after all TSDBs are replayed.
**Checklist**
=> [ingesters] Send heartbeat during wall replay

docs/configuration/config-file-reference.md, pkg/tracing/tracing.go
Use the existing TLS config as the other clients as, for example:
https://github.com/cortexproject/cortex/blob/04bb64dcb3842fd11a9b46e2ca9666eb3e0681a7/pkg/alertmanager/alertmanager_client.go#L35-L40
**Checklist**
=> Using tls client config as the other clients on cortex

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/distributor/distributor_test.go, pkg/util/validation/errors.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
This PR introduces a new limit `max_series_label_size_bytes`.
Currently, it is possible for users of Cortex to OOM kill distributors and ingesters by increasing the size of each label and label value. For instance, a user can send 1 million series with each series having 30 labels of maximum size. `1 million * 30 labels * 3 KB per label = 85 GB`.
This new limit can prevent this from happening by rejecting series that have a combined label size greater than this limit.
Example: if the `max_series_label_size_bytes` is set to 10 KB, any series that exceed will be rejected. 1 million active series for a user will consume `1 million * 10 KB = 9 GB`.
**Checklist**
=> Add new limit: max_series_label_size_bytes

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, integration/e2ecortex/storage.go, pkg/cortex/cortex_test.go, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go, pkg/storage/bucket/sse_bucket_client_test.go
Some providers may only support one of those bucket lookup styles.
**Checklist**
=> Make s3 bucket lookup type configurable

CHANGELOG.md, pkg/util/validation/errors.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
The truncated message maybe not be helpful for users to find the problem.
**Checklist**
=> Add label name to labelValueTooLongError

pkg/ingester/ingester.go
Add partial failure logs to ingester push. We currently have logs on grpc_logging which just log the first error. This gives us more visibility on what is occurring in the ingester.
New log:
```
level=warn ts=2022-09-07T06:59:57.34613661Z caller=ingester.go:1009 org_id=XXXXXXX msg="partial failure to push" err="cannot add series: ingesters's max series limit reached"
```
Existent log:
```
level=warn ts=2022-09-07T06:59:58.084669264Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=83.84µs err="user=xxxxxxxx: cannot add series: ingesters's max series limit reached" msg="gRPC\n"
```
**Checklist**
=> Add log message for partial failure on push

CHANGELOG.md, pkg/tracing/sampler/sampling.go, pkg/tracing/sampler/sampling_test.go, pkg/tracing/tracing.go
Creates a simple sampler as the `TraceIDRatioBased` does not work well with xray generated Ids.
See: https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/aws/xray#section-readme
```
It is a general suggestion to not use the traceIDRatioSampler while also using the X-Ray IDGenerator. The non-random nature of building an X-Ray traceId may lead to unexpected sampling results.
```
This sampler simple randomly pick traces to be sampled based on the fraction received as parameter. The sample decision is then propagated via the `parentBased` sampler.
**Checklist**
=> Respecting `-tracing.otel.sample-ratio` configuration when enabling OpenTelemetry tracing with X-ray

pkg/alertmanager/distributor_test.go
This is just fixing the test introduced by https://github.com/cortexproject/cortex/pull/4840
The tests sets the number of AM to fail/succeed but as we pick them randomly the tests can fail (if for instance we expect one retry but we pick a health ingester in the first try)
This change the tests to always return the failures first no matter which AM we pick.
=> Fixing Flaky AM test

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
This normally was done after release, let's see how can we pick it up.
Update: Looks like it worked on the first try :)
=> Add release 1.11.1 to the backwards compatibility matrix

pkg/compactor/compactor.go
Signed-off-by: Alan Protasio <approtas@amazon.com>
Ignore not found errors when compacting users.
https://github.com/cortexproject/cortex/pull/4805 introduced a new markers that is being called on the shuffle sharding grouper and  its expected to receive 404, causing `thanos_objstore_bucket_operation_failures_total` metric to spike.
With this change, we should not count 404s towards `thanos_objstore_bucket_operation_failures_total`.
**Checklist**
=> Ignore not found errors when compacting users

pkg/compactor/block_visit_marker.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/compactor/shuffle_sharding_planner.go, pkg/compactor/shuffle_sharding_planner_test.go
Just a follow up of https://github.com/cortexproject/cortex/pull/4870
On that PR we were not counting 404s on all buckets operations. This PR only ignores 404s when fetching the visitor marker as this error is expected there.
**Checklist**
=> Follow up of 4870 - Ignore 404 on `thanos_objstore_bucket_operation_failures_total` only when fetching the markers

pkg/querier/distributor_queryable.go, pkg/querier/duplicates_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/remote_read_test.go, pkg/querier/series/series_set.go, pkg/querier/series/series_set_test.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/querier/timeseries_series_set.go, pkg/querier/timeseries_series_set_test.go, pkg/querier/tripperware/queryrange/series_test.go, pkg/querier/tripperware/queryrange/value.go
We are always sorting the response even when its not needed.
We still need to sort the series if we are querying multiples backends (ex: ingesters + store-gateways) as the result needs to be sorted in order to be merged [here](https://github.com/cortexproject/cortex/blob/28a8a37efb94ffd1f5482f4f58667f144fc456b3/pkg/querier/querier.go#L388).
* Each backend should be responsible to not returning duplicated timeseries:
* When querying ingesters the dedup happens [here](https://github.com/cortexproject/cortex/blob/28a8a37efb94ffd1f5482f4f58667f144fc456b3/pkg/distributor/query.go#L356-L380)
* When querying store gateways this flag is [ignored](https://github.com/cortexproject/cortex/blob/28a8a37efb94ffd1f5482f4f58667f144fc456b3/pkg/querier/blocks_store_queryable.go#L321) …
=> Using `sortSeries` from Select to decided to sort the response on DistributorQueryable

CHANGELOG.md, pkg/querier/tripperware/queryrange/split_by_interval.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go
Right now, if we send a query range with the start == end, queryfrontend short circuit  the request and return an empty response.
We should still send this request as prometheus returns 1 step in such scenarios.
**Checklist**
=> QueryFronted should send request to queriers when query_range has start==end

pkg/distributor/ha_tracker.go, pkg/distributor/ha_tracker_test.go
Signed-off-by: songjiayang <songjiayang1@gmail.com>
Fixes #4879
**Checklist**
=> Adding HA tracker kv store type validation

CHANGELOG.md, pkg/alertmanager/alertstore/local/store.go, pkg/alertmanager/alertstore/local/store_test.go, pkg/alertmanager/multitenant_test.go
Populating the templates when using alertmanager local store.
Fixes #4888
**Checklist**
=> Templates in use are being removed by alertmanager cleanup logic

Makefile, packaging/fpm/Dockerfile
I was doing 1.13.1 release and got an error `https://quay.io/repository/cortexproject/fpm not found` when doing `make packages`, which used to work before.  I am not sure how `https://quay.io/repository/cortexproject/fpm` was removed from quay.io, but we gotta move on with our lives. 
With some reverse-engineering I determined that the `https://quay.io/repository/cortexproject/fpm` was built from `packaging/fpm/Dockerfile`, so I built that and pushed it to `quay.io/repository/cortexproject/fpm`, then ran `make packages` again, which completed successfully. 
I had to upgrade Alpine version in `packaging/fpm/Dockerfile` in order to be able to install the latest `ruby` successfully. I also had to change the command line arg for doc generation for `gem install` because [--no-ri --no-rdoc are …
=> Upgrade fpm image

GOVERNANCE.md
I would like to call an official vote to update the governance with changes around maintainership. Please see  the diff in this PR for the changes. 
Per [existing governance rule](https://cortexmetrics.io/docs/contributing/governance/#changes-in-governance), 2/3 majority votes are required for the changes to pass. 
Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first.
=> [Vote] Governance update around maintainership 

CHANGELOG.md, pkg/storage/bucket/s3/bucket_client.go
~Introduces a boolean flag to enable AWS SDK for go auth~
Enables AWS SDK for go auth
Enable IMDSv1 again #4896  and most likely other use cases
**Checklist**
=> Enable AWS SDK for go authentication to fix IMDSv1 issue

pkg/ruler/rulestore/configdb/store.go
Signed-off-by: Florian Lehner <florianl@users.noreply.github.com>
Preallocate memory instead of enforcing an incremental growth. This will result in less work for the garbage collector.
**Checklist**
Trivial change that improve performance but does not have a visible effect for users or developers.
=> preallocate memory

CHANGELOG.md, pkg/distributor/distributor.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Signed-off-by: songjiayang <songjiayang1@gmail.com>
**What this PR does**: 
Fixes #4904
**Checklist**
=> Cache user overrides in `distributor.Push` to reduce lock contention.

pkg/api/handlers.go, pkg/cortex/cortex.go, pkg/querier/querier.go, pkg/ruler/compat.go
Update Cortex query related functions to accept `v1.QueryEngine` rather than `promql.Engine`. This allows us to explore other query engines like https://github.com/thanos-community/promql-engine
**Checklist**
=> update function signature to use v1.QueryEngine

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager_client.go, pkg/querier/store_gateway_client.go
Enable snappy compression for store gateway and alertmanager gRPC client.
Now I just make it a default, but we can go with flag, too.
**Checklist**
=> chore: make grpc compression configurable for store gateway and alertmanager client

go.mod, go.sum, pkg/querier/tripperware/test_shard_by_query_utils.go, vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go, vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go, vendor/modules.txt
Update Thanos to https://github.com/thanos-io/thanos/commit/d5744e794d97a4d9c6e398c44e0a2166ee82f8b8
Fix sharding behavior for vector matches #5799: https://github.com/thanos-io/thanos/pull/5799
**Checklist**
=> chore: Update Thanos

docs/proposals/timeseries-partitioning-in-compactor.md
Added compaction and clean up workflow to partitioning compactor proposal (#4843)
Fixes #4705
**Checklist**
=> Update proposal for timeseries partitioning in compactor

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
This PR adds "interruption" as a new category of compaction outcome.  Currently, compaction starts and then it either fails or succeeds according to metrics.  In the event of a graceful shutdown, an ongoing compaction is recorded as a failure and `cortex_compactor_runs_failed_total` and `cortex_compactor_tenants_processing_failed` are incremented.  This makes it cumbersome to monitor for compaction failures.  After this PR, compactions interrupted by shutdown will not be recorded as failures but rather as "interruptions".
**Notes**:
Ideally, we could also verify in unit tests that `cortex_compactor_tenants_processing_failed` is not incremented, but this would require more complicated refactoring because `cortex_compactor_tenants_processing_*` metrics are reset at …
=> treat interrupted compactions different than failures

docs/configuration/v1-guarantees.md
The metric name was changed in [this commit](https://github.com/alvinlin123/cortex/commit/a9a96cb246f293fabe722fa797dfa0a6f516ca57), but I guess we forgot about doc. Let's update it now; never too late :)
=> Update deprecated flag metric name in doc

CHANGELOG.md, pkg/ingester/ingester.go
Signed-off-by: Daniel Deluiggi <ddeluigg@amazon.com>
We accidently add a duplicate log line on ingester in #4803
**Checklist**
=> Remove duplicate log message

.github/workflows/test-build-deploy.yml
Someone told me about https://clomonitor.io/projects/cncf/cortex during KubeCon, and that Google would make some donation on behalf of Cortex if it reaches score of 100 for security. 
I care about both security and the donation, so this PR set the default `GITHUB_TOKEN` permission to read only; conforming to https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
=> Set github token permission default to read-all

CHANGELOG.md, integration/getting_started_with_gossiped_ring_test.go, integration/querier_test.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores_test.go
Right now `cortex_bucket_store_blocks_loaded` metric is the total blocks loaded for each store gateway instance.
This pr makes it per user so that we can know the # of blocks for each tenant.
This pr changes the behavior of the metric so we need `sum` to get the previous value back.
If we want to have compatibility then I can add a separate metric `cortex_bucket_store_blocks_loaded_per_user` rather than changing existing ones.
**Checklist**
=> Make cortex_bucket_store_blocks_loaded metric per user

RELEASE.md
This is to conform with https://github.com/ossf/scorecard/blob/084bcd90098bababa68c6abfe28dc777bfc4b060/docs/checks.md#signed-releases. Why? Because it's the right thing to do with added benefit of Google will make donation on Cortex's behalf: https://www.cncf.io/blog/2022/10/12/whats-new-at-kubecon-cloudnativecon-north-america-in-the-motor-city-or-is-it-motown-or-the-paris-of-the-midwest/
=> Add signing release artifacts instruction

website/layouts/partials/footer.html
To address: https://clomonitor.io/docs/topics/checks/#legal
This is how it looks:
=> Add trademark notice to website footer

CHANGELOG.md, pkg/storage/tsdb/bucketindex/markers_bucket_client.go
Signed-off-by: Daniel Deluiggi <ddeluigg@amazon.com>
Change order Cortex upload markers to storage. In some situations, if the second call fails blocks can be left without being delete. This try to avoid it by always updating the global marker first
Fixes #4872
**Checklist**
=> Upload global marker before local

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/queryrange/query_range.go
Before [this](https://github.com/cortexproject/cortex/pull/4863) change, the query-frontend did not do any manipulation for instant queries and the QF was basically a proxy. 
https://github.com/cortexproject/cortex/pull/4863 changed that and introduced  middlewares also for instant queries in order to be able to manipulate the  queries and implement the `shard by` optimization.
The problem now is that we are not forwarding all the headers from the original request to the querier, including the `Accept-Encoding` one and, this means that we stopped to gzip those requests between the query-frontend and the querier.
PS: This was already the case for `query_range`
This PR is changing this behavior and making the QF always ask the querier to return the response gzipped. …
=> Always request querier to return gzipped response

.github/workflows/scripts/install-docker.sh, integration/e2e/service.go
=> Upgrde build docker engine to latest version

MAINTAINERS
I would like to call for a vote to add @yeya24 as Cortex maintainer.
Ben is currently Thanos maintainer, and he had been very active in contributing to Cortex ever since he joined AWS about 1.5 months back. Here is [a list of Ben's contribution](https://github.com/cortexproject/cortex/pulls?q=author%3Ayeya24+). I can see that Ben is passionate about helping Cortex, and his experience being Thanos maintainer can be a great help.
Per [existing change in maintainership governance rule](https://cortexmetrics.io/docs/contributing/governance/#changes-in-maintainership), 2/3 majority votes are required for the changes to pass.
Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first. …
=> [Vote] Ben Ye (yeya24) as new Cortex maintainers

go.mod, go.sum, pkg/querier/tripperware/test_shard_by_query_utils.go, vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go, vendor/github.com/thanos-io/thanos/pkg/querysharding/analysis.go, vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go, vendor/modules.txt
This pr updates Thanos to include https://github.com/thanos-io/thanos/pull/5880.
It mainly fixes cases mentioned in https://github.com/thanos-io/thanos/issues/5879
**Checklist**
=> Update Thanos to get latest querysharding fix

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_test.go
Fix response to be ungzipped when status code is not 2xx. If status code is not 2xx, Prometheus returns error like while Cortex QFE returns the gzipped response. We should always ungzipped the body.
**Checklist**
=> fix response error to be ungzipped when status code is not 2xx

CHANGELOG.md, docs/api/_index.md, pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go
Grafana uses this API to detect Cortex version and decides whether to use series API with matchers or the label values API. Support it will benefit Grafana & Cortex users to use an API with better performance.
This is a new feature in Grafana https://github.com/grafana/grafana/pull/56496.
**Checklist**
=> Support Prometheus /api/v1/status/buildinfo API on Querier/QFE

integration/querier_sharding_test.go
I am guessing that by increasing number of queries (sample space), we are less likely to deviated from the assertion of `require.InDelta(t, 0, diff, numQueries*0.20)`. 
By empirical data, if I start more than 100 queries concurrently, I get HTTP 429 error; so I implemented some batching logic on top of the original `numQueries`. I have tuned bunch of config in Cortex and could not get rid of the HTTP 429, so I came to believe the 429 may be caused by the file description issue mentioned in the original comment.
=> Make querier_sharding_test less brittle

build-image/Dockerfile
Upgrade build image to use Go [1.19.3](https://go.dev/doc/devel/release#go1.19.minor)
**Checklist**
=> Upgrade build image to use go 1.19.3

docs/contributing/how-to-update-the-build-image.md, docs/contributing/how-to-upgrade-golang-version.md
Remove duplicated build instructions.
**Checklist**
=> Combine upgrade-golang-version with update the build image

CHANGELOG.md, docs/api/_index.md, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go
1. We ensure select start time is always a non-negative value (we set it to 0 if it is < 0) to avoid int64 overflow issue. 
2. For `/api/v1/series` API and start time of 0, we just fallback to query ingesters only to avoid OOM kills. This should work well for those clients who don't support specifying `start` on series API. 
`/api/v1/series` API supports optional `start` and `end` parameters. Since Cortex uses the Prometheus API code, right now if `start` is not specified, it will use the min value here https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L725. This happens for some clients that don't configure these params.
The issue here is that if start time is too small, …
=> limit get series API call time range when start param is not specified

CHANGELOG.md, pkg/frontend/transport/handler.go
Right now if a query fails at query frontend, no query parameters will be logged so we don't have any visibility about what's the failed query and why it failed.
This pr always log query params to make sure we catch them.
**Checklist**
=> Log query params in query frontend when error

cmd/thanosconvert/main.go, docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md, pkg/querier/block.go, tools/thanosconvert/thanosconvert.go
Cortex doesn't support downsampling and cannot handle downsampled blocks migrated from Thanos.
This pr adds a note on the migration guide to avoid issues like https://github.com/cortexproject/cortex/issues/4982.
**Checklist**
=> Add note about thanos downsampled block migration

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/frontend/frontend_test.go, pkg/frontend/v1/frontend.go, pkg/frontend/v1/frontend_test.go, pkg/frontend/v1/queue_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/queue/user_queues.go, pkg/scheduler/queue/user_queues_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/validation/limits.go
Now the QFE queue size is a global configuration https://github.com/cortexproject/cortex/blob/master/pkg/frontend/v1/frontend.go#L40, which means we cannot override the queue size for different tenants.
For different tenants, we may want to use different queue sizes based on their query concurrency. Making it a per-tenant config in limits makes it more flexible and easier to update during runtime.
**Checklist**
=> Make max outstanding queries per tenant config in limits

CHANGELOG.md, cmd/query-tee/main.go
Signed-off-by: wangguoliang <iamwgliang@gmail.com>
Adding /api/v1/query_exemplars API endpoint support to query-tee.
**Checklist**
=> Add /api/v1/query_exemplars route support to query-tee

.github/workflows/test-build-deploy.yml, integration/backward_compatibility_test.go
Last step of: https://github.com/cortexproject/cortex/blob/master/RELEASE.md#publish-a-stable-release
```
Open a PR to add the new version to the backward compatibility integration test (integration/backward_compatibility_test.go)
```
=> Adding compatibility tests for 1.13 and 1.14

pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/gateway_test.go
Just removing some left over https://github.com/cortexproject/cortex/pull/2599
This code was reverted some code code was left behind.
=> chore: Small code clean up

CHANGELOG.md, pkg/frontend/v1/frontend.go, pkg/scheduler/scheduler.go
We are using the default bucket layout for queue duration histograms. However, the default upper bound is only 10s, which might not be very sufficient in real use cases. This pr raises the upper bound to 60 seconds.
**Checklist**
=> Increase upper bound for queue duration histogram bucket

CHANGELOG.md, pkg/frontend/v1/frontend.go, pkg/frontend/v1/frontend_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/scheduler.go
Add a new counter metric `cortex_request_queue_requests_total` in the query queue for total requests.
This is useful to calculate the rate because we only have a gauge metric for queue length before so it is hard to know how many requests are there and its rate.
**Checklist**
=> Add counter metrics for total requests going to queue

.github/workflows/scripts/install-docker.sh, .github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, cmd/thanosconvert/Dockerfile, push-images
Build ARM Images ARM Images:
The image was tested on an AWS Graviton Instance:
IMAGE Example: 
* quay.io/cortexproject/cortex:HEAD-efbbb29 
* cortexproject/cortex:HEAD-efbbb29
Output:
```
docker run quay.io/cortexproject/cortex:HEAD-efbbb29
level=info ts=2022-12-15T02:23:42.704220664Z caller=main.go:194 msg="Starting Cortex" version="(version=1.14.0, branch=HEAD, revision=9be1ec5)"
level=info ts=2022-12-15T02:23:42.704821947Z caller=server.go:306 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2022-12-15T02:23:42.705918487Z caller=log.go:117 msg="error running cortex" err="no s3 endpoint in config file\ngithub.com/thanos-io/objstore/providers/s3.validate\n\t/__w/cortex/cortex/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:348\n …
```
=> Building Arm Images

CHANGELOG.md, pkg/tracing/sampler/sampling.go, pkg/tracing/sampler/sampling_test.go, pkg/tracing/tracing.go
Fix the NewRandomRatioBased panic.
This sampler were using a random - which is not thread safe:
```
// NewSource returns a new pseudo-random Source seeded with the given value.
// Unlike the default Source used by top-level functions, this source is not
// safe for concurrent use by multiple goroutines.
func NewSource(seed int64) Source {
var rng rngSource
rng.Seed(seed)
return &rng
}
```
```
goroutine 514103346 [running]:
math/rand.(*rngSource).Uint64(...)
/opt/brazil-pkg-cache/packages/GoLang/GoLang-1.x.108333.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0x0?)
/opt/brazil-pkg-cache/packages/GoLang/GoLang-1.x.108333.0/AL2_x86_64/DEV.STD.PTHREAD/build/lib/src/math/rand/rng.go:234 +0x92
math/rand.(*Rand).Int63(...) …
```
=> Fix tracing.NewRandomRatioBased panic

pkg/tracing/sampler/sampling_test.go
**What this PR does**: Remove flapping test in tracing sampling
**Checklist**
This was flapping like this
```
--- FAIL: Test_ShouldSample (0.13s)
--- FAIL: Test_ShouldSample/should_sample_1% (0.03s)
sampling_test.go:70: 
Error Trace:	/__w/cortex/cortex/pkg/tracing/sampler/sampling_test.go:70
Error:      	Max difference between 100 and 127 allowed is 10, but difference was -27
Test:       	Test_ShouldSample/should_sample_1%
```
=> Remove flapping test in tracing sampling

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
**What this PR does**: Fix opsgenie validation
**Checklist**
=> Fix opsgenie validation

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/shuffle_sharding_grouper.go, pkg/compactor/shuffle_sharding_grouper_test.go
Signed-off-by: Alex Le <leqiyue@amazon.com>
Fixed no compact block got grouped in shuffle sharding grouper which caused blocks with no compact marker were always grouped and tried to be compacted. With concurrency set to 1, this would prevent new blocks got compacted.
**Checklist**
=> Fixed no compact block got grouped in shuffle sharding grouper

CHANGELOG.md, pkg/compactor/blocks_cleaner.go
Signed-off-by: wangguoliang <iamwgliang@gmail.com>
Let blocks_cleaner delete blocks concurrently. And it can make blocks cleanup faster when there is large amount of blocks.
**Checklist**
=> Let blocks_cleaner delete blocks concurrently

CHANGELOG.md, pkg/cortex/tracing.go
`github.com/thanos-io/objstore` package has its own tracing library and requires to set the tracer key to get traces. See https://github.com/thanos-io/objstore/pull/33
**Checklist**
=> Fix objstore tracing instrumentation

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/split_by_interval.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go, pkg/querier/tripperware/shard_by.go
Create span to measure how long QF takes to merge responses as this method can take considerable amount of time for big response.
**Checklist**
=> Create Span for the codec MergeResponse method

pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/query_test.go, pkg/querier/tripperware/queryrange/query_range.go
`SampleStream` will be marshal/unmarshalled in query frontend for instant query response. Right now, it uses `encoding/json` library for json serialization. This PR switches it to json iter library which should provide better performance.
Existing tests should still pass.
Benchmark
UnMarshal
```
name                              old time/op    new time/op    delta
SampleStreamUnmarshalJSONITER-10    1.64ms ± 0%    1.05ms ± 0%   ~     (p=1.000 n=1+1)                          
name                              old alloc/op   new alloc/op   delta
SampleStreamUnmarshalJSONITER-10     934kB ± 0%    1090kB ± 0%   ~     (p=1.000 n=1+1)
name                              old allocs/op  new allocs/op  delta …
```
=> switch encoding/json to json iter

pkg/util/tls/test/tls_integration_test.go
Get second port without closing first one to prevent port clashing
Fixes #5038 
or tries too :) 
**Checklist**
=> Get second port without closing first one to prevent port clashing

pkg/distributor/distributor_ring_test.go, pkg/distributor/distributor_test.go, pkg/distributor/ha_tracker_test.go, pkg/distributor/ingestion_rate_strategy_test.go, pkg/distributor/query_test.go
Makes all distributors tests in parallel to speed them up
In my machine:
Previous: 
```
go test ./pkg/distributor/ -v -count 1 -parallel 1
ok  	github.com/cortexproject/cortex/pkg/distributor	48.067s
```
After:
```
go test ./pkg/distributor/ -v -count 1
ok  	github.com/cortexproject/cortex/pkg/distributor	15.635s
```
**Checklist**
=> Parallelize distributor tests

CHANGELOG.md, pkg/cortex/modules.go, pkg/querier/tripperware/instantquery/instant_query_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go, pkg/querier/tripperware/shard_by.go, pkg/querier/tripperware/test_shard_by_query_utils.go
From the trace, the instant query tripperware adds some overhead for response serilization/deserilization. For this example, it takes 15s+ while the whole query time is 23s.
The issue is, if the tenant doesn't enable vertical sharding, or the query itself is not even shardable, the additional overhead is still there and we don't have a way to skip that. This pr checks whether vertical sharding is applicable before passing the request down to the tripperware.
**Checklist**
=> Skip instant query round tripper if sharding is not applicable.

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Fixes an issue where the ingesters were returning empty response for metadata APIs.
**Checklist**
=> Bug fix: ingesters returning empty response

pkg/distributor/query.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/merge.go, pkg/querier/tripperware/merge_test.go
Use `string(labels.Bytes())` instead of `labels.String()` for the deduplication map key. Since we don't have to print the map key, we just use the key to find the samples and as long as it remains the same sorting order, we can safely replace the method.
Benchmark 
```
name    old time/op    new time/op    delta
Label-10    9.60µs ± 0%    1.60µs ± 0%   ~     (p=1.000 n=1+1)
name    old alloc/op   new alloc/op   delta
Label-10    7.79kB ± 0%    3.71kB ± 0%   ~     (p=1.000 n=1+1)
name    old allocs/op  new allocs/op  delta
Label-10       111 ± 0%         2 ± 0%   ~     (p=1.000 n=1+1)
```
**Checklist**
=> Use labels Bytes() rather than String() for map key

CHANGELOG.md, pkg/util/push/push.go
Signed-off-by: Daniel Deluiggi <ddeluigg@amazon.com>
Change the log level from returns of Push API. 5xx still logs error and now 4xx logs warn. Do not log on 429 status to avoid overloading the service
**Checklist**
=> Change log level for 4xx on Push API. Do not log on 429

CHANGELOG.md, pkg/alertmanager/alertmanager.go
Allow cortex to read time_intervals as the new feature from upstream alert manager. See https://github.com/prometheus/alertmanager/pull/2779
mute_time_intervals will be still working
**Checklist**
=> allow time interval for alert manager

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/distributor.go, pkg/alertmanager/distributor_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
**What this PR does**: Support enabled_tenants and disabled_tenants in alertmanager 
Fixes #5115
**Checklist**
=> Support enabled_tenants and disabled_tenants in alertmanager

CHANGELOG.md, pkg/ingester/ingester.go
When streaming metadata from ingesters we are closing the querier before the request finish.
This cause a race condition when the blocks from where the metadata is being read is deleted (when we close the querier we decrement the pendingRead waitgroup on the blocks allowing it to be deleted)
See: https://github.com/cortexproject/cortex/blob/a63bbb07fe4fbfbf40d8fa0623e5f8e0bf9c4d3c/pkg/ingester/ingester.go#L1333-L1334
https://github.com/cortexproject/cortex/blob/a63bbb07fe4fbfbf40d8fa0623e5f8e0bf9c4d3c/pkg/ingester/ingester.go#L1317-L1321
This information is being read from an mmaped file on the index header, see:
https://github.com/prometheus/prometheus/blob/c70d85baed260f6013afd18d6cd0ffcac4339861/tsdb/index/index.go#L1517
This PR create commons methods that also …
=> Fix Segmentation fault on ingester due race condition when reading blocks that are being deleted

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/runtime-config.yaml, docs/configuration/single-process-config-blocks-local.yaml, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/storage/tsdb/config.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Signed-off-by: sahnib <sahnib@amazon.com>
Makes TSDB max exemplars config per tenant. **Note that the MaxExemplars value is passed down to prometheus tsdb at `tsdb.Open` call, hence this configuration would not be hot loaded at this time - unless the ingesters re-open the database handle, or go through a restart.**. 
Fixes [#5016](https://github.com/cortexproject/cortex/issues/5016)
**Checklist**
=> Make TSDB max exemplars config per tenant 

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
Signed-off-by: sahnib <sahnib@amazon.com>
This PR renames the `blocks-storage.tsdb.max-exemplars` flag in limits to `ingester.max-exemplars`, because this limit is applied at ingestion time. The current name is confusing because it points to store gateway instead of ingester. 
**Checklist**
=> Rename max exemplars limit flag to ingester.max-exemplars.

CHANGELOG.md, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, cmd/thanosconvert/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile, packaging/fpm/Dockerfile
Update Dockerfiles to use Alpine 3.17
**Checklist**
=> Update Dockerfiles to use Alpine 3.17

CHANGELOG.md, pkg/ring/kv/dynamodb/client.go, pkg/ring/kv/dynamodb/dynamodb.go, pkg/ring/kv/dynamodb/dynamodb_test.go
Signed-off-by: Daniel Deluiggi <ddeluigg@amazon.com>
Dynamodb has limitations on size of batch request. The current limit is at 25 actions per request.
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html
Adding slices on batch for ddb kv store.
**Checklist**
=> Dynamodb kv batch on slices

pkg/tracing/tracing.go, pkg/tracing/tracing_test.go
We are merging 2 resources in `newResource` when initializing. However, one resource is using the schema URL for v1.12.0 while another one is using the schema URL for v1.17.0.
In order to fix this, I removed merging two resources, instead just statically set the service name attribute.
https://github.com/cortexproject/cortex/issues/5139
**Checklist**
=> Fix conflict schema url when initializing resources

pkg/frontend/transport/handler.go
Only initialize query stats if it is not enabled. If stats exist in the context then we don't initalize a new one.
**Checklist**
=> initialize querier stats in QFE only if it is not enabled

.github/workflows/test-build-deploy.yml, CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/blocks-storage/store-gateway.template, docs/configuration/config-file-reference.md, integration/e2e/cache/cache.go, integration/e2e/images/images.go, integration/querier_test.go, pkg/cortexpb/compat_test.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/redis_client_config.go, pkg/storage/tsdb/redis_client_config_test.go
Support redis as backend for caching bucket and index cache. Previously only in memory and memcached are supported cache backends.
Fixes #5056 #5049
**Checklist**
=> Add redis as index cache and caching bucket backend

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/split_by_interval.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go, pkg/querier/tripperware/shard_by.go
This PR addresses a bug in query vertical sharding where the merged result doesn't sort the series by sample value for `sort()` and `sort_desc()` functions.
Fixes: https://github.com/thanos-io/thanos/issues/6059
Thanos PR: https://github.com/thanos-io/thanos/pull/6125
**Checklist**
=> Fix sorted queries do not produce sorted results for shardable queries

README.md
Since 1.14.0 is released, change from "to be" to "was.
LOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Update README.md for chunk deprecation note

pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/queryrange/query_range.go
As the json are generated by cortex itself we should be able to trust that they are valid. This PR disable this validation as it can be very memory intensive as shown bellow:
**Checklist**
=> Disable `ValidateJsonRawMessage` flag from jsoniter

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
- This PR fixes a bug in the `/api/v1/series` which returns status code `500` when the query hits the limits.
- The validation error is converted into a 422 error here: https://github.com/cortexproject/cortex/blob/master/pkg/querier/error_translate_queryable.go#L39
- Therefore the error should be wrapped inside `validation.LimitError`. We do this in other APIs: https://github.com/cortexproject/cortex/blob/master/pkg/distributor/query.go#L326
```
level=warn ts=2023-02-23T00:00:00Z caller=logging.go:86 msg="POST /prometheus/api/v1/series (500) 1.232489841s Response: \"{\\\"status\\\":\\\"error\\\",\\\"errorType\\\":\\\"internal\\\",\\\"error\\\":\\\"the query hit the aggregated data size limit (limit: 1000000000 bytes)\\\"}\" ws: false; Accept: application/json, …
```
=> Fix returning 5XX for limits errors in series API

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go
- This ports the sharding fix implemented in Thanos: https://github.com/thanos-io/thanos/pull/6125
- If the root expr is `topk` or `bottomk`, the response will be concatenated without a global sort.
- If the AST contains `sort` or `sort_desc`, the response will be sorted by values.
- Else, the response will be sorted by labels.
Examples:
| # | Query                                                                | Merge mechanism                | Prometheus Link                                                                                                                                                                                               | Remarks                     |
|---|----------------------------------------------------------------------|------------- …
=> Fix the incorrect ordering for topk and bottomk in shardable queries

docs/configuration/config-file-reference.md, tools/doc-generator/main.go
A reference should either have a logical or alpanumeric order. The previous layout had neither, which made navigating the reference quite a challenge IMHO.
I've restructered the reference to be alphanumeric order, which makes navigating the page easier.
**Checklist**
=> reorder cortex config reference

CHANGELOG.md, pkg/ingester/ingester.go
We are using this new log line added recently to investigate issues with ingester. The log line should be at debug level. We have distributor client logs to a general service error
**Checklist**
=> Decrease log level for ingester partial failure

CHANGELOG.md, pkg/compactor/shuffle_sharding_planner.go, pkg/compactor/shuffle_sharding_planner_test.go
Shuffle sharding planner should not fail the compaction if one of blocks in group is under visit by other compactor. Instead, it should return nil group so that compactor would move onto next compaction.
**Checklist**
=> Fixed issue that shuffle sharding planner return error if block is under visit by other compactor

CHANGELOG.md, pkg/cortexpb/slicesPool.go, pkg/cortexpb/slicesPool_test.go, pkg/cortexpb/timeseries.go, pkg/cortexpb/timeseries_test.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/client/client.go
Just some tentative to reuse the write requests and the byte slices when marshaling the write requests from distributors to ingesters.
Bench Results: 
```
BenchmarkMarshallWriteRequest/no-pool-16         	   40658	     29358 ns/op	   19136 B/op	       2 allocs/op
BenchmarkMarshallWriteRequest/no-pool-16         	   40474	     29386 ns/op	   19136 B/op	       2 allocs/op
BenchmarkMarshallWriteRequest/no-pool-16         	   40921	     29294 ns/op	   19136 B/op	       2 allocs/op
BenchmarkMarshallWriteRequest/no-pool-16         	   40840	     29317 ns/op	   19136 B/op	       2 allocs/op
BenchmarkMarshallWriteRequest/no-pool-16         	   40756	     29344 ns/op	   19136 B/op	       2 allocs/op
BenchmarkMarshallWriteRequest/byte_pool-16       	   44792	     26797 ns/op …
```
=> Reuse write request from distributor to Ingesters

integration/e2ecortex/client.go, integration/query_frontend_test.go, pkg/frontend/transport/handler.go
To prevent reading the reader multiple times in #5201, instead we first parse the form to read the body if it is a POST request, then we set body to the buffer we copied. This could make sure we read the buf later only once.
I have added integration test cases for query frontend with vertical sharding enabled. Tests should pass after this fix.
Note: 
If it is a GET request and it sets body to non empty, in this case the buffer is nil so we will set body to nil. But I think this is fine as `ParseForm` method only cares about url params and ignores body if it is a GET request.
Fixes #5201
**Checklist**
=> Fix read reader multiple times in QFE

CHANGELOG.md, pkg/util/grpcencoding/snappy/snappy.go
CPU usage can be reduced by up to 25% with this optimization.
**Checklist**
=> Implement grpc.Compressor.DecompressedSize for snappy to optimize memory allocations

CHANGELOG.md, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go, pkg/util/grpcencoding/snappy/snappy.go
`BucketWithRetries` for S3 reused the same Reader inside retry logic which caused empty content got uploaded during retry. This PR should fix this problem by only retrying upload operation if the input Reader is seekable.
**Checklist**
=> Fix S3 BucketWithRetries upload empty content issue

CHANGELOG.md
**What this PR does**: Fix changelog order to be [CHANGE], [FEATURE], [ENHANCEMENT], [BUGFIX]
**Checklist**
Necessary for 1.15 release
=> Fix changelog order to be CFEB

pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go
This PR fixed an uncaught code logic introduced in #5217 which return `nil` even there is error being returned after retrying bucket operation. Also, added more logging for troubleshooting bucket operation failures.
**Checklist**
=> Fix nil error got returned when there was error after retry

integration/query_fuzz_test.go
Previous in the query fuzzer integration test, we only log the failed cases but didn't fail the test itself. 
Because at that time, we have many known cases of vertical sharding that could cause inconsistent results. Now since those known issues are fixed, we can enable to fail the fuzzer test so that we can know it failed and check workflows in detail.
**Checklist**
=> Fail query fuzzer test if inconsistent

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/series.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go, pkg/util/validation/limits.go
1. Support OOO samples ingestion. This is a new feature from Prometheus v2.39.x and we just need to enable it via flag.
2. Add `out_of_order_time_window` to limits so that each tenant can configure their own OOO time window.
3. Add `out_of_order_cap_max` in the ingester configuration. This is not a per-tenant configuration.
Fixes https://github.com/cortexproject/cortex/issues/4895
**Checklist**
=> Support out of order samples ingestion

docs/api/_index.md
Because we are going to release v1.15.0 soon, we should update the API doc with new API. 
I also introduced a column called "available since" as a way to allow API doc to be updated at the same time as code change. I will find some time to backfill the "available since" column for other APIs.
Fixes #4984
**Checklist**
=> Add build info API to doc

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go
**What this PR does**:  Following metrics were [updated](https://github.com/cortexproject/cortex/pull/5177) in thanos from summary to histogram. 
cortex_bucket_store_series_blocks_queried
cortex_bucket_store_series_data_fetched
cortex_bucket_store_series_data_size_touched_bytes
cortex_bucket_store_series_data_size_fetched_bytes
cortex_bucket_store_series_data_touched
cortex_bucket_store_series_result_series
Fixes #5216
**Checklist**
=> Store Gateway: Convert metrics from summary to histograms

CHANGELOG.md, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go
Store gateway may panic if the s3 client return nil error with some nil value.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12a2e04]
goroutine 10142 [running]:
github.com/thanos-io/objstore.(*timingReadCloser).Close(0xc01643ea80)
/go/src/github.com/cortexproject/cortex/vendor/github.com/thanos-io/objstore/objstore.go:638 +0x24
github.com/thanos-io/objstore.(*tracingReadCloser).Close(0xc0187b2e80)
/go/src/github.com/cortexproject/cortex/vendor/github.com/thanos-io/objstore/tracing.go:149 +0x2d
github.com/thanos-io/thanos/pkg/runutil.CloseWithLogOnErr({0x3e2b8c0, 0xc000dafb80}, {0x7f16340f7a60?, …
```
=> Catch context error in the s3 bucket client

pkg/ring/model_test.go
This PR adds unit test to `resolveConflicts` function
Fixes #5079 
**Checklist**
=> Add unit test for resolveConflicts function

docs/contributing/_index.md, docs/contributing/how-to-update-the-build-image.md
Fixes typos and a grammar error in the contributing section of the docs
**Checklist**
=> Fix typos and a grammar error

pkg/compactor/compactor_test.go, pkg/storage/bucket/client_mock.go, pkg/storage/bucket/client_test.go
fix compactor unit test error for TestCompactor_ShouldCompactOnlyShardsOwnedByTheInstanceOnShardingEnabledWithShuffleShardingAndMultipleInstancesRunning case:
1.fix data race in ClientMock.MockGet(), the following code will cause a data race:
```		// Since we return an ReadCloser and it can be consumed only once,
// each time the mocked Get() is called we do create a new one, so
// that getting the same mocked object twice works as expected.
mockedGet := m.On("Get", mock.Anything, name)
mockedGet.Run(func(args mock.Arguments) {
mockedGet.Return(ioutil.NopCloser(bytes.NewReader([]byte(content))), err)
})
```
2.multiple compactor instances run out of order. We cannot use the MockGetTimes method to ensure that visit-mark.json is accessed by the correct instance. We …
=> fix compactor unit test error

CHANGELOG.md, integration/e2ecortex/client.go, integration/query_frontend_test.go, pkg/frontend/transport/handler.go
Fix the remote read bug in query frontend.
The bug is that `r.ParseForm` doesn't handle the remote read protobuf type request body correctly.
Fixes #5253
**Checklist**
=> fix remote read error in query frontend

CHANGELOG.md, integration/e2ecortex/client.go, integration/querier_test.go, integration/query_frontend_test.go, integration/query_fuzz_test.go, integration/zone_aware_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/error_translate_queryable.go, pkg/util/limiter/query_limiter.go
Handle the gRPC response code change. Cortex querier should identify the error when we reach the limit and convert it into correct validation error.
Didn't add unit test, but I added an E2E test which should be able to ensure the correctness.
Fixes #5285
**Checklist**
=> Handle grpc code resource exhausted for store gateway

pkg/cortex/modules.go, pkg/frontend/transport/handler.go, pkg/querier/worker/frontend_processor.go, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/worker.go
Log query response size in query frontend query stats log.
Also I added a line of log to log the response size and http status code in querier. This is helpful to track whether a user's response has went beyond the max response body size.
**Checklist**
=> log query response size in QFE and querier

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
Validate the PagerDuty config to block setting `routing_key_file` and `service_key_file`.
This fields got introduced on: https://github.com/prometheus/alertmanager/commit/1045dc0f2144e1463941d56210e0e6ebaff2a73e
**Checklist**
=> Validating new fields on the PagerDuty AM config

CHANGELOG.md, pkg/cortexpb/compat.go, pkg/cortexpb/cortex.pb.go, pkg/cortexpb/cortex.proto, pkg/cortexpb/timeseries.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/series.go, pkg/querier/tripperware/instantquery/instantquery.pb.go, pkg/ruler/compat.go
* Update Cortex proto with the new native histogram format from [prometheus](https://github.com/prometheus/prometheus/blob/0bf707e288eaa8694105e53c81a102017529793d/prompb/types.pb.go#L367)
* Create a new reason on the discarded metric: `native-histogram-sample`.
**Checklist**
=> Creating label `native-histogram-sample` on the `cortex_discarded_samples_total` to keep track of discarded native histogram samples

pkg/querier/blocks_store_queryable_test.go, pkg/querier/chunk_store_queryable_test.go, pkg/querier/error_translate_queryable_test.go, pkg/querier/querier_test.go
This pr tries to disable parallel tests if thanos engine is enabled. We saw data race in our tests previously because we are also parallelize the initialization of the thanos query engine. However, the initialization is not thread safe.
So this pr I am trying to disable parallelization for it and also just removed thanos engine tests if possible in some tests, in order to make tests execution faster.
**Checklist**
=> Disable parallel tests when thanos engine is enabled

CHANGELOG.md, integration/ruler_test.go, pkg/ruler/compat.go
Adding user label to cortex_ruler_queries_failed_total, cortex_ruler_queries_total, cortex_ruler_write_requests_failed_total, cortex_ruler_write_requests_total metrics. This would allow for better tracking of failures at a user level
**Checklist**
- [ X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Add user label to ruler query and write metrics

.github/workflows/test-build-deploy.yml, Makefile, build-image/Dockerfile
if it's not the proper way to do this, 
just let me know
Bump the go version to remove some CVEs detected by our scans.
go version : 1.20.1, solved in 1.20.3
CVE-2023-24538  / critical
CVE-2023-24536 / high
CVE-2023-24537 / high
CVE-2023-24534 / high
Nonw
**Checklist**
=> upgrade to go 1.20.4

CHANGELOG.md, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ring/batch.go
Add more detailed spans for push requests path. 
**Checklist**
=> Add span on push for distributor and ingester

pkg/distributor/distributor.go
We are seeing very high latencies on label related APIs. Having the additional info in the trace span can help us troubleshoot the issue and understand the bottleneck. Especially to see how long it takes to merge responses and deduplicate.
**Checklist**
=> Add additional tracing span for merging labels responses

CHANGELOG.md, integration/query_frontend_test.go, pkg/cortex/modules.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_middlewares.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/instantquery/shard_by_query_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/step_align.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go, pkg/querier/tripperware/subquery.go, pkg/querier/tripperware/subquery_test.go
In Prometheus, there is a step size check to make sure we don't have too many samples for a series for range query because it takes step and range parameters https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L503.
However, there is no such check for subquery, which makes subqueries to have very large steps such as `up[30d:1s]`. This could easily OOM kill queriers.
This pr adds the same step size check in QFE to reject such queries.
**Checklist**
=> Reject small subquery step size in query frontend

.github/workflows/test-build-deploy.yml, Makefile, build-image/Dockerfile
Cherry pick change from main branch to address critical CVEs.
=> Cherry pick "upgrade to Go 1.20.4" from main branch

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/shuffle_sharding_grouper.go
Exposing Thanos `accept-malformed-index` (https://github.com/thanos-io/thanos/blob/7000066202b4f0f8b2ecab548c5c8d08dfa89532/pkg/compact/compact.go#L340) to Cortex compactor
**Checklist**
=> Exposing Thanos accept-malformed-index to Cortex compactor

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager_client.go
Make Alert manager grpc `MaxRecvMsgSize` and `MaxSendMsgSize` configurable.
Fixes #5330 
**Checklist**
=> Make AM grpc MaxRecvMsgSize and MaxSendMsgSize configurable

CHANGELOG.md, pkg/storage/tsdb/bucketindex/updater.go, pkg/storage/tsdb/bucketindex/updater_test.go
Bucket index updater should ignore meta not found for partial blocks to avoid increasing `thanos_objstore_bucket_operation_failures_total` metric when checking partial blocks.
**Checklist**
=> Bucket index updater should ignore meta not found for partial blocks

pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/query.go
Create jsoniter SampleStream Decoder to optimize its deserialization.
QueryFrontend can benefit from this as it deserialize the responses from the queriers:
```
goos: linux
goarch: amd64
pkg: github.com/cortexproject/cortex/pkg/querier/tripperware/instantquery
cpu: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
│   /tmp/old   │              /tmp/new               │
│    sec/op    │    sec/op     vs base               │
_Decode/100_samples-32       280.5µ ± ∞ ¹   209.3µ ± ∞ ¹  -25.36% (p=0.008 n=5)
_Decode/1000_samples-32      2.875m ± ∞ ¹   2.133m ± ∞ ¹  -25.82% (p=0.008 n=5)
_Decode/10000_samples-32     28.83m ± ∞ ¹   21.55m ± ∞ ¹  -25.24% (p=0.008 n=5)
_Decode/100000_samples-32    304.5m ± ∞ ¹   247.3m ± ∞ ¹  -18.79% (p=0.008 n=5)
_Decode/1000000_samples-32 …
```
=> Optimize the decoding of SampleStream

cmd/cortex/main.go, cmd/cortex/main_test.go
Due to the capacity problem of prometheus, we are trying to find a long-term storage system. We are currently investigating cortex. After starting from the source code for the first time, we found that the startup log cannot be understood. 
```
GOPATH=/Users/fuling/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/yg/39mj_zbd46532cfbdh1f8fx40000gp/T/GoLand/___go_build_github_com_cortexproject_cortex_cmd_cortex github.com/cortexproject/cortex/cmd/cortex #gosetup
/private/var/folders/yg/39mj_zbd46532cfbdh1f8fx40000gp/T/GoLand/___go_build_github_com_cortexproject_cortex_cmd_cortex
level=info ts=2023-04-24T02:22:01.29409Z caller=main.go:194 msg="Starting Cortex" version="(version=, branch=, revision=7ef779119d1d2e8bcb63f4099dac3f39979880ac)"
level=warn …
```
=> Return a more friendly error message when there is no configuration file

CHANGELOG.md, pkg/frontend/transport/handler.go
Include query length in query frontend query stats log. This can be helpful to filter large queries using some log search tool.
**Checklist**
=> include query_length field in query stats log

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Add a per user counter metrics for number of queries. This is helpful to track per tenant QPS.
=> Add a per user query counter metric

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Revert the query counter I added in last pr.
It turns out there is already a metric for the same purpose. https://github.com/cortexproject/cortex/blob/master/pkg/querier/tripperware/roundtrip.go#L108
**Checklist**
=> Revert new cortex_queries_total metric

CHANGELOG.md, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go
Currently the logic for existing store gateway instances to re-sync block is too aggressive, leading to unnecessary re-sync when pods are restarted due to OOM or when doing rollout deployment.
Unnecessary re-sync increases chance of OOM and query unavailability.
- `ring.HasReplicationSetChanged` is used to determine whether re-sync should be performed (true if number of instances, or state/address/token of any instance changes)
- Store gateway is scaled up => Number of instances in the ring is increased, then the instance state changes from JOINING -> ACTIVE => existing instances re-sync blocks at most twice, once for number of instance change and once for state change
- Store gateway is scaled down => Instance state changes from ACTIVE -> LEAVING, then number of …
=> Do not resync blocks in running store gateways during rollout deployment and container restart

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go
Add some other bucket store metrics from store gateway. They are:
- `cortex_bucket_store_sent_chunk_size_bytes` a histogram to understand how much chunk size per request
- `cortex_bucket_store_postings_size_bytes ` a histogram to understand how much posting size we have per request
- `cortex_bucket_store_empty_postings_total ` a counter to know how many empty postings we have
**Checklist**
=> Add additional bucket store metrics

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/frontend/v1/frontend.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/scheduler.go, pkg/storegateway/gateway_test.go, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go, pkg/util/shard.go, pkg/util/shard_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This PR allows querier and store-gateway tenant shard sizes to be configured as a percentage of a total 
For backwards compatibility, the data type was changed to float64.
- If the configured value is < 1, it'll be treated as a percentage.
- If the value is > 1, it'll be treated as a constant number
Fixes #5374
**Checklist**
=> Allow shard sizes to be percent of instances

CHANGELOG.md, pkg/ring/kv/etcd/etcd.go
Adds context timeouts to calls to etcd from the KV store etcd implementation.
When called with a context without deadline, underlying calls to etcd from the etcd implementation of KV store can block forever when etcd is unavailable, emitting no logs or KV metrics indicating the problem.
For consistency and predictability, this PR adds timeouts to the context at the KV store level, rather than relying on clients of the KV store to specify deadlines at every call. This allows calls to timeout and emit metrics that can be alerted and acted on.
N/A
**Checklist**
=> Added timeouts to contexts when calling etcd

pkg/querier/blocks_store_queryable.go
Reduce store gateway stats logs by only logging those queries that got series matched.
**Checklist**
=> Don't log store gateway query stats if no series matched

CHANGELOG.md, pkg/ring/basic_lifecycler.go, pkg/ring/lifecycler.go, pkg/ring/ticker.go
In some cases where the service scale at the same moment, cortex can create a influx of message in the same time. This helps spread the load in the kv store.
**Checklist**
=> Add jitter for heartbeat

CHANGELOG.md, pkg/ring/ring.go, pkg/ring/ring_test.go
`ring.Get` that should return n (or more) instances which form the replicas for the given key uses the following configs:
- `ring.cfg.ReplicationFactor` to control how many replicas you would like to use per key
- `ring.cfg.ZoneAwarenessEnabled` to allow replicas to be across the zones evenly
Problem is, when `ZoneAwarenessEnabled` is enabled and `ReplicationFactor` is greater than number of available zones, the function was silently ignoring the ReplicationFactor and returned only one instance from each zone:
https://github.com/cortexproject/cortex/blob/a307fc04ce295391f8927da19299bb5d26ecfbd8/pkg/ring/ring.go#L376-L380
RF doesn't need to be bound to number of zones, and the following scenario is valid as well:
- There are 3 available zones
- Setting RF to 6 would …
=> Allow RF greater than number of zones to select more than one instance per zone

pkg/storegateway/bucket_stores.go
Same as https://github.com/thanos-io/thanos/pull/6449
**Checklist**
=> Estimate chunk and series size from meta.json file

docs/getting-started/_index.md
I was following [the single instance, single process set up](https://cortexmetrics.io/docs/getting-started/#single-instance-single-process) for Cortex but when I was trying to add data source using `http://host.docker.internal`, I was getting this error:
`Error reading Prometheus: Post "http://host.docker.internal:9009/prometheus/api/v1/query": dial tcp: lookup host.docker.internal on 192.168.1.1:53: no such host`
I guess, `host.docker.internal` is not supported before Ubuntu 20.04. Even though I am using Ubuntu 22.04, I still got that error.
So, I created this PR for the folks who face this problem so that they can run `hostname -I | awk '{print $1}'` and paste the result to Grafana and can have Grafana up and running.
**Checklist**
=> Update single instance, single process example in the getting started document

CHANGELOG.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storegateway/gateway_ring.go
Add `-store-gateway.sharding-ring.keep-instance-in-the-ring-on-shutdown`.
The new config sets `KeepInstanceInTheRingOnShutdown` configuration in basic_lifecycler, which skips unregistering instance if set to true.
https://github.com/cortexproject/cortex/blob/6dd44ee4961d37d3ca2e79ef48714fee58b37839/pkg/ring/basic_lifecycler.go#L244-L252
Similar to `-ingester.unregister-on-shutdown`, this new config is helpful when you want to eliminate ring-sync during rollout deployment.
n/a
**Checklist**
=> Expose KeepInstanceInTheRingOnShutdown config for store gateway

CHANGELOG.md, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/ring/model.go, pkg/ring/model_test.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go
During rollout deployment of store gateway, the ring check logic is expected to return true only if:
1. Number of instances in the ring changed
2. Tokens of the instances have changed
3. Zone of the instances have changed
However, the comparison logic`hasReplicationSetChangedExcluding` sorts the instance descriptions by address before comparing, returning true when the new instance address changes the order of the instances:
1. Before: [{Addr: 127.0.0.1, Tokens: {1, 2, 3}}, {Addr: 127.0.0.2, Tokens: {4, 5, 6}]
2. After: [{Addr: 127.0.0.3, Tokens: {1, 2, 3}}, {Addr: 127.0.0.2, Tokens: {4, 5, 6}]
3. hasRingChanged should return false, but it was returning true because of:
https://github.com/cortexproject/cortex/blob/ca0ce934d3e2d0ff0ab64c97971c04a8ba535ca3/pkg/ring/rep …
=> Fix bug in store gateway ring comparison logic

pkg/ring/lifecycler.go
Fix flaky `TestShuffleShardWithCaching` test.
There is a race condition where we flip the state from PENDING to ACTIVE and we heartbeat before storing on the KV.
This race condition became more evident after https://github.com/cortexproject/cortex/pull/5404 as now wen can heartbeat faster than the  heartbeat interval.
The fix seems to be get the tokens from the lifecycle (not only the state) when performing the heartbeat.
**Checklist**
=> Fix flaky `TestShuffleShardWithCaching` test

CHANGELOG.md, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/ring/batch.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util.go, pkg/ring/util_test.go
Given the conditions:
1. Replication factor is greater than number of zones
2. One instance is added/removed from the ring
the replication set returned by `ring.Get` can contain more than one member changed. Consider the following scenario:
Initial state:
- There are 12 store-gateways in the zone-aware ring that has 3 zones
- We are calling `ring.Get` for the block `01H3EBEAT3EZA6RH49Y0PGBRQ0`, which is used for querier to find list of store-gateways to query for, and store-gateways to know if it needs to sync that block
- With RF=6 and zone-aware replication, we'll return the following six pods for the block:
- sg1, sg3, sg5, sg6, sg8, sg10
Adding a new store-gateway:
- sg13 is added such that its token falls between sg1 and sg2
- With RF=6 and zone-aware …
=> Fix bug where adding/removing instance with RF > len(zones) will introduce more than one member change in Get replication set

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go
Rename `cortex_bucket_store_cached_postings_compression_time_seconds` to `cortex_bucket_store_cached_postings_compression_time_seconds_total`.
The metric in Thanos is `thanos_bucket_store_cached_postings_compression_time_seconds_total`. It is a counter, not a histogram so add `_total` suffix to the Cortex metric as well.
**Checklist**
=> Add _total suffix to cached posting compression time metric

pkg/ring/lifecycler.go, pkg/ring/ring_test.go
Add a min value to jitter delay.
Improve flake test
On #5404 while adding jitter to heartbeat, we increased the chance of a concurrency issue between autoJoin and heartbeat. We do have in some cases where autoJoin fails and need to retry situations where a instance can go to ACTIVE with no tokens.
On #5428, we try to mitigate it by also synicng the tokens, but this can create performance overhead when we have conflict tokens between instances.
We are here adding a min value for the jitter to avoid concurrency and braking tests. 
**Checklist**
=> Avoid concurrency between heartbeat and autoJoin

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor_ring.go, pkg/compactor/compactor_ring_test.go
Add  configuration for compactor to save token on file
In some scenarios (slow compactor), we can run into situations that 2 compactor are compacting the same customer. Compactor-A start cleaning from tenant-123, then a service restart occur and compactor-b with the new tokens is the owner of tenant-123, compactor-b also start cleaning of tenant -123.
This change avoids multiple resharding when compactors are restarted.
**Checklist**
=> Enable compactor to use 'TokensFilePath' on ring lifecycler

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/cortexpb/extensions.go, pkg/cortexpb/extensions_test.go, pkg/distributor/distributor.go, pkg/util/grpcclient/grpcclient.go, pkg/util/grpcclient/signing_handler.go, pkg/util/grpcclient/signing_handler_test.go
Sign the write requests to prevent future data corruption as https://github.com/cortexproject/cortex/issues/5419  
Related to: #5419
**Checklist**
=> [Experimental] Signing write requests

pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go, pkg/storage/tsdb/bucketindex/markers_bucket_client.go, pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go, pkg/storage/tsdb/testutil/objstore.go
Fix objstore retry when uploading markers.
These operations were not being retried as we were wrapping the original `io.Reader` into a `bytes.NewBuffer` which is not seek-able. The fix is simply to wrap them into a `bytes.NewReader` instead `bytes.NewBuffer`.
**Checklist**
=> fix retry on markers

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/storage/bucket/sse_bucket_client.go, pkg/storage/bucket/sse_bucket_client_test.go, pkg/storage/tsdb/testutil/objstore.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/util/errors/errors.go, pkg/util/errors/errors_test.go
This is a follow up of https://github.com/cortexproject/cortex/pull/5420 and basically change the return code  from `ResourceExhausted` to `PermissionDenied`.
Also adding the changelog that was forgotten on the last PR.
**Checklist**
=> Changing return code from storegateway for CMK errors

CHANGELOG.md, pkg/frontend/v2/frontend.go, pkg/frontend/v2/frontend_scheduler_worker.go
We found out that when using query frontend v2 mode (with query scheduler), sometimes queries at store gateway are not successfully canceled even if requests canceled at query frontend. We also tested the same query using query frontend v1 but there is no such issue.
After some investigation, the issue turns out the `cancelCh` being a blocking channel. So when there are a few requests to cancel, sometimes the cancellation signal cannot enqueue, resulting downstream request cannot be canceled.
```
select {
case <-ctx.Done():
if cancelCh != nil {
select {
case cancelCh <- freq.queryID:
// cancellation sent.
default:
// failed to cancel, ignore.
}
}
```
Using the code above, it will go to the `default` statement rather than enqueuing the cancellation successfully.
This …
=> Fix query frontend v2 failed to cancel request

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/querier/blocks_finder_bucket_index.go, pkg/querier/blocks_finder_bucket_index_test.go, pkg/storage/tsdb/bucketindex/loader.go, pkg/storage/tsdb/bucketindex/loader_test.go, pkg/storage/tsdb/bucketindex/storage.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/caching_bucket_test.go, pkg/storage/tsdb/testutil/objstore.go
This PR introduce a new file to be saved together with the bucket index with the status of the last sync (bucket index update).
The bucket sync status is used on ingesters/queriers/storegateways/compactors to halt any operation for a given tenant if the bucket index could not be updated due CMK errors.
**Checklist**
=> Implementing Bucket index sync status file

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/providers/s3/s3.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go, vendor/modules.txt
Implementing multi-level caching for the index cache.
With the PR we will be able to configure multiples caching layers like for example "inMemory" as L1 cache and "memcache" as l2 cache.
The configuration will now accept a `Comma separated ordered list of index cache backend type` and cortex will use the cache in order (l1,l2,ln).
Currently we don't "backfill" the data from a Ln+1 to a Ln cache but this can be implemented in the future.
PS: This change should be a NoOp if only 1 cache is configured.
**Checklist**
=> Implementing multi level index cache

CHANGELOG.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_test.go
Add the alert name in the error log
**Checklist**
=> add alert name in error log

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/user_state_test.go
Adds an admin contact address flag to the ingester and uses it while printing error messages when hitting limits.
Fixes #5452 
**Checklist**
=> Add ingester flag to customize message in limiter error messages

CHANGELOG.md, pkg/storage/tsdb/bucketindex/updater.go, pkg/storage/tsdb/bucketindex/updater_test.go
Improve cases where we have cleaner concurrency for the same tenant.
Compactor can run cleaner for the same tenant at the same time (eg. ring resharding)
In that case we can have some concurrence issues with deletion blockers
Example:
Compactor1 - c1
Compactor2 - c2
T0 - c1 start cleaner (list blocks and deletion markers)
T1 - c2 start cleaner (list blocks)
T2 - c1 start deletes all blocks and global markers
T3 - c2 continue cleaning (list global markers)
In this scenario, it is possible that c2 will find a block but not the global marker because c1 already delete it. Leaving a dangling block on the index causing consistency check failures at queries.
To avoid this scenario, we are changing the order we look for blocks. First global markers and then all blocks. We …
=> Avoid concurrency cleaners

pkg/ingester/metrics.go
=> Remove deprecated ingester metrics

integration/e2e/metrics.go, integration/querier_test.go
Trying to fix the flaky test of https://github.com/cortexproject/cortex/actions/runs/5652118655/job/15313406382?pr=5477.
Error log
```
querier_test.go:273: 
Error Trace:	/home/runner/work/cortex/cortex/integration/querier_test.go:273
unable to find metrics [thanos_store_index_cache_requests_total] with expected values. Last error: <nil>. Last values: [26]
Test:       	TestQuerierWithBlocksStorageRunningInMicroservicesMode/blocks_sharding_disabled,_ingester_gRPC_streaming_disabled,_multilevel_index_cache_(inmemory,_memcached),thanosEngine=false
```
Expected value is 28 but it is flaky and sometimes become 26.
Tried to reproduce this issue locally. When the flakiness happens, metrics from 2 store gateway will be below. Requests …
=> Fix flaky integration test of multi level index cache

CHANGELOG.md, pkg/querier/blocks_store_balanced_set.go, pkg/querier/blocks_store_balanced_set_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/replication_set.go
This pr changes `GetClientsFor ` method of `BlocksStoreSet ` interface to take an additional map of retried zones.
`blocksStoreReplicationSet` is mainly changed. If zone awareness is not enabled, the logic should be the same. If enabled, the algorithm is:
1. There is a map to track number of attempts for each zone per block.
2. For each block, we get the min attempts over all zones.
3. Iterate all instances in the replication set, if the instance is located in the zone where its attempts == minAttempts, pick the target instance.
Fixes #5468
**Checklist**
=> Fix querier try store gateways on different zones

integration/e2e/metrics.go, integration/querier_test.go
`thanos_memcached_operations_total` will also be affected by cache hits and the flaky tests so this pr tries to fix it.
The logic is try to query L0 and L1 metrics and understand cache hits. For each cache hits in L0, we have one less requests to memcached.
**Checklist**
=> Fix flaky on thanos_memcached_operations_total metrics

pkg/cortex/modules.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/shard_by_query_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/roundtrip.go
This pr removes the `noStepSubQueryInterval` param in both instant and range codec.
Also make sure we only check `SubQueryStepSizeCheck` once at the initial round tripper. No need to check individually in separate tripperwares.
**Checklist**
=> Unify subquery step size check in a single place

integration/querier_test.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go
This is the continuation of #5451
With this change we will backfill the cache from the L+1 to L level.
**Checklist**
=> Backfill lower caches on the multi cache implementation

CHANGELOG.md, pkg/ring/kv/dynamodb/dynamodb.go, pkg/ring/kv/dynamodb/dynamodb_test.go, pkg/ring/kv/dynamodb/metrics.go
=> Add Label values Batch, Delete, Put for ddb metrics.

CHANGELOG.md, docs/blocks-storage/store-gateway.md, docs/blocks-storage/store-gateway.template, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_replicated_set.go, pkg/querier/blocks_store_replicated_set_test.go, pkg/ring/ring.go, pkg/ring/ring_test.go, pkg/ring/util_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go
Add a new method `ShuffleShardWithZoneStability ` in `ReadRing` interface. It does the same thing as `ShuffleShard` but makes a slight change:
1. It doesn't round up shard size to be multiple of `numZones` when zone awareness is enabled.
If shardSize is divisible by `numZones`, the behavior should be the same.
If shardSize is not divisible by `numZones`, for example, shard size 8 and num zones is 3. Then 2 zones are assigned to have 3 instances and 1 zone has 2 instances. Because we iterate over zones using the same order so we can ensure the consistency.
Fixes #5467 
**Checklist**
=> StoreGateway: fix store gateway shuffle sharding consistency issue when shard size change by 1

CHANGELOG.md, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/results_cache.go
Decoding and merging response in query frontend can take a long time, and if the context has been cancelled in the process it should stop as well.
This PR adds context error check before heavy operations within decode and merge responses.
n/a
**Checklist**
=> Query Frontend: Handle context error before decoding and merging responses

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor_ring.go
Allow the compactor ring unregisteronshutdown to be configurable. So during compactor statefulset rollout restart, the ring topology can stay the same, without causing resharding and re download of blocks.
**Checklist**
=> allow compactor unregisteronshutdown to be configurable

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/frontend/v2/frontend.go, pkg/frontend/v2/frontend_scheduler_worker.go
The current implementation cannot ensure that one tenant's requests are evenly distributed among all schedulers. As a result, some scheduler queues may be full, while others still have some room left.
This PR attempts to retry 429 requests randomly if there are multiple query-schedulers. We may need a more sophisticated approach to effectively address this issue.
**Checklist**
=> Re-enqueue 429 requests if there are multiple query-schedulers

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ring/kv/dynamodb/client.go, pkg/ring/kv/dynamodb/client_test.go, pkg/ring/kv/dynamodb/metrics.go
Right now in DDB KV, if the instance change its state very fast (within 1 sec), then the change of state will be rejected, because the timestamp of the instance didn't change. And the timestamp of the instance has 1 sec resolution. (https://github.com/cortexproject/cortex/blob/master/pkg/ring/ring.proto#L22)
So if no change detected (because the change is rejected), we retry the CAS (i.e. the f callback function), so the timestamp of the instance is updated. So next retry will succeed. This is similar idea in memberlist (https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/memberlist/memberlist_client.go#L838)
**Checklist**
=> if no change detected, retry

pkg/ring/kv/dynamodb/dynamodb.go
Need to set return consumed capacity in DDB request. Otherwise, zero will be returned for the consumed capacity.
**Checklist**
=> need to set return consumed capacity in input

CHANGELOG.md, pkg/storage/tsdb/bucketindex/index.go, pkg/storage/tsdb/bucketindex/index_test.go
We added Index Stats info to the `meta.json` file and use that to estimate series and chunk size. However, when store gateway uses bucket index, it won't actually download `meta.json` file from object store. It will generate `meta.json` file from the information provided by bucket index.
This pr adds additional fields `series_max_size ` and `chunk_max_size` to bucket index per block to help address this issue. The change is also backward compatible from what I tested.
**Checklist**
=> Add index stats info to bucket index

go.mod, go.sum, pkg/storage/bucket/client_mock.go, pkg/storage/bucket/prefixed_bucket_client.go, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go, pkg/storage/bucket/sse_bucket_client.go, pkg/storage/bucket/sse_bucket_client_test.go, pkg/storage/tsdb/bucketindex/markers_bucket_client.go, pkg/storage/tsdb/bucketindex/storage.go, pkg/storage/tsdb/bucketindex/updater.go, pkg/storage/tsdb/testutil/objstore.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/README.md, vendor/github.com/thanos-io/objstore/inmem.go, vendor/github.com/thanos-io/objstore/objstore.go, vendor/github.com/thanos-io/objstore/prefixed_bucket.go, vendor/github.com/thanos-io/objstore/providers/azure/azure.go, vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go, vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go, vendor/github.com/thanos-io/objstore/providers/s3/s3.go, vendor/github.com/thanos-io/objstore/providers/swift/swift.go, vendor/github.com/thanos-io/objstore/testing.go, vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go, vendor/modules.txt
* Update to the latest thanos objectstore
* Fix 5xx when key gets revoke on store gateway
**Checklist**
=> Update Thanos objsstore

pkg/storage/tsdb/bucketindex/loader.go, pkg/storage/tsdb/bucketindex/loader_test.go
Fixing bucket index status when index is not cached and we failed to load the index due access denied - In this case we should not fallback to `Unknown` but instead try to load the status from the objstore.
This fix the case when querier regain access to the CMK key after the permission was revoked for longer than `-blocks-storage.bucket-store.bucket-index.max-stale-period`. (in those cases we could read the bucket index again but the index was stale causing 5xx)
**Checklist**
=> Fix sync bucket index status

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Changing the compact folder to include the userId.
This is just to enhance the isolation between tenants.
**Checklist**
=> Adding the userId on the compact dir path

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/cortex/modules.go
This is just a small refactor:
Setting `t.Overrides` reference just once on the compactor and doing so, the same reference can be used on both interfaces: `ConfigProvider` and `Limits`.
Keeping the reference as `*validation.Overrides` is already the case on other components like ingesters:
https://github.com/cortexproject/cortex/blob/c56d882c624bf6c4ad432add8bac56fabce75862/pkg/ingester/ingester.go#L178-L187
**Checklist**
=> Refactor to avoid keep the "limits override" 2 times on compactor

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go
=> Add new metric for store gateway chunk refetches

CHANGELOG.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/alertmanager/alertmanager_ring.go, pkg/alertmanager/multitenant_test.go, pkg/ring/basic_lifecycler.go, pkg/ruler/ruler_ring.go, pkg/ruler/ruler_test.go, pkg/storegateway/gateway_ring.go
Add a configurable final sleep to the ruler/alertmanager/store-gateway lifecycler. This is to overcome the information delay in the ring if DDB KV is used as the backend.
e.g Ruler-1 is stopping and set it self to LEAVING. The information takes about 30s to reach other ruler, within in this 30s, if other ruler takes a GetRules call, it will iterate all the rulers that it thinks are healthy. It will wrongfully think the LEAVING ruler is healthy. But in reality, the LEAVING ruler already shutdown itself (because we don't have any delay). Then the GetRules will fail (because we don't have HA, and we can not tolerate a single ruler failure)
The solution is to add a delay when the ruler set itself to LEAVING, during this LEAVING time, if other ruler send the request. …
=> add configurable final-sleep time for basic lifecycler

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
This adds additional validation logic to ensure there are no duration values of zero in the compactor's BlockRanges config. If there are, the next validation rule would panic when trying to divide by zero. 
(I considered adding the check to the existing code, but a period of 0 here is invalid anyway, for a different reason)
**Checklist**
=> Fix possible division by zero during compactor config validation

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go
Now build info API is enabled by default. However, this will break Grafana with Cortex as data source.
To fix this, I make build info API disabled by default and added a flag to enable this if needed. 
This should help with problems like https://github.com/cortexproject/cortex/issues/5445
**Checklist**
=> Add feature flag to enable build info API

pkg/storage/tsdb/bucketindex/storage.go, pkg/storage/tsdb/bucketindex/storage_test.go
Return a Reader which implement Seek interface to be able to retry the upload of index in s3
https://github.com/cortexproject/cortex/blob/baa9d27889a1790359a80943685d4c7695e66e9e/pkg/storage/bucket/s3/bucket_client.go#L176
**Checklist**
=> Retry WriteIndex on bucketUpload

CHANGELOG.md, pkg/alertmanager/alertspb/compat.go, pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/alertmanager/alertstore/store_test.go, pkg/alertmanager/api.go, pkg/alertmanager/state_replication.go
This is a continuation of https://github.com/cortexproject/cortex/pull/5420
Handling access denied errors when cortex lose the access to the CMK (causing access denied on the objstorage).
In those cases AM will crash and fail to start as shown below:
```
ts=2023-08-31T19:21:28.327076006Z caller=cortex.go:444 level=error msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: failed to load alertmanager configurations for owned users: failed to fetch alertmanager config for user REDACTED: User: REDACTED is not authorized to perform: kms:Decrypt on the resource associated with this ciphertext because the resource does not exist in this Region, no resource-based policies allow access, or a resource-based policy explicitly …
```
=> [AlertManager] Handling CMK AccessDenied errors

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
- Making GCInterval Configurable
- Added the flag `-alertmanager.alerts-gc-interval` to configure alert manager Garbage collection Interval.
**Checklist**
=> Making GCInterval Configurable

pkg/storage/tsdb/bucketindex/loader.go, pkg/storage/tsdb/bucketindex/loader_test.go
* Update the index sync status when refreshing the cached indexes on the bucket index loader.
**Checklist**
=> update bucket sync status when refreshing the cache

CHANGELOG.md, pkg/storegateway/chunk_bytes_pool.go, pkg/storegateway/chunk_bytes_pool_test.go
Create new `cortex_bucket_store_chunk_pool_bytes_total` to add metrics around the byte slices returned to the pool.
This metric has a overlap with the existing ones - which should be deprecated if this PR is accepted.
**Checklist**
=> Creating new metric around chunks bytespool

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/ruler_test.go, pkg/ruler/compat.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/util/validation/limits.go, tools/doc-generator/parser.go
=> disable rule groups

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/header.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/github.com/thanos-io/thanos/pkg/store/proxy_heap.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go, vendor/modules.txt
Update thanos version to https://github.com/thanos-io/thanos/pull/6465 to bring in postings fetch optimization.
**Checklist**
=> Update thanos version to bring posting fetch optimization

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go, tools/doc-generator/main.go, tools/doc-generator/parser.go
When we added a slice of struct to limits config, we noticed the doc generator produces something like below
[disabled_rule_groups: <list of rule groups to disable> | default = ]
It would be nice to document the structure of DisabledRuleGroup type in the documentation. This PR modifies the parse function and if the config is a slice of struct, then it appends a [root block at the end](https://github.com/cortexproject/cortex/pull/5557/files#diff-cb926e77cd909b1b1b3c064945736ad4515cd2bb5a6a81f46bc59542bdb6409aR4936)
However if we want to insert a root block right after the current block, then it would require some additional changes
**Checklist**
=> Small enhancement to doc generator to account for slices

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway.go
Store gateway can only handle set number of requests at a given time, and rest of the requests are just queued up, waiting in the queryGate (channel). Since queriers select store gateways randomly without any information about their load, lots of requests could flood to one store gateway instance and slows down overall query latency (or could even lead to timeouts).
This PR add a new configuration `-blocks-storage.bucket-store.max-inflight-request` that allows requests to be rejected fast, which then queriers could try other store gateway replicas without waiting.
n/a
**Checklist**
=> Add max-inflight-requests limit to store gateway

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
We don't want to retry all 5xxs as in Thanos most of the errors will become `Unknown` gRPC status code, which becomes 5xx in Cortex. But not all of them are retriable.
This pr adds retry client conn closing error. 
Previously only `codes.Unavailable` got retried. This will cause issues for instant query as we only retry range queries. And the querier retry feature is not fully utilized.
**Checklist**
=> Retry more errors in block storage querier

CHANGELOG.md, pkg/querier/tripperware/roundtrip.go
Track number of get series request requests in QFE. Basically we adds a new label value for `op` of `cortex_query_frontend_queries_total` metric 
**Checklist**
=> Track number of get series request requests in QFE

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/ingester/ingester_test.go, pkg/purger/tenant_deletion_api.go, pkg/storage/tsdb/tenant_deletion_mark.go, pkg/storage/tsdb/tenant_deletion_mark_test.go
This marker is used by cortex to clean up the tenant files after deletion and so should still be accessible by cortex after the deletion.
This file also only store the time of the deletion (non sensitive), and so, i don't see any reason why we need this to be encrypted tenant key.
```
type TenantDeletionMark struct {
// Unix timestamp when deletion marker was created.
DeletionTime int64 `json:"deletion_time"`
// Unix timestamp when cleanup was finished.
FinishedTime int64 `json:"finished_time,omitempty"`
}
```
**Checklist**
=> Do no use tenant key on S3 KMS SSE when uploading deletion marker

CHANGELOG.md, pkg/querier/worker/scheduler_processor.go
We have two extra logs when the query times out:
```
ts=2023-08-29T15:57:55.2976267Z caller=scheduler_processor.go:187 level=info msg="finished request" status_code=499 response_size=95
ts=2023-08-29T15:57:55.297738564Z caller=scheduler_processor.go:211 level=error msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=10.1.121.156:9095
ts=2023-08-29T15:57:55.297766783Z caller=scheduler_processor.go:163 level=error msg="error notifying scheduler about finished query" err=EOF addr=10.1.126.155:9095
```
We can check the context before notifying the frontend and scheduler if context error is not nil.
n/a
**Checklist**
=> Check context before notifying frontend and scheduler

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/index_cache_test.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go, vendor/github.com/thanos-io/thanos/pkg/block/indexheader/parallel_bucket.go, vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/filter_cache.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/github.com/thanos-io/thanos/pkg/tenancy/tenancy.go, vendor/modules.txt
Add filtered index cache to Cortex. This allows different index caches to store different type of data.
For example, expanded postings is usually much smaller than postings so storing them and keep the hit ratio high is more efficient than caching both postings and expanded postings, especially in those memory constraint scenario like inmemory cache (size usually small)
**Checklist**
=> Support filtered index cache

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go
This PR emits the `alertmanager_dispatcher_aggregation_groups` and `alertmanager_dispatcher_alert_processing_duration_seconds` metrics from alertmanager dispatcher. 
Fixes #5588
**Checklist**
=> Add AM aggregation group metrics

pkg/ring/kv/dynamodb/client.go, pkg/tracing/tracing.go
I saw some bad logs in our Cortex deployment:
```
ts=2023-10-08T16:52:50.695689964Z caller=client.go:81 level=info class=DynamodbKvClient component=compactor dynamodbkvinitialized=(MISSING)
```
Log function call requires a key-value pair so add `msg` here as the message key.
**Checklist**
=> Fix log message missing key field

CHANGELOG.md, pkg/ruler/compat.go
This PR adds some additional contextual information and query statistics to Ruler logs. This will be in effect only when query statistics is enabled
**Checklist**
=> Add contextual information and query statistics to log

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go, vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go, vendor/github.com/thanos-io/thanos/pkg/store/proxy.go, vendor/modules.txt
Upgrade Thanos library to latest main version.
This includes several improvements and bug fixes:
1. https://github.com/thanos-io/thanos/pull/6806
2. https://github.com/thanos-io/thanos/pull/6816
3. https://github.com/thanos-io/thanos/pull/6817
4. https://github.com/thanos-io/thanos/pull/6807
5. https://github.com/thanos-io/thanos/pull/6801
**Checklist**
=> Upgrade thanos to latest main

CHANGELOG.md, pkg/ruler/ruler.go
This PR adds 2 metrics to track the following
- Latency of loading rules from storage
- Overall latency to load and sync rules
**Checklist**
=> Add metric to measure rule group load time

CHANGELOG.md, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go
This pr checks context in multi level cache and also adds two new histogram metric to track the latency to fetch data and backfill respectively.
The main reason to add the context check is for https://github.com/cortexproject/cortex/pull/5486. We have a backfill mechanism from higher level caches to lower level caches. For example, items exist in L2 cache (for example memcached) will backfill to L1 cache (inmemory cache).
However, when backfilling, `cache.StoreXXX` method doesn't take context as parameter. When backfilling thousands of keys, it might take quite a long time. In my test environment, I can see backfilling to inmemory cache took more than 2 minute to finish due to high lock contention.
The two histogram metrics are useful to measure the fetch and …
=> Multi level cache: check context add latency histogram

pkg/frontend/transport/handler.go
Put the query field at the end to avoid truncating other fields in the log.
Some logging system has max length limitation. `query` param can go very long especially when users are using `*` together with Grafana template variables so the query string might contain all their label values.
When query stats log got truncated, some useful information might be missed like time range, status code, user agent, etc
**Checklist**
=> Put query field at the end of query stats log

CHANGELOG.md, pkg/ingester/ingester.go
Make ingester shipper always upload compacted blocks.
For ingesters, compacted blocks should never happen unless OOO samples is enabled. It should be fine to always enabled it.
And since vertical compaction is enabled in compactor, uploading compacted blocks should be safe.
Supercedes https://github.com/cortexproject/cortex/pull/5416
**Checklist**
=> Ingester: Always upload compacted blocks

CHANGELOG.md, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/testutils.go
This PR is a fix for https://github.com/cortexproject/cortex/issues/5620
**Checklist**
=> Fix querier limiter bug under multiselect

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
Prometheus TSDB adds some new TSDB metrics and they are useful to have in Cortex ingester as well.
Fixes #5623 
**Checklist**
=> Add new TSDB metrics from Prometheus

.github/workflows/test-build-deploy.yml, Makefile, build-image/Dockerfile
Bump to latest go version before making the release.
go 1.21.3 pathces a CVE in go 1.21.0 https://github.com/golang/go/issues/63417.
**Checklist**
=> Update go version to 1.21.3

integration/query_frontend_test.go
I saw flaky test `TestQueryFrontendNoRetryChunkPool` a lot after we added this test. For example, https://github.com/cortexproject/cortex/actions/runs/6764732560/job/18383544803.
In the test, we expect querier failed to query SG due to chunk pool error. Querier will retry 3 times and return error to QFE. QFE will not retry the error and return 500 because it is chunk pool exhaustion error.
Querier has a consistency checker to decide whether we want to retry the block. When flaky happens, if the block is uploaded within the upload grace period, querier won't retry and it will return 200, causing test to fail.
The `upload grace period` is consistency check delay + 3 * bucket sync interval. consistency check delay is configured as 0s and bucket sync interval is 5s. So …
=> Fix flaky TestQueryFrontendNoRetryChunkPool test

pkg/configs/db/postgres/postgres.go, pkg/cortexpb/compat_test.go, pkg/querier/batch/batch.go, pkg/querier/worker/frontend_processor.go, pkg/ring/lifecycler.go, pkg/util/log/log.go, pkg/util/log/wrappers.go
=> chore: pkg import only once

CHANGELOG.md, go.mod, go.sum, integration/querier_test.go, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/inmemory_index_cache.go, pkg/storage/tsdb/inmemory_index_cache_test.go, pkg/storage/tsdb/multilevel_cache_test.go, vendor/github.com/VictoriaMetrics/fastcache/LICENSE, vendor/github.com/VictoriaMetrics/fastcache/README.md, vendor/github.com/VictoriaMetrics/fastcache/bigcache.go, vendor/github.com/VictoriaMetrics/fastcache/fastcache.go, vendor/github.com/VictoriaMetrics/fastcache/file.go, vendor/github.com/VictoriaMetrics/fastcache/malloc_heap.go, vendor/github.com/VictoriaMetrics/fastcache/malloc_mmap.go, vendor/modules.txt
This PR adds a new inmemory index cache implementation, based on the https://github.com/VictoriaMetrics/fastcache library.
The previous inmemory index cache will be replaced by this one. As the previous inmemory index cache has pretty bad performance under high concurrency environment https://github.com/thanos-io/thanos/issues/6762.
**Checklist**
=> Replace inmemory index cache to fastcache based implementation

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
=> Add cortex_ingester_tsdb_data_replay_duration_seconds metric

pkg/ruler/api.go, pkg/ruler/ruler.go
With this PR the `ListRuleGroupsForUserAndNamespace` function should not be called in the `CreateRuleGroup` endpoint if the `MaxRuleGroups` limit for the tenant is not set. The existing tests for the validation should still pass after this change.
Fixes #5646
**Checklist**
=> Skip listing rule groups in CreateRuleGroup api if max rule groups limit is not set

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
We found that `param_query` unabled to be logged in query frontend in latest Cortex version caused by https://github.com/cortexproject/cortex/pull/5622.
The bug is that, `queryFields` is of type `[]string`, `fields` is of type `[]interface{}`.
```
fields = append(fields, queryFields)
```
This append will add `queryFields []string` as a single element to `fields` slice, causing the params unable to be logged.
The correct way is to add key, value as two separate fields using `fields = append(fields, queryFields...)`.
```
func formatQueryString(queryString url.Values) (fields []interface{}) {
var queryFields []string
for k, v := range queryString {
// If `query` or `match[]` field exists, we always put it as the last field.
if k == "query" || k == "match[]" { …
```
=> Fix param_query omitted in query frontend query stats log

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, integration/query_frontend_test.go, pkg/cortex/modules.go, pkg/querier/querier.go, pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go
Expose `querier.max-subquery-steps` subquery max allowed steps limit as a flag. This default limit is 0, which disables this check so that we can keep the behavior the same as previous releases and Prometheus
Fixes #5651
**Checklist**
=> Add querier.max-subquery-steps to make subquery step size check optional

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Allow distributor to actually include native histograms data in write request when sending to ingesters.
This should make the new metric added in https://github.com/cortexproject/cortex/pull/5289 actually work.
**Checklist**
=> Fix distributor sends native histograms

pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go
https://github.com/cortexproject/cortex/pull/5661 introduces a bug when backfilling the items. It is used in a for loop and goroutine closure, so we have to assign the variables again.
Added test cases to reproduce the issue. It could happen when we backfill more than 1 items and previous unit tests couldn't catch that.
Skipping changelog.
**Checklist**
=> Fix async backfill loop issue

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor_test.go, pkg/purger/tenant_deletion_api_test.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/tenant_deletion_mark.go, pkg/storage/tsdb/tenant_deletion_mark_test.go, pkg/storage/tsdb/users_scanner.go, pkg/storage/tsdb/users_scanner_test.go, pkg/util/allowed_tenants.go
- If the `tenant_cleanup_delay` is large (say 24h), a deleted tenant can be continued to be synced by the store-gateways.
- This is because the  `s3://<bucket>/<tenantID>/markers/tenant-deletion-mark.json` will be kept for 24h after the tenant has been deleted.
- If there are a lots of users being created and deleted in the cluster (canary testing), there could be a lot of deleted users synced by the store-gateway.
- This change moves the `tenant-deletion-mark.json` to a global markers directory. 
- `s3://<bucket>/__markers__/<tenantID>/tenant-deletion-mark.json`
- The string `__markers__` is treated as special an no tenants are allowed to have that name.
- With this change, the tenants can immediately be cleaned up by the cleaner after deletion and no longer has to …
=> Move tenant-deletion-mark to a global dir

CHANGELOG.md, cmd/cortex/Dockerfile, cmd/query-tee/Dockerfile, cmd/test-exporter/Dockerfile, cmd/thanosconvert/Dockerfile, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile, packaging/fpm/Dockerfile
Upgrades Alpine to 3.18. Intended to fix several security vulnerabilities in alpine packages. In particular, Jfrog Xray is flagging `CVE-2022-48174`. I'm unsure if it's correct, as the image has the latest busybox in 3.17. Regardless, it's much easier to upgrade to keep scans clean instead of tracking various false positives. I have some 3.18 images and this vuln does not show up.
None
**Checklist**
=> Upgrade Alpine to 3.18

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Add additional metrics to record compactor start and stop duration in seconds. These metrics would be helpful to keep track of abnormally long start or stop time of compactor.
NA
**Checklist**
=> Add compactor start duration in seconds metric

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, pkg/storage/tsdb/index_cache.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/multilevel_cache_test.go
Refactored multilevel cache code to integrate it better with cache items filtering.
By filtering caches in multilevel cache itself, we can avoid putting unnecessary tasks into the async processor queue.
We observed that when backfilling  a large amount of items (10M+), even if the operation is async, putting all items into the backfill queue can already take 20s+.
This change also refactor the async queue operation to not enqueue items one by one, instead we enqueue the whole items that need backfilling, and we have a cap to avoid backfilling too much data
**Checklist**
=> Improve async processor handling enabled items, optimize code further

pkg/compactor/compactor_test.go
Fix compactor test to ignore "compactor stopped" log which might not have time to be emitted to logger soon enough.
NA
**Checklist**
=> Fix compactor test

pkg/compactor/blocks_cleaner.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/ingester/ingester_test.go, pkg/purger/tenant_deletion_api.go, pkg/purger/tenant_deletion_api_test.go, pkg/storage/bucket/client.go, pkg/storage/bucket/client_mock.go, pkg/storage/tsdb/bucketindex/markers_bucket_client.go, pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go, pkg/storage/tsdb/bucketindex/storage_test.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/tenant_deletion_mark.go, pkg/storage/tsdb/tenant_deletion_mark_test.go, pkg/storage/tsdb/testutil/objstore.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go
We should not count 404 in the `thanos_objstore_bucket_operation_failures_total` as this is an expected error in this case.
https://github.com/cortexproject/cortex/pull/5676 introduced a fallback that started to cause this metric to spike
**Checklist**
=> Do not count 404 errors when checking if tenant deletion markers exists

CHANGELOG.md, pkg/compactor/compactor_test.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/storage/tsdb/users_scanner.go, pkg/storage/tsdb/users_scanner_test.go, tools/thanosconvert/thanosconvert_test.go
This PR fixes an issue introduced in #5676. 
After the `tenant-deletion-mark.json` is moved to the global dir, the cleaner cannot discover tenants that were cleaned up before. This PR fixes the problem by also scanning the `__markers__` directory to discover the deleted tenants.
**Checklist**
=> Fix cleaner not discovering deleted users from global dir

docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_store_queryable.go, pkg/storage/tsdb/caching_bucket.go, pkg/storegateway/bucket_stores.go
Use Caching Bucket for compactor operations, except the cleaner which serves as the source of truth for tenant bucket index.
**Checklist**
=> use caching bucket for compactor, except cleaner

pkg/querier/tripperware/priority.go, pkg/querier/tripperware/priority_test.go, pkg/querier/tripperware/roundtrip.go
When a query fails to be parsed in query priority, we return parse error and the error will be converted to 5xx server error.
This pr changes the code to forward the request to querier instead and let it returns 4xx error.
**Checklist**
=> fix query priority throws 5xx when 4xx

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
Expose query priority enabled and default priority to cli flags. By exposing cli flags, it is easier to change enable/disable query priority feature without changing the Cortex config file.
**Checklist**
=> Expose query priority enabled and default priority to cli flags

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Prometheus drops labels which are empty
https://github.com/prometheus/prometheus/blob/69abd6d9f65a6358025461510237366f1d939c70/tsdb/head_append.go#L429
When creating the sharding token in distributor for income timeserie we use all labels to create the token. We end up in a situation where after dropping labels with empty values, we have the same timeserie in multiple ingesters. This change ignore labels with empty values to be used by sharding.
**Checklist**
=> Filter empty labels from sharding key

CHANGELOG.md, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/results_cache_test.go
Checks whether offset is negative or not, and if negative, it does not cache the query result.
Fixes #5678 
**Checklist**
=> Query Frontend: queries with negative offset should check whether it is cacheable or not

pkg/ring/basic_lifecycler.go, pkg/ring/ring.go, pkg/ruler/ruler.go, pkg/ruler/ruler_ring.go, pkg/ruler/ruler_test.go
1. Since ruler is not HA yet, when a ruler stopping, it briefly set it self to LEAVING first, and then removes itself from the KVStore.
There is some period of time when other ruler thinks this ruler is in LEAVING state, causing list rule 5xx with error `too many unhealthy instances in the ring`
If we consider LEAVING rule as healthy when list rules, we won't encounter this problem. And LEAVING ruler will still serve list rule request and after about 1min, the ruler will be removed from KV and ring, then request won't go to this ruler anymore.
2. Also added some log in changeState in basic lifecycler, so we have better visibility of the state change of instance.
**Checklist**
=> Add new ListRuleRingOp to ruler and add more logs to the changeState in basic lifecycler

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/storage/bucket/client_mock.go, pkg/storage/bucket/sse_bucket_client_test.go
…
Compactor should skip retry without failure if there is permission denied error. Because permission denied error caused by CMK cannot be auto resolved until operator set up the permission correctly. Also, check logic [here](https://github.com/cortexproject/cortex/blob/8282a2f538483919f0e7010c6958e4f7beb3db8e/pkg/compactor/compactor.go#L709) should prevent next compaction to start if CMK error is not fixed.
NA
**Checklist**
=> Compactor should skip retry without failure if there is permission denied error

CHANGELOG.md, docs/configuration/config-file-reference.md, go.mod, pkg/tracing/tracing.go
For tracing with opentelemetry, Cortex uses otlpgrpc protocol to send traces to OTLP backends.
When you have multiple tracing backends, it is always recommended to have load balancing. Since gRPC is a long lived connection, it is more recommended to do client side loadbalancing. For more details, can refer to https://github.com/grpc/grpc/blob/master/doc/load-balancing.md. In this pr, I added an option to enable `round_robin` policy, by default it is `pick_first`.
This pr also enables `kuberesolver` support which allows to resolve endpoint with prefix `kubernetes://`, for example `kubernetes://opentelemetry-collector.tracing:4317` to be resolved as a k8s service and return the actual endpoint IPs (pod IP). This is helpful because `kuberesolver` watches the backend …
=> otlpgrpc: turn on round_robin LB policy and kuberesolver for resolving k8s service endpoints

CHANGELOG.md, pkg/storage/tsdb/redis_client_config.go
Fixes https://github.com/cortexproject/cortex/issues/5733
`cache-size` flag doesn't get passed to redis client config.
**Checklist**
=> Fix passing of redis client cache size

pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/ruler/rulestore/bucketclient/bucket_client.go
In S3 bucket with retries client, we require input object to be a `Seeker` so that the request is retriable.
For ruler and alertmanager, some upload operations still use `bytes.NewBuffer`, which doesn't implement `Seeker` so that upload to S3 operation may fail without any retries.
**Checklist**
=> Use bytes reader to retry file upload to S3

CHANGELOG.md, pkg/ingester/ingester.go
This change basically reverts https://github.com/cortexproject/cortex/pull/5625 and enables a new flag introduced in Prometheus https://github.com/prometheus/prometheus/pull/13393 to always disable overlapping compaction in ingester.
This new flag makes sure that all overlapping compaction happens at compactor side and ingester doesn't need to waste resources to do vertical compaction.
**Checklist**
=> Disable upload compacted blocks and overlapping compaction in ingester

CHANGELOG.md, pkg/distributor/distributor.go
Currently, there are no metrics that include rate-limited samples. I am considering counting the number of rate-limited samples in distributor_samples_in_total. Alternatively, we could add a separate metric.
**Checklist**
=> Count the number of rate-limited samples in distributor_samples_in_total

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/querier.go
Store Gateway Query Stats is always enabled before, which might produce too many unnecessary logs for some users. This pr put this feature under a flag so that users can disable it at will.
Fixes #5721
**Checklist**
=> Add flag to disable store gateway query stats

CHANGELOG.md, integration/ingester_sharding_test.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
There is a discrepancy between the current behavior of the system and the documented functionality regarding the setting of the ingestion_tenant_shard_size parameter.
Current Behavior
When attempting to set the -distributor.ingestion-tenant-shard-size flag to 0, the system throws an error.
Expected Behavior (As Per Documentation)
The documentation states the following:
```
[ingestion_tenant_shard_size: <int> | default = 0]
```
According to this, setting the value to 0 should **be supported** and is intended to disable shuffle sharding for the tenant.
**Rationale for Setting the Value to 0**
The intention behind setting the ingestion_tenant_shard_size to 0 by default is to enable shuffle-sharding, while also allowing a tenant to utilize the entire ring as the shard size. This setup is …
=> Distributor default sharding should support default 0 value.

.github/workflows/test-build-deploy.yml
CodeQL is breaking in master branch because of the following errors: `Error: Resource not accessible by integration`. This PR adds the appropriate permissions for the job to be able to submit back to the security tab under the master branch. Our permission set is `read-only` by default, this overrides that specific behavior for this particular "Security" related job.
Looking at the job's setup - the security events is set to read, I believe this should be set to "Write". This is also why I believe it's not reporting the status to the Security Tab.
Fixes #5761 
**Related Issue:**
https://github.com/github/codeql/issues/8843
**Checklist**
=> Overwriting permissions on security related jobs

.github/workflows/test-build-deploy.yml, CHANGELOG.md, build-image/Dockerfile
**What this PR does**: Updates build-image to use go 1.21.6 to eliminate vulnerabilities in go: `CVE-2023-45284`, `CVE-2023-39326`, `CVE-2023-45283`, `CVE-2023-45285`.
**Checklist**
=> Update Dockerfile to golang 1.21.6

CHANGELOG.md, integration/ruler_test.go, pkg/cortex/modules.go, pkg/ruler/compat.go, pkg/ruler/manager.go, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/ruler/manager_test.go, pkg/ruler/ruler_test.go
In https://github.com/cortexproject/cortex/pull/5312 the rule evaluation metrics related to queries and append became per user metrics. But unlike other per user metrics, the multitenant manager is [NOT currently deleting](https://github.com/cortexproject/cortex/blob/master/pkg/ruler/manager.go#L129-L132) these metrics when the ruler manager is deleted leaving multiple dangling metrics. In this PR, we delete these dangling metrics when the rule manager is deleted.
**Checklist**
=> Remove user specific evaluation metrics when rule manager is removed

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/zone_aware_test.go, pkg/distributor/distributor.go, pkg/distributor/query.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/replication_set_tracker.go, pkg/ring/replication_set_tracker_test.go
Added a new flag `-distributor.zone-results-quorum-metadata` to only include quorum number of zones as query results of metadata APIs like label names, values and series.
This helps improve performance and latency. Image we have 3 zones. Now when zone awareness is enabled, we wait for all ingester results from at least 2 zones to be received before returning the results. However, for results from the 3rd zone, we are still trying to merge them. This can be inefficient as the results from 3rd zone are basically duplicates.
Thus, this pr tries to only use results from 2 zones. By having less data to merge, improve the latency as well as memory usage.
**Checklist**
=> Option to include quorum zone results for DistributorQueryable metadata API

pkg/ring/replication_set_test.go
Example run: https://github.com/cortexproject/cortex/actions/runs/7992293857/job/21826435951
```
--- FAIL: TestReplicationSet_Do (0.12s)
--- FAIL: TestReplicationSet_Do/max_unavailable_zones_=_1,_zoneResultsQuorum_=_false,_should_contain_5_results_(2_from_zone1,_2_from_zone2_and_1_from_zone3) (0.00s)
replication_set_test.go:261: 
Error Trace:	/__w/cortex/cortex/pkg/ring/replication_set_test.go:261
Error:      	Not equal: 
expected: []interface {}{1, 1, 1, 1, 1}
actual  : []interface {}{1, 1, 1, 1}
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,2 @@
-([]interface {}) (len=5) {
- (int) 1,
+([]interface {}) (len=4) {
(int) 1,
Test:       	TestReplicationSet_Do/max_unavailable_zones_=_1,_zoneResultsQuorum_=_false,_should_contain_5_results_(2_from_zone1,_2_from_zone2_and_1_from …
```
=> Remove flaky test case of replicationset.Do

go.mod, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/strings.go, pkg/util/strings_test.go, pkg/util/test_util.go
This PR changes the strategy we use to merge sorted slices containing the labels values/keys on the GetLabels and GetLabelValues APIs.
Before we were getting the response from each ingesters, adding in a map and sorting at the end to dedup/sort the response.
Now we are using Loser Tree for merge (same as used on https://github.com/prometheus/prometheus/pull/12878) and also using more than one core to merge those slices.
Benchmark from the GetLabelsValues APIs with different duplication factors (Ex: 0.67 duplication ratio means that the resulting slice will have 33% of the sum of the strings on the input slices):
```
goos: linux
goarch: amd64
pkg: github.com/cortexproject/cortex/pkg/distributor
cpu: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
│   /tmp/old   │ …
```
=> Merging slices from the labels APIs using more than 1 cpu and k-way

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/compactor/compactor.go, pkg/querier/blocks_finder_bucket_scan.go, pkg/storage/tsdb/bucketindex/block_ids_fetcher.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/circuit_breaker.go, pkg/storage/tsdb/memcache_client_config.go, pkg/storage/tsdb/redis_client_config.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go, vendor/github.com/thanos-io/thanos/pkg/cache/caching_bucket_config.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/cacheutil.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go, vendor/github.com/thanos-io/thanos/pkg/pool/pool.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/cachekey/cachekey.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/modules.txt
Updated Thanos version to latest main https://github.com/thanos-io/thanos/commit/e7cd6c1c60fb3287b4ae7cd27092d5695f55bdbd.
Added circuit breaker support to Cortex cache clients using the feature added in Thanos https://github.com/thanos-io/thanos/pull/7010.
This is helpful to prevent overloading external caches using `SET` requests such as memcached.
**Checklist**
=> support set async circuit breaker for memcached and redis client

docs/getting-started/_index.md
=> Update docker image consul (deprecated) by hashicorp/consul

CHANGELOG.md, pkg/util/grpcutil/util.go
This fixes a dormant bug because of which the streaming GRPC clients are not honoring the overrides for `MaxRecvMsgSize` and `MaxSendMsgSize`.
This issue only surfaces if the stream response size is > 4MB.
**Checklist**
=> Fix GRPC client not honouring call options

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/tripperware/instantquery/instant_query_middlewares.go, pkg/querier/tripperware/instantquery/limits.go, pkg/querier/tripperware/instantquery/limits_test.go, pkg/querier/tripperware/queryrange/limits_test.go, pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
Right now, there is a check for max query length in the query frontend query range middleware. It only checks the `start` and `end` parameter of range query API and see if it exceeds a maximum time range.
However, this check doesn't analyze the query string itself. For example, `up[60d]`. The time window `60d` can be very large and exceeds the limit. However, it is not checked at query frontend.
To fix this issue, there is another checkfor max query length at Querier right now, which happens per `Select` only and it considers the time range of the query itself. For example, `up[60d]` can be rejected at Querier if the limit is configured as 30d.
However, this solution isn't perfect because a query can have multiple selects. `rate(up[25d]) + rate(up[25d] offset 25d) + …
=> Consider query select time in max query length check

CHANGELOG.md, cmd/cortex/main.go
Deprecate `mem-ballast-size-bytes` flag.
Fixes #5283
**Checklist**
=> Mark mem ballast flag as deprecated

go.mod, go.sum, integration/e2e/util.go, integration/e2ecortex/storage.go, integration/query_fuzz_test.go, vendor/github.com/cortexproject/promqlsmith/opts.go, vendor/github.com/cortexproject/promqlsmith/promqlsmith.go, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/modules.txt
Added an integration test which utilizes `promqlsmith` as a random query generator to generate random matchers.
The test case will run 2 sets of queriers and store gateways. One with lazy expanded posting enabled and one isn't.
Test case creates a block with predefined series and upload the block to minio used in the integration test.
Then run GetSeries API 1000 times with randomly generated matchers and compare whether the two results are the same or not.
I plan to create another test case in another pr to compare Prometheus and Store Gateway with lazy expanded postings enabled.
**Checklist**
=> Add store gateway lazy expanded posting fuzz test to verify correctness

CHANGELOG.md, pkg/querier/distributor_queryable.go, pkg/querier/querier.go, pkg/querier/series/series_set.go
Add some context cancellation checks on GetSeries
**Checklist**
=> add context cancellation checks on GetSeries

CHANGELOG.md, pkg/ring/kv/dynamodb/client.go, pkg/ring/kv/dynamodb/client_test.go
We are now also updating the staleData on CAS operation.
The CAS operation is mostly used via lifecycle and did not had any data before. This change start to also have stale data on lifecycle. This is mainly important because the ring of a lifecycle is used by distributor to check local limits.
When using DDB and having unhealthy distributors on the ring, the healthInstancesCount on the ring was calculated wrong because the staleData was not set and by that the timestamp from the last update was empty making the heartbeat of pods be always healthy. This introduce stale data to lifecycle which is used to check for local limits.
**Checklist**
=> Update cache on CAS for DDB

pkg/storage/tsdb/inmemory_index_cache.go
as 'reflect.StringHeader' is deprecated, it is replaced with an unsafe package.
Fixes #5774 
**Checklist**
=> change the reflect package to an unsafe package

CHANGELOG.md, pkg/ruler/manager.go, pkg/ruler/manager_test.go
Currently the manager's SyncRuleGroups and GetRules methods share the same lock. This means that if SyncRuleGroups becomes slow then GetRules will have to wait a long time to acquire the lock.
SyncRuleGroups can become slow when rule groups are updated with slow running rules because the rule group will wait for currently evaluating rule to finish before it stops
This PR fixes this problem by:
1. Using the `userManagerMtx` for it's intended purpose which is to protect the `userManagers` map
2. Convert `useManagerMtx` to RWMutex so that exclusive lock is acquired only when a new manager is created or clean up occurs at the end of `SyncRuleGroups`. By doing this, the duration of exclusive lock is reduced and the scope is reduced
3. Introduce `syncRuleMtx` to ensure …
=> Improve GetRules performance

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/querier/blocks_finder_bucket_scan.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/querier/blocks_store_queryable.go, pkg/storage/tsdb/bucketindex/block_ids_fetcher.go, pkg/storage/tsdb/bucketindex/block_ids_fetcher_test.go, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go
Allowing configuring different strategies to fetch block IDs from object store, similar to https://github.com/thanos-io/thanos/pull/7134.
Thanos changed its block listing strategy in https://github.com/thanos-io/thanos/pull/6474 which iterates the whole bucket. This can be extremely slow in some object store implementation. For example, when bucket versioning is enabled in S3, it is very slow to iterate the whole bucket. This impacts Thanos as well as Cortex 1.16.0 release.
In https://github.com/thanos-io/thanos/pull/7134, Thanos reverts its block listing strategy back to the original one to avoid iterating the whole bucket. Thus, exposing the same configuration in Cortex and make the default configuration `Concurrent`, which is the old working behavior. …
=> Configurable block listing strategy

CHANGELOG.md, pkg/distributor/distributor.go, pkg/util/strings.go, pkg/util/strings_test.go
Add context error check while merging slices for GetLabel operations
**Checklist**
=> add context cancellation checks on merging GetLabel slices

CHANGELOG.md, pkg/alertmanager/lifecycle.go, pkg/alertmanager/multitenant_test.go, pkg/cortex/cortex.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ring/basic_lifecycler.go, pkg/ring/lifecycler.go, pkg/ring/ring_test.go, pkg/ring/token_generator.go, pkg/ring/token_generator_test.go, pkg/ring/util.go, pkg/ring/util_test.go, pkg/ruler/lifecycle.go, pkg/ruler/lifecycle_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_test.go
This PR implements the Spread Minimize Token Generator algorithm based on https://github.com/grafana/dskit/pull/321 by GL (thank you), but the implementation is slightly different.
The algorithm implemented in the DSKit package creates tokens in "order", and so, all the tokens need to be created using this algorithm and require a reshard for existing clusters.
The proposal in this PR is slightly different. Here, we create tokens based on the state of the ring right at a given moment, and so, we can achieve similar benefits as soon as new ingesters join the ring (no need to reshard all existing ingesters).
The algorithm is basically as follows:
When registering a new ingester, we first:
* Determine the expected ownership of the new ingester based on the existing …
=> Implementing Spread Minimizing Token Generator

integration/query_fuzz_test.go
RandRange implementation:
```
func RandRange(rnd *rand.Rand, min, max int64) int64 {
return rnd.Int63n(max-min) + min
}
```
`rnd.Int63n` requires the input to be > 0, otherwise it panics.
minT can have value [startMs, endMs-1]. Then minT + 1 can be endMs at maximum.  When calculating `maxT = e2e.RandRange(rnd, minT + 1, endMs)` it is possible to cause possible. I ran into this issue locally.
```
minT := e2e.RandRange(rnd, startMs, endMs)
```
**Checklist**
=> Fix rand int63n panic in query fuzz test

CHANGELOG.md, docs/api/_index.md, docs/configuration/v1-guarantees.md, go.mod, integration/e2ecortex/client.go, integration/otlp_test.go, pkg/api/api.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go
**What this PR does**: Implements OTLP ingestion. Based on the good work done by @Aneurysm9 🙇 
~This needs integration tests and unit tests~
Fixes #4981
**Checklist**
=> OTLP Ingestion

pkg/storage/tsdb/bucketindex/index.go, pkg/storage/tsdb/config.go, pkg/util/limiter/query_limiter.go, pkg/util/metrics_helper.go, tools/querytee/response_comparator.go
Fix function names
**Checklist**
=> Fix function names

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go
This PR adds a new config in S3 bucket client `send_content_md5` to specify the checksum algorithm to use when put objects. If true, use MD5. Otherwise use CRC32C.
Previously, bucket client uses CRC32C, which got an issue reported in #5829 when using non Amazon S3 object storage like Cloudflare R2. With the change in this pr, it should work out of the box. Thanos sets this value to true by default as well
If users want to stick with using CRC32C, they can turn off this flag.
Fixes #5829 
**Checklist**
=> Add S3 send_content_md5 config and default to use MD5

pkg/ruler/ruler_ring.go
Fixes failure in test code that references a method that was already removed by a previous PR
**Checklist**
=> Fix usage of math.Min since the util method was removed

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, build-image/Dockerfile, go.mod
**What this PR does**: Upgrades go to 1.21.9. Includes fixes for CVE-2023-45288, CVE-2024-24783, CVE-2023-45290, CVE-2023-45289
**Checklist**
=> Upgrade to go 1.21.9

ADOPTERS.md
What this PR does: Adds Apple as an Adopter
We use and contribute to the Cortex project. We operate Cortex in multiple regions and availability zones to provide a resilient datastore service for AIML observability metric workloads with ingestion rates of a billion+ per minute.
=> Add Apple as an Adopter

docs/configuration/config-file-reference.md, pkg/ring/lifecycler.go
Expose documentation for change merged on https://github.com/cortexproject/cortex/pull/5855
This feature is still experimental but we can document it.
**Checklist**
=> Add doc for the Spread minimize token generator

CHANGELOG.md, pkg/ring/http.go, pkg/ring/ring.go, pkg/ring/ring_test.go
This PR include 3 changes:
* Fix how the ring owership is calculated on the ring status page
* Before we were calculating the distance from the token to the next one, but instead, we should calculate the distance from the previous one.
* If AZ aware is enabled, only take tokens from the ingester AZ to calculate the ownership
* Add a column to show the difference in percentual from the expected ownership to the actual ownership.  
**Checklist**
=> Fixing how ring ownership is calculated on the ring status page

pkg/distributor/distributor_test.go, pkg/util/strings_test.go, pkg/util/test_util.go
We initialize `RandomStrings` in `pkg/util/test_util.go` which allocates 50MB data in heap in Cortex binary. This variable is used only in tests. The increased also showed up in the heap dump below.
In this PR I removed the global variable for `RandomStrings` in `pkg/util` and move it to specific test files instead. This should reduce the memory usage in heap.
**Checklist**
=> fix random string used in test allocating 50MB in Cortex binary

pkg/cortexpb/extensions.go, pkg/cortexpb/extensions_test.go
Optimize how we calculate the write signature:
Before we were falling back to use a less optimal way to calculate when the signature input was > "maxBufferSize" and now we are reusing that buffer to calculate the hash in "batchs"
Benchmark Results:
```
goos: linux
goarch: amd64
pkg: github.com/cortexproject/cortex/pkg/cortexpb
cpu: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
│   /tmp/old   │              /tmp/new               │
│    sec/op    │    sec/op     vs base               │
SignRequest/WriteRequestSize:_10-32	 1.032µ ± ∞ ¹   1.038µ ± ∞ ¹	    ~ (p=0.111 n=5)
SignRequest/WriteRequestSize:_100-32     5.182µ ± ∞ ¹   4.224µ ± ∞ ¹  -18.49% (p=0.008 n=5)
SignRequest/WriteRequestSize:_1000-32    48.09µ ± ∞ ¹   35.85µ ± ∞ ¹  -25.44% (p=0.008 n=5) …
```
=> Optimize Write Signature calculation

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, build-image/Dockerfile
This fixes the issue where node 14 script was being deprecated and a 60 second window starts. Upgrading to Node 18 version.
https://github.com/cortexproject/cortex/issues/5877
**Checklist**
=> Node Version Upgrade - 14x to 18x

CHANGELOG.md, pkg/configs/db/db.go, pkg/configs/db/db_test.go
Removed endline and extra space from password. Added test for the same.
Fixes #5444
**Checklist**
=> Fixed db password file endline issue

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ring/lifecycler.go, pkg/util/time.go, pkg/util/time_test.go
https://github.com/cortexproject/cortex/pull/5919 We introduced a jitter on the head compaction. This PR is proposing to change that jitter to take in consideration the AZ of the ingester.
Lets say we configure to have a head compaction interval set at 15 minutes across 3 Availability Zones (AZs). Prior to this change, the ingesters would determine a random jitter and perform the head compaction at any minute within each 15-minute interval. This change ensure that within every 15-minute interval, Ingesters in AZ1 execute head compaction from minute 0 to 5, those in AZ2 from minute 5 to 10, and those in AZ3 from minute 10 to 15.
I added a log on every tick to show the time of the tick and the AZ of the ingester on a 15 minutes period:
| aws.az | tick_time | count(*) …
=> Making ingester head compaction jitter Zone aware.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Cleaning up stale ingester metrics on distributor (and querier) when the ingester get restarted and change its address.
Before this change, those metrics were never cleaned and it can end up creating a huge amount of useless dimentions.
**Checklist**
=> Cleaning up stale ingester metrics

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ring/ring.go, pkg/ring/ring_test.go
Creates a flag to allow disabling the "detailed ring metrics"
The metrics indicate the ownership or token count per ingester. However, since they are generated by the distributor, they can rapidly generate a large number of metrics. (every distributor will emit the same value)
Those metrics are not super useful as they only change when we have a configuration change (number of tokens) or a scale up /down of ingesters (ownership) -> Both of these informations are already on the ring page on the distributor.
**Checklist**
=> Allowing to disabled detailed ring metrics

pkg/ingester/client/client.go, pkg/ingester/client/client_test.go
In last PR https://github.com/cortexproject/cortex/pull/5917, new metric `ingester_client_inflight_push_requests` for ingester client was introduced. This metric got ingester address as label. This metric should be cleaned when client is closed to avoid high cardinality. 
**Checklist**
=> Clean up ingester client inflightPushRequests on close

CHANGELOG.md, docs/configuration/arguments.md, docs/configuration/config-file-reference.md, pkg/ring/kv/etcd/etcd.go
Adding the -etcd.ping-without-stream-allowed parameter
This parameter allows the setting of the PermitWithoutStream  so it can be disabled  (default behaviour is still true).
Allowing to set this Parameter  is a solution for 
https://github.com/cortexproject/cortex/issues/5897
Fixes #5897 
**Checklist**
=> Adding the -etcd.ping-without-stream-allowed parameter

pkg/storage/tsdb/bucketindex/loader.go
This PR fix the issue where the Context comes in cancelled during a query split and giving the false impression that it cannot load the bucket index.
**Checklist**
- [NA ] Tests updated
=> Catch context error when getting bucket index

pkg/ingester/client/client.go
Create one more bucket for ingester client request time histogram.
Today we have 6 bucket which are
`[1, 4, 16, 64, 256, 1024]` ms
Cortex default timeout is 2s
```
f.DurationVar(&cfg.RemoteTimeout, "distributor.remote-timeout", 2*time.Second, "Timeout for downstream ingesters.")
```
It would be benefital to add a new bucket which would be `4096s`
**Checklist**
=> Increase number of buckets for ingester_client_request_duration_seconds

docs/configuration/config-file-reference.md, pkg/cortex/runtime_config_test.go, pkg/ingester/limiter.go, pkg/util/validation/exporter.go, pkg/util/validation/limits.go
Removing deprecated chunk storage flag.
This flag was used on chunk storage but we removed chunk storage 2 releases ago.
**Checklist**
=> Removing deprecated chunk storage flag

pkg/querier/tenantfederation/merge_queryable.go, pkg/querier/tenantfederation/merge_queryable_test.go
We are creating a job which has the tenant name for each tenant to
query, but we use the incorrect index in the `ids` slice that contains
the list of tenants. This causes the querier to select results for the
first tenant in the list of tenants to match with instead of the actual
tenant the querier was intended for.
I updated the existing tests to check the labels of the results as well
instead of only relying on the number of series found.
Fixes https://github.com/cortexproject/cortex/issues/5941
**Checklist**
=> Select correct tenant during query federation

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
We have the `user` and `type` dimensions in the wrong order for this metric. This PR is fixing that.
**Checklist**
=> Fix `cortex_ingester_tsdb_head_samples_appended_total` metric dimentions

docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/limiter.go, pkg/ingester/metrics.go, pkg/ingester/user_state.go, pkg/util/validation/limits.go, tools/doc-generator/parser.go
This pull request (PR) introduces a new limit Active Series "Per LabelSet." This limit functions similarly to -ingester.max-series-per-metric, but allowing users to define the maximum number of series per LabelSet.
These limits are configurable via runtime settings and with the following format:
```
max_series_per_label_set:
- label_set:
labelName1: LabelValue1
limit: 10
- label_set:
labelName1: LabelValue1
labelName2: LabelValue2
limit: 3
```
The limits are applied "Per labelset", meaning that only metrics containing all the labels of the limit will be subjected to it.
Additionally, a new metric is implemented to monitor the active timeseries for each limit as follows:
```
cortex_ingester_active_series_per_labelset{labelset="{label1=\"value1\"}",user="1"} 3 …
```
=> Proposal: Create a new "Per LabelSet" limit

CHANGELOG.md, pkg/ruler/api_test.go, pkg/util/api/response.go
Omit empty data field in response to be consistent with Prometheus and Grafana.
**Checklist**
=> Fix response with data omitempty

pkg/chunk/chunk.go, pkg/chunk/encoding/encoding.go, pkg/chunk/iterator.go, pkg/querier/batch/batch.go, pkg/querier/batch/batch_test.go, pkg/querier/batch/chunk.go, pkg/querier/batch/chunk_test.go, pkg/querier/batch/merge.go, pkg/querier/batch/merge_test.go, pkg/querier/batch/non_overlapping.go, pkg/querier/batch/non_overlapping_test.go, pkg/querier/batch/stream.go, pkg/querier/batch/stream_test.go, pkg/util/histogram/testutils.go
Support native histogram chunks in batch iterator. This should unlock native histogram support in Querier.
Since we haven't added support to ingest native histograms yet, I will try to add querying native histograms of Querier in another PR.
**Checklist**
=> Implement histogram iterators for batch

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/limiter.go, pkg/ingester/user_state.go
Follow up of https://github.com/cortexproject/cortex/pull/5950
This PR is adding some missing things:
* Changelog
* Add the `per_labelset_series_limit` dimention on the `cortex_discarded_samples_total` metric
* Backfill the new limits when Updating the `cortex_ingester_active_series_per_labelset`
* Before this change, a new metric "matching" the new limits needed to be added so we could backfill it. 
**Checklist**
=> Backfilling the new limits when updating the metrics

CHANGELOG.md, go.mod, go.sum, pkg/storegateway/bucket_stores.go, pkg/util/log/wrappers.go, vendor/github.com/thanos-io/thanos/pkg/block/metadata/markers.go, vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/compact/planner.go, vendor/github.com/thanos-io/thanos/pkg/extpromql/parser.go, vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go, vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/github.com/thanos-io/thanos/pkg/store/proxy.go, vendor/github.com/thanos-io/thanos/pkg/tenancy/tenancy.go, vendor/modules.txt
Pull https://github.com/thanos-io/thanos/pull/7367 and configure request logger to include context information.
Tested locally. `test-id=abc` are request ID used as an example.
```
ts=2024-05-17T22:37:23.817443Z caller=bucket.go:1140 level=info org_id=fake test-id=abc block=01HXQFWA3CDSRX9ZTHGFS4GTQS msg=posting
```
**Checklist**
=> Add request id to store gateway logger

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go
In v1.15.2, ingesters configured with OOO samples ingestion enabled
could hit this bug (https://github.com/cortexproject/cortex/issues/5402)
where ingesters would not upload compacted blocks
(https://github.com/thanos-io/thanos/issues/6462).
In v1.16.1, ingesters are configured to always upload compacted blocks
(https://github.com/cortexproject/cortex/pull/5625).
In v1.17, ingesters stopped uploading compacted blocks
(https://github.com/cortexproject/cortex/pull/5735).
This can cause problems for users upgrading from v1.15.2 with OOO
ingestion enabled to v1.17 because both versions are hard coded to
disable uploading compacted blocks from the ingesters.
The workaround was to downgrade from v1.17 to v1.16 to allow those
compacted blocks to be uploaded (and eventually …
=> Parameterize ingester upload compact blocks

integration/e2e/db/db.go
Using `minio/health/live` instead of `/minio/health/ready` to determine if the minio is running.
The Liveness probe is deeper than the ready probe as explained here:
https://gist.github.com/nitisht/0c11d8c670f565b58d930b526ba0f2ed
```
17:12:57 Starting minio-9000
17:12:57 Ports for container: e2e-cortex-test-minio-9000 Mapping: map[9000:32775]
alertmanager_test.go:169: 
Error Trace:	/home/runner/work/cortex/cortex/integration/alertmanager_test.go:169
Server not initialized, please try again.
upload s3 object
github.com/thanos-io/objstore/providers/s3.(*Bucket).Upload
/home/runner/work/cortex/cortex/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:514
github.com/cortexproject/cortex/integration.TestAlertmanagerClustering …
```
=> [Flaky test ] Using minio live probe to check if the minio is running

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, integration/query_frontend_test.go, pkg/cortex/modules.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go
This configuration is deprecated for a long time.
This PR is removing this config from the codebase:
```
[query_store_for_labels_enabled: <boolean> | default = false]
```
**Checklist**
=> Remove `query_store_for_labels_enabled` configuration

pkg/ring/ring_test.go
* seems we wanted to use the random with a seed to make the fuzzy test reproducible locally but we were not using the `rnd` struct with the defined seed to get the random numbers.
* This will make easier to reproduce the test locally when it fail.
**Checklist**
=> Using the `random` created on the test instead the default rand

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/ruler/ruler.go, pkg/ruler/ruler_ring.go
Allow rulers to reuse tokens across restarts. This is important for us because when you are running a fleet with a large numbers of rulers that are updated one at a time, you get a lot of churn if the tokens are not persistent across restarts: rule groups that were owned by a ruler might change ownership several times because every time they find a new owner, this new owner is also restarted. By preserving the tokens the churn is reduced because after the restart the rules will return to the original ruler that they belong to.
**Checklist**
=> rulers: Add support to persist tokens in rulers

pkg/ring/kv/memberlist/memberlist_client_test.go, pkg/ring/lifecycler_test.go
The tests rely on the CPU's wall clock which can be unreliable if there is CPU starvation. If we give the tests enough time to run, they are more much more reliable and resilient to CPU starvation.
Increase time for testing
**Checklist**
=> Fix Ring/Memberlist Join Test Flakiness

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/metrics.go, pkg/ingester/user_state.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
MaxSeriesPerLabelset was introduced on https://github.com/cortexproject/cortex/pull/5950 but the configuration format would not allow us in the future to configure more limits as "samples ingested per labelset"
This PR is just changing the configuration to be a bit more generic where we can extend to other limits in the future:
Config Before:
```
max_series_per_label_set:
- label_set:
labelName1: LabelValue1
limit: 10
- label_set:
labelName1: LabelValue1
labelName2: LabelValue2
limit: 3
```
Config Now:
```
limits_per_label_set:
- label_set:
labelName1: LabelValue1
limits:
max_series: 10
- label_set:
labelName1: LabelValue1
labelName2: LabelValue2
limits:
max_series: 3
```
We also changed the usage metric from `cortex_ingester_active_series_per_labelset ` to …
=> Changing the per labelset config to be more generic

pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/bucket_client_test.go
I noticed that store gateway still retry even when the context is canceled when fetching data from S3. Explicitly check the errors so we don't have to retry and wait for the backoff time.
**Checklist**
=> S3 bucket: Don't retry when ctx cancel

pkg/querier/tripperware/merge.go, pkg/querier/tripperware/merge_test.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/query.pb.go, pkg/querier/tripperware/query.proto, pkg/querier/tripperware/query_test.go
Support querying native histograms in query frontend.
Have to copy and change quite a bit of serialization code from client_golang since we use our own protobuf type.
**Checklist**
=> support querying native histograms in query frontend

pkg/distributor/distributor_test.go
Follow up of https://github.com/cortexproject/cortex/pull/5986.
Update unit tests for distributor push and query native histograms. 
**Checklist**
=> Update unit tests for distributor push native histograms

MAINTAINERS
I would like to call for a vote to add @CharlieTLe as Cortex mantainer.
Charlie has been very active in contributing to Cortex. Here is [a list of Charlie's contribution](https://github.com/cortexproject/cortex/issues?q=author%3ACharlieTLe). I can see Charlie is very invested in Cortex and will continue to do so in the years to come.
Per [existing change in maintainership governance rule](https://cortexmetrics.io/docs/contributing/governance/#changes-in-maintainership), 2/3 majority votes are required for the changes to pass.
Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first.
=> [Vote] Charlie Le (CharlieTLe) as new Cortex maintainer

CHANGELOG.md, pkg/querier/querier.go, pkg/querier/querier_test.go
Even though `ignoreMaxQueryLength` is set to true to disable max query length check at Querier, we still want to enforce it for `/api/v1/series` API. Because there is not a dedicated GetSeries tripperware in Query Frontend. So when `ignoreMaxQueryLength` set to false, there is no protection for `/api/v1/series` API.
**Checklist**
=> Enforce /api/v1/series API query length check at Querier

pkg/ring/token_generator.go, pkg/ring/token_generator_test.go
Fix cases where 2 ingesters have the same `RegisteredTimestamp` and end up generating the same tokens for the MinimizeSpreadToken token generation strategy. 
**Checklist**
=> Using Ingester Id as a tiebreaker for MinimizeSpreadTokenGenerator

integration/e2e/util.go, integration/native_histogram_test.go
Follow up of https://github.com/cortexproject/cortex/pull/6031. This PR adds integration for native histograms.
**Checklist**
=> Integration test for native histograms

CHANGELOG.md, pkg/cortex/cortex.go
This PR changes Cortex server to always enable native histogram instrumentation for `cortex_request_duration_seconds` metric.
This is a change for Cortex users if their monitoring Prometheus enables `native-histogram` feature. `cortex_request_duration_seconds_bucket`, `cortex_request_duration_seconds_sum` and `cortex_request_duration_seconds_count` metric will be converted into native histogram `cortex_request_duration_seconds`.
If `native-histogram` feature is not enabled then there is no user facing changes.
**Checklist**
=> Enable native histogram for Cortex req duration metric

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, pkg/ingester/ingester.go, pkg/ingester/lifecycle_test.go, pkg/util/strings.go
We implemented an experimental feature to dedup label strings in memory.
When adding a new series, we check if the string is already used by other series and if so, we return the previous reference for the same canonical string. Additionally, a reference count is maintained to determine when a string can be safely removed from memory.
The dedup is done on the `PostCreation` and `PostDeletion` hooks from TSDB.
As far as i can tell it seems safe to do so there as those hooks are called sync when creating the new series.
https://github.com/prometheus/prometheus/blob/main/tsdb/head.go#L2026
During initial testing, we observed a notable reduction in HEAP size on the ingesters, ranging from 25% to 30%. No changes on CPU was noticed.
Fixes …
=> Adding experimental flag for Metrics Labels String Interning

pkg/storage/tsdb/bucketindex/loader.go
Query failure or timeout would cause context got cancelled anytime before loading bucket index. This change should make sure `cortex_bucket_index_load_failures_total` will not increase if such thing happens.
**Checklist**
=> Make sure bucket index load failure will not increase if there is context error

CHANGELOG.md, pkg/ring/token_generator.go, pkg/ring/token_generator_test.go
Before this PR, the `MinimizeSpreadTokenGenerator` was not taking into consideration the current ownership of an ingester when generating extra tokens for it.
Lets say that the expected ownership of an ingester is 5% and we it already have 3% ownership. When trying to generate new tokens before this fix, the ingester would end up with 8% ownership instead of 5%. 
This case can happen when we have tokens conflict.
**Checklist**
=> [Minimize Spread Token Generator] Calculate current ownership when generating tokens for an ingester that already have tokens

CHANGELOG.md, pkg/api/api.go, pkg/ingester/ingester.go, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go
Create a new section on the ingester ring status page to allow operator to renew ingesters tokens.
Sometimes this can be useful when dealing with hot sharding.
**Checklist**
=> Allowing renenerate ingester tokens

integration/e2e/util.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester_test.go, pkg/querier/batch/batch_test.go, pkg/querier/batch/chunk_test.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/querier_test.go, pkg/ruler/compat_test.go, pkg/util/histogram/testutils.go, pkg/util/test_util.go
Reuse Prometheus upstream `tsdbutil` package to generate test histograms data.
**Checklist**
=> Reuse native histogram test functions from Prometheus

build-image/Dockerfile
- Updates the build image to use go 1.22.5
- Will update the go.mod in a follow up PR
Reason for updating:
- I want to bring in the latest version of Thanos PromQL engine. They've updated to 1.22 [here](https://github.com/thanos-io/promql-engine/blob/main/go.mod#L3)
**Checklist**
=> Update build image go version to 1.22.5

build-image/Dockerfile
- Updating faillint to support go 1.22
**Checklist**
=> Update faillint for go 1.22

CHANGELOG.md, integration/e2e/util.go, integration/e2ecortex/client.go, integration/native_histogram_test.go, integration/otlp_test.go
Also changed native histogram tests to allow comparing native histogram count and sum rather than simply checking nil.
Fixes #6070
**Checklist**
=> Support exponential histogram in OTLP ingestion

CHANGELOG.md, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/query.go, pkg/ring/model.go, pkg/ring/ring.go, pkg/ring/util_test.go
Change the metrics `cortex_distributor_ingester_appends_total`, `cortex_distributor_ingester_append_failures_total`, `cortex_distributor_ingester_queries_total`, and `cortex_distributor_ingester_query_failures_total` to use the ingester ID instead of the IP as the label value.
Previously, we used the IP as the label value, which made it challenging to correlate IP addresses with specific ingesters and resulted in unclear dashboard graphs.
With this change, the ingester ID will be used instead of the IP.
Before:
After:
**Checklist**
=> Using ingester id instead of address on the distributor metrics.

pkg/compactor/compactor_test.go
Function `CompactWithBlockPopulator` should return `[]ulid.ULID`. However, in compactor_test.go, two places of mocked 
`CompactWithBlockPopulator` function return `ulid.ULID`. This PR fixed the incorrect return value.
**Checklist**
=> Fixed incorrect return value for mocked function

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance_limits.go, pkg/ingester/instance_limits_test.go
This PR extended work done at #5798.
From tests, it was noticed that the metrics is accurate but does not show the impacting volume on ingester. I am proposing to remove from the metric any pre and post execution and count the metric only when the ingester is actually resolving the query. That from tests is when we see issues with CPU usage on ingesters.
Also adding a new ingester instance limit, similar to the existent `max_inflight_push_requests` to limit the max number of inflight queries on ingesters. The reads are from any GET operation on ingesters.
**Checklist**
- [] Documentation added
=> Add new query inflight request on ingester

CHANGELOG.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/util/log/wrappers.go
Created `WithExecutionID` wrapper for log and use it for each compaction cycle. With this, it is easier to debug compactor issue through log.
**Checklist**
=> Add unique execution ID for each compaction cycle in log for easy debugging

CHANGELOG.md, pkg/ring/batch.go
Avoid nesting httpgrpcutil.WrapHTTPGrpcError.
This cluster has ~600 QPS, and ~400 of them are 2xx.
**Checklist**
=> Reduce distributor memory usage when error volume is high

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortexpb/histograms.go, pkg/distributor/distributor.go, pkg/util/validation/errors.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Introduce a new limit `max_native_histogram_buckets` which limits maximum number of buckets of a native histogram sample. When exceeding the limit, Distributor will try to reduce the ingested histogram resolution until it is within the buckeet limit or the resolution can't be reduced anymore.
Fixes #6092
**Checklist**
=> Implement max bucket limit and automatic resolution reduction

pkg/ingester/ingester.go
This PR adds `CompactOOOHead` at the end of `userTSDB.compactHead`.
Fixes #6107 
**Checklist**
=> Ingester: compact ooo head during head compaction

development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml, development/tsdb-blocks-storage-s3-gossip/dev.dockerfile, development/tsdb-blocks-storage-s3-gossip/docker-compose.yml, development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml, development/tsdb-blocks-storage-s3/config/cortex.yaml, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-s3/docker-compose.yml, development/tsdb-blocks-storage-swift-single-binary/docker-compose.yml
Fixed cortex dockerfile and updated consul docker image tag so that docker compose is able to successfully pull consul and swift images.
Removed invalid enable_alertmanager_v2 cortex config param from microservice mode config files to fix cortex start up.
cleanup: removed 'version' compose tag to silence deprecation warning
Fixes #None
**Checklist**
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> fix(build): docker compose environments

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Split cleaner cycle into two separated cycles. One is for active tenants to be cleaned for deleted blocks and update bucket index. Another cycle is for deleted tenants to be cleaned for any data upon deletion. The reason separating those two is that sometime cleaning data for deleted tenant could take a long time to fully delete all blocks if the tenant is large enough. This would block the rest of tenants to be cleaned or deleted which would result in delay bucket index update for active tenants. Separating could prevent this kind of blockage to happen
**Checklist**
=> Split cleaner cycle for active and deleted tenants

MAINTAINERS
I can't believe this day would come, but I am stepping down as Cortex maintainer because I no longer have capacity to give Cortex the love it needs anymore. Also, Cortex is in good hands with existing maintainers from diverse set of companies.
It's been a fun ride. I still remember my [first Cortex PR](https://github.com/cortexproject/cortex/pull/2741) that allows me to build Cortex in my employer's network, and [the day I became maintainer 3 years ago](https://github.com/cortexproject/cortex/commit/b4daa22055ffec14311d8b5d2d9429f1bd575dad). It was full of joys and emotions. But there is always an end to a party, and for me it's today. 
Thank you all for the great work and support thus far!
=> Stepping down as Cortex maintainer

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
Fix `cortex_ingester_tsdb_mmap_chunks_total` metric. This metric is `prometheus_tsdb_mmap_chunks_total` is a counter, not a gauge. 
https://github.com/prometheus/prometheus/blob/5681ec50e1fc1e591c4dcc63eb343478ea2082ee/tsdb/head.go#L498-L501
**Checklist**
=> Fix cortex_ingester_tsdb_mmap_chunks_total metric

CHANGELOG.md, pkg/util/push/otlp.go
This PR makes the OTLP handler consistent on metric name.
`AddMetricSuffixes` is set to true in Prometheus OTLP handler but we don't apply the same. https://github.com/prometheus/prometheus/blob/main/storage/remote/write_handler.go#L506
**Checklist**
=> OTLP handler: enable metric name normalization

CHANGELOG.md, integration/e2ecortex/client.go, integration/otlp_test.go, pkg/cortexpb/histograms.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go
Seems `Histograms` was not successfully included as part of the Push request when calling the OTLP handler. The unit test didn't catch this problem with insufficient coverage and there is a bug in the integration test where it calls `Push` instead of `OTLP` handler
**Checklist**
=> Fix OTLP native histogram push

pkg/ruler/api.go, pkg/ruler/api_test.go, pkg/ruler/ruler.go, pkg/ruler/rulespb/compat.go
This is a follow-up to #6085, which added support for setting the `query_offset` field on individual recording rule groups, as well as a per-tenant `ruler_query_offset` limit that should be used when no individual recording rule group offset is set.
It turns out that compatibility code to convert from a protobuf RuleGroup to a prometheus RuleGroup was coercing null-value query offsets to explicit 0s, which meant that no rule groups would ever fall back to the per-tenant offset.
This PR fixes that issue, and it cleans up handling of the query offset in a few other ruler files.
**Testing**
To test this locally, I started cortex with a 1m per-tenant `ruler_query_offset` limit:
```
$ curl -s http://localhost:9009/config | grep query_offset
ruler_query_offset: 1m
```
Then I created some …
=> Fix query offset issue on individual rule groups

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Add a new per tenant metric called _cortex_query_samples_total_ which contains the number of fetched samples for each query requests. It provides an accurate count of fetched samples for each tenants.
**Checklist**
=> Add cortex_query_samples_total metric

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/querier/querier.go
Deprecate and enable by default `querier.ingester-metadata-streaming` flag and mark to be removed after v1.18.
This flag is around and stable for more than 2 years and there is no reason to be disabled. 
**Checklist**
=> Deprecate 'querier.ingester-metadata-streaming' flag

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/frontend/v1/frontend.go, pkg/frontend/v1/frontend_test.go, pkg/frontend/v1/queue_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/queue/user_queues.go, pkg/scheduler/queue/user_queues_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
We documented to deprecate this flag after 1.17
**Checklist**
=> Deprecating `querier.max-outstanding-requests-per-tenant` and `-query-scheduler.max-outstanding-requests-per-tenant` flags

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/backward_compatibility_test.go, pkg/frontend/v2/frontend.go, pkg/ingester/client/client.go, pkg/querier/worker/worker.go, pkg/ruler/ruler.go, pkg/scheduler/scheduler.go, pkg/util/grpcclient/grpcclient.go
Enable `snappy-block` compression on ingester clients.
This compression gives up to 10x less network and no notable CPU difference:
See: 
https://github.com/cortexproject/cortex/pull/5215#issuecomment-1474662520
https://github.com/cortexproject/cortex/pull/5215#issuecomment-1478837526
This compression showed to reduce the network 
**Checklist**
=> Enable 'snappy-block' compression on ingester clients by default

pkg/ruler/ruler_test.go
When test calls 
```
r.syncRules(context.Background(), rulerSyncReasonInitial)
```
It will also start the manager and eval for the rules.
In some cases the eval runs faster than the comparison for tests using health filter. If the eval runs, it will change rule's health to `OK` or `BAD`. This will make the test fail as it will not be what it is expecting.
Increasing the interval makes a longer wait before running the eval which gives more time for the test to finish.
Fixes #6106
**Checklist**
=> Increase interval for ruler test

CHANGELOG.md, integration/query_frontend_test.go, pkg/querier/tripperware/query_attribute_matcher.go, pkg/querier/tripperware/query_attribute_matcher_test.go
Fix for bug in query rejection 
Fixes #6143 
**Checklist**
=> fix for query_rejection bug

pkg/ingester/ingester.go, pkg/querier/series/series_set.go, pkg/storage/tsdb/inmemory_index_cache.go, pkg/util/context.go
Apply the same as https://github.com/prometheus/prometheus/pull/14118 to only check context cancellation every 128 iterations. This should help with the performance a bit but overall it is just a small portion of the CPU profile.
**Checklist**
=> Check context cancellation every 128 iterations

CHANGELOG.md, pkg/querier/querier.go
At modifier flag was marked as deprecated in release v1.14.0. This PR removes it
**Checklist**
=> Remove querier.at-modifier-enabled flag

CHANGELOG.md, pkg/tracing/tracing.go
`oltp_endpoint` config was marked as deprecated since release v1.15.0. We already keep it for 2 releases and we can remove the flag.
**Checklist**
=> Remove tracing oltp endpoint flag

CHANGELOG.md, docs/blocks-storage/store-gateway.md, pkg/storegateway/gateway_ring.go
In https://github.com/cortexproject/cortex/pull/5489, we added a new shuffle sharding strategy to ensure consistency when zone aware.
We claimed to make this the default in release 1.17 and remove the old option in release 1.18.
Since we missed it last release, we make it the default in the upcoming 1.18 release and remove the old algorithm in release 1.19  
**Checklist**
=> Always enable zone stable shuffle sharding for store gateway

docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/partition_compaction_grouper.go, pkg/compactor/partition_compaction_planner.go, pkg/util/shard.go
This PR only introduced feature flag and logic to switch between current shuffle sharding group planner and partition compaction group planner. Nothing is implemented for partition compaction group planner yet.
**Checklist**
=> Create feature flag to switch between current shuffle sharding group planner and partition compaction group planner

CHANGELOG.md, integration/ruler_test.go, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
Add a new per tenant metric called `cortex_ruler_rule_groups_in_store` which contains the number of rule groups each tenant has in store (s3 for example). The metric provides an accurate count of rule groups that is not affected by the health of the rulers or resharding.
Fixes #5866 
**Checklist**
=> Add cortex_ruler_rule_groups_in_store metric

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/manager_metrics.go, pkg/ruler/manager_metrics_test.go, pkg/ruler/ruler.go
Add query statistics metrics to Ruler when _--ruler.query-stats-enabled=true_ to track how many data are fetched by the alerting rule or recording rules for each tenants. 
**Checklist**
=> Add query metrics to ruler query stats

CHANGELOG.md, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Create a new metric, cortex_reduced_resolution_histogram_samples_total, to track the number of native histogram samples that had to be reduced because the number of buckets exceeded the allowed limit.
**Checklist**
=> Create `cortex_reduced_resolution_histogram_samples_total` metric

pkg/ruler/ruler_test.go
- This one test was not using the temp dir for storing rules.
- The following files were always created when running tests locally:
- `pkg/ruler/user2/namespace`
- `pkg/ruler/user3/namespace`
**Checklist**
=> Use temp dir for ruler LoadPartialGroups test

docs/proposals/ruler-ha-new.md, docs/proposals/ruler-ha.md
Proposal for Ruler HA
I can add more details as necessary
**Checklist**
=> Ruler HA - Proposal

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/ruler_test.go, pkg/cortex/modules.go, pkg/ruler/compat.go, pkg/ruler/frontend_client.go, pkg/ruler/frontend_client_pool.go, pkg/ruler/frontend_client_test.go, pkg/ruler/frontend_decoder.go, pkg/ruler/frontend_decoder_test.go, pkg/ruler/manager.go, pkg/ruler/manager_test.go, pkg/ruler/ruler.go
Add `ruler.frontend-address` to allow query to query frontends instead of ingesters. If `-ruler.frontend-address` is set, rulers query to query frontends for evaluating rules. It can support query frontend features like vertical query sharding.
Fixes #5105 
**Checklist**
=> Support Ruler to query Query Frontend

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
- Store-gateway now accepts a new limit param: https://github.com/thanos-io/thanos/pull/7652
- Now we can pass the limit parameter to store-gateway if set.
**Note**:
- The TODOs can be addressed after changes in both Thanos and Prometheus in the merge functions.
**Checklist**
=> StoreGateway: Implement metadata API limit in queryable

integration/querier_test.go
Saw this test fail: https://github.com/cortexproject/cortex/actions/runs/10761255507/job/29840284232
Adding this test option to make the test wait until the metric is available.
```
querier_test.go:231: 
Error Trace:	/home/runner/work/cortex/cortex/integration/querier_test.go:231
metric not found
github.com/cortexproject/cortex/integration/e2e.init
<autogenerated>:1
runtime.doInit1
/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/proc.go:7176
runtime.doInit
/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/proc.go:7143
runtime.main
/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/proc.go:253
runtime.goexit
/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/asm_amd64.s:1695 …
```
=> fix: querier integration flaky test

pkg/ingester/http_admin.go, pkg/ingester/http_admin_test.go, pkg/ingester/ingester_test.go, pkg/ring/model.go, pkg/ring/model_test.go
Fixed the following bugs related to ReadOnly state of ingester:
- `/ingester/all_user_stats` endpoint cannot have web page rendered properly. `LoadedBlocks` field got wrong name in template.
- Ingester with `ReadOnly` state is not considered as ready which would cause rolling update stuck if there is at least one ingester in `ReadOnly` state.
**Checklist**
=> Fixed ingester ReadOnly state related bugs

pkg/ring/lifecycler.go
Adds a timeout context to the lifecycler heartbeat to prevent requests to the ring from waiting indefinitely in case of a network issue.
Fixes #6211
**Checklist**
- [ N/A ] Tests updated
- [ X ] Documentation added
- [ X ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Add timeout on lifecycler heartbeat

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
In Distributor's validation logic, we currently update `DiscardedSamples` metric when there is no label.
However, it doesn't count native histogram samples, only normal samples. It doesn't track discarded exemplars or track it in a wrong way https://github.com/cortexproject/cortex/blob/master/pkg/distributor/distributor.go#L898
**Checklist**
=> Improve validation metrics for discarded samples and exemplars

CHANGELOG.md, integration/api_endpoints_test.go, integration/getting_started_single_process_config_local_test.go, integration/getting_started_single_process_config_test.go, integration/getting_started_with_gossiped_ring_test.go, integration/integration_memberlist_single_binary_test.go, integration/otlp_test.go, integration/querier_test.go, integration/query_fuzz_test.go, integration/ruler_test.go, integration/runtime_config_test.go, pkg/cortex/cortex_test.go, pkg/cortex/modules.go
Enable compactor and alertmanager in target all.
Fixes #6098 
**Checklist**
=> Enable compactor and alertmanager in target all

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Root cause:
[tsdb.DefaultBlocksToDelete](https://github.com/cortexproject/cortex/blob/master/vendor/github.com/prometheus/prometheus/tsdb/db.go#L1629) has logic to get blocks beyond retention period ([tsdb.BeyondTimeRetention](https://github.com/cortexproject/cortex/blob/master/vendor/github.com/prometheus/prometheus/tsdb/db.go#L1671)). However, this code only check retention period of a block against the newest block in TSDB. If TSDB stopped getting newer blocks, any existing blocks within retention period against the newest block currently in TSDB will never got deleted. 
For instance:
Retention period is set to 1h
Current time is: 2024-09-24T10:00:00Z
Blocks in TSDB:
block 1: MaxTime: 2024-09-24T06:00:00Z
block 2: MaxTime: 2024-09-24T05:50:00Z
block 3: MaxTime: …
=> Fixed bug that blocks cannot be fully deleted from TSDB

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/config_test.go
Add `blocks-storage.tsdb.wal-compression-type` to support zstd wal compression type. Deprecate `blocks-storage.tsdb.wal-compression-enabled`.
**Checklist**
=> Add tsdb wal compression type zstd

docs/configuration/config-file-reference.md, pkg/ruler/ruler.go
=> Make LivenessCheck Timeout Configurable

integration/e2e/scenario_test.go, integration/e2e/service.go
The E2E tests use `docker stop` to stop the container, but the container can still be in the process of being removed after the stop command is executed. This can cause tests that stop and start a container in rapid succession with the same container name to fail with conflicting container names.
Example error message in an integration test:
```
00:08:14 Stopping query-frontend
00:08:14 Stopping store-gateway
=== RUN
TestNewDistributorsCanPushToOldIngestersWithReplication/Backward_compatibility_upgradir
00:08:14 Starting store-gateway
00:08:14 store-gateway: docker: Error response from daemon: Conflict. The container name "/e2e-cortex-test-store-gateway" is already in use by container "b750a7b7e2e3eebc617ac832de2c8a643f884bbc79b0c8961ceebace8cad5c85". You have to …
```
=> Wait until container is removed after stopping

integration/e2ecortex/client.go, integration/otlp_test.go
Add an otlp exemplar ingestion test.
Fixes #6235 
**Checklist**
=> Add otlp exemplar ingestion test

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, integration/querier_test.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/caching_bucket_test.go
Add an in-memory chunk cache to Store Gateway.
Fixes #6239 
**Checklist**
=> Add in-memory chunk cache

pkg/querier/querier.go, pkg/querier/querier_test.go
Check day range limit in LabelNames and LabelValues. Return query too long error if `MaxQueryLength` limit is exceeded.
=> [Querier] Add day range limit for LabelNames and LabelValues

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/caching_bucket.go
Edit metadata cache backend description to be more accurate.
Fixes
**Checklist**
=> [Chore] Edit metadata cache supported values description

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/ingester/client/client.go, pkg/querier/store_gateway_client.go, pkg/querier/store_gateway_client_test.go, pkg/util/grpcclient/grpcclient.go, pkg/util/grpcclient/health_check.go, pkg/util/grpcclient/health_check_test.go
WIP/Proposal
Create a experimental HealthCheck GRPC Handler.
This health check will evaluate the targets and immediately terminate the request if a target is marked as unhealthy.
Immediately terminating the request when the target is unresponsive provides two major benefits:
* Prevent overload on distributors
* Avoid trying to call unhealthy SG and so, retry the request on a healthy one faster.
**Checklist**
=> Create a experimental HealthCheck GRPC Handler

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, integration/querier_test.go, pkg/storage/tsdb/caching_bucket.go, pkg/storage/tsdb/caching_bucket_test.go, pkg/storage/tsdb/multilevel_chunk_cache.go, pkg/storage/tsdb/multilevel_chunk_cache_test.go
Support multi-level chunk cache like a multi-level cache for the index and add metrics for tracking multi-level cache behavior.
- `cortex_store_multilevel_chunks_cache_fetch_duration_seconds`, tracks latency to fetch item
- `cortex_store_multilevel_chunks_cache_backfill_duration_seconds`, tracks latency to backfill item
- `cortex_store_multilevel_chunks_cache_backfill_dropped_items_total`, tracks # of dropped items due to buffer fullness when backfilling
- `cortex_store_multilevel_chunks_cache_store_dropped_items_total`, tracks # of dropped items due to buffer fullness when storing
Add a multi level chunk cache
Fixes #6240 
**Checklist**
=> Add multi-level chunk cache

CHANGELOG.md, pkg/util/grpcclient/health_check.go, pkg/util/grpcclient/health_check_test.go
Fix connection leak on the health check. See https://github.com/cortexproject/cortex/pull/6225
This happened when the healthcheck interval was > than 1 second. In this case we were opening the connections and not closing it.
**Checklist**
=> Fix healthcheck interceptors

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/index_cache.go
Change `-blocks-storage.bucket-store.index-cache.memcached.max-async-concurrency` default value 50 to 3 as mentioned in #6249
**Checklist**
=> Add index cache max async concurrency

pkg/util/grpcclient/health_check.go, pkg/util/grpcclient/health_check_test.go
Just a small change to avoid creating new connections on every health check call.
**Checklist**
=> Reusing the grpc client to perform health check

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/querier.go
By exposing the number of store gateway consistency check attempts from Querier, users can customize with higher retries based on their configuration of Replication Factor
**Checklist**
=> expose flag for max store gateway consistency check attempts

docs/configuration/single-process-config-blocks-gossip-1.yaml, docs/configuration/single-process-config-blocks-gossip-2.yaml, docs/configuration/single-process-config-blocks-local.yaml, docs/configuration/single-process-config-blocks-tls.yaml, docs/configuration/single-process-config-blocks.yaml
#6204 added Alertmanager to `all` target.
However, single process documents do not contain alertmanager configs, so the Cortex fails to start using these configs.
This PR adds alertmanager configs to single process documents.
**Checklist**
=> Add alertmanager config to single process documents

pkg/util/push/otlp_test.go
This PR adds `json` format otlp ingestion test. The decoder support both of `proto` and `json` format (https://github.com/prometheus/prometheus/blob/main/storage/remote/codec.go#L883). But, the existing test only covers the `proto` format ingestion.
This PR adds a test making sure the `json` format of the otlp push request also ingests well.
**Checklist**
=> Add json format otlp ingestion test

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go
This PR adds `-blocks-storage.s3.list-objects-version` to configure s3 list API version.
Use case: If users use s3 compatible backends that don't fully support `ListObjectV2`, they (including me) would want to use V1 api. 
The thanos expose it (https://github.com/thanos-io/objstore/blob/23ebe2eacadd89cf23bf0fbd931352112b4c846d/providers/s3/s3.go#L137).
**Checklist**
=> Add list objects version to s3 config

CHANGELOG.md, integration/query_fuzz_test.go, pkg/ingester/ingester.go
Disable chunk trimming in Ingesters to skip duplicated works in the query engine and Ingesters.
Fixes #6269 
**Checklist**
=> Disable chunk trimming in ingester

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/bucket/swift/bucket_client.go, pkg/storage/bucket/swift/config.go
Currently, the only way to auth is to use `username/password` when users use Swift backend. But there is a case where users don't know their OpenStack account but application credentials issued by others (administrators of Openstack account, they don't want to expose Openstack account's `username/password`). To address this concern, support an application credential auth for OpenStack swift backend so that users can auth in various ways (`username/password` or `application credential`).
**Checklist**
=> Support application credential auth for Openstack swift

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/query_fuzz_test.go, pkg/ingester/ingester.go
This changes https://github.com/cortexproject/cortex/pull/6270 to mark the behavior optional under a feature flag.
We noticed that query result got changed if disabling chunk trimming for the following test case, captured by fuzz test.
https://github.com/cortexproject/cortex/actions/runs/11621920479/job/32367371250?pr=6298 
The failure seems correctly captured as `timestamp` function returns timestamp of the sample so if certain samples are not trimmed then the result changes.
I think the behavior is not intended but let's make disable chunk trimming a feature flag for now and users can enable it at their own risk
```
query_fuzz_test.go:188: case 296 results mismatch.
range query: timestamp({__name__="test_series_3"} @ end() …
```
=> Put ingester disable chunk trimming a feature flag

go.mod, go.sum, integration/query_fuzz_test.go, vendor/github.com/cortexproject/promqlsmith/opts.go, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/modules.txt
Upgrade promqlsmith to https://github.com/cortexproject/promqlsmith/pull/129 to support `label_join` and `label_replace`.
Improved existing `TestDisableChunkTrimmingFuzz` test case to generate multiple series under a single metric name as well as reducing the generated queries' complexity.
**Checklist**
=> Support label_join and label_replace in query fuzz tests

docs/configuration/config-file-reference.md, pkg/querier/tripperware/queryrange/query_range_middlewares.go
=> fix typo in usage message for querier.split-queries-by-interval flag

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/memcache_client_config.go, pkg/storage/tsdb/redis_client_config.go
Change all `max-async-concurrency` default values `50` to `3`
it includes
`-blocks-storage.bucket-store.index-cache.memcached.max-async-concurrency`
`-blocks-storage.bucket-store.index-cache.redis.max-async-concurrency`
`-blocks-storage.bucket-store.chunks-cache.memcached.max-async-concurrency`
`-blocks-storage.bucket-store.chunks-cache.redis.max-async-concurrency`
FYI. `max-async-concurrency` default values of the multilevels (index, chunks) are already `3`.
**Checklist**
=> Change all max async concurrency

pkg/distributor/distributor_test.go
This PR fixes `BenchmarkDistributor_Push` to runnable.
Current `BenchmarkDistributor_Push` gets `panic`.
Reasons:
-  `noopIngester` not implements `PushPreAlloc`.
- `reg` in the distributor is nil, it causes `panic` at `validateMetrics: validation.NewValidateMetrics(reg)`. (https://github.com/cortexproject/cortex/blob/master/pkg/distributor/distributor.go#L356)
**Checklist**
=> Fix BenchmarkDistributor_Push benchmark

CHANGELOG.md, pkg/storegateway/chunk_bytes_pool.go, pkg/storegateway/chunk_bytes_pool_test.go
- Adding a new metric for tracking in-use bytes in store-gateway.
- This should help us catch leaks in the pool more easily
**Checklist**
=> storegateway: Add a metric for chunk pool inuse bytes

pkg/storage/tsdb/multilevel_chunk_cache.go, pkg/storage/tsdb/multilevel_chunk_cache_test.go
We can have a race when we partially fetch data on the multilevel cache. The reason for that is internally, the object store changes the dic returned by the cache and this races with the cache internal implementation.
Ex: https://github.com/thanos-io/thanos/blob/d6d19c568f8dc6005a9184d3a5a994da4f0d8c75/pkg/store/cache/caching_bucket.go#L469
Right now this PR only have the unit test demonstrating the issue.
PS: I also optimized the cache to not fetch keys that were already found on the previous cache implementation.
**Checklist**
=> Fix race on chunks multilevel cache + Optimize to avoid refetching already found keys. 

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/e2ecortex/client.go, integration/otlp_test.go, pkg/api/api.go, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go, pkg/util/validation/limits.go
Change otlp handler to consist with the prometheus otlp handler.
Changes are as follows:
- Enable `target_info` metric by default, it is only disabled when `distributor.otlp-config.disable-target-info` is `true`.
- Add `-distributor.otlp-config.convert-all-attributes` flag to retain the existing behavior (always convert all metric attributes)
- Add a per tenant config `distributor.promote-resource-attributes` to specify promte resource attributes for each tenants. It works only if `distributor.otlp-config.convert-all-attributes` is `false`.
Fixes #6236 
**Checklist**
=> Change otlp attribute conversion to be consistent with prometheus

pkg/storage/tsdb/expanded_postings_cache.go, pkg/storage/tsdb/expanded_postings_cache_test.go
Follow up of https://github.com/cortexproject/cortex/pull/6296
Under concurrency, we are fetching the postings multiples times for the same key.
The reason for that is we load the previous promise from the cache but the promise does not have the ts set yet and so, we assume is expired:
See:
https://github.com/cortexproject/cortex/blob/2e5488af4fc582b6f63afa4ec0543f31aef161c5/pkg/storage/tsdb/expanded_postings_cache.go#L320-L332
This PR is simplifying the implementation and waiting the loaded promise to finish before checking if is expired.
First commit of the PR has only the test showing the problem.
**Checklist**
- [NA] `CHANGELOG.md` updated - the order of entries should be …
=> Fix: PostingCache promise should fetch data only once

docs/architecture.md
The Openstack Swift can considered stable now. We've had it for over 4 years since #2440.
I've been running Cortex using Swift for longer than a year. It seems stable :D.
**Checklist**
=> Remove openstack swift experimental

pkg/storage/tsdb/expanded_postings_cache.go, pkg/storage/tsdb/expanded_postings_cache_test.go
Add reason why the key was evicted in the `cortex_ingester_expanded_postings_cache_evicts` metric
**Checklist**
=> Add reason why the key was evicted in the `cortex_ingester_expanded_postings_cache_evicts` metric

docs/blocks-storage/_index.md
This PR removes Openstack swift `experimental` at `Blocks Storage` section.
In #6316, it was removed at `architecture`.
I just found out it exists `Blocks Storage` section as well..
**Checklist**
=> Remove openstack swfit experimental in blocks storage

.github/workflows/test-build-deploy.yml, integration/query_fuzz_test.go
Use Prometheus v2.55.1 image in query fuzz as it fixes a query regression.
**Checklist**
=> Upgrade to use prometheus v2.55.1 in fuzz

go.mod, go.sum, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/inmem.go, vendor/github.com/thanos-io/objstore/objstore.go, vendor/github.com/thanos-io/objstore/providers/azure/azure.go, vendor/github.com/thanos-io/objstore/providers/azure/helpers.go, vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go, vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go, vendor/github.com/thanos-io/objstore/providers/s3/s3.go, vendor/github.com/thanos-io/objstore/providers/swift/swift.go, vendor/github.com/thanos-io/objstore/testing.go, vendor/modules.txt
Pull https://github.com/thanos-io/objstore/pull/153
**Checklist**
=> update thanos objstore library to pull object duration metric fix

integration/e2ecortex/client.go, integration/query_fuzz_test.go
In fuzz test, run 1000 test cases rather than 100 test cases. We found that 100 test cases might not be enough to capture some of the regression we saw.
**Checklist**
=> Run more test cases per query fuzz test

docs/getting-started/alerts.yaml, docs/getting-started/dashboards/alertmanager.json, docs/getting-started/dashboards/cortex-compactor-resources.json, docs/getting-started/dashboards/cortex-compactor.json, docs/getting-started/dashboards/cortex-config.json, docs/getting-started/dashboards/cortex-object-store.json, docs/getting-started/dashboards/cortex-queries.json, docs/getting-started/dashboards/cortex-reads.json, docs/getting-started/dashboards/cortex-rollout-progress.json, docs/getting-started/dashboards/cortex-scaling.json, docs/getting-started/dashboards/cortex-slow-queries.json, docs/getting-started/dashboards/cortex-writes.json, docs/getting-started/dashboards/ruler.json, docs/getting-started/rules.yaml
pulls in latest changes from cortex-jsonnet to update the dashboards in Grafana. also updates the alerting and recording rules.
Changes:
- https://github.com/cortexproject/cortex-jsonnet/pull/58
- https://github.com/cortexproject/cortex-jsonnet/pull/62
- https://github.com/cortexproject/cortex-jsonnet/pull/60
- https://github.com/cortexproject/cortex-jsonnet/pull/59
=> update cortex dashboards

docs/getting-started/Makefile, docs/getting-started/_index.md, docs/getting-started/docker-compose.yaml
- Adds more info to the getting started guide on what's in the guides
- Sets up seaweedfs before other services in single binary mode guide
- Fix healthchecks in docker-compose
- Set up recipe for cortex-jsonnet in Makefile
=> Update getting started guide, seaweedfs setup, and healthchecks in docker-compose

CHANGELOG.md, pkg/ruler/api_test.go, pkg/ruler/compat.go, pkg/ruler/ruler_test.go, pkg/ruler/store_mock_test.go
* Allow rules that are being evaluated to successfully complete/timeout when rulers are shutdown. Before this PR, we were canceling the context right away, wasting all the work performed by the queries.
This is done by removing the cancel signal of the context passed to the Prometheus rules manager. Instead we are going to rely on the shutdown mechanism of the rules manager and timeout of the queries executed by the rules.
In the unit tests I tried to avoid adding sleeps and instead used channels to coordinate the execution of the queries to simulate the problem. 
**Checklist**
=> Don't propagate cancel signal to the Prometheus rules manager context

pkg/cortex/modules.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_middlewares.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/instantquery/shard_by_query_test.go
We are using a globally initialized `InstantQueryCodec` everywhere and it defaults to `protobuf` codec. This PR removes the global codec
**Checklist**
Existing integration test should cover it.
=> Stop using global instant query codec

docs/guides/alert-manager-configuration.md, docs/guides/authentication-and-authorisation.md, docs/guides/capacity-planning.md, docs/guides/encryption-at-rest.md, docs/guides/encryption-at-rest.template, docs/guides/glossary.md, docs/guides/gossip-ring-getting-started.md, docs/guides/ha-pair-handling.md, docs/guides/ingesters-rolling-updates.md, docs/guides/ingesters-scaling-up-and-down.md, docs/guides/limitations.md, docs/guides/overrides-exporter.md, docs/guides/running-cortex-on-kubernetes.md, docs/guides/sharded_ruler.md, docs/guides/shuffle-sharding.md, docs/guides/tls.md, docs/guides/tracing.md, docs/guides/zone-replication.md
The guides could use some proof reading, so I've updated each of them so fix grammar issues and typos.
=> docs: proofread guides

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/api/api.go, pkg/distributor/distributor.go, pkg/util/http.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go
This PR adds `-distributor.otlp-max-recv-msg-size` flag to limit OTLP request size in bytes like the Prometheus remote write push.
Also, it adds otlp body decompression logic tests.
**Checklist**
=> Add flag for limiting OTLP request size

pkg/ruler/api.go, pkg/ruler/api_test.go
The JSON tag for ```GroupNextToken string       `json:"groupNextToken:omitempty"``` is incorrect. It should be ```GroupNextToken string       `json:"groupNextToken,omitempty"```
**Checklist**
=> Bug fix on JSON Tag

integration/query_fuzz_test.go
Relaxing a bit the float comparison on the fuzz test.
Currently, we allow floats to differ an absolute margin (1e-6). This PR is also allowing the floats to differ by a relative fraction (1.e-10 or 0.00000001% - this is less than 1 second if the result is a epoch now) .
This helps prevent fuzz test failing when the result number is relatively big, ex:
```
query_fuzz_test.go:397: case 0 results mismatch.
range query: avg(exp({__name__="test_series_2"}))
res1: {} =>
485165195.4097903 @[1731610569.504]
1318815734.4832146 @[1731610599.504]
3584912846.131592 @[1731610629.504]
9744803446.248903 @[1731610659.504]
26489122129.84347 @[1731610689.504]
72004899337.38588 @[1731610719.504]
195729609428.83878 @[1731610749.504]
532048240601.79865 @[1731610779.504] …
```
=> Relaxing float comparison on fuzz testing

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/distributor_mixed_ha_samples_test.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/validation/limits.go
Added new implementation that makes the distributor accept multiple HA pairs (cluster, replica) in the same requets/batch. This can be enabled with a new flag, **accept_mixed_ha_samples**, an will take effect only if accept_ha_samples is set to true.
This implementation check every timeseries from the request if it has both cluster and replica labels. If yes, then it checks the KV store to see if it matches with the elected replica. If not, the current timeseries is discarded (not added to the validatedTimeseries) and the rest of the batch moves on.
It also ensures that when the cluster label is missing the replica label is not removed.
Fixes #6256
**Checklist**
=> Distributor accept multiple HA Tracker pairs in the same request

go.mod, go.sum, pkg/chunk/cache/memcached_client.go, pkg/compactor/compactor.go, pkg/querier/blocks_store_balanced_set.go, pkg/ring/bench/ring_memberlist_test.go, pkg/ring/kv/memberlist/dnsprovider.go, pkg/ring/kv/memberlist/memberlist_client.go, pkg/ring/kv/memberlist/memberlist_client_test.go, vendor/github.com/thanos-io/thanos/pkg/cache/groupcache.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/clientconfig/http.go, vendor/github.com/thanos-io/thanos/pkg/compact/compact.go, vendor/github.com/thanos-io/thanos/pkg/discovery/dns/grpc.go, vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go, vendor/github.com/thanos-io/thanos/pkg/discovery/memcache/provider.go, vendor/github.com/thanos-io/thanos/pkg/extpromql/parser.go, vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go, vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/modules.txt
Upgrade Thanos version to https://github.com/thanos-io/thanos/pull/7915 as it is an important bug fix for store gateway.
Relevant changes to us:
- https://github.com/thanos-io/thanos/pull/7915
- https://github.com/thanos-io/thanos/pull/7887
- https://github.com/thanos-io/thanos/pull/7886
**Checklist**
=> Upgrade thanos version to fix store gateway buf reuse issue

GOVERNANCE.md
Calling a vote to add the "Triage role" for the cortex project.
I think we have many new contributors that can start helping the project more on the triage role as a path to become maintainer in the future.
Similar to the triage role in thanos: https://thanos.io/tip/thanos/maintainers.md/#triage
As per governance, this needs 2/3 majority vote from active maintainers to be approved.
**Checklist**
=> Vote to add triage role on Cortex

GOVERNANCE.md, MAINTAINERS, MAINTAINERS.md, tools/website/web-pre.sh
Adding the list of maintainers on the governance page on cortex website.
Triagers will also be listed on the cortex governance page.
**Checklist**
=> Adding list of Maintainers on the governance page

docs/guides/ha-pair-handling.md
This PR fixes typo in ha pair docs: https://cortexmetrics.io/docs/guides/ha-pair-handling/ (Promethei -> Prometheus)
**Checklist**
=> Fix typo in ha pair docs

build-image/Dockerfile
We now need `envsubst` command to build the website assets:
See:
**Checklist**
=> Install get test on the build image

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, go.mod, go.sum, integration/query_fuzz_test.go, pkg/cortex/modules.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/tripperware/merge.go, pkg/querier/tripperware/merge_test.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go, vendor/github.com/cortexproject/promqlsmith/opts.go, vendor/github.com/cortexproject/promqlsmith/promqlsmith.go, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/modules.txt
This PR adds an experimental flag `querier.enable-promql-experimental-functions ` to enable experimental promQL functions to be used.
This PR tests experimental promQL functions except `limitk` and `limit_ratio`. These are the sampling aggregator returns subnet of the input samples. So, we should devise another test to verify the compatibility between Cortex and Prometheus.   
Fixes #6307 
**Checklist**
=> Support experimental promql functions

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/storage/tsdb/expanded_postings_cache.go, pkg/storage/tsdb/expanded_postings_cache_test.go
For cortex deployments with huge number of tenants, creating a 8mb seed slice per tenant can be wasteful. 
This PR is creating 1 seed slice per ingester (16mb now) and reusing it across all the tenants.
**Checklist**
=> Using a single seed array for expanded postings cache on ingesters

pkg/ingester/ingester_test.go, pkg/storage/tsdb/expanded_postings_cache.go
We are using the wrong index on the stripped lock, causing data race.
This fix the issue by using the correct index on the stripped lock.
First commit has the test showing the race (failing): https://github.com/cortexproject/cortex/actions/runs/11981212549/job/33407007009
```
==================
Read at 0x00c004dc8010 by goroutine 18675:
github.com/cortexproject/cortex/pkg/storage/tsdb.(*seedByHash).incrementSeed()
/__w/cortex/cortex/pkg/storage/tsdb/expanded_postings_cache.go:317 +0x208
github.com/cortexproject/cortex/pkg/storage/tsdb.(*blocksPostingsForMatchersCache).ExpireSeries()
/__w/cortex/cortex/pkg/storage/tsdb/expanded_postings_cache.go:1[61](https://github.com/cortexproject/cortex/actions/runs/11981212549/job/33407007009#step:6:62) +0x157 …
```
=> Fix data race on expanded postings Cache

pkg/querier/blocks_store_queryable.go
This PR improves consistency check warn log.
The current `err` in the log is always `nil` because not `nil` error has already been returned at https://github.com/cortexproject/cortex/blob/master/pkg/querier/blocks_store_queryable.go#L562.
**Checklist**
=> Improve consistency check warn log

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
This PR adds two ingester metrics `cortex_ingester_ingested_native_histograms_total` and `cortex_ingester_ingested_native_histograms_failures_total` to track ingesting native histogram.
**Checklist**
=> Add metrics to track ingesting native histograms

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Adds a new limit to distributor for the number of inflight ingester client requests and expose new gauge metric to measure the number of inflight requests.
Fixes #6358
**Checklist**
=> Add distributor inflight client request limit

pkg/querier/querier_test.go
This PR fixes flaky `querier_test.go` due to race condition from https://github.com/cortexproject/cortex/blob/master/pkg/querier/querier.go#L211.
Failed logs:
```
Write at 0x00000396adb7 by goroutine 2291:
github.com/cortexproject/cortex/pkg/querier.New()
/__w/cortex/cortex/pkg/querier/querier.go:211 +0x766
github.com/cortexproject/cortex/pkg/querier.TestQuerier_ValidateQueryTimeRange_MaxQueryLength_Series()
/__w/cortex/cortex/pkg/querier/querier_test.go:913 +0x60d
testing.tRunner()
/usr/local/go/src/testing/testing.go:1690 +0x226
testing.(*T).Run.gowrap1()
/usr/local/go/src/testing/testing.go:1743 +0x44
Previous write at 0x00000396adb7 by goroutine 2[65](https://github.com/cortexproject/cortex/actions/runs/12042319929/job/33575766176?pr=6330#step:6:66)0: …
```
=> Fix flaky querier unit test

docs/guides/ha-pair-handling.md
This PR adds docs for #6278 to improve the usability of this feature.
**Checklist**
=> Add docs for accept multiple ha pairs

CHANGELOG.md, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Exposes a new native histogram metric `cortex_label_size_bytes` to allow tenants to monitor how close they are to hitting the label size limit.
Fixes #6372
**Checklist**
=> Add label size bytes native histogram

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ring/kv/consul/client.go, pkg/ring/kv/consul/client_test.go
This PR adds a tls config to consul like other kv stores (etcd, memberlist).
**Checklist**
=> Add tls config to consul

integration/native_histogram_test.go, pkg/querier/codec/protobuf_codec.go, pkg/querier/codec/protobuf_codec_test.go, pkg/querier/tripperware/instantquery/instant_query_test.go
The current implementation of querier protobuf codec does not serialize prometheus native histograms. This PR allows querier protobuf codec to handle responses with native histograms.
**Checklist**
=> Add support for native histograms in querier protobuf codec

pkg/frontend/transport/handler.go
Add logging for query requests in QFE before query execution. Query requests are logged only if `query_stats_enabled` is enabled. This is useful for debugging queries that failed to return to QFE. 
**Checklist**
=> Log query requests in QFE before query execution

pkg/frontend/transport/handler.go
Follow up of https://github.com/cortexproject/cortex/pull/6390.
We want to also log Grafana headers such as dashboard ID and panel ID here as well.
**Checklist**
=> log grafana headers along with query request before query execution

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/cortex/runtime_config.go, pkg/cortex/runtime_config_test.go, pkg/ruler/api_test.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/external_labels.go, pkg/ruler/external_labels_test.go, pkg/ruler/manager.go, pkg/ruler/manager_test.go, pkg/ruler/ruler_ring_test.go, pkg/ruler/ruler_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Add support for per-user external labels, this currently applies only to alerting rules, but we may consider adding them to remote read in the future.
**Checklist**
=> Ruler: Add support for per-user external labels

pkg/util/log/log.go
Clean up the logging code a bit before we switch to use slog.
`LevelFilter` is not needed anymore as the common package already switch to use `go-kit/log`. See the TODO comment there.
**Checklist**
=> chore: remove unnecessary level filter

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Keeps track of the number of chunks queried by the ingester.
Fixes: https://github.com/cortexproject/cortex/issues/6396
**Checklist**
=> ingester: Fix regression on usage of cortex_ingester_queried_chunks

go.mod, go.sum, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go, pkg/util/log/log.go, pkg/util/log/slog_adapter.go, pkg/util/log/slog_adapter_test.go, vendor/github.com/tjhop/slog-gokit/.goreleaser.yaml, vendor/github.com/tjhop/slog-gokit/LICENSE, vendor/github.com/tjhop/slog-gokit/Makefile, vendor/github.com/tjhop/slog-gokit/README.md, vendor/github.com/tjhop/slog-gokit/handler.go, vendor/github.com/tjhop/slog-gokit/level.go, vendor/modules.txt
This PR adds a slogAdapter converting `go-kit/log` to `slog`.
It would be good to use `slogAdapter` to upgrade the Prometheus version. We could implement features included in Prometheus v3.0.0, like OTLP metadata, OOO ingestion native histogram, UTF-8 support, and so on.
After that, we could migrate whole logs to `slog` if needed.
Fixes #6402 
**Checklist**
=> Add slogAdapter

go.mod, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/util/strings.go, vendor/github.com/hashicorp/golang-lru/v2/expirable/expirable_lru.go, vendor/modules.txt
Fix Race when the  `-ingester.labels-string-interning-enabled` experimental feature is enabled.
The race happens as tsdb calls the PostCreation outside the lock (see [this](https://github.com/prometheus/prometheus/blob/6c8163e9aa180f87576a955072d43bda9685c519/tsdb/head.go#L2034-L2042)) but after the series is already added on the `s.hashes` hash. With this, this series is already returned on the GetByHash method and so, we may race with the interning.
This change is proposing intern the strings using a LRU cache and so we can stop managing the release of the strings. The LRU ttl is set to be similar to the range blocks interval and so, we should not keep strings in the heap for more time than needed. …
=> Fix race on the string interning

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/distributor.go, pkg/alertmanager/multitenant.go, pkg/distributor/distributor.go, pkg/ring/batch.go, pkg/ring/ring_test.go, pkg/util/worker_pool.go, pkg/util/worker_pool_test.go
Implement an option to use a goroutine worker pool to handle requests from the distributor to ingesters, rather than spawning a new goroutine for each request.
This PR was inspired on: https://github.com/grpc/grpc-go/pull/3204
Looking at the distributor flame graph, we could see that lots of cpu was being used on the  `runtime.newstack` call: 
This problem increases with the RemoteWrite TPS and the number of ingesters in the cluster (as, for request and ingesters, we create a new go routine).
With this PR enabled, we could see a reduction on 20% of CPU on some cortex cluster with hundreds of ingesters.
We could not see any `runtime.newstack` on the cpu flamegraph after the option was enabled.
**Checklist**
=> Create a goroutine worker pool to send data from distributors to ingesters.

CHANGELOG.md, pkg/ingester/ingester_test.go, pkg/ingester/user_state.go
https://github.com/cortexproject/cortex/pull/5950 introduced a new limit Active Series "Per LabelSet."
Running cortex with the `-race` flag, we found that there is possible race condition on the `labelSetCounter`.
The `TestPushRace` test was update to demonstrate the issue.
https://github.com/cortexproject/cortex/actions/runs/12246709889/job/34163143753
**Checklist**
=> Fix race on the LabelSet Counter

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/exthttp/hedging.go, vendor/github.com/thanos-io/thanos/pkg/store/storepb/inprocess.go, vendor/modules.txt
This PR updates the Thanos version to d0d93dbf3efc.
Fix:
- https://github.com/thanos-io/thanos/pull/7962
**Checklist**
=> Update thanos version to d0d93dbf3efc

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/modules.txt
Upgrade Thanos to latest main https://github.com/thanos-io/thanos/commit/51c7dcd8c27814fd4f3d64e5d6294cdd1772ccb5.
Changes include:
- https://github.com/thanos-io/thanos/pull/7961
**Checklist**
=> Update thanos to latest main to pull lazy posting improvements

docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/util/grpcclient/health_check.go
Adds `healthcheck` prefix on the health check CLI config.
The config before was, for instance, `-querier.store-gateway-client.timeout` which is very confusing.
This feature is marked as experimental and its not being released (even as experimental) yet, so we should be ok to just rename it.
**Checklist**
- [NA ] Documentation added
- [NA ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Changing client healthcheck config cli argument

integration/query_fuzz_test.go
This PR improves the query fuzz test to skip non-deterministic queries.
It can prevent test fail due to the non-deterministic queries like `bottomk by (job) (pi(), days_in_month(-{__name__="test_series_a"} offset 1m17s))`.
Change log
-  We decide to change comparer for `bottomk` and `topk`.
Fixes #6323 
**Checklist**
=> Change query fuzz test for bottomk, topk

.github/workflows/test-build-deploy.yml, Makefile, pkg/ingester/ingester.go, pkg/ingester/ingester_no_race_test.go, pkg/ingester/ingester_test.go
#6296 introduced an experimental flag to cache expanded postings, including postings from the head blocks. In that PR, the TSDB PostCreation hook is used to "expire" cache keys when new metrics are added for a specific metric name.
The issue happens under scenarios of high concurrency, where a key may be expired before the new series are available for querying, leading to cached results that exclude the new series.
The root cause is that the PostCreation hook is invoked after the series is created but before it is added to memPostings:
Relevant code:
* Hook Invocation: https://github.com/prometheus/prometheus/blob/e1bfdd22571d874e1f9154d1a35ce3a8569ded36/tsdb/head.go#L2042
* New Series added to the memPostings: …
=> Expanded Postings Cache can cache results without the nearly created series under high load.

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go, pkg/querier/stats/stats.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/util.go
This PR adds # of series in query response to the query-stat log.
Fixes #6421 
**Checklist**
=> Add # of series in query response to query stat log

pkg/frontend/v1/frontend.go, pkg/frontend/v1/frontend_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
`cortex_request_queue_requests_total` is a high cardinality metric with `user` as its label and we didn't clean it up properly for inactive users.
**Checklist**
=> Cleanup dangling request queue metrics

pkg/ingester/ingester_test.go, pkg/querier/batch/batch.go, pkg/querier/batch/batch_test.go, pkg/querier/batch/merge.go, pkg/querier/batch/merge_test.go, pkg/querier/chunk_store_queryable.go, pkg/querier/distributor_queryable.go, pkg/querier/querier.go, pkg/querier/querier_test.go
Reusing Batch iterators to optimize memory allocation on queriers.
Micro bench results: 
```
goos: darwin
goarch: arm64
pkg: github.com/cortexproject/cortex/pkg/querier/batch
cpu: Apple M1 Pro
BenchmarkMergeIterator
BenchmarkMergeIterator/reuse-true
BenchmarkMergeIterator/reuse-true-10         	   13018	     84397 ns/op	    7672 B/op	      46 allocs/op
BenchmarkMergeIterator/reuse-false
BenchmarkMergeIterator/reuse-false-10        	   14043	     86693 ns/op	   16680 B/op	      51 allocs/op
```
**Checklist**
=> Reusing Batch Iterators

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester_test.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/user_state.go, pkg/ingester/user_state_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
We added per labelset limits in Per LabelSet, which allows users to define `subtenants` within a user by defining labelsets and we can apply limits such as active series to throttle the usage of each subtenant.
There is a scenario where `team` label is used to define subtenants for a user. However, there might be a lot of teams and it is not easy to set limits for every team explicitly. Instead, users can define labelsets limits for some of the large teams and use put rest of teams using a catch all limit. This is called the default partition, which means it matches series that doesn't match any of the existing labelset limits.
Default partition doesn't have any label defined. In the example below, the second limit is the default partition and it should match all …
=> Add default partition when no matching labelset liimits

pkg/ingester/ingester.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
The cortex_ingester_inflight_push_requests metric currently monitors the inflightPushRequests atomic integer directly.
This approach can be misleading, as the value fluctuates significantly and only represents the exact value at the time of scraping.
This PR modifies the metric to report the maximum number of concurrent requests observed within each one-minute interval.
I think is fine changing this metric (instead of creating a new one) as the intent was always the same.
**Checklist**
=> Enhance `cortex_ingester_inflight_push_requests`  metric

docs/guides/tracing.md
Fixes the markdown link for other otel collectors in the tracing guide.
Fixes #
**Checklist**
=> docs: fix markdown link for other otel collectors

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
Follow up of #6437
**Checklist**
=> Update `cortex_ingester_inflight_push_requests` metric description

pkg/util/push/otlp_test.go
This PR adds a benchmark for the OTLP write handler.
The result is as follows:
```
BenchmarkOTLPWriteHandler
BenchmarkOTLPWriteHandler/json_with_no_compression
BenchmarkOTLPWriteHandler/json_with_no_compression-10         	   57388	     19514 ns/op	   21898 B/op	     355 allocs/op
BenchmarkOTLPWriteHandler/json_with_gzip
BenchmarkOTLPWriteHandler/json_with_gzip-10                   	   36260	     33121 ns/op	   68106 B/op	     365 allocs/op
BenchmarkOTLPWriteHandler/proto_with_no_compression
BenchmarkOTLPWriteHandler/proto_with_no_compression-10        	   77604	     15191 ns/op	   19700 B/op	     263 allocs/op
BenchmarkOTLPWriteHandler/proto_with_gzip
BenchmarkOTLPWriteHandler/proto_with_gzip-10                  	   49032	     24456 ns/op	   64703 B/op	     270 allocs/op
PASS
```
**Which …
=> Add OTLP write handler benchmark

docs/guides/open-telemetry-collector.md
This PR adds guide docs for the open-telemetry collector so that the users can integrate it with the Cortex more easily.
Fixes #6428 
**Checklist**
=> Add docs for open telemetry collector

CHANGELOG.md, pkg/api/handlers.go, pkg/querier/codec/instrumented_codec.go, pkg/querier/codec/protobuf_codec_test.go
We already have a similar metric `cortex_querier_response_message_bytes_bucket` but this metric shows the response size after the compression (gzip).
This new metric tracks the size of the request before the compression. This can be useful as the responses are decompressed on QF and it can cause OOM errors.
In a future PR we may wanna create an option to limit the size of the responses from Queriers, so we protect QF from OOM.
**Checklist**
=> Create new `cortex_querier_codec_response_size` histogram to track the size of the encoded Query responses

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/metrics.go, pkg/distributor/metrics_test.go, pkg/util/active_user.go, pkg/util/active_user_test.go
With limits per label set change, we have visibility of usage of each label set in Ingester.
This PR adds new `cortex_distributor_received_samples_per_labelset_total` in distributor so that we can get ingestion rate per label set.
**Checklist**
=> Add distributor per labelset received samples metric

CHANGELOG.md, pkg/querier/tripperware/queryrange/split_by_interval.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go
- Fixes @ modifier for sub query
- When sub queries are split by QFE, currently the @ modifier is not applied. This causes wrong results as the @ modifier will be applied on querier.
**Checklist**
=> QFE: Fix @ modifier for subquery

pkg/storage/tsdb/expanded_postings_cache.go, pkg/storage/tsdb/expanded_postings_cache_test.go
Small fix to avoid over-allocating the build when creating the cache key.
Before this change we were adding the blocks and seed size for every matcher while we only really use those values once per key.
**Checklist**
=> Avoid over allocating strings.Builder when creating cache key

CHANGELOG.md, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_store_metrics_test.go
Added `cortex_bucket_store_indexheader_load_duration_seconds` and `cortex_bucket_store_indexheader_download_duration_seconds` metrics for time of downloading and loading index header files.
We already have `cortex_bucket_store_block_load_duration_seconds` for total time loading an individual block. But these 2 metrics expose more information of the internal steps of loading blocks.
**Checklist**
=> expose indexheader download and load duration histograms

pkg/ingester/ingester_test.go, pkg/storage/tsdb/expanded_postings_cache.go, pkg/storage/tsdb/expanded_postings_cache_test.go
Before this PR, the cache miss due `expired` as counted in the eviction metric, but the cache entry was not really evicted at that point, but rather replaced. This new metric will help to understand if increasing the "ttl" would help the cache hit ratio or not.
**Checklist**
=> Create `cortex_ingester_expanded_postings_cache_miss` metric

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/querier/tenantfederation/merge_queryable.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/querier/tenantfederation/tenant_federation.go
This PR adds a `-tenant-federation.max-concurrent` flags to make the number of workers processing federated query configurable. and add a `cortex_querier_federated_tenants_per_query` histogram to track the number of tenants per query.
**Checklist**
=> Make the number of workers processing federated query configurable

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Currently, the `MetricsForLabelMatchersStream` accumulates all result series in memory before starts streaming.
The PR changes to stream series as soon as the batch size is reached.
**Checklist**
=> Improve streaming on MetricsForLabelMatchersStream method

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Use slice pooling to populate the query stream response.
Under very high query load (lots of rules), the slice created when returning the query response is a big part of the alloc memory causing more frequent GC.
This PR is proposing to reuse those slices in order to safe GC CPU cycles.
Benchmark:
```
goos: darwin
goarch: amd64
pkg: github.com/cortexproject/cortex/pkg/ingester
cpu: VirtualApple @ 2.50GHz
│   /tmp/old   │              /tmp/new               │
│    sec/op    │    sec/op     vs base               │
Ingester_QueryStream_Chunks/samplesCount=10;_seriesCount=10-10    20.74µ ± 11%   20.56µ ± 14%        ~ (p=1.000 n=6)
Ingester_QueryStream_Chunks/samplesCount=10;_seriesCount=50-10    92.38µ ± 11%   84.27µ ± 17%        ~ (p=0.132 n=6) …
```
=> Use slice pooling to populate the query stream response

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, go.mod, integration/ruler_test.go, pkg/querier/codec/protobuf_codec.go, pkg/querier/codec/protobuf_codec_test.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_test.go, pkg/querier/tripperware/query.go, pkg/querier/tripperware/queryrange/marshaling_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_test.go, pkg/querier/tripperware/queryrange/split_by_interval_test.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go, pkg/ruler/frontend_client.go, pkg/ruler/frontend_client_pool.go, pkg/ruler/frontend_client_test.go, pkg/ruler/frontend_decoder.go, pkg/ruler/frontend_decoder_test.go, pkg/ruler/ruler.go
In #6151, we can retrieve query results from Query frontends when the rules are evaluated. The limitation was, since we only support `json` format, we cannot retrieve query results including the `native histogram`.
To address this concern, this PR adds `-ruler.query-response-format` flag, which specifies which format to use when retrieving query results from the Query frontend. The supported values are `protobuf` and `json`, so we can retrieve proto format query results when we set the value to `protobuf`.
**Checklist**
=> Support ruler to retrieve proto format query response

integration/query_fuzz_test.go
- Fixes flakiness in fuzz tests for count_values func.
- `count_values` returns a float in the metric which is not always accurate.
```
[
{
"metric": { "job": "prometheus", "value": "0" },
"value": [1734628158, "5"]
},
{
"metric": { "job": "prometheus", "value": "16254.5" },
"value": [1734628158, "9"]
},
{
"metric": { "job": "prometheus", "value": "17551.083333333336" },
"value": [1734628158, "1"]
}
]
```
- Example of one such failure: https://github.com/cortexproject/cortex/actions/runs/12586943624/job/35081958645
**Checklist**
=> Fix flaky fuzz tests with count_values

docs/guides/rule-evaluations-via-query-frontend.md
Add docs on configuring Ruler to evaluate rules via Query Frontend and the pros and cons of this feature.
Fixes #6198 
**Checklist**
=> docs:Add support rule evaluation via query frontend docs

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/redis_client_config.go
Fixes  #[6459](https://github.com/cortexproject/cortex/issues/6459)
```
cortex/cmd/cortex$ go run main.go -help | grep redis | grep tls
-blocks-storage.bucket-store.chunks-cache.redis.tls-ca-path string
-blocks-storage.bucket-store.chunks-cache.redis.tls-cert-path string
-blocks-storage.bucket-store.chunks-cache.redis.tls-enabled
Whether to enable tls for redis connection.
-blocks-storage.bucket-store.chunks-cache.redis.tls-insecure-skip-verify
-blocks-storage.bucket-store.chunks-cache.redis.tls-key-path string
-blocks-storage.bucket-store.chunks-cache.redis.tls-server-name string
-blocks-storage.bucket-store.index-cache.redis.tls-ca-path string
-blocks-storage.bucket-store.index-cache.redis.tls-cert-path string
-blocks-storage.bucket-store.index-cache.redis.tls-enabled
Whether to enable …
```
=> remove multiple dots in redis flags

pkg/ring/kv/etcd/mock_test.go
Copied from https://github.com/grafana/dskit/pull/336
Fixes a race condition during setup for Client.Watch tests where a conditional variable broadcast was missed by the caller waiting on the conditional variable.
Verified by running the tests many times with a timeout:
```
go test -timeout=10s -count=10000 -run=TestMockKV_Watch ./pkg/ring/kv/etcd/
```
Fixes:
- https://github.com/cortexproject/cortex/issues/6478
- https://github.com/cortexproject/cortex/issues/5564
=> kv/etcd: Fix race condition within unit test for Watch method

CHANGELOG.md, pkg/cortex/modules.go, pkg/querier/tenantfederation/exemplar_merge_queryable.go, pkg/querier/tenantfederation/exemplar_merge_queryable_test.go
Currently, the tenant federation only supports federated queries on series select, label values, and label names.
So, if users use this feature and want to query exemplars for multiple tenants, they should query one by one.
To address this situation, this PR adds an exemplar federated query.
**Checklist**
=> Support exemplar federated query

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/query_fuzz_test.go, pkg/distributor/distributor_test.go, pkg/ingester/client/compat.go, pkg/ingester/client/compat_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/lifecycle_test.go, pkg/ingester/metrics.go, pkg/querier/remote_read.go
Implement matchers cache on ingesters.
The cache can be configured using the new `matchers_cache_max_items` config.
Supersedes https://github.com/cortexproject/cortex/pull/6382
**Checklist**
=> Implement  matchers cache on Ingester

pkg/ha/ha_tracker.go, pkg/ha/ha_tracker_test.go
The main purpose of this pr is to add a goroutine to update tenant HA replica groups to metrics periodically.
Fixes #6397
**Checklist**
=> Added UserReplicaGroupMetrics

pkg/storage/bucket/azure/bucket_client.go, pkg/storage/bucket/gcs/bucket_client.go, pkg/storage/bucket/swift/bucket_client.go
This PR refactors bucket client init code to pass config directly to the Thanos instead of serializing it.
**Checklist**
=> refactor bucket client to pass config directly

CHANGELOG.md, integration/ruler_test.go, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go, pkg/querier/tripperware/roundtrip.go
This PR adds a `source` label to query stat metrics.
When the user enables `-ruler.frontend-address`, the query stat metrics get changed whenever the ruler evaluates the rules. In other words, the query stat metrics are influenced by `ruler` and `other source` even though the user wants to track the metrics only by `other source`.
This PR attaches the `source` label to address this situation. 
**Checklist**
=> Add source label to query stats metrics

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/storage/tsdb/config.go, pkg/storage/tsdb/expanded_postings_cache.go
Create a background routine to purge expired items from the postings cache.
Before this change, items can linger indefinitely in the cache if no new items were aded.
**Checklist**
=> Purge expired postings cache items due inactivity

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/cacheutil/async_op.go, vendor/modules.txt
* Update thanos to `4ba0ba403896` which includes a fix to the cacheutil package
Fixes #6480 
**Checklist**
=> Update thanos to 4ba0ba403896

pkg/util/concurrency/runner.go
This PR changes to calculate # of go-routines only once on the `runner`.
**Checklist**
=> calculate # of concurrency only once at the runner

pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/compactor/partitioned_group_info.go
Added extra logic in block cleaner to handle partitioning compaction related logic. Cleaner would delete compacted blocks from partitioning compaction because partitioning compaction will not delete any parent blocks on compaction complete since those parent blocks would be used to compact other partition from the same time range. Cleaner would use partition group info file along with partition visit marker to determine if parent blocks can be deleted or not. Cleaner also would delete partition group info file and partition visit marker accordingly.
**Checklist**
=> Add cleaner logic to clean partition compaction blocks and related files

go.mod, go.sum, pkg/storegateway/bucket_stores.go, vendor/github.com/thanos-io/thanos/pkg/discovery/dns/grpc.go, vendor/github.com/thanos-io/thanos/pkg/errutil/multierror.go, vendor/github.com/thanos-io/thanos/pkg/extkingpin/flags.go, vendor/github.com/thanos-io/thanos/pkg/extkingpin/path_content_reloader.go, vendor/github.com/thanos-io/thanos/pkg/query/endpointset.go, vendor/github.com/thanos-io/thanos/pkg/store/bucket.go, vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go, vendor/modules.txt
Update Thanos version to latest main. No user facing changes.
Mainly to get https://github.com/thanos-io/thanos/pull/8049 but we still leave the value hardcoded for now.
**Checklist**
=> Update thanos version to main

pkg/ingester/ingester.go
https://github.com/cortexproject/cortex/pull/6502 added a background check to expire the expandedPonstings cache.
This new code can have a race that can cause panic.
This PR is fixing this possible race condition. 
**Checklist**
=> Fix race that can cause nil reference when using expanded postings

CHANGELOG.md, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go
This PR adds more `op` label values to the `cortex_query_frontend_queries_total` metric.
The added label values are: `remote_read`, `label_names`, `label_values`, `metadata`, and `query_exemplars`.
**Checklist**
=> Add more op label values to cortex_query_frontend_queries_total metric

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go
=> Allow use of non-dualstack endpoints for S3 blocks storage

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/util/grpcclient/grpcclient.go
Make gRPC client connection timeout configurable. By default the value is 20s, which means if a target is unreachable like during a deployment, client side needs to wait for 20s to retry. This PR changes the connection timeout to 5s.
**Checklist**
=> Expose grpc client connect timeout config and default to 5s

integration/integration_memberlist_single_binary_test.go, pkg/compactor/background_chunks_series_set.go, pkg/compactor/blocks_cleaner.go, pkg/compactor/compactor.go, pkg/compactor/compactor_metrics.go, pkg/compactor/compactor_metrics_test.go, pkg/compactor/compactor_paritioning_test.go, pkg/compactor/compactor_test.go, pkg/compactor/partition_compaction_complete_checker.go, pkg/compactor/sharded_block_populator.go, pkg/compactor/sharded_compaction_lifecycle_callback.go, pkg/compactor/sharded_compaction_lifecycle_callback_test.go, pkg/compactor/sharded_posting.go, pkg/compactor/sharded_posting_test.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/copy.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/port.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/rand.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/sysprocattr.go, vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/sysprocattr_linux.go, vendor/modules.txt
Implement partitioning compaction related lifecycle functions to make partitioning compaction end to end working.
- `PartitionCompactionBlockDeletableChecker` makes sure no parent blocks got deleted after each compaction. Cleaner would handle parent blocks clean up for partitioning compaction.
- `ShardedBlockPopulator` would use `ShardedPosting` to including particular series in the result block.
- `ShardedCompactionLifecycleCallback`is used to emit partitioning compaction metrics at beginning and end of compaction. It also initialize `ShardedBlockPopulator` for each compaction.
**Checklist**
=> Hook up partition compaction end to end implementation

pkg/ingester/ingester_test.go
Adding a test case for https://github.com/cortexproject/cortex/pull/6518
```
=== RUN   TestIngesterDeletionRace
[signal SIGSEGV: segmentation violation code=0x2 addr=0xf0 pc=0x1016cba4c]
goroutine 177 [running]:
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).expirePostingsCache(0x14000d4d908, {0x102160e90, 0x1400004d9f0})
/Users/approtas/workspace/cortex/pkg/ingester/ingester.go:2814 +0x3c
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).starting.NewTimerService.func2({0x102160e90, 0x1400004d9f0})
/Users/approtas/workspace/cortex/pkg/util/services/services.go:33 +0xd0
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0x14000ae41e0) …
```
=> Test for nil on expire expanded postings

pkg/querier/worker/frontend_processor.go, pkg/querier/worker/scheduler_processor.go
The PR adds a log when a querier starts running a request. We currently log when a querier finishes a request but we do not log when it picks one up. If the log for finishing the request is missing, it is hard to identify if querier successfully received the request or not.
**Checklist**
=> log when a request starts running in querier

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go
Deprecate the `-blocks-storage.tsdb.wal-compression-enabled` flag.
Fixes #6238 
**Checklist**
=> Deprecate -blocks-storage.tsdb.wal-compression-enabled flag

pkg/ingester/ingester_test.go
Attempt to fix 
```
==================
Write at 0x0000048e5c08 by goroutine 51695:
github.com/cortexproject/cortex/pkg/ingester.TestInstanceLimitsUnmarshal()
/__w/cortex/cortex/pkg/ingester/instance_limits_test.go:11 +0xc8
testing.tRunner()
/usr/local/go/src/testing/testing.go:1690 +0x226
testing.(*T).Run.gowrap1()
/usr/local/go/src/testing/testing.go:1743 +0x44
Previous read at 0x0000048e5c08 by goroutine 51502:
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).getInstanceLimits()
/__w/cortex/cortex/pkg/ingester/ingester.go:3171 +0xdc
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).updateLoop()
/__w/cortex/cortex/pkg/ingester/ingester.go:927 +0x5a
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).updateLoop-fm() …
```
=> Fix TestIngester_UpdateLabelSetMetrics test

pkg/compactor/partition_compaction_grouper.go, pkg/compactor/partition_compaction_grouper_test.go
`blocksGroupWithPartition` extends `blocksGroup`. However, when calling functions inside `blocksGroup` from a `blocksGroupWithPartition` instance, those attributes defined inside `blocksGroup` were not set properly when initialize `blocksGroupWithPartition`. This caused unexpected value returned from `blocksGroup` functions.
The fix is removing duplicate attributes from `blocksGroupWithPartition` that already defined inside `blocksGroup`. When initializing `blocksGroupWithPartition` instance, those attributes in `blocksGroup` should be explicitly provided.
**Checklist**
=> Fixed blocksGroupWithPartition unable to reuse functions from blocksGroup

pkg/cortex/cortex.go
This PR removes a `TransferChunks` gRPC method because the chunk storage has been deprecated since v1.10.0.
**Checklist**
=> Remove TransferChunks gRPC method

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/cortex/modules.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/query.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/lazyquery/lazyquery.go, pkg/querier/partialdata/partia_data.go, pkg/querier/partialdata/partial_data_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/testutils.go, pkg/querier/tripperware/limits.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/results_cache_test.go, pkg/querier/tripperware/test_shard_by_query_utils.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/replication_set_tracker.go, pkg/ring/replication_set_tracker_test.go, pkg/ruler/ruler_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This PR introduces new limits (tenant config) of `query_partial_data` and `rules_partial_data`, which allows tenants to receive 2xx with a warning message when querying ingesters fail in zones greater than max unavailable zones, but less than all available zones.
For example, in the following scenario,
- Total zone count: 3
- Max unavailable zone: 1
- Zones where ingesters are failing: 2
Current behavior always returns 5xx:
But with this feature enabled, customers will receive data with warning message "Query result may contain partial data".
This is useful for cortex setup that replicates ingested data across different zones. In this case, even if ingesters from different zones go down, there is a high probability of full data available in ingesters from the …
=> Query Partial Data

docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ring/kv/dynamodb/client.go, pkg/ring/kv/dynamodb/client_test.go, pkg/ring/kv/dynamodb/dynamodb.go
This PR tries to fix https://github.com/cortexproject/cortex/issues/6211 using a different approach of https://github.com/cortexproject/cortex/pull/6212.
https://github.com/cortexproject/cortex/pull/6212 added context timeout to `heartbeat` but there are more places missing context timeout.
This PR instead tries to enforce context timeout on DDB KV so that request to DDB KV doesn't hang forever.
**Checklist**
=> Add timeout for dynamodb ring kv

integration/query_fuzz_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/storage/tsdb/expanded_postings_cache.go
See: https://github.com/cortexproject/cortex/issues/6556
This PR includes:
* Added unit test to catch the issue
* Improve fuzz test to add GetSeries call and run queries at a "future" timestamp
* Increase the runs from 100 to 300 on the fuzz test (even though 100 was pretty consistent to catch the issue)
* Bypass caching logic if the query is "in the future"
Additionally, we improved the prom to include all the matchers types: https://github.com/cortexproject/promqlsmith/pull/142
Fixes https://github.com/cortexproject/cortex/issues/6556
**Checklist**
=> Fix: expanded postings can cache wrong data when queries are issued "in the future"

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
This PR adds a `too_many_tenants` reason label value to the `cortex_rejected_queries_total` metric to track the rejected query count due to the # of tenant limits.
**Checklist**
=> Add a too_many_tenants label to cortex_rejected_queries_total metric

CHANGELOG.md, pkg/distributor/distributor.go, pkg/querier/blocks_store_queryable.go
This PR is
1. Apply bytes limiter to `Distributor.LabelNames` and `Distributor.LabelValuesForLabelNames` functions, and
2. Fix a bug in `Distributor.MetricsForLabelMatchersStream` where bytes limiter was overwriting the error from the stream response
N/A
**Checklist**
=> Apply bytes limiter to LabelNames and LabelValuesForLabelNames

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Im proposing to return an error on the `getTSDB` function when the userDB is not found.
Everytime we invoke this function on the codebase we need to check if the return is nil but is very easy to forget to do so and cause problem like: https://github.com/cortexproject/cortex/pull/6518 https://github.com/cortexproject/cortex/pull/6521
Ex:
https://github.com/cortexproject/cortex/blob/4b32f29e3d08d729f96f153f347c4d49a4ee6a58/pkg/ingester/ingester.go#L991-L995
I think returning an error in such case will force us to always think about this case and prevent such scenarios in the future.
**Checklist**
=> Return error on the getTSDB function when user is not found.

CHANGELOG.md, pkg/ingester/user_state.go
This PR fixes a race condition of the labelset counter.
Fixes #6572 
**Checklist**
=> Fix labelset race condition

pkg/ruler/api_test.go
These tests were flaky: sometimes they get evaluated before the test
issues the GET request, sometimes they do not.
The reproducers are:
```
go test -count=1000 -run TestRuler_rules_limit ./pkg/ruler/
go test -count=1000 -run TestRuler_rules ./pkg/ruler/
go test -count=1000 -run TestRuler_rules_special_characters ./pkg/ruler/
```
This fixes the flakiness by removing evaluation-related fields from the response before comparing.
Fixes #6546
**Checklist**
=> Flaky rules test fix

pkg/compactor/blocks_cleaner_test.go, pkg/compactor/partitioned_group_info.go
Cleaner supposed to mark all blocks from completed partition group for deletion. However, it will mark blocks with no-compact marker for deletion as well. This would result in no-compact blocks got deleted. This PR is fixing this issue by adding extra check to make sure no-compact blocks will not be marked for deletion during this process.
**Checklist**
=> Cleaner should not put deletion marker for blocks with no-compact marker

.github/workflows/test-build-deploy.yml
Updates Ubuntu actions runners.
Fixes #6582 
**Checklist**
=> update ubuntu action runners

pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/results_cache_test.go, pkg/querier/tripperware/queryrange/split_by_interval.go
Add dynamic interval cache splitter. Follow up for dynamic query splitting https://github.com/cortexproject/cortex/pull/6458
**Checklist**
=> Add dynamic interval cache splitter

CHANGELOG.md, pkg/querier/codec/protobuf_codec.go, pkg/querier/codec/protobuf_codec_test.go
Prune buckets at the end to remove nil element to avoid panic.
Fixes #6594
**Checklist**
=> fix native histogram empty bucket marshal panic

pkg/ring/model.go
Sort ingesters when generating token lookup table in ring to fix consistency issues.
Since map iteration order is undefined, successive calls to `getTokensInfo()` can return different results when tokens are owned by multiple instances in the ring. I don't know enough about the ring to say whether that is expected to occur, but in the tests it does and this fixes that test.
See the linked issue for more details and here for a reproducible test: https://github.com/dsabsay/cortex/tree/flaky-ring-consistency-test-repro
I validated the test locally by running my reproducer (linked above) twice (failed both times), applying this patch and running the same test (passed both times). I don't think it's worth merging the reproducer as it takes 5mins to run utilizing 16 cores …
=> sort ingesters when generating token lookup table fix #6513

CHANGELOG.md, integration/query_frontend_test.go, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/results_cache_test.go
with [this](https://github.com/cortexproject/cortex/pull/6228) PR, peakSamples and processedSamples was added to query stats. They work when queries are directly queried from datasource, and doesn't apply for results_cache. 
this PR will populate those fields for query stats for responses from results cache
**Checklist**
=> retrieve peakSamples and processedSamples query stats from results_cache

pkg/ruler/ruler.go
Fixes a bug in LivenessCheck where it can result in a seg fault when ruler is initializing and the context can be nil. 
https://github.com/cortexproject/cortex/blob/7292d8dcfc04d1d92dbaf20c70995362f9ee562b/pkg/util/services/basic_service.go#L277
When the ruler is initializing, it cannot evaluate rules since it has not loaded the rules yet. Therefore, in this case, we return an error as well which allows secondary ruler to evaluate the rule group one more time
**Checklist**
=> Avoid liveness check seg-fault in 'New' state

CHANGELOG.md, docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager_client.go, pkg/querier/store_gateway_client.go, pkg/util/grpcclient/grpcclient.go
Continue work on https://github.com/cortexproject/cortex/pull/6523
Add the timeout to SG/Alertmanager by default
**Checklist**
=> Set default conn timeout of 5 sec for storeGateway and alertmanager clients

pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go
If a tenant got empty bucket index (no blocks cannot be found), not only bucket index file and status file should be removed also debug directory and partitioned-groups directory (if partitioning enabled) should be removed as well.
**Checklist**
=> Cleaner should remove debug and partitioned-groups directories if bucket store is empty for the tenant

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_test.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go, pkg/util/validation/limits.go
The prometheus alermanager [PR](https://github.com/prometheus/alertmanager/pull/3852), which included alertmanager v0.28.0, adds limits for silences.
This PR applies silence limits per tenant.
Follow up #6590
**Checklist**
=>  Add for tenant silences limit

pkg/querier/tripperware/queryrange/split_by_interval.go
Split interval function could return an error in three cases
- Query parsing error
- Query analyzer error
- Error retrieving tenant userId
Since all of these should be 4xx, the current behaviour of returning 5xx is wrong.
**Checklist**
=> Fix: split interval function should return 4xx

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
This PR adds new receiver validation for `msteamsv2` and `rocketchat` to protect the disclosure of local files like other receivers.
Follow up: #6590 
**Checklist**
=> Add receiver validation for msteamsv2 and rocketchat

CHANGELOG.md, integration/e2ecortex/client.go, integration/otlp_test.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go
This PR adds ingestion OTLP metadata.
Fixes #6247
**Checklist**
=> Support otlp metadata ingestion

go.mod, go.sum, vendor/github.com/thanos-io/promql-engine/execution/execution.go, vendor/github.com/thanos-io/promql-engine/execution/scan/subquery.go, vendor/github.com/thanos-io/promql-engine/ringbuffer/functions.go, vendor/github.com/thanos-io/promql-engine/ringbuffer/generic.go, vendor/github.com/thanos-io/promql-engine/ringbuffer/rate.go, vendor/github.com/thanos-io/promql-engine/storage/prometheus/matrix_selector.go, vendor/github.com/thanos-io/promql-engine/storage/prometheus/scanners.go, vendor/modules.txt
Upgrade thanos promql engine version to pull https://github.com/thanos-io/promql-engine/pull/519 which fixes a performance regression.
**Checklist**
=> Upgrade promql engine to pull fix for performance regression

pkg/ingester/ingester.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
See https://github.com/prometheus/prometheus/pull/14489.
`storage.NewMergeSeriesSet` can handle limit now so we can pass down limit from labels API
**Checklist**
=> Pass limit to merge serieset for labels API

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
When an idle tsdb is closing, we mark the userDB as closing (or closed) and ask to close tsdb. While the tsdb is clossing and userDb is still on the ingester list, it can happen that a query request is received by the ingester and it will fail with 
```
open querier for head range head (mint: X, maxt: Y): open querier for block range head (mint: X, maxt: Y): open chunk reader: can't read from a closed head
```
To avoid this from happening, we are adding a readLock similar to the acquireAppendLock, that will make sure no query request is inflight when closing an idle tsdb and it will return a empty response if the request is received after the tsdb is already closing
**Checklist**
=> Add check to avoid query 5xx when closing tsdb

pkg/ring/ring_test.go
Use 128 tokens instead of 10,000. Use ringDesc when generating testValues and creating a ring of ingesters.
Fixes: https://github.com/cortexproject/cortex/issues/6513
Related: https://github.com/cortexproject/cortex/pull/6535
=> Fix flaky ring consistency test

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/alertmanager/alertmanager_ring.go, pkg/alertmanager/multitenant.go
Add existent features of ring to AlertManager ring. This will avoid AlertManager to regenerate tokens on restart.
**Checklist**
=> Add tokenFile and persisit on ring features for AM ring

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/native_histogram_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This PR adds a `-ingester.enable-ooo-native-histograms` flag to enable out-of-order native histogram ingestion per tenant.
**Checklist**
=> Add ooo native histogram ingestion

build-image/Dockerfile
Updates the Dockerfile to reference go 1.24.0. Once the image is created then I will reference the new build image in the config files mentioned in https://github.com/cortexproject/cortex/blob/master/docs/contributing/how-to-update-the-build-image.md
Fixes #6625
=> update go to 1.24

CHANGELOG.md, pkg/querier/stats/stats.go, pkg/querier/stats/stats_test.go, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/scheduler_processor_test.go
This is PR fixes querier panic when marshaling `QueryResultRequest`.
Fixes #6599 
**Checklist**
=> Fix querier panic when marshaling QueryResultRequest

build-image/Dockerfile
Bumps the golangci-lint package to a higher version that supports go 1.24.0
Needed to fix the pipeline failures [here](https://github.com/cortexproject/cortex/pull/6637).
Fixes #6625
=> bump golangci-lint version

pkg/ruler/ruler_test.go
Removes an unnecessary if/else block in `ruler_test.go`
Fixes #6287 
**Checklist**
=> remove redundant if else block in `ruler_test.go`

build-image/Dockerfile
Part of #6625 
This is a version bump for the [faillint linter](url), needed to support go 1.24.
Created because I ran into [this issue](https://github.com/cortexproject/cortex/actions/runs/13794661971/job/38583192205?pr=6637) while working on [this PR](https://github.com/cortexproject/cortex/pull/6637).
**Checklist**
=> bumps faillint version to 1.15 to support go 1.24

.github/workflows/test-build-deploy.yml, Makefile, go.mod, pkg/distributor/distributor.go, pkg/frontend/transport/handler.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/limits.go, pkg/querier/tripperware/instantquery/limits_test.go, pkg/querier/tripperware/query_attribute_matcher.go, pkg/querier/tripperware/queryrange/limits.go, pkg/querier/tripperware/queryrange/limits_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/results_cache.go, pkg/querier/tripperware/queryrange/split_by_interval.go, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/shard_by.go, pkg/querier/tripperware/util.go, pkg/storegateway/limiter.go
This PR replaces all references of the older build image with the new build image that is now on go 1.24.0.
I wasn't sure if the version in `go.mod` needs to be updated from 1.23.0 to 1.24.0, hopefully a maintainer can chime in and let me know.
`master-8508125da` is the image that I found in [these logs](https://github.com/cortexproject/cortex/actions/runs/13786546194/job/38558312453), per the documentation. 
Fixes #6636
Regarding all the changes to `httpgrpc.ErrorF` calls, please see the section on vet in the [1.24 release notes](https://tip.golang.org/doc/go1.24).
=> Update workflows to use the latest image with go 1.24.0

CHANGELOG.md, pkg/ring/lifecycler.go, pkg/ring/lifecycler_test.go
When restarting ingester which are in READONLY we can cause a resharding which this PR is trying to avoid.
When a ingester is in READONLY, we extend the shard of tenant to return more than the original value. This is done to avoid errors on Push or missing data on Query.
Problem occurs when we restart ingester. The READONLY ingester will go to LEAVING which is ok for Push but it changes the tenant shard for Query. It can lead to miss calls from querier/ruler to ingesters.
**Checklist**
=> Keep readonly state when stopping lifecycler

pkg/ingester/ingester_test.go
Ingester are expected to receive labels ordered. This test is ingesting labels not ordered. Nit fixing it.
**Checklist**
=> Fix ingester test label order

docs/guides/native-histograms.md
This PR introduces docs for native histograms.
It includes:
- how to configure native histogram ingestion
- how to enable out-of-order native histogram ingestion 
Related: #6626 
**Checklist**
=> Add docs for native histogram

integration/e2e/images/images.go, integration/e2e/util.go, integration/query_fuzz_test.go
This PR adds a query fuzz test for the native histogram, It compares query result Cortex with the latest Prometheus.
Fixes #6093 
**Checklist**
=> Add native histogram query fuzz test

go.mod, pkg/compactor/sharded_block_populator.go, pkg/ring/lifecycler_test.go, pkg/storage/tsdb/multilevel_cache.go, pkg/storage/tsdb/users_scanner_test.go
The experimental functions in `golang.org/x/exp/slices` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
**Checklist**
=> Replace `golang.org/x/exp/slices` with stdlib `slices`

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, docs/guides/native-histograms.md, integration/native_histogram_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This PR makes out-of-order ingestion for native histograms automatically enabled when `-ingester.out-of-order-time-window > 0` and `-blocks-storage.tsdb.enable-native-histograms=true` as the Prometheus changed its behavior  at the https://github.com/prometheus/prometheus/pull/16207.
**Checklist**
=> Make ooo native histograms ingestion automatically enabled

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go
The alertmanager [v0.26.0](https://github.com/prometheus/alertmanager/releases/tag/v0.26.0) added maintenance metrics for nflog and silences. This PR adds these metrics to the Cortex.
Added metrics are:
- cortex_alertmanager_nflog_maintenance_total
- cortex_alertmanager_nflog_maintenance_errors_total
- cortex_alertmanager_silences_maintenance_total
- cortex_alertmanager_silences_maintenance_errors_total
**Checklist**
=> Add nflog and silences metrics

pkg/ruler/frontend_decoder.go, pkg/ruler/frontend_decoder_test.go
Ensure that the labels are in order because we are iterating over map[string]string which has a random sorting order. I think the consequence of not sorting this is that when using a frontend directly, the write requests might have unsorted labels in them.
=> ruler/decoder: ensure labels order

integration/query_fuzz_test.go
This PR fixes the flaky TestNativeHistogramFuzz test using the `compareFloats` when comparing float64 values.
**Checklist**
=> Fix flaky TestNativeHistogramFuzz

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/query.go, pkg/ring/replication_set.go, pkg/ring/replication_set_test.go, pkg/ring/replication_set_tracker.go, pkg/ring/replication_set_tracker_test.go
Query partial data (https://github.com/cortexproject/cortex/pull/6526) was introduced such that queries to ingesters return 200 even when data from ingesters can be partial.
This is an improvement on top to add metric and enhanced logging to further debug why partial data was returned to the customers.
n/a
**Checklist**
=> Add metric and enhanced logging for query partial data

go.mod, go.sum, integration/query_fuzz_test.go, vendor/github.com/cortexproject/promqlsmith/opts.go, vendor/github.com/cortexproject/promqlsmith/promqlsmith.go, vendor/github.com/cortexproject/promqlsmith/walk.go, vendor/modules.txt
Upgrade promqlsmith to https://github.com/cortexproject/promqlsmith/pull/155.
This includes:
- Built-in max depth limit so we don't have to check generated query depth on Cortex
- Better support for generating queries with vector matching. But we are not enabling it in this PR
**Checklist**
=> Upgrade promqlsmith version to latest

MAINTAINERS.md, README.md, website/config.toml, website/content/en/_index.html, website/layouts/partials/footer.html
**What this PR does**: Include OpenTelemetry in the title and other enhancements
**Checklist**
=> README: Include OpenTelemetry in the title and other enhancements

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
After https://github.com/cortexproject/cortex/pull/6470, we added another label to QFE per user metrics. This requires us to change how we clean up those metrics. Instead of `DeleteLabelValues`, we need to change to use `util.DeleteMatchingLabels` instead.
Also created a unit test to capture this regression
**Checklist**
=> fix query frontend per tenant metrics leak when cleaning up user labels

integration/query_fuzz_test.go
This PR fixes native histogram comparer. The current comparer fails when the `Count` is NaN.
**Checklist**
=> Fix NH comparer when Count is NaN

pkg/ingester/ingester.go, pkg/util/strings.go
Create `noOpInterner` in case string interning is disabled.
This prevent some go routines to be created by the LRU cache.
**Checklist**
=> Create a `noOpInterner` in case string interning is disabled

CHANGELOG.md, integration/resource_based_limiter_test.go, pkg/cortex/modules.go, pkg/cortex/modules_test.go, pkg/util/limiter/resource_based_limiter.go, pkg/util/limiter/resource_based_limiter_test.go, pkg/util/resource/monitor.go, pkg/util/resource/monitor_test.go, pkg/util/resource/scanner.go, pkg/util/resource/scanner_test.go
Resource monitor introduced from https://github.com/cortexproject/cortex/pull/6674 contained bugs that were not covered in unit tests.
This PR fixes the bugs and add unit tests to cover them.
Double checked in the dev environment that resource monitor and resource based limiter work as expected:
```
ts=2025-04-23T03:29:39.25743507Z caller=ingester.go:2222 level=warn msg="failed to accept request" err="cpu utilization limit reached (limit: 0.020, utilization: 0.028)"
```
n/a
**Checklist**
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Resource monitor: fix bugs + add tests

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
This PR changes to return status code 400(Bad Request) when the tenant resolution fail.
**Checklist**
=> Return bad request when the tenant resolving fail

pkg/cortexpb/signature.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/querier/distributor_queryable.go, pkg/querier/distributor_queryable_test.go, pkg/querier/querier_test.go, pkg/querier/series/series_set.go, pkg/querier/testutils.go
Remove complex conversions when selecting only series: `LabelAdapters` -> `model.Metric(map)` -> `labels.Labels`.
**Checklist**
=> Avoid unnecessary conversions between model.Metric and labels.Labels

pkg/ingester/ingester.go
This PR slightly optimizes the `userStats` function in the Ingester.
**Checklist**
=> Optimize ingester userStats func

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/storage/tsdb/config.go, pkg/util/validation/limits.go
Replace EnableNativeHistograms from TSDB config with EnableNativeHistogramPerUser Limit
**Checklist**
=>  Replace EnableNativeHistograms from TSDB config with PerTenant Limit

.github/ISSUE_TEMPLATE/blog_post.yml
Based on https://github.com/opensearch-project/project-website/blob/main/.github/ISSUE_TEMPLATE/blog_post.yml
**What this PR does**: Creates an issue template for planning blog posts.
**Checklist**
=> Create issue template for new blog posts

pkg/scheduler/scheduler_test.go
This PR fixes the flaky `TestSchedulerShutdown_FrontendLoop` test. It should ensure the scheduler has been terminated.
Failed test logs:
```
--- FAIL: TestSchedulerShutdown_FrontendLoop (0.00s)
scheduler_test.go:282: 
Error Trace:	/__w/cortex/cortex/pkg/scheduler/scheduler_test.go:282
Error:      	Should be true
Test:       	TestSchedulerShutdown_FrontendLoop
FAIL
```
Fixes #6724 
**Checklist**
=> Fix flaky TestSchedulerShutdown_FrontendLoop

CHANGELOG.md, docs/configuration/config-file-reference.md, integration/backward_compatibility_test.go, pkg/ingester/ingester.go, pkg/ingester/user_metrics_metadata.go, pkg/ingester/user_metrics_metadata_test.go
The PR #6681 implements a metadata API query parameter (limit, limit_per_metric, and metric). During a deployment when the querier is on an older version and the ingester is on a new version, the querier always passes 0 values for limits. If then, the ingester returns an empty response.
This PR adds a`-ingester.skip-metadata-limits` flag to make the ingester return metadata during the deployment. After the deployment, set this flag to `false` to use the metadata API with the limits.
**Checklist**
=> Add ingester.skip-metadata-limits flag

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go
This PR add out of order check for each label sets when handling push request. Ingester would fail the request if out of order label set found. If the out of order labels was caused by distributor in weird state, it would let end user to retry the push request.
NA
**Checklist**
=> Push request should fail when label set is out of order

pkg/ruler/manager.go, pkg/ruler/ruler_test.go
Previously, TestRecoverAlertsPostOutage had a data race:
```
==================
Read at 0x00c025bbfc30 by goroutine 56074:
github.com/prometheus/prometheus/rules.(*Group).Eval.func1()
/Users/danielsabsay/git/cortex/vendor/github.com/prometheus/prometheus/rules/group.go:569 +0xc8a
github.com/prometheus/prometheus/rules.(*Group).Eval()
/Users/danielsabsay/git/cortex/vendor/github.com/prometheus/prometheus/rules/group.go:666 +0x4e5
github.com/prometheus/prometheus/rules.DefaultEvalIterationFunc()
/Users/danielsabsay/git/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:81 +0x1a5
github.com/cortexproject/cortex/pkg/ruler.ruleGroupIterationFunc()
/Users/danielsabsay/git/cortex/pkg/ruler/manager.go:272 +0x4a9 …
```
=> Fix data race in TestRecoverAlertsPostOutage

CHANGELOG.md, pkg/tenant/resolver.go, pkg/tenant/resolver_test.go, pkg/tenant/tenant.go, pkg/tenant/tenant_test.go
Currently, a tenantID validation has been applied only for the MultiResolver.
This PR adds a validation of the tenantID to the single resolver. The validation rules follow the [docs](https://cortexmetrics.io/docs/guides/limitations/).
**Checklist**
=> Validate tenantID on single resolver

integration/query_fuzz_test.go
This PR fixes `TestNativeHistogramFuzz` test to cover queries that contain `count_values`.
For example, the query
```
count_values(
"value",
avg without (status_code, series) (
(
{__name__="test_series_a"} offset 2m30s
unless
{__name__="test_series_a",status_code="404"} offset 2m11s
)
)
)
```
the result is
```
status": "success",
"data": {
"resultType": "matrix",
"result": [
{
"metric": {
"value": "{count:102, sum:202.39999999999998, [-4,-2.82842712474619):11, [-2.82842712474619,-2):11, [-1.414213562373095,-1):12, [-1,-0.7071067811865475):11, [-0.001,0.001]:12, (0.7071067811865475,1]:11, (1,1.414213562373095]:12, (2,2.82842712474619]:11, (2.82842712474619,4]:11}"
},
"values": [
[
1747623681,
"1"
]
]
},
```
So, we need to cover this case in `TestNativeHistogramFuzz`.
**Which issue(s) this …
=> Fix TestNativeHistogramFuzz to cover queries that contain count_values

docs/proposals/parquet-storage.md
This PR adds a design proposal for Parquet Storage in Cortex
**Checklist**
=> Add proposal for parquet storage

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/partition_compaction_grouper.go, pkg/compactor/shuffle_sharding_grouper.go, pkg/util/validation/limits.go
Adds percentage based sharding if the tenant's `compactor.tenant-shard-size` is > 0 and < 1.
This sets the shard size to `compactor.tenant-shard-size` * `num_current_compactors`
Fixes #6738
**Checklist**
=> Add compactor percentage based sharding

CHANGELOG.md, docs/guides/limitations.md, pkg/storage/tsdb/tenant_deletion_mark.go, pkg/storage/tsdb/users_scanner.go, pkg/tenant/resolver_test.go, pkg/tenant/tenant.go, pkg/tenant/tenant_test.go, pkg/util/allowed_tenants.go
This PR adds a `__markers__` tenant ID validation logic. It was considered invalid in #5676.
**Checklist**
=> Add __markers__ tenantID validation

integration/parquet_querier_test.go, pkg/cortex/modules.go, pkg/querier/querier.go
Just renaming the new flag.
**Checklist**
=> Changing flag from `query-parquet-files`  to 'enable_parquet_queryable'

go.mod, go.sum, pkg/parquetconverter/converter.go, pkg/querier/parquet_queryable.go, pkg/querier/parquet_queryable_test.go, vendor/github.com/prometheus-community/parquet-common/convert/convert.go, vendor/github.com/prometheus-community/parquet-common/convert/writer.go, vendor/github.com/prometheus-community/parquet-common/schema/encoder.go, vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/search/parquet_queriable.go, vendor/github.com/prometheus-community/parquet-common/storage/bucket_read_at.go, vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go, vendor/modules.txt
Introduces several improvements to the Parquet implementation:
* Adds fallback to the blocks store queryable when vertical sharding is enabled, as this is currently unsupported in the Parquet queryable.
* Sorts blocks by timestamp in the converter to prioritize recent blocks during conversion
* Adds support for configuring maxRowGroupSize and flag to enabled/disableon-disk buffer in the converter.
* Randomizes tenant order during conversion to improve fairness.
* Pull latest parquet common 
Part of https://github.com/cortexproject/cortex/pull/6712
**Checklist**
=> Fallback to the blocks queryable if vertical sharding is enabled

CHANGELOG.md, pkg/util/active_user.go
I have noticed a race condition in `active_user.go`. (https://github.com/cortexproject/cortex/actions/runs/15336995596/job/43156054957?pr=6763)
This PR fixes it.
The logs are:
```
Read at 0x00c00411e420 by goroutine 996:
github.com/cortexproject/cortex/pkg/util.(*ActiveUsers).ActiveUsers()
/__w/cortex/cortex/pkg/util/active_user.go:98 +0x87
github.com/cortexproject/cortex/pkg/util.(*ActiveUsersCleanupService).ActiveUsers()
/__w/cortex/cortex/pkg/util/active_user.go:146 +0x139
github.com/cortexproject/cortex/pkg/distributor.(*Distributor).updateLabelSetMetrics()
/__w/cortex/cortex/pkg/distributor/distributor.go:814 +0x104
github.com/cortexproject/cortex/pkg/distributor.(*Distributor).running()
/__w/cortex/cortex/pkg/distributor/distributor.go:489 +0x4b1 …
```
=> Fix race condition in active user

pkg/querier/parquet_queryable.go, pkg/querier/querier.go
Caching the parquet shards to avoid re-opening then on every query.
Part of https://github.com/cortexproject/cortex/pull/6712
**Checklist**
=> Caching Parquet shards

CHANGELOG.md, go.mod, go.sum, pkg/ingester/ingester.go, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go, vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go, vendor/modules.txt
Update thanos to version https://github.com/thanos-io/thanos/commit/4ad45948cd1098000270dc52c8d2f5f077e02076
Enable skip corrupted blocks when using shipper for ingester.
Forwarding new metric used by thanos
```
cortex_ingester_shipper_corrupted_blocks_total
```
**Checklist**
=> Skip corrupt blocks on shipper

CHANGELOG.md, docs/blocks-storage/compactor.md, docs/configuration/config-file-reference.md, pkg/compactor/compactor.go, pkg/storage/tsdb/caching_bucket.go
There was an attempt before to support metadata cache for compactor in https://github.com/cortexproject/cortex/pull/5682.
It only supports compactor and ignores cleaner as it is intended for cleaner to be source of truth of the bucket.
This makes sense but Cleaner also does a lot of calls to object storage so it would be nice to explore if we can use metadata caching bucket for Cleaner.
This PR tries to cache certain objstore operations for cleaner:
- GET for block meta.json
- GET for tenant deletion marker
- Iter for list of tenants
**Checklist**
=> Support caching bucket for cleaner

CHANGELOG.md, pkg/ruler/compat.go
In some cases, the Distributor returns a 2xx with error. On the ruler side, this causes `failedWrites` to be incremented. This PR prevents `failedWrites` counter from being incremented in cases where the distributor returns a 2xx with an error
=> Ruler: Prevent counting 2xx responses as failed writes

pkg/api/queryapi/query_api.go, pkg/querier/parquet_queryable.go, pkg/querier/parquet_queryable_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go
This PR allows override block store to query in parquet queryable via HTTP header `X-Cortex-BlockStore-Type`. It can be set to either `tsdb` or `parquet`. If `tsdb`, it forces to query store gateway (TSDB). If `parquet`, it forces to query parquet blocks if possible + tsdb blocks if missing.
This can be useful for rollout and it can be enabled per request basis to test parquet storage. Note that this is block store switch is only available for Instant and Range query API as we have our own query handlers there. It is not available for labels API today.
**Checklist**
=> allow override parquet queryable block store via header

integration/ingester_stream_push_test.go, pkg/ingester/ingester.go
`PushStream` would cause ingester to panic with NPE when `Push` returned nil response with an erro to `PushStream`
NA
**Checklist**
=> Fixed nil pointer error from PushStream in ingester when Push return nil response with an error

integration/query_fuzz_test.go
Disable topk and bottomk aggregation in query fuzz test since they are quite flaky
**Checklist**
=> Disable topk and bottomk aggregation in query fuzz test

pkg/querier/parquet_queryable.go
Just improving logs and adding some traces spans on the parquet queryable.
**Checklist**
=> Improving logs and adding some spans on the parquet queryable

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/storage/bucket/bucket_util.go, pkg/storage/bucket/bucket_util_test.go
Two optimization being made for cleaner:
- Use non-block way to push cleaner jobs to active user channel and delete user channel. So that long run time deletion job would not block cleaning job in the next cycle.
-  Introduced concurrent way to do DeletePrefix. So it is faster to delete directory with large number of files. Tested with 1k files in one directory. Sequential deletion took 17s and Concurrent deletion took 1.3s
**Checklist**
=> Optimize cleaner run time

CHANGELOG.md, integration/parquet_querier_test.go, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go, pkg/parquetconverter/converter.go, pkg/parquetconverter/converter_test.go, pkg/parquetconverter/metrics.go, pkg/storage/parquet/util.go, pkg/storage/parquet/util_test.go, pkg/storage/tsdb/bucketindex/index.go
This PR tries to add more Parquet metrics.
Cleaner:
- Add `cortex_bucket_parquet_unconverted_blocks_count` metric for total number of TSDB blocks that should be converted to Parquet but not available yet. This can be useful to see the backlog.
Converter:
- Add `cortex_parquet_converter_convert_block_delay_minutes` histogram metric. This is to track the delay from the time when TSDB block is uploaded to the time the block is converted to Parquet format.
- Add `cortex_parquet_converter_block_convert_failures_total` metric for number of failed block conversions. This tracks all conversion failures except context cancellation error.
**Checklist**
=> Add parquet convert failure, block delay and total block to convert metrics

docs/getting-started/_index.md, docs/getting-started/docker-compose.yaml, docs/getting-started/grafana-datasource-docker.yaml
- Creates a docker compose for Grafana to point to cortex
- Set up the kind demo and verify Grafana is pointing to cortex
Fixes #6132 
**Checklist**
=> fix(grafana-datasource): Grafana Datasource pointing to wrong service

CHANGELOG.md, pkg/chunk/json_helpers.go, pkg/querier/tripperware/query.go
Stream json encoding using existing functions, reducing CPU usage ~50%.
After upgrading from v1.16 to v1.19, the frontend's CPU usage increased significantly. The primary cause appears to be related to JSON codec, the use of `encoding/json` and the read-and-parse process. This patch addresses both issues. However, despite applying the patch, CPU usage remains higher than it was prior to the upgrade. The exact reason for this is unclear, maybe it is due to Go 1.24 or something else, but profiling results still show that decoding labels continues to consume a substantial amount of processing time (profile below).
**Checklist**
=> Enhance the performance of the frontend JSON codec

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go
Add `ignore_blocks_before` config so that Store Gateway won't sync blocks that are too old. This can be useful for tiered Store Gateway deployment. Another use case is when migrating to Parquet based storage, Store Gateway can be gradually scale down so we can use this config to load less blocks.
**Checklist**
=> Allow store gateway to ignore syncing blocks older than certain time

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/querier_tenant_federation_test.go, pkg/cortex/modules.go, pkg/querier/tenantfederation/exemplar_merge_queryable_test.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/querier/tenantfederation/metadata_merge_querier_test.go, pkg/querier/tenantfederation/regex_resolver.go, pkg/querier/tenantfederation/regex_resolver_test.go, pkg/querier/tenantfederation/tenant_federation.go, pkg/tenant/resolver.go, pkg/tenant/tenant.go
This PR introduces a regex tenant resolver to allow regex in the `X-Scope-OrgID` value when the user uses `tenant-federation` feature.
It introduces two flags, `tenant-federation.regex-matcher-enabled` and `tenant-federation.user-sync-interval`.
- The `tenant-federation.regex-matcher-enabled` enables the regex resolver, which allows regex to the `X-Scope-OrgID` value.
- The `tenant-federation.user-sync-interval` specifies how frequently to scan users. The scanned users are used to calculate matched tenantIDs.
The regex matching rule follows the Prometheus regex matcher (`=~`), See [here](https://prometheus.io/docs/prometheus/latest/querying/basics/#regular-expressions).
For example, if there are 3 tenants, whose IDs are `user-1`, `user-2`, and `user-3`. We can set `X-Scope-OrgID` to …
=> Introduce a regex tenant resolver

CHANGELOG.md, docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/storage/tsdb/caching_bucket.go
When cleanUpUser takes long it might delay compaction cleaner metrics leaving the user blind to what is happening. This approach separate metrics in another go routine which will run independently if the cleanUser is impaired
**Checklist**
=> Split compactor cleaner metrics

CHANGELOG.md, docs/configuration/config-file-reference.md, pkg/util/validation/errors.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Add native histogram max sample size bytes limit validation.
This is added b/c native histogram can have infinite buckets for a given schema increasing the size of a nh sample. Size of a NH sample can also grow due to other factors like Spans. Although max_bucket_count limit reduces resolution of NH samples, but this limit is added to discard samples if the sample size is excessive and can load Distributors. 
This limit is not added as per-user override.
**Checklist**
=> Add native histogram max sample size limit validation

pkg/api/queryapi/query_api.go
The `prometheus/web/api/v1/api.go` handler was originally used for instant and range queries in Cortex. When the handlers for both query types were moved to `pkg/api/queryapi/query_api.go`, we did not include the wrapper for compression #6763.
This is an issue because it can cause query responses to hit the configured `grpc-max-send-msg-size`. It also makes the response compression configuration non-functional.
```
[response_compression: <string> | default = "gzip"]
```
**Checklist**
=> Add response compression wrapper for query api

pkg/alertmanager/multitenant_test.go, pkg/compactor/compactor_paritioning_test.go, pkg/compactor/compactor_test.go, pkg/compactor/partition_compaction_grouper_test.go, pkg/compactor/shuffle_sharding_grouper_test.go, pkg/cortex/modules.go, pkg/distributor/distributor_test.go, pkg/distributor/ingestion_rate_strategy_test.go, pkg/ingester/ingester_test.go, pkg/ingester/limiter_test.go, pkg/ingester/user_metrics_metadata_test.go, pkg/ingester/user_state_test.go, pkg/parquetconverter/converter_test.go, pkg/querier/distributor_queryable_test.go, pkg/querier/parquet_queryable_test.go, pkg/querier/querier_test.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go, pkg/querier/tripperware/roundtrip_test.go, pkg/ruler/ruler_test.go, pkg/storegateway/gateway_test.go, pkg/util/push/otlp_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
The `NewOverrides` always return `nil` err. So, this PR deletes it to remove the unnecessary error handling.
**Checklist**
=> refactor: delete a NumOverrides error

pkg/querier/tenantfederation/regex_resolver.go, pkg/querier/tenantfederation/regex_resolver_test.go, pkg/tenant/tenant.go
This PR adds tenantID validation to the `regex validator` to filter out unsupported or too-long tenantID.
**Checklist**
=> Add tenantID validation to regex validator

CHANGELOG.md, pkg/cortex/modules.go, pkg/frontend/transport/handler.go, pkg/querier/tenantfederation/exemplar_merge_queryable_test.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/querier/tenantfederation/metadata_merge_querier_test.go, pkg/querier/tenantfederation/regex_resolver.go, pkg/querier/tenantfederation/regex_resolver_test.go
This PR implements a `tenant-federation.max-tenant` flag logic when the `tenant-federation.regex-matcher-enabled ` flag is enabled.
Since the QFE uses a `regex validator`, which validates input regex and passes it to the Query scheduler or Querier, the QFE handler cannot validate the max tenant limit.
Instead of emitting an error when # of matched tenants over the `tenant-federation.max-tenant`, I adjusted # of tenants to query because # of matched tenants is unexpected if the user uses a regex like `user-+`.  
**Checklist**
=> Add a query result limit to regex matcher

MAINTAINERS.md
I would like to start a vote to add @SungJin1212 as a new maintainer for Cortex.
Sungjin has became a Triager since Nov 2024. He has more than 100 PRs in total to the project and has been the most active contributor overall since he started his contributions.
You can find his contributions here: https://github.com/cortexproject/cortex/issues?q=is%3Apr+is%3Aopen+author%3ASungJin1212
Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first.
=> [Vote] SungJin1212 as new Cortex maintainer

pkg/ingester/ingester.go
There was memory leak when using StreamPush. Each request would wrap original context and update original context with wrapped version. This would cause memory to hold all those wrapped version and never clean them up. This PR is fixing this issue.
NA
**Checklist**
=> Fixed memory leak in PushStream caused by reusing context

docs/guides/native-histograms.md
The #6718 has moved `enable_native_histograms` to the limit config. This PR applies that change to the docs.
**Checklist**
=> Fix YAML definition to NH docs

go.mod, go.sum, pkg/querier/parquet_queryable.go, vendor/github.com/prometheus-community/parquet-common/convert/convert.go, vendor/github.com/prometheus-community/parquet-common/convert/merge.go, vendor/github.com/prometheus-community/parquet-common/convert/writer.go, vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go, vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go, vendor/github.com/prometheus-community/parquet-common/storage/read_at.go, vendor/github.com/prometheus-community/parquet-common/util/fixtures.go, vendor/modules.txt
Update parquet common to latest.
Benchmark is showing very good opmizations:
**Checklist**
=> Updating parquet common to latest

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
This PR adds a `cortex_slow_queries_total` metric to track # of slow queries per user.
The cortex treats the query as slow when the query RTT is longer than the specified `LogQueriesLongerThan`.
**Checklist**
=> Add a cortex_slow_queries_total to track # of slow queries

pkg/ring/basic_lifecycler_test.go
This PR fixes a flaky test `TestBasicLifecycler_HeartbeatWhileStopping`.
The reason is that since timestamps are Unix seconds, `currTimestamp` might not accurately reflect the time.
In other words, one second is insufficient to accurately reflect the heartbeat time to `currTimestamp`.
**Checklist**
=> Fix flaky TestBasicLifecycler_HeartbeatWhileStopping

docs/proposals/limits-api.md, docs/proposals/user-overrides-api.md
This PR adds a proposal for a tenant limits API.
**Checklist**
=> Add proposal for user overrides API

pkg/cortexpb/codec.go, pkg/cortexpb/codec_test.go
Follow up of https://github.com/cortexproject/cortex/pull/6808
Lets not use the buffered byte slices if the message is not "releasable"
**Checklist**
=> Do not use buffer pool when message is not releasable

docs/configuration/arguments.md
The `inmemory` store will not work correctly with multiple distributors as each distributor can have a different state, causing injestion errors. The PR adds a warning to the docs to clarify this.
Fixes #5145 
**Checklist**
=> docs: Add warning for inmemory ha-tracker to clarify its usage

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance_limits.go, pkg/ingester/metrics.go
Introduce a new metric with reason from when ingester returns an error. Currently this will be useful for throttling customer on tooManyInflightRequests. We can expand for more error reasons as needed
**Checklist**
=> New metric for ingester errors

integration/query_response_compression_test.go
Add integration test for query response compression from query-frontend. Gzip handler `github.com/klauspost/compress/gzhttp` used in query-frontend only compresses responses larger than 1024 bytes.
**Checklist**
=> Add query-frontend response compression integration test

docs/blocks-storage/querier.md, docs/configuration/config-file-reference.md, docs/guides/parquet-mode.md, pkg/cortex/cortex.go, pkg/parquetconverter/converter.go, pkg/querier/querier.go
Exposting Parquet configs.
Fixes https://github.com/cortexproject/cortex/issues/6886 together with https://github.com/cortexproject/cortex/pull/6919
**Checklist**
=> Exposing parquet configs

CHANGELOG.md, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
This PR changes Ruler to emit an error message when the rule synchronization fails.
**Checklist**
=> Emit error when the rule synchronization fails

pkg/cortex/modules.go
This fixes a panic when using memberlist kv.
```
2025/08/02 19:06:15 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
ts=2025-08-02T19:06:15.056837612Z caller=main.go:200 level=info msg="Starting Cortex" version="(version=1.19.0, branch=master, revision=e31c57ce86)"
ts=2025-08-02T19:06:15.056964695Z caller=server.go:321 level=info http=[::[]:8080 grpc=[::]:9095 msg="server listening on addresses"
ts=2025-08-02T19:06:15.057437362Z caller=module_service.go:64 level=info msg=initialising module=server
ts=2025-08-02T19:06:15.057487445Z caller=module_service.go:64 level=info msg=initialising module=runtime-config
ts=2025-08-02T19:06:15.057490404Z caller=module_service.go:64 level=info msg=initialising module=memberlist-kv
ts=2025-08-02T19:06:15.057832112Z …
```
=> Allow parquet converter for memberlist KV

integration/querier_test.go, pkg/api/handlers.go, pkg/api/queryapi/query_api.go, pkg/api/queryapi/query_api_test.go, pkg/cortex/cortex.go, pkg/cortex/modules.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/frontend/config.go, pkg/querier/querier.go, pkg/querier/tripperware/instantquery/instant_query.go, pkg/querier/tripperware/instantquery/instant_query_middlewares_test.go, pkg/querier/tripperware/queryrange/query_range.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
This PR enables the queriers to execute a logical plan derived from the serialized logical plan in the request body, under the distributed execution feature flag. It includes a fallback to the PromQL engine when necessary.
Unit tests have been added to verify that queries are correctly executed from the logical plan in the request body when expected, as opposed to the query string in the request URL.
Fixes 
**Checklist**
=> allow queriers to execute from logical query plans

docs/blocks-storage/querier.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, go.mod, go.sum, pkg/storage/tsdb/config.go, vendor/github.com/prometheus-community/parquet-common/convert/convert.go, vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go, vendor/github.com/prometheus-community/parquet-common/schema/encoder.go, vendor/github.com/prometheus-community/parquet-common/schema/schema.go, vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go, vendor/github.com/prometheus-community/parquet-common/storage/read_at.go, vendor/modules.txt
Make `parquet_labels_cache` config not hidden. Also upgrade parquet common to latest main.
Changes pulled:
- https://github.com/prometheus-community/parquet-common/pull/92
- https://github.com/prometheus-community/parquet-common/pull/93
- https://github.com/prometheus-community/parquet-common/pull/94
**Checklist**
=> Upgrade parquet common and expose parquet labels cache config

go.mod, go.sum, pkg/querier/parquet_queryable_test.go, vendor/github.com/prometheus-community/parquet-common/search/constraint.go, vendor/github.com/prometheus-community/parquet-common/search/materialize.go, vendor/github.com/prometheus-community/parquet-common/util/bitmap.go, vendor/modules.txt
Pull new improvements on parquet common:
- https://github.com/prometheus-community/parquet-common/pull/96
- https://github.com/prometheus-community/parquet-common/pull/98
- https://github.com/prometheus-community/parquet-common/pull/97
**Checklist**
=> Update parquet common library to latest

pkg/querier/blocks_finder_bucket_index.go, pkg/querier/blocks_finder_bucket_index_test.go, pkg/querier/blocks_finder_bucket_scan.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/parquet_queryable.go, pkg/querier/parquet_queryable_test.go
This PR extends the `BlockFinder` interface's `GetBlocks` method to accept the list of query matchers. This allows downstream projects to extend the block finding strategy to allow experimenting with some different partitioning strategies.
We are testing it out with TSDB blocks partitioned by metric name. By passing the list of matchers when finding blocks, this allows us to filter out blocks that won't have the metric name at all so we query fewer blocks. We will try to upstream this soon.
There is no any user facing change in this PR other than the interface change.
**Checklist**
=> Extend block finder get blocks interface with matchers

CHANGELOG.md, docs/configuration/config-file-reference.md, docs/configuration/v1-guarantees.md, integration/e2ecortex/client.go, integration/otlp_test.go, pkg/distributor/distributor.go, pkg/util/push/otlp.go, pkg/util/push/otlp_test.go
This PR adds an experimental `-distributor.otlp.enable-type-and-unit-labels` flag to add `__type__` and `__unit__` labels for OTLP metrics.
Fixes #6952 
**Checklist**
=> Add enable type and unit labels flag

build-image/Dockerfile
Update build image to address vulnerabilities:
* https://github.com/advisories/GHSA-j5pm-7495-qmr3 - Fixed by Go 1.24.6
* https://github.com/advisories/GHSA-wprm-fgrx-xj42 - Fixed by Go 1.24.5
* https://github.com/advisories/GHSA-6f52-wpx2-hvf2 - Fixed by Go 1.24.4
* https://github.com/advisories/GHSA-jw54-c8rr-pjpq - Fixed by Go 1.24.4
* https://github.com/advisories/GHSA-62jj-gr2r-5c34 - Fixed by Go 1.24.4
---
**Checklist**
=> Chore: update build image to use Go 1.24.6

pkg/querier/blocks_store_queryable_test.go, pkg/util/limiter/resource_based_limiter.go, pkg/util/limiter/resource_based_limiter_test.go
`isRetryableError` from blocks_store_queryable checks if the error chain includes `limiter.ResourceLimitReachedError` struct:
```
func isRetryableError(err error) bool {
// retry upon resource exhaustion error from resource monitor
var resourceExhaustedErr *limiter.ResourceLimitReachedError
if errors.As(err, &resourceExhaustedErr) {
return true
}
```
https://github.com/cortexproject/cortex/blob/master/pkg/querier/blocks_store_queryable.go#L1206-L1211
However, resource based limiter was not returning that error struct, hence this check was returning false.
Since the goal of resource based throttling is to protect subset of pods with high resource utilization, we do want to retry them on other pods.
n/a
**Testing**:
Before the fix: …
=> Fix error from resource based throttling to be retryable

CHANGELOG.md, pkg/querier/tripperware/roundtrip.go, pkg/querier/tripperware/roundtrip_test.go
At #6978, `api/v1/parse_query` API has been added. This PR adds `parse_query` as a label value to the `op` label at `cortex_query_frontend_queries_total `.
**Checklist**
=> Add parse query op label to queries total metric

website/content/en/blog/2025/query-rejection.md
Improves query rejection blog post. 
- added `Ruler Queries` part.
- there was an error on example query, so fixed it. 
- Some other wording changes for overall improvement. 
**Checklist**
=> query rejection blog post improvement

pkg/api/queryapi/query_api.go, pkg/cortex/modules.go, pkg/distributed_execution/codec.go, pkg/distributed_execution/codec_test.go, pkg/distributed_execution/distributed_optimizer.go, pkg/distributed_execution/distributed_optimizer_test.go, pkg/distributed_execution/fragment_key.go, pkg/distributed_execution/remote_node.go, pkg/distributed_execution/remote_node_test.go, pkg/querier/tripperware/distributed_query.go, pkg/querier/tripperware/distributed_query_test.go, pkg/querier/tripperware/instantquery/instant_query_middlewares.go, pkg/querier/tripperware/instantquery/instant_query_middlewares_test.go, pkg/querier/tripperware/queryrange/query_range_middlewares.go, pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
Implements a distributed optimizer in the distributed execution middleware that introduces remote nodes in the logical plan to mark fragmentation points. It focuses on binary aggregation queries and includes un-marshal functionality to maintain remote node integrity in the processing pipeline
For distributed query execution feature
**Checklist**
=> add logical plan distributed optimizer to query frontend

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Currently, Native Histogram Ingestion Rate Limiter partially discard/drop the NH samples and respond with 2XX.
The PR updates the Native Histogram Ingestion Rate Limiter to respond with 429 when dropping/discarding samples.
**Checklist**
=> Bug fix: Return 429 response when Native Histogram samples are discarded by Native Histogram Ingestion Rate Limiter

go.mod, go.sum, vendor/modules.txt
**What this PR does**: Upgrades weave works-common to https://github.com/cortexproject/weaveworks-common/pull/6
well, we still need to do more to remove this dependency, but this is a step in the right direction
=> Upgrades weaveworks-common to remove aws-sdk-go dependency

docs/blocks-storage/compactor.md, docs/blocks-storage/store-gateway.md, docs/configuration/config-file-reference.md, pkg/ring/kv/client.go
**What this PR does**: Improve docs on dynamodb ring flags/configuration
Seen while working on https://github.com/cortexproject/cortex/pull/7004
**Checklist**
=> Include dynamodb as a ring store in the docs

Makefile
`make modernize` emits warning messages. This PR addresses it.
```
Makefile:312: warning: overriding commands for target `modernize'
Makefile:130: warning: ignoring old commands for target `modernize'
```
**Checklist**
=> chore: delete warning message in make modernize

go.mod, go.sum, pkg/ring/kv/memberlist/metrics.go, vendor/github.com/hashicorp/go-metrics/.gitignore, vendor/github.com/hashicorp/go-metrics/.travis.yml, vendor/github.com/hashicorp/go-metrics/LICENSE, vendor/github.com/hashicorp/go-metrics/README.md, vendor/github.com/hashicorp/go-metrics/const_js.go, vendor/github.com/hashicorp/go-metrics/const_unix.go, vendor/github.com/hashicorp/go-metrics/const_windows.go, vendor/github.com/hashicorp/go-metrics/inmem.go, vendor/github.com/hashicorp/go-metrics/inmem_endpoint.go, vendor/github.com/hashicorp/go-metrics/inmem_signal.go, vendor/github.com/hashicorp/go-metrics/metrics.go, vendor/github.com/hashicorp/go-metrics/prometheus/prometheus.go, vendor/github.com/hashicorp/go-metrics/sink.go, vendor/github.com/hashicorp/go-metrics/start.go, vendor/github.com/hashicorp/go-metrics/statsd.go, vendor/github.com/hashicorp/go-metrics/statsite.go, vendor/modules.txt
**What this PR does**: Updates armon/hashicorp metrics library
Fixes #7028
**Checklist**
=> Updates armon/hashicorp metrics library

docs/configuration/config-file-reference.md, pkg/util/validation/limits.go
Mark parquet runtime configs unhidden from configs
**Checklist**
=> Unhide parquet runtime configs

Makefile, schemas/cortex-config-schema.json, tools/doc-generator/json_schema_writer.go, tools/doc-generator/main.go
Adds a JSON schema for our cortex configuration so that we could get validation and auto completion in editors that support the yaml-language-server. This will make it easier to understand our configuration since the description of what each field is about will also appear as a popover in the ide when the field is hovered over by the cursor.
Changes to the schema are automated just like how the docs are generated, making it easy to maintain.
**Checklist**
=> Set up cortex config json schema generator

pkg/util/discardedseries/perlabelset_tracker.go, pkg/util/discardedseries/perlabelset_tracker_test.go
Fix flaky test `TestPerLabelsetDiscardedSeriesTracker`.
```
go test -count=100 -race -run TestPerLabelsetDiscardedSeriesTracker ./pkg/util/discardedseries
--- FAIL: TestPerLabelsetDiscardedSeriesTracker (0.00s)
perlabelset_tracker_test.go:117: 
Error Trace:	/__w/cortex/cortex/pkg/util/discardedseries/perlabelset_tracker_test.go:117
/__w/cortex/cortex/pkg/util/discardedseries/perlabelset_tracker_test.go:84
Error:      	Not equal: 
expected: 0
actual  : 1
Test:       	TestPerLabelsetDiscardedSeriesTracker
FAIL
```
The reason is that all users share `labelsetsToDelete`. When processing `user2`, the labelSetId for `user1` could be deleted.
**Checklist**
=> Fix flaky TestPerLabelsetDiscardedSeriesTracker
